UMAprotocol/protocol

packages/affiliates/payouts/dappmining/2021-04-05_2021-04-12_YD-ETH-JUN21_0013.json

**Motivation**
#2858
**Details**
Dapp mining for YD-ETH-JUN21 week 14 using 0.3 of dev mining rewards for this period: `Math.floor(10891.884429811309161646 * 0.3) = 3267`
```
{
"config": {
],
"empRewards": "10891.884429811309161646",
"weekNumber": 13,
"endDate": "04/12/2021 11:00 PM",
"startDate": "04/05/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 14

---

packages/affiliates/payouts/dappmining/2021-04-05_2021-04-12_YD-BTC-JUN21_0013.json

**Motivation**
#2859
**Details**
Dapp mining for YD-BTC-JUN21 week 14 using 0.3 of dev mining rewards for this period: `Math.floor(6034.224413253494686331 * 0.3) = 1810`
```
{
"config": {
],
"empRewards": "6034.224413253494686331",
"weekNumber": 13,
"endDate": "04/12/2021 11:00 PM",
"startDate": "04/05/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 14

---

packages/liquidator/src/proxyTransactionWrapper.js

**Motivation**
There is a small error in the log produced that is sent to Winston resulting in an error slack message. This PR should address this.
Faulty slack log:
The error produced is `Error:TypeError: Cannot read property 'length' of undefined`. The `undefined` in reference here is the `txnConfig`. This was not correctly set previously and is addressed in this PR.

fix(liquidator): address issue in log produced resulting in Winston slack transport error

---

packages/financial-templates-lib/src/price-feed/ExpressionPriceFeed.js
packages/financial-templates-lib/src/price-feed/utils.js

**Motivation**
Sometimes `timestamp` is passed in as a String via an upstream `getHistoricalPrice()` call, such as [here](https://github.com/UMAprotocol/protocol/blob/master/packages/core/scripts/local/getHistoricalPrice.js#L94) in the script that's designed to aid UMA voters. This bug currently causes the script to return a slightly different price than one that would be returned by the `optimistic-oracle-proposer` bot, which correctly inputs `timestamp` as a Number [here](https://github.com/UMAprotocol/protocol/blob/master/packages/optimistic-oracle/src/proposer.js#L265).
There might be other instances in the repo where a String `timestamp` is unexpectedly passed into this Blockfinder utility method expecting a number.
**Testing**
Check a box to describe how you tested these changes and …

fix(blockfinder): Explicitly cast timestamp to Number

---

packages/funding-rate-proposer/src/proposer.js
packages/funding-rate-proposer/test/proposer.js

**Motivation**
Funding Rate Proposer bot uses the latest block timestamp as the request timestamp. Any disputes will reference this same timestamp, therefore the proposed price should be the historical price for this timestamp. Currently, the current price is used, but the current price can be off from the historical price at the request timestamp because of the lag between the last block time and the current (off-chain) system time.
The latest block timestamp is used as the request time instead of the current system time because the Optimistic Oracle prevents request timestamps from being >= the latest block time. See [this PR](https://github.com/UMAprotocol/protocol/pull/2687) for more details.
**Testing**
Check a box to describe how you tested these changes and list the steps for …

fix(funding-rate-proposer): Use historical-price to propose funding rates

---

packages/affiliates/payouts/dappmining/2021-04-12_2021-04-19_YD-BTC-JUN21_0014.json

**Motivation**
#2887
**Details**
Dapp mining for YD-BTC-JUN21 week 15 from 2021/04/12 to 2021/04/19 using 0.3 of dev mining rewards for this period: `Math.floor(6199.595527018841149926 * 0.3) = 1859`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "6199.595527018841149926",
"weekNumber": 14,
"endDate": "04/19/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 15

---

packages/financial-templates-lib/src/price-feed/FallBackPriceFeed.js

The Expression price feed does not fully implement the `PriceFeedInterface` resulting in errors in production. An example error is shown below:
This PR addresses this issue.

fix(FallBackPriceFeed): implement missing method that broke in production

---

packages/liquidator/src/liquidator.js
packages/liquidator/src/proxyTransactionWrapper.js
packages/liquidator/test/Liquidator.js

**Motivation**
Previously, if the liquidator's reserve currency was equal to the collateral currency an error was thrown that looked like this:
This occurred within the `getEffectiveSyntheticTokenBalance` method in the `proxyTransactionWrapper` when trying to compute how much collateral could be purchased using the reserve currency.
This error occurred as there is no uniswap exchange between two tokens of the same type.
**Summary**
**Details**
To address this, this PR adds a small bit of branching logic to skip the trading computation in the case of a collateral and reserve match. Tests were also added to verify this behavior, including the case when all collateral is spent.
**Testing**
Check a box to describe …

fix(liquidator): update DSProxy to deal with reserve currency matching collateral currency

---

.yarnrc

**Motivation**
Docker hub has been failing with some builds due to timeouts. See screenshot below:
This PR adds a 5 min timeout delay to the yarn process which should hopefully help with this issue. It's not a guaranteed fix though. Curious to hear from @UMAprotocol/eng if you see any better solutions.

fix(lerna): add yarn network timeout to help slow build processes

---

packages/serverless-orchestration/src/ServerlessSpoke.js

**Motivation**
Hanging or timeout processes are very difficult to debug if you can't track progress within the child process.
**Summary**
Adds a simple few lines that will tell the child process to stream its output to the parent's output streams. No changes to existing logs.
**Testing**
**Issue(s)**
N/A

feat(serverless): make spoke stream stdout and stderr to parent

---

packages/financial-templates-lib/package.json
packages/funding-rate-proposer/index.js
yarn.lock

**Motivation**
`@google-cloud/logging-winston` version 4.0.0 was a breaking change that updated the `google-cloud/logging` dependency to [v8](https://github.com/googleapis/nodejs-logging-winston/pull/513).
I'm unable to run Serverless Hub locally that sends requests to the Spoke on GCP, and this patches that. I suspect this might solve the `writeAfterEnd` error we're seeing with GCP logs on the `funding-rate-mainnet-proposer` bot.
**Testing**

Fix: Update google cloud/logging winston

---

packages/affiliates/payouts/dappmining/2021-04-19_2021-04-26_YD-BTC-JUN21_0015.json

**Motivation**
#2909
**Details**
Dapp mining for YD-BTC-JUN21 week 16 from 2021/04/19 to 2021/04/26 using 0.3 of dev mining rewards for this period: `Math.floor(5250.512260643829691485 * 0.3) = 1575`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "5250.512260643829691485",
"weekNumber": 15,
"endDate": "04/26/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 16

---

packages/common/browser.js
packages/common/index.js
packages/common/src/ProviderUtils.js
packages/common/src/RetryProvider.js

**Motivation**
To help the bots be more resilient in the face of flaky node behavior, it would be nice for providers to be able to do per-request retries.
**Summary**
Adds a retry provider that can be used to retry failing requests and fallback to secondary node providers for individual failing requests.
**Testing**
**Issue(s)**
N/A

feat(common): add retry provider

---

packages/core/contracts/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.sol
packages/core/test/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.js
packages/liquidator/src/proxyTransactionWrapper.js
packages/liquidator/test/Liquidator.js

**Motivation**
After testing out some more edge cases with the `ReserveCurrencyLiquidator` I realized there is a scenario that the contracts were not designed to handle and were not tested against. In particular what happens when the `ReserveCurrencyLiquidator` is told to liquidate a position that is larger than the sum of all reserve and collateral currency the DSProxy has access to? 
In the previous implementation, the transaction would revert. After this PR the DSProxy will liquidate as much as it can, using all reserves in the process.
**Summary**
Added extra logic and unit tests to the `ReserveCurrencyLiquidator` to accommodate a token shortfall.
**Details**
In addition to the make changes done in this PR I also refactored `ReserveCurrencyLiquidator` a small amount by pulling out …

fix(ReserveCurrencyLiquidator): improve how the contract handles reserve OR collateral currency shortfall

---

packages/common/src/PriceIdentifierUtils.js
packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
Default price feed configs for XSUSHIUSD, BALUSD and uSTONKS_JUN21 are needed. 
**Summary**
These price feeds follow the methodologies determined in:
- [UMIP-68](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-68.md) for XSUSHIUSD
- [UMIP-73](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-73.md) for BALUSD
- [UMIP-79](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-79.md) for uSTONKS_JUN21
**Testing**
Ran monitor bots locally.
**Issue(s)**
NA

feat(financial-templates-lib): Add default price feed configs for XSUSHIUSD, BALUSD and uSTONKS_JUN21

---

packages/affiliates/payouts/dappmining/2021-04-26_2021-05-03_YD-ETH-JUN21_0016.json

**Motivation**
#2932
**Details**
Dapp mining for YD-ETH-JUN21 week 17 from 2021/04/26 to 2021/05/03 using 0.3 of dev mining rewards for this period: `Math.floor(17063.961746333554030422 * 0.3) = 5119`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "17063.961746333554030422",
"weekNumber": 16,
"endDate": "05/03/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 17

---

packages/affiliates/payouts/dappmining/2021-04-26_2021-05-03_YD-BTC-JUN21_0016.json

**Motivation**
#2933
**Details**
Dapp mining for YD-BTC-JUN21 week 17 from 2021/04/26 to 2021/05/03 using 0.3 of dev mining rewards for this period: `Math.floor(4926.277501606561144476 * 0.3) = 1477`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "4926.277501606561144476",
"weekNumber": 16,
"endDate": "05/03/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 17

---

ci/generate_lerna_config.sh
packages/financial-templates-lib/src/clients/FinancialContractEventClient.js

**Motivation**
On the newest tests, we received output Exit code `137` - Out of memory. This MR upgrade the memory size to avoid it.
**Testing**

fix (CircleCI): Upgrade executor size

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js

**Motivation**
When a `twapLength` is defined for a cryptowatch price feed, `invertPrice` is not used. This PR allows for inverting cryptowatch prices while also using a twap.
To reproduce, define a non-zero `twapLength` config parameter for any cryptowatch default price feed config that also has an `invertPrice` value of true.
**Summary**
Inverts the twap returned from `_computeTwap()` when `invertPrice` is true.
**Testing**
Tested locally by running a monitor bot, but did not add anything to the unit tests. Happy to do so if it is necessary.
**Issue(s)**
NA

fix(price-feeds): allow for cryptowatch price inversion when twapLength is defined

---

Dockerfile

**Motivation**
https://github.com/UMAprotocol/protocol/commit/3ba662f99bb9d1c33b207457ce9fa6cb90336d98 broke the docker build.
**Summary**
Installs required package to fix the docker build. Also makes a small improvement to use yarn directly instead of npx lerna bootstrap, which should save a little time.
**Testing**
**Issue(s)**
N/A

fix(docker): fix broken docker build

---

packages/affiliates/.gitignore
packages/affiliates/libs/uniswap/models.ts
packages/affiliates/libs/uniswap/processor.ts
packages/affiliates/libs/uniswap/utils.ts
packages/affiliates/package.json
packages/affiliates/scripts/univ3.js
packages/affiliates/scripts/univ3.ts
packages/affiliates/tsconfig.json

**Motivation**
https://app.clubhouse.io/uma-project/story/563/interface-with-uniswap-v3-to-get-lp-positions
**Summary**
This mainly shows how we can relevenat uniswap v3 liquidity mining state. pools, positions and ticks through events and contract queries.  This will be useful for determining reward values for liquidity mining.  This is very much a work in progress, but its a good checkpoint before the code gets too large. 
**Details**
You will notice this uses ethers, this is mainly becuase I was building typechain files from uniswap and it built to ethers, so all types were based on this. This could probably be switched to web3 with a bit of work.
Most of the logic is split between 3 files:
- `scripts/univ3` - this shows how to fetch events and state from contracts and put them into …

feat(affiliates): uniswap v3 fetch state proof of concept

---

ci/check_lerna_packages.sh

**Motivation**
The current test process depends on compare edit packages from last master commit. On master branch that was a problem comparing the latest commit with himself. This PR fix that logic to test the past commit.
**Testing**

fix (CircleCI): Restore packages tests on master

---

packages/financial-templates-lib/src/helpers/GasEstimator.js

**Motivation**
Right now the gas estimator returns the `SafeGasPrice` or `fast` gas price, depending on the API called. Ideally, we should always use the _fastest_ price returned. 
An example of where this matters is when proposing UMIPs. The script will use the recommended price and the gas price will move up a few GWEI and before you know it you are stuck with a pending transaction. At all times we should use the `fastest` recommendation to ensure transactions are mined as soon as posible. This should result in a general improvement in quality of life for proposers as well as indirectly improve the bots performance (and reduce how often we need to bump gas).
**Summary**
Update the default.
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers …

feat(GasEstimator): update the default to use fast gas price

---

packages/merkle-distributor/kpi-options-helpers/calculate-uma-tvl.ts

**Motivation**
There have been scenarios where the TVL returned by the serverless script is orders of magnitude off. This PR adds a reasonable bound (less than 100 billion and more than 10 million) to the UMA tvl.
**Summary**
Errors in providers or APIs can manifest in erroneous TVL. 
**Testing**

fix(tvl-calculator): filter out unrealistic numbers

---

.circleci/config.yml

**Motivation**
The old method used for tests, needed a specific context to execute. In the current improvement, we can avoid this step and allow execute the tests on each PR.
**Testing**

fix (CircleCI): Remove context from tests

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
This data source is getting deprecated on June 30th and moreover I don't know for certain whether its using a similar process for computing the XAUUSD price as the tradermade pricefeed. For now, we should remove this pricefeed and longer term figure out a better back up for tradermade.
**Testing**

improve(price-feed): Remove quandl feed from backup pricefeed

---

packages/common/src/HardhatConfig.js
packages/common/src/PublicNetworks.js
packages/common/src/TruffleConfig.js

**Motivation**
Now that [infura](https://consensys.net/blog/press-release/infura-and-truffle-now-support-polygon/) supports Polygon, it makes adding the mainnet and testnet into our truffle config very easy.
**Summary**
Can now run truffle and hardhat commands like so:
- `yarn truffle migrate --network polygon-matic/mumbai`
- `yarn hardhat deploy --network matic/mumbai`
**Details**
**Testing**

feat: Add polygon networks to truffle and hardhat configs

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
The [PUNKETH_TWAP](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-84.md) and [USDXIO](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-71.md) price identifiers need price feed configs. USDXIO is in this PR because pr #2940 has some minor CI issues. This closes 2940.
**Testing**
**Issue(s)**
NA

feat(price-feed): Add default pf configs for PUNKETH_TWAP and USDXIO

---

packages/affiliates/payouts/dappmining/2021-05-03_2021-05-10_YD-ETH-JUN21_0017.json

**Motivation**
#2964
**Details**
Dapp mining for YD-ETH-JUN21 week 18 from 2021/05/03 to 2021/05/10 using 0.3 of dev mining rewards for this period: `Math.floor(19889.437199636786683807 * 0.3) = 5966`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "19889.437199636786683807",
"weekNumber": 17,
"endDate": "05/10/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 18

---

packages/affiliates/payouts/dappmining/2021-05-03_2021-05-10_YD-BTC-JUN21_0017.json

**Motivation**
#2965
**Details**
Dapp mining for YD-BTC-JUN21 week 18 from 2021/05/03 to 2021/05/10 using 0.3 of dev mining rewards for this period: `Math.floor(4713.840652689190631001 * 0.3) = 1414`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "4713.840652689190631001",
"weekNumber": 17,
"endDate": "05/10/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 18

---

packages/financial-templates-lib/package.json
packages/financial-templates-lib/test/proxy-transaction-handler/DSProxyManager.js

**Motivation**
The DSProxy test was in financial-templates-lib was not being run because it wasn't included in the test command. Because it wasn't being run, it had some unnoticed issues in some of the log messages it expected.
**Summary**
Corrected the test command and fixed the test.
**Testing**
**Issue(s)**
N/A

fix(financial-templates-lib): fix issues in test that was not being run by ci

---

packages/affiliates/package.json

**Motivation**
If packages are set to `"private": true` then they are not picked up in our new Lerna CI configuration. This PR modifies this to ensure that affiliates is no longer private so that the test will run in CI.
**Summary**
Fixed affiliates CI.
**Testing**

fix(affiliates-ci): removed private from package.json

---

.prettierignore
packages/core/README.md
packages/core/browser.ts
packages/core/index.ts
packages/core/package.json
packages/core/tsconfig.json

**Motivation**
The current typescript exports are broken for frontend imports because you can't do imports like `@uma/core/x/y/z`.
**Summary**
This change improves the types exported from the index file so they can be imported that way and includes the ethers factories.
**Testing**
**Issue(s)**
N/A

fix(core): fix typescript exports

---

package.json
packages/common/package.json
packages/financial-templates-lib/package.json
packages/serverless-orchestration/package.json
yarn.lock

**Motivation**
Previously, the protocol repo was using web3 1.3.4. this generates irritating logs every time any script is run:
```
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
```
These are produced in the bots as well, which is pretty useless.
To resolve this, we simply need to bump the web3 version to 1.3.5. as described [here](https://github.com/ChainSafe/web3.js/issues/3898).
**Summary**
Bumps web3 version to fix warning message.
**Testing**

fix(package.json): bump web3 to 1.3.5

---

packages/affiliates/payouts/dappmining/2021-05-10_2021-05-17_YD-ETH-JUN21_0018.json

**Motivation**
#2991
**Details**
Dapp mining for YD-ETH-JUN21 week 19 from 2021/05/10 to 2021/05/17 using 0.3 of dev mining rewards for this period: `Math.floor(21154.941496412668613825 * 0.3) = 6346`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "21154.941496412668613825",
"weekNumber": 18,
"endDate": "05/17/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 19

---

packages/affiliates/payouts/dappmining/2021-05-10_2021-05-17_YD-BTC-JUN21_0018.json

**Motivation**
#2992
**Details**
Dapp mining for YD-BTC-JUN21 week 19 from 2021/05/10 to 2021/05/17 using 0.3 of dev mining rewards for this period: `Math.floor(4646.946594266890166579 * 0.3) = 1394`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "4646.946594266890166579",
"weekNumber": 18,
"endDate": "05/17/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 19

---

packages/common/package.json

**Motivation**
Common breaks when being rebuilt.
**Summary**
Common erroneously detects the dist folder as being build inputs and throws and error when trying to overwrite (not sure why), so this adds a step to delete the folder before rebuilding.
**Testing**
**Issue(s)**
N/A

fix(common): fix build issue

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js
packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js

**Motivation**
Cryptowatch price feed should throw an error if it doesn't have an OHLC data point for a requested historical price rather than trying to fill the gap.
**Summary**
Slightly modified how the feed searches through the data to find a price.
**Testing**
**Issue(s)**
N/A

fix(financial-templates-lib): make CW price feed error on missing data

---

packages/monitors/src/SyntheticPegMonitor.js
packages/monitors/test/SyntheticPegMonitor.js

**Motivation**
The recent change in the cryptowatch price feed means that requesting historical prices that are _very_ recent no longer works. This causes the vol monitor to throw warnings.
**Summary**
This makes the vol monitor use the current price rather than a recent historical price.
**Testing**
**Issue(s)**
N/A

fix(monitors): update vol monitor to work with recent changes in the CW price feed

---

packages/core/scripts/local/getHistoricalPrice.js
packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js

**Motivation**
Recent cryptowatch changes can sometimes cause historical price lookups to fail. We should provide useful information to allow the user to make informed decisions about what price to use.
**Summary**
Added error logs in the CW price feed to output the closest prices when an exact OHLC isn't available. Also added minor usability improvements to the CW price feed and getHistoricalPrice script.
Sample output:
```
$ yarn truffle exec scripts/local/getHistoricalPrice.js --time 1621430236 --identifier USDOCEAN --network test
yarn run v1.22.5
$ /Users/matt/git/protocol/node_modules/.bin/truffle exec scripts/local/getHistoricalPrice.js --time 1621430236 --identifier USDOCEAN --network test
> Warning: possible unsupported (undocumented in help) command line option: …
```

improve(core): make getHistoricalPrice give better results when price lookups fail

---

packages/core/scripts/local/getHistoricalPrice.js
packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
`node.js`'s `Number` type loses precision after a certain amount of decimals, thus the truncation logic in this script that first casts to `Number` and then calls `.toFixed()` can lose precision. This fix performs string manipulation instead.
Also changes `bittrex:oceanusdt` to `kraken:oceanusd` in `DefaultPriceFeedConfig`.
**Testing**

fix(get-historical-price-script): Do not cast to `Number` before truncating decimals

---

.circleci/config.yml

**Motivation**
Release job is failing because rsync isn't installed.
**Summary**
Install rsync in that job.
**Testing**
**Issue(s)**
N/A

fix(release): install rsync in ci release job

---

README.md

**Motivation**
After removing the docs site, we broke the logo in the readme. This PR fixes this.
Before:
After:

fix(readme.md): add back broken logo

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
Adds [DEXTFUSD](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-91.md#technical-specifications-5) and [USDDEXTF](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-91.md#technical-specifications-5) default price feed configs. 
This closes #2986, which was having issues with commit history/dco. 
**Testing**
**Issue(s)**
Closes #2986

feat(default-pf-config): Add DEXTFUSD and USDDEXTF price feed configs

---

packages/affiliates/payouts/dappmining/2021-05-17_2021-05-24_YD-BTC-JUN21_0019.json

**Motivation**
#3020
**Details**
Dapp mining for YD-BTC-JUN21 week 20 from 2021/05/17 to 2021/05/24 using 0.3 of dev mining rewards for this period: `Math.floor(4077.856849607247169508 * 0.3) = 1223`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "4077.856849607247169508",
"weekNumber": 19,
"endDate": "05/24/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 20

---

packages/core/contracts/chainbridge/BeaconOracle.sol
packages/core/contracts/chainbridge/BeaconOracleMock.sol
packages/core/contracts/chainbridge/SinkOracle.sol
packages/core/contracts/chainbridge/SourceOracle.sol
packages/core/test/chainbridge/beaconOracle.js
packages/core/test/chainbridge/e2e.js
packages/core/test/chainbridge/sinkOracle.js
packages/core/test/chainbridge/sourceOracle.js

**Motivation**
Currently, anyone can call `Bridge.deposit` directly to induce duplicate `Deposit` events. This is problematic because an offchain Relayer monitoring the `Bridge` is expected to submit transactions to bridge messages across EVM networks.
**Summary**
This PR adds two pending states to the BeaconOracle `PriceRequest` struct. The idea is that an initial call to `SinkOracle.requestPrice` or `SourceOracle.publishPrice` should mark the state as `pendingRequest` and `pendingResolve` respectively. These calls will call `Bridge.deposit` which is expected to subsequently call back to `SinkOracle.validateDeposit` and `SourceOracle.validateDeposit`. These `validateDeposits` should then mark the states as `Requested` and `Resolved`, or revert if the state is not a pending one.
This fix …

improve(beacon-oracles): validateDeposit should revert after first execution

---

packages/financial-templates-lib/src/logger/Logger.js

**Motivation**
Sometimes the logger transport provides very useless errors, like this:
These are hard to debug.
The source of the problem is the `Logger` where we try and extract the `stack` from `Error` message. This PR modifies this to try and pull other parts of the log message to not return `null`.
**Summary**
I discovered this by looking in the spoke logs and saw this:
In the case of this error, there is no `stack`. this is why the error showed up as `null`. Rather, we should first try extract the `stack` and if this does not exist then go for the `message`. Further, we can try calling the `.toString()` method that every `Error` object has. Finally, if this does not exist produce an error string to inform that something went wrong.
**Testing**
Check a box to describe how you tested …

fix(Logger): address flaky error reporting

---

packages/common/src/TruffleConfig.js

**Motivation**
Every time I try use the truffle console with a GCKMS provider I get a timeout that looks like this:
If I increase the timeout this error goes away. I suspect it's due to me being down at the tip of Africa and GCKMS providers require a fair amount of back and forth with GCP.
**Summary**
Updates the default truffle config to include a longer timeout.
**Testing**
**Issue(s)**
Fixes #XXXX

fix(TruffleConfig): Increase networkCheckTimeout for slower connections

---

ci/generate_lerna_config.sh

**Motivation**
The current tests method are not using variables for execute the jobs. This change allow the tests execution on pipeline for external users.
**Testing**

fix (CircleCI): Remove context from required jobs

---

packages/core/contracts/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.sol
packages/core/test/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.js
packages/liquidator/src/proxyTransactionWrapper.js
packages/liquidator/test/Liquidator.js

**Motivation**
In the most recent market downturn, it became apparent that the single reserve currency liquidator might trade poorly, resulting in high slippage, when pools are shallow. This PR adds logic to bound slippage within the single reserve currency liquidator.
**Summary**
Added in a `maxSlippage` that bounds the maximum trade slippage the bot will execute under.
**Details**
Please see detailed comments in the PR & smart contracts explaining the numerical technique used to bound slippage.
**Testing**

feat(liquidator): add maxSlippage parameter to single reserve currency liquidator

---

packages/core/contracts/chainbridge/BeaconOracle.sol
packages/core/contracts/chainbridge/SinkOracle.sol
packages/core/contracts/chainbridge/SourceOracle.sol
packages/core/test/chainbridge/beaconOracle.js
packages/core/test/chainbridge/e2e.js
packages/core/test/chainbridge/sinkOracle.js
packages/core/test/chainbridge/sourceOracle.js

**Motivation**
Audit response to Pull Requests #2903 and #3013
These PRs use Chainbridge to send messages between different EVM-compatible chains. In particular, DVM price requests are passed from another chain to the Ethereum mainnet, where the standard resolution mechanism can occur. Once resolved, the price is pushed back to the "sink" chain where it can be utilized. This allows UMA financial contracts to be deployed in multiple different chains but still use the Ethereum mainnet DVM to resolve prices as required.
**Summary**
Contract changes:
- On both chains, the [`PriceRequestAdded` event](https://github.com/UMAprotocol/protocol/blob/2814e8021294adb2578649ed57fb066e86bb5b73/packages/core/contracts/chainbridge/BeaconOracle.sol#L81) includes the `msg.sender` as the `requester`. …

improve(beacon-oracle): Audit Response for L2 infrastructure contracts

---

packages/core/contracts/common/implementation/dsproxy/DSGuardFactory.sol
packages/core/contracts/common/implementation/dsproxy/DSProxyFactory.sol
packages/core/networks/1.json

**Motivation**
To enable the DSPRoxy we use in liquidation to be accessible by multiple EOAs, we require a DSGuard & DSAuthority to set up permissions on who can and cant call methods on the DSProxy over and above the normal "owner" setup. This PR adds the associated smart contracts to facilitate this.

feat(DSProxy): add DSGuard contracts to enable multi-dsproxy ownership

---

packages/bot-strategy-runner/src/index.ts

**Motivation**
When running in cloud run bot settings sometimes need to be set to `0`. For example `pollingDelay` must be set to `0` to run in serverless mode. The way the code was set up before makes this config impossible due to how defaults are set. This PR addresses this.

fix(bot-stratergy-runner): fix broken default setting

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
The `lookback` was set incorrectly for the `SPOT_BALANCER_ETH` component of the `BALUSD` default price feed config.
Although this has no impact on the calculated price, this can cause issues for bot operators and voters being able to query for the BALUSD price.
**Summary**
Changes BALUSD `lookback` specification to `7200`.
**Testing**
**Issue(s)**
NA

fix(default-pf-config): Fix lookback period for BALUSD price id

---

packages/affiliates/payouts/dappmining/2021-05-24_2021-05-31_YD-BTC-JUN21_0020.json

**Motivation**
#3049
**Details**
Dapp mining for YD-BTC-JUN21 week 21 from 2021/05/24 to 2021/05/31 using 0.3 of dev mining rewards for this period: `Math.floor(1771.999459009231614049 * 0.3) = 531`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1771.999459009231614049",
"weekNumber": 20,
"endDate": "05/31/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 21

---

packages/bot-strategy-runner/src/BotEntryWrapper.ts
packages/common/src/TransactionUtils.js
packages/disputer/index.js
packages/financial-templates-lib/src/logger/PagerDutyTransport.js
packages/financial-templates-lib/src/logger/SlackTransport.js
packages/financial-templates-lib/src/logger/Transports.js
packages/liquidator/index.js
packages/monitors/index.js
packages/monitors/src/BalanceMonitor.js
packages/monitors/src/CRMonitor.js
packages/monitors/src/ContractMonitor.js
packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/src/SyntheticPegMonitor.js
packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
This PR adds the ability for Winston logs to be directed to different "paths" enabling more granular control over where messages are sent.
**Summary**
- Add two main paths: `notificationPath: "risk-management"` & `notificationPath: "infrastructure-error"`
- Refactor how configs are fed into these transports. NOTE this is a breaking change and updates to configs must be rolled out at the same time!
**Testing**
**Issue(s)**
Fixes #XXXX

feat(Winston-logger): add multiple escalation paths depending on message context

---

packages/core/scripts/local/getHistoricalPrice.js

**Motivation**
Based upon multiple community discussions, the rounding specification for the USDETH price identifier was determined to not use enough decimals. This updates the rounding specification in the getHistoricalPrice script to be 8 decimals. This is accompanied by an update to the [UMIP](https://github.com/UMAprotocol/UMIPs/pull/311).
**Summary**
Updates script.
**Testing**
**Issue(s)**
NA

feat(voting-script): Update USDETH rounding specification to 8 decimals

---

packages/core/test/bot-helpers/atomic-disputer/ReserveCurrencyDisputer.js
packages/core/test/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.js
packages/core/test/bot-helpers/uniswap-broker/UniswapV2Broker.js
packages/disputer/test/Disputer.js
packages/disputer/test/index.js
packages/liquidator/src/proxyTransactionWrapper.js
packages/liquidator/test/Liquidator.js
packages/liquidator/test/index.js
packages/trader/test/UniswapV2Trader.ts

**Motivation**
There are a number of common places through the monorepo where the method `createContractObjectFromJson` are repeated over and over. This PR removes this.

clean(bot-tests): remove repeated function from repo

---

packages/common/src/ContractUtils.js
packages/common/src/UniswapV3Helpers.js
packages/core/test/bot-helpers/atomic-disputer/ReserveCurrencyDisputer.js
packages/core/test/bot-helpers/atomic-liquidator/ReserveCurrencyLiquidator.js
packages/core/test/bot-helpers/uniswap-broker/UniswapV2Broker.js
packages/core/test/bot-helpers/uniswap-broker/UniswapV3Broker.js
packages/disputer/test/Disputer.js
packages/disputer/test/index.js
packages/liquidator/src/proxyTransactionWrapper.js
packages/liquidator/test/Liquidator.js
packages/liquidator/test/index.js
packages/trader/test/UniswapV2Trader.ts
packages/trader/test/UniswapV3Trader.ts

**Motivation**
`createContractObjectFromJson` requires a web3 instance to extract the current provider. This works fine when running in unit tests as the `web3` instance is global. however, when run in production, the `web3` instance is _not_ globle. This causes errors when running in production.
When running within the `proxytransaction` wrapper, for example, we would need to pass in the `web3` object.
This PR simply addresses this.

fix(common-ContractUtils): Add web3 param injection to createContractObjectFromJson

---

packages/sdk/package.json

**Motivation**
Publish command in ci is failing.
**Summary**
sdk package is missing the package.json directive that tells it to use a public rather than private package (scoped packages default to private).
**Testing**
**Issue(s)**
N/A

fix(sdk): fix sdk publish

---

packages/affiliates/payouts/dappmining/2021-05-31_2021-06-07_YD-ETH-JUN21_0021.json

**Motivation**
#3071
**Details**
Dapp mining for YD-ETH-JUN21 week 22 from 2021/05/31 to 2021/06/07 using 0.3 of dev mining rewards for this period: `Math.floor(11225.669859025500779243 * 0.3) = 3367`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "11225.669859025500779243",
"weekNumber": 21,
"endDate": "06/07/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 22

---

packages/affiliates/payouts/dappmining/2021-05-31_2021-06-07_YD-BTC-JUN21_0021.json

**Motivation**
#3072
**Details**
Dapp mining for YD-BTC-JUN21 week 22 from 2021/05/31 to 2021/06/07 using 0.3 of dev mining rewards for this period: `Math.floor(1585.125877249389143764 * 0.3) = 475`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1585.125877249389143764",
"weekNumber": 21,
"endDate": "06/07/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 22

---

packages/core/contracts/financial-templates/common/financial-product-libraries/contract-for-difference-libraries/RangeBondContractForDifferenceFinancialProductLibrary.sol
packages/core/contracts/financial-templates/test/ContractForDifferenceMock.sol
packages/core/test/financial-templates/common/financial-product-libraries/contract-for-difference-libraries/RangeBondContractForDifferenceFinancialProductLibrary.js

**Motivation**
Add range bonds Contract for difference financial product library and unit tests.
A range bond is defined as = Yield Dollar - Put Option + Call option.
Numerically this is found using:        
- `N` = Notional of bond
- `P` = price of token
- `T` = number of tokens
- `R1` = Low Price Range
- `R2` = High Price Range
- long token redemption: `T = min(N/P,N/R1) + max((N/R2*(P-R2))/P,0)`
As the financial product library returns a number between 0 and 1 for CFD payouts, we can take the long token redemption value `T` and divide it by the CFDs `collateralPerPair` to find a number between 0 and 1 that represents the long/short payout `expiryPercentLong`.

feat(CFD): Add range bond financial template library

---

packages/common/src/HardhatConfig.js
packages/common/src/hardhat/tasks/identifiers.js
packages/core/contracts/oracle/implementation/OptimisticOracle.sol
packages/core/contracts/polygon/OracleChildTunnel.sol
packages/core/deploy/012_deploy_optimistic_oracle.js
packages/core/networks/5.json
packages/core/networks/80001.json
packages/optimistic-oracle/index.js

**Motivation**
- Updated `OptimisticOracle`, `OracleChildTunnel`, and `OracleRootTunnel` deployments to reflect latest ancillary data logic.
- fixed typo in comment in `OptimisticOracle.sol`
- added `stampAncillaryData` read only method to `OracleChildTunnel.sol` for convenience
- fixed optimistic oracle deployment script
- updated `packages/optimistic-oracle/index.js` run script comments with instructions on how to run bot on sidechain where `OracleChildTunnel` is deployed as the Oracle
- 
**Details**
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to …

improve: Nit changes made after integration testing OptimisticOracle + Oracle Tunnel system on Mumbai <> Goerli

---

packages/common/browser.js
packages/common/src/Constants.js
packages/common/src/hardhat/fixtures/default.js
packages/common/src/hardhat/fixtures/index.js

**Motivation**
To run tests completely with hardhat, we need a default fixture that is used alongside deployments to do additional setup.
**Summary**
This adds a fixtures directory and a default fixture to common/hardhat. The fixture essentially mirrors the additional logic in truffle migrations beyond the core deployments.
**Testing**
**Issue(s)**
N/A

feat(hardhat): add default hardhat test fixture

---

packages/affiliates/payouts/dappmining/2021-06-07_2021-06-14_YD-BTC-JUN21_0022.json

**Motivation**
#3104
**Details**
Dapp mining for YD-BTC-JUN21 week 23 from 2021/06/07 to 2021/06/14 using 0.3 of dev mining rewards for this period: `Math.floor(1559.526628265841820598 * 0.3) = 467`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1559.526628265841820598",
"weekNumber": 22,
"endDate": "06/14/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 23

---

packages/disputer/index.js

**Motivation**
The disputers startup logs are missing a field `proxyTransactionWrapperConfig`. This makes some debugging difficult.

fix(disputer-index): add a missing log field

---

packages/serverless-orchestration/src/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessHub.js

**Motivation**
The most recent changes to the serverless hub made the logs **very** noisy. This PR reduces the noise by moving where logs are produced and opting for a more aggregate logging approach.
Before this PR: 
After this PR the logs are far more redacted:

fix(serverlesshub): reduce logging noise

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js

**Motivation**
There is a bug in the CryptowatchPriceFeed `getCurrentPrice` method, where an incorrectly inverted value is returned if `twapLength` and `invertPrice` is defined.
This is because the price is being inverted twice. Once in `_computeTwap()` and once in `getCurrentPrice()`.
**Summary**
Changes `getCurrentPrice()` to only invert if twapLength is not defined.
**Testing**
**Issue(s)**
NA

fix(cw-pricefeed): Fix getCurrentPrice when twapLength and invertPrice is defined

---

packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/BinaryOptionLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/CoveredCallLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LinearLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
packages/core/contracts/financial-templates/test/LongShortPairFinancialProjectLibraryTest.sol
packages/core/contracts/financial-templates/test/LongShortPairMock.sol
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/BinaryOptionLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/CoveredCallLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LinearLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/long-short-pair/LongShortPair.js
packages/core/test/financial-templates/long-short-pair/LongShortPairCreator.js

**Motivation**
The UMA team has chosen to re-name the "contract for difference" (CFD) to "long short pair" (LSP). This PR updates the contracts and tests through the `core` package to this effect.

feat(LSP): rename all instances and variants of "contract for difference" to "long short pair"

---

packages/common/src/HardhatConfig.js

**Motivation**
The [hardhat docs](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html) say you need to require the plugin in the config. We don't currently do this in our config.
Right now: `hardhat etherscan-verify` seems to work. However, this command seems to be slightly different from `hardhat verify`, which doesn't work unless the plugin is added to the config.
Not sure why this is this is the case or what the deep differences are, but we should do as recommended and put it in the config.
**Summary**
Added the require to the config.
**Testing**
**Issue(s)**
N/A

fix(common): explicitly require the hardhat etherscan verification plugin

---

packages/common/src/PriceIdentifierUtils.js

**Motivation**
There is no price feed for the `SPACEXLAUNCH` price identifier, so the Optimistic Oracle proposer should ignore requests for it.
**Summary**
Adds `SPACEXLAUNCH` to the `OPTIMISTIC_ORACLE_IGNORE_POST_EXPIRY` list.
**Testing**
**Issue(s)**
NA

feat(price-identifier-utils): Ignore SPACEXLAUNCH price id OO requests

---

packages/optimistic-oracle/index.js

**Motivation**
The OO is missing a notification path which means that its logs are sometimes sent to the wrong chat on slack. this PR address this by updating the notification path to match that of the other bots.
**Summary**
updates a log in the OO.
**Testing**
Fixes #XXXX

fix(OO): Address wrong log pathing

---

packages/liquidator/src/liquidator.js
packages/liquidator/test/Liquidator.js

**Motivation**
The current liquidator design makes it possible for the liquidator to liquidate itself. This is an extremely undesirable state. This PR makes it impossible for this to happen by preventing the liquidator from liquidating positions where it is the sponsor.
**Summary**
Updated tests and implementation.
**Testing**

feat(liquidator): prevent liquidator from liquidating itself

---

packages/api/package.json

**Motivation**
api package is being published under the name `api` rather than `@uma/api`.
**Summary**
Updated the package.json.
**Testing**
**Issue(s)**
N/A

fix: update api package name to be under @uma

---

packages/core/deploy/023_deploy_state_sync_mock.js
packages/core/deploy/024_deploy_fx_root_mock.js
packages/core/deploy/025_deploy_fx_child_mock.js
packages/core/deploy/026_deploy_oracle_root_tunnel.js
packages/core/deploy/027_deploy_oracle_child_tunnel.js
packages/core/deploy/028_deploy_governor_child_tunnel.js
packages/core/deploy/029_deploy_governor_root_tunnel.js

**Motivation**
Polygon bridge contracts fail to deploy on networks other than those with hardcoded addresses in the deployment scripts (including local networks needed for testing).
**Summary**
Mocks were added to deployment process as a fallback in case these hardcoded addresses aren't present. These mocks are tagged with `test` and their names so they won't be deployed as a part of a typical l2 polygon deployment unless specifically added.
**Testing**
**Issue(s)**
N/A

fix(core): fix polygon deployent scripts for test/local environments

---

packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/BinaryOptionLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/CoveredCallLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LinearLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol

**Motivation**
As a general rule, all public methods in the `core` package's smart contracts should include `nonReentrant` and  `nonReetrantView` modifiers. the LSP was missing these modifiers in a number of key places, in particular the `create` function in the `LongShortPair` that is used in the minting of LSP tokens. 
**Summary**
Adds `nonReentrant` and  `nonReetrantView` modifieriers to required locations in smart contract code.
**Testing**

fix(LSP): Add missing rentrancy modifiers

---

packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.js

**Motivation**
There was a small but substantial bug in the `RangeBondLongShortPairFinancialProductLibrary.sol` that enabled the bond's params to be overridden. Clearly, this is undesirable behavior as it could lead to a malicious actor affecting settlement differently from the original contract parameterization. This PR fixes this bug as well as the tests that were showing up false positives on this test case.
**Summary**
Updated the contracts and tests to address a bug in an LSP contract.
**Testing**

fix(LSP): Prevent parameter override on Range Bond Lib

---

packages/core/test/financial-templates/long-short-pair/LongShortPair.js

**Motivation**
The LSP currently contains no unit tests to validate that it behaves correctly with non-18 decimal collateral. Many partners want to collateralized this product in USDC and so it's only prudent to write some tests to validate this behavior works exactly as expected.
**Summary**
Updates the LSP tests to validate USDC works with full lifecycle.
**Testing**

feat(LSP): Validate all logic works as expected with non-18 decimal collateral

---

packages/affiliates/payouts/dappmining/2021-06-14_2021-06-21_YD-BTC-JUN21_0023.json

**Motivation**
#3144
**Details**
Dapp mining for YD-BTC-JUN21 week 24 from 2021/06/14 to 2021/06/21 using 0.3 of dev mining rewards for this period: `Math.floor(1809.384886931907091379 * 0.3) = 542`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1809.384886931907091379",
"weekNumber": 23,
"endDate": "06/21/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 24

---

packages/core/contracts/common/implementation/Lockable.sol
packages/core/contracts/common/implementation/Testable.sol
packages/core/contracts/common/implementation/Timer.sol
packages/core/contracts/financial-templates/common/TokenFactory.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/BinaryOptionLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/CoveredCallLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LinearLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
packages/core/contracts/financial-templates/test/LongShortPairFinancialProjectLibraryTest.sol
packages/core/test/financial-templates/TokenFactory.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/BinaryOptionLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/CoveredCallLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/LinearLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.js
packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.js
packages/core/test/financial-templates/long-short-pair/LongShortPair.js
packages/core/test/financial-templates/long-short-pair/LongShortPairCreator.js
packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js

**Motivation**
OZ identified a number of small issues during their audit. Most of these are typographical or semantic with major functionality issues identified. This PR implements the required changes to correct all errors identified in the audit.
**Summary**
Fixes the LSP contract post-OZ audit. All comments rased from OZ (as can be seen below) have been implemented in this PR.
**The OZ feedback on this set of contracts was as follows**:
The Long-Short-Pair template was developed and modified over several pull requests. Instead of reviewing the PRs individually, we reviewed the completed files. In particular, we reviewed the files in the [`long-short-pair` folder](https://github.com/UMAprotocol/protocol/tree/b508f536ddfd94a79f93f633142bdc868b73461c/packages/core/contracts/financial-templ …

fix(LSP): Audit nits and cleanup

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol

**Motivation**
@Reinis-FRP identified two typos within the LSP creator. This PR addresses these typos.
**Testing**

fix(LSP-creator): address incorrect comment in creator

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/libs/queries.ts
packages/api/src/libs/utils.test.ts
packages/api/src/libs/utils.ts
packages/api/src/services/actions.ts
packages/api/src/services/collateral-prices.ts
packages/api/src/services/synthetic-prices.ts
packages/sdk/src/libs/utils.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1492/convert-synthetic-prices-to-usd
**Summary**
In order to calculate TVM, we need all synthetics priced in USD.  Previously we only stored the native synthetic value, which may or may not be valued against usd. PR adds the feature as well as refactors some api calls. 
This adds a conversion utility which converts to usd based on synthetic price and collateral price.  USD synthetic prices are stored in the prices table, keyed by token address. API is refactored to make querying this data a bit easier. 
**Details**
This refactors and updates docs for several api endpoints and all prices are returned as USD in wei. The main pattern here is that it allows you to query by erc20 address …

feat(api): add usd price conversions to synthetic prices

---

packages/affiliates/payouts/dappmining/2021-06-21_2021-06-28_YD-BTC-JUN21_0024.json

**Motivation**
#3164
**Details**
Dapp mining for YD-BTC-JUN21 week 25 from 2021/06/21 to 2021/06/28 using 0.3 of dev mining rewards for this period: `Math.floor(1255.641272439175516273 * 0.3) = 376`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1255.641272439175516273",
"weekNumber": 24,
"endDate": "06/28/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 25

---

packages/financial-templates-lib/src/price-feed/DominationFinancePriceFeed.js

Signed-off-by: Josh Bowden <josbow@gmail.com>
**Motivation**
Uses `api.domination.finance` endpoint exclusively for all API requests. See #3160.
**Summary**
The API URL was changed from `live.domination.finance` to `api.domination.finance` for the historical price feed.
The `api` endpoint does not do any processing of the pricing data and simply returns the raw historical data from CoinGecko. 
The `live` endpoint is primarily used to power our website's chart and has some data preprocessing for grouping by ticks, etc. 
Importantly, at the moment the `api` endpoint is significantly more stable than the `live` endpoint, primarily due to the fact that the `api` endpoint is not stateful.
**Testing** …

fix(api): use api.domination.finance endpoint (#3160)

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
Hub doesn't provide a trace when it has internal errors.
**Summary**
Print out the trace as the error message.
**Testing**
**Issue(s)**
N/A

fix: add trace to fatal hub errors

---

packages/common/src/PriceIdentifierUtils.js
packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
uSTONKS_0921 needs a default price feed config. This price identifier switches to a manual calculation at expiry, so it also needs to be added to the `OPTIMISTIC_ORACLE_IGNORE_POST_EXPIRY` list.
**Testing**
**Issue(s)**
NA

feat(pf-configs): Add default pf config for uSTONKS_0921 and add to OO ignore list

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
packages/core/test/financial-templates/long-short-pair/LongShortPair.js
packages/core/test/financial-templates/long-short-pair/LongShortPairCreator.js
packages/core/test/proxy-scripts/lsp-broker/LspUniswapV2Broker.js

**Motivation**
The LSP contract needs three additional pieces of functionality:
- The notion of a `pairName` to name an LPS contract. This is useful in front ends to display information about the contract.
- The ability for the deployer to set a custom OO liveness via a `optimisticOracleLivenessTime` param. This is important with complex price requests that might need more than the normal 2 hours to facilitate price proposal verification.
- The ability for the deployer to set a custom OO bond via a `optimisticOracleProposerBond` param. This lets the deployer create stronger security guarantees around price proposals as there is now a cost associated with an invalid proposal.
**Summary**
Updated contracts and unit tests to add a) `pairName`, b) `optimisticOracleLivenessTime` and c) …

feat(LSP): Add LSP pair name, OO liveness and OO bond settings

---

packages/core/contracts/chainbridge/SinkGovernor.sol
packages/core/contracts/chainbridge/SourceGovernor.sol
packages/core/contracts/chainbridge/SourceOracle.sol

**Motivation**
The following audit comments are addressed unless otherwise noted:
This PR extends the logic from [PR 2903](https://github.com/UMAprotocol/protocol/pull/2903/) to send governance actions from the main chain to another EVM-compatible "sink" chain.
There are a couple of misleading comments that should be corrected:
- ~The [`@title` comment](https://github.com/mrice32/protocol/blob/5e81b20b13a961cab8f54b89d2e145a946cd9619/packages/core/contracts/chainbridge/SourceGovernor.sol#L10) of the `SourceGovernor` actually describes the behavior of the `SinkGovernor`.~ This comment was already resolved by [this PR](https://github.com/UMAprotocol/protocol/commit/73644b1794f89078dd5d185402f92d6b7bd14a92#diff-65ed03a28337581c1f4384ac6554ff092fe47a2c0360006fc27fe7f7d1a261d2)
- The …

fix(chainbridge): Response to audit

---

packages/core/contracts/common/implementation/AncillaryData.sol
packages/core/contracts/common/test/AncillaryDataTest.sol
packages/core/contracts/oracle/implementation/OptimisticOracle.sol
packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
packages/core/contracts/polygon/GovernorRootTunnel.sol
packages/core/contracts/polygon/OracleBaseTunnel.sol
packages/core/contracts/polygon/OracleChildTunnel.sol
packages/core/contracts/polygon/OracleRootTunnel.sol
packages/core/contracts/polygon/README.md
packages/core/test/common/AncillaryData.js

This PR introduces the `AncillaryData` library. It also modifies the `_getAncillaryData` function of the `FundingRateApplier` contract and the `_stampAncillaryData` function of the `OptimisticOracle` contract. Further, it removes some revert reasons in the code base to save bytecode. However, as the code is modified again in Pull Request 3054, we will defer the majority of our comments to our [review of that pull request](#3054).
Our only immediate comments are as follows:
- The `requestPrice` function of the `OptimisticOracle` now [calls `stampAncillaryData`](https://github.com/UMAprotocol/protocol/blob/43d569f66af0323813716927ef2dcc8c7f60dd33/packages/core/contracts/oracle/implementation/OptimisticOracle.sol#L166), which is a pass-through function for the internal [`_stampAncillaryData` …

fix(polygon-tunnel): Response to audit

---

packages/affiliates/payouts/dappmining/2021-06-28_2021-07-05_YD-BTC-JUN21_0025.json

**Motivation**
#3193
**Details**
Dapp mining for YD-BTC-JUN21 week 26 from 2021/06/28 to 2021/07/05 using 0.3 of dev mining rewards for this period: `Math.floor(244.271569556685043569 * 0.3) = 73`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "244.271569556685043569",
"weekNumber": 25,
"endDate": "07/05/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21 week 26

---

packages/affiliates/payouts/dappmining/2021-06-28_2021-07-05_YD-ETH-JUN21_0025.json

**Motivation**
#3192
**Details**
Dapp mining for YD-ETH-JUN21 week 26 from 2021/06/28 to 2021/07/05 using 0.3 of dev mining rewards for this period: `Math.floor(1718.977346695976989487 * 0.3) = 515`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "1718.977346695976989487",
"weekNumber": 25,
"endDate": "07/05/2021 11:00 PM", …
```

improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 26

---

packages/core/networks/1.json

**Motivation**
While helping devx with some deployment info, I realized there was a mistake in the mainnet networks file. the LSP creator address does not point to the correct contract and rather points to a `Finder` contract which must have been deployed by mistake when creating the LSP deployment.
**Summary**
Fixes a mistake in the networks file.
**Testing**

fix(networks file): fix broken LSP creator address

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/libs/queries.ts
packages/api/src/services/actions.ts
packages/api/src/services/emp-stats.ts
packages/api/src/tables/emp-stats-history/sorted-js-map.test.ts
packages/api/src/tables/emp-stats-history/sorted-js-map.ts
packages/api/src/tables/emp-stats-history/utils.ts
packages/api/src/tables/emp-stats/js-map.test.ts
packages/api/src/tables/emp-stats/utils.ts
packages/sdk/src/libs/coingecko/coingecko.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1533/refactor-emp-stats-to-break-apart-tvl-tvm-and-other-stats-from-the-same-blob
**Summary**
Refactors the emp stats table to take a single value per table. Updates public api calls to reflect this change, stats no longer return a bundle of stats which include tvl and tvm, but rather you must explicitly call for tvl or tvm directly.  
**Details**
This mainly changes the emp-stats service, the emp-stats-history table structure and app state.  This change essentially changes the 1 historical stat table per emp, and now creates a single table per statistic. TVL and TVM get their own tables, and host multiple emp time series data. Queries on these tables are updated to reflect this.  This allows us now to have separate timestamps for …

improve(api): 1533 refactor emp stats to have a table per stat type

---

packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol

**Motivation**
OZ left a number of additional feedback points on commenting after the most recent audit fixes. This PR addresses these issues. Additionally, `getPositionTokens` was found to be missing a reentrant modifier which was added.
**Testing**

fix(LSP): Address audit commenting issues

---

packages/core/contracts/proxy-scripts/bot-action-wrappers/PositionSettler.sol
packages/trader/scripts/RedeemTokensWithDSProxy.ts
packages/trader/scripts/SettleExpiredPositionWithDSProxy.ts

**Motivation**
While running the single reserve liquidator bot, we created a number of positions due to liquidations. As these contracts are now settling, we require a DSProxy helper script to let us settle these positions. This PR adds the smart contract and script to facilitate this settling of positions.
**Note**: I placed this script within the `trader` package so it would be alongside the other DSProxy helper scripts. This is a bad location and should be moved in future.
**Testing**

liquidator(Proxy-Helper-Scripts): Add DSProxy script to settle an expired position

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol

**Motivation**
A few small final comments were left on the LSP contracts after the addition of the OO liveness time, OO proposal bond and pair name. In particular, these comments were as follows:
This PR introduces a new `pairName` property of `LongShortPair` financial contracts and allows the creator to set custom values for the optimistic oracle's liveness and bond. It also refactors the `LongShortPair` and `LongShortPairCreator` contracts to use an initialization struct instead of a large number of individual parameters.
Our comments are:
- The `createLongShortPair` [`@param` comment](https://github.com/UMAprotocol/protocol/blob/4eaa2e1c23065503336e61bf16916cefbab046bc/packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol#L71) does not list the `pairName` …

fix(LSP): Continuous audit commenting and require modifications

---

packages/core/contracts/common/implementation/AncillaryData.sol
packages/core/contracts/polygon/GovernorChildTunnel.sol

**Motivation**
This PR addresses the comments from [our review of PR 3061](#3061) and [our batch review of PRs 3054, 3082, and 3092](#3054). We have the following comment:
- The [comment](https://github.com/UMAprotocol/protocol/blob/dd211c4e3825fe007d1161025a34e9901b26031a/packages/core/contracts/common/implementation/AncillaryData.sol#L101) explaining the `constructPrefix` function says "appended as a prefix" instead of "prepended".
This PR modifies the chainbridge `SourceGovernor` and `SinkGovernor` contracts so the cross-chain messages cannot specify an ETH amount. We don't have any comments.
It also implements the Polygon Tunnel for governance actions. In particular, it introduces `GovernorRootTunnel` and `GovernorChildTunnel`. Our only comment is that [line …

fix: Response to audit of #3188 and #3089

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/services/actions.ts
packages/api/src/services/market-prices.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1673/add-historical-prices-for-market-data
**Summary**
Adds a table to accumualte historical prices for market prices from the time server starts. This will not backfill history, its not clear that its possible with the api we are using. 
**Details**
This exposes 2 new api endpoints:
- historicalMarketPricesBetween
- sliceHistoricalMarketPrices
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1673/add-historical-prices-for-market-data

feat(api): add historical market prices and expose in api

---

.eslintrc.js
packages/common/src/HardhatConfig.js

**Motivation**
We can't compile with high values for runs (for user gas optimization) because we have a few large contracts that require low runs values to be deployable.
**Summary**
Use hardhat options to compile most contracts with a high runs value, but leave the large contracts with a runs value of 199.
Note: this makes the compilation process take a little longer.
**Testing**
**Issue(s)**
N/A

feat(common): add compiler overrides to allow most contracts to be gas optimized

---

packages/sdk/src/libs/clients/index.ts
packages/sdk/src/libs/clients/lsp-creator/README.md
packages/sdk/src/libs/clients/lsp-creator/client.e2e.ts
packages/sdk/src/libs/clients/lsp-creator/client.ts
packages/sdk/src/libs/clients/lsp-creator/index.ts
packages/sdk/src/libs/clients/lsp/README.md
packages/sdk/src/libs/clients/lsp/client.e2e.ts
packages/sdk/src/libs/clients/lsp/client.ts
packages/sdk/src/libs/clients/lsp/index.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1539/create-lsp-client-in-sdk
**Summary**
Adds 2 clients and some basic tests:
- lsp creator client - allows us to search for address based on network, get a typechain client and deduce deployed lsps by events
- lsp client - allows us to get a typechain client as well as deduce balances based on lsp events
This is a part of a larger task to get lsp state into the api.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1539/create-lsp-client-in-sdk

feat(sdk): 1539 add lsp creator client and lsp client

---

packages/api/src/libs/queries.ts
packages/api/src/services/actions.ts
packages/api/src/services/emp-stats.ts
packages/api/src/tables/emp-stats/js-map.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1680/add-latest-global-tvl-value-and-expose-in-api
**Summary**
Theres an existing call to calculate tvl based on a number of emp addresses. This just calls it on an interval and caches it in the latest tvl table under the key "global".  This is a prerequisite to adding global tvl history, which we currently do not have, we only have tvl per EMP.
**Details**
No api changes were necessary, but when a user requests global tvl, it returns the cached version now rather than doing the math for the request. 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1680/add-latest-global …

feat(api): 1680 cache global tvl rather than compute it for every query

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/libs/queries.ts
packages/api/src/services/actions.ts
packages/api/src/services/emp-stats.ts
packages/api/src/tables/emp-stats-history/sorted-js-map.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1674/add-the-global-tvl-history-to-the-api
**Summary**
Adds global historical tvl processing and exposes in api.
**Details**
This adds 2 new api endpoints specifically for global tvl:
- globalTvlHistoryBetween(start = 0, end: number = nowS(), currency: CurrencySymbol = "usd") => StatData[]
- globalTvlSlice(start = 0, length = 1, currency: CurrencySymbol = "usd")  => StatData[]
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1674/add-the-global-tvl-history-to-the-api

feat(api): add global tvl history and api calls

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/libs/utils.ts
packages/api/src/services/collateral-prices.ts
packages/api/src/services/emp-registry.ts
packages/api/src/services/emp-state.ts
packages/api/src/services/emp-stats.ts
packages/api/src/services/erc20-state.ts
packages/api/src/services/express.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts
packages/api/src/services/market-prices.ts
packages/api/src/services/synthetic-prices.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1728/add-debugging-profiling-logs-to-api-to-determine-what-is-causing-failure
**Summary**
Adds a profiling helper class which can be enabled or disabled with a boolean. Its used around key calls that could possibly be failing.
Requires `debug=1` in env to enable
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1728/add-debugging-profiling-logs-to-api-to-determine-what-is-causing-failure

feat(api): add debugging profiling logs to api to determine

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
UMAUSD and DIGGBTC need to be updated to cater to a couple of specific use cases that will use these price identifiers.
- UMAUSD needs a 1 hr TWAP for UMA Range Tokens
- DIGGBTC needs a 24 hr TWAP to support DIGG rebasing calculations
- DIGGETH was only updated to leave it unchanged, since it referenced DIGGBTC
This pr is accompanied by an [UMIP update](https://github.com/UMAprotocol/UMIPs/pull/365).
**Testing**
**Issue(s)**
NA

feat(df-pf-configs): Update DIGGBTC, DIGGETH and UMAUSD price feed configs

---

packages/api/package.json
packages/api/src/apps/api/app.ts
packages/sdk/src/libs/clients/emp/client.ts
packages/sdk/src/libs/clients/erc20/client.ts
packages/sdk/src/libs/clients/lsp-creator/client.ts
packages/sdk/src/libs/clients/lsp/client.ts
packages/sdk/src/libs/clients/multicall/client.ts
packages/sdk/src/libs/clients/registry/client.ts
packages/sdk/src/libs/index.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1775/bug-replace-ts-node-with-node-when-running-api
**Summary**
This fixes some sdk imports which caused api to crash when running the built version. 
**Details**
Previously we could only run the api with ts-node. This fixes the runtime errors so that it runs from build. The hope is we can remove another possible cause of the API hitting 100% cpu usage intermittently.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1775/bug-replace-ts-node-with-node-when-running-api

fix(api,sdk): allow build to run with node by fixing imports

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/examples/action-client.e2e.ts
packages/api/src/examples/action-client.ts
packages/api/src/index.ts
packages/api/src/libs/queries.ts
packages/api/src/services/actions/emp.ts
packages/api/src/services/actions/index.ts
packages/api/src/services/actions/lsp.ts
packages/api/src/services/express-channels.ts
packages/api/src/services/index.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1714/expose-lsp-state-through-api
**Summary**
This exposes LSP state queried through ingestion services to the express api.
**Details**
There was some refactoring done to how the API works, but it should remain backward compatible. Specific contract calls to the api are now separated by "channels", so the path prepends `/emp/` or `/lsp/` to the action for instance `localhost:8282/emp/actions` - to list all actions on the channel.  The root channel `/` and `/emp` are identical for backward compatibility to existing clients, but this is deprecated and will probably change in the future.
Several new API calls were added specifically for the LSP which mirror many of the EMP calls. The …

feat(api): expose various lsp state calls and refactor api slightly

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/libs/utils.test.ts
packages/api/src/libs/utils.ts
packages/api/src/services/index.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/multi-lsp-creator.ts
packages/api/src/tables/lsps/js-map.test.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1818/determine-how-to-pull-in-other-factories-for-pulling-in-lsps-in-the-api
**Summary**
Add a multi-lsp-creator service that just takes an array of lsp creator addresses and wraps the interface to a single lsp creator service, which then discovers known lsps.  Environment variable must be specified to manually add these creator addresses. If no address is specified, it will always default to the latest known address.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1818/determine-how-to-pull-in-other-factories-for-pulling-in-lsps-in-the-api

feat(api): add ability to specify multiple LSP creator addresses

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/libs/queries/emp.ts
packages/api/src/libs/queries/index.ts
packages/api/src/libs/queries/lsp.ts
packages/api/src/services/actions/emp.ts
packages/api/src/services/actions/lsp.ts
packages/api/src/services/index.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts
packages/api/src/services/stats/emp.ts
packages/api/src/services/stats/index.ts
packages/api/src/services/stats/lsp.ts
packages/api/src/services/synthetic-prices.ts
packages/api/src/tables/lsps/utils.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1490/ability-to-pull-in-tvl-for-each-lsp
**Summary**
This refactors stats and queries to accommodate LSP TVL stats as well as adds some new API calls on the LSP channel. 
**Details**
This adds several TVL calls, including historical and TVL backfill for LSP. Readme is updated with calls.
With slightly more refactoring, LSP and EMP stats could potentially share a lot of the same code, but I was afraid this would be too many unecessary changes, so instead business logic is copied and scoped to a specific contract type. 
Future work will need to combine both EMP and LSP TVL and expose in global, or unified stats
**Testing**
Check a box to describe how you tested these changes and list …

feat(api): 1490 add lsp tvl calculations, per contract, totals and history

---

packages/affiliates/liquidity-mining/CalculateUniswapLPRewards.js
packages/affiliates/liquidity-mining/JoinRolledPayouts.js
packages/core/test/proxy-scripts/atomic-disputer/ReserveCurrencyDisputer.js
packages/core/test/proxy-scripts/atomic-liquidator/ReserveCurrencyLiquidator.js
packages/core/test/proxy-scripts/lsp-broker/LspUniswapV2Broker.js
packages/core/test/proxy-scripts/uniswap-broker/UniswapV2Broker.js
packages/disputer/test/Disputer.js
packages/financial-templates-lib/src/clients/TokenBalanceClient.js
packages/liquidator/test/Liquidator.js
packages/monitors/src/BalanceMonitor.js
packages/monitors/src/CRMonitor.js
packages/trader/test/UniswapV2Trader.ts

**Motivation**
Due to my general stupidity, I've managed to make the same spelling mistake in a number of places in the repo. This Pr fixes this.
**Summary**
Fixes a `ballance` to `balance` in all the places I've made this mistake :)
**Testing**

fix(cross-package): Fixed typo of "ballance"->"balance" in a few packages

---

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js

**Motivation**
Price feeds should support querying custom nodes.
**Summary**
Add a parameter to all price feeds that allows the user to specify an env variable that the feed should use to find the node url to pass to web3.
For example:
```
config = {
nodeUrlEnvVar: "POLYGON_NODE_URL",
...
};
```
This configuration would tell the feed to use the environment variable `POLYGON_NODE_URL` to get the node url that it should use. It was done this way so that users aren't forced to hardcode their node urls in the config json.
**Testing**
**Issue(s)**
N/A

feat: add multichain support for price feeds

---

.eslintrc.js
packages/affiliates/libs/uniswap/contracts.ts
packages/api/src/libs/queries/emp.ts
packages/api/src/services/express-channels.ts
packages/api/src/services/express.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/stats/global.ts
packages/bot-strategy-runner/src/ConfigBuilder.ts
packages/bot-strategy-runner/src/index.ts
packages/common/src/HardhatConfig.ts
packages/common/src/ProviderUtils.ts
packages/common/src/SolidityTestUtils.ts
packages/core/scripts/mainnet/WithdrawTokens.ts
packages/merkle-distributor/integration-test/MerkleDistributorHelper.ts
packages/reporters/liquidation-reporter/liquidation-reporter.ts
packages/sdk/src/libs/clients/emp/client.ts
packages/sdk/src/libs/clients/erc20/client.ts
packages/sdk/src/libs/clients/lsp-creator/client.ts
packages/sdk/src/libs/clients/lsp/client.ts
packages/sdk/src/libs/clients/registry/client.ts

**Motivation**
The eslint considers an unused variable a warning for typescript.
**Summary**
Added a rule to make this an error rather than warning.
Note: I think this is a warning by default because typescript, itself, can check for this. However, rather than change the tsconfigs, it seems easier to add this to eslint. Long term, we may want to have a standard tsconfig that we inherit from, but that's a slightly larger project.
This also fixes a minor issue with unexported functions in common.
The two other common warnings for ts code are:
- `@typescript-eslint/no-explicit-any` -- we still use any in a lot of places, so we either need to disable it individually or just keep this rule off and just try to avoid any as much as possible.
- `@typescript-eslint/explicit-module-boundary-types` …

fix: make unused variables an error in the typescript linter

---

packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/SuccessTokenLongShortPairFinancialProductLibrary.sol
packages/core/test/financial-templates/common/financial-product-libraries/long-short-pair-libraries/SuccessTokenLongShortPairFinancialProductLibrary.js

**Motivation**
We would like to have a generalized `SuccessToken` financial product library where the base percentage can be set as a parameter, with the remaining percentage acting like an embedded call option.
**Summary**
Using the `SimpleSuccessToken` as a model, this PR adds a generalized `SuccessToken` financial product library and associated tests.
**Details**
* We discussed creating an even more generalized financial product library, where the "option" part of the payout could follow arbitrary logic defined in an external financial product library, which could be a call option, binary option, range token, or something else. It was determined that this was actually harder to reason about as a deployer, in addition to being more difficult to test, so we stuck with the call option …

feat(fpl): add generalized success token FPL with parameterized base percentage

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js

**Motivation**
ibBTC related price identifiers defined in [UMIP-119](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-119.md) needs default price feed configuration.
**Summary**
Default price feed configuration was added for ibBTC/BTC, BTC/ibBTC, ibBTC/USD and USD/ibBTC price identifiers.
**Details**
These price feed configurations utilizes multichain support introduced in #3277.
**Testing**
**Issue(s)**
NA

feat(pf-configs): Add default pf configs for ibBTC/BTC, BTC/ibBTC, ibBTC/USD and USD/ibBTC

---

packages/api/src/apps/api/README.md
packages/api/src/libs/queries/emp.ts
packages/api/src/libs/queries/lsp.ts
packages/api/src/services/actions/emp.ts
packages/api/src/services/actions/global.ts
packages/api/src/services/actions/lsp.ts
packages/api/src/services/lsp-state.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1884/add-single-contract-tvl-calls-to-global-channel
**Summary**
There were several calls requested by francesco to be added to facilitate data requests when the type of contract is unknown. These are documented in the readme.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1884/add-single-contract-tvl-calls-to-global-channel

feat(api): 1884 add additional global utility calls

---

packages/api/src/apps/api/app.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1921/add-pairname-to-lsp-state-in-api
**Summary**
Enables pairName for lsps and updates some tests to verify
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1921/add-pairname-to-lsp-state-in-api

feat(api): add pairName to lsp state

---

packages/api/src/services/actions/global.ts
packages/api/src/services/actions/lsp.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1922/bug-fix-global-tvm
**Summary**
This was erroring when global calls was trying to call tvm for LSP. This simply adds a placeholder that returns 0.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1922/bug-fix-global-tvm

fix(api): give lsp actions 0 tvm call, and throw errs on tvm history

---

packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1923/get-pairname-on-lsp-conditionally-with-fallback-if-unavailable
**Summary**
This seperates out pairName into its own call outside of multicall. if pairname does not exist on the particular contract it will set the state to null, adds a test to make sure it comes in properly.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1923/get-pairname-on-lsp-conditionally-with-fallback-if-unavailable

feat(api): allow pairName optionally if contract supports it

---

packages/common/package.json
packages/common/src/gckms/GckmsConfig.ts
packages/common/src/gckms/utils.ts

**Motivation**
The gckms system has been broken since the typescript upgrade in common.
**Summary**
This PR fixes three distinct issues:
- The previous implementation imported the gckms file incorrectly, assuming it was a JSON file.
- The previous implementation did not copy the pre-existing js hidden file to dist. It assumed it was a typescript file that was compiled. However, the tsc compiler ignores files preceded by a `.` by default, so making this work as a ts file is tricky.
- The previous implementation did an incorrect type check and string conversion in order to generate the private keys.
Note: this new process _does_ require you to run the build with the gckms override file if you intend to use it. Adding the override file _after_ building will not work.
**Testing**
Check a box …

fix(common): fix issues with gckms typescript conversion

---

packages/serverless-orchestration/src/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessHub.js

**Motivation**
After the most recent serverless hub update (see https://github.com/UMAprotocol/protocol/pull/3299) a small bug was introduced that only showed itself while testing in production. While the update presented in #3299 works in tests, it does not work in production due to the nesting of logs when running with the bot strategy runner.
This PR makes a small modification to cast the nested logs to a string before looking for the `Started` keyword.
**Summary**
Fixed serverless hub.
**Note this change has been verified in production on the main serverless hub in GCP**
**Testing**

fix(serverless-hub) address started keyword-lookup

---

packages/api/src/services/market-prices.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1963/bug-adjust-matcha-price-call-to-use-correct-decimals
**Summary**
Some market prices were not showing, this may have been to querying the matcha api with the wrong quantity of synthetic. Small change to use token decimals to set the correct synthetic amount when calling matcha api. 
**Details**
This synthetic token used to not return a market price: 0x2dE7A5157693a895ae8E55b1e935e23451a77cB3, which it now does after this fix 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1963/bug-adjust-matcha-price-call-to-use-correct-decimals

fix(api): use token decimals when looking up market price

---

packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/libs/queries/lsp.ts
packages/api/src/services/actions/lsp.ts
packages/api/src/services/stats/lsp.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/1953/update-the-global-tvm-to-account-for-lsps
**Summary**
This replicates a lot of the infrastructure from EMP TVM to LSP TVM. The final TVM values for LSPs are just copied from its TVL, so ultimately the user just sees the LSP TVL as TVM.  The global TVM is also updated with the new global TVM values.
Global TVM value goes from 31.6 million -> 45.4 million with this new addition
**Details**
This allows the frontend to call to get an LSPs tvm per address or a group of addresses on the `lsp/tvm` action. Most likely this wont be used. The main change comes from the global tvm value which should now be slightly higher and no changes to FE necessary for this.  Another minor …

feat(api): add lsp tvm by copying in tvl as the source

---

packages/api/src/apps/api/app.ts

**Motivation**
https://app.clubhouse.io/uma-project/story/2006/bug-emp-registry-and-lsp-creator-miss-created-contracts
**Summary**
This ensures the right block numbers are being set when calling update on services which use block events. Previously we were missing some contract creation events because some block ranges were being skipped. This just updates these calls with the correct block ranges on init and for each tick.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/2006/bug-emp-registry-and-lsp-creator-miss-created-contracts

fix(api): fix event queries for discovering contracts

---

packages/core/contracts-ovm/insured-bridge/implementation/BridgeAdmin.sol
packages/core/contracts-ovm/insured-bridge/implementation/BridgePool.sol
packages/core/contracts-ovm/insured-bridge/implementation/OVM_BridgeDepositBox.sol
packages/core/test/insured-bridge/BridgePool.js

**Motivation**
This PR cleans up some stuff in the insured bridge contracts, addresses some outstanding todos and adds some additional code hygiene.
The main(only) logic change in this PR is the introduction of a new state variable in the bridge pool called `pendingReserves`. This variable acts to track _eserves that are not yet utilized but are pre-allocated for a pending relay_. i.e if a relay action has happened, which has used funds, but it is not yet finalized, an LP should not be able to pull out their funds if it will prevent the relay action from finalizing.
**Testing**

feat(insured-bridge): clean comments, address some todos and general code hygiene

---

packages/common/src/PriceIdentifierUtils.ts
packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts

**Motivation**
The GASETH-0921 price identifier needs a default price feed config and also needs to be ignored by OO bots at expiry.
**Testing**
**Issue(s)**
NA

feat(df-pf-configs): Add GASETH-0921 default price feed config

---

packages/common/src/PriceIdentifierUtils.ts

**Motivation**
Some price identifiers do not have accompanying price feeds and should be ignored by OO bots. 
**Summary**
Adds price identifiers to OPTIMISTIC_ORACLE_IGNORE list.
**Testing**
**Issue(s)**
NA

feat(common): Ignore Optimistic Oracle requests for identifiers without price feeds

---

packages/core/deploy/006_deploy_voting.js
packages/serverless-orchestration/.mocharc.js
packages/serverless-orchestration/hardhat.config.js
packages/serverless-orchestration/package.json
packages/serverless-orchestration/test/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessSpoke.js
packages/serverless-orchestration/truffle-config.js

**Motivation**
All packages should be fully migrated to running on hardhat without the truffle plugin.
**Summary**
These packages still require an external node to be run (either hardhat node or ganache), but they now don't require truffle.
**Testing**
**Issue(s)**
N/A

improve(serverless-orchestration): migrate to hardhat

---

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.ts
packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js

**Motivation**
We would like to have a more obvious way for users to specify what node they want a price feed connected to.
**Summary**
This PR modifies how the user specifies this by establishing a standard `NODE_URL_[CHAIN_ID]` env variable that users can use to specify the node for a particular chain id. The price feeds will be parameterized with the chain id (`chainId` field) and this url will automatically be used with that feed.
**Testing**
**Issue(s)**
N/A

feat(financial-templates-lib): improve the way alternative nodes are handled in the price feeds

---

packages/api/src/apps/api/app.ts
packages/api/src/services/emp-registry.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/multi-lsp-creator.ts
packages/sdk/package.json
packages/sdk/src/clients/emp/client.ts
packages/sdk/src/clients/erc20/client.ts
packages/sdk/src/clients/lsp-creator/client.e2e.ts
packages/sdk/src/clients/lsp-creator/client.ts
packages/sdk/src/clients/lsp/client.ts
packages/sdk/src/clients/multicall/client.ts
packages/sdk/src/clients/multicall2/client.ts
packages/sdk/src/clients/registry/README.md
packages/sdk/src/clients/registry/client.e2e.ts
packages/sdk/src/clients/registry/client.ts
packages/sdk/src/index.ts

**Motivation**
We want to remove all uses of the core artifacts directly (or through the old get* methods in core) to allow us to remove the truffle build from core.
**Summary**
This removes all direct references to core in the sdk package.
**Testing**
**Issue(s)**
N/A

improve(sdk): remove @uma/core references from sdk package

---

packages/common/src/HardhatConfig.ts
packages/common/src/hardhat/plugins/ExtendedWeb3.ts
packages/trader/.mocharc.js
packages/trader/hardhat.config.ts
packages/trader/package.json
packages/trader/src/RangeTrader.ts
packages/trader/src/exchange-adapters/ExchangeAdapterInterface.ts
packages/trader/src/exchange-adapters/UniswapV2Trader.ts
packages/trader/src/exchange-adapters/UniswapV3Trader.ts
packages/trader/test/UniswapV2Trader.ts
packages/trader/test/UniswapV3Trader.ts
packages/trader/test/index.ts
packages/trader/truffle-config.js

**Motivation**
Migrate trader off of truffle.
**Summary**
Similar to other PRs, this moves off of any direct dependence on truffle. All tests can be run with mocha (which uses pulls in hardhat under the hood).
Note: there were a few minor source code changes required to get this to work.
**Testing**
**Issue(s)**
N/A

feat(trader): migrate away from truffle

---

packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts
packages/api/src/services/multi-lsp-creator.ts
packages/api/src/tables/lsps/js-map.ts
packages/api/src/tables/lsps/utils.ts
packages/sdk/src/clients/lsp-creator/client.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2281/add-created-timestamp-to-lsp-contracts-in-sdk
**Summary**
The api now holds additional info about the created event for LSPs contract. Based on the event's block number we are now able to serve the created timestamp for this type of financial contract
**Testing**

improve(api): add created timestamp for LSPs

---

packages/core/scripts/BuildContractVersionHashes.js
packages/monitors/.mocharc.js
packages/monitors/hardhat.config.js
packages/monitors/index.js
packages/monitors/package.json
packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/test/BalanceMonitor.js
packages/monitors/test/CRMonitor.js
packages/monitors/test/ContractMonitor.js
packages/monitors/test/OptimisticOracleContractMonitor.js
packages/monitors/test/SyntheticPegMonitor.js
packages/monitors/test/index.js
packages/monitors/truffle-config.js

**Motivation**
We'd like to drop truffle entirely.
**Summary**
This drops truffle and the majority of the core methods from monitors. The only exception is the contract version finder -- we'll need to decide what to do with that down the line to allow our bots to no longer depend on core.
**Testing**
**Issue(s)**
N/A

feat(monitors): remove all truffle dependencies

---

packages/api/package.json
packages/api/src/apps/api/app.ts
packages/api/src/libs/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2260/bug-connection-not-open-on-send
**Summary**
Some research on this error leads me to believe this has to do with web3 websocket disconnecting after being open for some time.  This PR configures the websocket to try to reconnect if this happens. 
**Details**
Config defaults were pulled from other parts of the repo, as this has been done before. 
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2260/bug-connection-not-open-on-send

fix(api): add retry options to web3 websocket

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/index.ts
packages/api/src/libs/utils.ts
packages/api/src/services/emp-state.ts
packages/api/src/services/lsp-state.e2e.ts
packages/api/src/services/lsp-state.ts
packages/sdk/src/index.ts
packages/sdk/src/tables/emps/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/1502/use-multicall-to-prevent-high-infura-usage-for-api-calls-to-contracts
**Summary**
This PR introduces the Multicall2 contract for getting the state of an EMP contract by wrapping the calls into batches instead of using multiple `asyncValues()` calls.
**Testing**

perf(api): perform EMPs calls in batch

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/libs/utils.test.ts
packages/api/src/libs/utils.ts
packages/api/src/services/emp-registry.ts
packages/api/src/services/emp-state.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/lsp-state.ts
packages/api/src/services/multi-lsp-creator.ts

**Motivation**
https://app.shortcut.com/uma-project/stories/space/unsaved
**Summary**
This separates asyncronous loops between checking for new contracts and updating contract state. It seems like the contract state update loop stops after some point, so this will now throw an error if it takes too long.  Some utility functions were added to support these changes.
This also adds some event driven updates as we want to get contract state quickly after discovery.  Its important to note that this change introduces process dependencies between services which use events to communicate. The emp registry and emp state services must now always be within the same process, and the lsp-creator and lsp-state services must likewise also be in the same …

fix(api): better state updating loops and timeouts

---

packages/core/contracts-ovm/insured-bridge/implementation/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js
packages/core/test/insured-bridge/e2e/InsuredBridge.e2e.js
packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/src/price-feed/InsuredBridgePriceFeed.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js
packages/financial-templates-lib/test/price-feed/InsuredBridgePriceFeed.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
The motivation for this PR is gas costs. This reduces the `relayDeposit` average gas cost from 1.2mil to 1mil.
**Summary**
`BridgePool.sol`:
- Removes `priceRequestAncillaryDataHash => depositHash` mapping and instead call the OO directly in `relayDeposit` and `speedupRelay` to determine if a relay was disputed.  
- Remove requirement that you can only speedup undisputed relays
- Remove L1 token from deposit data struct since its stored as contract state variable
`Relayer.ts`:
- Validate that pending relay is valid to avoid speeding up invalid relays
`L2Client`
- Add `depositContract` to deposit struct
`L1Client`
- Add `getRelayForDeposit` helper method that `Relayer` can use to validate relays against deposits.
**Testing**
Check a box to describe how you tested these …

feat(insured-bridge): Refactoring for gas savings

---

packages/api/package.json
packages/api/src/apps/index.ts
packages/api/src/apps/lsp_api/README.md
packages/api/src/apps/lsp_api/app.ts
packages/api/src/apps/lsp_api/index.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2329/optimize-api-for-startup-speed-when-testing
**Summary**
This is to support e2e testing against the LSP umaverse UI. Currently the api takes forever to start mainly due to emp and price feed requests. This is stripped out in this version to allow both faster startup and more responsive updates (tighter update loops) for lsp state and discovering new lsp contracts. This will help when developing e2e LSP tests and automation speed. 
**Details**
to run the new version of the app run `yarn lsp_api`
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2329/optimize-api-for-startup-speed-when-testing

feat(api): optimize api for startup speed when testing

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.ts
packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js

**Motivation**
Currently when `historicalTimestampBuffer` is set > 0, the CW pricefeed expands the valid price period through which to look for a historical price. It matches the earliest price period, which potentially returns the incorrect price if the exact historical price is available.
**Summary**
This PR changes the CW pricefeed to first match the earliest price period without accounting for the historical timestamp buffer, then if nothing is found, it uses the buffer to expand the period.
**Testing**

fix(cryptowatch-pricefeed): Optimistically match price period without buffer first before resorting to buffer

---

packages/core/contracts-ovm/insured-bridge/external/OVM_Lockable.sol
packages/core/contracts-ovm/insured-bridge/implementation/BridgeAdmin.sol
packages/core/contracts-ovm/insured-bridge/implementation/BridgePool.sol
packages/core/contracts-ovm/insured-bridge/implementation/OVM_BridgeDepositBox.sol

**Motivation**
Functions that make external contract calls should guard against reentrancy.
Modifiers add ~10,000 gas on average to calls. As an example, this represents a 1% increase to `relayDeposit`.
**Testing**

feat(insured-bridge): Add reentrancy guards

---

packages/common/src/hardhat/tasks/artifacts.ts

**Motivation**
To allow backend packages (like the SDK) to gracefully switch between contracts-node and contracts-frontend depending on the env, we would like the functions in contracts-frontend to be available in contracts-node.
**Summary**
- `get[ContractName]{Address, Bytecode, Abi}` functional forms should all be available in contracts-node.
- `get[ContractName]Address` has a minor difference between the two packages -- it returns a `Promise<string>` in contracts-node to allow it to work gracefully in hardhat tests. Rather than making things more annoying on the FE packages, I figure the packages that want to incorporate both can either manually handle both cases with a wrapper or just put an await in front of the call, which will work regardless of whether a value or Promise is …

feat(contracts-node): export similar functions in contracts-node as contracts-frontend

---

packages/core/contracts-ovm/insured-bridge/implementation/BridgeDepositBox.sol
packages/core/contracts-ovm/insured-bridge/implementation/Ownable_BridgeDepositBox.sol

**Motivation**
As part of testing, we often require a setup that is not dependent on one L1/L2 implementation. Rather than mimicking every possible combination, it would be nice to have a bridge deposit box designed for this kind of environment. Think front end testing. To this effect, this PR adds a `Ownable_BridgeDepositBox` which is meant to be deployed on the same provider as the other across contracts to aid in testing.
**Summary**
This PR also moved the `StandardBridgeLike` interface into the `OVM_BridgeDepositBox` file as this is where it is used.
**Testing**

feat(insured-bridge): Add "ownable" bridge deposit box to simplify testing

---

packages/common/src/ProviderUtils.ts
packages/serverless-orchestration/test/ServerlessSpoke.js

**Motivation**
We'd like to drop truffle related components from the repo.
**Summary**
To drop the truffle config from common, we need all packages to no longer require it.
I wanted to separate out this sensitive change (i.e. could break bots!) to getWeb3() as a precursor to a larger refactor where all truffle-related components are dropped.
My suggested path forward is to carefully review this, commit it and verify that once deployed, all types of bots run correctly.
**Testing**
**Issue(s)**
N/A

feat(common): HIGH-RISK remove dependence on truffle config for getWeb3

---

packages/core/.solcover.js

**Motivation**
Solcover config was left in core accidentally
**Summary**
Removed the core .solcover file that depended on the common one that was removed in #3398.
**Testing**
**Issue(s)**
Fixes #XXXX

improve(core): remove dependent solcover config

---

packages/common/src/PriceIdentifierUtils.ts

**Motivation**
This identifier does not have a price feed and therefore needs to be proposed manually and be blacklisted from the OO bots. 
**Summary**
Adds `PUNKETH` and `PUNKETH_TWAP` to OO ignore list.
**Testing**
**Issue(s)**
NA

fix(price-identifier-utils): Blacklist uPunks identifiers from OO

---

packages/sdk/package.json
packages/sdk/src/across/feeCalculator.test.ts
packages/sdk/src/across/feeCalculator.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2406/refactor-across-fees-in-sdk-to-remove-web3-dependency
**Summary**
Was able to switch to using ethers native bignumber and utilities, ditching both web3 and bn.js. Was not able to remove the decimal.js dependency, since whats available in ethers (fixednumber) does not have `pow`.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2406/refactor-across-fees-in-sdk-to-remove-web3-dependency

improve(sdk): refactor fee calc to use ethers and bignumber

---

packages/core/test/insured-bridge/AVM_BridgeDepositBox.js
packages/core/test/insured-bridge/BridgeDepositBox.js
packages/core/test/insured-bridge/BridgePool.js
packages/core/test/insured-bridge/OVM_BridgeDepositBox.js
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js

**Motivation**
There are some cases where we should use the `const { web3 } = hre;` (see @mrice32 's PR here: https://github.com/UMAprotocol/protocol/pull/3406#discussion_r719995423 where the changes were made on another PR)
**Summary**
Update the case where we already import `hre` to more correctly import `web3`. Note that there are still many files that use the old syntax. This is the case if we don't first import `const hre = require("hardhat");`. For example, see here: https://github.com/UMAprotocol/protocol/blob/8773494d29cf0428ca6d65f0272b135ba3dafcbf/packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js#L1
**Testing**

fix(hardhat): update HRE syntax

---

packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js
packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
If an instant relayer underpays a recipient, perhaps because the realizedLpFeePct specified by the Relay is set too high, then currently they will receive the full relay amount when the Relay eventually settles. They will net the amount that they underpaid.
We need a way to keep track of whether instant relayers paid the correct amount, and to make sure that users always receive the correct relayed amount.
**Summary**
This PR introduces a new mapping of hashed `{depositHash, relay.realizedLpFeePct}` to `instantRelayer` address. Whenever a relay is proposed for a deposit, this `instantRelayHash` is deterministically linked to it and allows any `instantRelayer` to speed up the relay. If the relay params end up getting finalized, then the instant relayer who sped up those …

fix(insured-bridge): Instant relayer should only receive refund iff they sped up valid relay

---

packages/common/src/PriceIdentifierUtils.ts
packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts

**Motivation**
PUNKETH-1221 and GASETH-1221 are both self referential price identifiers that reference their own token's trading price prior to expiry. Both identifiers need default price feed configs and need to be ignored for OO expiry requests, since those requests will require a different pricing calculation. 
**Summary**
Adds default pf configs for PUNKETH-1221 and GASETH-1221 and ignores them for OO expiry requests. 
**Testing**
**Issue(s)**
NA

feat(pf-configs): Add PUNKETH-1221 and GASETH-1221 default pf configs

---

packages/core/contracts/common/implementation/AncillaryData.sol

**Motivation**
Converting bytes32 to utf8 is expensive.
**Summary**
I found a brilliant implementation from 2016 on a the solidity gitter here https://gitter.im/ethereum/solidity?at=5840d23416207f7b0ed08c9b, which brought the gas cost down to nearly nothing. It was originally built for addresses, but some quick mods made it work for bytes32. Note: I tried to modify the implementation as little as possible on the first go, but I will try to optimize it a bit more for code size, maintainability (comments), and gas. I quickly did compare its output to our other conversion function to verify the output and it seemed to work. 
Before:
```
Relay: 546086
Speed up: 94842
Settle: 312914
Total: 953842
```
After:
```
Relay: 488411
Speed up: 94842
Settle: 255240
Total: 838493
```
Total savings: …

feat(insured-bridge): optimize bytes32 encode function

---

packages/core/contracts/common/implementation/AncillaryData.sol

**Motivation**
We should improve the gas efficiency of our address utf8 encoding process similar to bytes32.
**Summary**
Old gas:
```
Relay: 488411
Speed up: 94842
Settle: 255240
Total: 838493
```
New gas:
```
Relay: 455196
Speed up: 94842
Settle: 255240
Total: 805278
```
Improvement: `33215`
**Testing**
**Issue(s)**
N/A

feat(contracts): optimize address -> utf8 conversion

---

packages/core/contracts-ovm/insured-bridge/implementation/BridgeDepositBox.sol
packages/core/contracts/insured-bridge/BridgeAdmin.sol
packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
packages/core/test/insured-bridge/BridgeAdmin.js
packages/insured-bridge-relayer/src/RelayerHelpers.ts

**Motivation**
The current Bridge Admin has no means to support a 1:n relationship between L1 tokens and L2 tokens. For example, consider USDC on arbitrum L2 and optimism L2. This PR updates the implementation to support this kind of whitelisting behaviour.
**Summary**
In addition to solving the relationship problem within the data structure, this PR also adds a unit test to show how the `whitelistToken` method should be used when updating the `bridgePool` address within L2 `BridgeDepositBox`es.
**Testing**

fix(insured-bridge): fix whitelist to work with multiple L2 chains

---

packages/core/contracts/insured-bridge/BridgeAdmin.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
packages/core/contracts/insured-bridge/interfaces/BridgePoolInterface.sol
packages/core/test/insured-bridge/BridgeAdmin.js
packages/core/test/insured-bridge/BridgePool.js

**Motivation**
The bridge pool currently has a set owner that cant be changed. There might be cases where we wish to upgrade the bridge admin to a new address, if we change just the bridge admin contract implementation. 
**Summary**
This PR adds a small change to the bridge Pool and Bridge admin to enable the upgradability of the bridgeAdmin address
**Testing**

feat(insured-bridge): Add the ability to transfer bridgeAdmin in the bridgePool to enable upgradability

---

packages/core/contracts/common/implementation/Testable.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
packages/core/test/insured-bridge/ArbitrumMessenger.js
packages/core/test/insured-bridge/BridgeAdmin.js
packages/core/test/insured-bridge/BridgePool.js
packages/core/test/insured-bridge/OptimismMessenger.js

**Motivation**
We'd like relay and speed up to be able to be called in the same transaction. Using multicall is intractible because it requires the caller to predict the time.
**Summary**
This adds a method relayAndSpeedUp to allow relay and speed up to be done simultaneously. There's a fair amount of repeated code, but the advantage is that there are some gas savings that we get from not having to do repeated transfers or verifications.
**Testing**
**Issue(s)**
N/A

feat(across): allow relay and speed up to be called simultaneously

---

packages/core/contracts/insured-bridge/BridgeAdmin.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js
packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/price-feed/InsuredBridgePriceFeed.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
`relayAndSpeedUp` takes a `DepositData` struct as first param, while `relayDeposit` takes in de-structured `DepositData` params. The latter can easily take in a `DepositData` struct.
**Testing**

feat(insured-bridge): Block instant relays post-expiry and change relayDeposit interface to match relayAndSpeedUp

---

packages/core/contracts-ovm/insured-bridge/implementation/BridgeDepositBox.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js

**Motivation**
If it is a weth pool, the LP should be able to deposit and withdraw directly with ETH which should auto wrap for them.
**Summary**
- Adds the ability for `addLiquidity` to deposit ETH directly, if it is a WETH pool. This behaves the same as `deposit` method on L2 where: if a `msg.value` is included with the TX then the contract auto wraps and deposits weth for the user. Else, the user can deposit WETH (as if it was a normal ERC20) with the "standard" flow.
- Adds a bool to `removeLiquidity` to enable liquidity providers to pull out their funds in ETH, if it is an eth pool.
**Testing**

feat(across): Enable LP deposit/withdraw in ETH

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/apps/datastore_api/README.md
packages/api/src/apps/datastore_api/app.ts
packages/api/src/apps/lsp_api/README.md
packages/api/src/apps/lsp_api/app.ts
packages/api/src/services/emp-registry.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2356/allow-env-to-override-emp-registry-address-in-api
**Summary**
This PR adds option to overwrite the address of the Emp Registry contract by providing a custom env variable.
**Testing**
**Issue(s)**
Fixes #XXXX

improve(api): provide option to overwrite emp registry address

---

packages/affiliates/gas-rebate/VoterGasRebate.js
packages/common/src/TransactionUtils.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts

**Motivation**
This method is the compute-time bottle neck in the `Relayer`.
**Summary**
One way to speed up this method is to increase the number of blocks that we travel per search. Currently it binary searches up and down incrementing/decrementing by only 1 block. Empirically increasing this value speeds up time significantly.
Additionally, increasing averageBlockTime seems to also speed up time significantly. I believe this is the case because making more queries in the initial loop to find a `block.timestamp < targetTimestamp` is much less costly than overshooting on the first query and needing to crawl back.
For example, using an `averageBlockTime = 14` finds a `block.timestamp < targetTimestamp` in 4 tries and completes the function in 2.5 seconds. On the other hand, using …

improve(common): Speed up default behavior for findBlockNumberAtTImestamp

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/price-feed/CreatePriceFeed.ts
packages/financial-templates-lib/src/price-feed/FundingRateMultiplierPriceFeed.ts
packages/financial-templates-lib/src/price-feed/LPPriceFeed.ts
packages/financial-templates-lib/src/price-feed/VaultPriceFeed.ts
packages/financial-templates-lib/src/price-feed/utils.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/price-feed/FundingRateMultiplierPriceFeed.js
packages/financial-templates-lib/test/price-feed/HarvestVaultPriceFeed.js
packages/financial-templates-lib/test/price-feed/LPPriceFeed.js
packages/financial-templates-lib/test/price-feed/VaultPriceFeed.js
packages/financial-templates-lib/test/price-feed/utils.js
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
We'd like to speed up our block searching by timestamp in the relay bots.
**Summary**
This PR changes two things:
- Swaps out the finder algorithm in the relay client for one that uses binary search rather than a linear search as the current one does.
- Makes the BlockFinder a true class rather than a function that returns a function. This makes it easier to work with in typescript. There was a little bit of cleanup in the price feeds related to this change. Overall, this simplified the integration in the price feeds and the relayer bot.
**Testing**
**Issue(s)**
N/A

feat: use faster block finder

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/test/financial-templates/long-short-pair/LongShortPair.js

**Motivation**
_In the LongShortPair contract, a zero early expiration timestamp is used as a flag to indicate that nobody has triggered the early expiration mechanism. However, it is possible to trigger that mechanism with a zero timestamp. In this scenario, the Optimistic Oracle will be be invoked but the protection against subsequent price requests will not be effective. Fortunately, once the settlement price is chosen, it won't be overriden, so this won't lead to inconsistent settlements. Nevertheless, a subsequent price request could change the recorded early expiration timestamp, even if the zero timestamp is used to determine the settlement price. It could also emit a misleading event._
This PR fixes this by preventing the request early expire …

fix(lsp): Fix request early expiration with timestamp of 0

---

packages/core/contracts/insured-bridge/BridgeDepositBox.sol
packages/core/contracts/insured-bridge/avm/AVM_BridgeDepositBox.sol
packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol

**Motivation**
_Many of the events defined in this codebase have parameters that should be indexed: • newAdmin in BridgePoolsAdminTransferred_
• _chainId in WhitelistToken_
• _l2Token in TokensBridged_
• _newAdmin in SetXDomainAdmin_
This PR addresses some of these issues. Other similar issues were implemented in PR https://github.com/UMAprotocol/protocol/pull/3489
**Testing**
**Issue(s)**
Fixes #XXXX

fix(BridgePool): add more indexed params

---

packages/core/contracts/insured-bridge/BridgeAdmin.sol

**Motivation**
OZ pointed out that:
_All functions in BridgeAdmin that call _relayMessage assume the transaction value matches the l1CallValue parameter, but this is not enforced._
This PR addresses this by adding a require to the internal `_relayMesage` method to make this requirement.
**Testing**
**Issue(s)**
Fixes #XXXX

fix(BridgeAdmin): validated amount sent is correct when making admin calls

---

packages/core/contracts/insured-bridge/BridgeDepositBox.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/contracts/insured-bridge/avm/AVM_BridgeDepositBox.sol
packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol

**Motivation**
OZ pointed out the following issue:
_There are some instances throughout the codebase where the Ethereum Natural Specification is missing or incomplete. Examples include:_
- _the BridgeDepositBox, AVM_BridgeDepositBox and OVM_BridgeDepositBox constructors are missing a @param comment for the l1Weth parameter._
- _the BridgePool constructor is missing a @param comment for the isWethPool parameter._
This PR adds the correct natspec docs
**Testing**

fix(BridgePool): address missing nat-spec

---

packages/core/contracts/insured-bridge/BridgePool.sol

**Motivation**
_The BridgePool contract inherits from ExpandedERC20 so that it can issue LP tokens to liquidity providers. This inherits the functionality of OpenZeppelin's ERC20 contract and also provides administrator privileges to the contract deployer, which allows them to mint and burn LP tokens. However, this power is not required and, if exercised, could unfairly penalize liquidity providers._
This issue was previously fixed in PR https://github.com/UMAprotocol/protocol/pull/3492
However, there was still a lingering redundant import. This PR fixes this.
**Testing**

fix(BridgePool): remove redundant ExpandedERC20 import

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol

**Motivation**
OZ identified the following contract issues:
_The requestEarlyExpiration and expire functions of the LongShortPair contract each assume that the caller has granted the contract an allowance to pull the proposer reward._
This PR updates the natspec to include this information.
**Testing**

fix(lsp): Fix requestEarlyExpiration and expire natspec comments

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol

**Motivation**
_The LongShortPair contract generally treats timestamps as uint64 values, which are implicitly cast to uint256 values when passed to the Optimistic Oracle. However, the requestTimestamp parameter of the _requestOraclePrice function is prematurely cast to a uint256. This has no functional consequences._
While this does not present any issues, the code was updated for consistency with the rest of the codebase.
**Testing**

fix(lsp): Fix inconsistent type casting for expiration timestamp

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol

**Motivation**
_The settle function of the LongShortPair contract considers settlement conditions when the current time is strictly before or after the expiration timestamp. However, it incorrectly reverts when the current time matches the expiration timestamp._
This PR fixes this by making a small modification to the settle method, as recommended by OZ.
**Testing**

fix(lsp): Fix incorrect inequality for expiration timestamp in settle method

---

packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
packages/core/test/financial-templates/long-short-pair/LongShortPairCreator.js

**Motivation**
OZ audit identified the following issue:
_The LongShortPair contract retrieves a proposer reward from whichever address triggers the expiration, which is used to incentivize price proposals in the Optimistic Oracle. However, the LongShortPairCreator contract also retrieves and forwards the funds from the deployer address. These additional funds are not passed to the Optimistic Oracle, and instead remain trapped within the LongShortPair contract._
To address this, the duplicate transfer in the factory was removed.
**Testing**

fix(lsp): remove duplicate transfer in factory

---

packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol

…
**Motivation**
The `SkinnyOptimisticOracle` invokes callback functions on the price requester, if they exist, so the requester can respond to significant state changes. However, the callback is incorrectly invoked on the price proposer instead of the price requester in the `proposePriceFor` function. This means the price requester is unable to respond to price proposals.
Fortunately, this feature is not used in the current code base. Nevertheless, consider invoking the `priceProposed`callback on the requester.
**Testing**

fix(skinny-optimistic-oracle): proposePrice callback should be to requester not msg.sender

---

packages/core/contracts/common/implementation/AncillaryData.sol
packages/core/contracts/common/test/AncillaryDataTest.sol
packages/core/test/common/AncillaryData.js

**Motivation**
The `appendKeyValueBytes32` function should combine its inputs into a formatted bytes array. However, the `currentAncillaryData` is incorrectly discarded.
Since the ancillary data influences the oracle resolution process, an incorrect value could undermine the oracle results. Fortunately, there is only one call to `appendKeyValueBytes32` in the codebase, and it uses an empty `currentAncillaryData` buffer, so the bug does not affect this case.
This PR updates the `appendKeyValueBytes32` function so that the `currentAncillaryData` is included in the returned bytes array.
**Testing**

fix(ancillary-data-lib): Fix faulty append function

---

packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
packages/core/test/oracle/SkinnyOptimisticOracle.js

…
**Motivation**
We default the proposer bond amount to the final fee in the case where the caller sets it to 0. Original discussion for this decision in the `requestPrice` method can be found [here](https://github.com/UMAprotocol/protocol/pull/3409#discussion_r719747949).
We forgot to do the same default logic in `requestAndProposePriceFor`.
From the audit:
> The `requestPrice` function of the `SkinnyOptimisticOracle` contract uses the final fee as the bond if the bond is not specified. However, the `requestAndProposePriceFor` function may use a zero bond, which contradicts its `@notice` and `@param` comments. A zero bond weakens the incentive against invalid proposal or disputes.
Fortunately, the only call to this function in the code base sets a proposer bond. Nevertheless, consider …

fix(skinny-optimistic-oracle): Default proposer bond to final fee in requestAndProposePriceFor

---

packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js

**Motivation**
The `_getDepositHash` function of the `BridgePool` contract unrolls the `depositData` struct to interstice the `l1Token` as an argument in the composition of `keccak256` with the abi encoding. This makes the operation unnecessarily verbose and can lead to bugs when reimplemented on other layers.
Consider simplifying the arguments to simply be the ordered pair `depositData` and `l1Token`.
**Testing**

improve(insured-bridge): Reduce verbosity of _getDepositHash()

---

packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol

**Motivation**
The `requestAndProposePriceFor` function of the `SkinnyOptimisticOracle` contract makes a call to an untrusted `msg.sender` but is not guarded by a `nonReentrant` modifier. While, in this instance, this does not seem to be a security concern, this can introduce unexpected behavior.
Consider adding the `nonReentrant` modifier to all functions which make calls to possibly untrusted contracts.
**Testing**

fix(skinny-optimistic-oracle): Reentrancy guard requestAndProposePriceFor

---

packages/core/contracts/insured-bridge/BridgePool.sol

**Motivation**
`onlyFromOptimisticOracle` is a leftover modifier from when `BridgePool` would provide `priceProposed` and `priceDisputed` callback methods that only the `OptimisticOracle` could call back into. These callbacks were used to track a relay request's life cycle, but this tracking is no longer neccessary.
Relay requests only result in Optimistic Oracle price requests on disputes.
**Testing**

fix(insured-bridge): Remove unused modifier

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/src/price-feed/CreatePriceFeed.ts
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/RelayerConfig.ts
packages/insured-bridge-relayer/src/index.ts

**Motivation**
Every time the relayer runs and sends relays it generates an error right after the fact. This is irritating. This PR fixes this behaviour.
**Summary**
The issue boiled down to double counting deposits due to incorrect filtering in the `Relayer.ts`. See code for more details on the bug and the solution.
Note that this issue was not shown in unit tests as it is an artefact of having multiple pools (more than 1 token) on one relayer.
**Testing**

fix(across-bots): Address issue where relayer produces an error after every relay

---

packages/core/contracts/insured-bridge/avm/Arbitrum_Messenger.sol
packages/core/contracts/insured-bridge/test/Arbitrum_InboxMock.sol
packages/core/test/insured-bridge/ArbitrumMessenger.js

**Motivation**
The `relayMessage` function of the `Arbitrum_Messenger` contract does not emit a relevant event after executing a sensitive action. The `relayMessage` function calls as a subroutine `sentTxToL2NoAliasing` which itself returns the `uint256` value `seqNum`, but this return value is not logged in the `relayMessage` function.
Consider emitting events after sensitive changes take place, to facilitate tracking and notify off-chain clients following the contract's activity.
**Testing**

improve(arbitrum-messenger): Emit event including return value of Arbitrum sys contract call

---

packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js

**Motivation**
This reverts commit 4f315a69402b0d5e1804ce2cb53db5d6ace0e7e6.
Since there are live `BridgePool` contracts that are being tested in production, we need the contract code in Master to match that in production, otherwise the bots will fail. A follow up PR will re-implement commit 4f315a69402b0d5e1804ce2cb53db5d6ace0e7e6 but we cannot merge it in until the beta production contracts are closed.
**Testing**

revert(insured-bridge): undo change to internal _getDepositHash() 

---

packages/sdk/src/across/clients/README.md
packages/sdk/src/across/clients/bridgePool.ts
packages/sdk/src/across/transactionManager.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2785/bridgepool-sdk-returns-a-negative-value-for-deposits
**Summary**
This automatically updates pool and user after it detects a transaction completes. Do not update manually, just wait for events to update state for you. This waits 3 confirmations because of inconsistency of events showing up in infura immediately after tx completes.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2785/bridgepool-sdk-returns-a-negative-value-for-deposits

fix(sdk): update user and pool after transaction confirms

---

packages/core/contracts/common/implementation/MultiCaller.sol
packages/core/contracts/insured-bridge/BridgePool.sol

**Motivation**
To enable more scalable off-chain infrastructure, it would be useful to be able to send batches of transactions. We can do this easily with multicall. However, multicall runs a risk of being used along side `msg.value`. to deal with this, we simply can prevent multicall usage with any transaction with `msg.value`.
**Summary**
Adds back multicall with a block on any tx with `msg.value`.
**Testing**

feat(insured-bridge): add back safe multicaller

---

packages/common/src/HardhatConfig.ts
packages/common/src/PublicNetworks.ts
packages/common/src/hardhat/tasks/acrossPool.ts
packages/core/networks/1.json
packages/core/networks/42161.json

**Motivation**
Small PR to uddate deployment addresses to latest mainnet and arbitrum deployments. Also contains a fix to the across pool script to address wethpool bool.
**Testing**

feat(core): add new deployment addresses for across and update script

---

packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
packages/financial-templates-lib/test/clients/OptimisticOracleClient.js

**Motivation**
This is a prerequisite PR to enabling the `optimistic-oracle-proposer` to work with the `SkinnyOptimisticOracle` contract. This should make the OptimisticOracleClient work with all existing bots without modifications, but also enable the caller to specify the client to detect a SkinnyOptimisticOracle.
**Testing**

feat(optimistic-oracle-client): Can read SkinnyOptimisticOracle state

---

packages/sdk/src/across/clients/bridgePool.e2e.ts
packages/sdk/src/across/clients/bridgePool.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2919/sdk-across-pooleventstate-can-sometimes-query-the-same-event-more-than-once
**Summary**
When querying events, this class stores the last endBlock as the new startBlock for the next event query. The problem is that events returned are inclusive for start/end blocks. It may lead to duplicate events being returned. So this simply increements the next startBlock to be endblock+ 1.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2919/sdk-across-pooleventstate-can-sometimes-query-the-same-event-more-than-once

fix(sdk): fix next startblock for pooleventstate

---

packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/RelayerConfig.ts
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
There is a current bug in the relayer's `matchRelayWithDeposit` method that begins a fallback search for a `FundsDeposited` event at the **BridgePool's deployment block height**, but this is nonsensical as the event is emitted by the **BridgeDepositBox**. 
Therefore this PR adds a new mapping of L2 deposit box deployment block heights.
This PR also renames config variables to be more accurate.
**Testing**

fix(across-relayer): Deposit search should start at BridgeDeposit block height, not BridgePool block height

---

packages/insured-bridge-relayer/src/Relayer.ts

**Motivation**
I noticed that Finalizer was not settling an UMA relay, but settled ETH relays that occurred after it. This was because there was a "return" statement where there should be a "continue" statement in the Finalizer's `for` loop.
**Testing**

fix(across-relayer): Finalizer can settle multiple L1 tokens

---

packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
There are currently no unit tests for whether bot can handle multiple L1 whitelisted tokens. These unit tests would have caught the bug that #3580 fixed.
**Testing**

improve(across-relayer): Add unit tests for multiple whitelisted L1 tokens

---

packages/api/src/apps/api/README.md
packages/api/src/apps/api/app.ts
packages/api/src/apps/datastore_api/app.ts
packages/api/src/apps/lsp_api/app.ts
packages/api/src/apps/serverless_write/README.md
packages/api/src/apps/serverless_write/app.ts
packages/api/src/libs/utils.ts
packages/api/src/services/collateral-prices.ts
packages/api/src/services/contracts.ts
packages/api/src/services/emp-registry.ts
packages/api/src/services/emp-state.ts
packages/api/src/services/lsp-creator.ts
packages/api/src/services/multi-lsp-creator.ts
packages/sdk/src/coingecko/coingecko.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2389/ability-to-pull-in-polygon-contracts-in-api
**Summary**
Required changes in order to support Polygon contracts:
- Add support for other networks: optional env added `NETWORK_CHAIN_ID`
- Configure `serverless_write` application to use http web3 provider
- Implement fetching contract events in batches because some web3 providers proved to be really slow (see details in the Testing section below)
- Deploy Multicall2 contract on Polygon chain `0xf279b9d041e2449998Ab244995c1D8810F48321B`
- other optimisations
**Testing**
Infura and Chainstack web3 providers proved to be really slow for querying events of Polygon EMP contracts. On the …

feat(api): add ability to pull in Polygon contracts

---

packages/sdk/src/across/clients/bridgePool.e2e.ts
packages/sdk/src/across/clients/bridgePool.test.ts
packages/sdk/src/across/clients/bridgePool.ts
packages/sdk/src/across/utils.test.ts
packages/sdk/src/across/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/2966/pool-apy-appears-to-be-inaccurate
**Summary**
Use timestamps to calculate more accurate periods for apy/apr calcs
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2966/pool-apy-appears-to-be-inaccurate

fix: use timestamps to calculate apy periods for more accuracy

---

packages/sdk/src/across/clients/bridgePool.ts

**Motivation**
Bug fix.
**Summary**
There's a typo that causes the PoolState to export the wrong variable for `liquidityUtilizationCurrent`.
**Testing**
**Issue(s)**
N/A

fix(sdk): fix typo in PoolClient

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
The disputer bot should dispute the largest invalid relays first to de-risk the system as much as posible.
**Summary**
Updates the L1 client to sort relays by deposit size, when working with the disputer.
**Testing**

feat(across-relayer): sort by deposit size when disputing

---

packages/contract-notifier/package.json

**Motivation**
ci is broken due to a minor misconfiguration in the contract-notifier package.
**Summary**
Fixed the configuration so the publish settings work with a non paid npm account.
**Testing**
**Issue(s)**
N/A

fix: fix ci publish

---

packages/sdk/src/across/clients/bridgePool.ts
packages/sdk/src/across/transactionManager.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3217/trezor-trezor-one-hw-wallets-cannot-add-liquidity-on-across-pool
**Summary**
This removes  signer.populateTransaction from the transaction manager. This actually caused 2 major problems. 
1.  it assumed signers were eip-1559 compatible, causing errors when sent to metamask with hardware wallets that are not compatible.
2.  it set gas estimates that might be different from what the app was estimating during a "max eth send" event, causing the transaction to fail validation before being sent to metamask.  
Now all unset fields will be set by metamask, which has more control and information about the wallet environment.
Because we remove populateTransaction, we allow manual overrides in …

fix(sdk): do not pre-populate transactions, allow overrides

---

packages/core/contracts/insured-bridge/BridgeAdmin.sol
packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
packages/core/contracts/insured-bridge/interfaces/BridgePoolInterface.sol
packages/core/test/insured-bridge/BridgeAdmin.js
packages/core/test/insured-bridge/BridgePool.js

**Motivation**
This rate is not easy to set and forget and should be configurable by Bridge admin.
**Testing**

feat(across): Add Setter for LP Fee %/second in BridgePool

---

packages/core/contracts/cross-chain-oracle/OracleBase.sol
packages/core/contracts/cross-chain-oracle/OracleHub.sol
packages/core/test/cross-chain-oracle/OracleBase.js
packages/core/test/cross-chain-oracle/OracleSpoke.js

**Motivation**
`OracleBase.publishPrice` can currently only be called after a price is requested, which usually comes via a cross-chain price request. This is unnecessarily restrictive as the `OracleSpokes` should be able to make all prices available that have been resolved on the DVM, even if they weren't originally requested via the `OracleSpoke` on the child network.
**Testing**

improve(cross-chain-oracle): Allow publishPrice to be called for any DVM resolved price

---

packages/core/contracts/insured-bridge/BridgePool.sol
packages/core/test/insured-bridge/BridgePool.js

**Motivation**
_undistributedLpFees should be thought of as a component of utilizedReserves. It's not guaranteed to be smaller than liquidReserves, which means line 742 could unexpected negative overflow. The exchange rate should compute liquidReserves + utilizedReserves first, and then subtract undistributedLpFees_
A manual test was done to verify this behaviour. Indeed, when `undistributedLpFees_` is greater than `liquidReserves ` the `exchangeRateCurrent` method reverts. The impact of this prevents adding/removing liquidity and does not break anything else. I created a test that would add liquidity then relay once to get a value in undistributedLpFees then relay again to use almost all liquidReserves such that `undistributedLpFees>liquidReserves` …

fix(across): address possible underflow in bridge pool

---

packages/core/contracts/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Arbitrum_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
packages/core/test/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.js

**Motivation**
We would like to support EVM compatible chains that we haven't built specialized bridge integrations for.
**Summary**
This contract matches the interface of other ChildMessengers, but instead of bridging, it just emits logs on incoming messages and allows an admin to send messages out.
**Testing**
**Issue(s)**
N/A

feat: add Admin_ChildMessenger

---

packages/insured-bridge-relayer/src/Relayer.ts

**Motivation**
For the disputer, when a pending relay is skipped because its `chainID !== L2Client's chain ID` but the `chainID` is whitelisted, the bot should add an `undefined` entry to the relaysToDispute array, but incorrectly adds `null`.
I discovered this bug because the `Optimism` bot was timing out unexpectedly when there were ONLY pending relays for `Arbitrum` deposits, and therefore an array of `null` pending relays were being passed to `_generateRelayTransactionForPendingDeposit` which only filters out `undefined` relays. However, this bug mysteriously 
disappeared when an `undefined` relay was added to the array passed to `_generateRelayTransactionForPendingDeposit`, for example when the relay is for the `Optimism` chain but its already sped up!
**Testing**
Check a box to …

fix(across-relayer): Skipped relay should add `undefined` to disputeRelay array, not `null`

---

packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/RelayerConfig.ts
packages/insured-bridge-relayer/src/RelayerHelpers.ts
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/index.ts

**Motivation**
Currently the user must specify the `RATE_MODELS` for any L2 network that hasn't whitelisted all of the tokens in the default `RATE_MODELS` dictionary in `@uma/sdk`. We should not ask the user to specify `RATE_MODELS` and they should instead be able to rely on the default in the code. This PR prunes the whitelist derived from `RATE_MODELS` for a specific L2 by removing any L1 tokens not on that chain's specific deposit box.
**Testing**

improve(across-relayer): Should prune whitelisted L1 tokens using L2 events

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts

**Motivation**
After each loop iteration, `fromBlock` gets set to `toBlock + 1`, while `toBlock` gets set to the latest block height. If latest block height doesn't advance fast enough between `update()` calls, then its possible that `toBlock > fromBlock`, so we should exit early in this case.
**Testing**

improve(across-relayer): Exit early if block search period is < 0

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts

**Motivation**
CrossDomainFinalizer queries for `WhitelistTokenEvents` but L1 client does the same thing in its `update()` method. We should cache all such events in the L1 client and read them from the CrossDomainFinalizer.
**Testing**

improve(across-relayer): Remove redundant L1 event query

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/insured-bridge-relayer/src/RelayerHelpers.ts
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/index.ts

**Motivation**
L2 event data is less reliable than L1 event data and even less so than querying L1 contracts directly. 
**Testing**

fix(across-relayer): Prune L1 token whitelist using L1 contract state instead of L2 event data

---

packages/core/test/insured-bridge/BridgePool.js

**Motivation**
A user on discord had an issue removing liquidity when utilization was high. this PR shows that even if there is a state mismatch you should be be able to remove liquidity, granted there is sufficient funds in the pool.

feat(across): show that even when internal account mismatches state, can still call removeLiquidity if enough implied liquidity

---

packages/insured-bridge-relayer/src/RelayerConfig.ts

**Motivation**
The default should be set to some buffer below the 100,000 limit based on how the `index.ts` file computes the start block to set in the L2 client. It takes the L2 latest block and then subtracts `L2_BLOCK_LOOKBACK` to get the start
block. A little after, the L2 client updates and sets its own `toBlock` to the latest L2 block at the update time. Therefore, its possible that block height increases enough between the initial L2 latest block query and
the second one that more than 100,000 blocks are queried and the API throws an error.
This fix was inspired by this error which occurs inconsistently:
**Testing**

improve(across-relayer): Reduce default L2_BLOCK_LOOKBACK

---

packages/financial-templates-lib/src/price-feed/utils.ts
packages/sdk/package.json
packages/sdk/src/across/README.md
packages/sdk/src/across/index.ts
packages/sdk/src/across/lpFeeCalculator.ts
packages/sdk/src/across/test/lpFeeCalculator.e2e.ts
packages/sdk/src/across/utils.test.ts
packages/sdk/src/blockFinder.ts
packages/sdk/src/index.ts
packages/sdk/src/utils.ts
yarn.lock

**Motivation**
https://app.shortcut.com/uma-project/story/3307/add-support-for-l2s-that-are-more-than-10-mintues-behind-in-sdk
**Summary**
Wraps the lpfee calculation to add an optional timestamp with the query. The timestamp does a block lookup using BlockFinder code in financial-templates-lib.
**Details**
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3307/add-support-for-l2s-that-are-more-than-10-mintues-behind-in-sdk

feat(sdk): add timestamp search for lp fee pct calculation

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.ts
packages/financial-templates-lib/src/price-feed/PriceFeedInterface.ts
packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js

**Motivation**
The CryptoWatchPriceFeed should be able to read `twapLength` as a parameter specified in ancillary data if available.
**Testing**

improve(cryptowatch-pricefeed): Use twapLength from parsed ancillary data

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts

**Motivation**
This log will be helpful to determine which block was used to compute realized LP fee %, which is derived from the `deposit.quoteTime`.
**Testing**

improve(across-relayer): Additional logging when computing realized LP fee %

---

packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
packages/core/test/cross-chain-oracle/OracleSpoke.js
packages/core/test/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.js

**Motivation**
I believe we should stamp ancillary data in these public methods. I originally removed this stamping logic in [this PR](https://github.com/UMAprotocol/protocol/pull/3627) because the previous `stampAncillaryData` implementation stamped the `msg.sender` address, which means that only the original requester could call `has/getPrice`, but now that we removed it we can add stamping for the caller’s convenience. 
This improves the caller's experience as they only need to pass the original ancillary data that was passed into `requestPrice`.
This PR is possible because `stampAncillaryData` now only stamps the `block.chainId` which is not affected by who the `msg.sender` is.
**Testing**

improve(cross-chain-oracle): Stamp ancillary data in hasPrice and getPrice

---

packages/core/contracts/insured-bridge/RateModelStore.sol
packages/core/test/insured-bridge/RateModelStore.js

**Motivation**
Storing the RATE_MODEL dictionary on-chain provides a trustless, transparent single-source of truth for all clients of this dictionary including the relayer bot, and the across front-end.
**Testing**

feat(across): Add RateModelStore contract

---

packages/common/src/TransactionUtils.ts
packages/common/test/TransactionUtils.js

**Motivation**
Certain types of transaction errors cause the bot to hang.
**Summary**
This catches errors that are thrown before we get a transaction hash back.
**Testing**
**Issue(s)**
N/A

fix: throw errors when transaction fails pre tx hash

---

packages/common/src/FormattingUtils.ts
packages/insured-bridge-relayer/src/Relayer.ts

**Motivation**
This PR makes two logs changes:
1) slack logs sent by the relayer should not wrap to a extra line. to solve this I removed the `pct` from some logs, which was redundant, the make the logs take up a little bit less space
2) there was a subtle bug in the slack markdown creator that removed the last char from the markdown text. see example below:
this slack message:
shows the address as 0xb1A...A68aD but the address ends in a 4, having lost the last param. hovering shows this loss:
this was also fixed.

fix(slack-logger/relay-logs): small logger fixes

---

packages/core/contracts/cross-chain-oracle/chain-adapters/Arbitrum_ParentMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol

**Motivation**
_The Optimism_ParentMessenger and Arbitrum_ParentMessenger contracts inconsistently apply the
nonReentrant modifier. Consider including it on all public functions._
This PR fixes this by consistently applying nonReentrant modifiers to all public functions.
**Testing**

fix(cross-chain-oracle): [L02] add more nonReentrant() modifiers

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol

**Motivation**
_Many functions in the OptimisticRewarderBase contract are missing the @return parameter in their
Natural Specification comments. Consider including it for completeness._
This PR fixes this and adds a few other small commenting changes to the `OptimisticRewarderBase`.
**Testing**

fix(optimistic-rewarder): [L05] improved natspec commenting

---

packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol

**Motivation**
OZ identified the following issue: _The GovernorSpoke contract incorrectly uses the ChildMessengerConsumerInterface type to describe its messenger variable. Consider using the ChildMessengerInterface instead._
This PR fixes this by using the correct interface.
**Testing**

fix(cross-chain-oracle): [N03] address incorrect interface

---

packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol

**Motivation**
OZ identified a number of typographical errors:
In the Admin_ChildMessenger contract, impleenting should be implementing
In the OptimisticRewarderBase contract, timestap should be timestamp.
In the OptimisticRewarderBase contract, liveness liveness should be liveness.
In the GovernorSpoke contract, only called should be only be called.
In the Optimism_ChildMessenger contract:
onlyCrossDomainAccount should be onlyFromCrossDomainAccount.
addresses on the L1 should be addresses on the L2
This PR addresses these.
**Testing**

fix(core-contracts): [N06] fix some typographical errors

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol
packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderCreator.sol
packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderToken.sol
packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticStaker.sol

**Motivation**
OZ identified the following issue: 
To improve readability of the code, consider removing the following unused imports:
- The OptimisticRewarderBase contract imports the unused Constants contract
- The OptimisticRewarderToken contract imports unused OptimisticRewarder contract
- The OptimisticRewarderCreator contract imports unused ERC721 and Testable contracts
- the OptimisticStaker contract imports usused OptimisticRewarder and
OptimisticRewarderToken contracts
This PR addresses this by removing these imports.
**Testing**

fix(optimistic-rewarder): [N07] addressed unused imports

---

packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol
packages/core/contracts/cross-chain-oracle/interfaces/ChildMessengerConsumerInterface.sol

OZ identified the following issues:
_Here are some misleading comments we identified during our review:
ChildMessengerConsumerInterface.sol:
Line 5 says "parent messenger" instead of "child messenger"
GovernorSpoke.sol:
Lines 49-51 links to a Gnosis file even though the comment says the snippet was copied
from Governor.sol. Additionally, the snippet is not identical to the one in Governor.sol_
This PR addresses these misleading comments.
**Testing**

fix(cross-chain-oracle): [L03] fixed wrong commenting

---

packages/core/contracts/oracle/implementation/Proposer.sol
packages/core/test/oracle/Proposer.js

**Motivation**
```
The resolveProposal function of the Proposer contract simply validates that the oracle has resolved,
but does not check if the bond has been distributed. This means the same proposal can be resolved
multiple times, resulting in duplicate bond payments. Consider flagging or deleting existing proposals
when they are resolved.
```
**Summary**
This PR deletes the proposal after it is resolved to avoid re-resolution.
**Testing**
**Issue(s)**
N/A

fix: [C02] Proposer cannot pay rewards out multiple times for the same proposal

---

packages/core/contracts/cross-chain-oracle/chain-adapters/Arbitrum_ParentMessenger.sol

**Motivation**
Comments are misleading about what the `refundL2Address` should be set to. Clarifies that address should be set to an EOA or contract that can spend the funds.
**Testing**

improve(cross-chain-oracle): Clarify comments for refundL2Address

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
Hub errors have been consistently failing to bubble up to the winston transports.
**Summary**
This modifies how the logger is created in the hub (one per request), so that we can use the `waitForLogger` function.
It also makes the waiting period customizable via an environment variable `WAIT_FOR_LOGGER_DELAY`, which will allow users to increase the waiting period on the fly without rebuilding.
**Testing**
**Issue(s)**
N/A

fix: harden logger waiting in serverless hub

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol
packages/core/test/financial-templates/optimistic-rewarder/OptimisticRewarder.js

**Motivation**
```
The OptimisticRewarderBase contract defines a Disputed event that is intended to be triggered if a
redemption is disputed. However, this event is not emitted within or outside of the
OptimisticRewarderBase contract.
Consider emitting the event after sensitive changes take place in the dispute function, to facilitate
tracking and notify off-chain clients following the contracts' activity.
```
**Summary**
This PR uses and tests the new event.
**Testing**
**Issue(s)**
Fixes #XXXX

fix: [L01] uses the declared Disputed event

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol
packages/core/test/financial-templates/optimistic-rewarder/OptimisticRewarder.js

**Motivation**
```
When disputing a reward request, the OptimisticRewardBase contract first triggers a proposal on the
SkinnyOptimisticOracle and then disputes that proposal. However, the proposal sets the expiration
time as an offset from the current (dispute) time, while the dispute specifies the expiration as an offset
from the time of the original reward request. In most cases, this discrepancy will prevent the oracle
from identifying the proposal to be disputed, which means valid disputes will not be processed and
invalid reward requests will be accepted.
Consider updating the dispute invocation to correctly specify the proposal to be disputed.
```
**Summary**
This changes the timestamp passed into the Request object provided to the dispute function to match what the …

fix: [C01] fixes issue where disputes are impossible in the OptimisticRewarder

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol
packages/core/test/financial-templates/optimistic-rewarder/OptimisticRewarder.js

**Motivation**
```
The OptimisticRewarderBase contract defines a Requested event which is emitted from the
requestRedemption function when a redemption is requested. This event is defined to emit the expiry
time of the redemption as its last parameter. However, when the event is emitted, its last parameter is
incorrectly set to the current time.
Similarly the Redeemed event reads the expiry time after the record is deleted, so it will be incorrectly
set to zero.
Given that this event can be used to trigger off-chain computations, consider updating the emitted
value appropriately.
```
**Summary**
Corrected as suggested in the Motivation.
Added tests for these events.
**Testing**
**Issue(s)**
N/A

fix: [M01] fixes incorrect event parameters

---

packages/core/contracts/financial-templates/optimistic-rewarder/OptimisticRewarderBase.sol

**Motivation**
```
In order to invoke the Optimistic Oracle, the OptimisticRewarderBase contract grants it a token
allowance, so it can pull the bond payments. If the proposal fails, the reward redemption is cancelled
but the allowance is not reset. Therefore, the Optimistic Oracle will retain an unnecessary residual
allowance until the next time a dispute is triggered. Consider revoking the allowance if the proposal
fails.
```
This PR addresses this by decreasing the allowance granted before proposing the price request. Additionally, `safeApprove` was replaced with `safeIncreaseAllowance` to more correctly use the `safeERC20` lib.
**Testing**

fix: [L06] fix Residual allowance

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/insured-bridge-relayer/src/index.ts

**Motivation**
There is a common issue in the across bots producing irritating logs in slack and making some bots timeout under some conditions. See the screenshot below for the common log.
The cause of this is logging nested JS objects, containing BigNumbers, using the `@google-cloud/logging-winston` package. 
**Summary**
This PR fixes this until a more perminat solution can be implemented.
**Testing**

fix: [across] address issue with nested BN

---

packages/serverless-orchestration/src/ServerlessSpoke.js

**Motivation**
We are producing logs too big to fit into GCP's stack driver. This PR cuts down on the logs sent all in one go. Screenshot below shows the issue attempted to be fixed in this PR:
**Summary**
decreases log bloat.
**Testing**

fix: [across] address issue log mapping

---

packages/sdk/src/across/clients/bridgePool.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3476/fix-bug-with-sdk-validatewithdraw-in-across-client
Someone who tried to withdraw a large lp position ran into an error and could not withdraw.  see [slack](https://risklabs.slack.com/archives/C02D94M08F7/p1638392549018600)
**Summary**
Removes the line that checks against `pool.liquidReserves`
**Details**
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3476/fix-bug-with-sdk-validatewithdraw-in-across-client

fix(sdk): fix pool withdraw validation

---

packages/bot-strategy-runner/src/index.ts
packages/contract-notifier/index.js
packages/disputer/index.js
packages/funding-rate-proposer/index.js
packages/fx-tunnel-relayer/src/index.ts
packages/insured-bridge-relayer/src/index.ts
packages/liquidator/index.js
packages/monitors/index.js
packages/optimistic-oracle/index.js
packages/serverless-orchestration/src/ServerlessHub.js
packages/trader/src/index.ts

**Motivation**
The `waitForLogger` utility is extremely inconsistant in production and has proven to be dangerous to use. If this utility is called before all GCP logs have fully flushed out of the stream the process will hang until it times out, producing no logs. This makes it very difficult to figure out what's going wrong with the bots and to debug.
Unfortunately, there is no easy solution to this. Ideally, we want a utility that can halt code execution until all streams have been fully flushed (i.e all upstream messages sent). This is not posible with Winston. Note that their documentation claims this is posible but in practice it just does not work. See [this](https://github.com/winstonjs/winston/issues/1250) PR for the best solution I've found (which inspired the original …

fix: [bots] remove wait for logger

---

packages/core/contracts/cross-chain-oracle/GovernorHub.sol
packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol
packages/core/contracts/cross-chain-oracle/test/GovernorMessengerMock.sol
packages/core/test/cross-chain-oracle/GovernorHub.js
packages/core/test/cross-chain-oracle/GovernorSpoke.js
packages/core/test/cross-chain-oracle/chain-adapters/Arbitrum_ParentMessenger.js
packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.js

**Motivation**
The `GovernorSpoke` contract should be able to execute multiple transactions atomically keep the Governance system from losing control of the sequencing of important actions.
**Summary**
This adds a more complex structure for cross-chain messages so that they can contain multiple transactions rather than one.
**Testing**
**Issue(s)**
N/A

feat: governor spoke is able to execute multiple transactions atomically

---

packages/sdk/src/across/README.md
packages/sdk/src/across/constants.ts
packages/sdk/src/across/gasFeeCalculator.e2e.ts
packages/sdk/src/across/gasFeeCalculator.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3644/improve-gas-fee-calculator-in-sdk-to-add-frontend-functionality
**Summary**
This adds a wrapper function to the previous bare bones fee estimator. This roughly matches the output in frontend specific function, but will require some changes for integration. This also adds a "discount" parameter which is optional, to reduce gas costs by the discount rate. 
current frontend definition:
sdk definition 
**Details**
output of this function with the same params as frontend is returning `0.053160704612800294` in eth transfer fees vs across showing `0.0506`, so its in the same ballpark                                                                                      
**Testing**
Check a …

feat(sdk): add detailed gas deposit fees for across

---

packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
packages/sdk/src/across/constants.ts

**Motivation**
If the cross-domain finaliser looks forward to the current block the OptimismBridgeAdapter will error out as L2 transactions have not yet been included in the L1 StateCommitmentChain. This makes the bot throw errors every time a L2->L1 transfer is initiated until the `StateCommitmentChain` has been updated.
The solution is to add an offset on how new the blocks should be that we look at, thereby avoiding the above situation.
**Summary**
Fixes an issue with fresh blocks in the Optimism finaliser.

fix(bots): correct optimism toBlock issue

---

packages/core/networks/4.json
packages/core/networks/80001.json

Signed-off-by: Alex Gaines <againes@umaproject.org>
**Motivation**
The new LSP creator has already been added to other networks. This adds the same contract version to Mumbai. This PR also includes FPL addresses for RInkeby.
**Summary**
Adds the deployed addresses to the networks file.
**Testing**

feat: update mumbai lsp creator and add rinkeby fpl addresses

---

packages/insured-bridge-relayer/package.json
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/index.ts

**Motivation**
We would like to run the relayer for multiple chains in the same process to avoid nonce collisions and allow better batching.
**Summary**
Much of the code was already ready for this change. It only required a top-level Promise.allSettled to loop over all the chainIds we wanted to support.
Note: this should be backwards compatible with all existing configuration. It simply removes a restriction.
**Testing**
**Issue(s)**
N/A

feat: add functionality for relayer to run on multiple chainIds

---

packages/common/src/Constants.ts
packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/test/Polygon_ChildMessengerMock.sol
packages/core/contracts/oracle/implementation/Constants.sol
packages/core/test/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.js

**Motivation**
Currently the `ChildMessenger` doesn't allow upgradeability of the `OracleHub` and `OracleSpoke`. This contract instead can easily implement upgradeability by reading these addresses from the `Finder` for the child network, which can be modified by L1 governance.
**Testing**

improve(cross-chain-oracle): Use Finder in PolygonChildMessenger

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts

**Motivation**
The CVXUSD and USDCVX price identifiers from [UMIP-141](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-141.md) need default price feed configs.
**Summary**
Adds default price feed configs.
**Testing**
**Issue(s)**
NA

feat(pf-configs): Add default pf config for CVXUSD and USDCVX

---

packages/sdk/src/across/clients/bridgePool.ts
packages/sdk/src/index.ts
packages/sdk/src/oracle/index.ts
packages/sdk/src/oracle/services/erc20.ts
packages/sdk/src/oracle/services/index.ts
packages/sdk/src/oracle/services/tests/erc20.e2e.ts
packages/sdk/src/oracle/types/ethers.ts
packages/sdk/src/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3779/add-basic-erc20-service-for-oo-in-sdk
**Summary**
This basic client will be used during the approval flow in the full oracle client eventually. Factory creates a client with or without multicall as multicall is not available on all chains.
**Testing**

feat(sdk): basic erc20 and erc20 multicall client

---

packages/core/contracts/common/implementation/HasFinder.sol
packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol
packages/core/contracts/cross-chain-oracle/OracleBase.sol
packages/core/contracts/cross-chain-oracle/OracleHub.sol
packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
packages/core/contracts/cross-chain-oracle/SpokeBase.sol
packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
packages/core/contracts/cross-chain-oracle/test/OracleBaseMock.sol

**Motivation**
I discovered while testing out contracts on live test networks that the `GovernorSpoke` does not make its `finder` address public. This is because the `GovernorSpoke` inherits the `SpokeBase` who's `finder` global variable is private. 
I found this a puzzling design choice so I flipped it to `public`, only to run into compile errors. This is because `OracleBase` also has a `finder` global variable that is `public`, and the `OracleSpoke` inherits both `OracleBase` and `SpokeBase`.
The very simple but naive fix was to add a `finder` public variable to the one contract that _only_ inherits `SpokeBase` but not `OracleBase`: the `GovernorSpoke` contract.
However, it feels weird (cc @mrice32 ) to keep having to declare `finder` in contracts that inherit one another. Instead, we …

refactor(cross-chain-oracle): Add HasFinder base contract

---

packages/insured-bridge-relayer/src/index.ts

**Motivation**
Discovered this was printing out "[Object object]" instead of the error reason.message as intended. For example, here was the sample Error `Object` i logged to console:
```
{
status: 'rejected',
reason: {
code: -32005,
message: 'eth_getLogs block range too large, range: 1332798, max: 100000'
}
}
```
**Testing**

fix(across-relayer): Fix error log

---

packages/insured-bridge-relayer/src/ProfitabilityCalculator.ts
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/ProfitabilityCalculator.ts
packages/insured-bridge-relayer/test/Relayer.ts
packages/insured-bridge-relayer/test/mocks/MockProfitabilityCalculator.ts

**Motivation**
There is a bug in the profitability module that affects tokens whose decimals are != 18.
**Summary**
The profitability module now uses the token's decimals to convert between the amount of the token and its corresponding value in ETH.
Note: this doesn't add new tests. Rather, it modifies existing tests to take decimals into account.
**Testing**
**Issue(s)**
N/A

fix: fix profitability module

---

package.json
packages/api/package.json
packages/api/src/libs/zrx.ts
packages/api/src/services/collateral-prices.ts
packages/api/src/services/synthetic-prices.ts
packages/bot-strategy-runner/src/BotEntryWrapper.ts
packages/common/src/SolidityTestUtils.ts
packages/common/src/TransactionUtils.ts
packages/core/contracts/common/test/MultiCallerTest.sol
packages/financial-templates-lib/src/index.ts
packages/financial-templates-lib/src/price-feed/CreatePriceFeed.ts
packages/fx-tunnel-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/MulticallBundler.ts
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/helpers.ts
packages/insured-bridge-relayer/src/index.ts
packages/insured-bridge-relayer/test/MulticallBundler.ts
packages/insured-bridge-relayer/test/Relayer.ts
packages/sdk/package.json
packages/sdk/src/across/transactionManager.ts
packages/sdk/src/tables/base/table.ts
packages/trader/src/exchange-adapters/UniswapV2Trader.ts
packages/trader/src/exchange-adapters/UniswapV3Trader.ts
yarn.lock

**Motivation**
We'd like the relayer bot to do as much batching as possible.
**Summary**
Rather than doing the batching within the transaction-producing code, this adds a separate bundler that transactions are added to over the course of the bot run. Then, the bundler sorts the transactions by target and fires off batches that are as large as possible.
Note: this upgrades the typescript version to get access to the `Awaited` generic type. This caused some issues with compilation elsewhere in the repo, which were fixed in this PR.
**Testing**
**Issue(s)**
N/A

feat: add transaction bundler to relayer for better batching

---

packages/insured-bridge-relayer/src/index.ts

**Motivation**
Multicall bundler is sending transactions twice.
**Summary**
N/A
**Testing**
**Issue(s)**
Fixes #XXXX

fix: fix bug in multicall bundler

---

packages/fx-tunnel-relayer/src/RelayerConfig.ts
packages/fx-tunnel-relayer/src/index.ts

**Motivation**
Currently, the fx-tunnel-relayer has no node redundancy. If its node fails, it throws.
**Summary**
Make fx-tunnel-relayer use getWeb3 for all of its nodes, so it can take advantage of retry configs for more redundancy.
This meant we needed a way to provide the chain id that it should use for its polygon node so it can provide it to getWeb3.. This adds a CHAIN_ID env variable for this purpose. Happy to consider other options for how to pull in mainnet and polygon nodes via getWeb3.
**Testing**
**Issue(s)**
Fixes #XXXX

feat: add bot redundancy to fx-tunnel-relayer

---

packages/sdk/src/oracle/services/erc20.ts
packages/sdk/src/oracle/store/index.ts
packages/sdk/src/oracle/store/read.ts
packages/sdk/src/oracle/store/store.ts
packages/sdk/src/oracle/store/test/store.test.ts
packages/sdk/src/oracle/types/state.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3810/add-ability-to-read-from-global-state
**Summary**
This adds a basic way to simplify calls to read global state by creating a type safe class with some common calls. Calls are automatically scoped based on the users current input, ie which request they are currently looking at. This means though that reads for some calls wont work unless the input is set ahead of time.  This is mainly meant as an example of how to add calls as needed.
**Testing**

feat(sdk): add basic state reader to oo client

---

packages/common/src/ContractUtils.ts
packages/common/src/TimeUtils.ts
packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
packages/financial-templates-lib/src/clients/OptimisticOracleEventClient.ts
packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
packages/fx-tunnel-relayer/src/index.ts
packages/monitors/index.js
packages/optimistic-oracle/index.js

**Motivation**
Event querying on Arbitrum cannot look at more than 10,000 blocks at a time. This PR defines a new environment variable `process.env.MAX_BLOCKS_PER_EVENT_SEARCH` that can be used to control the amount of blocks to search in a single event web3 query
**Testing**

improve(optimistic-oracle-event-client): Support paginated block search config for Arbitrum Infura

---

packages/api/src/apps/serverless_write/app.ts
packages/api/src/libs/utils.ts

**Motivation**
Quick PR for allowing the serverless api to use both http and ws url providers for ethers
**Testing**
**Issue(s)**
Fixes #XXXX

fix(api): allow both http and ws providers

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
The hub doesn't have any capacity to retry its requests. This causes it to sometimes be flaky.
**Summary**
This allows the hub to pull in the spoke's retry config to allow it to construct a retry provider.
**Testing**
**Issue(s)**
N/A

feat: make hub respect bot retry configs

---

packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/tests/client.e2e.ts
packages/sdk/src/oracle/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3781/add-approval-checking-logic
**Summary**
Adds a way to flag important errors the user has when trying to propose. This takes the shape as an array of booleans, which are keyed by an enum type which is self explanatory.  This way you can check on the frontend something like 
`if(flags[ProposalFlags.InvalidContractState]) ...`
**Testing**

feat(sdk): add preview flags for proposing for oo

---

packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts

**Motivation**
When there is state disagreement having chain ID is useful in the context of the batch relayer. This PR adds this.
**Summary**
**Testing**

feat (across-docs): add chain ID to state disagreement log

---

packages/monitors/src/OptimisticOracleContractMonitor.js

**Motivation**
Sometimes the OO monitor will fail to decode data. in this cae we need to still see the ancillary data within the price request. this PR adds a fallback to use utf-8 decoding in this case so the logs are still usable.
sample log that could not be decoded:
Using `Web3.utils.hexToUtf8(ancillaryData)` this should be able to be decoded.
**Testing**

 (OO-monitor): Add UTF-8 fallback decoding to OO bot

---

packages/sdk/src/oracle/services/index.ts
packages/sdk/src/oracle/services/statemachine.ts
packages/sdk/src/oracle/services/tests/statemachine.test.ts
packages/sdk/src/oracle/store/store.ts
packages/sdk/src/oracle/types/index.ts
packages/sdk/src/oracle/types/statemachine.ts

**Motivation**
https://app.shortcut.com/uma-project/story/3974/add-statemachine-runner-to-oo-client-for-handling-all-change-requests
**Summary**
This is a generic state machine implementation which will be used for triggering and tracking transactions, as well as fetching state on chain in reaction to user requests.  It has some features useful to tracking transactions, such as an interval value to prevent over querying, automatic error managament, and an optional memory space used for accumulating data across state transitions. 
**Details**
A statemachine is really useful for asyncronous tasks, like waiting for a pending transaction, or fetching several pieces of state conditionally or in series which may cause branching cases.  We can …

feat(sdk): add generic state machine runner

---

packages/core/deploy/051_deploy_proposer.js
packages/core/networks/1.json

**Motivation**
To move to a decentralized proposal system, we need to deploy a proposer contract.
**Summary**
Adds simple proposer deployment script and a deployed proposer address.
**Testing**
**Issue(s)**
N/A

feat: add proposer address and deployment script

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/src/RelayerConfig.ts
packages/insured-bridge-relayer/src/index.ts

**Motivation**
Its easy to forget to update this map of L1 tokens to bridge pool deployment times, and moreover its trivial to approximate these deployment times using on-chain data.
**Summary**
This adds no additional web3 requests to each bot run, it just stores extra data from the existing web3 requests.
**Testing**

improve(across-relayer): Remove hardcoded deployment data maps

---

packages/optimistic-oracle/index.js
packages/optimistic-oracle/src/proposer.js
packages/optimistic-oracle/test/proposer.js

**Motivation**
The optimistic oracle bot should optionally do settlements for arbitrary accounts.
**Summary**
This adds a new variable in the bot's config to allow additional accounts to be considered during settlement.
**Testing**
**Issue(s)**
N/A

feat: allow bot to settle on behalf of other accounts

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.ts
packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
packages/scripts/src/local/getHistoricalPrice.js

**Motivation**
Normally price feed should pick the last available price at or before request timestamp.
**Summary**
When price request timestamp matches close timestamp for Cryptowatch it now resolves to matching close price (previously it returned open price for the same period).
**Details**
Added check on whether price request timestamp matches end of OHLC period.
**Testing**

fix(pf): use close price for matching cryptowatch close timestamps

---

packages/monitors/src/OptimisticOracleContractMonitor.js

Logs in the #optimistic-oracle-alerts channel (and soon to be discord channels) can be very messy and hard to read. this PR adds in some line breaks to the logs to help with readability.

feat(OO-bot): Add additional line breaks to logs

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts
packages/financial-templates-lib/src/logger/Transports.ts
packages/monitors/src/OptimisticOracleContractMonitor.js

**Motivation**
We want to be able to send messages from our bots to discord. This PR adds a discord transport to facilitate this.
The configs are set to be the same as slack: a `defaultWebHookUrl` that is used for all messages unless a `escalationPathWebhookUrls` is provided for the associated message `notificationPath`.
Sample message
**Testing**

feat(transports): Add discord logger transport

---

packages/monitors/src/OptimisticOracleContractMonitor.js
packages/optimistic-oracle/src/proposer.js
packages/optimistic-oracle/test/proposer.js
packages/optimistic-oracle/test/skinnyProposer.js

Settlement logs can be really messy. this was not an issue before as we were not settling a lot of request. now, however, we are settling requests on a number of chains. To improve quality of life, this PR refines how settlement logs are produced.
Sample message boy output mark-down:
[0x3C4...4293BC](https://etherscan.io/address/0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC) proposed a price of1.00 proposal for TEST8DECIMALS at timestamp 1643168842 with Ancillary data 0x which has been settled! proposer payout is 2.00 tx: [0xcad...cfc567](https://etherscan.io/tx/0xcad8a94db472de0aff860dd8db7b594f59cb0d522a0b8499051b2eaabfcfc567)

feat(OO-bot): Improve settlement logs

---

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.ts

**Motivation**
Need to improve ability to verify Cryptowat.ch price feed for custom OHLC periods.
**Summary**
When running Cryptowat.ch price feed with non-default OHLC period use this value in the API links provided in verbose logging (previously it was hardcoded to 60s).
**Testing**

fix(pf): Use provided ohlcPeriod in cryptowatch pf verbose log

---

packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/test/OptimisticOracleContractMonitor.js

**Motivation**
UI links overflow slack messages.
**Summary**
This just splits the UI link into its own message.
Note: these UI links are never sent as errors. If the regular message is sent as error, this UI link is downgraded to info, so it won't send alerts.
**Testing**
**Issue(s)**
N/A

feat(monitors): split UI link from other log messages due to length 

---

packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
packages/insured-bridge-relayer/test/CrossDomainFinalizer.ts

If pool utilization is high we should more aggresivly send funds over the bridge. This PR adds a 75% cutoff at which the `crossDomainFinalizationThreshold` is halfed to make bridging more aggressive as we run out of funds.
**Testing**
**Issue(s)**
Fixes #XXXX

feat(across-bots): Send funds more aggressivly over bridge when util is high

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts

**Motivation**
We dont always want to post all messages to the discord transport, like we do with other transports. For example, you might only want to post messages that include the specific escalation path. eg you send OO messages to slack but not risk/infrastructure messages.
this PR adds another setting`postOnNonEscalationPaths` that lets the user toggle this behavour.
**Details**
**Testing**

feat(transports): Modify discord transport config

---

packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts

**Motivation**
OO proposer logs was producing wrong etherscan links.
The OO proposer was pulling the chainId from the OO client [here](https://github.com/UMAprotocol/protocol/blob/f169c8f1442e0e2ebb8b7efadf505eea9bfed7da/packages/optimistic-oracle/src/proposer.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L43). 
This was not functioning correctly due to this state variable being private on OO client. this make this call default to undefined, and thus the `createEtherscanLinkMarkdown` was producing links for mainnet, which is wrong.
**Summary**
This PR fixes this by exposing the OO clients chainId variable so the proposer can correctly pull this.
**Testing**
Check a box to describe how …

feat(OO-proposer): make chainId a public varible to enable the proposer to correctly pull the value

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts

**Motivation**
We want to be able to send Discord messages to multiple channels (webhooks). This PR enables this. The PR also makes a small refinement into the message title.
**Testing**
- [C]  Ran end-to-end test, running the code as in production

feat(Discord-Transport): Add ability to send to multiple discord channels at once and refine default log format

---

packages/sdk/src/oracle/services/statemachines/index.ts
packages/sdk/src/oracle/services/statemachines/statemachine.ts
packages/sdk/src/oracle/tests/client.e2e.ts

**Motivation**
State machine queue was acting like a stack and not a queue, which could cause commands to starve.
**Summary**
Use shift instead of pop when dequeuing
**Testing**

fix(sdk): fix properly unqueuing commands from statemachine queue

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts

**Motivation**
We only want to send messages to Discord if and only if the message contains markdown.
**Testing**

feat(Discord-transport): Only send discord logs if the message contains mrkdwn

---

packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/statemachines/fetchPastEvents.ts
packages/sdk/src/oracle/services/statemachines/index.ts
packages/sdk/src/oracle/services/statemachines/pollNewEvents.ts
packages/sdk/src/oracle/services/statemachines/statemachine.ts
packages/sdk/src/oracle/services/statemachines/utils.ts
packages/sdk/src/oracle/services/update.ts
packages/sdk/src/oracle/store/read.ts
packages/sdk/src/oracle/store/write.ts
packages/sdk/src/oracle/tests/utils.test.ts
packages/sdk/src/oracle/types/ethers.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/types/statemachine.ts
packages/sdk/src/oracle/utils.ts

**Motivation**
We need a way to fetch oracle events to build up a table of requests we can lookup from. 
**Summary**
This adds 2 new commands which run at the start of the app. One is responsible for fetching historical events in a robust way, the other fetches all new events.  Historical events are tricky because of chains other than mainnet restricting the range of blocks you can query. This adds logic to dynamically adjust the range to prevent errors, and also allows a configurable "start block" on each chain to prevent history from going back to block 0.  Eventually these events will be used to populate a request index page. 
**Details**
Event requests spanning too large a block range cause errors on polygon-infura. To be really resilient to …

feat(sdk): request list checker using events

---

packages/insured-bridge-relayer/src/MulticallBundler.ts

**Motivation**
The #infrastructure slack channel is becoming too busy. This PR adds a seperate excilation path for across to faciliate the creation of a #across-infrastructure.
**Testing**

feat(Across-Bots): Add additional notification path for across infra to split away from uma infra

---

packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/errors.ts
packages/sdk/src/oracle/services/sortedRequests.ts
packages/sdk/src/oracle/services/statemachines/fetchPastEvents.ts
packages/sdk/src/oracle/services/statemachines/pollNewEvents.ts
packages/sdk/src/oracle/services/update.ts
packages/sdk/src/oracle/store/has.ts
packages/sdk/src/oracle/store/index.ts
packages/sdk/src/oracle/store/read.ts
packages/sdk/src/oracle/store/write.ts
packages/sdk/src/oracle/tests/errors.test.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/utils.ts
packages/sdk/src/utils.ts

BREAKING CHANGE!: request type properties can now be undefined
**Motivation**
We want to be able to link to the transactions that requested/proposed/disputed requests.
**Summary**
Updates event decoding to also attach transaction hash data to the active request on an interval. Uses exisitng polling commands to update the request. 
**Testing**

feat(sdk): use events to populate transaction/block numbers for state

---

packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
packages/optimistic-oracle/src/proposer.js
packages/optimistic-oracle/test/proposer.js

**Motivation**
The OptimisticOracle bot should be able to optionally settle _all_ proposals.
**Testing**
**Issue(s)**
N/A

feat!: add setting to allow OO proposer to settle anyone's proposals

---

packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
packages/insured-bridge-relayer/test/CrossDomainFinalizer.ts

**Motivation**
There is an issue finalizing L2->L1 canonical transfers. This PR addresses this by including the L2 ETH address on optimism in the whitelist so the bot correctly atempts to finalize these.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX

feat(CrossDomainFinalizer): Fix issue finalizing OP L2->L1 transfers

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts

**Motivation**
Discord API sometimes hits rate limit issues. This PR adds a dirty fix to this by slowing down how quickly we hit the API.
**Summary**
**Testing**

feat(discordTransport): Add in a delay between sequential restful calls to discord API to work around rate limits

---

packages/sdk/src/across/test/rateModel.e2e.ts
packages/sdk/src/oracle/README.md
packages/sdk/src/oracle/services/statemachines/disputePrice.ts
packages/sdk/src/oracle/services/statemachines/proposePrice.ts
packages/sdk/src/oracle/services/statemachines/settle.ts
packages/sdk/src/tables/README.md

**Motivation**
Transaction hashes were not being added to the request state when submitting them
**Summary**
This adds transaction hashes to request state when you propose, dispute and settle. Just uses the hash returned from the transaction. Waits until tx is mined before adding it. 
There was a bunch of new linting issues found, so those can be ignored. 
**Testing**

fix(sdk): add tx hashes to dispute, settle, propose 

---

packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts

**Motivation**
Dai Has the same address on Optimism and Arbitrum. This means the previous PR to remove Dai from the L2->L1 Cross domain finalizer from optimism also resulted in it being removed from the Arbitrum finalizer.
This PR adds a further step in the filtration process on L2Addresses to include Dai on arbitrum, thereby re-enabling this token for finalization.
**Testing**

feat: fix dai on Arbitrum L2->L1 Cross Domain Finalizer

---

packages/financial-templates-lib/src/logger/DiscordTransport.ts
packages/financial-templates-lib/src/logger/SlackTransport.ts
packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/test/OptimisticOracleContractMonitor.js

**Motivation**
There are a number of features we'd like to add to the Discord transport:
- Use short link format on UI links to reduce log bloat. This should also remove the extra log produced for each of these.
- removing settlement logs from all discord channels
- Only having proposal logs in oo-fact-checking channel
- request and proposal logs in oo-events channel
This PR implements the above goals.
**Summary**
Short links are done by removing the duplicate logic and refining the `_generateUILink` function in the OO monitor.
The discord transport is refined to accomidate a new prop: `discordSettings` which can be used to spesific sub sets of transports.
**Testing**

fix(discord-transport): Remove extra log messages for links and refine discord config to be more granular on where messages are sent

---

packages/sdk/src/across/constants.ts

**Motivation**
Optimism is now producing blocks faster then when this code was first created. we need to simply ignore more blocks to wait a bit longer until the blocks have hit L1 before looking for finalisation transactions to avoid hitting this error:
This comes about as a result of the L2 transaction not yet being included into an L1 block.
**Summary**
Fixes a bug in the cross domain finaliser on optimism.
**Testing**

fix(across-cross-domain-finalizer): increase Optimism State commitment delay constant

---

packages/insured-bridge-relayer/src/Relayer.ts

**Motivation**
Bot considers a speed up transaction as possible when it should not, causing the bot to be confused and generate errors when the Speedup is profitable but the instant relay is not.
**Summary**
This forces speed up revenue to be 0 when the relay is not in the pending state.
**Testing**
**Issue(s)**
N/A

fix: fix bug in relayer where speedup is attempted when impossible

---

packages/insured-bridge-relayer/src/Relayer.ts
packages/insured-bridge-relayer/test/Relayer.ts

**Motivation**
Bot should not send error logs when a relay is unprofitable as it's irritating.
**Testing**

fix: changed log lvl of unprofitable relays from error to info

---

packages/common/src/ProviderUtils.ts
packages/common/src/RetryProvider.ts
packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js

**Motivation**
We'd like the redundant provider calls to have at least the same number of retries that they normally do.
**Summary**
This updates the way that the redundant providers are created in a few ways:
1. It no longer concatenates the primary RetryProvider with the split "fallback" or redundant ones, since the primary RetryProvider is contains all of the other providers (so it amounts to calling the same provider twice).
2. If there is no Retry config, this just constructs a single provider with no retries using the NODE_URL_<chain id> env variable. This is done because if the user didn't include a retry config, they did not intend to have any retries.
3. It adds some additional logging to the retry provider. Now, when it errors, it will print out an error for each URL in the …

feat: add better provider logging and retries to redundant event calls

---

Dockerfile

**Motivation**
We have seen some issues when running infra on node 16. this PR locks the container to 14, the version with known compatibility.
**Testing**

fix: lock node version to 14

---

packages/common/src/RetryProvider.ts

**Motivation**
Only the last error is printed and the `.toString()` causes the log to print [Object object] instead of the actual error.
**Summary**
This fixes the aforementioned issues.
**Testing**
**Issue(s)**
N/A

fix: fix error printing bugs in #3852

---

packages/serverless-orchestration/src/ServerlessSpoke.js

**Motivation**
Max buffer is being _sometimes_ in the bots due to the extreme amount of logging coming from the arbitrum finalizer.
We're seeing logs like this:
```
"execResponse":{"error":{"code":"ERR_CHILD_PROCESS_STDIO_MAXBUFFER"
```
**Summary**
To stop the process from being terminated due to the buffer being maxed out, this PR extends the buffer by 8x to alleviate the issue. I'm unaware of how to completely get rid of this issue, but there doesn't seem to be an obvious reason why we can't extend the buffer to 8MB from a default of 1MB.
See [docs](https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processexeccommand-options-callback) for more info on this option.
**Testing** …

fix(serverless-spoke): extend stdout buffer to avoid process being killed

---

packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js

**Motivation**
We're often seeing errors like this:
```
One of the blocks specified in filter (fromBlock, toBlock or blockHash) cannot be found.
```
**Summary**
I'm assuming this is happening because of block propagation delays between providers. To more accurately determine the latest block to query for each provider, this change queries all redundant providers and takes the min to ensure all providers have seen that block.
**Testing**
**Issue(s)**
N/A

fix(across-relayer): more accurately determine a safe last block number to query

---

.eslintrc.js
packages/financial-templates-lib/src/logger/DiscordTransport.ts
packages/financial-templates-lib/src/logger/Logger.ts
packages/monitors/index.js
packages/monitors/test/OptimisticOracleContractMonitor.js
packages/monitors/test/index.js

**Motivation**
The discord transport was having rate limiting issues when we try and send too many requests at once. This PR implements a log queue that preseves dropped logs and backs off when the discord API informs us that we are hitting it too hard.
Note: The implementation done here will work well for other transports that struggle to flush! we could re-work this same technique into the slack, pagerduty and GCP transports in the future and bring back the much loved `waitForLogger` method that was deprecated due to its issues.
**Summary**
Fixes Discord transport and introduces a new paridime of log-blocking-flushing for the UMA ecosystem 🧘‍♂️.
**Testing**

fix: Address Discord transport rate limiting issues

---

packages/api/src/services/collateral-prices.ts
packages/api/src/types.ts
packages/sdk/src/coingecko/coingecko.ts

**Motivation**
https://app.shortcut.com/uma-project/story/5168/the-suint-kpi-option-is-showing-0-for-tvl-but-has-45k-uma-in-the-contract-https-polygonscan-com
**Summary**
Basically what I did was to identify the L2 ERC20 addresses for which CoinGecko didn't return a price and use the price of the corresponding mainnet address as fallback.
I also added an extra log to identify easily this issue
**Testing**

fix: fallback to mainnet prices for L2 ERC20 tokens

---

packages/sdk/src/coingecko/coingecko.ts

**Motivation**
The profitability calculator in across v2 will need to find contract prices by contract address on chains other than Ethereum. This PR extends the interface to accomidate this.
**Testing**

feat: add ability to define chains other than ethereum in  calls

---

packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/statemachines/disputePrice.ts
packages/sdk/src/oracle/services/statemachines/pollNewEvents.ts
packages/sdk/src/oracle/services/statemachines/proposePrice.ts
packages/sdk/src/oracle/store/write.ts
packages/sdk/src/oracle/types/ethers.ts
packages/sdk/src/oracle/utils.ts

**Motivation**
https://app.shortcut.com/uma-project/story/4883/have-the-app-refresh-more-frequently-so-the-state-of-proposals-is-more-accurately-reflected-without-the-user-needing-to-refresh
The index page was not updating correctly when sending proposal/deposits in detail page.
**Summary**
This strips events of transaction receipt when proposign/disputing and adds them to the internal event list and updates the index state.  also fixes potential bug where polling for new events was not working.
**Testing**
Tested this on kovan using already pending requests. tested proposal and dispute and both worked to update index page accordingly

fix(sdk): syncronize oo client index and details page

---

packages/sdk/src/oracle/README.md
packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/services/statemachines/fetchPastEvents.ts
packages/sdk/src/oracle/tests/utils.test.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/utils.ts

**Motivation**
Loading polygon requests are slow, since there are so many. 
**Summary**
This adds some levers to pull to change the performance characteristics of loading requests. You can now restrict the max block range, as well as the earliest block to ignore.
**Testing**
Tested this by playing with the OO UI locally and have seen a large speed up in performance with the right parameters.

fix(sdk): improve oracle data loading

---

packages/core/contracts/common/implementation/Lockable.sol
packages/core/contracts/oracle/implementation/OptimisticOracle.sol
packages/core/contracts/oracle/implementation/test/OptimisticRequesterTest.sol
packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
packages/core/test/oracle/OptimisticOracle.js

**Motivation**
We would like the OO to handle event-based requests.
Note: test changes are not included yet, as I wanted to nail down the contracts first.
**Summary**
Rather than create a new flavor of the OO, it seemed somewhat simple to add this feature to the existing OO using an additional boolean in the Request struct.
For non event-based requests, this should add a few branches, but cost no real additional gas. We could potentially make an optimization to how we measure the length of the stamped ancillary data to decrease gas costs for those requests.
Event-based queries will be more expensive. They will involve an additional call to the OO, and they will require a more costly ancillary data stamping/construction when calling into the DVM.
This is how the event-based process works: …

feat: add event based request path for OO

---

packages/sdk/build.js

**Motivation**
https://app.shortcut.com/uma-project/story/5250/adjust-the-sdk-build-script-to-not-use-fs-rmsync
**Summary**
I replaced the `rmSync` function call with functions that were added in older versions of NodeJS. The build script works now with NodeJS versions < v14.14
**Testing**

fix(sdk): replace rmSync for better compatibility

---

packages/core/contracts/oracle/interfaces/V1OptimisticOracleInterface.sol
packages/sdk/src/clients/optimisticOracle/client.ts

**Motivation**
We need to preserve the old interface to continue interacting with the deployed OO.
**Summary**
This adds a "V1" interface that should be used when interacting with the existing deployed OO. The SDK client was also updated.
**Testing**
**Issue(s)**
N/A

fix: add v1 OO interface for backcompat for downstream users

---

packages/monitors/src/OptimisticOracleContractMonitor.js

**Motivation**
#3891 didn't correctly update the checks for the Optimistic Oracle vs Skinny Optimistic Oracle.
**Summary**
This corrects the checks to correctly check for !== SkinnyOptimisticOracle rather than === OptimisticOracle (since there are multiple OptmisticOracle abis now).
**Testing**
**Issue(s)**
N/A

fix: fix OO bot

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts

Hotfix to split queries since there are now over 10k events.

fix: split l1 block queries at specific block

---

packages/core/contracts/oracle/implementation/OptimisticOracle.sol

**Motivation**
The OptimisticOracle contract includes the directive using AncillaryData for bytes ,
even though none of the library methods are ever used directly on a bytes value.
Consider removing the directive if it will remain unused.
**Summary**
Removed the directive.
**Testing**
**Issue(s)**
N/A

fix: [N12] Unused "using for" directive

---

packages/core/contracts/oracle/implementation/OptimisticOracle.sol
packages/core/contracts/zodiac/OptimisticGovernor.sol

**Motivation**
Throughout the OptimisticGovernor contract, to check if a proposal has been approved
by the Optimistic Oracle the literal value int256 1e18 is used, where 1e18 signifies that a
proposal was not rejected by the Optimistic Oracle.
Similarly, in the update to the OptimisticOracle contract the function proposedPrice
uses a magic value type(int256).min to indicate that an event-based proposal cannot be
resolved, because the event has not yet taken place.
Lastly, in the OptimisticOracle contract the MAX_ADDED_ANCILLARY_DATA constant is
declared on line 129. On the next line the constant should be used, but instead the value of the
constant is used directly to derive another constant.
To improve the overall readability of the codebase and to facilitate refactoring, consider …

fix: [N09] Unexplained and unused constants

---

packages/contract-notifier/README.md
packages/contract-notifier/index.js
packages/contract-notifier/src/ContractNotifier.js

**Motivation**
There are increasing number of LSP contract deployments on other chains than Ethereum mainnet that should be monitored for upcoming expirations.
**Summary**
Allows running `contract-notifier` against selected API endpoints for supported chains.
**Details**
Each instance of `contract-notifier` is expected to run against its configured `chainId` and corresponding `apiEndpoint`. Google Datastore already had `chainId` parameter, so no changes needed there.
**Testing**

feat(contract-notifier): add multichain support

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
Across v2 monitor requires to know information about a number of chains latest blocks and last blocks seen. This PR updates the hub to add addtional storage slots to enable this.
**Testing**

feat: extend serverless to contain more configs for multi-chain

---

packages/sdk/src/blockFinder.ts

**Motivation**
We're seeing bots break because of "undefined" blocks.
**Summary**
After running the debugger to get the state of the `this.blocks` array, I found that the this.blocks array was not sorted. This should be impossible since the elements are always inserted sorted and never removed.
After looking through the insertion points, I found this one, which computes the index, makes an async call, and then uses that index to insert the queried element. When this class is used concurrently, the state of this.blocks could have changed between the initiation of the async call and when it returns.
To avoid this, we need to recompute the index after the async call.
Note: it's hard to definitively say when this is fixed because the async scheduling is inherently chaotic. However, I will run …

fix: fix BlockFinder concurrency issue

---

packages/core/contracts/financial-templates/optimistic-distributor/OptimisticDistributor.sol
packages/core/test/financial-templates/optimistic-distributor/OptimisticDistributor.js

**Motivation**
Reward distribution could have been blocked if Optimistic Oracle upgrade is performed between proposal and execution.
**Summary**
This fix unblocks creating new proposals id Optimistic Oracle upgrade is detected.
**Details**
In case of Optimistic Oracle upgrade the proposal should be repeated and previous request should be settled manually through old Optimistic Oracle.
**Testing**
**Issue(s)**

fix(optimistic-distributor): handle optimistic oracle upgrades

---

packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
packages/sdk/src/across/feeCalculator.test.ts
packages/sdk/src/across/feeCalculator.ts

**Motivation**
[A change to UMIP-136](https://github.com/UMAprotocol/UMIPs/pull/515) will require that realized LP fee %'s are accurate to 6 decimals. This PR changes the fee calculator to always return realized LP fees to this precision.
**Summary**
Reviewers, there are two questions I have:
- Currently I am changing the precision of the realized LP fee % in the `sdk`, but I wonder if this should be lower at the client level?
- Does there exist a common function we can use to implement the precision change? I don't like manipulating the string as I am doing as it seems error prone.
**Testing**

feat: Round realized LP fee % to match UMIP

---

packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
packages/core/test/merkle-distributor/MerkleDistributor.js

**Motivation**
Paid out claims were not tracked correctly for batched claims.
**Summary**
`remainingAmount` is now reduced by the sum of batched claim amounts.
**Details**
Tests have been also modified to include the same recipient address for underfunded rewards set.
**Testing**

fix(merkle-distributor): tracking remainingAmount in claimMulti

---

packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
packages/financial-templates-lib/src/price-feed/InsuredBridgePriceFeed.ts

**Motivation**
Some nodes like Infura cannot return more than 10,000 events, and the default search for these clients is set to look up events for ALL of history
**Summary**
Sets a default page size for event queries. Note that `InsuredBridgePriceFeed.getHistoricalPrice` is not used in `insured-bridge-relayer` and its only used in the validation script `getHistoricalPrice`.
**Testing**

fix: Across V1 event clients need to use paginated event search query now that DepositRelayed has over 10,000 events

---

packages/financial-templates-lib/src/logger/SlackTransport.ts
packages/financial-templates-lib/test/logger/SlackTransport.splitByNewLine.js
packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js

Signed-off-by: kevinh@umaproject.org
**Motivation**
Currently the Slack transport logger only splits objects into several messages if the char limit is exceeded. This doesn't work for mrkdwn (Slack's version of Markdown) because it's a single string. Many bots use Mrkdwn to print reports and messages and their messages can get redacted if exceed the limit.
**Summary**
This PR adds logic to SlackTransport to split mrkdwn text into several Slack messages if exceed the limit.
**Testing**

feat(logger): Split long mrkdwn text into smaller chunks under Slack's 3000-char limit

---

packages/financial-templates-lib/src/logger/SlackTransport.ts
packages/financial-templates-lib/test/logger/SlackTransport.splitByNewLine.js

**Motivation**
When a multi-line message is broken into multiple messages to fit Slack's length limit, currently, the Slack transport logic would skip the first line of a new message. This issue is fixed in this PR.
Live test result: https://risklabs.slack.com/archives/C03GT3LE78E/p1656264890397689
**Testing**

fix(logger): Update slack transport logic to not skip one line when breaking a multi-line message into multiple messages

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts

**Motivation**
ETHDOM and USDTDOM need default price feed configs as they are used by LSP contracts.
**Summary**
Adds ETHDOM and USDTDOM pf configs to default price feed config file.
**Testing**

feat(pf-configs): Add default price feed configs for ETHDOM and USDTDOM

---

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts

**Motivation**
uSPAC10 price feed API is not available any more.
**Summary**
Remove `uSPAC10` from default price feed config
**Testing**
**Issue(s)**

fix(pf): remove uSPAC10 from default price feed config

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
This will allow the hub to have custom timeouts based on the scheduler that sends the request.
**Testing**
**Issue(s)**
N/A

feat: add request-level override for spoke rejection timeout

---

packages/sdk/src/clients/bridgeDepositBox/client.e2e.ts
packages/sdk/src/clients/bridgePool/client.e2e.ts
packages/sdk/src/clients/optimisticOracle/client.ts
packages/sdk/src/clients/rateModelStore/client.e2e.ts
packages/sdk/src/clients/skinnyOptimisticOracle/client.ts
packages/sdk/src/oracle/README.md
packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/factory.ts
packages/sdk/src/oracle/index.ts
packages/sdk/src/oracle/optimisticFactory.ts
packages/sdk/src/oracle/services/index.ts
packages/sdk/src/oracle/services/skinnyOptimisticOracle.ts
packages/sdk/src/oracle/services/sortedRequests.ts
packages/sdk/src/oracle/services/tests/skinnyOracle.e2e.ts
packages/sdk/src/oracle/services/update.ts
packages/sdk/src/oracle/skinnyFactory.ts
packages/sdk/src/oracle/store/read.ts
packages/sdk/src/oracle/store/write.ts
packages/sdk/src/oracle/types/interfaces.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/utils.ts

BREAKING CHANGE: instantiating oracle client now requires passing configs keyed by optimistic or skinny oracle types
**Motivation**
We want to add skinny oo to the oracle client
**Summary**
This makes the required changes to support the skinny oo, mainly this is adding the skinny stateful client and adding a new factory function to allow user to create clients of multiple types. docs are also updated.  THis is a breaking change, and changes are tested on the OO UI frontend, there will need to be a new PR on the FE to integrate these changes.
**Details**
**Testing**
Check a box to describe how you tested …

feat(sdk)!: add skinny oo client and separate factories

---

packages/financial-templates-lib/src/helpers/GasEstimator.ts
packages/fx-tunnel-relayer/src/Relayer.ts
packages/fx-tunnel-relayer/src/RelayerConfig.ts
packages/fx-tunnel-relayer/src/index.ts
packages/fx-tunnel-relayer/test/Relayer.ts
packages/fx-tunnel-relayer/test/index.ts

**Motivation**
Currently the lookback is constrained to be > 1-2 hours which isn't sufficient for the average Polygon-->L1 message time which is ~3 hours on average.
This PR also fixes a bug with the GasEstimator where maxPriorityFeePerGas > maxFeePerGas which is prevalent in legacy gas markets like Polygon where we just set `fastest` gas equal to max priority fee.
I used this code to finalize an L2 to L1 message thats about 20 hours old: https://etherscan.io/tx/0xc2109a95dedb085a4b85dc6e9a55e10a38231f3df07fb6630baccb3f90c2a9d5
**Testing**

improve: fx-tunnel-relayer should use paginated event search to increase lookback range

---

packages/core/contracts/oracle/implementation/Staker.sol
packages/core/test/oracle/Staker.ts

**Motivation**
We would like for users to be able to stake their rewards in a single transaction.
**Summary**
This adds a method to withdraw and stake rewards.
**Testing**
**Issue(s)**
N/A

feat(voting-v2): add method to withdraw and restake

---

packages/polymarket-notifier/src/polymarketNotifier.js

**Motivation**
Alerts are being sent daily for test markets that are not included in the Polymarket API. This PR prevents alerts for proposals that do not have pricing in the Polymarket API. The original logic was decided upon due to wanting alerts sent if the API is down, however, in that situation we have existing infrastructure alerts.
**Testing**

improve(polymarket-notifier): Remove undefined Polymarket alerts

---

packages/scripts/src/admin-proposals/adminChildRegistration.ts

**Motivation**
Add a script to register arbitrary contracts in Registry and Finder in non-rollup chains from the `AdminChild_Messenger`
**Summary**
Created a new script that runs the required transactions and receives as arguments the contract name and contract address to register
Example of transaction run in avalanche: https://dashboard.tenderly.co/tx/ava/0x8acd9cd97c17322a5dc552d9bbc2ee9af159a7111eb2f6b7b16d6f2c9323a06c
**Details**
**Testing**

feat: add script to register oo in side chains with admin child

---

packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/VotingV2.js

**Motivation**
```
The request processing logic within _updateAccountSlashingTrackers is not
able to correctly handle multiple rolled votes that appear sequentually in the request array.
```
**Summary**
To avoid adding more complexity to this logic, I implemented the simple change suggested by the audit.
```
A straightforward fix that sets requestIndex =
deletedRequests[requestIndex] on line 845 (remove the + 1 ) and then inserts a
continue statement. This would return execution back to line 843 where
requestIndex would be incremented as before, but ensures that the
deletedRequests[requestIndex] != 0 test on line 845 is applied to this new
index.
```
**Testing**
Check a box to describe how you tested these changes and list the steps …

fix: [H01] fixes duplicate request rewards

---

packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/SpamGuard.js

**Motivation**
Setting the spam deletion bond is retroactive and affects previously signalled bonds, resulting in refund inconsistencies.
```
If the owner mistakenly calls setSpamDeletionProposalBond between a spam deletion
request and its execution, the value of the refunded bond will differ from the originally
submitted bond, thereby leading to a loss for either the original requester or the VotingV2
contract.
```
**Summary**
As the auditors suggested, we added a bond attribute to the SpamDeletionRequest struct to keep track of bond values separately from changes to spamDeletionProposalBond.
**Testing**

fix: [M01] Incorrect refund of spamDeletionProposalBond

---

packages/core/contracts/oracle/implementation/DesignatedVotingV2.sol
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/DesignatedVotingV2.js

**Motivation**
*OZ identified the following issue:*
```
In order to submit a vote on a price request, the voter must construct an off-chain hash by
encoding the following data in order and then computing the keccak256 hash: price , salt ,
voterAddress , time , ancillaryData , currentRoundId , and identifier . This can
be seen in lines 559-563 of the VotingV2 contract's revealVote function, where the
contract constructs a reveal hash that should match the one that was committed:
require(
keccak256(abi.encodePacked(price, salt, msg.sender, time, ancillaryData,
currentRoundId, identifier)) ==
voteSubmission.commit,
"Revealed data != commit hash"
);
The structure of the commit hash is described in the docstrings of several functions within the
DesignatedVotingV2 and VotingV2 contracts. …
```

fix: [L04]: Incorrect documentation for voting commit hash

---

packages/core/contracts/oracle/implementation/DesignatedVotingV2.sol
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/DesignatedVotingV2.js

**Motivation**
```
In the DesignatedVotingV2 contract, the retrieveRewards function name suggests
that the caller will gain possession of the rewards; this assumption is further reinforced by the
docstring's description of the return value as "amount of rewards that the user should receive".
However, instead of transferring rewards to the user, the retrieveRewards function
restakes user's rewards.
To avoid confusion, consider renaming the retrieveRewards function to
withdrawAndRestakeRewards or some other name that more accurately describes its
behavior.
```
This PR implements the recomended changes.
**Testing**

fix: [L03]: Imprecise function name

---

packages/core/contracts/oracle/implementation/SlashingLibrary.sol

**Motivation**
*OZ identified the following optimization in code readability:*
```
Within the SlashingLibrary contract, the functions calcWrongVoteSlashPerToken
and calcNoVoteSlashPerToken both return a hard-coded value of 1600000000000000 .
Numeric literals with a large number of digits are more difficult to interpret, requiring the reader
or reviewer to count the number of digits to ensure correctness.
Solidity supports scientific notation representation for large values. Consider replacing these
integer values with their more compact equivalent representation 1.6e15 .
```
*This PR impelements the changes requested*
**Testing**

fix: [N21]: Too many digits in numeric literals

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
```
In the VotingV2 contract, the function executeSpamDeletion contains the magic value
1e18 which represents a successful vote in favor of a spam deletion request.
Using inline magic values hinders code legibility and increases the chance of introducing
erroneous values.
Consider assigning all magic values to descriptive constants and replacing all semantically
matching occurrences of the value with its respective constant.
```
*Changes implemented in this PR:*
Rather than using a const, as requested, I changed the check to be `resolutionPrice != 0`. This removes the magic number and is actually more correct as _any_ non-zero value is considered "yes" with governance actions, as can be seen …

fix: [N11]: Remove magic numbers

---

packages/core/contracts/oracle/implementation/Staker.sol

**Motivation**
*OZ identified the following issue:*
```
The withdrawRewards function in the Staker contract emits a WithdrawnRewards
event to log the minting of rewards tokens to the voter than called the function. However, the
event is emitted outside the if block that checks for a non-zero value of tokensToMint . If
no rewards are minted, the WithdrawnRewards event will be logged even though no state
change occurred, wasting gas and possibly leading to confusion.
Consider only emitted the WithdrawnRewards event when tokensToMint is not zero.
```
*This PR implements the following solution:*
Moving of this event back into the if/else block.
**Testing**

fix: [N05]: Remove redundant WithdrawnRewards event emission

---

packages/core/contracts/oracle/implementation/ProposerV2.sol

**Motivation**
*OZ identified the following issue*
```
The ProposalV2 contract erroneously imports Voting.sol instead of VotingV2.sol .
Currently, all function signatures used within ProposalV2 are available in both Voting.sol
and VotingV2.sol , thereby preventing any direct consequences.
Consider upgrading the import to VotingV2.sol for consistency.
```
*Solution implemented in this PR:*
Swapped the import of `Voting.sol` to `OracleAncillaryInterface.sol` which has the required interface for the correct function of `ProposerV2.sol`.
**Testing**
**Issue(s)**
Fixes #XXXX

fix: [N04]: Correction of Erroneous imports

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
*OZ identified the following issues:*
```
In the VotingV2 contract, lines 1136-1140 in the _priceRequestResolved function
perform the removal of an element from the pendingPriceRequests array. The
executeSpamDeletion function within the same contract re-implements this same code on
lines 1010-1016, with the only difference being that priceRequest has been replaced with
priceRequests[requestId] .
Consider moving this duplicated code into a new shared function.
```
*Solution presented in this PR*
The removal of pending price requests was refactored to use an internal method `_removeRequestFromPendingPriceRequests`.
**Testing**

fix: [N02]: Removal of redundant code

---

packages/core/contracts/oracle/implementation/DesignatedVotingV2Factory.sol

**Motivation**
*OZ identified the following issue:*
```
The DesignatedVotingV2Factory contract inherits from the Withdrawable contract, a
base contract which provides the ability to create a Withdraw role and assign it to one or more
addresses to grant them the ability to withdraw ETH or ERC20 tokens from the contract by
using the corresponding withdraw and withdrawErc20 functions.
The Withdrawable contract provides two functions for configuring this role,
_createWithdrawRole and setWithdrawRole , and the documentation for these
functions indicates that one or the other must be called by the derived contract
( DesignatedVotingV2Factory in this case) in order for withdraws to function properly.
However, the DesignatedVotingV2Factory contract does not call either function,
rendering the …
```

fix: [L10]: Withdraw role is not configured

---

packages/common/src/Constants.ts
packages/common/src/hardhat/fixtures/default.ts
packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
packages/core/contracts/financial-templates/optimistic-distributor/OptimisticDistributor.sol
packages/core/contracts/oracle/implementation/Constants.sol
packages/core/contracts/zodiac/OptimisticGovernor.sol
packages/core/test/financial-templates/long-short-pair/LongShortPair.js
packages/core/test/financial-templates/optimistic-distributor/OptimisticDistributor.js
packages/core/test/zodiac/OptimisticGovernor.js

**Motivation**
This PR shows how the OO v2 can be used with `LongShortPair`, `OptimisticDistributor` and `OptimisticGovernor` with minimal changes.
**Summary**
Only modification make to contracts is changing the import paths and type definition.
**Testing**

fix: Upgrade all dependent contracts to use the OOv2 and show they work in unit tests

---

packages/core/contracts/oracle/implementation/DesignatedVotingV2.sol
packages/core/contracts/oracle/implementation/SlashingLibrary.sol
packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
```
The code base contains multiple occurrences of misleading or incorrect documentation:
In the contract DesignatedVotingV2 , the comment on line 21 "Is also permanently
permissioned as the minter role" appears to be a copy & paste error as a minting
function is not part of the contract. Consider removing the comment.
```
*Changes implemented in this PR:*
Misleading comments were either fixed or removed (when not required).
**Testing**

fix: [N12]: Address Misleading documentation

---

packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/test/OptimisticOracleContractMonitor.js
packages/optimistic-oracle/test/index.js
packages/optimistic-oracle/test/proposerV2.js

**Motivation**
This PR updates the monitor, disputer and proposer bots to work with the OOv2.
**Summary**
Bot and test updated.
**Testing**

fix: Update the Monitor, proposer and disputer bots to work with OOv2 contracts

---

packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/VotingV2.js

**Motivation**
Note: this PR only fixes part of the issue that OZ found. The other portions of the issues did not require fixes, rather they required more explanation of how a migration might work.
```
The onlyRegisteredContract modifier allows forwarding price requests from the
contract deployed at migratedAddress to VotingV2 after migratedAddress has
been set, but the onlyIfNotMigrated modifier prevents anyone from voting on those
requests.
```
**Summary**
This PR does two things:
1. Disables all price request additions after migration.
2. Allows approved contracts to retrieve prices as necessary after migration, as restricting this is unnecessary if requesting new prices is disallowed.
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to …

fix: [M04] improve migration process

---

packages/sdk/src/clients/optimisticOracleV2/client.e2e.ts
packages/sdk/src/clients/optimisticOracleV2/client.ts
packages/sdk/src/oracle/optimisticFactory.ts
packages/sdk/src/oracle/optimisticV2Factory.ts
packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/optimisticOracleV2.ts
packages/sdk/src/oracle/services/skinnyOptimisticOracle.ts
packages/sdk/src/oracle/services/statemachines/setActiveRequestByTransaction.ts
packages/sdk/src/oracle/services/tests/skinnyOracle.e2e.ts
packages/sdk/src/oracle/skinnyFactory.ts
packages/sdk/src/oracle/tests/optimisticV2.e2e.ts
packages/sdk/src/oracle/types/interfaces.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/utils.ts

BREAKING CHANGE: oracle addresses are now required in configuration
**Motivation**
There were various issues we needed to correct in sdk:
1. optimistic oracle v2 is missing requestSettings on the request object
2. end to end client tests failing
3. hardcoded oracle addresses out of date, these are dangerous if not constantly maintained and should be explicitly specified by frontend client
**Summary**
There was a typo when including the oraclev2 client into the oraclev2 service, thats been corrected. All address lookups for oracle addresses have been removed. Oracle client e2e tests were fixed to run and a optimistic v2 test added for polygon. 
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to …

improve(sdk): fix abi issue, fix e2e tests, remove oracle addresses

---

packages/core/README.md
packages/core/contracts/common/implementation/MultiCaller.sol
packages/core/contracts/oracle/implementation/DesignatedVotingV2.sol
packages/core/contracts/oracle/implementation/GovernorV2.sol
packages/core/contracts/oracle/implementation/ProposerV2.sol
packages/core/contracts/oracle/implementation/SlashingLibrary.sol
packages/core/contracts/oracle/implementation/Staker.sol
packages/core/contracts/oracle/implementation/VoteTimingV2.sol
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/contracts/oracle/interfaces/VotingAncillaryInterface.sol

**Motivation**
*OZ identified the following issues:*
```
Consider addressing the following typographical errors:
In DesignatedVotingV2.sol :
line 54: "EG" should be "E.g."
line 71: "Eg:" should be "E.g."
line 72: "of for the price request" should be "of the price request"
line 75: "voters" should be "voter's"
line 89: "EG" should be "E.g."
In GovernorV2.sol :
line 98: "an an array" should be "an array"
In ProposerV2.sol :
line 115: "system, itself" should be "system itself"
In SlashingLibrary.sol :
line 59: Remove space before "wrongVoteSlashPerToken"
In Staker.sol :
line 13: "prorate" should be "pro rata"
line 53: "voterPendingUnStake" should be "voterPendingUnstake"
line 91: "prorate" should be "pro rata"
line 93: Remove erroneous comment line
line 111: "a active reveal" should be "an …
```

fix: [N22]: Fix Typographical errors

---

packages/sdk/src/clients/optimisticOracleV2/client.ts
packages/sdk/src/oracle/README.md
packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/optimisticOracleV2.ts
packages/sdk/src/oracle/tests/optimisticV2.e2e.ts
packages/sdk/src/oracle/types/interfaces.ts

BREAKING CHANGE: Request object shape has been modified to normalize v1 and v2 request data
**Motivation**
There were issues in the UI with failing transactions due to a missing bond amount on oo v2 requests. 
**Summary**
Turns out several fields on the v1 request were moved to the v2 request settings object.  These missing fields caused certain logic to be skipped leading to a bad UI state where you could propose before you approved or had insufficient balance. The solution was to create a normalized request object, flattening the data more like v1 which works with exsiting logic. 
**Testing**

fix(sdk)!: fix missing bond on oo v2 request

---

packages/core/contracts/zodiac/OptimisticGovernor.sol

Signed-off-by: Alex Gaines <againes@umaproject.org>
**Motivation**
This PR intends to fix an issue in the optimistic governor contract whereby it cannot be used as a mastercopy for a proxy because of how the re-entrancy guard is initialized. However, our previously audited version of the [Lockable](https://github.com/UMAprotocol/protocol/blob/master/packages/core/contracts/common/implementation/Lockable.sol) contract does allow derived contracts to update the _notEntered value.
Our original solution was to create an optimistic governor factory contract with this [PR](https://github.com/UMAprotocol/protocol/pull/4114), however, see the PR comments for rationale on why an update to the contract is more appealing.
**Summary**
In the `setup` method, `_startReentrantGuardDisabled()` is called …

fix(optimistic-governor): Optimistic Governor re-entrancy guard update

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol
packages/core/contracts/oracle/implementation/GovernorV2.sol
packages/core/contracts/oracle/implementation/test/EmergencyProposerTest.sol
packages/core/test/oracle/EmergencyProposer.js
packages/core/test/oracle/GovernorV2.js
packages/core/test/oracle/ProposerV2.js

**Motivation**
We'd like to have a system for emergency proposals in case the DVM breaks.
**Summary**
This adds an EmergencyProposer contract that mirrors the proposer contract, but can perform unilateral actions on the Governor without DVM approval.
**Testing**
**Issue(s)**
N/A

feat: add emergency proposer

---

packages/sdk/src/coingecko/coingecko.ts

**Motivation**
The Across v1 bots submit a single price request per ERC20 token. This
is suspected to cause sporadic rate-limiting by CoinGecko. I am testing
a change to consolidate the price requests, so that we have the option
of reducing our load on CoinGecko.
**Summary**
Modify the Result type definition to be less strict about the specific
field(s) that are returned by CoinGecko.
**Testing**
Check a box to describe how you tested these changes and list the
steps for reviewers to test.
Steps:
- SDK unit test.
- Ran the Across insured-bridge-relayer bot.

fix(coingecko): Remove getContractPrices usd constraint

---

packages/core/contracts/oracle/implementation/Staker.sol
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/contracts/oracle/implementation/test/ZeroedSlashingLibaryTest.sol
packages/core/test/oracle/VotingV2.js

**Motivation**
There is a known issue with slashing summing intra rolled round. in effect, if a staker stakes during an active reveal round and the vote rolls they can dodge slashing tracker updates. This PR implements a further refinement over the solution proposed in https://github.com/UMAprotocol/protocol/pull/4139
**Summary**
Solution: instead of  [PR4146](https://github.com/UMAprotocol/protocol/pull/4146/files) is modify the _getStartingIndexForStaker function to always subtract the pendingPriceRequests.length  regardless of whether the VotingV2 contract is in active reveal or not. This way each user has the ability to correctly roll (or settle) any pending price requests as necessary without having to add extra logic in commitVote to handle this scenario. There may be concerns about …

fix: wrong slashing sum

---

packages/sdk/src/clients/skinnyOptimisticOracle/client.ts
packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/optimisticOracleV2.ts
packages/sdk/src/oracle/services/skinnyOptimisticOracle.ts
packages/sdk/src/oracle/services/statemachines/setActiveRequestByTransaction.ts
packages/sdk/src/oracle/types/ethers.ts
packages/sdk/src/oracle/types/interfaces.ts

**Motivation**
1. Disputes are unable to be viewed in the OO UI using the url by transaction hash method.
2. Proposer tx hash missing from requests
**Summary**
Needed to update our oracle interface to include a way to parse logs from a transaction receipt. Previously we never changed the contract instance based on which oracle was in use (v1,v2 or skinny). This caused an issue when decoding skinny logs.  The fix was to add a function to decode logs in the oo interface and use it in our `setActiveRequestByTransaction` handler.
after this issue was fixed, a new one surfaced where trnasaction hashes were missing from request objects. this was an issue with decoding events and not copying over the previously decoded request object, thereby losing …

fix(sdk): fix failing lookup for skinny oo by tx hash

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol

**Motivation**
```
The EmergencyProposal contract is used to construct an emergency recovery transaction
that bypasses the standard voting process. The intention is to provide an alternate execution
path that can be utilized to fix an incorrectly configured VotingV2 contract.
Any user can propose an emergency transaction via the emergencyPropose function, but
the size of the required bond is expected to be large enough that it is unlikely that an individual
or the UMA team would be able to sufficiently fund the bond amount on their own. Proposals
are executed using the emergencyExecute function in the GovernorV2 contract. The
executor address has the sole ability to call this function, giving it veto power over any
proposal. The UMA team controls the …
```

fix: [L01]: Prevent the governor from proposing emergency actions

---

packages/core/contracts/umips/VotingUpgraderV2.sol

**Motivation**
```
The codebase contains several occurrences of misleading or incorrect documentation:
In the contract VotingUpgraderV2: - The comment on line 41 "Existing governor is the only one
who can initiate the upgrade" appears to be a copy & paste error from line 38 which is
identical. Consider rewriting the comment. - The comment on line 52 "Addresses to upgrade"
does not apply to the newVoting variable on line 53. Consider rewriting the comment. - The
comment on line 62 "Removes an address from the whitelist" does not apply to the
VotingUpgraderV2 constructor. Consider rewriting the comment.
```
PR implements the following change: All issues, as identified, were fixed.

fix: [N02]: Misleading documentation

---

packages/core/contracts/oracle/implementation/Staker.sol

**Motivation**
```
In the Staker contract, the functions setDelegate and setDelegator use the
nonReentrant modifier. This is not required as these two functions are only updating the
state and cannot be exploited through a reentrancy attack.
Consider removing the nonReentrant modifier from these functions.
```
This PR removes this modifier on these two functions.

fix: [N04]: Unnecessary modifier in setDelegate and setDelegator

---

packages/common/src/HardhatConfig.ts
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/package.json
packages/core/test/oracle/VotingV2.js
yarn.lock

**Motivation**
While testing the voting contract on Goerli, we found a very specific situation that cases price requests to become unresolvable. This is a bug in the Voting contract that we believe was missed in the audit.
If: a) a price request is made, b) the request rolls, c) the only participant who votes on the request was not staked before the request AND they staked during the reveal phase post roll then the request becomes unresolvable. If the request rolls again and someone who was staked before the request participates in the vote then it again becomes resolvable. 
The reason this happens is a subtle interplay between how the contract’s rolling logic works with staker’s account trackers. In particular, we consider the “starting index” that a staker is susceptible to slashing …

fix: DVM2.0 Address bug in rolling votes + having no active stakers participate

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol

**Motivation**
```
In the EmergencyProposer contract, the executeEmergencyProposal function has
public visibility. This is not required as the function is not called within the contract.
Consider changing the visibility of the executeEmergencyProposal function to
external.
```
**This PR updates the contracts, as requested**.

fix: [N10]: Unnecessary public visability in executeEmergencyProposal

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
OZ signaled:
```
Per the comment on _getPriceOrError , the string return value should be non-empty only when the function returns false . However, the additional logic to query prices from a previous voting contract via _getPriceFromPreviousVotingContract may return a non- empty string even when the price was successfully retrieved. Because the string message is only used in the error case, users will never see the "Returned from previous contract" string.
Consider returning an empty string when _getPriceOrError returns true .
```
**Summary**
Remove unnecessary non-empty string return value.
**Testing**

fix: [N09]  unnecessary non-empty return value on success

---

packages/core/contracts/oracle/implementation/test/EmergencyProposerTest.sol
packages/core/contracts/umips/VotingUpgrader.sol

**Motivation**
In the latest audit OZ signaled that the following contracts had an old pragma version:
- EmergencyProposerTest.sol
- VotingUpgraderV2.sol
**Summary**
Update the pragma version to `0.8.16` in the contracts listed above. 
**Testing**

fix: [L10] unlocked solidity version pragma

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol

**Motivation**
In the last audit OZ signaled:
```
In the EmergencyProposal contract, the executeEmergencyProposal function iterates through the transactions submitted 
on the proposal and executes them. However, only the first element in the array is able to execute a payable transaction,
as the first element of the proposed transactions will transfer the entirety of the contract ETH balance, meaning that 
subsequent transactions will have a value of zero.
Consider documenting this behavior thoroughly as it may not be obvious or intuitive to the proposal submitter.
```
**Summary**
Improve `executeEmergencyProposal` & `emergencyPropose` to clarify how the transactions execution work
**Testing**
Check a box to describe how you tested …

fix: [L08]: improve executeEmergencyProposal docstring

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
OZ signaled in the audit some missing `onlyIfNotMigrated`  modifiers :
```
The modifier onlyIfNotMigrated and its underlying private function _requireNotMigrated are used to ensure that the voting contract being called is the most recent voting contract deployed. 
This prevents users from requesting prices and voting on price requests on an outdated voting contract. However, onlyIfNotMigrated is missing from the functions requestGovernanceAction and signalRequestsAsSpamForDeletion .
Both of these functions will call _requestPrice , which initiates a new price request. Consequently, users will not be able to vote on this request due to the onlyIfNotMigrated modifier being present on commitVote , and could potentially be …
```

fix: [L06]: add missing onlyIfNotMigrated modifiers

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
OZ signaled:
```
In the VotingV2 contract, the function _getPriceFromPreviousVotingContract allows the current voting contract to query and retrieve prices from a previous voting contract. However, the function is defined with public visibility. As a result, this function can be directly called and could be used to bypass the _requireRegisteredContract check used by the onlyRegisteredContract modifier on hasPrice and getPrice . This would unintentionally allow users to access price details from a previous voting contract.
Consider changing the visibility of _getPriceFromPreviousVotingContract from public to private.
```
**Summary**
Change _getPriceFromPreviousVotingContract visibility to private
**Details**
This may be …

fix: [L02]: _getPriceFromPreviousVotingContract function visibility

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol
packages/core/test/oracle/EmergencyProposer.js

**Motivation**
OZ signaled the following issue:
```
The setQuorum function does not validate the size of the bond relative to the supply of the token used for the quorum value. In the case that the quorum is mistakenly set to be larger than the total token supply, no emergency proposal could be created.
The setMinimumWaitTime function does not validate that the newMinimumWaitTime is within a reasonable time frame. In the case that minimumWaitTime is mistakenly set to be a large interval consisting of multiple months or even years, no emergency proposal would pass until the time frame could expire.
```
**Summary**
Add extra validation in quorum and wait minimum time setters.
**Details**
This may be unnecessary for some PRs. Catch-all …

fix: [M01]: quorum and wait time validation in setters

---

packages/core/test/oracle/EmergencyProposer.js

**Motivation**
```
In the EmergencyProposer contract, the following events all contain a uint256
lockedTokens parameter:
EmergencyProposalRemoved
EmergencyProposalSlashed
EmergencyProposalExecuted
In each case, when these events are emitted, the value of lockedTokens will always be zero,
which effectively provides no information because the value never changes.
```
**Solution:**
This Pr makes no changes to the contract code as we belive this issue is wrong. This PR shows in unit tests how the `lockedTokens` param is non-zero.

fix: [N06]: Redundant event parameters

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol
packages/core/contracts/oracle/implementation/Staker.sol
packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
OZ signaled that some functions were missing docstrings:
```
In PR #4110:
• The _stakeTo function in the Staker contract has no docstring In PR #4118:
• The _previousVotingContract parameter has no corresponding @param line in the VotingV2 constructor docstring
• The _getPriceFromPreviousVotingContract function in VotingV2 has no docstring
In PR #4128:
• The emergencyPropose function in EmergencyProposer returns a value but its
docstring has no corresponding @return line 
In PR #4135:
• The retrieveRewardsOnMigratedVotingContract function in VotingV2 returns a value but its docstring has no corresponding @return line
```
Oz also pointed out the following functions but it has been decided not to add docstring in the test …

fix: [L04]: add missing docstrings

---

packages/core/contracts/oracle/implementation/EmergencyProposer.sol
packages/core/contracts/umips/VotingUpgraderV2.sol

**Motivation**
OZ identified the following issues before providing the final audit feedback:
```
small typo in #4151 - "cant"
Also in #4159 it looks like VotingUpgrader.sol was changed instead of VotingUpgraderV2.sol
In #4152 there is still an issue with the line "Addresses to upgrade..." b/c it says "addresses" plural, not "address" singular
```
This PR addresses the 3 issues identified.

fix: [post-audit-feedback]: Address typos and small issues identified before getting full audit feedback

---

packages/serverless-orchestration/src/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessHub.js

**Motivation**
We want to create multiple sizes for spoke pool hardware and configure this from the hub. This will help lower gcp costs.
**Summary**
Add a backward compatible change. env var `SPOKE_URLS` which must be specified as an object keyed by `name` and a value of the spokes url.  This is an optional argument.  To utilize this in the bot, specify in the confige `spokeUrlName` which must match the `name` key in the `SPOKE_URLS` env var.
example:
```js
// in a bot config
{
"environmentVariables": {
SPOKE_URLS={"small":"url to small spokes","large":"url to large spokes"}
},
spokeUrlName:"small",
}
```
**Testing**

feat(serverless): add ability to specify labeled spoke urls

---

packages/core/networks/5.json

**Motivation**
During my tests in the previous deployment, I accidentally allowed the pricing request with index 0 to roll; this prevents the slashing mechanism from performing properly and must be avoided. For this reason I have had to deploy a new contract.
In this last deployment I have deployed with the starting request index argument greater than zero, this prevents the above problem from occurring. This also ensures that in the mainnet deployment we are safe from these problems. 
**Summary**
Deployed new voting v2 contract
**Details**
**Testing**
Check a box to describe how you tested these …

fix: add new voting v2 address goerli

---

packages/common/src/hardhat/tasks/artifacts.ts

**Motivation**
Allow users to get addresses without async calls in contracts-node.
**Summary**
To allow users to access addresses without an async call, this exports the get[name]StaticAddress() function to avoid hardhat resolution.
**Testing**
**Issue(s)**
N/A

feat: export get[name]StaticAddress() from contracts-node

---

packages/core/contracts/oracle/implementation/Staker.sol
packages/core/contracts/oracle/implementation/VotingV2.sol
packages/core/test/oracle/VotingV2.js

**Motivation**
I have found residual mentions of the concept of active stake that got unnoticed in the latest changes.
Additionally, because we are approaching the bytecode limit for deployment and `allowUnlimitedContractSize` is enabled, I've included a test in VotingV2 to prevent modifications from going beyond the limit unintentionally.
**Summary**
- Refactor: rename variables
- Add bytecode limit test
**Testing**

fix: residual active stake naming

---

packages/scripts/src/upgrade-tests/voting2/0_Deploy.ts
packages/scripts/src/upgrade-tests/voting2/1_Propose.ts
packages/scripts/src/upgrade-tests/voting2/2_Verify.ts

**Motivation**
During my latest tests I realised that the upgrade process was missing the transfer of the owner role of the Voting Token to the new GovernorV2.
We did transfer the old Governor ownership to the GovernorV2 so this situation could have been recoverable but it's obviously a problem that we need to fix and we address in this PR.
Additionally, in the current state, after the migration to the GovernorV2 and VotingV2, the GovernorV2 roles are set like this:
`GovernorV2.Roles.Owner`: `deployer_address` (Used when running [0_Deploy.ts](https://github.com/UMAprotocol/protocol/blob/67df04f9ccaeed055e123485db1bd235d591cd96/packages/scripts/src/upgrade-tests/voting2/0_Deploy.ts))
`GovernorV2.Roles.Proposer`: `deployer_address` (Used …

fix: add missing transfer of voting token

---

packages/financial-templates-lib/src/logger/Formatters.ts
packages/financial-templates-lib/test/logger/BigNumberFormatter.js

**Motivation**
The logger is currently modifying objects that are passed to it when it contains a BigNumber or BN.
**Summary**
This change updates the logger to detect when a nested value has changed and then copying all containing objects recursively.
**Details**
**Testing**
**Issue(s)**
N/A

fix: copy logs when changing BNs to strings

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
Some multichain bots use NODE_URLS_ exclusively env variables for an array of node urls rather than NODE_URL_. It would simplify configs if the hub was able to pick up both rather than only supporting NODE_URL_.
**Summary**
Adds NODE_URLS_ support to the hub.
**Testing**
**Issue(s)**
N/A

feat(serverless-hub): hub should respect NODE_URLS_ env vars

---

packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
#4201 broke the Hub in the serverless orchestration package.
**Summary**
This fixes that code by reading the array directly rather than assuming the value is a JSON field.
**Testing**
**Issue(s)**
N/A

fix: fix JSON assumption in #4201

---

packages/scripts/src/upgrade-tests/voting2/2_Verify.ts
packages/scripts/src/upgrade-tests/voting2/3_SimulateVoting.ts
packages/scripts/src/upgrade-tests/voting2/readme.md

**Motivation**
As part of DVMv2 upgrade testing make sure that new contracts are functional.
**Summary**
Additional vote simulation checks that it is possible to stake/unstake, claim rewards and resolve regular price requests in DVMv2.
**Details**
- 3 voter accounts are funded with each one below GAT and every two exceeding GAT
- 3 Voters stake UMA
- Requester initiates regular data request through Optimistic Oracle
- Price request is not resolved due to only 1 voter participating
- All voters unstake, claim rewards and restake
- Verify rewards are correct
- Requester initiates second data request
- Price is resolved on both requests and available to requester
- Verify slashing is applied correctly and unstake all UMA
**Testing**
Check a box to describe how you tested these changes and …

feat(scripts): Add vote simulation in upgraded DVMv2

---

.circleci/config.yml
ci/tests/test-financial-templates-lib.sh
ci/tests/test-liquidator.sh
ci/tests/test-not-required.sh
ci/tests/test-packages.sh
ci/tests/test-required.sh

**Motivation**
[Node LTS version](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-10-25-version-18120-hydrogen-lts-ruyadorno-and-rafaelgss) changed recently, and some packages still using old LTS. Version is now fixed on code.
Signed-off-by: Evaldo Felipe [contato@evaldofelipe.com](mailto:contato@evaldofelipe.com)
**Testing**

Fix(CI): Change node version

---

packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
packages/core/contracts/merkle-distributor/implementation/MerkleDistributorInterface.sol

feat(merkle-distributor): Make overridable functions public

---

packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/OwnerUnplugSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol

**Motivation**
To reduce complexity and avoid race conditions check to use DVM as Oracle only at assertion time.
**Summary**
Moves check on which Oracle to use (DVM or SMM) at assertion time.
**Details**
This also made `setUnplugOnAssertionId` redundant as it should not be effective after assertion is made.
**Testing**

feat(core): oa check dvm as oracle at assertion

---

packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Lifecycle.t.sol

**Motivation**
Proposer address was not stored when not provided explicitly.
**Summary**
Store msg.sender when zero address passed as proposer.
**Details**
Also added tests for expected event logs.
**Testing**

fix(core) address oa proposer address bug

---

packages/core/contracts/oracle/implementation/VotingV2.sol

**Motivation**
Fixes the bug identified in https://github.com/UMAprotocol/protocol/pull/4210
**Summary**
Calculate the `nextIndexToProcess` to be utilised during `_updateAccountSlashingTrackers()` based on whether the `voterAddress` has never staked or has already staked. This method prevents the problem in which non-staked users might enqueue empty requests to `priceRequestsIds`
**Testing**

fix: price request index bug

---

packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistCallerSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistProposerSovereignSecurityManager.sol
packages/core/test/foundry/optimistic-assertor/Common.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistCallerSovereignSecurityManager.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistProposerSovereignSecurityManager.t.sol

**Motivation**
Users of Optimistic Asserter might want to allow only whitelisted proposers.
**Summary**
Adds whitelisted proposer checking Sovereign Security Manager.
**Details**
Owner of SSM should also register expected requesting contract as it is supposed to correctly pass its `msg.sender` as `proposer` field when calling `assertTruthFor`.
**Testing**

feat(core): add whitelist proposer ssm

---

packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/OwnerDiscardOracleSovereignSecurityManager.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/OwnerDiscardOracleSovereignSecurityManager.t.sol

**Motivation**
Users of Optimistic Assertor might want to discard Oracle result on disputes.
**Summary**
Adds Sovereign Security Manager where its owner can control whether disputed assertions can still be resolved as true via Oracle arbitration or Optimistic Asserter uses resolved answer only for bond settlement.
**Testing**

feat(core): implement ssm able to discard disputed assertions

---

packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/SuperbondSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistCallerSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistProposerSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
packages/core/test/foundry/optimistic-assertor/Common.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.EdgeCases.t.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.Events.t.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.Lifecycle.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/SuperbondOracleSovereignSecurityManager.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistCallerSovereignSecurityManager.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistProposerSovereignSecurityManager.t.sol

**Motivation**
Some applications might need assertion rules defined in their custom price identifier.
**Summary**
Adds ability to pass custom price identifier for the assertion.
**Details**
This also moves `sovereignSecurityManager` and `assertingCaller` under `ssmSettings` properties to avoid stack too deep error.
**Testing**

feat(core): add custom price identifier to oa

---

packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
packages/core/contracts/optimistic-assertor/implementation/examples/Insurance.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistCallerSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistProposerSovereignSecurityManager.sol
packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
packages/core/test/foundry/optimistic-assertor/Common.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.EdgeCases.t.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.Events.t.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.Lifecycle.t.sol
packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistCallerSovereignSecurityManager.t.sol
packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistProposerSovereignSecurityManager.t.sol

**Motivation**
Optimistic Asserter custom price identifier was added in #4254, but was merged in non-master branch.
**Summary**
Adds custom price identifier to Optimistic Asserter master branch.
**Details**
Originally #4254 was opened against [reinis-frp/superbond-ssm](https://github.com/UMAprotocol/protocol/tree/reinis-frp/superbond-ssm) in order to ensure stack too deep errors would be avoided also after #4244 will get merged.
**Testing**

feat(core): add custom price identifier to oa (master)

---

packages/sdk/src/oracle/README.md
packages/sdk/src/oracle/client.ts
packages/sdk/src/oracle/services/optimisticOracle.ts
packages/sdk/src/oracle/services/skinnyOptimisticOracle.ts
packages/sdk/src/oracle/services/statemachines/fetchEventBased.ts
packages/sdk/src/oracle/services/statemachines/index.ts
packages/sdk/src/oracle/services/statemachines/statemachine.ts
packages/sdk/src/oracle/types/state.ts
packages/sdk/src/oracle/types/statemachine.ts

**Motivation**
We need the ability to know if requests have event based expiry in the OO app index page. Currently the index page lists requests based on events, which do not include the event based expiry data. 
**Summary**
This adds a polling command which searches for any requests without event based expiry data, and makes a request to teh contract to fetch it if it doesnt exist. Previously this would only be fetched once a user selected the request and navigated to detail page. 
**Details**
**Testing**
This …

feat: add event based fetching for all requests

---

packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol

**Motivation**
Some Sovereign Security implementations might want to apply policies per unique claim (e.g. if there is another assertion after dispute).
**Summary**
Stores hashed claim as `claimId` in `Assertion` struct that that can be accessed in `readAssertion` method.
**Testing**

feat(core): store claimId in oa

---

packages/core/contracts/optimistic-assertor/implementation/examples/DataAsserter.sol
packages/core/test/foundry/optimistic-assertor/examples/DataAsserter.t.sol

**Motivation**
This contract allows assertions on any form of data to be made using the UMA Optimistic Assertor and stores the
proposed value so that it may be retrieved on chain. It only enables one assertion per pair of dataId and asserter
address. The dataId is intended to be an arbitrary value that uniquely identifies a specific piece of information in
the consuming contract and is replaceable. Similarly, any data structure can be used to replace the asserted data.
**Summary**
- `DataAsserter` contract
- Tests
**Testing**

feat: data asserter contract

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
packages/core/test/foundry/optimistic-asserter/Common.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.EdgeCases.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Lifecycle.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Ownership.t.sol

**Motivation**
We need to be able to set the burned bond percentage
**Summary**
- Add only owner burned percentage setter
- Add tests
**Testing**
**Issue(s)**
Fixes #XXXX

feat: add setter for burned bond percentage

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
packages/core/test/foundry/optimistic-asserter/Common.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Lifecycle.t.sol

**Motivation**
This PR adds some additional refinements on the OA. In particular:
- change aoRequester oaAsserter in _stampAssertion
- change address(this) to asserter in stampAssertion
- get rid of proposer prop in getId
- add caller address(msg.sender) to the AssertionMade event.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX

feat: continue adding small OA refinements

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicies.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicy.t.sol

**Motivation**
This PR refines how bond burning works when disputes are settled when working with the a OA in disconnected SSM mode.
**Summary**
If an assertion is set to not use the DVM for resolution then there should be no bond burning. This PR adds this logic.

feat: further refine OA bonds under disputes

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/BaseSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/OwnerDiscardOracleSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/OwnerSelectOracleSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/WhitelistAsserterSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/WhitelistCallerSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/implementation/sovereign-security/WhitelistDisputerSovereignSecurity.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
packages/core/contracts/optimistic-asserter/interfaces/SovereignSecurityInterface.sol
packages/core/test/foundry/optimistic-asserter/Common.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicy.t.sol
packages/core/test/foundry/optimistic-asserter/SovereignSecurity/BaseSovereignSecurity.t.sol
packages/core/test/foundry/optimistic-asserter/SovereignSecurity/OwnerDiscardOracleSovereignSecurity.t.sol
packages/core/test/foundry/optimistic-asserter/SovereignSecurity/OwnerSelectOracleSovereignSecurity.t.sol
packages/core/test/foundry/optimistic-asserter/SovereignSecurity/WhitelistAsserterSovereignSecurity.t.sol
packages/core/test/foundry/optimistic-asserter/SovereignSecurity/WhitelistCallerSovereignSecurity.t.sol

**Motivation**
Reduce Optimistic Asserter gas costs.
**Summary**
Changes Sovereign Security policy property names so that default values are false.
**Testing**

feat(core): default false ss policy properties

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/BaseEscalationManager.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/DisputeLimitingEscalationManager.sol
packages/core/contracts/optimistic-asserter/implementation/examples/DataAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/examples/Insurance.sol
packages/core/contracts/optimistic-asserter/implementation/examples/PredictionMarket.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterCallbackRecipientInterface.sol
packages/core/test/foundry/optimistic-asserter/Common.sol
packages/core/test/foundry/optimistic-asserter/EscalationManager/DisputeLimitingEscalationManager.t.sol
packages/core/test/foundry/optimistic-asserter/EscalationManager/WhitelistCallerEscalationManager.t.sol
packages/core/test/foundry/optimistic-asserter/examples/PredictionMarket.Assertion.t.sol
packages/core/test/foundry/optimistic-asserter/examples/PredictionMarket.Resolve.t.sol

**Motivation**
Demonstrate use of dispute callbacks in Escalation Manager.
**Summary**
This Escalation Manager blocks all assertions till the blocking dispute is resolved by Oracle.
**Details**
In order to avoid interference among different applications this Escalation Manager allows assertions only from one requesting contract.
**Testing**

feat(core): implement dispute limiting escalation manager

---

packages/core/contracts/optimistic-asserter/implementation/ClaimData.sol
packages/core/contracts/optimistic-asserter/implementation/examples/DataAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/examples/Insurance.sol
packages/core/contracts/optimistic-asserter/implementation/examples/PredictionMarket.sol

**Motivation**
Usage of AncillaryData library naming in example client contracts would be confusing.
**Summary**
Imports and renames AncillaryData as ClaimData library that can be imported by requesting contracts when manipulating claim bytes data.
**Details**
Optimistic Asserter still uses original AncillaryData library as it does so only in the context of constructing ancillary data when making Oracle request.
**Testing**

feat(core): use renamed claimdata library in oa

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Lifecycle.t.sol

**Motivation**
We should have additional props in assertionIds to avoid collisions. This PR adds both the caller and the block timestamp to the calling ID.

feat: add additional props to assertionId

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
packages/core/test/foundry/optimistic-asserter/Common.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Lifecycle.t.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicy.t.sol

**Motivation**
Method is more useful when the caller can pass the asserter in.
**Summary**
Added an asserter argument to assertTruthWithDefaults.
**Testing**
**Issue(s)**
Fixes #XXXX

feat: add asserter argument to assertTruthWithDefaults

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/FullPolicyEscalationManager.sol

**Motivation**
```
Consider fixing the following docstrings and inline comments:
In OptimisticAsserter.sol , the comment on line 88 claims the caller is the
asserter, but that is not necessarily true.
In FullPolicyEscalationManager.sol , comments on line 161, line 171, and line
180 for the respective setDisputeCallerInWhitelist ,
setWhitelistedAssertingCallers , and setWhitelistedAsserters functions
state "Adds a ... to the whitelist". In reality, the functions can both add and remove from
the whitelists.
```
This PR addresses these issues by fixing the comments.

fix[OA-audit-L03]: Address erronous docstrings and comments

---

packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol

**Motivation**
OZ identified the following issues:
```
The argument to the getMinimumBond function in the OptimisticAsserterInterface
interface is named currencyAddress , but it is named currency in the
OptimisticAsserter contract on line 358.
For clarity, consider renaming one of the arguments so the interface matches the
implementation.
```
This PR addresses this by implementing the change requested.

fix[OA-audit-N05]: Address argument name mismatches between interface and implementation

---

packages/core/contracts/common/implementation/MultiCaller.sol

**Motivation**
OZ identifies the following issue: 
```
The multicall function of the MultiCaller contract is declared payable but does not
accept any ETH. In the interest of clarity, consider removing the payable keyword.
```
This PR updates the multicaller contract to remove both the require and the payable keyword.

fix[OA-audit-N08]: Fix address multicaller payability

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol

**Motivation**
```
The _isDisputeAllowed function in the OptimisticAsserter contract may call
isDisputeAllowed on an optional EscalationManagerInterface contract. In
practice, the policy is to not validate disputers when no escalation manager is specified, so the
function will exit early instead of invoking a function on the zero address.
Nevertheless, in the interest of local reasoning, consider adding a zero-address check on the
em address prior to using it to make external function calls. Also consider swapping line 449
and line 450 so that the em address assignment is only made when this variable is required.
```
**Summary**
Add non-zero address check and return early

fix[OA-audit-N09]: Missing check for non-zero address

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol

**Motivation**
```
Below is a list of functions that have public visibility that can be limited to external visibility in the OptimisticAsserter contract:
- assertTruthWithDefaults
- disputeAssertion
- settleAndGetAssertionResult
```
This PR addresses the above issue by changing the visibility of these functions to external.

fix[OA-audit-N11]: Declare functions as external

---

packages/core/contracts/optimistic-asserter/interfaces/EscalationManagerInterface.sol

**Motivation**
```
In EscalationManagerInterface.sol , the import OptimisticAsserterInterface.sol is unused and could be removed.
```
This PR addresses the above issue by removing the unused import.

fix[OA-audit-N13]: Remove unused import

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol

**Motivation**
```
Within the OptimisticAsserter contract, named return variables are used inconsistently.
```
This PR addresses the above issue by removing the unused named return variables.
Note that `assertTruth` still has to keep named return variable in order to avoid stack too deep error.

fix[OA-audit-N14]: Consistent use of named return variables

---

.gitmodules
packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/BaseEscalationManager.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/FullPolicyEscalationManager.sol

**Motivation**
```
Consider addressing the following instances of redundant code within the codebase:
- The override keyword can be removed from all functions in the BaseEscalationManager contract.
- Consider deduplicating this code by creating a shared getRequestId function. Additionally, consider making this function publicly available for user convenience.
- Within the FullPolicyEscalationManger contract, the require statement in the configureEscalationManager function can be simplified
- Consider modifying the existing _getEscalationManager function to return an address type, and using it in all the identified locations other than line 435 to perform the escalationManager lookup
- In the _callbackOnAssertionResolve and _callbackOnAssertionDispute …
```

fix[OA-audit-N10]: Fix redundant code

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/contracts/optimistic-asserter/implementation/escalation-manager/FullPolicyEscalationManager.sol

**Motivation**
```
The OptimisticAsserter and FullPolicyEscalationManager contracts use the
constant value 1e18 in the settleAssertion and getPrice functions without
documenting the value's meaning.
Literal values in the codebase without an explained meaning make the code harder to
understand and maintain, thus hindering the experience of developers, auditors, and external
contributors alike. To improve the code's readability and facilitate refactoring, consider defining
a constant for every magic number, giving it a clear and self-explanatory name.
```
**Summary**
Add constant variable representing the numerical true value

fix[OA-audit-N15]: Use of magic numbers

---

packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicy.t.sol
packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.Arbitrate.t.sol

**Motivation**
```
While the existing design allows the DVM to collect a fee for providing oracle services, it does not allow an escalation manager to collect any fee to cover its potential cost for providing the same service.
```
With this PR the oracle fee is always paid to UMA Store, even when dispute is arbitrated via the escalation manager.
Note that this does not follow suggestion in the audit report because switching to arbitrate via the escalation manager is designed only as a fallback mechanism when there are risks of DVM corruption.
Also the prior mechanism to not pay oracle fees when arbitrating via the escalation manager could potentially pose escalation manager to spam attacks, thus dispute should always have the oracle fee.

fix[OA-audit-N03]: Always send oracle fee to the Store

---

packages/common/src/TimeUtils.ts
packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
packages/financial-templates-lib/test/price-feed/utils.js
packages/sdk/src/blockFinder.ts
packages/sdk/src/utils.ts

The `BlockFinder` is faster if there is an approximate average time estimate for a chain, and these chains were missing.

improve: Update blockfinder to be faster for chains with new average time estimates: {10, 288, 42161}

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
```
In VotingV2.sol, the comment on line 1251 should be "Gas optimized uint64 increment."
```
This PR fixes the issue mentioned.

fix[DVM2.0-audit-L03]: Fix erroneous comment

---

packages/core/contracts/data-verification-mechanism/implementation/EmergencyProposer.sol
packages/core/test/hardhat/data-verification-mechanism/EmergencyProposer.js

**Motivation**
```
In the emergencyPropose function in the EmergencyProposer contract, a lack of input
validation allows for proposals to be created that contain no transactions.
```
This PR addresses this issue by adding a check that ensures the length of the transactions input array is not zero.

fix[DVM2.0-audit-N01]: Add input validation to EmergencyProposer

---

packages/core/contracts/data-verification-mechanism/implementation/EmergencyProposer.sol
packages/core/test/hardhat/data-verification-mechanism/EmergencyProposer.js

**Motivation**
```
In the EmergencyProposer contract, after a proposal has expired, slashing or executing a
proposal can be front-run by the proposer (or executor) by calling removeProposal . Since
an emergency proposal can be created by anyone so long as they have the required bond, this
could allow a malicious actor to create a necessary emergency proposal only to front-run
execution of the proposal by removing it. A new proposal would then need to be created and
would not be able to be executed until minimumWaitTime has passed.
Consider only allowing the owner or executor to remove proposals after they have expired
to prevent such an attack.
```
This PR addresses this by implementing the recomended change.

fix[DVM2.0-audit-L02]: Emergency proposal execution can be front-run by proposer

---

packages/core/contracts/data-verification-mechanism/implementation/test/PunitiveSlashingLibraryTest.sol
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

Motivation
```
When users add or remove stake, the global cumulativeStake value is updated
accordingly. When applying slash rewards or penalties, the cumulative stake is not updated.
This is because slashing transfers stake between users, so the total slash amounts should sum
to zero.
However, a user cannot be slashed more than their stake, so a penalty that would reduce the
stake to negative is implicitly reduced. This undermines the balance between total slash
penalties and total slash rewards. Consequently, the total user stake will exceed the
cumulativeStake parameter, and too many rewards will be issued.
Consider increasing the cumulativeStake accordingly whenever slash penalties are
reduced. It's worth noting that this correction only applies when …
```

fix[DVM2.0-audit-M02]: Incorrect rewards released

---

packages/core/contracts/data-verification-mechanism/implementation/ResultComputationV2.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/contracts/data-verification-mechanism/interfaces/VotingV2Interface.sol
packages/core/deploy/052_deploy_votingV2.js
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

**Motivation**
The PAT, which was recently introduced, makes the incentives far better for those who want to intentionally roll/delete a vote in the case of spam or to prolong the voting period/gather more information.
However, a small caveat of the PAT is that it creates a two-tiered resolution system, where a certain quorum of voters need to agree to resolve a vote, but if many voters sit out because they intend to roll the vote, the threshold for _agreeing_ on an outcome becomes as small as half of that quorum. The intention of this PR is to make a slight modification to the PAT to make the incentives simpler and stronger in cases of high controversy over rolls/spam.
The SPAT (Schelling Point Activation Threshold) is simply a percentage of staked tokens that _must_ agree on the outcome …

feat: [Proposal] Change PAT -> SPAT

---

.gitmodules
packages/core/test/hardhat/merkle-distributor/MerkleDistributor.js
yarn.lock

Current tests import MerkleTree from @uma/merkle-distrbutor which is a deprecated package. This PR imports MerkleTree from @uma/common and uses the latest MerkleTree class

fix: Fix MerkleDistributor unit tests

---

scripts/run_release.sh

**Motivation**
We had to rotate our circleci secrets due to [this security alert](https://circleci.com/blog/january-4-2023-security-alert/). After the rotation, our npm publishing process broke due to [this issue](https://github.com/lerna/lerna/issues/2788) with newer npm tokens.
**Summary**
This fixes our npm publish process to work with recently generated keys. The previous logic (unintentionally) depended on the keys being of some sort of legacy type that worked with lerna's internal pre-checks.
Note: I tested this locally by generating a new key, verifying the old logic failed, fixing with this flag, and then successfully running the release that was previously failing.
**Testing** …

fix: fix release process for new npm token types

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/contracts/data-verification-mechanism/interfaces/VotingV2Interface.sol
packages/core/test/foundry/data-verification-mechanism/fork-tests/CommonDataVerificationMechanismForkTest.sol
packages/core/test/foundry/data-verification-mechanism/fork-tests/FakeLifeCycle.ft.sol
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

**Motivation**
Add "post update" function versions of some view external functions in the VotingV2 contract to simplify the access to the price requests information after [processing resolvable price requests](https://github.com/UMAprotocol/protocol/blob/9c55f013d23dc04780c0222788b2fa347ec29a17/packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol#L716).
**Summary**
- Add again the `getPendingRequests` and `getPendingRequestsPostUpdate`
- Group getNumberOfPendingPriceRequests and getNumberOfResolvedPriceRequests into getNumberOfRequests + add the “processed” version getNumberOfRequestsPostUpdate
**Details**
This may be unnecessary for some PRs. Catch-all for detailed explanations about the implementation …

feat: add post update functions

---

packages/common/src/EthersProviderUtils.ts
packages/common/src/index.ts
packages/scripts/package.json
packages/scripts/src/monitor-dvm/MonitorDeletion.ts
packages/scripts/src/monitor-dvm/MonitorEmergency.ts
packages/scripts/src/monitor-dvm/MonitorGovernance.ts
packages/scripts/src/monitor-dvm/MonitorGovernorTransfers.ts
packages/scripts/src/monitor-dvm/MonitorMints.ts
packages/scripts/src/monitor-dvm/MonitorRolled.ts
packages/scripts/src/monitor-dvm/MonitorStakes.ts
packages/scripts/src/monitor-dvm/MonitorUnstakes.ts
packages/scripts/src/monitor-dvm/README.md
packages/scripts/src/monitor-dvm/common.ts
packages/scripts/src/utils/contracts.ts

**Motivation**
DVMv2 monitor bot requires RPC node redundancy.
**Summary**
Uses EthersRetryProvider as redundant RPC provider for DVMv2 monitor bots.
**Details**
This should be merged only after #4389 that implements EthersRetryProvider, thus changes in `common` package should be ignored for this PR.
**Testing**
**Issue(s)**
Fixes #XXXX

feat: redundant rpc in dvm-v2 monitor

---

packages/common/src/EthersProviderUtils.ts
packages/common/src/index.ts

**Motivation**
When using ethers monitoring applications require RPC node redundancy.
**Summary**
Implements EthersRetryProvider that retries requests and uses provider fallback list.
**Details**
This implementation was inspired by [RetryProvider](https://github.com/across-protocol/relayer-v2/blob/e762204a3a275e6cacc0d5a252f6709151a234af/src/utils/ProviderUtils.ts#L112) from Across. Compared to Across this does not yet implement rate limiting, node quorum and result comparison, but can be added in future if required by applications in the protocol repo.
**Testing**
**Issue(s)**
Fixes #XXXX

feat: add ethers retry provider

---

packages/core/networks/1.json
packages/core/networks/10.json
packages/core/networks/137.json
packages/core/networks/288.json
packages/core/networks/42161.json

**Motivation**
Optimistic Asserter should be available on production networks.
**Summary**
Adds Optimistic Asserter deployments on Ethereum mainnet, Polygon, Optimism, Arbitrum and Boba.
**Issue(s)**
Fixes #XXXX

feat: deploy optimistic asserter on production networks

---

package.json
packages/scripts/package.json
packages/scripts/src/upgrade-tests/register-new-contract/1_Propose.ts
packages/scripts/src/upgrade-tests/register-new-contract/2_Verify.ts
packages/scripts/src/upgrade-tests/register-new-contract/3_VerifyRelays.ts
packages/scripts/src/upgrade-tests/register-new-contract/common.ts
packages/scripts/src/upgrade-tests/register-new-contract/readme.md
packages/scripts/src/utils/relay.ts
yarn.lock

**Motivation**
Add scripts to propose the registration of the Optimistic Asserter in the Registry and Finder in mainnet and l2 chains (Polygon, Arbitrum, Optimism, Boba).
**Summary**
- Add proposal script that can be run in mainnet or mainnet fork
- Add verification script for mainnet
- Add verification script for l2 networks
- Add common relay functions in [relay.ts](https://github.com/UMAprotocol/protocol/blob/md0x/oa-proposals/packages/scripts/src/utils/relay.ts)
**Testing**
**Issue(s)**
Fixes #XXXX

feat: optimistic asserter admin proposals

---

packages/scripts/src/monitor-dvm/common.ts
packages/scripts/src/monitor-oa/common.ts

**Motivation**
Monitor bots dependent on redundant ethers RPC provider did not use correct chain blocks in serverless.
**Summary**
Adds chain specific block number range for monitor bots dependent on redundant ethers RPC provider.
**Testing**

fix: chain specific block range for bots

---

packages/core/contracts/common/implementation/MultiCaller.sol
packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol

**Motivation**
When working on a sample OA intergration contract I realized we are missing some key functions within the OA interface. This PR addresses this.
**Summary**
Adds OA interfaces that were missing.
**Testing**

fix(oa): Add missing interface function for Optimistic Asseter

---

packages/core/package.json
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Arbitrum_ChildMessenger.js
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Arbitrum_ParentMessenger.js
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.js
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.js
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.js
packages/core/test/hardhat/cross-chain-oracle/chain-adapters/Polygon_ParentMessenger.js
packages/core/test/hardhat/helpers/SmockitHelper.js
yarn.lock

**Motivation**
https://github.com/UMAprotocol/protocol/pull/4397 broke ci silently by upgrading the hardhat version. Because ci _only_ runs on packages that have been directly modified, this PR did not trigger a ci run on core, but because it modified the hardhat version, it did ultimately have an impact.
The hardhat change broke compatibility with Smock v1 (the optimism package), which we use in some of our tests in core. To keep compatibility, we needed to upgrade to Smock v2, which has a different syntax. This is what this PR does.
Note: In the future, we should tweak the ci system to rerun everything when yarn.lock or package.json changes to ensure that packages don't silently break. However, that is out of scope for this PR.
**Summary**
This upgrades the core package to Smock v2. …

fix: fix core ci due to hardhat upgrade

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

**Motivation**
```
When the slash amount is calculated in the DidNotVote and WrongVote cases, it is rounded towards zero meaning
the staker will always be slightly under-penalized. In the CorrectVote case, the slash amount is again rounded
towards zero meaning the staker will be slightly under-rewarded for correctly voting. The rounding causes a
discrepancy between the total post-slash token balance of DidNotVote / WrongVote stakers and CorrectVote
stakers. This could cause the cumulativeStake value and the total internal stake value of each staker in the
contract to be unequal.
When the cumulativeStake value is an under-estimate, underflow can occur in two places within the contract:
- First, if the total amount unstaked and withdrawn from the contract …
```

fix(dvm2.0): H-01 - Address slashing rounding errors

---

packages/common/src/SolidityTestUtils.ts
packages/common/test/SolidityTestUtils.js

**Motivation**
When testing it might be important to check for specific revert message to make sure error is happening in the expected path.
**Summary**
Implements didContractRevertWith that accepts promise for contract call and expected revert message.
**Testing**

feat(common): match exact reverts with didContractRevertWith

---

packages/common/src/SolidityTestUtils.ts
packages/core/contracts/data-verification-mechanism/implementation/FixedSlashSlashingLibrary.sol
packages/core/contracts/data-verification-mechanism/implementation/GovernorV2.sol
packages/core/contracts/data-verification-mechanism/implementation/ProposerV2.sol
packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/test/hardhat/data-verification-mechanism/FixedSlashSlashingLibrary.js
packages/core/test/hardhat/data-verification-mechanism/GovernorV2.js
packages/core/test/hardhat/data-verification-mechanism/ProposerV2.js
packages/core/test/hardhat/data-verification-mechanism/Staker.js
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

**Motivation**
```
The following inputs lack the appropriate validation:
- The amount argument to the _stakeTo function in the Staker contract should be validated to ensure it is
non-zero.
- The amount argument to the requestUnstake function in the Staker contract should be validated to ensure it
is non-zero.
- The _baseSlashAmount and _governanceSlashAmount arguments to the constructor of the
FixedSlashSlashingLibrary contract should both be strictly less than 1e18 to prevent slashing more than 100%
of a voter's staked balance.
- In the propose function in the GovernorV2 contract, a lack of input validation allows for proposals that
contain no transactions to be created. Consider adding a check that ensures the length of the transactions
input array is …
```

fix(dvm2.0): L-05 - Add input validation

---

packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/test/hardhat/data-verification-mechanism/Staker.js
packages/scripts/src/monitoring-dvm2.0/common.ts

```
L-02 Changing the unstake cooldown
retroactively impacts stakers
Increasing the unstake cooldown time in the Staker contract using the
setUnstakeCoolDown function can result in a staker being unable to withdraw their stake at
the anticipated time when they initially requested to unstake. This happens as only the
unstakeRequestTime is cached for a staker, instead of the time at which they will be able
to unstake.
Consider caching the time at which a staker will be able to execute their unstake.
```
The solution in this PR is to store the pre-calculated `unstakeTime` instead of the `requestUnstakeTime`. By doing this we fix the retroactive behaviour of the `setUnstakeCoolDown` function reported by OZ. 
Additionally we allow to shortcut the …

fix(dvm2.0): L-02 - Retroactively unstake cooldown

---

packages/core/contracts/data-verification-mechanism/implementation/EmergencyProposer.sol
packages/core/contracts/data-verification-mechanism/implementation/GovernorV2.sol
packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
```
The following instances of misleading documentation have been identified:
- The docstring for the withdrawAndRestake function in the Staker contract states that "This method requires
that the msg.sender (voter or delegate) has approved this contract." but approval is not required as the
voting token is never transferred from the voter or delegate's wallet.
- The docstring for the setEmissionRate function in the Staker contract states the emission rate as "...per
second per staked token", but the emission rate is per second.
- The docstring for the removeProposal function in the EmergencyProposer contract states that "...the executor
or proposer can use this function" when only the owner and executor can call the function. The proposer …
```

fix(dvm2.0): N-06 - Address misleading documentation

---

packages/core/contracts/data-verification-mechanism/implementation/DesignatedVotingV2.sol
packages/core/contracts/data-verification-mechanism/implementation/EmergencyProposer.sol
packages/core/contracts/data-verification-mechanism/implementation/ResultComputationV2.sol
packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
```
Consider addressing the following typographical errors:
- On line 127 in the Staker contract, "lastRequestIndexConsidered" should be "nextIndexToProcess".
- On line 47 in the EmergencyProposer contract, "elapsed" should be "elapse".
- On line 47 in the ResultComputationV2 library, "minVoteThreshold" should be "minTotalVotes and
minModalVotes".
- On line 61 in the ResultComputationV2 library, "modeThreshold and minVoteThreshold" should be
"minTotalVotes and minModalVotes".
- On line 81 in the ResultComputationV2 library, "FixedPoint.Unsigned" should be "uint128".
- On line 30 and line 32 in the DesignatedVotingV2 contract, "DesignatedVoting" should be
"DesignatedVotingV2".
- On line 585 in the VotingV2 contract, "uint256" should be …
```

fix(dvm2.0): N-08 - Address typographical errors

---

packages/core/contracts/data-verification-mechanism/implementation/DesignatedVotingV2.sol

**Motivation**
```
In the DesignatedVotingV2 contract the import VotingV2Interface.sol is unused and could be removed.
```
This PR addresses this issue by removing the unused import.

fix(dvm2.0): N-09 - Remove unused import

---

packages/core/contracts/data-verification-mechanism/implementation/DesignatedVotingV2Factory.sol
packages/core/contracts/data-verification-mechanism/implementation/FixedSlashSlashingLibrary.sol
packages/core/contracts/data-verification-mechanism/implementation/ProposerV2.sol
packages/core/contracts/data-verification-mechanism/implementation/VoteTiming.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
```
Several functions in the codebase lack complete documentation:
- The getRoundIdToVoteOnRequest function in the VotingV2 contract
- All input arguments to the init function in the VotingTiming library
- The baseSlashAmount and governanceSlashAmount state variables in the FixedSlashSlashingLibrary contract
- The constructor in the FixedSlashSlashingLibrary contract
- The finder and designatedVotingContracts state variables in the DesignatedVotingV2Factory contract
- All state variables in the ProposerV2 contract
```
This PR addresses this issue by adding missing docstrings.

fix(dvm2.0): L-09 - Add missing docstrings

---

packages/core/contracts/data-verification-mechanism/implementation/Staker.sol

**Motivation**
```
Consider emitting events for the following state changes:
When emissionRate is set in the constructor of the Staker contract.
When unstakeCoolDown is set in the constructor of the Staker contract.
Emitting events provides a convenient way for external entities to observe and react to
changes in the contract's state.
```
This PR fixes this by using the setters (with events) to the constructor.

fix(dvm2.0): L-08 - Address missing emmitted props when setting unstake cooldown and emission rate in construction

---

package.json
packages/core/contracts/data-verification-mechanism/interfaces/StakerInterface.sol
packages/serverless-orchestration/src/ServerlessHub.js

**Motivation**
OZ identified:
```
The following instances of mismatched argument names between contracts and interfaces are
present:
The setEmissionRate function in the Staker interface has an argument named
emissionRate , but it is named newEmissionRate in the Staker contract.
The setUnstakeCoolDown function in the Staker interface has an argument named
emissionRate , but it is named newUnstakeCoolDown in the Staker contract.
For clarity, consider renaming one of the arguments so the interface matches the
implementation.
```
This PR fixes it.
**Summary**
**Details** …

fix(dvm2.0): N-01 Address interface inconsistancy

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/contracts/data-verification-mechanism/interfaces/VotingV2Interface.sol
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

```
M-01 Inaccurate function results
The following functions return information about the state of the VotingV2 contract:
getPendingRequests : returns an array of pending requests to be voted on in the
current round.
currentActiveRequests : returns a boolean to indicate whether there are any active
requests.
_getPriceOrError : returns a boolean to indicate success or failure to retrieve a price
for a price request, a price (if applicable), and a string error (if applicable).
getNumberOfPriceRequests : returns the number of pending price requests and the
number of resolved price requests.
However, these functions can return results that are inconsistent with the true state of the
VotingV2 contract. The functions getPendingRequests , currentActiveRequests …
```

fix(dvm2.0): M-01 - Inaccurate function results

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/contracts/data-verification-mechanism/implementation/test/VotingV2Test.sol
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

```
M-02 onlyIfNotMigrated modifier can prevent
price requests from being resolved
As part of migrating to a new voting contract, the onlyIfNotMigrated modifier is used to
restrict access to the following functions in the VotingV2 contract:
requestPrice
requestGovernanceAction
commitVote
revealVote
However, when a migration does occur, the onlyIfNotMigrated modifier prevents stakers
from being able to commit and reveal votes. The consequence of this is twofold: stakers who
did not reveal their vote before the migration could be unintentionally slashed if any price
requests were to resolve, and price requests that did not resolve this round would be
permanently unresolvable. Regular price requests would eventually be deleted from the system
when they …
```

fix(dvm2.0): M-02 - Enable commit/reveal post migration to still enable requests to be settled if voted on during a migration

---

packages/core/contracts/data-verification-mechanism/implementation/DesignatedVotingV2.sol
packages/core/contracts/data-verification-mechanism/implementation/DesignatedVotingV2Factory.sol
packages/core/contracts/data-verification-mechanism/implementation/GovernorV2.sol
packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
OZ identified the following:
```
The following state variables are only set once within their respective constructors:
The votingToken variable in the Staker contract.
The finder variable in the DesignatedVotingV2 contract.
The finder variable in the DesignatedVotingV2Factory contract.
The finder variable in the GovernorV2 contract.
Consider declaring these state variables as immutable to increase gas efficiency and enhance
the clarity of the codebase.
```

fix(dvm2.0): N-10 Mark all state variables that can be as immutable

---

packages/core/contracts/data-verification-mechanism/implementation/Staker.sol

**Motivation**
```
L-11 Redundant Code
The following instances of redundant code have been identified:
The requestUnstake and executeUnstake functions in the Staker contract do
not need to include override .
In the getVoterFromDelegate function in the Staker contract, the
delegateToStaker[caller] value is read from storage up to three times.
The requestPrice function in the VotingV2 contract can only be called if the
contract has not been migrated, as the onlyIfNotMigrated modifier checks that the
migratedAddress is non-zero. The onlyRegisteredContract modifier checks if
msg.sender is the migratedAddress . Since the onlyIfNotMigrated modifier
will cause execution to revert if the contract is migrated, the msg.sender will never be
the migratedAddress in …
```

fix(dvm2.0): L-11 - Address duplicate code

---

packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/contracts/data-verification-mechanism/interfaces/OracleInterface.sol
packages/core/contracts/data-verification-mechanism/interfaces/VotingV2Interface.sol

**Motivation**
OZ identified:
```
N-07 public functions that should have
external visibility
The following public functions should be external :
The stake function in the Staker contract
The stakeTo function in the Staker contract
The withdrawRewards function in the Staker contract
The hasPrice(bytes32, uint256) function in the VotingV2 contract (except the
version with the bytes memory ancillaryData argument, which should indeed be
public )
The getPriceRequestStatuses function in the VotingV2 contract
The revealVote function in the VotingV2 contract
The commitAndEmitEncryptedVote function in the VotingV2 contract
The retrieveRewardsOnMigratedVotingContract function in the VotingV2
contract
Consider changing the visibility of these functions to external in order to clarify that these …
```

fix(dvm2.0): N-07 Ensure all external functions are marked as such

---

packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
packages/core/test/hardhat/data-verification-mechanism/DesignatedVotingV2.js
packages/core/test/hardhat/data-verification-mechanism/VotingV2.js

**Motivation**
```
The hashed price that is committed during the commit phase is calculated by using the
msg.sender address as is verified by the revealVote function in the VotingV2 contract.
If a voter has delegated their voting to another address, the delegate address will be used for
calculating the hash. Since the delegate can change at anytime, it is possible that a voter will
be unable to reveal their vote if they have changed their delegate or if they have revoked
delegation which will result in their staked balance being slashed.
Consider using the voter address in the hashed price to ensure a voter will always be able to
reveal their vote.
```
This PR changes the voting contracts by using the `voter` address in all cases when computing the hash. …

fix(dvm2.0): L-04: Add ability to change delegate during voting round

---

packages/common/src/TimeUtils.ts

Boba averaging 600 blocks a day and trending down [source](https://bobascan.com/chart/tx).
This is roughly 150 seconds per block
I'd like to release a new `npm` package with this change to make across bots more efficient

improve(common): Change Boba average block time

---

packages/common/src/EthersSignerUtils.ts
packages/scripts/src/upgrade-tests/register-new-contract/1_Propose.ts
packages/scripts/src/upgrade-tests/register-new-contract/common.ts

**Motivation**
Before this update we couldn't use `getGckmsSigner` in a hardhat script run with `yarn hardhat run ./pathToScript --network localhost` because `yarn hardhat run` doens't allow arbitrary positional arguments as required in `getGckmsSigner` previously.
With this change we can now use `getGckmsSigner` by passing the name of the wallet we want to instantiate.

feat: update getGckmsSigner to be used in hardhat scripts

---

packages/core/contracts/data-verification-mechanism/implementation/FixedSlashSlashingLibrary.sol
packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol

**Motivation**
Final audit report included notes on issues that were partially resolved:
```
- M-01: getPendingRequests and _getPriceOrError can still return results that indicate price
requests have been resolved even though they have not been processed yet, and this behavior
has not been clearly documented in either function.
- L-09: The targetRoundId argument to the getRoundIdToVoteOnRequest function in
the VotingV2 contract is undocumented. The baseSlashAmount and governanceSlashAmount state variables in the
FixedSlashSlashingLibrary contract are undocumented.
```
This PR addresses these unresolved issues with additional documentation. No contract logic is changed.

fix: dvm-v2 contract comments

---

packages/scripts/src/admin-proposals/simulateVoteV2.ts
packages/scripts/src/upgrade-tests/voting2/1_Propose.ts
packages/scripts/src/upgrade-tests/voting2/readme.md

**Motivation**
When downgrading the `VotingUpgraderV2.upgrader` needs to be the `EmergencyProposer.executor`
Previously, when doing a downgrade we deployed a new VotingUpgraderV2 that used the account[0] as the upgrader, account[0] was also the `EmergencyProposer.executor` so this change wasn't required.
When testing against the mainnet deployments, during the downgrade, the new VotingUpgraderV2.upgrader has to 
be the EmergencyProposer.executor which is a multisig different than account[0]. For these scripts to work, we need to update this argument.
Note that with this change, the full upgrade workflow (Deploy, Propose, Verify, Downgrade, ...) still works identically as before given that account[0] is used as the `VotingUpgraderV2.upgrader` and `EmergencyProposer.executor`

feat: update downgrade upgrader

---

packages/monitor-v2/src/health-check-runner/index.ts

The health check is missing a key word that the hub expects. See log.
This PR fixes this.

fix: fix an issue in the health check

---

packages/scripts/src/migration/dvm2-designated-voting/0_Deploy.ts
packages/scripts/src/migration/dvm2-designated-voting/2_Delegate.ts
yarn.lock

**Motivation**
When migrating people's DV wallets, we'd like to be able to replace their hot wallets in the process.
**Summary**
This adds the ability for the script runner to swap out the hot wallet as a part of the delegation process by providing an env called HOT_WALLET_REPLACEMENTS.
**Testing**
**Issue(s)**
N/A

feat: add ability to replace wallets in DV migration

---

packages/monitor-v2/src/monitor-dvm/index.ts
packages/monitor-v2/src/monitor-oo-v3/index.ts

**Motivation**
Some of log transports used by monitor-v2 bots require time to flush.
**Summary**
Adds 5 second delay to DVM2.0 and OOv3 monitoring bots before exiting on success.
**Testing**

fix: allow monitors to flush log transport

---

packages/scripts/src/monitoring-dvm2.0/slashingEvents.ts
packages/scripts/src/monitoring-dvm2.0/unstake.ts
packages/scripts/src/monitoring-dvm2.0/voterStakes.ts
packages/scripts/src/upgrade-tests/voting2/3_SimulateVoting.ts
packages/scripts/src/utils/votingv2-utils.ts

**Motivation**
In order to do accurate calculations in the VotingV2 upgrade simulation script we need to first unstake all preexisting voter.
**Summary**
Add unstake of all voters at the beginning of the script

fix: add preexisting unstaking step to simulation script

---

packages/core/networks/1.json
packages/core/networks/5.json

**Motivation**
For compleatness, we should have `DesignatedVotingV2Factory` on goerli in the deployment file.

feat: add designated voting factory on goerli

---

packages/scripts/src/utils/votingv2-utils.ts

**Motivation**
Unstake DVM2.0 fails because of insufficient eth balance to unstake from voter wallets. We need to increase voter balances to make sure they have enough ETH to unstake.
**Summary**
- Set ETH balance of voter before unstaking

fix: unstake health check

---

packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
packages/monitor-v2/test/OptimisticOracleV3Monitor.ts

**Motivation**
Simplify bot configuration.
**Summary**
Adds optimistic-oracle notificationPath to OOv3 monitor bot.
**Testing**

feat: add notification path for oov3 monitor

---

packages/monitor-v2/src/monitor-dvm/common.ts
packages/monitor-v2/src/monitor-dvm/index.ts
packages/monitor-v2/src/monitor-oo-v3/common.ts
packages/monitor-v2/src/monitor-oo-v3/index.ts

**Motivation**
If no new blocks were mined between serverless runs monitoring bots would fail.
**Summary**
Allows starting block higher than ending block in serverless for monitor-v2 bots.
**Details**
Serverless hub might inject starting block value higher than end block if there were no new blocks mined between runs. This fix skips block range check in serverless and exits loop.
**Testing**

fix: monitor-v2 block range in serverless

---

packages/scripts/src/monitoring-dvm2.0/gasMonitor.ts

**Motivation**
We would like to monitor the upper bound of some events on the contracts under high gas conditions. This PR monitors the condition where resolion and updating account slashing trackers cost a lot in gas.

feat: add gas limit monitor health check for resolution and settlement

---

packages/monitor-v2/test/DVM2Monitor.ts

**Motivation**
In some instances monitor bot tests failed due to out-of sync hardhat EVM timing.
**Summary**
Uses timestamp from contract state when submitting requests in DVM2 monitor bot testing.
**Details**
**Testing**

fix: request timing in dvm2 monitor tests

---

packages/scripts/src/monitoring-dvm2.0/unstake.ts

**Motivation**
Fixes the unstake health check of DVM2.0 by adding the same tolerance used in other parts of this scripts.
Every voter slashed, represented by a `VoterSlashed` event, can result in 1 WEI drift in favour of the VotingV2 contract.
**Summary**
- Add rounding tolerance to `cumulativeStake` check after all users exiting.

fix: unstake health check tolerance

---

packages/core/contracts/optimistic-governor/implementation/OptimisticGovernor.sol
packages/core/test/hardhat/optimistic-governor/OptimisticGovernor.js

**Motivation**
```
The OptimisticGovernor contract's assertionDisputedCallback function does not
validate whether its assertionId argument is valid (i.e., whether it is associated with a
proposal). This allows a ProposalDeleted event to be emitted for any assertionId
value, not just values that correspond to actual proposals.
```
**Summary**
This PR addresses this issue by adding a check in the assertionDisputedCallback function that ensures the assertionId value maps to a non-zero proposalHash.
**Testing**

fix(og): L-01 - Restrict ProposalDeleted event emission to valid assertionId

---

packages/core/contracts/optimistic-governor/implementation/OptimisticGovernor.sol
packages/core/test/hardhat/optimistic-governor/OptimisticGovernor.js

**Motivation**
```
The setEscalationManager administrative function in OptimisticGovernor does not
perform any checks to validate that the _escalationManager address is a contract.
Specifying an address where no contract code is deployed could result in unexpected behavior
since the OptimisticOracleV3 contract expects that all escalation managers implement
EscalationManagerInterface .
```
**Summary**
This PR addresses this issue by using the existing _isContract function to validate the _escalationManager argument unless it is zero address when disabling the Escalation Manager.
**Testing**

fix(og): L-03 - Add contract address check in setEscalationManager

---

packages/core/contracts/optimistic-governor/implementation/OptimisticGovernor.sol

**Motivation**
```
Some functions in the OptimisticGovernor contract use leading underscores to name
either input parameters or local variables in cases where there is no name collision with the
contract's storage variables:
• proposeTransactions : Input parameters _transactions and _explanation
• executeProposal : Input parameter _transactions and local variable
_proposalHash
• deleteProposalOnUpgrade : Input parameter _proposalHash
• _constructClaim : Input parameters _proposalHash and _explanation
```
**Summary**
This PR addresses this issue by removing the leading underscore from these parameters, and also updating the corresponding docstrings.
**Testing**

fix(og): N-01 - Consistent variable naming

---

packages/core/contracts/optimistic-governor/implementation/OptimisticGovernor.sol
packages/core/test/hardhat/optimistic-governor/OptimisticGovernor.js

**Motivation**
```
The proposalHashes and assertionIds mapping names misleadingly reflect the
contents of one another (i.e., proposalHashes stores assertionId values, and
assertionIds stores proposalHash values).
```
**Summary**
This PR addresses this issue by swapping the names of the proposalHashes and assertionIds mappings, so that the variable names correspond to the values being stored.
**Testing**

fix(og): N-03 - Swap misleading variable names

---

packages/core/contracts/optimistic-governor/implementation/OptimisticGovernor.sol

**Motivation**
```
The executeProposal function has the payable modifier. However, any ETH sent is not
used in the function and will be locked in the OptimisticGovernor contract.
```
**Summary**
This PR addresses this issue by removing the payable attribute to avoid potentially locking ETH in the OptimisticGovernor contract.
**Testing**

fix(og): N-02 - Remove payable in executeProposal

---

packages/core/package.json
yarn.lock

**Motivation**
Before deploying updated Optimistic Governor contract make sure its external dependencies are up to date.
**Summary**
Updates Gnosis Zodiac dependency to v3.2.0
**Details**
Most notable changes that affect the contracts inherited by the Optimistic Governor since the previous version (v1.0.3 from October 2021) are:
- [Add custom errors](https://github.com/gnosis/zodiac/commit/193e6a88f987046073842d331d6928ba96bce744)
- [Add custom error params](https://github.com/gnosis/zodiac/commit/000af65cc67be8e7de1ad5476a3e5376dc89e6b6)
- [check that target master copy has code](https://github.com/gnosis/zodiac/pull/90)
- [Fix guardable](https://github.com/gnosis/zodiac/pull/109)
- [Updates OpenZeppelin contracts to 4.8.1](https://github.com/gnosis/zodiac/pull/110)
**Testing**
Check a …

feat(core): update zodiac dependency version

---

packages/sdk/src/clients/optimisticOracle/client.ts
packages/sdk/src/clients/optimisticOracleV2/client.ts
packages/sdk/src/clients/skinnyOptimisticOracle/client.ts
packages/sdk/src/oracle/services/statemachines/setActiveRequestByTransaction.ts
packages/sdk/src/oracle/types/ethers.ts
packages/sdk/src/oracle/types/interfaces.ts
packages/sdk/src/utils.ts

**Motivation**
In the oracle dapp, we were not correctly using event log indexes to differentiate between requests generated within the same transaction. optimism frequently does this when reqeusts are disputed, but issuing a new request in the same transaction.
**Summary**
we make sure to add correct log index to requests when parsed from events. these events are also used now to search based on known requests to find a match, in order to set the users currently selected request, or if not in the list, it will query contract events and find a match that way. 
**Testing**
Tested this with the dapp itself by integrateing changes.

feat: add logIndexes to request data and searching

---

packages/core/contracts/data-verification-mechanism/test/MockOracle.sol
packages/core/contracts/data-verification-mechanism/test/MockOracleAncillary.sol
packages/core/contracts/data-verification-mechanism/test/MockOracleGovernance.sol
packages/core/test/foundry/optimistic-oracle-v3/CommonOptimisticOracleV3Test.sol
packages/core/test/foundry/optimistic-oracle-v3/OptimisticOracleV3.Events.t.sol

**Motivation**
Make it easier to interact with mocked oracle when testing Optimistic Oracle dispute flow. It is especially useful for testing in Foundry that currently does not have convenient way to parse unindexed event parameters.
**Summary**
Stores and retrieves all mocked oracle requests by their hashed request identifier. Adds wrapper method pushPriceByRequestId to resolve request identified by its hash instead of its individual parameters.
**Details**
When initiating and resolving requests this change also emits the hashed request identifier.
This PR also deletes relevant requestedPrices array element when resolving requests so that getPendingQueries would return correct state of pending requests.
**Testing**
Check a box to describe how you tested these changes and list the steps …

feat(core): reference requests by hash in mock oracle

---

packages/scripts/src/utils/constants.js
packages/scripts/tsconfig.json

**Motivation**
#4519 broke some of JS scripts when converting constants to typescript.
**Summary**
Converts constants back to javascript and allows other TS scripts to import required constants.
**Details**
The source of the issue was requiring the same constants in JS as well as importing them in TS.
**Testing**

fix(scripts): allow js imports

---

packages/monitor-v2/src/monitor-og/MonitorLogger.ts
packages/monitor-v2/test/OptimisticGovernorMonitor.ts

**Motivation**
Optimistic Governor users might want to get paged on transaction proposals and disputes.
**Summary**
Changes log level to error for transaction proposals and deletion (that occurs on disputes).
**Testing**

fix(monitor-v2): og monitor log levels

---

packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/README.md
packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/src/monitor-polymarket/index.ts
packages/monitor-v2/test/PolymarketMonitor.ts

**Motivation**
The previous design wasn't compatible with serverless bots configs as this bot was running in a continuous process.
**Summary**
- Filter ended markets from markets query
- Parallelise ancillary on-chain requests
- Simplify bot structure
**Testing**
Fixes #XXXX

feat: make polymarket notifier serverless

---

packages/monitor-v2/src/monitor-polymarket/common.ts

**Motivation**
The polymarket bot is erroring because some markets don't exist on the clob API.
**Summary**
Until we figure out why, this adds defaulting to allow the bot to continue to run, just ignoring those parts of the book that return errors.
**Testing**
**Issue(s)**
N/A

fix: temp fix to handle erroring in PM bot

---

packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
packages/monitor-v2/test/OptimisticOracleV3Monitor.ts

**Motivation**
Optimistic Oracle V3 notifications should go to two separate Discord channels, similarly as it is done for Optimistic Oracle V2.
**Summary**
Adds discord specific channels to Optimistic Oracle V3 monitor bot.
**Testing**

fix(monitor-v2): add oov3 bot discord channels

---

packages/monitor-v2/src/monitor-og/MonitorEvents.ts
packages/monitor-v2/src/monitor-og/MonitorLogger.ts
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-oo-v3/MonitorAssertions.ts
packages/monitor-v2/src/monitor-oo-v3/MonitorDisputes.ts
packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
packages/monitor-v2/src/monitor-oo-v3/MonitorSettlements.ts
packages/monitor-v2/src/monitor-oo-v3/common.ts
packages/monitor-v2/src/utils/logger.ts

**Motivation**
When receiving alerts on Optimistic Governor or Optimistic Oracle V3 transactions, it would be convenient to include Oracle dApp URL similarly as it is already done for other types of oracles.
**Summary**
Adds Oracle dApp URL for Optimistic Governor proposals and all Optimistic Oracle V3 transactions.
**Testing**

feat(monitor-v2): add ui links in og and oov3 monitors

---

packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts

**Motivation**
Previous design was not handling correctly having multiple proposals for the same market
**Summary**
Use the latest price proposal for a market.

fix: polymarket notifier to use latest proposal for market

---

packages/monitor-v2/src/monitor-polymarket/common.ts

**Motivation**
There was a bug in the OrderFilled filtering in the polymarket notifier only considering buys of `outcomeToken0` and sells of `outcomeToken1`
**Summary**
Fix `OrderFilled` filtering
**Testing**
**Issue(s)**
Fixes #XXXX

fix: polymarket order filled filtering

---

packages/monitor-v2/src/monitor-polymarket/MonitorLogger.ts
packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/README.md
packages/monitor-v2/src/monitor-polymarket/abi/ctfAdapter.json
packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/test/PolymarketMonitor.ts
packages/monitor-v2/test/fixtures/UmaEcosystem.Fixture.ts

**Motivation**
- Notify if proposals are for markets with volume over a certain threshold that can be configured. (default to `500_000`)
- Add pagination to graphql queries: this was just implemented to the polymarket API.
- Filter market proposals with request timestamp and ancillary data to handle situation where 2 polymarket markets have the same ancillary data
Fixes UMA-1525, UMA-1524
**Testing**
**Issue(s)**
Fixes #XXXX

feat: polymarket notifier update

---

packages/core/test/foundry/optimistic-oracle-v3/OptimisticOracleV3.Events.t.sol

**Motivation**
[This update](https://github.com/foundry-rs/foundry/pull/4920) in foundry requires that expected events are emitted immediately in the next transaction. Without the fix protocol CI is blocking all PRs to be merged.
**Summary**
Fixes the issue by reorganizing foundry test logic so that there are no other transactions in between vm.expectEmit and the transaction that should trigger expected events.
**Details**
We were using _disputeAndGetOracleRequest subroutine after vm.expectEmit that mints and approves dispute bond. We move this funding logic before the vm.expectEmit to fix the issue.
**Testing**
**Issue(s)**
Fixes #XXXX

fix(core): forge event tests

---

packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-og/oSnapAutomation.ts

**Motivation**
Improve oSnap bot efficiency as pointed out in [this comment](https://github.com/UMAprotocol/protocol/pull/4591#discussion_r1262823869).
**Summary**
Uses Sets with `has` instead of Arrays with `includes` when matching elements in dynamic range addresses/events.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1651/optimize-osnap-bot-event-matching-with-set

fix(monitor-v2): use sets for osnap bots

---

packages/monitor-v2/src/monitor-og/README.md
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
packages/monitor-v2/test/OptimisticGovernorMonitor.ts

**Motivation**
Before oSnap automation bots are deployed in production it would benefit testing them in real environment without actually submitting transactions on-chain.
**Summary**
Adds SUBMIT_AUTOMATION environment that allows disabling tx submission when set to false.
**Details**
When SUBMIT_AUTOMATION is set to false, the bot only logs the attempted transaction without submitting it on-chain. This does not apply to bond approvals as they are still required for subsequent static calls to proposal/dispute.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1661/osnap-bot-should-have-option-not-to-submit-tx-while-testing

feat(monitor-v2): add disable tx option on osnap automation

---

packages/financial-templates-lib/package.json
packages/financial-templates-lib/src/logger/DiscordTicketTransport.ts
packages/financial-templates-lib/src/logger/Formatters.ts
packages/financial-templates-lib/src/logger/Logger.ts
packages/financial-templates-lib/src/logger/Transports.ts
yarn.lock

**Motivation**
OO verification can be improved by using Discord transport that can trigger ticket opening on new proposals/assertions.
**Summary**
Adds new Discord Ticket transport that prepends `$ticket` command before the message is submitted.
**Details**
This transport should be used with [Ticket Tool](https://tickettool.xyz/) configured to trigger ticket opening commands. Unlike a regular Discord transport, this cannot use webhooks since Ticket Tool does not support it. Instead, messages should be sent through Discord Bot with authentication token through Discord API.
This transport concatenates message and mrkdwn fields from logged info object and prepends `$ticket` command. Premium subscription of Ticket Tool is required for messages exceeding 250 characters.
This also strips URL …

feat(financial-templates-lib): implement discord ticket transport

---

packages/common/src/PublicNetworks.ts

**Motivation**
Across is adding new chains!
**Summary**
Adding:
- zkSync era Görli (280)
- zkSync era (324)
- Base (8453)
- Ethereum Sepolia (11155111)
Fixing:
- Base etherscan link (84531) (Needs a trailing /)

chore: Update PublicNetworks

---

packages/financial-templates-lib/src/logger/PagerDutyTransport.ts
packages/financial-templates-lib/src/logger/PagerDutyV2Transport.ts

**Motivation**
When bot sends link in Markdown formatted as <URL|TEXT> the PagerDuty does not resolve URL correctly as |TEXT is added to URL.
**Summary**
Removes anchor text from links in PagerDuty transports.
**Details**
This uses removeAnchorTextFromLinks that was created for DiscordTicketTransport.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1633/fix-markdown-links-for-pagerduty

fix(financial-templates-lib): remove anchor text from pd links

---

packages/financial-templates-lib/src/clients/OptimisticOracleEventClient.ts
packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
packages/monitors/src/OptimisticOracleContractMonitor.js
packages/monitors/test/OptimisticOracleContractMonitor.js

**Motivation**
Monitor bots handling OOv1/OOv2/SkinnyOO do not add eventIndex query parameter to Oracle URL as this was introduced after original monitor bots were built. We should add this parameter similar how we do in OOv3 monitor bots so that Oracle links in bot logs resolve correctly.
**Summary**
Updates oracle link generation in monitors package to be compatible with the current Oracle dApp.
**Details**
Also adds event log index to OptimisticOracleEventClient so that this can be easily added link generation in consuming monitor bots.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1700/add-eventindex-parameter-to-oracle-url-in-monitor-bots

fix: add event index to oo contract monitor

---

packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
packages/monitor-v2/test/OptimisticOracleV3Monitor.ts
packages/monitors/src/OptimisticOracleContractMonitor.js

**Motivation**
Monitor OO disputes in dedicated channel without raising PD error alerts.
**Summary**
Changes notification path for OO disputes.
**Details**
Log level for OOv3 is changed to warn. For older OO bot this should be changed in MONITOR_CONFIG.logOverrides.disputedPrice in environment.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1774/move-oo-disputes-to-slack-instead-of-pd

feat: dedicated channel for oo disputes

---

packages/serverless-orchestration/test/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessSpoke.js

**Motivation**
Kraken has shut down cryptowat.ch api causing some of serverless package tests using EMP monitors to fail and block new PRs.
**Summary**
Replaces EMP monitors with OO monitors in serverless package tests.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1876/cryptowatch-api-no-longer-works-causing-ci-to-fail

fix: use oo monitors in serverless tests

---

packages/api/package.json
packages/sdk/package.json
yarn.lock

**Motivation**
We are getting timeouts in GCP when accessing datastore. This seems to happen when process is running for a long time, a reboot fixes things.  It ends up causing pages to on call personnel.
**Summary**
We are going to simply try bumping the version of the library calling datastore.
**Testing**
**Issue(s)**
https://linear.app/uma/issue/UMA-1812/somekind-of-issue-with-api-server

improve(api): bump cloud datastore versions to potentially fix timeouts

---

packages/financial-templates-lib/src/logger/SlackTransport.ts

**Motivation**
Currently Slack transport can error under certain conditions when splitting lines.
**Summary**
Fixes Slack transport to avoid sending empty blocks.
**Details**
Slack webhook treats empty text blocks as invalid. This could have happened in splitByNewLine if the first line already exceeds Slack character limit. The fix avoids this by not starting the smallerBlocks array with createSectionBlock("").
**Testing**
**Issue(s)**
Fixes #XXXX

fix: avoid empty blocks in slack transport

---

packages/sdk/src/blockFinder.ts

This is a one-off comment to change the spelling from `grater` to `greater`

docs: comment correction

---

packages/monitor-v2/src/monitor-og/README.md
packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
packages/monitor-v2/src/monitor-og/common.ts

**Motivation**
Avoid false oSnap disputes caused by IPFS gateway issues.
**Summary**
Changes default oSnap dispute bot behavior not to trigger dispute caused by invalid IPFS gateway response.
**Details**
New DISPUTE_IPFS_SERVER_ERRORS variable defaults to false, but enabling it allows to return to the old behavior.
Since the returned HTTP response code behavior differs across providers we cannot reliably identify whether the referenced proposal is available on IPFS or not.
This change should not affect behavior of other modules. Particularly, any non-ok IPFS gateway responses would still trigger error alerts as the monitoring module would fail validation, as well as proposal module would abstain from posting the proposal till it can fetch IPFS hosted proposal.
**Testing**
Check a box to …

fix: do not dispute ipfs server errors by default

---

packages/common/src/TransactionUtils.ts
packages/common/test/SolidityTestUtils.js

**Motivation**
fx-tunnel-relayer bot was failing due to nonce management issue in TransactionUtils.
**Summary**
Fixes TransactionUtils by incrementing nonce only after static call succeeds.
**Details**
runTransaction from TransactionUtils modifies web3 object by adding nonces, but it was done before performing simulation with static call. This caused issues for fx-tunnel-relayer that attempted to run multiple relay transactions: after the first transaction reverted on call stage the next message had its nonce incremented causing it to hang in send phase.
**Testing**
TransactionUtils skip nonce management in test mode due to reasons discussed …

fix: increment nonce after static call

---

packages/api/src/services/express-channels.ts
packages/api/src/services/express.ts

**Motivation**
we want to add some kind of health check to the bots to make sure our connection to datastore is working. this can be done as long as we have a way to query routes through "GET". currently these actions require a POST.
**Summary**
This does not break any existing functionality, only mirrorss the  POST calls to GET calls using the exact same underlying logic
for health checks, you can now  hit  `GET global/listActive`
**Testing**

feat(api): add GET routes that mirror POST routes in express

---

packages/monitor-v2/src/monitor-og/README.md
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
packages/monitor-v2/test/OptimisticGovernorMonitor.ts

**Motivation**
oSnap execution module is spamming notification channel for proposals that are known to be misconfigured and will be reverting.
**Summary**
Adds ability to selectively blacklist automated proposal dispute/execution.
**Details**
We identify proposals by their assertionId's that are guaranteed to be unique.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2024/osnap-bot-trying-to-execute-bad-proposal-over-and-over

feat: skip disputes and execution for blacklisted assertions

---

packages/financial-templates-lib/src/helpers/GasEstimator.ts

**Motivation**
GasEstimator is using hardcoded maxPriorityFeePerGas for some of networks. This can cause errors if estimated maxFeePerGas gets below this.
**Summary**
Enforce that maxFeePerGas is not set below maxPriorityFeePerGas.
**Details**
We experienced the error recently on Polygon where estimated maxFeePerGas got below hardcoded 50 GWei maxPriorityFeePerGas
**Testing**
**Issue(s)**
Fixes #XXXX

fix: maxFeePerGas cannot be less than maxPriorityFeePerGas

---

packages/monitor-v2/src/monitor-og/README.md
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-og/oSnapAutomation.ts

**Motivation**
Manage gas consumption of oSnap execution bot.
**Summary**
Impose upper limit to gas usage (per proposal) when automatically executing oSnap proposals (defaults to 500k).
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2094/add-gas-limit-to-osnap-transactions-that-we-execute

feat: impose gas usage limit for automated osnap execution

---

packages/core/scripts/SetUpFoundryWithHardhat.sh

**Motivation**
The foundry scripts are failing in ci.
**Summary**
This patches the foundry script to detect if the forge-std folder is empty and deletes it if so.
In ci, the caching and/or installation process breaks in such a way where the lib folder exists, but the actual files are not present. This detects that situation and removes the entire thing before reinstalling.
**Testing**
**Issue(s)**
N/A

fix: fix foundry scripts in ci

---

.circleci/config.yml
Dockerfile
README.md

**Motivation**
Nodejs 16 is EOL and it's important to continue to get security updates from nodejs.
**Summary**
Updated all references to nodejs 16.
**Testing**
**Issue(s)**
N/A

fix: update nodejs version

---

packages/api/package.json
packages/api/src/apps/serverless_read/app.ts
packages/api/src/libs/index.ts
packages/api/src/libs/osnap.ts
packages/api/src/services/actions/index.ts
packages/api/src/services/actions/osnap.ts
packages/api/src/services/express-channels.ts
packages/api/src/types.ts
yarn.lock

**Motivation**
We want to add a serverless function for tenderly simulation with osnap proposals. this feature will be broken up into mutliple prs. first we need to make a space to put this function.
**Summary**
The path of least resistance is to put this in the exisitng API server. this is already running on gcp serverless infrastructure and its set up to add arbitrary new functions.  We add an optional route for tenderly simulations which are enabled with 3 optional environment variables: TENDERLY_ACCOUNT_NAME, TENDERLY_PROJECT_NAME, TENDERLY_ACCESS_KEY. Once set, a `osnap` route will be enabled.  Here is where we will ultimately put simulation logic in future PR. 
**Testing**

feat(api): add boilerplate for osnap tenderly sim

---

packages/monitor-v2/package.json
packages/monitor-v2/src/bot-oo-v3/README.md
packages/monitor-v2/src/bot-oo-v3/SettleAssertions.ts
packages/monitor-v2/src/bot-oo-v3/common.ts
packages/monitor-v2/test/OptimisticOracleV3Bot.ts
yarn.lock

**Motivation**
OOv3 bot looks for assertions that can be settled using block range based lookback. Sometimes this is not sufficient and we cannot guarantee that even standard 2h challenge window assertions get detected. This is particularly an issue for chains that don't have fixed block times (e.g. Arbitrum).
**Summary**
Use `BlockFinder` for time based lookback and set the default to use 72h that should cover most use cases.
**Testing**
Since BlockFinder does not work in local test network, this was tested in production:
- Made test assertion [here](https://arbiscan.io/tx/0x6ab738456f1403fe88335c2f9cda5704c43753ab2fe446a61d965b249d1382ef)
- Bot picked it up 2h later (after challenge window) …

fix!: time based lookback in oov3-bot

---

packages/serverless-orchestration/src/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessHub.js

**Motivation**
Serverless hub does not correctly handle block ranges when dealing with multi-network bots.
**Summary**
Fixes 2 bugs in Serverless hub to correctly store network block ranges for multi-network bot instances.
**Details**
We have not encountered this in prod as block ranges get also saved from single-network bot instances, but this could become an issue when adding new bots that have multiple networks not covered by other bots in the same spoke call.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2373/fix-serverless-hub-block-numbers-for-multiple-network-bots

fix: correctly store block numbers in serverless hub

---

packages/core/contracts/optimistic-oracle-v3/interfaces/EscalationManagerInterface.sol
packages/core/contracts/optimistic-oracle-v3/interfaces/OptimisticOracleV3CallbackRecipientInterface.sol
packages/core/contracts/optimistic-oracle-v3/interfaces/OptimisticOracleV3Interface.sol

- Relax OOv3 Interfaces Solidity Version Requirement to ^0.8.16

feat: Relax OOv3 Interfaces Solidity Version Requirement to ^0.8.16

---

packages/common/src/hardhat/tasks/dvmv2Testnet.ts

**Motivation**
DVMv2 testnet setup tasks was missing transfer of VotingV2 owner to GovernorV2. This is required so we can submit governance proposals on testnet.
**Summary**
Transfers VotingV2 owner to GovernorV2 in DVMv2 setup task for testnets.
**Testing**
**Issue(s)**
Fixes #XXXX

fix: transfer voting v2 owner to governor in testnet task

---

packages/scripts/src/admin-proposals/register-parent-messenger/0_Propose.ts
packages/scripts/src/admin-proposals/register-parent-messenger/1_Verify.ts
packages/scripts/src/admin-proposals/register-parent-messenger/common.ts
packages/scripts/src/admin-proposals/register-parent-messenger/readme.md

- Add custom script to register base parent messenger in OracleHub and GovernorHub in mainnet and set the `defaultGasLimit` to `500_000` in `OptimismParentMessenger` and `BaseParentMessenger`
Fixes UMA-2473

feat: register parent messenger proposal

---

packages/logger/src/logger/PersistentTransport.ts

We've seen quite a few socket related errors being spit out of the redis client, generating pages. Redis emits network errors frequently. I suspect that most are recoverable and unrelated to a particular request, so it's probably not right to page on them.
**Testing**

fix: emit redis errors to console rather than sending a logger error

---

packages/common/src/HardhatConfig.ts
packages/common/src/ProviderUtils.ts
packages/common/src/PublicNetworks.ts
packages/common/src/TimeUtils.ts
packages/common/src/hardhat/tasks/xchainSetup.ts
packages/core/contracts/cross-chain-oracle/README.md
packages/core/deploy/038_deploy_oracle_spoke.js
packages/core/deploy/039_deploy_oracle_hub.js
packages/core/deploy/040_deploy_governor_spoke.js
packages/core/deploy/041_deploy_governor_hub.js
packages/core/deploy/057_deploy_optimistic_oracle_V3.js
packages/core/deploy/064_deploy_blast_parent_messenger.js
packages/core/deploy/065_deploy_blast_child_messenger.js
packages/core/networks/1.json
packages/core/networks/81457.json
packages/financial-templates-lib/src/helpers/GasEstimator.ts

**Motivation**
Potential UMA integrations would need to use Optimistic Oracle on Blast network.
**Summary**
Adds Optimistic Oracle contract deployments for Blast network.
**Details**
- Add Blast network as a supported network
- Deploy Blast contracts and L1 Parent Messenger
- Verify contracts
- Run all the required L1 and L2 configurations
- Update configuration and verification scripts (including new default gas limit of 500k in parent messenger)
- Update readme
This requires governance action set Blast parent messenger on L1 (see verification script below):
```
$ yarn hardhat verify-xchain --network mainnet --l2 blast
🌕 Verifying L1 contract state 🌕
GovernorHub
- Owner set to Governor: ✅
- Messenger for chain ID 81457 set to ParentMessenger: ❌ ==> Requires …
```

feat: blast contract deployments

---

packages/logger/src/logger/Logger.ts
packages/logger/src/logger/PersistentTransport.ts

**Motivation**
Discord verification team reported that Optimistic Oracle bots are rate limited to 1 ticket per every serverless run cycle of 5 minutes. This is a bug that should be fixed.
**Summary**
Fixes Discord Ticket logger bug to allow submit max tickets as permitted by intended rate limit (1 ticket per 15 seconds).
**Details**
The bug is fixed by moving signal to pause persistent log queue transports only after waiting for logger flush timeout (we use 5 minutes for Oracle bots). In order to gracefully handle log delivery once this timeout passes this fix also changes `pauseProcessing` method to async and waits for `processed` event emitted from `processLogQueue` when it gets out of `while (this.canProcess)` loop.
**Testing**
Check a box to describe how you tested these changes and …

fix: pause persistent log queue after flush timeout

---

packages/monitor-v2/src/monitor-og/README.md
packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
packages/monitor-v2/src/monitor-og/common.ts
packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
packages/monitor-v2/test/OptimisticGovernorMonitor.ts

- Update the snapshot proposal logic to allow an environment variable to be passed, `REPROPOSE_DISPUTED`, which defaults to `false`, to enable reproposing disputed proposals.
- Add tests to verify the new functionality.

feat: Prevent reproposing disputed proposals in snapshot

---

packages/monitor-v2/src/monitor-og/oSnapAutomation.ts

**Motivation**
#4765 introduced side effects on oSnap bot:
- when proposing, it would not consider proposals that had been disputed (as intended by the fix), but this also extends to proposals from another snapshot votes that had been disputed and happens to have matching tx content with a new snapshot vote that has not been disputed since results of `getUndiscardedProposals` now can include also discarded proposals and are used as inputs in `filterUnblockedProposals`
- when disputing, it would consider all proposals, even those that had been disputed and are still in challenge window. this would result in bot error logging the failed dispute attempts since the proposal has been discarded from prior dispute
- when executing, it would also consider all disputed proposals that are past …

fix: osnap bot on disputed proposals

---

packages/logger/src/logger/Transports.ts

**Motivation**
Only send errors to PD, since paging over a warning is typically not done. These alerts can be sent via other means, like slack or discord rather than PD.
**Summary**
N/A
**Testing**

feat: filter warnings from PD

---

packages/serverless-orchestration/src/ServerlessHub.js
packages/serverless-orchestration/test/ServerlessHub.js

**Motivation**
Serverless hub tries to emit all the stdout for all the bots that it runs in a single log. This log can be so large that it fails to be emitted.
**Summary**
This PR splits the log into 2. One log that just lists the successful bot runs and a second that is emits a separate log per bot along with its output.
**Testing**
**Issue(s)**
Fixes #XXXX

fix: reduce log size for all calls returned correctly

---

packages/core/networks/168587773.json

Deployed a new OOV2 to Blast Sepolia because I ran into issues verifying the Blast Sepolia OOV2 on Blastscan. Deploying a new version was easier than troubleshooting.

fix(update OOV2 address on Blast Sepolia)

---

packages/affiliates/gas-rebate/VoterGasRebateV2.ts

- Update the gas rebates scripts to account for the new rules:
> Voters must have at least 500 UMA staked at the start of the commit period for the following commit and reveals transactions to be rebated.
> 
> Commited votes must be revealed to be rebated.
> 
> If a voter commits more than once on a dispute, only the ~~last~~ first commit will be rebated.

feat(gas-rebates): update gas rebate scripts with new rules

---

packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/test/PolymarketMonitor.ts

- Adds a new checkBeforeExpirationSeconds parameter to allow configuring how soon before expiration a proposal should be checked.
- Updates relevant tests to ensure the filtering logic works as expected.
- Improves flexibility in monitoring proposals close to expiration.

feat(polymarket-notifier): make expiration check delay configurable

---

packages/serverless-orchestration/src/ServerlessSpoke.js
packages/serverless-orchestration/test/ServerlessSpoke.js

This removes the splitting logic used to split commands and their args when passing to spawn. Since spawn's inputs are passed to a shell, the full string should be handled fine.

feat: remove command splitting

---

packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/test/PolymarketMonitor.ts

**Motivation**
We are getting paged on markets which have been disputed, we can safely ignore those
**Summary**
Looks for disputes within the same window of proposals we are checking, ignores any proposals which were disputed
**Testing**

fix(monitor-v2): ignore disputed requests for alerts

---

packages/scripts/src/admin-proposals/funding/0_Propose.ts
yarn.lock

**Motivation**
Funding proposal script was breaking when passing decimal amounts.
**Summary**
Uses ethers parser to convert the funding amount in the admin proposal script.
**Details**
There is a error on simulation against a local forked node:
```
eth_getBlockByNumber
Invalid JSON-RPC response's result.
Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/totalDifficulty: QUANTITY
```
This can be fixed by upgrading hardhat, but unfortunately it is not compatible with `@defi-wonderland/smock` that would break the testing. Hence, this PR does not include the hardhat upgrade and must be run locally (`yarn upgrade hardhat`) before simulating the fork tests.
**Testing** …

fix: funding proposal script

---

packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
packages/monitor-v2/test/OptimisticGovernorMonitor.ts

**Motivation**
oSnap automated proposer bot failed to handle proposals with multiple safes. Multiple safes were supported only in the monitoring and dispute bots, but they failed IPFS verification in proposer mode.
**Summary**
Adds support for multiple safes to oSnap automated proposer bot.
**Details**
oSnap automated proposer bot was splitting Snapshot proposals by safes as these have to be proposed separately, but this failed IPFS verification as IPFS had information on all safes while the passed proposal contained only one safe transactions. This PR resolves the issue by retaining the original proposal data that is used in verification.
**Testing**
**Issue(s)**
Fixes #XXXX

fix: support multiple safes in osnap automated proposals

---

packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/test/PolymarketMonitor.ts

- Fixed the proposal timestamp in the Polymarket notifier.
Previously, it was incorrectly using the request timestamp, which only affected the logs. The core logic remains correct as it relies on the expiration timestamp.

fix(polymarket-notifier): fix proposal timestamp

---

packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/common.ts
packages/monitor-v2/test/PolymarketMonitor.ts

- Adds `fillEventsLookbackSeconds` to `MonitoringParams` and uses it to derive `fromBlock` for `OrderFilled` queries, limiting how old orders are checked relative to notification time.

feat(polymarket-notifier): configurable time-based look-back for OrderFilled events

---

packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/common.ts

Changes Proposed in This PR
- Fix: Use the correct questionId when fetching market data for sports markets.
Context
Previously, the notifier was using the wrong questionId (kekkak(ancillarData)) for sports markets. However, these markets require a different questionId that is derived differently and returned by the API. This mismatch led to incorrect market data and, consequently, inaccurate notifications.
Only Winner markets were functioning correctly. Spread and Total markets were being processed incorrectly because we weren’t fetching the correct market data—just uninitialized values. This resulted in wrong payout calculations and, therefore, incorrect notifications.

fix: use correct questionId when fetching market data for sports markets

---

packages/logger/src/logger/ConsoleTransport.ts

`JSON.stringify` doens't handle bigints well. Here's a fix from the internet:
https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510
Helped me when debugging some Solana stuff

improve: handle bigint in logger

---

CODEOWNERS

This PR automatically removes @daywiss from the CODEOWNERS file via script.

Automated: Remove @daywiss from CODEOWNERS

---

packages/monitor-v2/package.json
packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
packages/monitor-v2/src/monitor-polymarket/common.ts
packages/toolkit/README.md
packages/toolkit/jest.config.js
packages/toolkit/package.json
packages/toolkit/src/__tests__/httpClient.test.ts
packages/toolkit/src/http/httpClient.ts
packages/toolkit/src/index.ts
packages/toolkit/tsconfig.json
packages/toolkit/tsup.config.ts
yarn.lock

- New shared `@uma/toolkit` HTTP client built on axios, bottleneck, and axios-retry with defaults for rate-limiting, timeouts, and exponential-backoff retries. 
- Replaces all API calls in the PM notifier (including Networker and retryAsync) with `params.httpClient`. 
- Configuration for concurrency and retry behavior is injected via `initMonitoringParams` driven by environment variables.

feat(pm-notifier): add retry backoff jitter http client

---

packages/optimistic-oracle/index.js

Some bots struggle to get all Optimistic Oracle events for the past 7 days. This allows to override this period in the bot-configs

fix: add oracle client lookback override

---

packages/fx-tunnel-relayer/src/Relayer.ts
packages/fx-tunnel-relayer/test/Relayer.ts

FX relay bot has been erroring in proof construction. Even if it has checked `this.maticPosClient.exitUtil.isCheckPointed` , the following `this.maticPosClient.exitUtil.buildPayloadForExit` call sometimes fails as if the block has not yet been checkpointed. This PR adds `IChainBlockInfo` for debugging purposes to inspect `lastChildBlock` vs `txBlockNumber`

fix: debug chainBlockInfo upon error in fx relay proof construction

---

packages/serverless-orchestration/package.json

Serverless had a few mis-specified dependencies, including some hard dependencies as dev dependencies, and some dev dependencies that weren't required at all.

chore(serverless): Cleanup dependencies

---

packages/scripts/src/admin-proposals/deprecate-oval-contracts/0_GeneratePayload.ts
packages/scripts/src/admin-proposals/deprecate-oval-contracts/1_Verify.ts
packages/scripts/src/admin-proposals/deprecate-oval-contracts/README.md

- Deprecate Oval transaction builder

feat: deprecate oval transaction builder
