- packages/serverless-orchestration/package.json
- packages/serverless-orchestration/src/ServerlessHub.js
- packages/serverless-orchestration/test/ServerlessHub.js
- yarn.lock
**Motivation**
This PR enables one hub to be used for Spokes running on different chains. Previously the assumption was that the hub and its spokes were running on the same chain.
**Summary**
The main complexity is ensuring that the block cache does not skip blocks between bots running on the same chain, which is why I need to run multiple passes of the `botConfig` list and precompute last seen blocks/latest head blocks before executing the spokes.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> refactor(serverless-hub): Support spokes running on multiple chains

- packages/core/networks/1.json
- packages/core/networks/137.json
- packages/core/networks/5.json
- packages/core/networks/80001.json
**Motivation**
EMP-related and GovernorTunnel contracts need to be added to deployments file.
**Summary**
- Corrected `OracleChildTunnel` deployed address
- Redeployed EMPLib and EMPCreator
- Removed chainbridge deployments
- Added `MockOracleAncillary` deployed address
- Deployed EMP contracts + `GovernorChildTunnel`
- Deployed `GovernorRootTunnel`
- Removed chainbridge deployments
**Testing**
> feat: New Deployments

- packages/monitors/src/OptimisticOracleContractMonitor.js
**Motivation**
OO Alerts should be segregated from other risk management alerts.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: Change OO Monitor alert channel

- packages/affiliates/payouts/dappmining/2021-06-07_2021-06-14_YD-ETH-JUN21_0022.json
**Motivation**
#3103
**Details**
Dapp mining for YD-ETH-JUN21 week 23 from 2021/06/07 to 2021/06/14 using 0.3 of dev mining rewards for this period: `Math.floor(10546.409693907659226619 * 0.3) = 3163`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "10546.409693907659226619",
"weekNumber": 22,
"endDate": "06/14/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 23

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/queries.ts
- packages/api/src/libs/utils.test.ts
- packages/api/src/libs/utils.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/services/index.ts
- packages/api/src/tables/emp-stats/index.ts
- packages/api/src/tables/emp-stats/js-map.test.ts
- packages/api/src/tables/emp-stats/js-map.ts
- packages/api/src/tables/emp-stats/utils.ts
- packages/api/src/tables/index.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1245/obtain-the-tvl-of-each-contract-on-uma
**Summary**
Adds a statistics service to calculate tvl (will have other stats in future) based on prices emp state and erc20 token state (for decimals).
Exposes this through a couple api endpoints `getEmpStats` and `listEmpStats`
**Details**
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1245/obtain-the-tvl-of-each-contract-on-uma
> feat(api): add tvl endpoints for each contract 

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/synthetic-prices.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/923/create-api-to-get-historical-prices-of-synths
**Summary**
This copies the pattern from previous historical collateral prices and applies it to synthetics.  it does this by copying over the latest price into a time series table which can queried from the api. 
**Details**
creates 2 new api routes, which are documented in the readme
- historicalSynthPricesByAddress
- sliceHistoricalSynthPricesByAddress
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/923/create-api-to-get-historical-prices-of-synths
> feat(api): api to get historical prices of synths

- packages/affiliates/libs/processors.js
**Motivation**
Affiliates run is crashing when a repay event is encountered. Surprisingly this event has not been seen before.
**Summary**
Add handler for repay event.
**Testing**
> fix(affiliates): add handler for repay event

- packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
**Motivation**
Add comments for developers who want to integrate the LSP contracts.
**Testing**
> improve(lsp): Add contract dev comments

- packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
- packages/core/test/financial-templates/long-short-pair/LongShortPair.js
**Motivation**
If `collateralPerPair=0`, then `redeem` and `settle` will both return 0 collateral, effectively locking up the collateral.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(lsp): Require collateralPerPair > 0

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/libs/queries.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/services/express.ts
- packages/sdk/src/libs/clients/emp/client.e2e.ts
- packages/sdk/src/libs/clients/erc20/client.e2e.ts
- packages/sdk/src/libs/clients/registry/client.e2e.ts
- packages/sdk/src/libs/coingecko/coingecko.e2e.ts
- packages/sdk/src/libs/coingecko/coingecko.ts
- packages/sdk/src/libs/stores/google-datastore/store.e2e.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/915/add-total-combined-tvl-to-api
**Summary**
Adds calls to get tvl based on all known emps, or a list of emp addresses through the `tvl` action.
**Details**
Adds a tvl endpoint `tvl(addresses?: string[], currency: CurrencySymbol = "usd") => string `
This tvl is currently returning a value of around 121m which is in line with https://monitor.simpleid.xyz/d/x4CYPILGk/uma?orgId=1&refresh=5m
This also adds some timing information just to see how long certain requests take for local profiling using `console.time`
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/915/add-total-combined-tvl-to-api
> feat(api): add total and partial tvl calls 

- packages/affiliates/payouts/dappmining/2021-06-14_2021-06-21_YD-ETH-JUN21_0023.json
**Motivation**
#3143
**Details**
Dapp mining for YD-ETH-JUN21 week 24 from 2021/06/14 to 2021/06/21 using 0.3 of dev mining rewards for this period: `Math.floor(10369.142467070941016149 * 0.3) = 3110`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "10369.142467070941016149",
"weekNumber": 23,
"endDate": "06/21/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 24

- packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
- packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
**Motivation**
Enables CryptoWatchPriceFeed to add a buffer around price periods when matching a historical timestamp.
**Testing**
> feat(cryptowatch): Add historical timestamp buffer

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/utils.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/tables/emp-stats-history/index.ts
- packages/api/src/tables/emp-stats-history/sorted-js-map.ts
- packages/api/src/tables/emp-stats-history/utils.ts
- packages/api/src/tables/index.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1301/ability-to-obtain-a-time-series-of-tvl-of-all-contracts-on-uma-and-for-each-contract
**Summary**
Adds historical emp stats (tvl, and eventually others), and allows you to query between timestamps.
**Details**
adds the route `getEmpStatsBetween(address: string, start = 0, end: number = Date.now(), currency: CurrencySymbol = "usd")`
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1301/ability-to-obtain-a-time-series-of-tvl-of-all-contracts-on-uma-and-for-each-contract
> feat(api): add ability to obtain a time series of tvl 

- packages/core/scripts/collateral-umip/1_Propose.js
- packages/core/scripts/creator-umip/1_Propose.js
- packages/core/scripts/identifier-umip/1_Propose.js
- packages/core/scripts/local/ClaimAllRewards.js
- packages/core/scripts/local/DeployEMP.js
- packages/core/scripts/mainnet/ExecuteAdmin.js
**Motivation**
- Script included some superfluous params in the ABI-encoded construction params, making verification hard.
- Add `chainId` to transaction config to work with (Polygon) endpoints that enforce transaction-replay-protection
**Testing**
> improve(core): Update deploy-emp script to enhance block explorer verification

- packages/common/README.md
**Motivation**
Readme has a typo.
**Summary**
Fixed the typo.
**Testing**
**Issue(s)**
N/A
> fix: common README

- packages/affiliates/payouts/dappmining/2021-06-21_2021-06-28_YD-ETH-JUN21_0024.json
**Motivation**
#3163
**Details**
Dapp mining for YD-ETH-JUN21 week 25 from 2021/06/21 to 2021/06/28 using 0.3 of dev mining rewards for this period: `Math.floor(7885.568595158589272944 * 0.3) = 2365`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "7885.568595158589272944",
"weekNumber": 24,
"endDate": "06/28/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 25

- packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
**Motivation**
The comment about how many collateral tokens need to be approved to call `create` in `LongShortPair.sol` was incorrect.
**Summary**
Replaced `/` with `*`.
**Details**
n/a
**Testing**
**Issue(s)**
n/a
> fix(comment): correct comment about token approvals for lsp minting

- packages/api/src/apps/api/README.md
- packages/api/src/libs/utils.test.ts
- packages/api/src/libs/utils.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/tables/emp-stats/utils.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1405/obtain-the-tvm-of-each-contract-on-uma
**Summary**
This adds tvm calculation which are very similar to tvl calculations, and updates the emp stats with this new data.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1405/obtain-the-tvm-of-each-contract-on-uma
> feat(api): 1405 add tvm calculations per emp 

- packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/RangeBondLongShortPairFinancialProductLibrary.sol
**Motivation**
While working through some computation on the range bond, it became clear that this comment could be improved. This PR makes a small change to the range bond commenting to make it cleaner and clearer.
**Summary**
Small comment update.
**Testing**
> feat(lps-libs): Update comment in range bond lib

- packages/core/networks/42.json
- packages/core/networks/80001.json
**Motivation**
Need to update test net deployment addresses for new LSP contract.
**Summary**
Updates Kovan and Mumbai network addresses.
> fix(networks): deploy and verify new LPS creator on testnets

- packages/affiliates/libs/affiliates/dappmining_v2.js
**Motivation**
#3198 
**Summary**
stop processing events for expired emps.
**Testing**
**Issue(s)**
Fixes #3198
> fix(affiliates): stop processing events for expired emps in dapp mining

- packages/sdk/src/libs/clients/index.ts
- packages/sdk/src/libs/clients/multicall/README.md
- packages/sdk/src/libs/clients/multicall/client.e2e.ts
- packages/sdk/src/libs/clients/multicall/client.ts
- packages/sdk/src/libs/clients/multicall/index.ts
- packages/sdk/src/libs/index.ts
- packages/sdk/src/libs/multicall.e2e.ts
- packages/sdk/src/libs/multicall.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1574/add-multicall-sdk-client
**Summary**
This adds a basic multi-call client which can be eventually used in the api.  Currently only supports read requests, not write (transactions).
**Details**
This adds a contract client and a small helper function which will help encode/decode requests responses to the multicall contract.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1574/add-multicall-sdk-client
> feat(sdk): 1574 add multicall client and helper

- packages/api/src/libs/queries.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1634/add-identifier-price-to-emp-state
**Summary**
Added 3 new properties when querying emp state, tokenSymbol, collateralSymbol, and identifierPrice (bot price)
**Details**
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1634/add-identifier-price-to-emp-state
> feat(api): add symbol names and identifier price to emp state

- packages/api/src/libs/zrx.e2e.ts
- packages/api/src/libs/zrx.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1620/create-matcha-api-client
**Summary**
This adds a small client class for matcha (0x) trade routing system. We will need this to fetch market prices on token pairs. This works with both symbols and token addresses.
**Details**
This is designed as a class in case we want to add additional api calls to matcha, its easily extendable.  The errors returned from this api are not really standard, so theres a significant amount of code to parse this out into a standard error message.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1620/create-matcha-api-client
> feat(api): 0x api client to fetch prices based on token name

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/queries.ts
- packages/api/src/libs/zrx.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/services/index.ts
- packages/api/src/services/market-prices.ts
- packages/api/src/services/synthetic-prices.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1523/connect-aggregator-api-to-our-api-or-sdk-for-pulling-in-the-best-price-the-token-is-trading-across-dexs
**Summary**
Adds infrastructure to fetch latest market price from 0x api, and keep it relatively up to date. This then gets added to emp state when queried as `tokenMarketPrice`. 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1523/connect-aggregator-api-to-our-api-or-sdk-for-pulling-in-the-best-price-the-token-is-trading-across-dexs
> feat(api): 1523 add market prices to emp state and call to list known market prices

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/services/emp-stats.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1464/backfill-tvl-time-series
**Summary**
Adds a backfill feature for emp stats tvl only (based on being able to backfill collateral price history from coingecko).  This makes no changes to the existing api.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1464/backfill-tvl-time-series
> feat(api): 1464 backfill tvl history 

- packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
- packages/core/test/financial-templates/long-short-pair/LongShortPair.js
**Motivation**
After some Kovan testing by the UMA team, it became apparent there are some cases where rounding can result in dust minting for free. This PR fixes this case and adds unit tests to validate the solution.
**Summary**
Update implementation and tests to better deal with rounding errors.
**Testing**
> feat(LSP): Add rounding protection and additional unit tests

- packages/core/contracts/polygon/README.md
**Motivation**
`README` should reference the `_processMessageFromRoot` internal method in `FxChildBaseTunnel` contract, not `_processMessageFromChild`.
h/t @Reinis-FRP for the catch.
> fix(polygon): Update typo in README

- packages/affiliates/libs/affiliates/utils.js
**Motivation**
https://app.clubhouse.io/uma-project/story/1618/update-dev-mining-script-with-configurable-reward-value
**Summary**
Changes default reward amount to be 35000 uma from 50000 uma.
**Details**
Did not make this configurable, since it doesn't need to be.  ends up outputting this for the config:
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1618/update-dev-mining-script-with-configurable-reward-value
> feat(affiliates): change dev mining total rewards down to 35000

- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
This allows inheriting UMIP-6 and UMIP-7 in other price identifier UMIPs without need to
rewrite `ETHBTC` and `BTCUSD` price feed configuration.
**Summary**
Add default price feed configuration for `ETHUSD` and `BTCUSD`.
**Details**
Currently default price feed configuration contains inverse identifiers (`USDETH` and `USDBTC`) that also could be referenced in the Expression price feed configuration, but this causes loosing precision (e.g. when dividing `Token/ETH` by rounded `USDETH` instead of multiplying `Token/ETH` with rounded `ETHUSD`. This would allow more compact price feed configuration examples in price identifier UMIPs referencing UMIP-6 or UMIP-7.
**Testing**
Check a box to describe how you tested these …
> feat(price-feed): Add default pf configs for ETHUSD and BTCUSD

- packages/core/scripts/collateral-umip/1_Propose.js
- packages/core/scripts/creator-umip/1_Propose.js
- packages/core/scripts/identifier-umip/1_Propose.js
- packages/core/scripts/optimistic-oracle-umip/1_Propose.js
- packages/core/scripts/register-contract-umip/1_Propose.js
- packages/core/scripts/register-contract-umip/2_VoteSimulate.js
- packages/core/scripts/register-contract-umip/3_Verify.js
- packages/core/scripts/umip-3/1_Propose.js
- packages/core/scripts/umip-8/1_Propose.js
- packages/core/scripts/voting-upgrade-umip/1_Propose.js
**Motivation**
To be used to execute pending UMIP's:
- [Upgrade `OptimisticOracle`](https://github.com/UMAprotocol/UMIPs/pull/349)
- [Register `OracleRootTunnel`](https://github.com/UMAprotocol/UMIPs/pull/350)
**Testing**
> feat: Add helper scripts to propose Admin transaction to register new contract

- packages/api/package.json
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/utils.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/emp-stats.ts
- packages/api/src/services/erc20-state.ts
- packages/api/src/services/index.ts
- packages/api/src/services/lsp-creator.ts
- packages/api/src/services/lsp-state.e2e.ts
- packages/api/src/services/lsp-state.ts
- packages/api/src/services/synthetic-prices.ts
- packages/api/src/tables/index.ts
- packages/api/src/tables/lsps/index.ts
- packages/api/src/tables/lsps/js-map.test.ts
- packages/api/src/tables/lsps/js-map.ts
- packages/api/src/tables/lsps/utils.ts
- packages/sdk/src/libs/clients/lsp-creator/client.e2e.ts
- yarn.lock
**Motivation**
https://app.clubhouse.io/uma-project/story/1445/ability-to-pull-in-token-information-for-lsp
**Summary**
Adds 2 lsp ingestion services. One that monitors the creator contract for newly launched tokens, and another which uses multicall to query lsp state. The state gets put into global app state. Api queries will be in the next PR.
**Details**
This does not expose lsp data through the API yet, just ingestion and puts into tables for later querying.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1445/ability-to-pull-in-token-information-for-lsp
> feat(api): 1445 add lsp state ingestion service

- packages/common/src/hardhat/tasks/fxTunnel.js
- packages/core/networks/1.json
- packages/core/networks/137.json
**Motivation**
Update mainnet address files with newly deployed addresses corresponding to UMIP proposals for (1) [the updated OptimisticOracle](https://github.com/UMAprotocol/UMIPs/pull/349) and (2) [the Polygon tunnel](https://github.com/UMAprotocol/UMIPs/pull/350).
**Summary**
This PR should not be merged in until the aforementioned UMIP's are merged in and governance transactions are executed.
A new release should be deployed after this PR is merged.
> feat: Update OptimisticOracle and Polygon Tunnel Addresses

- packages/api/src/services/actions.ts
**Motivation**
global tvl returning 0 from api
**Summary**
added missing return value on a branch
**Testing**
> fix(api): fix tvl showing 0

- packages/affiliates/payouts/devmining-status.json
**Motivation**
We changed dev mining rewards from 50000 to 35000
> fix(affiliates): change devmining-status totalReward from 50k to 35k

- packages/core/networks/80001.json
**Motivation**
Some existing Mumbai deployments are unverified on [mumbai.polygonscan.com](https://mumbai.polygonscan.com/), this PR addresses those addresses.
**Testing**
> feat(core): Update Mumbai addresses with verified ones

- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/queries/emp.ts
- packages/api/src/services/actions/emp.ts
- packages/api/src/services/actions/global.ts
- packages/api/src/services/actions/index.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1828/api-add-total-global-tvl-across-all-contract-types
**Summary**
This adds global routes, for now at `/global` and a total tvl across emps and lsps
**Details**
This adds the first global route calls at `/global` but with the intention of replacing calls at root ( `/`). This transition will require coordination with francesco, as root is being used to serve EMP state to not break current frontend code. 
Future PR will add additional calls as needed after coordinating with @Gamaranto and @Tulun 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1828/api-add-total-global-tvl-across-all-contract-types
> feat(api): 1828 start global routes, adding tvl

- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/queries/emp.ts
- packages/api/src/libs/queries/lsp.ts
- packages/api/src/services/actions/emp.ts
- packages/api/src/services/actions/global.ts
- packages/api/src/services/stats/emp.ts
- packages/api/src/services/stats/global.ts
- packages/api/src/services/stats/index.ts
- packages/api/src/services/synthetic-prices.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1837/api-add-total-global-historical-tvl-across-all-contract-types
https://app.clubhouse.io/uma-project/story/1827/add-global-unified-api-routes-across-contract-types
**Summary**
Adds global historical tvl calls as well as some helper utilities to discover contract state for any contract type from a single address. Because of time constraints i am putting these prs together.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1837/api-add-total-global-historical-tvl-across-all-contract-types
https://app.clubhouse.io/uma-project/story/1827/add-global-unified-api-routes-across …
> feat(api): 1837 global tvl history, various global utility calls

- packages/scripts/admin-proposals/addContractCreator.js
- packages/scripts/admin-proposals/collateral.js
- packages/scripts/admin-proposals/identifier.js
- packages/scripts/admin-proposals/registerContract.js
**Motivation**
Scripts should skip verification for any governance actions already completed.
**Testing**
> fix(scripts): Add checks in verify step if actions are already complete

- packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
- packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
**Motivation**
As part of automatic docs generation, we need to pull comment blocks from contracts. Some comments structure could be improved to increase readability.
**Summary**
Changed some LSP comment structures.
**Testing**
> feat(contract commenting): Change commenting style to better generate docs

- packages/insured-bridge-relayer/hardhat.config.ts
- packages/insured-bridge-relayer/package.json
- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/src/RelayerConfig.ts
- packages/insured-bridge-relayer/src/index.ts
- packages/insured-bridge-relayer/src/tsconfig.json
- packages/insured-bridge-relayer/test/index.ts
- packages/insured-bridge-relayer/tsconfig.json
**Motivation**
Insured bridge requires a bot. This PR adds the initial stub for this bot.
**Summary**
New bot stub.
**Testing**
> feat(insured-bridge): relayer bot initial stub

- packages/affiliates/apps/DevMiningRewards.js
- packages/affiliates/libs/affiliates/devmining_v2.js
- packages/affiliates/libs/affiliates/index.js
- packages/affiliates/libs/contracts.js
- packages/affiliates/scripts/basic-contract.js
- packages/affiliates/test/mocha/contracts.js
- packages/affiliates/test/mocha/devmining-v2.js
**Motivation**
https://app.clubhouse.io/uma-project/story/1776/update-the-dev-mining-script-to-use-tvl-instead-of-tvm-in-the-calculation
**Summary**
Adds tvl based rewarding as "v2" of devmining script. Keeps in place the original dev mining calculation but adds a second version based on collaterals only.  Much of the code is the same between the original version but some modifications.
Once merged the default unless specified otherwise will be to run v2. This should not be merged until after aug 2nd, since this is not needed until after.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1776/update-the-dev-mining-script-to-use-t …
> feat(affiliates): 1776 add v2 dev mining based on tvl

- packages/scripts/admin-proposals/addContractCreator.js
- packages/scripts/admin-proposals/collateral.js
**Motivation**
Fixes two small bugs in the admin proposal scripts.
**Summary**
* The collateral proposal script expects a `--fee` flag rather than `--fees`, but `const argv` was looking for `fees`.
* Contract creator verification for Polygon was hardcoded to the Polygon Governor address. This fix checks the newly registered Polygon contract address instead.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(admin): small bugfixes in admin proposal scripts

- packages/contracts-frontend/package.json
**Motivation**
"main" causes build issues in webpack
**Summary**
Remove "main".
**Testing**
**Issue(s)**
N/A
> fix(contracts-frontend): main causes build issues in webpack

- packages/core/scripts/local/GasEthQuery.js
This PR updates the query used to determine average gas prices such that it accounts for changes to the gas fee market made by EIP-1559
> Updates GasEthQuery to use receipt_effective_gas_price instead of raw gas price

- packages/api/src/libs/queries/emp.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1942/gcr-and-identifier-not-displaying-correctly
**Summary**
Does an extra calculation when identifier price is available to the gcr. So `gcr = total collateral / total tokens / identifier price`. The old gcr calculation is called `rawGcr` which is just `total collateral / total tokens`. No changes needed on frontend.
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1942/gcr-and-identifier-not-displaying-correctly
> fix(api): 1942 add price converted gcr field to emp state

- ci/generate_lerna_config.sh
- ci/tests/test-integration.sh
- packages/core/migrations/2_deploy_finder.js
- scripts/ovm/run-optimism.sh
**Motivation**
Add new integration tests on CI pipeline
**Testing**
> improve (CircleCI): Add integration tests

- packages/core/test/insured-bridge/e2e/InsuredBridge.e2e.js
**Motivation**
There was a small error in the e2e tests. This PR fixes this
> fix(e2e): fix broken test beforeEach

- packages/sdk/package.json
- packages/sdk/src/stores/google-datastore/store.e2e.ts
- packages/sdk/src/stores/google-datastore/store.ts
- yarn.lock
**Motivation**
https://app.clubhouse.io/uma-project/story/1882/add-google-datastore-store-in-sdk
**Summary**
This adds google data store integration based on the "store" interface.  There are some hacky things here because actually it was quite difficult to get some of the functionality cleanly out of the google datastore client.  I've commented on most of the wierdness.
**Details**
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1882/add-google-datastore-store-in-sdk
> feat(sdk): 1882 complete google datastore store integration and tests

- packages/financial-templates-lib/src/helpers/GasEstimator.js
**Motivation**
The change implemented on Monday to fix the `GasEstimator` made it incompatible with polygon. This PR fixes this.
> fix(GasEstimator):fix estimator on polygon

- packages/common/src/HardhatConfig.ts
- packages/core/contracts-ovm/insured-bridge/implementation/BridgePool.sol
- packages/core/test/insured-bridge/BridgePool.js
**Motivation**
This improves slow relayer UX because they no longer need to separately call `OptimisticOracle.settle` in addition to `BridgePool.settleRelay` to recoup their price request bond.
Tests were also added in this PR to improve readability.
**Testing**
> improve(insured-bridge): Settle resolved optimistic price requests that passed dispute period

- packages/sdk/src/index.ts
- scripts/ovm/run-optimism.sh
Signed-off-by: evaldofelipe <contato@evaldofelipe.com>
**Motivation**
The current method used build all the images on local, with this PR the images will be downloaded from the source repo of project from docker hub  
**Testing**
> Fix (CircleCI): Adjust images for integration tests

- packages/scripts/admin-proposals/simulateVote.js
**Motivation**
In the latest UMIP round, we ran into two issues with the vote simulation script.
1. The foundation wallet was not given enough ETH for a high-gas-price environment.
2. There was a bug with an undefined `id` variable.
**Summary**
This fix gives the foundation wallet 10 ETH on a local mainnet fork for vote simulation purposes and corrects `id` to `proposalId` for the governance execution step.
**Details**
There are also some additional console logs and the governor execution step comes from `accounts[0]` rather than the foundation wallet.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(vote): increase ETH for foundation wallet and fix variable

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/services/actions/emp.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/lsp-state.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/2249/post-expiry-ui-does-not-show-the-user-we-are-waiting-for-a-price-from-the-oo
**Summary**
Theres a bug where state updates stop happening on api contracts. This change removes block update events and updates on an env configurable timer instead. By default if not specified it will update every 10 minutes. 
**Details**
This also updates some logs to make it more obvious when things are happening. 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/2249/post-expiry-ui-does-not-show-the-user-we-are-waiting-for-a-price-from-the-oo
> fix(api): remove block events and update on timer

- packages/common/package.json
- packages/fx-tunnel-relayer/package.json
- packages/fx-tunnel-relayer/src/RelayerConfig.ts
**Motivation**
Small nit changes I made while integration testing this bot in production.
**Testing**
> fix(fx-tunnel-relayer): Bump maticjs version and update RelayerConfig

- packages/core/README.md
**Motivation**
The deployment process should be documented.
**Summary**
This adds a few lines to the readme to document the deployment process.
**Testing**
**Issue(s)**
N/A
> improve(core): add deployment and verification instructions

- packages/common/.mocharc.js
- packages/common/hardhat.config.js
- packages/common/package.json
- packages/common/test/AncillaryDataParser.js
- packages/common/test/TransactionUtils.js
**Motivation**
There are tests in common still relying on truffle migrations and core.
**Summary**
Aligned these tests with our new truffle-less hardhat setup.
**Testing**
**Issue(s)**
N/A
> improve(common): update common tests to no longer require core or truffle

- packages/api/package.json
- packages/sdk/README.md
- packages/sdk/build.js
- packages/sdk/package.json
- packages/sdk/src/clients/lsp-creator/client.e2e.ts
- packages/sdk/src/clients/lsp-creator/client.ts
- packages/sdk/src/clients/registry/client.e2e.ts
- packages/sdk/src/clients/registry/client.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tables/README.md
- packages/sdk/src/types.d.ts
- packages/sdk/templates/index.d.ts
- packages/sdk/tsdx.config.js
- yarn.lock
**Motivation**
https://app.shortcut.com/uma-project/story/2271/prepare-sdk-for-use-on-a-fe
**Summary**
This uses rollup-replace to go through and replace instances of `@uma/contracts-node` with `@uma/contracts-frontend` when building the frontend version. There ends up being 2 versions of the sdk in `dist/web` and `dist/node`.  Importing remains the same, so this seems to still run correctly on both api and a test frontend app without any changes.
This adds 2 new build commands
- `yarn build:web` - which builds to the frontend
- `yarn build:node` - which builds to node
- `yarn build` - which has been modified to run a script `build.js` so both builds are moved to independent folders
**Details**
Shows sdk size in frontend
**Testing**
Check …
> feat(sdk): add frontend build process to sdk

- packages/core/contracts/insured-bridge/BridgePool.sol
- packages/core/test/insured-bridge/BridgePool.js
- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/financial-templates-lib/src/price-feed/InsuredBridgePriceFeed.ts
- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
The `depositContract` address is currently emitted in the `DepositRelayed` event and included in the Optimistic price request's ancillary data. This is redundant as `chainId` is already included and `chainId => depositContract` is mapped in the `BridgeAdmin` address that is set upon construction of the `BridgePool`.
**Summary**
This change removes an external call to the `BridgeAdmin` and reduces the gas cost of `relayDeposit` by 10% (~100k gas).
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(insured-bridge): Remove deposit contract from BridgePool relay params

- packages/api/src/apps/api/app.ts
- packages/api/src/apps/lsp_api/app.ts
- packages/api/src/libs/utils.ts
**Motivation**
https://app.shortcut.com/uma-project/story/2354/fix-lsp-api-contract-discovery
**Summary**
There are 2 minor issues here:
1. lsp app incorrectly passed events
2. block interval was opinionated on block numbers, throwing a  lot of errors during testing
Fixed the lsp event issue by passing data correctly into the events. Second issue was fixed by removing assert from utility and handling the issue by the caller. In this case we choose to just not run updates if startblock >= endblock. 
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2354/fix-lsp-api-contract-discovery
> fix(api): discovery events and block interval check

- packages/scripts/setupFork.sh
- packages/scripts/src/admin-proposals/addContractCreator.js
- packages/scripts/src/admin-proposals/collateral.js
- packages/scripts/src/admin-proposals/executeProposal.js
- packages/scripts/src/admin-proposals/identifier.js
- packages/scripts/src/admin-proposals/registerContract.js
- packages/scripts/src/admin-proposals/simulateVote.js
**Motivation**
Ran into a couple of bugs that needed fixing in the admin proposal scripts.
**Summary**
- Fixed the directory link in the `setupFork` script
- Added some `await`s for getting contract addresses in the proposal scripts
**Details**
These are minor fixes following the big refactoring to remove Truffle. The `identifier` proposal script has been tested in production, with identical `await`-related fixes added to the other scripts but not tested.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(scripts): add some awaits and fix directory link

- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/proposer.js
**Motivation**
We should not approve collateral for blacklisted identifiers.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(optimistic-oracle-proposer): Should not approve collateral for blacklisted identifiers

- packages/common/src/PriceIdentifierUtils.ts
**Motivation**
Need to temporarily blacklist the stablespread identifier bc of data inconsistency. 
**Testing**
**Issue(s)**
NA
> fix(price-identifier-utils): Blacklist stablespread identifier

- packages/sdk/README.md
- packages/sdk/package.json
- packages/sdk/src/across/README.md
- packages/sdk/src/across/feeCalculator.test.ts
- packages/sdk/src/across/feeCalculator.ts
- packages/sdk/src/across/index.ts
- packages/sdk/src/index.ts
- yarn.lock
**Motivation**
https://app.shortcut.com/uma-project/story/2401/add-lp-fee-calculator-in-sdk
**Summary**
This is almost a direct port of [chris's work](https://github.com/UMAprotocol/protocol/blob/master/packages/financial-templates-lib/src/helpers/acrossFeesCalculator.ts) to give access to the across dapp. Added some additional docs based on the tests. 
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2401/add-lp-fee-calculator-in-sdk
> feat(sdk): add direct port of fee calculators and add docs

- packages/sdk/package.json
**Motivation**
https://app.shortcut.com/uma-project/story/2418/fix-sdk-release-build
**Summary**
Edit prepare script and min file size (unrelated to issue)
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2418/fix-sdk-release-build
> fix(sdk): edit prepare process for release

- packages/sdk/src/clients/bridgeDepositBox/README.md
- packages/sdk/src/clients/bridgeDepositBox/client.e2e.ts
- packages/sdk/src/clients/bridgeDepositBox/client.ts
- packages/sdk/src/clients/bridgeDepositBox/index.ts
- packages/sdk/src/clients/index.ts
**Motivation**
https://app.shortcut.com/uma-project/story/2411/add-bridge-deposit-box-client-to-sdk
**Summary**
Add a basic client and event decoder to sdk for bridge deposit box. Needed to support frontend across work.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2411/add-bridge-deposit-box-client-to-sdk
> feat(sdk): add bridge deposit box client

- packages/disputer/index.js
- packages/liquidator/index.js
- packages/monitors/index.js
- packages/serverless-orchestration/src/ServerlessSpoke.js
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(bots): add log waiting for happy bot paths

- packages/disputer/index.js
- packages/liquidator/index.js
- packages/monitors/index.js
- packages/serverless-orchestration/src/ServerlessSpoke.js
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: revert wait for logs, increase log wait in spoke

- packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
- packages/core/contracts/oracle/implementation/test/SkinnyOptimisticRequesterTest.sol
- packages/core/contracts/oracle/interfaces/SkinnyOptimisticOracleInterface.sol
**Motivation**
Following style implemented in #3427 
**Testing**
> refactor(skinny-oo): Make variable naming style consistent with rest of repo

- packages/sdk/src/across/README.md
- packages/sdk/src/across/constants.ts
- packages/sdk/src/across/gasFeeCalculator.e2e.ts
- packages/sdk/src/across/gasFeeCalculator.ts
- packages/sdk/src/across/index.ts
- packages/sdk/src/across/utils.test.ts
- packages/sdk/src/across/utils.ts
**Motivation**
https://app.shortcut.com/uma-project/story/2519/add-across-fast-slow-relay-gas-prices-to-sdk
**Summary**
Adds a gasFeeCalculator file for using to estimate gas fees when relaying. Also does an end to end test with documentation to show how to get the final result. Has estimations for eth/erc20/uma slow/fast transfers.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2519/add-across-fast-slow-relay-gas-prices-to-sdk
> feat(sdk): add across gas fee estimations

- packages/insured-bridge-relayer/src/Relayer.ts
**Summary**
- Some logs should have level downgraded from `warn` to `debug` so they don't appear on Slack.
- Replace key in log named `type` to `message`. Without the `message` key, the Winston transporter throws an error.
**Testing**
> fix(insured-bridge-relayer): Fix usage of Logger

- packages/scripts/src/admin-proposals/executeProposal.js
**Motivation**
Fixes the comments in the `executeProposal.js` script to reflect the new directory structure.
**Summary**
Adds `/src/`
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(script): minor fix to the comments

- packages/sdk/package.json
- packages/sdk/src/across/clients/README.md
- packages/sdk/src/across/clients/bridgePool.e2e.ts
- packages/sdk/src/across/clients/bridgePool.ts
- packages/sdk/src/across/index.ts
- packages/sdk/src/across/transactionManager.ts
- packages/sdk/src/across/utils.ts
- packages/sdk/src/clients/bridgePool/client.ts
- yarn.lock
**Motivation**
https://app.shortcut.com/uma-project/story/2735/bridge-pool-client-for-sending-transactions
**Summary**
Adds the final bridgepool client with read/write capability, meant for the pool tab.
**Details**
This breaks previous compatibility and code will need to migrate to use this new version.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2735/bridge-pool-client-for-sending-transactions
> feat(sdk)!: add read/write pool client and basic tx manager

- packages/affiliates/gas-rebate/VoterGasRebate.js
- packages/common/src/TransactionUtils.ts
- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
**Motivation**
Adds more precision to #3520 to ensure that `InsuredBridgeL1Client` finds the exact block containing the `deposit.quoteTime`
**Testing**
> improve(common): Improve precision of block finder common util

- packages/core/contracts/insured-bridge/BridgePool.sol
**Motivation**
There are require statements in the `BridgePool `contract without error messages.
**Testing**
> improve(insured-bridge): Add require messages

- packages/core/contracts/insured-bridge/BridgePool.sol
- packages/core/test/insured-bridge/BridgePool.js
- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/insured-bridge-relayer/test/Relayer.ts
**Motivation**
Reverts #3516 
**Testing**
> improve(insured-bridge): Remove deploymentTime

- packages/core/contracts/insured-bridge/BridgePool.sol
- packages/core/test/insured-bridge/BridgePool.js
- packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js
**Motivation**
This reverts commit d1a07f0c4e244acaf58f51a20c9a8d6e539f1bdd.
This PR cannot be merged in until the BridgePool contracts in production are paused and new contracts are deployed using code that includes this PR.
**Testing**
> improve(insured-bridge): Reduce verbosity of _getDepositHash()

- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/src/RelayerConfig.ts
- packages/insured-bridge-relayer/test/Relayer.ts
**Motivation**
Hardcoding the deployment block height saves a `findBlockForTime` call in the unhappy case where a `deposit` can't be found on the first run in the disputer flow.
**Testing**
> optimize(insured-bridge-relayer): Hardcode deployment block height

- packages/bot-strategy-runner/src/ConfigBuilder.ts
- packages/common/src/FormattingUtils.ts
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts
- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/src/RelayerConfig.ts
**Motivation**
`deposit.l1Token` has checksummed address, while `RelayerConfig.deployTimestamps` keys by lower-case.
**Testing**
> fix(insured-bridge-relayer): Key deployTimestamps by lowercase addresses

- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
Relayer and Disputer both send logs before they submit transactions, which makes it easier to debug any errors in the bot. The Finalizer does not do this.
**Testing**
> improve(across-relayer): Should log before sending settle transaction

- packages/sdk/src/across/clients/bridgePool.e2e.ts
- packages/sdk/src/across/clients/bridgePool.ts
- packages/sdk/src/clients/bridgePool/client.ts
- packages/sdk/src/index.ts
- packages/sdk/src/utils.ts
**Motivation**
https://app.shortcut.com/uma-project/story/2955/improve-event-handling-in-bridgepool-sdk-client
**Summary**
Adds another function to process events from transaction receipt to the PoolEventState class.  This also dedupes events in both event handling functions to ensure we dont get wrong balance. Order of events for these particular states is not important. 
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2955/improve-event-handling-in-bridgepool-sdk-client
> feat(sdk): add tx receipt decoding events to bridgepool client

- packages/core/contracts/oracle/implementation/test/SkinnyOptimisticRequesterTest.sol
- packages/core/networks/1.json
- packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
- packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
- packages/optimistic-oracle/index.js
- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/index.js
- packages/optimistic-oracle/test/skinnyProposer.js
**Motivation**
User can configure the `index.js` file to work with a "SkinnyOptimisticOracle" contract. A new unit test file that replicates the testing for the normal "OptimisticOracle" is created.
**Summary**
All changes to `proposer.js` and `index.js` are backwards compatible with existing bots and they will not require any modifications to keep working with the `OptimisticOracle`.
**Testing**
> feat(optimistic-oracle-proposer): Can propose, dispute, and settle SkinnyOptimisticOracle price requests

- packages/sdk/src/across/clients/README.md
- packages/sdk/src/across/clients/bridgePool.test.ts
- packages/sdk/src/across/clients/bridgePool.ts
BREAKING CHANGE: previewRemoval function api is changed to accept user object
**Motivation**
https://app.shortcut.com/uma-project/story/2983/pool-removal-preview-looks-like-calculations-might-be-incorrect
**Summary**
Changed some simple calculations in the previewRemoval function
**Details**
breaks across, so across will need to update when sdk version is updated
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2983/pool-removal-preview-looks-like-calculations-might-be-incorrect
> fix(sdk)!: fix pool removal preview calcs

- packages/sdk/src/across/clients/bridgePool.e2e.ts
- packages/sdk/src/across/clients/bridgePool.ts
**Motivation**
https://app.shortcut.com/uma-project/story/2989/total-pool-size-is-wrong
**Summary**
Remove pending reserves from total pool size calc
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/2989/total-pool-size-is-wrong
> fix(sdk): fix total pool size, remove pendingReserves

- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts
**Motivation**
Using rate model described in [UMIP-136](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-136.md)
**Testing**
> feat(financial-templates-lib): Add UMA rate model to InsuredBridgePriceFeed default config

- packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
- packages/financial-templates-lib/src/clients/OptimisticOracleEventClient.ts
- packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
- packages/monitors/index.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
**Motivation**
Client should be backwards compatible with OptimisticOracle events but also be configurable to query SkinnyOO events
**Testing**
> feat(optimistic-oracle-event-client): Add compatibility with SkinnyOptimisticOracle events

- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/financial-templates-lib/src/price-feed/InsuredBridgePriceFeed.ts
- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/financial-templates-lib/test/price-feed/InsuredBridgePriceFeed.js
- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
The current L1Client has some inefficiencies in them. This PR address these issues.
> fix(L1-client): optimize how the L1 client fetches some internal data

- packages/sdk/src/across/clients/bridgePool.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3162/fix-pool-size-regression
**Summary**
Undo a change from bad rebase to fix pool size 
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3162/fix-pool-size-regression
> fix(sdk): fix across pool size calculation regression

- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/insured-bridge-relayer/src/RelayerConfig.ts
**Motivation**
- `RelayerConfig`: Incorrectly casts a `string` to `Boolean()`, which produces unexpected results. Take `RELAYER_ENABLED=false` for example, this casts `Boolean('false") = true` instead of setting `RELAYER_ENABLED` to false`.
- 15 minutes is set improperly in L1 client
**Testing**
> fix(across-relayer): Two small patches

- packages/monitors/index.js
- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
- packages/monitors/test/index.js
**Motivation**
Should be backwards compatible and not affect monitor in production.
**Testing**
> feat(monitors): Add SkinnyOptimisticOracle monitor

- packages/contract-notifier/README.md
- packages/contract-notifier/index.js
- packages/contract-notifier/package.json
- packages/contract-notifier/src/ContractNotifier.js
**Motivation**
With the increasing usage of UMA financial contracts it would be beneficial to add automated notifier that tracks and reminds on soon to expire contracts.
**Summary**
This application implements expiring contracts notifier.
**Details**
Contract notifier uses UMA API to consult on all known financial contracts, filters soon to expire contracts and notifies them through logging mechanism that can forward it to Slack. Notified contracts are stored on Google Datastore, so on repeated runs the bot does not repeatedly notify the same contracts.
**Testing**
> feat(contract-notifier): implement expiring contracts notifier

- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/test/Relayer.ts
**Motivation**
The disputer should be able to send batches of disputes. This PR enables this.
**Testing**
> feat(across-relayer): enable batch disputing

- packages/common/src/ProviderUtils.ts
**Motivation**
When we generate keys in getWeb3 we don't respect user-provided network names.
**Summary**
This just adds a parameter to support this.
**Testing**
**Issue(s)**
N/A
> fix: minor fix to get web3 to respect user-provided network

- packages/scripts/README.md
**Motivation**
N/A
**Summary**
N/A
**Testing**
**Issue(s)**
N/A
> fix: fix typo in readme

- packages/financial-templates-lib/package.json
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts
- packages/insured-bridge-relayer/package.json
- packages/insured-bridge-relayer/src/RelayerConfig.ts
- yarn.lock
**Motivation**
We should reduce instances where we hardcode this JSON object, and read from a single source.
**Testing**
> improve(insured-bridge-price-feed): Use constant RATE_MODEL from @uma/sdk package

- packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ParentMessenger.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/test/Polygon_ChildMessengerMock.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/test/Polygon_ParentMessengerMock.sol
- packages/core/contracts/cross-chain-oracle/interfaces/ChildMessengerInterface.sol
- packages/core/contracts/cross-chain-oracle/interfaces/ParentMessengerInterface.sol
- packages/core/networks/5.json
- packages/core/networks/80001.json
- packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.js
- packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.js
- packages/core/test/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.js
- packages/core/test/cross-chain-oracle/chain-adapters/Polygon_ParentMessenger.js
**Motivation**
These adapters re use contracts from `external/polygon` that currently enable the cross chain contracts in `contracts/polygon` that only work for Polygon.
**Testing**
> feat(cross-chain-oracle): Add Polygon adapters

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
**Motivation**
We would like to be able to connect to the Boba network in hardhat.
**Summary**
Adds Boba to the network configs. Note: infura will not work for this network.
**Testing**
**Issue(s)**
N/A
> feat: add boba network

- packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol
- packages/core/test/cross-chain-oracle/chain-adapters/Arbitrum_ChildMessenger.js
**Motivation**
Tests broke to merge conflicts from #3628 
**Testing**
> fix(cross-chain-oracle): Fix unit tests

- packages/core/contracts/cross-chain-oracle/GovernorHub.sol
- packages/core/contracts/cross-chain-oracle/OracleHub.sol
**Motivation**
The inclusion of multi caller has proven to be very useful in a number of our other contracts. This PR adds it to the `OracleHub` and `OracleSpoke` to enable batched calls to make complex operations more atomic and efficient.
> feat(cross-chain-oracle): Add multicaller to oracleHub and spoke

- packages/financial-templates-lib/src/logger/PagerDutyTransport.ts
- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/test/Relayer.ts
- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
**Motivation**
This PR does two things:
1) Generates `error` level log on disputes and slow relays.
2) fixes the OO bot to decode encoded ancillary data.
> feat(logging): add error logging on disputes and slow relay. Decode OO ancillary data

- packages/insured-bridge-relayer/src/RelayerConfig.ts
> improve(across-relayer): Add Optimism start block

- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
After launching on Optimism we realized a few small issues due to multiple chain IDs. This PR addresses them.
> fix(across-bots): address issues found when launching on optimism regarding multiple chainIds

- packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
> fix(across-relayer): Checksum address before comparing

- packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
Relayer should not query events, we can easily move event-querying-logic into L2 client if we do this refactor and add an additional L2 client external function.
**Testing**
> refactor(across-relayer): Remove event querying from relayer code

- packages/sdk/src/across/clients/bridgePool.ts
- packages/sdk/src/across/constants.ts
- packages/sdk/src/across/feeCalculator.test.ts
- packages/sdk/src/across/feeCalculator.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3275/implement-projected-apy-calculation-in-sdk
**Summary**
Exposes a function already in the sdk for calcultaing instant apr fees. Uses this and rate model, utilization and adds it to pool data.
**Details**
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3275/implement-projected-apy-calculation-in-sdk
> feat(sdk): add projected apr calculation

- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
We should add log to this loop in case bot gets stuck here. This loop is highly likely to break in the future if the block history is large and RPC API endpoints are returning slowly (or we get rate-limited).
**Testing**
> improve(across-relayer): Add log to block search in unhappy dispute case

- packages/insured-bridge-relayer/src/RelayerConfig.ts
- packages/insured-bridge-relayer/test/index.ts
**Motivation**
- Using `assert` does not produce logs as expected, so throw errors which we know our logger can handle.
- There is no advantage to hardcoding supported chain ID's in the code, and it increases friction when deploying bots for new networks.
**Testing**
> improve(across-relayer): Remove hardcoded supported chain IDs list and throw errors instead of asserting

- packages/core/networks/1.json
**Motivation**
The new LSP creator has been done and audited for a while. It should be deployed.
**Summary**
Added the deployed address to the networks file.
**Testing**
**Issue(s)**
N/A
> feat: add new LSPCreator deployment

- packages/core/deploy/040_deploy_rate_model_store.js
- packages/core/networks/1.json
**Motivation**
Deployed new rate model store and uploaded 4 existing rate models via multicall.
**Testing**
> feat(core): Deploy new RateModel

- packages/sdk/src/across/gasFeeCalculator.ts
- packages/sdk/src/clients/etherchain/client.e2e.ts
- packages/sdk/src/clients/etherchain/client.ts
- packages/sdk/src/clients/etherchain/index.ts
- packages/sdk/src/clients/index.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3420/make-sure-the-fees-in-ui-matches-with-how-the-bots-are-calculating-fees
**Summary**
Match the fees with the ones calculated by the bots.
**Testing**
> improve(sdk): calculate fees using the same logic as the bots

- packages/core/contracts/cross-chain-oracle/OracleHub.sol
- packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/Arbitrum_ParentMessenger.sol
- packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
- packages/core/package.json
- yarn.lock
**Motivation**
OZ identified the following issues:
There are "TODO" comments in the code base that should be tracked in the project's issues backlog.
For example:
Line 37 of Arbitrum_ParentMessenger contract
Line 25 of Optimism_ChildMessenger contract
Lines 83 and 146 of OracleHub contract.
This PR either removes or implements these todos.
**Testing**
> fix(cross-domain-oracle): [N05] fixed outstanding todos

- packages/scripts/src/local/getHistoricalPrice.js
**Motivation**
https://github.com/UMAprotocol/protocol/issues/3675
**Summary**
Adds pretty print option to the Winston debugger instance
**Testing**
**Issue(s)**
Fixes #3675
> style (getHistoricalPrice): Add pretty print for JSON output from getHistoricalPrice

- packages/sdk/src/across/constants.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3571/fix-sdk-rate-model-address-for-uma
**Summary**
Replaces an all lower address with the proper checksum address in the rate model.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3571/fix-sdk-rate-model-address-for-uma
> fix(sdk): fix rate model address for uma

- packages/core/test/financial-templates/optimistic-rewarder/OptimisticRewarder.js
**Motivation**
Ci is broken due to a failed merge.
**Summary**
This fixes the event lookup.
**Testing**
**Issue(s)**
N/A
> fix: fix ci breakage from failed merge

- packages/sdk/src/across/README.md
- packages/sdk/src/across/constants.ts
- packages/sdk/src/across/gasFeeCalculator.e2e.ts
- packages/sdk/src/across/gasFeeCalculator.ts
- packages/sdk/src/across/index.ts
BREAKING CHANGE: calls to previous gas estimator must migrate to new interface
**Motivation**
https://app.shortcut.com/uma-project/story/3577/create-one-function-that-computes-fees-in-the-sdk
**Summary**
This adds a function for the end user to call with minimal inputs, and returns only the fee values needed for calling `depositBox.deposit`. See docs for details.  Missing from this implementation are non-percentage values, ie actual amounts taken from the relayed value. Future functions can be added for more frontend friendly calls. 
IMPORTANT: this breaks previous interfaces, so will require changes on across code to integrate
**Testing**
**Issue(s)** …
> feat(sdk)!: add improved gas fee function

- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/src/index.ts
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: [across] address issue log mapping

- packages/common/src/HardhatConfig.ts
**Motivation**
Deployments on Polygon failed with inherited auto `gasPrice` setting.
**Summary**
Set 30GWei gas price for Polygon deployments.
**Testing**
> fix(common): set polygon gas price manually

- packages/api/src/services/collateral-prices.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3691/api-startup-unable-to-parse-some-floats-when-fetching-prices
**Summary**
This was causing errors when quering certain prices which returned decimals longer than 18 digits, ex: `0.00004841587973576128`. So we use toFixed to truncate to 18.
**Testing**
**Issue(s)**
https://app.shortcut.com/uma-project/story/3691/api-startup-unable-to-parse-some-floats-when-fetching-prices
> fix(api): limit decimals when calling ethers.parseUnits

- packages/across-monitor/README.md
- packages/across-monitor/package.json
- packages/across-monitor/src/AcrossMonitor.ts
- packages/across-monitor/src/AcrossMonitorConfig.ts
- packages/across-monitor/src/RelayEventFetcher.ts
- packages/across-monitor/src/RelayEventProcessor.ts
- packages/across-monitor/src/index.ts
- packages/across-monitor/src/tsconfig.json
- packages/across-monitor/tsconfig.json
**Motivation**
With the increased use of Across bridge and expected development of independent relay network more visibility on the activity is required.
**Summary**
Across monitor bot implementation is added.
**Details**
Across monitor bot currently checks bridge pool utilization and relay related events triggered by unknown addresses.
**Testing**
> feat(across-monitor): Implement Across monitor bot

- packages/financial-templates-lib/src/price-feed/CreatePriceFeed.ts
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts
- packages/financial-templates-lib/src/price-feed/USPACPriceFeed.ts
- packages/financial-templates-lib/test/price-feed/USPACPriceFeed.js
Price feed implementation for uSPAC5 - price identifier for index of 5 most active SPACs
See UMIP: https://github.com/UMAprotocol/UMIPs/pull/428
> Price feed implementation for uSPAC5 - price identifier for index of 5 most active SPACs

- packages/sdk/src/oracle/constants.ts
- packages/sdk/src/oracle/services/index.ts
- packages/sdk/src/oracle/services/optimisticOracle.ts
- packages/sdk/src/oracle/services/tests/optimisticOracle.e2e.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3779/add-basic-erc20-service-for-oo-in-sdk
**Summary**
Very basic OO client with functionality for skinny oo ui
**Testing**
> feat(sdk): add basic optimistic oracle client for getting requests

- packages/across-monitor/src/AcrossMonitor.ts
**Motivation**
Non-whitelisted relayer module on Across monitor was missing relevant transaction hash link.
**Summary**
Adds transaction hash link to Across monitor non-whitelisted relayer module.
**Testing**
> feat(across-monitor): Add transaction hash to across monitor logs

- packages/financial-templates-lib/src/helpers/GasEstimator.ts
- packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
- packages/insured-bridge-relayer/src/MulticallBundler.ts
- packages/insured-bridge-relayer/src/ProfitabilityCalculator.ts
- packages/insured-bridge-relayer/src/Relayer.ts
- packages/insured-bridge-relayer/test/CrossDomainFinalizer.ts
- packages/insured-bridge-relayer/test/ProfitabilityCalculator.ts
- packages/insured-bridge-relayer/test/Relayer.ts
**Motivation**
Logs produced by the profitability module are not very useable. This PR refines these lots to make them more useable.
**Summary**
sample post PR log:
**Testing**
> feat(across-bots): improve profitability log detail

- packages/core/networks/288.json
- packages/scripts/src/ManualRelay.js
**Motivation**
We would like to have a script to manually relay a depost.
**Summary**
Adds a script to manually relay a deposit.
**Testing**
**Issue(s)**
N/A
> feat: add manual relay script

- packages/common/src/TimeUtils.ts
- packages/common/src/hardhat/tasks/identifiers.ts
- packages/common/src/hardhat/tasks/xchainSetup.ts
- packages/core/contracts/cross-chain-oracle/README.md
- packages/core/deploy/043_deploy_oracle_spoke.js
- packages/core/deploy/044_deploy_oracle_hub.js
- packages/core/deploy/045_deploy_governor_spoke.js
- packages/core/deploy/046_deploy_governor_hub.js
- packages/core/deploy/047_deploy_boba_parent_messenger.js
- packages/core/deploy/048_deploy_boba_child_messenger.js
- packages/core/networks/1.json
- packages/core/networks/288.json
- packages/core/networks/42161.json
> feat(core): Deploy + Setup Boba OptimisticOracle and Bridge contracts

- packages/sdk/src/across/gasFeeCalculator.e2e.ts
- packages/sdk/src/across/gasFeeCalculator.ts
- packages/sdk/src/across/test/rateModel.e2e.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3917/update-sdk-rate-model-calculations
**Summary**
change erc20 to use eth gas rates, also update how we converted gas to wei to use ethers tooling
**Testing**
> fix(sdk): update gas calculation for across

- packages/sdk/src/oracle/README.md
- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/index.ts
- packages/sdk/src/oracle/services/erc20.ts
- packages/sdk/src/oracle/services/optimisticOracle.ts
- packages/sdk/src/oracle/services/tests/erc20.e2e.ts
- packages/sdk/src/oracle/services/tests/optimisticOracle.e2e.ts
- packages/sdk/src/oracle/store/index.ts
- packages/sdk/src/oracle/store/read.ts
- packages/sdk/src/oracle/store/test/store.test.ts
- packages/sdk/src/oracle/store/write.ts
- packages/sdk/src/oracle/tests/client.e2e.ts
- packages/sdk/src/oracle/types/index.ts
- packages/sdk/src/oracle/types/misc.ts
- packages/sdk/src/oracle/types/state.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3813/wire-up-and-publicly-expose-oo-client-functions
**Summary**
Exposes basic client to frontend, allowing user to set the current request as well as the currently logged in user.  Next PR should add state updates based on collateral balances and allowances.
**Testing**
> feat(sdk): expose basic oo client interface

- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/index.ts
**Motivation**
https://app.shortcut.com/uma-project/story/3963/fix-oracle-client-exporting
**Summary**
This changes the exports around oracle client factory so they are accessible outside the sdk. 
**Testing**
> fix(sdk): properly export oo client factory

- packages/common/src/hardhat/tasks/finder.ts
- packages/common/src/hardhat/tasks/xchainSetup.ts
- packages/core/contracts/cross-chain-oracle/README.md
**Motivation**
There are a lot of moving parts and contract state to set before one can confidently say that an OptimisticOracleon an L2 is set up. The goal of this script is for users to have a source of truth in determining whether the setup is complete.
**Testing**
> feat(cross-chain-oracle): Add verification script to cross chain oracle setup

- packages/core/networks/1.json
**Motivation**
We should have the addresses of Bridge pools within the netwroks file. This PR addresses this.
**Summary**
Added bridge pools to 1.json.
**Testing**
>  (core): Add All bridge Pool addresses deployed so far (including new WBTC Pool)

- packages/common/src/Constants.ts
- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/common/src/hardhat/tasks/collateralWhitelist.ts
- packages/common/src/hardhat/tasks/xchainSetup.ts
- packages/core/contracts/cross-chain-oracle/README.md
- packages/core/deploy/043_deploy_oracle_spoke.js
- packages/core/deploy/045_deploy_governor_spoke.js
- packages/core/deploy/051_deploy_admin_child_messenger.js
- packages/core/networks/100.json
**Motivation**
Adds xDai deployments.
> feat(deployments): Add xDai deploys

- packages/common/src/hardhat/tasks/artifacts.ts
**Motivation**
Bug fix.
**Summary**
Correctly generates chainId from filename.
**Testing**
**Issue(s)**
N/A
> fix: fix #3747

- packages/common/package.json
- packages/common/src/TransactionUtils.ts
- packages/disputer/test/index.js
- packages/financial-templates-lib/src/helpers/GasEstimator.ts
- packages/liquidator/package.json
- packages/liquidator/test/index.js
- packages/trader/package.json
- yarn.lock
**Motivation**
Boba requires legacy transactions to be sent.
**Testing**
> improve(gas-estimator): Add Boba as legacy network

- packages/across-monitor/src/AcrossMonitor.ts
**Motivation**
In order to improve visibility dedicated channel for `across-monitor` bot should be created.
**Summary**
`notificationPath` is changed to dedicated `across-monitor` channel.
**Details**
This PR would also require adding `across-monitor` channel webhook to the bot environment.
**Testing**
> improve(across-monitor): Change notificationPath to dedicated channel

- packages/core/networks/288.json
**Motivation**
We want to test a price request sent from an LSP via the OO on Boba to the OracleSpoke.
**Testing**
> feat: Deploy Boba LSP

- packages/financial-templates-lib/src/helpers/GasEstimator.ts
**Motivation**
Arbitrum and Optimism, like Boba, only allow legacy transactions.
> improve(gas-estimator): Add defaults for Optimism and Arbitrum

- packages/sdk/src/across/clients/bridgePool.ts
- packages/sdk/src/across/constants.ts
**Motivation**
https://app.shortcut.com/uma-project/story/4142/update-pool-page-to-use-on-chain-rate-models
**Summary**
Use on chain rate model now. Adds optional configuration option to pass in rate model contract address when initializing pool client. 
**Testing**
> fix(sdk): use on chain rate model in pool client

- packages/scripts/src/admin-proposals/simulateVote.js
- packages/scripts/src/upgrade-tests/Proposer.js
**Motivation**
We want to verify that the decentralized proposal upgrade works as expected.
**Summary**
This script verifies that:
- The governance system will be functional after the upgrade.
- The governance system can revert the upgrade afterwards if any problems are discovered.
**Testing**
**Issue(s)**
N/A
> feat: add proposer upgrade verification script

- packages/core/networks/10.json
- packages/core/networks/42161.json
> improve: Deploy Optimism and Arbitrum LSPs

- .eslintrc.js
- packages/sdk/src/oracle/services/statemachines/switchOrAddChain.ts
- packages/sdk/src/oracle/utils.ts
**Motivation**
web3 rpc is very strict when sending data to user to add a new chain, causing errors when including unexpected props. 
**Summary**
added utility to strip unneeded props from object before requesting user add the new chain
**Testing**
> fix(sdk): fix chain metadata shape when adding new chain for user

- packages/monitors/test/OptimisticOracleContractMonitor.js
**Motivation**
Accidental comment was left in the test file.
**Summary**
N/A
**Testing**
**Issue(s)**
N/A
> improve(monitors): remove unintended comment

- packages/sdk/src/clients/index.ts
- packages/sdk/src/clients/optimisticOracle/README.md
- packages/sdk/src/clients/optimisticOracle/client.e2e.ts
- packages/sdk/src/clients/optimisticOracle/client.ts
- packages/sdk/src/clients/optimisticOracle/index.ts
**Motivation**
Add event decoding to OO events so we can get a list of requests.
**Summary**
Uses the sdk client template in src/clients to add event decoding, not to be confused with the oracle client, which is specifically a frontend client. Eventually this will be imported there to add request listing.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(sdk): add typechain oo event decoder

- packages/scripts/setupFork.sh
- packages/scripts/src/admin-proposals/addContractCreator.js
- packages/scripts/src/admin-proposals/collateral.js
- packages/scripts/src/admin-proposals/identifier.js
- packages/scripts/src/admin-proposals/registerContract.js
- packages/scripts/src/admin-proposals/utils.js
- packages/scripts/src/utils/seedProposerWithUma.js
**Motivation**
Small bug fix.
**Testing**
> fix(admin-scripts): Work with decentralized proposer

- packages/sdk/src/oracle/README.md
- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/services/optimisticOracle.ts
- packages/sdk/src/oracle/services/statemachines/pollActiveRequest.ts
- packages/sdk/src/oracle/services/statemachines/setActiveRequest.ts
- packages/sdk/src/oracle/services/statemachines/statemachine.ts
- packages/sdk/src/oracle/services/update.ts
- packages/sdk/src/oracle/store/read.ts
- packages/sdk/src/oracle/store/write.ts
- packages/sdk/src/oracle/tests/client.e2e.ts
- packages/sdk/src/oracle/types/state.ts
- packages/sdk/src/oracle/types/statemachine.ts
- packages/sdk/src/oracle/utils.ts
BREAKING CHANGE: oo flags have changed names for clarity
**Motivation**
Added some new flags for easier ui code, and also continually update active request to catch possible state changes ( and set flags accordingly)
**Summary**
Refactor flag names, add additional names to cover ui states needed based on request state. Add a command to conitinually update request if its in a state that could potentially change. Also add a block time per chain.
**Testing**
> improve(sdk): fix request state flags, poll for request changes

- packages/scripts/src/admin-proposals/executeProposal.js
**Motivation**
In production this script outputs errors about nonce management probably because its attempting to send new transactions before the previous one is mined. Manual nonce management is simple to implement.
**Testing**
> improve: Add manual nonce management to executeProposal script

- packages/sdk/src/oracle/types/state.ts
- packages/sdk/src/oracle/utils.ts
**Summary**
forgot to include expired as a state which can be settled
**Testing**
> fix(sdk): fix can settle flag to include expied state

- packages/sdk/src/clients/optimisticOracle/client.ts
- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/services/statemachines/pollActiveUser.ts
- packages/sdk/src/oracle/services/statemachines/statemachine.ts
- packages/sdk/src/oracle/types/statemachine.ts
**Motivation**
user balances/ approvals can change outside the app
**Summary**
adds a command to poll the active user on the active chain. its initialized on app construction. It uses the tx rate to determine how fast to poll per chain.
**Testing**
> feat(sdk): poll user balance and approval for oo client

- packages/sdk/src/across/clients/bridgePool.e2e.ts
- packages/sdk/src/across/clients/bridgePool.ts
**Motivation**
This started off as a potential bug with badger pool utilization, but no bug was found.
**Summary**
Ended up exposing utilization on pool and added some additional e2e pool tests.
**Testing**
> fix(sdk): expose more across pool values and add badger/wbtc to e2e tests

- packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
- packages/insured-bridge-relayer/src/Relayer.ts
**Motivation**
We are note sending all across logs to the right place. this PR fixes this.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(across-bots): pipe more logs to the correct channel

- packages/sdk/src/clients/optimisticOracle/client.ts
- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/services/index.ts
- packages/sdk/src/oracle/services/sortedRequests.ts
- packages/sdk/src/oracle/services/statemachines/fetchPastEvents.ts
- packages/sdk/src/oracle/services/statemachines/pollNewEvents.ts
- packages/sdk/src/oracle/services/update.ts
- packages/sdk/src/oracle/store/read.ts
- packages/sdk/src/oracle/store/write.ts
- packages/sdk/src/oracle/types/state.ts
- packages/sdk/src/stores/sorted-js-map/store.ts
**Motivation**
Provide a list of requests, sorted from newest to oldest. Keep list up to date with new requests.
**Summary**
This uses the existing sorted store to maintain a unique table of all requests across all chains. Its sorted by timestamp.  The full list gets attached to global state and is kept up to date as soon as new data comes in, meaning a FE client can use this list directly. 
**Testing**
> feat(sdk): add request list populated by oo events from newest to oldest

- packages/financial-templates-lib/src/helpers/multicall.ts
- packages/scripts/src/admin-proposals/README.md
- packages/scripts/src/admin-proposals/resolveProposal.js
- packages/scripts/src/admin-proposals/utils.js
**Motivation**
Convenience script that anyone can use to resolve all pending proposals for a specific proposer.
**Summary**
Previously, resolving proposals was done automatically in proposal scripts, but I think this was packing too many transactions in one script run.
**Testing**
> feat: Add resolveProposal script to retrieve all possible UMA bonds

- packages/sdk/src/oracle/README.md
- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/services/optimisticOracle.ts
- packages/sdk/src/oracle/services/statemachines/index.ts
- packages/sdk/src/oracle/services/statemachines/settle.ts
- packages/sdk/src/oracle/services/statemachines/statemachine.ts
- packages/sdk/src/oracle/types/statemachine.ts
**Motivation**
Want to be able to settle requests in oo UI.
**Summary**
Copies an existing command and just calls settle instead.
**Testing**
> feat(sdk): add oo settle ability

- packages/common/src/RoundingUtils.ts
- packages/common/test/RoundingUtils.js
**Motivation**
Price feed implementations and proposer/dispute bots need to use correct rounding method as specified in price identifier UMIP.
**Summary**
This adds utility function that can be used by price feeds to round price values.
**Testing**
> feat(common): implement rounding utils

- packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
**Motivation**
There is a bug with DAI on optimism with Across. this PR removes dai from the bot to fix this.
> feat(across-relayer): filter out DAI in cross domain finalizer

- packages/insured-bridge-relayer/src/CrossDomainFinalizer.ts
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> improve(across-relayer): Improve CrossDomainFinalizer logs

- packages/scripts/src/admin-proposals/utils.js
**Motivation**
ParentMessenger needs ETH to send message to L2 but doesn't need to hold excess (i.e. more than 0.15 ETH required for one message)
**Testing**
> fix(admin-proposal-script): Only send ETH to Arbitrum_ParentMessenger if balance is low

- packages/financial-templates-lib/src/helpers/multicall.ts
**Motivation**
`Multicall3` is backwards compatible with `Multicall` which we currently use. New features include cheaper gas cost, same address for all networks, and other features that we can take advantage of in the future.
[source](https://github.com/mds1/multicall#multicall3-contract-addresses)
**Testing**
> improve: Use multicall3 address

- packages/affiliates/hardhat.config.js
- packages/common/hardhat.config.js
- packages/common/package.json
- packages/common/src/HardhatConfig.ts
- packages/contracts-frontend/hardhat.config.cjs
- packages/contracts-node/hardhat.config.js
- packages/core/hardhat.config.js
- packages/disputer/hardhat.config.js
- packages/financial-templates-lib/hardhat.config.js
- packages/funding-rate-proposer/hardhat.config.js
- packages/fx-tunnel-relayer/hardhat.config.ts
- packages/insured-bridge-relayer/hardhat.config.ts
- packages/liquidator/hardhat.config.js
- packages/monitors/hardhat.config.js
- packages/optimistic-oracle/hardhat.config.js
- packages/scripts/hardhat.config.js
- packages/serverless-orchestration/hardhat.config.js
- packages/trader/hardhat.config.ts
- yarn.lock
**Motivation**
When importing the common package externally, errors are generated due to some missing exports, missing dependencies, and truffle dependency issues.
**Summary**
This PR intends to eliminate some of those issues.
**Testing**
**Issue(s)**
N/A
> fix: clean up a few missing and lingering dependencies in the common package

- packages/scripts/src/admin-proposals/changeFinderAddress.js
**Motivation**
This script will need to be used to upgrade the "Oracle" implementation address on the Polygon Finder so that we can upgrade the `OracleChildTunnel`. See #3863 for motivation for upgrading `OracleChildTunnel`. I tested this locally on mainnet fork.
**Testing**
> feat: Add admin script to change Finder address

- packages/polymarket-notifier/src/polymarketNotifier.js
Signed-off-by: Alex Gaines <againes@umaproject.org>
**Motivation**
Update to send pagerduty alerts on proposals that diverge from the Polymarket API.
**Testing**
> improve(polymarket-notifier): Polymarket notifier alert updates

- packages/scripts/src/admin-proposals/proposeAdminTransactions.js
**Motivation**
Its sometimes required that a UMIP will contain two types of transactions that are not normally bundled into the same admin transaction. For example: upgrading the polygon oracle tunnel system requires changing the Polygon Finder AND registering a contract on Mainnet.
This PR adds a helper script to bundle hard coded admin transactions.
**Details**
I tested this on mainnet-fork. Can test with `node ./packages/scripts/admin-proposals/proposeAdminTransactions.js --network mainnet-fork` followed by `--verify`-ing the `registerContract` and `changeFinderAddress` scripts.
- `HARDHAT_CHAIN_ID=1 yarn hardhat node --fork https://mainnet.infura.io/v3/XXXX --no-deploy --port 9545`
- export `NODE_URL_1=http://localhost:9545`
- export …
> feat: Add script to manually propose a single admin transaction

- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.ts
Signed-off-by: binomfx <binomfx@gmail.com>
Change shares list.
Previously tested.
> Update DefaultPriceFeedConfigs.ts - change shares list for uSPAC10

- packages/core/networks/1.json
- packages/core/networks/137.json
**Motivation**
Deploy contracts with upgraded FxBaseRootTunnel implementation, added in #3863 
**Testing**
> feat: Add Polygon tunnel addresses

- packages/core/contracts/zodiac/OptimisticGovernor.sol
- packages/core/test/zodiac/OptimisticGovernor.js
**Motivation**
Moving from the Skinny Optimistic Oracle to the regular Optimistic Oracle to have a better user experience.
**Summary**
Dealing with requests in calldata is a bad UX.
**Details**
For the most part, this PR simplifies the existing code since the regular OO makes fewer demands on the caller.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: use regular oo instead of skinny oo

- packages/core/contracts/financial-templates/optimistic-distributor/OptimisticDistributor.sol
- packages/core/contracts/zodiac/OptimisticGovernor.sol
- packages/core/test/financial-templates/optimistic-distributor/OptimisticDistributor.js
- packages/core/test/zodiac/OptimisticGovernor.js
**Motivation**
There were a few minor issues that needed resolution in both the Optimistic Governor and Optimistic Distributor.
**Summary**
Optimistic Distributor:
- Final fee and Store were unused.
Optimistic Governor:
- The deleteRejectedProposals method had a vulnerability where ancillary data was not being validated correctly.
- Natspec was missing on almost all methods.
- The setCollateral method was calling _sync when it didn't need to.
- The setCollateral method was nonReentrant, but that would prevent it being set via executions that originated from the Optimistic Governor.
- Remove unnecessary event, since the OptimisticOracle event contains the same info.
**Testing**
**Issue(s)**
N/A
> fix: fix minor issues with OG and OD

- packages/sdk/src/oracle/client.ts
- packages/sdk/src/oracle/services/statemachines/setActiveRequest.ts
- packages/sdk/src/oracle/services/statemachines/setActiveRequestByTransaction.ts
- packages/sdk/src/oracle/services/statemachines/statemachine.ts
- packages/sdk/src/oracle/services/statemachines/updateActiveRequest.ts
- packages/sdk/src/oracle/services/statemachines/utils.ts
- packages/sdk/src/oracle/store/has.ts
- packages/sdk/src/oracle/types/statemachine.ts
**Motivation**
Loading request details can be slow even if requests were previously visited.
**Summary**
This mainly splits up setting the active request, and updating the active request to 2 separate steps, and now only waits for the active request to be set before finishing "loading". This lets it show cached data if available. It also reduces the amount of data needed when updating the active request.
**Testing**
> improve: improve loading speed of request details

- packages/common/src/gckms/utils.ts
- packages/common/src/index.ts
**Motivation**
Export key retrieval code for GCKMS keys.
**Testing**
**Issue(s)**
N/A
> fix: add gckms utils to common export

- packages/monitors/src/OptimisticOracleContractMonitor.js
**Motivation**
Remaining comparisons from #3892 need to be fixed.
**Testing**
**Issue(s)**
N/A
> fix: remaining Optimistic Oracle bot comparisons

- package.json
- packages/across-monitor/src/AcrossMonitor.ts
- packages/across-monitor/src/AcrossMonitorConfig.ts
- packages/across-monitor/src/RelayEventProcessor.ts
- packages/across-monitor/src/index.ts
- packages/financial-templates-lib/src/clients/InsuredBridgeL1Client.ts
- packages/insured-bridge-relayer/src/RelayerConfig.ts
- packages/insured-bridge-relayer/src/index.ts
- packages/insured-bridge-relayer/test/index.ts
- yarn.lock
**Motivation**
Some event searches return > 10,000 values in production, we should paginate such event searches to avoid running into node-provider imposed limit.
**Testing**
> fix: Paginate InsuredBridgeL1Client event search for select events

- packages/core/networks/80001.json
**Motivation**
MockOracleAncillary on Mumbai was deployed with old instance of Finder contract.
**Summary**
New MockOracleAncillary instance address on Mumbai added.
**Details**
Finder has also been updated to point `Oracle` to the new MockOracleAncillary address.
**Testing**
> fix(core): update MockOracle deployment address

- packages/sdk/src/across/clients/bridgePool.ts
**Motivation**
event queries are timing out in across
**Summary**
scope event queries to active user
**Testing**
Ran this locally and saw error go away
> fix(sdk/across): scope query events to user

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
`collateral` is unnecessarily cast as `address` in the `setUp` function.
**Summary**
Remove the unnecessary cast.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-10, Unnecessary cast

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
`OptimisticOracle` is imported but never used.
**Summary**
Removes the import.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-11, Unnecessary imports

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
There were some typographical errors in the inline comments.
**Summary**
Fixed them.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-07, Typographical errors

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
The elements of the `Transaction` struct, if stored on-chain, would be more gas efficient if the `operation` came after the `to` address.
**Summary**
Re-ordered the elements.
**Details**
This is in case future iterations of the `OptimisticGovernor` or other contracts that interact with it want to store the full transactions on-chain using the `Transaction` struct.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-06, Suboptimal struct packing

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Functions that are `public` should be set as `external` if they are never used internally by the contract.
**Summary**
Changed transaction proposal, execution, and deletion functions to `external`, along with `sync`.
**Details**
Initially OpenZeppelin suggested that the setter functions should be set to `external`, but I left them as `public` because they actually will be used internally during the `setUp` function to avoid code duplication, per L-02.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-05, Some public functions could be external

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Some commented code was left in the `proposeTransactions` and `executeProposal` functions.
**Summary**
Deletes unused commented code.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-01, Commented out code

- packages/core/contracts/oracle/implementation/OptimisticOracle.sol
- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
The inline documentation was misleading in several places in the `OptimisticGovernor`.
**Summary**
- Correctly explains what is being updated by the `_sync` function
- Corrects explanation of the bond in the `setUp` function
- Corrects a copy-paste error for the `_originalTime` parameter in the `deleteRejectedProposal` function
- Corrects slightly incorrect explanation of when the `settleAndGetPrice` function will revert
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: L-03, Misleading inline documentation

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
In many places, events are not emitted after executing sensitive actions. This adds events for updates to the bond, collateral, rules, liveness, and identifier.
**Summary**
Events are defined and emitted in various functions.
**Details**
No events were added to the `setUp` function in this PR, but the PR for L-02 will have `setUp` call the various set* functions internally, which will emit the events. Similarly, the PR for M-01 includes events for the combined `setCollateralAndBond` function.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: M-02, lack of event emission after sensitive actions

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
The `proposeTransactions` function will fail if the proposer has not set an appropriate allowance for the `OptimisticGovernor` contract but this is not documented in the code.
**Summary**
Adds inline documentation explaining that the function will fail if a proper allowance is not set.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-08, Undocumented implicit approval requirements

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
`ProposalDeleted` and `TransactionsProposed` events would be more useful if they included more information.
**Summary**
Adds the `msg.sender` and status to the `ProposalDeleted` event and adds a `challengeWindowEnds` value to the `TransactionsProposed` event, so that disputers know by what time they must submit disputes.
**Details**
A separate PR adds a `deleteDisputedProposal` function, which has a "Disputed" status in the `ProposalDeleted` event.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: L-01, Events lacking information

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Since the `finder` is only set up on initialization, it could be made `immutable` and set in the constructor rather than the `setUp` function. This more clearly signals intent and reduces gas costs.
**Summary**
Set `finder` in constructor and make `immutable`.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-04, immutable value could be used

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
There were some `private` functions listed before the `internal` functions.
**Summary**
Re-ordered the functions.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: N-02, Coding style deviates from Solidity Style Guide

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
The `OptimisticGovernor` would benefit from more rigorous input validation.
**Summary**
Checks that `_finder` is nonzero, that `_liveness` is less than 5,200 weeks, and that `_rules` is non-empty, in various setter functions.
**Details**
A bond set to zero is valid. This is clarified in inline comments in the PR for M-01.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: M-03, Lack of input validation

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Before this PR, proposal deletion functions could be called repeatedly for the same proposal. This wastes gas, so there is no incentive to do so, but it could result in multiple `ProposalDeleted` events, which could be confusing.
**Summary**
Checks that proposal still exists before deleting the proposal and emitting an event.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: L-04, Proposals can be deleted repeatedly

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
This PR uses the `set*` functions in the `setUp` function to set the bond, collateral, identifier, and so on, instead of duplicating code.
**Summary**
Deletes duplicate code and calls the `set*` functions in `setUp`.
**Details**
The `setCollateralAndBond` function from the fix for M-01 is carried into this PR since it is used in the `setUp` function.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: L-02, Duplicated code

- packages/core/contracts/zodiac/OptimisticGovernor.sol
- packages/core/test/zodiac/OptimisticGovernor.js
**Motivation**
This PR resolves a potential issue. Right now, a proposal that is disputed can be executed if the dispute is resolved in the proposer's favor. This can be a problem because it could allow for things like multiple withdrawals or stale smart contract updates. Here are two failure examples:
**Double Withdrawal**
1. Alice creates a valid proposal to withdraw funds.
2. Proposal is disputed.
3. Alice creates a second valid proposal to withdraw funds.
4. Second proposal is not disputed and funds are withdrawn.
5. First proposal is validated and funds are withdrawn a second time.
**Stale Smart Contract Update**
1. Alice creates a valid proposal to update an interest rate in a smart contract system controlled by an Avatar. …
> fix: add ability to delete disputed proposals

- packages/scripts/src/admin-proposals/transferTokensFromGovernor.js
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add script for transferring uma tokens from governor

- packages/serverless-orchestration/src/ServerlessHub.js
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: add additional serverless logic

- packages/serverless-orchestration/src/ServerlessHub.js
**Motivation**
The previous "fix" to the serverless hub actually broke it. This PR rolls back that change.
**Testing**
> fix: roll back previous serverless hub change

- packages/scripts/src/admin-proposals/transferTokensFromGovernor.js
**Motivation**
- Assertion in verification was breaking if the recipient already has UMA at that address, since it was checking that the balance equaled the amount transferred. Removed this check for now in favor of manual verification.
- Added logs for manual verification of before-and-after balances for the recipient address and the Governor.
**Summary**
See motivation.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: improvements to the uma transfer script

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/416.json
- packages/core/networks/43114.json
**Motivation**
New chain deployments required some updates to `networks` and config files.
**Summary**
Adds `networks` files for Avalanche and SX Network and updates `HardhatConfig.ts`, `ProviderUtils.ts`, and `PublicNetworks.ts` with new chain information.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add avalanche and sx to networks

- packages/core/contracts/financial-templates/optimistic-distributor/OptimisticDistributor.sol
**Motivation**
Audit identified the following issue:
_bondToken can be made immutable_
**Summary**
This PR fixes identified issue by making `bondToken` variable explicitly immutable.
**Testing**
> fix(optimistic-distributor): [N07] bondToken made immutable

- packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
**Motivation**
Audit identified the following issue:
_Typographical errors_
**Summary**
This PR fixes identified issue by declaring `rewardCurrency` and `currentRewardToken` as IERC20.
**Testing**
> fix(merkle-distributor): [N18] fix typographical errors

- packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
**Motivation**
Audit identified the following issue:
_Gas optimizations_
**Summary**
This PR fixes identified issue by adding gas optimizations
**Details**
`ipfsHash` parameter to `setWindow` is declared `calldata`.
`claim` function is declared as `external`.
Do not initialize `batchedAmount` to 0.
**Testing**
> fix(merkle-distributor): [N16] add gas optimizations

- packages/core/contracts/financial-templates/optimistic-distributor/OptimisticDistributor.sol
**Motivation**
Audit identified the following issue:
_Checks-effects-interactions is not adhered to within various functions_
**Summary**
This PR fixes identified issue by using checks-effects-interactions pattern.
**Details**
`rewardToken` transfers are moved to the end of the `createReward` and `increaseReward` functions.
**Testing**
> fix(optimistic-distributor): [N11] use checks-effects-interactions pattern

- packages/sdk/src/clients/index.ts
- packages/sdk/src/clients/skinnyOptimisticOracle/README.md
- packages/sdk/src/clients/skinnyOptimisticOracle/client.e2e.ts
- packages/sdk/src/clients/skinnyOptimisticOracle/client.ts
- packages/sdk/src/clients/skinnyOptimisticOracle/index.ts
**Motivation**
We need to add support for skinny oo in oracle UI.  This is the first step in a series of prs. 
**Summary**
Adds a basic client to build state from contract events
**Testing**
> feat(sdk): add basic skinny oo client

- packages/contract-notifier/src/ContractNotifier.js
**Motivation**
Expiring contracts notifier needs dedicated logging channel.
**Summary**
Changed `notificationPath` to dedicated `outcome-expirations`.
**Testing**
> feat(contract-notifier): use outcome-expirations notificationPath

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Response to OZ audit feedback on proposal hashes.
**Summary**
* Emits the proposal hash in the `TransactionsProposed` event, for convenience.
* Adds a constant for the `PROPOSAL_HASH_KEY` that is used repeatedly in ancillary data construction, to minimize risk of typos.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> improve: use constant for PROPOSAL_HASH_KEY and emit proposal hash when transactions are proposed

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Address OZ note (response to the response on M03) that the error log for exceeding max liveness should make it clear that liveness is strictly less than 5200 weeks.
**Summary**
Updated the log. The actual liveness was updated in an earlier PR: https://github.com/UMAprotocol/protocol/pull/3950
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: correct comment on max liveness

- packages/polymarket-notifier/src/polymarketNotifier.js
**Motivation**
Polymarket API notifier needs dedicated logging channel.
**Summary**
Changed `notificationPath` to dedicated `polymarket-notifier`.
**Testing**
> feat(polymarket-notifier): use polymarket-notifier notificationPath

- packages/core/contracts/zodiac/OptimisticGovernor.sol
**Motivation**
Per OZ feedback (response to the response to L03), updates comments to clarify in `deleteRejectedProposal` that `settleAndGetPrice` will revert if the price has not been settled and can not currently be settled, consistent with other comments.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: consistent comments

- packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
- packages/sdk/src/across/feeCalculator.test.ts
- packages/sdk/src/across/feeCalculator.ts
This reverts commit 675eaa73dab1389c6cdf649b1d3197aa22ad640a.
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> Revert "feat: Round realized LP fee % to match UMIP (#3898)"

- packages/core/test/zodiac/OptimisticGovernor.js
**Motivation**
Updates the existing Optimistic Governor tests to follow changes to the contract from the audit.
**Summary**
Many tests that were commented out during the audit have been uncommented and refactored to use the new contract code.
**Details**
Due to the simpler contract interface, the tests are a bit cleaner and some older tests were deleted. Other tests are still commented out or left empty, to be filled in later. This pull request brings our test coverage back up to the level it was at prior to the audit.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: get older optimistic governor tests working

- packages/scripts/README.md
**Motivation**
@Tulun ran into some issues running these scripts that required cleaning the contracts and reinstalling dependencies.
**Summary**
This just adds some extra instructions to help users build the repo and troubleshoot if they have issues.
**Testing**
**Issue(s)**
N/A
> improve(scripts): add initial install instructions and troubleshooting to README

- packages/insured-bridge-relayer/src/ProfitabilityCalculator.ts
- packages/insured-bridge-relayer/test/ProfitabilityCalculator.ts
**Motivation**
Across v1 bots are no longer relaying so this warning isn't useful.
**Summary**
N/A
**Testing**
**Issue(s)**
N/A
> improve: change CG API warn to debug

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
`PriceRequestAdded` event in `VotingV2.sol` was missing `ancillaryData`
**Summary**
Add `ancillaryData` to `PriceRequestAdded` event.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(core): add missing ancilliary data to price events

- packages/common/src/Constants.ts
- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/9001.json
**Motivation**
Deploy non-rollup chain smart contracts to EVMOS
**Summary**
Deployed and verified the following contracts:
- Finder 0xeF684C38F94F48775959ECf2012D7E864ffb9dd4 
- OptimisticOracle 0x09aea4b2242abC8bb4BB78D537A67a245A7bEC64 	
- IdentifierWhitelist 0x7E63A5f1a8F0B4d0934B2f2327DAED3F6bb2ee75		
- AddressWhitelist 0x3baD7AD0728f9917d1Bf08af5782dCbD516cDd96						
- Store 0x38fAc33bD20D4c4Cce085C0f347153C06CbA2968					
- OracleSpoke 0x9b4A302A548c7e313c2b74C461db7b84d3074A84				
- GovernorSpoke 0x3Db06DA8F0a24A525f314eeC954fC5c6a973d40E			
- Admin_ChildMessenger 0xD29C85F15DF544bA632C9E25829fd29d767d7978			
- Registry 0x2271a5E74eA8A29764ab10523575b41AA52455f0					
- OptimisticOracleV2 0xd2ecb3afe598b746F8123CaE365a598DA831A449
> feat: add evmos hardhat config and deployment addresses

- packages/core/contracts/oracle/implementation/SlashingLibrary.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/contracts/oracle/interfaces/VotingV2Interface.sol
- packages/core/deploy/051_deploy_votingV2.js
- packages/core/deploy/052_deploy_slashingLibrary.js
- packages/core/test/oracle/VotingV2.js
**Motivation**
Create a slashing library contract to calculate the slash amounts in UMAv2.0
**Summary**
- Added SlashingLibrary contract
- Moved slashing functions to the new contract
- Added setter test
**Testing**
> feat: add slashing library

- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/test/oracle/VotingV2.js
**Motivation**
The previous slash calculation implied some extra floors, resulting in a loss of precision. We can simplify to do only one division.
**Summary**
Simplifying the calculation so that there is only one division
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: simplify slash calculation

- packages/fx-tunnel-relayer/package.json
**Motivation**
CI is failing due to an out of memory error [see this](https://app.circleci.com/pipelines/github/UMAprotocol/protocol/18589/workflows/8461737d-b305-4ed6-8796-67f2808b92f4/jobs/156815)
**Summary**
Increase `yarn test` node process memory
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: increase yarn test node process mem to fix ci

- packages/core/networks/416.json
- packages/core/networks/43114.json
**Motivation**
Deploy the OptimisticOracleV2 in Avalanche and SX networks
**Summary**
Add OptimisticOracleV2 deployment addresses in Avalanche and SX networks
**Testing**
> feat: add oov2 deployments in avalanche and sx

- packages/common/src/Constants.ts
- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/82.json
**Motivation**
We needed to do a full deployment of the Optimistic Oracle contracts in Meter network.
**Summary**
* Add Meter network to hardhat config
* Deploy contracts to Meter and add addresses.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add meter network

- packages/contract-notifier/package.json
- packages/polymarket-notifier/package.json
- yarn.lock
**Motivation**
There is an ongoing issue in cloud run causing us to be unable to retrieve data from datastore consistently. Unable to replicate locally.
**Summary**
Attempting to push an update to these packages may help, but unsure.
**Testing**
**Issue(s)**
N/A
> fix: update datastore packages

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> refactor: finder immutable

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> refactor: adding cheaper increment function for loops trackers

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: price requests length

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: store price ids in memory

- packages/core/contracts/oracle/implementation/GovernorV2.sol
- packages/core/contracts/oracle/implementation/ProposerV2.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/contracts/oracle/interfaces/OracleGovernanceInterface.sol
- packages/core/contracts/oracle/test/MockOracleAncillary.sol
- packages/core/contracts/oracle/test/MockOracleGovernance.sol
- packages/core/test/oracle/GovernorV2.js
- packages/core/test/oracle/ProposerV2.js
- packages/core/test/oracle/VotingV2.js
**Motivation**
Allow governance actions to pass ancillary data
**Summary**
- Added ancillary data to `requestGovernanceAction` and `propose` functions in GovernorV2 and ProposerV2
- Added `ProposerV2` contract with new `propose` function interface
- Added `MockOracleGovernance` to we used with new interfaces
- Updated tests
**Testing**
> feat: add ancillary data to governance proposals

- packages/core/test/oracle/VotingGas.js
- packages/core/test/oracle/VotingV2Gas.js
**Motivation**
We would like to compare the gas costs of Voting and VotingV2.
**Summary**
This PR adds two test suites, one for Voting and one for VotingV2 that print out detailed gas costs for different methods.
Notes: 
- Because these print out lots of data, they are skipped unless the user provides the GAS_TEST=true environment variable.
- Because gas costs on the first run are often not representative (init costs), these scripts each do two runs. We should use the second for comparisons.
- This script commits and reveals individually since the batch methods are being removed. Once the multicall methods are in, we should swap these scripts to using batch in v1 and multicall in v2.
From the estimates below, it looks like the new voting system is marginally more expensive than the old …
> improve: add gas tests for voting v1 and voting v2

- packages/core/test/oracle/VotingGas.js
- packages/core/test/oracle/VotingV2Gas.js
**Motivation**
Batching is what we do in production, so it's more realistic to test with batching.
**Summary**
This adds batching to the voting methods in both scripts.
It also adds a claim step to the VotingV2 lifecycle test, since a fairly regular reward claim should be priced in.
The total gas comparison as of this change:
- Average V1 steady-state lifecycle cost for 4 votes: `717598`
- Average V2 steady-state lifecycle cost for 4 votes: `1401092`
Full run output:
```
$ GAS_TEST=true yarn hardhat test test/oracle/VotingGas.js test/oracle/VotingV2Gas.js
yarn run v1.22.5
$ /Users/matt/git/protocol/node_modules/.bin/hardhat test test/oracle/VotingGas.js test/oracle/VotingV2Gas.js
Voting Gas Test
Initialize Run. Gas costs will likely be higher than typical
Gas costs for 4 voters, 4 …
```
> feat: batch transactions in gas scripts

- packages/core/contracts/oracle/implementation/Staker.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/test/oracle/VotingV2.js
**Motivation**
The delegation process proposed in a previous PR can be simplified. This PR does just this.
**Testing**
> feat: DVM2.0 simplified delegation system

- packages/core/contracts/oracle/implementation/GovernorV2.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/test/oracle/VotingV2.js
**Motivation**
Removing unused imports.
**Testing**
**Issue(s)**
N/A
> refactor: clean imports

- packages/core/networks/43114.json
**Motivation**
Deploy `TokenFactory,LongShortPairCreator,LongShortPairLibraries` in Avalanche network
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: deploy lsp contracts in avalanche

- packages/core/networks/5.json
**Motivation**
The `MockOracleAncillary` deployed address on Goerli was listed twice in the network file.
**Summary**
Removed the duplicate.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: remove duplicate contract listing

- packages/core/networks/5.json
**Motivation**
Deploy new DVM 2.0 contracts to goerli
**Summary**
Deployed the DVM 2.0 contracts and some of the base contracts (VotingToken, Finder, Registry,...) to start from scratch and make sure all the configs are good. 
**Testing**
> feat: add new goerli addresses

- packages/core/test/oracle/SpamGuard.js
**Motivation**
Update spam test check that an internal call to `_resolvePriceRequest` during a price request deletion execution doesn't break anything
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: update spam test

- packages/common/src/HardhatConfig.ts
- packages/core/contracts/oracle/implementation/DesignatedVotingV2.sol
- packages/core/contracts/oracle/implementation/DesignatedVotingV2Factory.sol
- packages/core/contracts/oracle/implementation/GovernorV2.sol
- packages/core/contracts/oracle/implementation/ProposerV2.sol
- packages/core/contracts/oracle/implementation/ResultComputationV2.sol
- packages/core/contracts/oracle/implementation/VoteTimingV2.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/contracts/oracle/implementation/test/VoteTimingV2Test.sol
- packages/core/contracts/oracle/implementation/test/VotingV2Test.sol
- packages/core/contracts/oracle/interfaces/VotingV2Interface.sol
**Motivation**
```
Consider locking the version pragma to the same Solidity version used during development
and testing. Also consider setting this version to be the latest release.
```
**Summary**
Lock solidity version to the version used during implementation/testing `0.8.9`
**Details**
**Testing**
> feat: [L09] Unlocked Solidity version pragma

- CONTRIBUTING.md
**Motivation**
We should remind reviewers that it is their responsibility to resolve their own comments.
> improve(CONTRIBUTING): Add guidelines about reviewing PR's

- packages/core/contracts/oracle/implementation/Staker.sol
- packages/core/test/oracle/Staker.js
**Motivation**
Due to turning off CI(as a result of a circleCI issue) we managed to merge some broken tests. This PR addresses this, fixing the tests.
**Testing**
> fix: DVM2.0 address issue with merging without CI and fix staker tests

- packages/core/contracts/financial-templates/common/financial-product-libraries/long-short-pair-libraries/FlooredLinearLongShortPairFinancialProductLibrary.sol
**Motivation**
In order to transform #4119 in diffed format this PR just duplicates `LinearLongShortPairFinancialProductLibrary.sol` into `FlooredLinearLongShortPairFinancialProductLibrary.sol` as suggested [here](https://github.com/UMAprotocol/protocol/pull/4119#pullrequestreview-1077408431).
**Details**
Contract name had to be changed from `LinearLongShortPairFinancialProductLibrary` to `CopiedFromLinearLongShortPairFinancialProductLibrary` in order not to break build process due to duplicate contract naming.
**Testing**
> feat(core): copy linear fpl

- packages/sdk/src/oracle/utils.ts
**Motivation**
OO UI failed to switch/add polygon chain.
**Summary**
Polygons configuration object had some extra fields on it (earliestBlockNumber, maxEventRangeQuery), which when passed to metamask. Metamask makes sure there are no unknown fields on the object. We simply strip out the extra data before passing to metamask. 
**Details**
**Testing**
> fix(sdk): properly convert config to be used as chain data in MM

- packages/core/contracts/umips/VotingUpgraderV2.sol
- packages/scripts/src/upgrade-tests/voting2/0_Deploy.ts
- packages/scripts/src/upgrade-tests/voting2/1_Propose.ts
- packages/scripts/src/upgrade-tests/voting2/2_Verify.ts
- packages/scripts/src/upgrade-tests/voting2/migrationUtils.ts
- packages/scripts/src/upgrade-tests/voting2/readme.md
- packages/scripts/src/utils/constants.js
- packages/scripts/src/utils/seedProposerWithUma.js
**Motivation**
Scripts to migrate from Voting to VotingV2
**Summary**
Created 3 scripts to deploy, propose and verify the transactions to migrate from Voting to VotingV2.
We are reusing the  [VotingUpgrader](https://github.com/UMAprotocol/protocol/blob/md0x/voting-v2-migration/packages/core/contracts/umips/VotingUpgrader.sol) contract
**Testing**
> feat: add migration scripts to voting v2

- packages/core/contracts/oracle/implementation/Staker.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/contracts/oracle/implementation/test/VotingV2Test.sol
- packages/core/contracts/oracle/interfaces/MinimumVotingAncillaryInterface.sol
- packages/core/contracts/oracle/interfaces/VotingV2Interface.sol
- packages/core/test/oracle/VotingV2.js
**Motivation**
We had reached the point where we'd run out of bytecode in the contract. This PR fixes this by restructuring/changing some stuff around.
**Testing**
> Proposal: Small contract restructure to save some bytecode

- packages/scripts/src/upgrade-tests/voting2/0_Deploy.ts
**Motivation**
The VotingV2 constructor arguments have changed recently and the migration scripts were outdated. 
**Summary**
Update the deployment script to add the new VotingV2 constructor argument.
**Testing**
> feat: update votingv2 deployment arguments

- packages/core/contracts/zodiac/test/OptimisticGovernorTest.sol
- packages/core/contracts/zodiac/test/TestModuleProxyFactory.sol
- packages/core/test/zodiac/OptimisticGovernor.js
**Motivation**
Optimistic Governor would be deployed using minimal proxy pattern that requires testing.
**Summary**
Adds test to Optimistic Governor when deployed using minimal proxy pattern.
**Details**
Test covers proposal execution through Optimistic Governor that was deployed using minimal proxy pattern. This shows that the re-entrancy guard fix in #4123 addresses the issue.
**Testing**
> test(core): test minimal proxy optimistic governor

- packages/financial-templates-lib/package.json
- packages/financial-templates-lib/src/logger/PagerDutyTransportV2.ts
- packages/financial-templates-lib/src/logger/PagerDutyV2Transport.ts
- packages/financial-templates-lib/src/logger/Transports.ts
- yarn.lock
**Motivation**
This adds the new v2 pagerduty event logger, which can let us use hte native pagerduty incident router.   See [api docs here](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgx-send-an-alert-event). 
**Summary**
Simply adds a v2 pagerduty transport which uses a client library under the hood.  This was tested with below script. This tries to maintain the structure from v1 calls
**Testing**
Tested this using a small script 
```js
import { createNewLogger } from "./src";
const transportsConfig = {
pagerDutyV2Config:{   
integrationKey:"xxx"
}
}
async function run(): Promise<void> {    
const logger = …
```
> feat: pagerduty v2 logger

- packages/core/contracts/oracle/implementation/EmergencyProposer.sol
**Motivation**
In the latest audit OZ signaled:
```
In the EmergencyProposer contract, the following files are imported but not used:
• Constants.sol
• OracleAncillaryInterface.sol • AdminIdentifierLib.sol
```
**Summary**
Remove unused imports in `EmergencyProposer.sol`
**Testing**
> fix: [N11] remove unused imports

- packages/core/contracts/oracle/implementation/Staker.sol
- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
Oz signaled some redundant code:
```
Consider making the following changes to eliminate unnecessary code:
• In PR #4110, Staker.sol :
◦ line 246: The override keyword can be removed from the
withdrawAndRestake function 
• In PR #4135, VotingV2.sol :
◦ lines 978-980: The uint256(i) casts can be replaced with the variable i because i is already declared as a uint256 type on line 976
◦ line 1045: (rewards) can be changed to rewards
```
**Summary**
Remove redundant code
**Testing**
> fix: [N05] remove redundant code

- packages/core/contracts/umips/VotingUpgraderV2.sol
**Motivation**
OZ signaled in the latest audit that some variables can be immutable in VotingUpgraderV2:
existingGovernor , newGovernor , existingVoting , newVoting , and finder
**Summary**
Convert variables to immutable
**Testing**
> fix: [N01] lack of immutable identifier

- packages/core/contracts/oracle/implementation/VotingV2.sol
**Motivation**
Oz signaled:
```
Within VotingV2.sol there are require statements that lack error messages. For
instance:
The require statement on line 257 of VotingV2.sol
The require statement on line 265 of VotingV2.sol
The require statement on line 486 of VotingV2.sol
The require statement on line 704 of VotingV2.sol
The require statement on line 928 of VotingV2.sol
The require statement on line 964 of VotingV2.sol
The require statement on line 971 of VotingV2.sol
```
**Summary**
Add missing require messages.
**Details**
**This leaves a total of 60 bytes within the EIP170 limit in `VotingV2`.**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: [L05] add missing require messages in voting v2

- packages/core/contracts/oracle/implementation/VotingV2.sol
- packages/core/test/oracle/VotingV2.js
**Motivation**
After recent changes, the VotingV2 contract exceeded the bytecode limit.
**Summary**
Remove the require messages needed to reduce the size
**Testing**
> fix: votingv2 contract size

- packages/scripts/src/admin-proposals/changeFinderAddress.js
- packages/scripts/src/admin-proposals/identifier.js
- packages/scripts/src/admin-proposals/simulateVote.js
- packages/scripts/src/admin-proposals/transferTokensFromGovernor.js
- packages/scripts/src/admin-proposals/utils.js
- packages/scripts/src/utils/seedProposerWithUma.js
**Motivation**
Admin proposal scripts failed to run on OSes with case sensitive file systems (e.g. Linux).
**Summary**
Replaces `Web3` with `web3` in `require` statements.
**Testing**
> fix(scripts): support case sensitive file systems

- packages/affiliates/test/mocha-mainnet/models.js
- packages/common/src/PriceIdentifierUtils.ts
**Motivation**
PR to remove "NUMERICAL" from the supported identifier list.
> fix: ignore NUMERICAL identifier

- packages/polymarket-notifier/README.md
- packages/polymarket-notifier/src/polymarketNotifier.js
Signed-off-by: Alex Gaines <againes@umaproject.org>
**Motivation**
The alert currently returned by the polymarket notifier is difficult to interpret. This PR provides additional information when there is an issue with the response returned from the Polymarket API.
**Summary**
Improve the error returned when there is an issue with the Polymarket API and also include the `CUSTOM_NODE_URL` in the README which is missing.
**Testing**
> improve (polymarket-notifier): Update polymarket notifier error message

- packages/core/networks/80001.json
**Motivation**
We want OOv2 available on Mumbai for testing.
**Summary**
Adds the deployed OOv2 contract on Mumbai to our networks file.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add oov2 to mumbai

- packages/core/contracts/oracle/implementation/OptimisticAssertor.sol
**Motivation**
First optimistic assertor implementation, done together with @chrismaree and @Reinis-FRP
**Details**
**Testing**
> feat: first optimistic assertor implementation

- packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
- packages/core/contracts/merkle-distributor/implementation/MerkleDistributorInterface.sol
- packages/core/package.json
- packages/core/test/merkle-distributor/MerkleDistributor.js
PR applies bug fix originally discovered [here](https://github.com/across-protocol/contracts-v2/pull/193). Goal is to make this MerkleDistributor in this repo the canonical version and make the Across MerkleDistributor an extension
> fix: Fix bug in MerkleDistributor that doesn't decrement remainingAmount for merkle windows correctly

- packages/core/contracts/oracle/implementation/OptimisticAssertor.sol
- packages/core/contracts/oracle/interfaces/OptimisticAsserterCallbackRecipientInterface.sol
- packages/core/contracts/oracle/interfaces/OptimisticAssertorInterface.sol
- packages/core/contracts/oracle/interfaces/SovereignSecurityManagerInterface.sol
**Motivation**
Second optimistic assertor implementation, done together with @chrismaree and @md0x 
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: second optimistic assertor implementation

- packages/core/contracts/oracle/implementation/BaseSovereignSecurityManager.sol
- packages/core/contracts/oracle/implementation/OptimisticAssertor.sol
- packages/core/contracts/oracle/implementation/OwnerUnplugSovereignSecurityManager.sol
- packages/core/contracts/oracle/implementation/WhitelistedSovereignSecurityManager.sol
- packages/core/contracts/oracle/interfaces/OptimisticAsserterCallbackRecipientInterface.sol
- packages/core/contracts/oracle/interfaces/OptimisticAssertorInterface.sol
- packages/core/contracts/oracle/interfaces/SovereignSecurityManagerInterface.sol
**Motivation**
Third optimistic assertor implementation, done together with @Reinis-FRP and @md0x
> feat: Add OptimisticAssertor Sovereign security manager

- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/OwnerUnplugSovereignSecurityManager.sol
**Motivation**
Rename Sovereign security variables to improve clarity
**Summary**
Rename variables
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: rename oa sovereign security variables

- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/OwnerSelectOracleSovereignSecurityManager.sol
**Motivation**
Rename  `OwnerUnplugOracleSovereignSecurityManager` to `OwnerSelectOracleSovereignSecurityManager` to be consistent with naming.
**Summary**
Rename contract
**Testing**
**Issue(s)**
Fixes #XXXX
> refactor: rename sovereign security manager implementation

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/BaseSovereignSecurityManager.sol
- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/OwnerSelectOracleSovereignSecurityManager.sol
- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/WhitelistedSovereignSecurityManager.sol
- packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
- packages/core/contracts/optimistic-assertor/interfaces/SovereignSecurityManagerInterface.sol
**Motivation**
Get and configure assertion policies in `assertTruth` function
**Summary**
The configuration of the assertions regarding whether assertions can be made, whether the DVM is to be used for this and whether the result of the resolution is to be used, is now done in assertTruth.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: oa sovereign security policies

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/contracts/optimistic-assertor/implementation/test/OptimisticAssertorTest.sol
- packages/core/test/foundry/fixtures/optimistic-assertor/OptimisticAssertorFixture.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Lifecycle.t.sol
**Summary**
- Add first lifecycle assertion test
- Add `OptimisticAssertorTest` contract to override time
- Add `getCurrentTime` function
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: optimsitic assertor happy path test and timer integration

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/test/foundry/fixtures/dvm/MockDvmFixture.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Edgecases.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Lifecycle.t.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Ownership.t.sol
**Description**
Add optimistic assertor dispute test and fix some issues
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add assertion dispute test and fix issues

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Edgecases.sol
**Motivation**
Tests should validate Optimistic Asserter function parameters.
**Summary**
Adds tests for validating Optimistic Asserter function parameters.
**Testing**
> test(core): validate oa function parameters

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Edgecases.sol
**Motivation**
Optimistic Assertor allowed multiple disputes by passing zero disputer address.
**Summary**
Change passed disputer address to msg.sender if zero address was provided.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(core): avoid duplicate oa disputes

- packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
**Motivation**
Need to verify Sovereign Security Manager policies.
**Summary**
Adds tests on Optimistic Assertor behavior based on mocked Sovereign Security Manager policies.
**Testing**
> test(core): ssm policies on oa

- packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
**Motivation**
We should check Optimistic Assertor issues callbacks correctly.
**Summary**
Adds tests on expected callback function calls from Optimistic Assertor.
**Testing**
> test(core): check oa callbacks

- packages/core/contracts/optimistic-assertor/implementation/sovereign-security-manager/BaseSovereignSecurityManager.sol
- packages/core/test/foundry/optimistic-assertor/BaseSovereignSecurityManager.t.sol
- packages/core/test/foundry/optimistic-assertor/OwnerSelectOracleSovereignSecurityManager.t.sol
- packages/core/test/foundry/optimistic-assertor/WhitelistedSovereignSecurityManager.t.sol
**Summary**
Add unit tests for Sovereign Security Manager
**Testing**
> feat: sovereign security manager unit tests

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/contracts/optimistic-assertor/interfaces/OptimisticAsserterCallbackRecipientInterface.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
**Motivation**
The dispute callback is necessary to implement dispute logics, notably in the Sovereign Security Manager but also in any contract that wants to be able to subscribe to this information and act accordingly.
**Summary**
Add on dispute callback
**Testing**
> feat: add dispute callbacks

- packages/core/test/foundry/optimistic-assertor/Common.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.EdgeCases.t.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Events.t.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Lifecycle.t.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAsserter.Ownership.t.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
- packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/BaseSovereignSecurityManager.t.sol
- packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/OwnerSelectOracleSovereignSecurityManager.t.sol
- packages/core/test/foundry/optimistic-assertor/SovereignSecurityManagers/WhitelistedSovereignSecurityManager.t.sol
**Motivation**
This PR refines some of the foundry work to re-use common files, refactor some of the structure and generall work on cleaning up the assertion structure.
> feat: refactor tests to use common implementation and general clean

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/contracts/optimistic-assertor/implementation/examples/Insurance.sol
- packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
- packages/core/test/foundry/optimistic-assertor/examples/Insurance.t.sol
**Motivation**
Add an example implementation of an Insurance contract that uses the Optimistic Arbitrator
**Summary**
- Add Insurance contract
- Small updates in Optimistic Arbitrator to improve consumers usage (getMinimumBond, OA Interface updates)
- Test Insurance contract
**Testing**
> feat: insurance implementation with optimistic assertor

- packages/core/networks/5.json
**Motivation**
We deployed a new Voting V2 contract in goerli to test the claim of old rewards and retrieving price requests in the previous Voting contract.
**Summary**
Add VotingV2 address in goerli
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add new voting v2 goerli address

- packages/core/contracts/optimistic-assertor/implementation/OptimisticAssertor.sol
- packages/core/contracts/optimistic-assertor/interfaces/OptimisticAssertorInterface.sol
- packages/core/contracts/optimistic-assertor/interfaces/SovereignSecurityManagerInterface.sol
- packages/core/test/foundry/optimistic-assertor/Common.sol
- packages/core/test/foundry/optimistic-assertor/OptimisticAssertor.SsmPolicies.t.sol
**Motivation**
This PR is the result of a code reading session together with @Reinis-FRP and @chrismaree 
**Summary**
- Add TODO's on things to rename, simplify or reconsider in the Optimistic Assertor and Sovereign Security Manager
- Small fixes
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add todos optimistic assertor and ssm

- packages/core/test/foundry/optimistic-assertor/examples/DataAsserter.t.sol
**Summary**
Fix data asserter tests
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: data asserter test

- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/BaseSovereignSecurity.t.sol
- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/OwnerDiscardOracleSovereignSecurity.t.sol
- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/OwnerSelectOracleSovereignSecurity.t.sol
- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/WhitelistCallerSovereignSecurity.t.sol
- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/WhitelistDisputerSovereignSecurity.t.sol
- packages/core/test/foundry/optimistic-asserter/SovereignSecurity/WhitelistProposerSovereignSecurity.t.sol
**Summary**
Rename `ss` to `sovereignSecurity` in tests
**Testing**
**Issue(s)**
Fixes #XXXX
> refactor: rename ss to sovereign security in tests

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
- packages/core/contracts/optimistic-asserter/interfaces/SovereignSecurityInterface.sol
This PR adds some additional TODOs that came out of another code reading session.
> feat: add additional code reading todos

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add multicall support and other small nits

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: optimistic assertor gas optimisations

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
- packages/core/contracts/optimistic-asserter/interfaces/EscalationManagerInterface.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
- packages/core/test/foundry/optimistic-asserter/Common.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
**Summary**
Reviews and addresses remaining Optimistic Asserter TODOs.
**Testing**
> feat(core): address oa todos

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
- packages/core/contracts/optimistic-asserter/implementation/examples/DataAsserter.sol
- packages/core/contracts/optimistic-asserter/implementation/examples/Insurance.sol
- packages/core/contracts/optimistic-asserter/implementation/examples/PredictionMarket.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
- packages/core/test/foundry/optimistic-asserter/Common.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.EdgeCases.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Maintenance.t.sol
**Motivation**
Minor gas improvements in Optimistic Asserter.
**Summary**
Changing order of `assertTruth` arguments slightly improves gas costs (96 gas for `assertTruthWithDefaults` call).
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(core): minor oa gas improvement

- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
**Motivation**
Improve gas efficiency of the assertion calls.
**Summary**
This improves variable packing by grouping variables in the assertion to minimize the total number of slots and grouping by when the variables are written to.
This seems to drop the average gas usage of both forms of assertTruth by about 15-20k gas.
**Testing**
**Issue(s)**
N/A
> feat: improved variable packing

- packages/core/contracts/optimistic-asserter/implementation/escalation-manager/FullPolicyEscalationManager.sol
- packages/core/test/foundry/optimistic-asserter/EscalationManager/FullPolicyEscalationManager.t.sol
**Motivation**
Add the FullPolicyEscalationManager
**Summary**
- FullPolicyEscalationManager
- Tests
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add full policy escalation manager

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
- packages/core/test/foundry/optimistic-asserter/Common.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Events.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Lifecycle.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.SsPolicy.t.sol
**Motivation**
Add docstrings to the OA constructor
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: constructor natspec

- packages/core/test/foundry/optimistic-asserter/Common.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Callbacks.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.EdgeCases.t.sol
- packages/core/test/foundry/optimistic-asserter/OptimisticAsserter.Maintenance.t.sol
**Motivation**
Some of tests were disabled due to stack too deep errors.
**Summary**
Uses constants for some of common state variables in Optimistic Asserter tests.
**Testing**
> fix(core): fix broken oa tests

- packages/core/contracts/optimistic-asserter/implementation/test/AssertingCallerTest.sol
- packages/core/test/foundry/optimistic-asserter/Common.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/BaseEscalationManager.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.Arbitrate.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.BlockAssertion.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.BlockDispute.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.Common.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/FullPolicyEscalationManager.DiscardOracle.t.sol
- packages/core/test/foundry/optimistic-asserter/integration-tests/OptimisticAsserter.BaseEscalationManager.t.sol
**Motivation**
Verify Optimistic Asserter interacts with Escalation Managers as expected.
**Summary**
Adds integration tests to Optimistic Asserter paired with Base Escalation Manager and Full Policy Escalation Manager.
**Details**
This also adds `OptimisticAsserterTest` as a wrapper contract to pass through assertions on user's behalf. This is required to properly distinguish between asserter and asserting caller in the integration tests.
**Testing**
> test(core): oa integration tests

- packages/core/contracts/optimistic-asserter/implementation/OptimisticAsserter.sol
- packages/core/contracts/optimistic-asserter/implementation/escalation-manager/BaseEscalationManager.sol
- packages/core/contracts/optimistic-asserter/implementation/escalation-manager/FullPolicyEscalationManager.sol
- packages/core/contracts/optimistic-asserter/interfaces/EscalationManagerInterface.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterCallbackRecipientInterface.sol
- packages/core/contracts/optimistic-asserter/interfaces/OptimisticAsserterInterface.sol
**Motivation**
```
Several contracts and functions in the codebase lack complete documentation.
```
This PR addresses this by adding missing documentation.
> fix[OA-audit-L04]: Add missing or incomplete docstrings

- CONTRIBUTING.md
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> Added missing word 'with' on line 33

- packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
- packages/core/test/foundry/data-verification-mechanism/fork-tests/FakeLifeCycle.ft.sol
- packages/core/test/hardhat/data-verification-mechanism/VotingV2.js
- packages/core/test/hardhat/data-verification-mechanism/VotingV2Gas.js
**Motivation**
To run gas tests against voting v2 we need to fix a small issue that came about after the previous audits fixes.
Additionally, this PR makes a number of small gas refinements and general clean up changes on the voting contracts.
> fix: [DVM2.0-gas-golf]: Decrease gas cost through small optimisations

- packages/core/contracts/data-verification-mechanism/implementation/SlashingLibrary.sol
- packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
- packages/core/contracts/data-verification-mechanism/implementation/test/PriceIdentifierSlashingLibaryTest.sol
- packages/core/contracts/data-verification-mechanism/implementation/test/PunitiveSlashingLibraryTest.sol
- packages/core/contracts/data-verification-mechanism/implementation/test/ZeroedSlashingLibaryTest.sol
- packages/core/contracts/data-verification-mechanism/interfaces/SlashingLibraryInterface.sol
- packages/core/test/hardhat/data-verification-mechanism/VotingV2.js
**Motivation**
This change has no effect on contracts at present but allows us to send a price request reference to the slashing library so that we can design more complicated slashing rules in the future.
For example: 
- slashing rules based on the `priceRequest.identifier`
- slashing rules based on the `priceRequest.ancillaryData`
- slashing rules based on the `priceRequest.time`
**Summary**
- Add a `bytes32 priceRequestId` param to `SlashingLibrary.calcSlashing`
- Remove unneeded function to save bytecode size
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: [DVM2.0-audit-small-refinement] slashing library price request id reference

- packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
- packages/core/test/hardhat/data-verification-mechanism/VotingV2.js
**Motivation**
We need to emit the precise slash/reward information that is given to the user for each resolved price request. 
We have made attempts in the subgraph to recreate these calculations offchain but sometimes it can be very complicated. 
The slash/reward per price request is critical information.
**Summary**
Add a new event `VoterSlashed` and change the existing one to `VoterSlashApplied`
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add partial voter slashed event

- packages/core/networks/5.json
**Motivation**
Deploy VotingV2 and SlashingLibrary latest contracts to goerli
> feat: deploy new votingv2 and slashing library goerli

- .circleci/config.yml
**Motivation**
The circleci ssh key needed to be rotated.
**Summary**
This adds the new fingerprint for the new key.
**Testing**
**Issue(s)**
N/A
> fix(ci): update circleci ssh key

- packages/core/contracts/data-verification-mechanism/implementation/VotingV2.sol
- packages/core/contracts/data-verification-mechanism/interfaces/VotingV2Interface.sol
- packages/core/test/hardhat/data-verification-mechanism/GovernorV2.js
- packages/core/test/hardhat/data-verification-mechanism/VotingV2.js
- packages/scripts/src/admin-proposals/simulateVoteV2.ts
**Summary**
Add more information to the return type of `getPendingRequests` (rollCount, isGovernance and lastVotingRound) and add new function `getProcessedPendingRequests` to be called statically off-chain to return the more up to date state of the pending price request
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add getProcessedPendingRequests

- packages/core/contracts/data-verification-mechanism/implementation/Staker.sol
**Motivation**
Small commenting change on the Staker.sol contract to match the state of comments on the VotingV2.sol contract.
> feat: small commenting change to be as consistant as posible

- packages/common/src/Constants.ts
- packages/core/deploy/057_deploy_optimistic_asserter.js
- packages/core/networks/5.json
**Motivation**
Deploy Optimistic Asserter for bot testing.
**Summary**
Adds deploy script for Optimistic Asserter and adds Goerli deployment to networks.
> feat: optimistic asserter deployment on goerli

- packages/common/package.json
- packages/common/src/HardhatConfig.ts
- yarn.lock
**Motivation**
Add support for contract verification on Boba.
**Summary**
Adds support for contract verification on Boba.
**Testing**
> feat: contract verification on boba

- packages/scripts/src/monitor-oa/MonitorAssertions.ts
- packages/scripts/src/monitor-oa/MonitorDisputes.ts
- packages/scripts/src/monitor-oa/MonitorLogger.ts
- packages/scripts/src/monitor-oa/MonitorSettlements.ts
- packages/scripts/src/monitor-oa/README.md
- packages/scripts/src/monitor-oa/common.ts
- packages/scripts/src/monitor-oa/index.ts
- packages/scripts/src/utils/contracts.ts
**Motivation**
Optimistic Asserter deployments should be monitored.
**Summary**
Adds simple monitor bot to report assertions, disputes and settlements on Optimistic Asserter.
**Testing**
> feat: implement optimistic asserter monitor

- packages/common/src/PriceIdentifierUtils.ts
**Motivation**
This identifier can't be verified by the bots.
**Summary**
Adds DECENTRA-LIST to the ignore list.
**Testing**
**Issue(s)**
N/A
> fix: ignore decentralist identifier

- package.json
- packages/serverless-orchestration/src/ServerlessHub.js
A previous PR had broken the linter within CI. this pr fixes this.
> fix: address linter issue on master

- packages/scripts/src/monitoring-dvm2.0/slashingEvents.ts
**Motivation**
The slashingEvents health checks are failing in goerli due to expected rounding deviations.
**Summary**
Add tolerance to the slashingEvents
> feat: add tolerance to slashingEvents checks

- packages/core/networks/1.json
- packages/core/networks/10.json
- packages/core/networks/137.json
- packages/core/networks/288.json
- packages/core/networks/42161.json
- packages/core/networks/5.json
**Motivation**
Due to renaming and upgrade need to have new Optimistic Oracle V3 contract deployments added.
**Summary**
Adds Optimistic Oracle V3 contract deployments to network files.
**Testing**
> feat: add OOv3 deployments

- packages/core/contracts/data-verification-mechanism/implementation/EmergencyProposer.sol
- packages/core/contracts/data-verification-mechanism/implementation/GovernorV2.sol
- packages/core/contracts/data-verification-mechanism/implementation/ProposerV2.sol
**Motivation**
Improve usability for users that require atomic calls to all DVMv2 contracts (only VotingV2 had this)
**Summary**
Adds Multicaller to GovernorV2, ProposerV2 and EmergencyProposer.
**Testing**
> feat: add multicaller to dvm v2 contracts

- packages/core/networks/5.json
**Motivation**
Deploy new DVM2.0 contracts after recent audit changes.
**Summary**
Deploy:
- VotingV2
- FixedSlashingLibrary
- GovernorV2
- ProposerV2
- EmergencyProposer
> feat: add new dvm2.0 deployments goerli

- packages/monitor-v2/src/health-check-runner/index.ts
- yarn.lock
**Motivation**
As with the deployment of the health check runner, we found some issues where logs were not propogating to Slack or discord in some situations. This PR addresses this as well as improves the quality of the log outputs.
> fix: addres issues with health-check-runner with slack and pagerduty

- packages/core/networks/1.json
**Motivation**
Add DVM2.0 contracts addresses
**Summary**
Deployed with [0_Deploy](https://github.com/UMAprotocol/protocol/blob/master/packages/scripts/src/upgrade-tests/voting2/0_Deploy.ts) and added the following addresses:
- VotingV2
- GovernorV2
- FixedSlashingLibrary
- EmergencyProposer
- ProposerV2
- VotingUpgraderV2
> feat: add dvm2.0 addresses

- packages/monitor-v2/src/monitor-dvm/index.ts
**Motivation**
There was typo in logged DVM monitor name.
**Summary**
Fixes typo in DVM monitor name at logs.
**Testing**
> fix: dvm monitor name

- packages/scripts/src/admin-proposals/executeProposalV2.ts
- packages/scripts/src/utils/contracts.ts
**Motivation**
On some operating systems web3 timed out when the existing proposal execution script is run with multicall.
**Summary**
Adds governance proposal execution script implemented in ethers and compatible with DVM2.0.
**Details**
The script can be improved to use built-in multicall funcionality of GovernorV2.
**Testing**
> feat: implement proposal execution with ethers

- packages/scripts/src/migration/dvm2-designated-voting/3_Delegate.ts
**Motivation**
In running this script, a few bugs were found that caused the payload to be invalid.
**Summary**
This PR just fixes the bugs and adds a little additional logging.
**Testing**
**Issue(s)**
N/A
> fix: fix a few bugs in 3_Delegate.ts

- packages/core/test/foundry/data-verification-mechanism/fork-tests/CommonDataVerificationMechanismForkTest.sol
**Motivation**
After the launch of the DVM2.0 there are some small updates that need to be made to some of the health checks. This PR addresses and issues with some foundry health checks.
> fix: add updated deployment addresses and fix stake size for foundry fork test

- packages/scripts/src/monitoring-dvm2.0/rollTiming.ts
**Motivation**
Mitigate request processing timing attack vector.
**Summary**
Adds DVM2.0 monitoring script that checks if any requests could be rolled into the current round.
**Testing**
> feat: monitor rollable request timing

- packages/scripts/src/admin-proposals/executeProposal.js
- packages/scripts/src/admin-proposals/simulateVote.js
- packages/scripts/src/admin-proposals/utils.js
**Motivation**
Add multicall option to execute and simulate scripts to be able to execute proposals in one tx.
**Description**
Add multicall option to execute and simulate scripts to be able to execute proposals in one tx.
> feat: add multicall option for execution in simulate and execute scripts

- packages/core/deploy/058_deploy_optimistic_governor.js
**Motivation**
Automate deployment of Optimistic Governor mastercopy.
**Summary**
Adds deployment script for Optimistic Governor mastercopy.
**Details**
It is not intended to use deployed contract directly. Instead, users should deploy minimal proxy contracts that delegate calls to this mastercopy.
**Testing**
> feat(core): deploy script for og mastercopy

- packages/scripts/src/admin-proposals/adminChildRegistration.ts
- packages/scripts/src/migration/dvm2-designated-voting/2_Migrate.ts
- packages/scripts/src/migration/dvm2-designated-voting/3_Delegate.ts
- packages/scripts/src/migration/dvm2-designated-voting/common.ts
- packages/scripts/src/utils/gnosisPayload.ts
**Motivation**
Support contract registration on networks where Admin_ChilMessenger is owned by multi-sig.
**Summary**
Modifies adminChildRegistration.ts script to output Gnosis Safe transaction payload to file.
**Testing**
> feat(scripts): admin child registration safe payload

- packages/polymarket-notifier/src/polymarketNotifier.js
**Motivation**
The current polymarket notifier implementation works but we should set the resolution contract as we did previously for consistency.
**Summary**
Undo the changes in the `resolutionContract` configuration.
> fix: resolution contract polymarket notifier

- packages/core/networks/100.json
- packages/core/networks/43114.json
- packages/core/networks/82.json
**Motivation**
Optimistic Governor depend on Optimistic Oracle V3 deployments on multisig relay chains.
**Summary**
Adds Optimistic Oracle V3 deplpoyments on Gnosis and Avalanche chains.
**Testing**
> feat(core): optimistic oracle v3 deployments on multisig relay chains

- packages/core/networks/1.json
- packages/core/networks/10.json
- packages/core/networks/100.json
- packages/core/networks/137.json
- packages/core/networks/288.json
- packages/core/networks/42161.json
- packages/core/networks/5.json
**Motivation**
Publish deployed Optimistic Governor contracts
**Summary**
Adds deployments of Optimistic Governor mastercopy contracts
**Testing**
> feat(core): add optimistic governor mastercopy deployments

- packages/core/networks/43114.json
**Motivation**
Publish deployed Optimistic Governor contract on Avalanche.
**Summary**
Adds deployment of Optimistic Governor mastercopy contract on Avalanche.
**Details**
This is follow-up PR to #4497 that had missing Avalanche deployment.
**Testing**
> feat(core): optimistic governor mastercopy on avalanche

- packages/polymarket-notifier/index.js
- packages/polymarket-notifier/src/polymarketNotifier.js
**Summary**
Configures the polymarket notifier correctly. Previous values were for testing purposes.
> feat: configure polymarket notifier

- packages/polymarket-notifier/README.md
- packages/polymarket-notifier/index.js
- packages/polymarket-notifier/src/polymarketNotifier.js
**Motivation**
Filter out markets with low liquidity from the polymarket notifier the reduce false positives alerts.
> feat: filter markets with low liquidity in polymarket notifier

- packages/scripts/src/utils/votingv2-utils.ts
**Motivation**
Updating trackers for all voters in a single multicall was causing out of gas issues. 
**Summary**
Batch update trackers in dvm2.0 health checks simulations.
> fix: dvm2.0 health checks simulation gas issues

- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
- packages/optimistic-oracle/src/proposer.js
**Motivation**
This small PR changes some details on problematic logger levels to try and make on-call live a little bit easier.
> feat: change logging levels

- package.json
- packages/common/src/EthersSignerUtils.ts
- packages/monitor-v2/src/bot-oo-v3/BotLogger.ts
- packages/monitor-v2/src/bot-oo-v3/README.md
- packages/monitor-v2/src/bot-oo-v3/SettleAssertions.ts
- packages/monitor-v2/src/bot-oo-v3/common.ts
- packages/monitor-v2/src/bot-oo-v3/index.ts
- packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
- packages/monitor-v2/src/monitor-oo-v3/common.ts
- packages/monitor-v2/src/utils/EventUtils.ts
- packages/monitor-v2/src/utils/contracts.ts
- packages/monitor-v2/test/OptimisticGovernorMonitor.ts
- packages/monitor-v2/test/OptimisticOracleV3Bot.ts
- yarn.lock
**Motivation**
Create a bot to settle OOv3 Assertions
**Summary**
- Create bot scaffolding
- Add settlement task
- Add tests
- Fix unrelated issues in OG monitoring
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: settle assertions bot

- packages/scripts/src/admin-proposals/simulateVoteV2.ts
- packages/scripts/src/monitoring-dvm2.0/simulateVoting.ts
- packages/scripts/src/upgrade-tests/voting2/3_SimulateVoting.ts
- packages/scripts/src/upgrade-tests/voting2/migrationUtils.ts
- packages/scripts/src/utils/constants.ts
- packages/scripts/src/utils/contracts.ts
- packages/scripts/src/utils/votingv2-utils.ts
**Motivation**
Allow regularly testing that VotingV2 contract is fully functional.
**Summary**
Adds health check script adapted from original packages/scripts/src/upgrade-tests/voting2/3_SimulateVoting.ts
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(scripts): vote simulation health check

- packages/scripts/src/admin-proposals/simulateVoteV2.ts
**Motivation**
When testing governance proposals it might be required to separately simulate and trace proposal execution (e.g. using executeProposalV2.ts)
**Summary**
Adds SKIP_EXECUTE option to vote simulation script in simulateVoteV2.ts
**Testing**
> feat(scripts): option to skip simulated vote execution

- packages/scripts/src/admin-proposals/simulateVoteV2.ts
**Motivation**
Improve vote simulation when testing new governance proposals to be as close as possible to actual state of DVM. 
**Summary**
Adds REAL_VOTERS option to simulateVoteV2.ts to impersonate all existing stakers in the contract when voting for proposed governance request.
**Testing**
> feat(scripts): simulate vote by all real stakers

- packages/monitor-v2/src/monitor-og/index.ts
**Motivation**
Optimistic Governor monitor had misleading startup/error messages.
**Summary**
Fixes Optimistic Governor monitor bot startup/error messages.
**Testing**
> fix(monitor-v2): og startup and error messages

- packages/monitor-v2/src/bot-oo-v3/README.md
- packages/monitor-v2/src/bot-oo-v3/SettleAssertions.ts
- packages/monitor-v2/src/bot-oo-v3/common.ts
- packages/monitor-v2/src/bot-oo-v3/index.ts
- packages/monitor-v2/test/OptimisticOracleV3Bot.ts
**Motivation**
The OOv3 settlement bot wasn't compatible with serverless environments. This PR updates the OOv3 bot to allow it to work as a single execution + adds gckms provider option. 
**Summary**
- Remove warming up concept
- Add same polling_delay pattern that the rest of bots have
- Add gckms
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: update oov3 settlement bot

- packages/monitor-v2/src/monitor-polymarket/common.ts
**Motivation**
reduse load on gql queries to polymarket in hopes we can reduce failed requests
**Summary**
filter out resolution status of markets to avoid settled and resolved
**Details**
**Testing**
> feat: reduce gql query size using additional filters

- packages/monitor-v2/src/monitor-polymarket/MonitorLogger.ts
- packages/monitor-v2/src/monitor-polymarket/index.ts
**Motivation**
There are two packages related to Polymarket (`packages/polymarket-notifier` and `packages/monitor-v2/src/monitor-polymarket`). They need to be distinguishable in logs.
**Summary**
Fixes bot label for `monitor-polymarket` to `PolymarketMonitor`. Also adds route to `infrastructure-error` notification path in case of errors.
**Testing**
> fix: polymarket monitor notifications

- packages/core/config/adapters/defiLlama/oSnap.json
**Motivation**
Add oSnap DefiLlama adapter config to be used by the [DefiLlama oSnap adapter](https://github.com/DefiLlama/DefiLlama-Adapters/pull/6024)
This config file is intended to be updated with new avatars and tokens to track.
> feat: add osnap defi llama adapter config

- packages/monitor-v2/src/monitor-polymarket/MonitorLogger.ts
- packages/monitor-v2/test/PolymarketMonitor.ts
- Set polymarket notifier logs level to `error`
> feat: turn on errors polymarket notifier

- packages/scripts/src/monitoring-dvm2.0/simulateVoting.ts
- packages/scripts/src/utils/constants.js
- packages/scripts/src/utils/seedProposerWithUma.js
**Motivation**
Remove the `accountWithUma` wallet from the tests and simulation scripts as this solution was not ideal to test and can be replaced with minting role wallet impersonation.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: remove account with uma

- packages/core/networks/1.json
**Motivation**
Add OriginValidator address
https://etherscan.io/address/0xed883ce9bb10416FF3113FDB4Abcb9830617aD27#code
> feat: add origin validator address mainnet

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/84531.json
**Motivation**
We would like to support a minimal viable Base goerli implementation. This PR implements the simplest posible setup to get the OOv3 running on Base goerli. Associated networks and config files are updated.
> feat: Deploy to Base Goerli

- packages/scripts/src/utils/votingv2-utils.ts
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: update trackers health checks

- packages/monitor-v2/src/price-speed-up/README.md
> fix: speed up readme

- packages/financial-templates-lib/src/clients/OptimisticOracleClient.ts
- packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
Fixes UMA-1394
**Motivation**
The OOv2 settler bot was not working for event based disputed and resolved price requests in the OOv2.
**Summary**
Fix the bot to work with OOv2 event based disputes
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: update optimistic oracle client to work with oov2

- packages/scripts/src/admin-proposals/change-final-fee/0_Propose.ts
- packages/scripts/src/admin-proposals/change-final-fee/1_Verify.ts
- packages/scripts/src/admin-proposals/change-final-fee/2_VerifyRelays.ts
- packages/scripts/src/admin-proposals/change-final-fee/README.md
- packages/scripts/src/admin-proposals/change-final-fee/common.ts
- packages/scripts/src/utils/relay.ts
**Motivation**
Add dvm2.0 set final fee proposal scripts
> feat: add dvm2.0 set final fee proposal scripts

- packages/common/src/TransactionUtils.ts
- packages/financial-templates-lib/src/helpers/GasEstimator.ts
- packages/financial-templates-lib/test/helpers/GasEstimator.js
Fixes UMA-1591
**Motivation**
The previous Gas Estimator was broken, mainly because the API used were not working.
By updating the API's we use, I think, we can fix it with the fewest changes.
I also considered using making the [web3/ethers param here](https://github.com/UMAprotocol/protocol/blob/4fa5c04125da1d77a8779aceac2da97f86607931/packages/financial-templates-lib/src/helpers/GasEstimator.ts#L105) mandatory so we can calculate the maxFeePerGas & maxPriorityFeePerGas without relying on free external and probably rate limited API's. But this would require bigger changes.
```
const pendingBlock = await web3.eth.getBlock("pending") 
const baseFee = pendingBlock.baseFeePerGas;
// maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas
const maxFeePerGas = baseFeePerGas * 3;
const …
```
> fix: gas estimator

- packages/monitor-v2/src/monitor-polymarket/common.ts
**Motivation**
Polymarket notifier was notifying more than once
**Summary**
Fix typo in market storage in gcp datastore.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: notified polymarket markets storage

- packages/core/deploy/057_deploy_optimistic_oracle_V3.js
- packages/core/networks/80001.json
**Motivation**
Users would like to test with the OOv3 on mumbai.
**Summary**
Added a Mumbai deployment of the OOV3 using hardhat deploy.
**Testing**
**Issue(s)**
N/A
> feat: add OOV3 on Mumbai

- packages/monitor-v2/package.json
- packages/monitor-v2/src/monitor-og/README.md
- packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
- packages/monitor-v2/src/monitor-og/common.ts
**Motivation**
There might be transient errors when fetching off-chain data for Snapshot verification. Adding retry logic could make the oSnap monitoring bot more robust.
**Summary**
Adds retry logic to IPFS and GraphQL requests when performing oSnap proposal verification.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(monitor-v2): add retry logic to snapshot verification

- packages/monitor-v2/src/llm-bot/common.ts
**Motivation**
In the context of the LLM disputer bots we want to implement an Optimist Oracle Client class to interact with the OO's and fetch the price requests and translate them to a unified type and store them.
This is a simple initial implementation to start with
**Summary**
> feat: add llm bot oo client class

- packages/monitor-v2/src/monitor-og/README.md
**Motivation**
#4587 added Tenderly simulation link to oSnap proposals, but lacked documentation.
**Summary**
Adds documentation on required environment variables for Tenderly simulation in oSnap monitor bot.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(monitor-v2): document tenderly env

- packages/monitor-v2/src/monitor-polymarket/README.md
**Motivation**
Fix typo
**Summary**
Fixes typo in PolyMarket notifier bot.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(monitor-v2): update pm readme

- packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
**Motivation**
Address [this comment](https://github.com/UMAprotocol/protocol/pull/4591#discussion_r1262827255) on logging oSnap automation errors.
**Summary**
Instead of throwing error, logs the error and proceeds with the next proposal/dispute.
**Details**
We still throw an error for failed bond approvals as that would anyway block submission of proposals/disputes.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1652/osnap-bot-error-logging
> fix(monitor-v2): log osnap proposal/dispute errors

- packages/monitor-v2/src/llm-bot/common.ts
- packages/monitor-v2/src/llm-bot/examples.ts
**Motivation**
Add filter class to filter OptimisticOracleClients requests and return new copies of them.
**Summary**
- Added simple OracleClientFilter interface that can receive an augmented OptimisticOracleClient and return the same type or a new one
- Added examples file and moved some code there
> feat: add llm filter interface

- packages/monitor-v2/src/bot-oo-v3/index.ts
- packages/monitor-v2/src/health-check-runner/index.ts
- packages/monitor-v2/src/monitor-dvm/index.ts
- packages/monitor-v2/src/monitor-og/index.ts
- packages/monitor-v2/src/monitor-oo-v3/index.ts
- packages/monitor-v2/src/monitor-polymarket/index.ts
- packages/monitor-v2/src/price-publisher/index.ts
- packages/monitor-v2/src/price-speed-up/index.ts
**Motivation**
Bots in monitor-v2 package did not properly wait for logger to flush.
**Summary**
Adds waiting for logger to flush in monitor-v2 package.
**Details**
Existing 5 second delay was sufficient for logger to deliver on all transports for bots in monitor-v2 package. With the introduction of Discord Ticket Tool Transport that highly depends on back-off due to rate limiting this might not be sufficient and we need feedback from transports to check if process can safely exit.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(monitor-v2): wait for logger

- packages/monitor-v2/src/monitor-oo-v3/MonitorLogger.ts
- packages/monitors/src/OptimisticOracleContractMonitor.js
**Motivation**
OO proposals/assertions should be routed to Discord Ticket Tool command channel.
**Summary**
Adds Discord Ticket Tool channel of OO proposals/assertions.
**Details**
This depends on Discord Ticket transport for alert delivery. Particularly, this should not be merged in before #4607 to deal with Ticket Tool rate limits and #4611 to wait for logger to flush in monitor-v2 package.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add discord ticket channel for oo verification

- packages/financial-templates-lib/src/logger/DiscordTicketTransport.ts
**Motivation**
Discord Ticket transport failed to deliver messages above 2000 characters.
**Summary**
Truncates Discord ticket transport messages if it exceeds 2000 characters.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(financial-templates-lib): truncate discord ticket transport

- packages/monitor-v2/package.json
- packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
- yarn.lock
**Motivation**
oSnap bot replay protection does not fully protect against replay attacks where the attacker submits second proposal with changed casing for CIDv1 in explanation. The bot would think its a different Snapshot proposal while the IPFS gateway would still resolve the proposal with alternative casing.
**Summary**
Adds IPFS hash validation to oSnap verification logic.
**Details**
Uses multiformats library trying to parse explanation as CID. This parses only lower case CIDv1 strings, so any attack trying to pass upper casing would be detected.
**Testing**
Writing unit tests would require implementing mocked servers for ipfs content and serving graphql queries. Instead, this was tested as …
> feat(monitor-v2): validate osnap explanation

- packages/monitor-v2/src/bot-oo-v3/common.ts
- packages/monitor-v2/src/llm-bot/OptimisticOracleV2Client.ts
- packages/monitor-v2/src/llm-bot/common.ts
- packages/monitor-v2/src/llm-bot/examples.ts
- packages/monitor-v2/src/utils/constants.ts
- packages/monitor-v2/test/OptimisticOracleV2Client.ts
- packages/monitor-v2/test/constants.ts
- packages/monitor-v2/test/fixtures/OptimisticOracleV2.Fixture.ts
**Motivation**
Implement the OptimisticOracleV2Client class for LLM (Liquidation Limit Monitoring) bots to retrieve and process price requests from the Optimistic Oracle V2 contract.
**Summary**
- Store requests in a map to prevent duplications
- The OOv2 client doesn't allow gaps between fetched block ranges forcing to process the blocks linearly
- Added isEventBased, blockNumber and transactionIndex to the `OptimisticOracleRequest` class
- Added setters in `OptimisticOracleRequest` for attributes that should be updated with contract events updates (e.g. price request is proposed, assertion is disputed, etc...)
- Introduced blockDefaults in constants.ts to store default block configurations.
- Created OptimisticOracleV2Client implementation to fetch Optimistic Oracle V2 data
**Testing** …
> feat: base oov2 client implementation

- packages/financial-templates-lib/src/logger/DiscordTicketTransport.ts
- packages/financial-templates-lib/test/logger/DiscordTicketTransport.truncateMessage.js
**Motivation**
Improve Discord Ticket verification by trying to preserve URLs in the message when truncating due to Discord character limit. This would allow to retain sufficient pointers (e.g. Oracle UI link) when parts of the message are truncated.
**Summary**
Modifies Discord Ticket message truncating logic to try preserve included URLs.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(financial-templates-lib): preserve url in truncated discord ticket

- packages/monitor-v2/src/monitor-og/index.ts
**Motivation**
Improve robustness of oSnap bot so that errors in one module do not affect processing of other modules.
**Summary**
Settles all promises on individual bot modules and errors each rejection separately.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(monitor-v2): settle all promises in osnap bot

- packages/scripts/src/admin-proposals/add-address-whitelist/0_Propose.ts
- packages/scripts/src/admin-proposals/add-address-whitelist/1_Verify.ts
- packages/scripts/src/admin-proposals/add-address-whitelist/readme.md
**Motivation**
Add script to whitelist a new address in AddressWhitelist and set the final fee in the Store for the corresponding address.
**Summary**
- Proposal script
- Verification script
- Readme
> feat: add proposal script to whitelist address and set final fee

- packages/optimistic-oracle/index.js
- packages/optimistic-oracle/test/index.js
**Motivation**
Ensure automatic Oracle dispute settlement on mainnet.
**Summary**
Updates default Oracle type to VotingV2.
**Details**
Optimistic Oracle proposer bot did not settle disputes on mainnet as the default Oracle to request resolved price still pointed to Voting while this needs upgrade to VotingV2. This was left unnoticed as most of disputes are on L2 networks where prices are resolved through OracleSpoke or OracleChildTunnel.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(optimistic-oracle): default oracle type

- packages/monitor-v2/src/llm-bot/OptimisticOracleV2.ts
- packages/monitor-v2/src/llm-bot/common.ts
- packages/monitor-v2/src/llm-bot/examples.ts
- packages/monitor-v2/test/OptimisticOracleV2LLM.ts
**Motivation**
Implement LLMStrategy class for LLM bot
Depends on https://github.com/UMAprotocol/protocol/pull/4594/files
> feat: add llm strategy class

- packages/scripts/src/admin-proposals/funding/0_Propose.ts
- packages/scripts/src/admin-proposals/funding/README.md
**Motivation**
Automate funding proposals in DVM2
**Summary**
Adds admin proposal script for single token funding from UMA governance.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1761/create-and-verify-proposal-for-ostake-uma-transfer
> feat: add governance funding proposal script

- packages/fx-tunnel-relayer/package.json
- yarn.lock
**Motivation**
fx-tunnel-relayer bot requires update in its matic dependency libs.
**Summary**
Updates fx-tunnel-relayer matic dependencies
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(fx-tunnel-relayer): bumb matic lib dependencies

- packages/affiliates/CHANGELOG.md
- packages/affiliates/package.json
- packages/api/CHANGELOG.md
- packages/api/package.json
- packages/contract-notifier/CHANGELOG.md
- packages/contract-notifier/package.json
- packages/financial-templates-lib/CHANGELOG.md
- packages/financial-templates-lib/package.json
- packages/fx-tunnel-relayer/CHANGELOG.md
- packages/fx-tunnel-relayer/package.json
- packages/llm-bot/package.json
- packages/monitor-v2/CHANGELOG.md
- packages/monitor-v2/package.json
- packages/monitors/CHANGELOG.md
- packages/monitors/package.json
- packages/optimistic-oracle/CHANGELOG.md
- packages/optimistic-oracle/package.json
- packages/polymarket-notifier/CHANGELOG.md
- packages/polymarket-notifier/package.json
- packages/scripts/CHANGELOG.md
- packages/scripts/package.json
- packages/serverless-orchestration/CHANGELOG.md
- packages/serverless-orchestration/package.json
**Motivation**
There have been quite some new features/fixes since last release and some of our docs reference npm packages that are out of date.
**Summary**
Runs release
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1767/publish-npm-releases-for-protocol
> feat: run release

- packages/llm-bot/CHANGELOG.md
**Motivation**
Forgot to add untracked changelog in #4641 
**Summary**
Adds missing changelog file for llm-bot
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: add missing llm-bot changelog

- packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
- packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
**Motivation**
Bots need to support Snapshot proposals with the new oSnap plugin.
**Summary**
Adds support of new oSnap plugin to oSnap monitoring and automation bots.
**Details**
**Testing**
In order to check that adding oSnap plugin support does not break existing bots this was tested as in production on Goerli:
- Used this [safe](https://goerli.etherscan.io/address/0xb2e88B3B3B4684bF55a667c85b6A2a59f85e568F) and [oSnap module](https://goerli.etherscan.io/address/0xf2E0ed03c11B7A09afA1Ca8ECd376D13A1cb6b20) on Goerli with 0 WETH bond, 5 minute liveness, 0 …
> feat: osnap plugin support in bots

- packages/monitors/test/index.js
**Motivation**
Kraken has shut down cryptowat.ch api causing some of monitors package tests to fail and block new PRs. We don't run any financial contract bots, so this should not affect security.
**Summary**
Removes financial contract tests in monitors that required cryptowat.ch api access.
**Details**
We might want to delete all financial contract support in bots in a separate PR.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-1876/cryptowatch-api-no-longer-works-causing-ci-to-fail
> fix: remove cryptowatch related tests

- packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
**Motivation**
oSnap automation bot produces error alerts on insufficient bond balance even if transaction submission has been deliberately turned off. We should reduce alert noise in this case.
**Summary**
Adds bot balance check and reduces log level to warn when transaction submission would fail due to insufficient funding and transaction submission has been turned off.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: suppress error based on balance

- packages/common/src/PublicNetworks.ts
- packages/monitor-v2/src/balance-monitor/BalanceMonitor.ts
- packages/monitor-v2/src/balance-monitor/README.md
- packages/monitor-v2/src/balance-monitor/common.ts
- packages/monitor-v2/src/balance-monitor/index.ts
**Motivation**
Avoid bot errors by monitoring their balances.
**Summary**
Adds generic account balance monitor bot.
**Details**
Both native token and ERC-20 token balance monitoring is supported.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2065/add-balance-monitoring-for-the-backrunner-and-rpc-addresses
> feat: generic balance monitor

- packages/common/package.json
- packages/common/src/AxiosRetry.ts
- packages/common/src/ObjectUtils.ts
- packages/common/src/TenderlyFork.ts
- packages/common/src/TenderlySimulation.ts
- packages/common/src/index.ts
- yarn.lock
**Motivation**
Monitoring bots might require to simulate a series of transactions (e.g. propose / execute oSnap proposals).
**Summary**
Adds Tenderly fork management methods to `@uma/common`.
**Details**
Also improves existing simulation module by using axios in a wrapped retry and adding docstrings.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: add tenderly fork management

- packages/common/src/TenderlySimulation.ts
**Motivation**
#4673 introduced bug when adding Tenderly fork management as its API response interface differs whether doing regular or forked simulation.
**Summary**
Fixes the issue by type checking both potential API response interfaces when creating the simulation request.
**Details**
Forked simulation response had its gas usage encoded as hex string in `simulation.receipt.gasUsed` while for regular simulations it was returned as number in `simulation.gas_used`.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: tenderly simulation response interface

- packages/monitor-v2/src/monitor-polymarket/abi/ctfAdapterV2.json
- packages/monitor-v2/src/monitor-polymarket/common.ts
- packages/monitor-v2/src/utils/contracts.ts
- packages/monitor-v2/test/PolymarketMonitor.ts
- Add new adapter to polymarket notifier
> feat: add new polymarket adapter to notifier

- .circleci/config.yml
- Dockerfile
- README.md
This reverts commit 8a07c79e93b6c07de3ccccdbddf534c0eb0f67c9.
> Revert "fix: update nodejs version (#4678)"

- packages/api/src/libs/osnap/utils.ts
- packages/api/src/services/actions/osnap.ts
**Motivation**
oSnap frontend requires API to simulate proposal execution.
**Summary**
API simulates requested oSnap proposal execution against Tenderly API.
**Details**
In order to simulate execution without forking, contract state needs to be overriden as if transactions were already proposed on oSnap and settled on OOv3:
- OptimisticGovernor knows of proposalHash pointing to non-zero asserionId in the assertionIds mapping;
- OptimisticOracleV3 has the Assertion with the above assertionId marked as settled.
This has a dependency on state override feature in `@uma/common` Tenderly simulation library, thus it can be merged only after #4688.
**Testing**
**Issue(s)**
Fixes …
> feat(api): api simulates osnap execution

- packages/monitor-v2/src/monitor-polymarket/common.ts
> feat: add polymarket api key to notifier

- packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
- packages/monitor-v2/src/monitor-polymarket/common.ts
- Fix polymarket notifier ancillary data fetching
> feat: fix polymarket notifier ancillary data fetching

- packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
- packages/monitor-v2/src/monitor-polymarket/common.ts
- Fetch price request status from polymarket adapters
- Type refactoring
> feat[polymarket-notifier]: fetch resolved status from polymarket adapter

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/common/src/TimeUtils.ts
- packages/common/src/hardhat/tasks/collateralWhitelist.ts
- packages/common/src/hardhat/tasks/finder.ts
- packages/common/src/hardhat/tasks/ownership.ts
- packages/common/src/hardhat/tasks/xchainSetup.ts
- packages/core/contracts/cross-chain-oracle/README.md
- packages/core/deploy/057_deploy_optimistic_oracle_V3.js
**Motivation**
Prepare scripts and configuration for OO deployment on https://coredao.org/
**Summary**
Updates scripts for non-rollup chain deployments and adds https://coredao.org network parameters.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2042/spec-oo-deployment-to-core-protocol
> feat: core deployment tasks

- packages/core/contracts/cross-chain-oracle/README.md
- packages/financial-templates-lib/src/helpers/GasEstimator.ts
**Motivation**
Core network has legacy gas settings and core network bots will require this being set in gas estimator.
**Summary**
Adds core network settings to gas estimator .
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: add core network gas estimation settings

- packages/monitor-v2/src/monitor-og/oSnapAutomation.ts
**Motivation**
Polygon gas price estimation doesn't seem to work on the oSnap automation.
**Testing**
> fix: oSnap automation polygon gas price estimation

- packages/core/contracts/cross-chain-oracle/README.md
- packages/core/networks/1116.json
**Motivation**
We've deployed OO contracts on Core mainnet that needs to be added to networks file.
**Summary**
Adds Core mainnet contract deployments.
**Details**
Verified contract state with `yarn hardhat verify-admin-xchain --network core`:
```
🌚 Verifying L2 contract state 🌚
Registry
- OptimisticOracle registered: ✅
- OptimisticOracleV2 registered: ✅
- OptimisticOracleV3 registered: ✅
- Owned by GovernorSpoke: ✅
Store
- Owned by GovernorSpoke: ✅
IdentifierWhitelist
- Owned by GovernorSpoke: ✅
AddressWhitelist
- Owned by GovernorSpoke: ✅
OptimisticOracleV3
- Owned by GovernorSpoke: ✅
Admin_ChildMessenger
- Set oracleSpoke: ✅
Finder
- Owned by GovernorSpoke: ✅
- Set "Store" in Finder: ✅
- Set "IdentifierWhitelist": ✅
- Set "CollateralWhitelist" in Finder: ✅
- Set "Oracle" in Finder (to …
```
> feat: add core network deployments

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/168587773.json
deployed sandboxed oracle environment to Blast Sepolia
> feat: deploy to Blast Sepolia

- packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
**Motivation**
Snapshot has changed its IPFS storage format, so we need to adjust oSnap bot logic.
**Summary**
Removes vote start/end timestamp verification from oSnap IPFS data.
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: remove vote periods from osnap ipfs verification

- scripts/run_release.sh
**Summary**
This flag should help on ignore Lerna to publish untracked files.
**Testing**
> fix(ci): ignore changes on temp folder

- .circleci/config.yml
- scripts/run_release.sh
**Summary**
Updates the method used to avoid missing folders
**Testing**
> fix(ci): Avoid missing packages folders

- packages/scripts/src/admin-proposals/change-final-fee/0_Propose.ts
- packages/scripts/src/admin-proposals/change-final-fee/1_Verify.ts
- packages/scripts/src/admin-proposals/change-final-fee/2_VerifyRelays.ts
- packages/scripts/src/admin-proposals/change-final-fee/README.md
- packages/scripts/src/admin-proposals/change-final-fee/common.ts
- Update governance proposal script to update final fees to take any erc20 token and whitelist when necessary.
> feat(script): update change final fee script

- packages/serverless-orchestration/src/ServerlessHub.js
- packages/serverless-orchestration/test/ServerlessHub.js
**Motivation**
The logic for multichain bot block number fetching in serverless hub still deviates from single chain bots that result in not caching of fetched block numbers for multichain bots and starting from genesis block first time when multichain bot is added for new chain.
**Summary**
Fixes the issue by using the same logic in multichain block number fetching as is used for single chain bots.
**Details**
Batches single chain and multichain block number fetching in a single promises array that is then processed using the same logic.
**Testing**
**Issue(s)**
Fixes: https://linear.app/uma/issue/UMA-2413/improve-block-number-fetching-for-multichain-blocks-in-hub
> fix: multichain blocks in serverless hub

- packages/monitor-v2/src/monitor-polymarket/MonitorProposalsOrderBook.ts
- packages/monitor-v2/src/monitor-polymarket/common.ts
- Polymarket api can return null resolvedBy address
> fix: polymarket api resolvedBy can be null

- packages/common/src/Constants.ts
- packages/common/src/Enums.ts
- packages/common/src/HardhatConfig.ts
- packages/common/src/hardhat/tasks/collateralWhitelist.ts
- packages/common/src/hardhat/tasks/dvmv2Testnet.ts
- packages/common/src/hardhat/tasks/registry.ts
- packages/core/contracts/data-verification-mechanism/README.md
- packages/core/deploy/003_deploy_registry.js
- packages/core/deploy/005_deploy_identifier_whitelist.js
- packages/core/deploy/008_deploy_store.js
- packages/core/deploy/011_deploy_address_whitelist.js
- packages/core/deploy/012_deploy_optimistic_oracle.js
- packages/core/deploy/035_deploy_skinny_optimistic_oracle.js
- packages/core/deploy/051_deploy_optimistic_oracle_V2.js
- packages/core/deploy/052_deploy_fixed_slash_slashing_library.js
- packages/core/deploy/053_deploy_votingV2.js
- packages/core/deploy/054_deploy_designated_votingV2_factory.js
- packages/core/deploy/056_deploy_skinny_optimistic_oracle_V2.js
- packages/core/deploy/057_deploy_optimistic_oracle_V3.js
- packages/core/deploy/060_deploy_proposer_v2.js
- packages/core/deploy/061_deploy_emergency_proposer.js
- packages/core/networks/11155111.json
**Motivation**
With the deprecation of Goerli, we need to deploy UMA Oracle contracts on Sepolia.
**Summary**
Adds UMA Oracle contract deployments for Sepolia testnet.
**Details**
Previously DVMv2 was deployed using upgrade scripts when migrating from prior version. For a fresh setup on new testnet we also needed adding support of DVMv2 on hardhat deploy scripts and setup tasks.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2348/contract-deployments
> feat: sepolia deployments

- packages/core/networks/11155111.json
**Motivation**
Voter dApp has dependency on old DVM v1 contracts, so we need to deploy them for Sepolia.
**Summary**
Adds deployed DVMv1 contracts for Sepolia
**Testing**
**Issue(s)**
Fixes #XXXX
> feat: old dvm contracts for sepolia

- Dockerfile
cc @james-a-morris 
**Testing**
> fix(ci): Update yarn execution

- Dockerfile
**Motivation**
We had some builds that not finished properly, because the docker image got inconsistent builds. The issue was a package when was installed as a dependency, they are sometimes not found by other package. To solve, we installed it on the environment.
**Testing**
> fix(ci): Adjust npx package concurreny

- packages/scripts/src/testnet/OptimisticOracleRequestSender.ts
- update testnet request sender to support sepolia
> feat: update testnet request sender to support sepolia

- packages/logger/package.json
- packages/logger/src/constants.ts
- packages/logger/src/helpers/typeGuards.ts
- packages/logger/src/index.ts
- packages/logger/src/logger/DatastoreTransport.ts
- packages/logger/src/logger/DiscordTicketTransport.ts
- packages/logger/src/logger/DiscordTransport.ts
- packages/logger/src/logger/Logger.ts
- yarn.lock
**Motivation**
Discord Ticket Tool transport can fail to log all messages within a serverless call if this exceeds rate limit of 15 logs per second.
**Summary**
Introduces persistent log queue management for Discord Ticket transport. Any rate limited logs would be resumed on the next run cycle.
**Details**
This creates an abstract base DatastoreTransport base class that saves all logged messages to Datastore. It has separate logic to process all messages upon logger creation or whenever new messages is logged by via the derived transport. The log queue processing method gets the oldest stored message with matching bot identifier that should be delivered by the derived transport respecting any of its rate limits. Processing of log queue continues till the queue is empty or the transport …
> fix: use persistent log queue for discord tickets

- packages/scripts/src/admin-proposals/add-identifier/0_Propose.ts
- packages/scripts/src/admin-proposals/add-identifier/1_Verify.ts
- packages/scripts/src/admin-proposals/add-identifier/2_VerifyRelays.ts
- packages/scripts/src/admin-proposals/add-identifier/common.ts
- packages/scripts/src/admin-proposals/add-identifier/readme.md
- Update identifier whitelist admin script to support rollups
> feat: update admin identifier whitelist script to support rollups

- packages/core/networks/8453.json
- Deploy Optimistic Governor mastercopy in Base
> feat: deploy optimistic governor mastercopy base

- packages/financial-templates-lib/src/helpers/GasEstimator.ts
**Motivation**
Blast bots were failing on gas estimation.
**Summary**
Use static 1 Gwei gas price on Blast and Base.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: blast and base gas estimator

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/core/deploy/057_deploy_optimistic_oracle_V3.js
- packages/core/networks/84532.json
- Support Base sepolia testnet
> feat: deploy base sepolia contracts

- packages/monitor-v2/src/price-publisher/PublishPrices.ts
- packages/monitor-v2/src/price-publisher/common.ts
- packages/monitor-v2/test/DVM2PricePublisherBot.ts
**Motivation**
Blast Oracle integrations require automated price publishing when resolved via DVM.
**Summary**
Ads support for Blast network in price publisher bot.
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2548/support-blast-in-dvm-price-publisher
> feat: support blast in dvm price publisher

- packages/common/src/HardhatConfig.ts
- packages/common/src/PublicNetworks.ts
**Motivation**
At the time when Amoy testnet contracts were deployed, Polygon listed OKLINK explorer as the primary block explorer and we used it for UMA protocol contract verification. Now that Polygon has switched their primary Amoy testnet to Polygonscan we expect most users would be interacting with UMA contracts through it.
**Summary**
Switch Amoy testnet block explorer to Polygonscan.
**Details**
We also now have verified deployed UMA protocol contracts on https://amoy.polygonscan.com/
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: switch to polygonscan for amoy

- packages/monitor-v2/src/monitor-og/SnapshotVerification.ts
**Motivation**
We plan to support multiple safes for oSnap plugin in Snapshot frontend. This requires updating the oSnap bot logic to support this once this feature is enabled in the frontend.
**Summary**
Adds support for multiple safes in oSnap plugin proposals.
**Details**
We keep single safe oSnap plugin support for backwards compatability
**Testing**
**Issue(s)**
Fixes https://linear.app/uma/issue/UMA-2584/update-bots-to-support-multiple-safe-format
> feat: support multiple safes in osnap plugin

- packages/optimistic-oracle/index.js
**Motivation**
we are getting timeouts and event query exceeded on blast network, seems lookback adjustments are not helping.
**Summary**
Theres a hardcoded lookback which we now use a config for if defined.
**Details**
we are overloading the lookback value originally used for oo proposer
**Testing**
**Issue(s)**
Fixes #XXXX
> improve(oo): reuse lookback config when initing ooclient

- packages/fx-tunnel-relayer/src/index.ts
**Motivation**
Tests were breaking with deprecation of Mumbay
**Summary**
Replaces mumbai with amoy in maticPOSClient init function
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(fx-tunnel-relayer): replace mumbay with amoy

- README.md
> Update README.md to fix broken image.

- packages/common/src/HardhatConfig.ts
- packages/common/src/ProviderUtils.ts
- packages/common/src/PublicNetworks.ts
- packages/core/networks/1513.json
illiad is Story Protocol's testnet:
https://docs.story.foundation/docs/story-network
> feat: deploy to illiad

- packages/scripts/src/admin-proposals/add-identifier/0_Propose.ts
- packages/scripts/src/admin-proposals/add-identifier/2_VerifyRelays.ts
- packages/scripts/src/admin-proposals/add-identifier/common.ts
- packages/scripts/src/admin-proposals/add-identifier/readme.md
- Add blast network to the identifier proposal scripts
> feat(admin-scripts): add blast to identifier proposal scripts

- packages/common/src/HardhatConfig.ts
- packages/common/src/PublicNetworks.ts
- Update Story network URLs after the mainnet launch
> feat(networks): update story mainnet urls

- packages/scripts/src/admin-proposals/set-gat-and-spat/0_Propose.ts
- packages/scripts/src/admin-proposals/set-gat-and-spat/1_Verify.ts
- packages/scripts/src/admin-proposals/set-gat-and-spat/README.md
- Add admin proposal scripts to update GAT and SPAT in VotingV2
> feat(admin-scripts): admin proposal to set gat and spat

- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/proposer.js
- packages/optimistic-oracle/test/proposerV2.js
- packages/optimistic-oracle/test/skinnyProposer.js
**Motivation**
We have seen degraded bot performance due to emitting massive amounts of debug logs (>2k per run on Polygon),
**Summary**
Removes debug log for ignored identifier in the OO proposer bot. This is not so useful anyways now that there are no synthetic contracts and all requests end up on the ignored list.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: drop debug logs for blacklisted identifiers

- packages/monitor-v2/src/monitor-polymarket/common.ts
- packages/monitor-v2/test/PolymarketMonitor.ts
**Motivation**
PM notifier failed to match whitelisted initializers
**Summary**
Removes 0x prefix when parsing ancillary data searching for initializer address
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: no 0x prefix for initializer in ancillary data

- packages/monitor-v2/src/monitor-polymarket/common.ts
- Adds a getOrFallback function that returns an empty orderbook when PM’s CLOB ABI responds with a 404 error saying “No orderbook exists for the requested token id.”
- Covers cases where a market isn’t tradable or just doesn’t have a live orderbook.
> fix(pm-notifier): add fallback function for markets without orderbook activity

- packages/monitor-v2/src/monitor-polymarket/common.ts
- packages/monitor-v2/src/monitor-polymarket/index.ts
- packages/toolkit/src/http/httpClient.ts
- Add onRetry callback to httpClient
- Log PM notifier http retry errors
> feat(pm-notifier): log http retry errors

- packages/logger/src/logger/DiscordTicketTransport.ts
- packages/logger/src/logger/PersistentTransport.ts
**Motivation**
Avoid rate limits by allowing multiple bots to use shared log queue.
**Summary**
Adds option to use shared log queue among multiple bots.
**Details**
In order not to break current queue we have to keep legacy (per bot identifier) queue till it is fully processed. All new logs are added to the new shared queue list, but the old queue is processed first. We can remove this legacy queue handling logic when all bots have been migrated to use the shared queue.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: shared log queue in persistent queue transports

- packages/logger/src/logger/DiscordTicketTransport.ts
**Motivation**
Discord ticket delivery did not integrate well with gateway login mechanism in increased load across multiple instances.
**Summary**
Uses Discord REST for Discord Ticket delivery instead of login based gateway mechanism.
**Details**
Under increased load even with global rate limiting in place we saw gateway session exhaustion as different bot instances got to login when they get a chance to deliver a message. Using REST simplifies this as no session is required being more usable in a serverless environment.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(logger): use rest for discord ticket transport

- packages/common/src/EthersTransactionUtils.ts
- packages/common/src/index.ts
- packages/common/test/EthersTransactionUtils.js
**Motivation**
Protocol repo lacks common utilities for sending  transactions with Ethers.
**Summary**
Adds transaction runner helper for Ethers.
**Details**
Helper transaction runner functions estimate gas limit and submit transactions. In case of errors it attempts to extract and add revert data for the caller to handle. Note that the revert data would be available only on `JsonRpcProvider` based signers/contracts as other providers might structure the error payload differently, but the functionality in the happy path should still be the same.
**Testing**
**Issue(s)**
Fixes #XXXX
> feat(common): ethers transaction runner

- packages/monitor-v2/src/monitor-polymarket/common.ts
- packages/monitor-v2/test/PolymarketMonitor.ts
- mcp otb api doesn't require auth anymore
> feat(pm-notifier): mcp otb api doesn't require auth anymore
