UMAprotocol/protocol

README.md
This also includes information on how to load our existing mainnet and ropsten deployments.
This also includes info about our HackerOne bug bounty program.
=> Update README to include basic dApp info

README.md, migrations/8_deploy_tokenized_derivative_creator.js, migrations/MigrationUtils.js, truffle.js
To make the README consistent and the repo more usable for those without a google cloud account, we should make a deployment option for mainnet and ropsten that uses a mnemonic rather than keys stored in google cloud.
This also updates the network ID for mainnet and ropsten to match their real network IDs.
=> Add mnemonic option for mainnet and ropsten

sponsor-dapp/package.json, sponsor-dapp/src/components/ContractInteraction.js, sponsor-dapp/src/utils/FormattingUtils.js
When numbers with many decimals were shown under text boxes in `ContractDetails`, they would expand the text box and break the expected alignment.  This PR limits the number of decimals to 4. The alignment issue can still be triggered if the number is very large, but we don't expect that case to be as common.
=> Limit decimal length for under-box text

ci/deploy_staging_dapp.sh
This is mainly just so people can see a preview in staging even if they have no contracts or tokens.
=> Deploy the monitoring + staging dapp version in CI

v0/scripts/publishPrices.sh
It was previously hardcoding the `priceFeed` key which may not be necessary in mnemonic or test networks.
=> Fix publishPrices.sh to not automatically provide keys

v1/contracts/Voting.sol, v1/test/Voting.js
Parts of this implementation will have to change when prices can
actually be requested and when results can actually be computed.
I tried to keep any assumptions about how price requests would work out of this PR, to avoid any conflicts.
Issue #381
=> Add basic implementation to commit votes

v1/migrations/2_deploy_voting.js, v1/test/Voting.js
As discussed offline, we may want to rename the contract Voting.sol to
something like Oracle.sol, DecentralizedOracle.sol, v2Oracle.sol, etc.
Issue #381
=> Add Voting contract to migrations

v1/contracts/FixedPoint.sol, v1/contracts/test/FixedPointTest.sol, v1/test/FixedPoint.js
See comments for some cases that aren't handled.
Explicitly declaring a fixed point uint as the Unsigned type helps with
readability. It's also helpful to bury all this functionality in a
common place, where we can add more specialized methods or improve these
computations as needed.
Issue #351
=> Add basic API and placeholder implementation of fixed point library

v1/contracts/FixedPoint.sol, v1/contracts/test/FixedPointTest.sol, v1/test/FixedPoint.js
Supports operations between an `Unsigned` and a regular `uint`. Note
that the `uint` does not have a scaling factor built in, e.g., "5" would
first get mapped to "5e18" before being operated on.
Issue #351
=> Add mixed operations to fixed point library for uints

ci/run_slither.sh, v1/contracts/VotingToken.sol, v1/migrations/3_deploy_voting_token.js, v1/test/VotingToken.js
This token uses OpenZeppelin's ERC20Snapshot implementation for
snapshotting. It further allows a given address to mint new tokens (in
prod, this address will be the Oracle that mints new tokens as voter
rewards).
I had to remove another Slither detector that falsely triggers.
Issue #405
=> Add UMA token contract

v1/contracts/Registry.sol, v1/contracts/RegistryInterface.sol, v1/test/Registry.js
I went back and forth on whether to manage approved derivative creators via a MultiRole or keep what v0/Registry.sol did. Here's what it would look using MultiRole, let me know if you prefer another way.
It might be easiest to look at commit 1683dbb, which contains the actual changes from v0/contracts/Registry.sol.
Further improvements that we could make to the Registry in either this PR or in follow up PRs:
1. Remove PointerValidity enum
2. Add formatted documentation
3. Add to migrations
Issue #409
=> Copy over Registry contract and use MultiRole

v1/migrations/5_deploy_finder.js, v1/scripts/CheckDeploymentValidity.js, v1/test/Finder.js, v1/utils/Constants.js
The only implementation it can currently find is the Registry. We should add the store, etc.
Fixes #390 
Tested by running:
```
$ $(npm bin)/truffle migrate --reset --network=test
```
and then:
```
$ $(npm bin)/truffle exec scripts/CheckDeploymentValidity.js  --network=test
Using network 'test'.
Deployment looks good!
```
=> Add Finder contract to migration

sponsor-dapp/src/components/ContractInteraction.js
Effectively, the helper text is disabled.
This situation happens when a contract will expire on remargin (so the
price feed price is ignored), but an Oracle price is not yet available.
There could be other situations as well.
Issue #417
=> Don't estimate #tokens that can be created if no underlying price

README.md, sponsor-dapp/src/App.test.js, sponsor-dapp/src/parameters.js, v0/config/identifiersTest.json, v0/migrations/8_deploy_tokenized_derivative_creator.js
I tried to section the readme a little better, and I set up a motivating example so anyone should be able to walk through the steps to deploy their own instance of our system.
Notes:
- I added a line to the migration to automatically whitelist ETH on the test network.
- To make the ETH whitelisting work, I had to provide a mapping from 0x0 -> ETH in the private network config for the dapp.
- I changed the test identifier to be BTCETH since that's much easier to deploy than an SPY tracker.
=> Readme Updates

README.md
Not sure if this is a good plan or not:
The v1 section is incomplete but correct for the system as it is today.
As we fully build out the system, we'll continue to expand that section,
copying from the v0 section as needed.
Alternatively, we could also just delete the leftover instructions about v0, leaving only the pointer to the v0 branch.
Issue #424
=> Separate README into v1 and v0 sections

core/contracts/Testable.sol, core/contracts/test/TestableTest.sol, core/test/Testable.js
Following @ptare 's suggestion, `Testable` is now a standalone contract without any ownership restrictions.
=> Convert Testable into a pure contract

core/contracts/OracleInterface.sol, core/contracts/Voting.sol, core/contracts/test/MockOracle.sol
This is so that tests for other contracts that interact with the Oracle
don't have to deal with the phasing, voting, etc.
Also needed to add another method `hasPrice` to `OracleInterface`.
Issue #453 
=> Add MockOracle that implements OracleInterface

.solhint.json, core/contracts/AddressWhitelist.sol, core/contracts/Registry.sol, core/contracts/Store.sol, core/test/AddressWhitelist.js, core/test/Registry.js
Can add back a lint check.
Fixes issue #389.
=> Change all event names to be different from function names

core/test/Store.js
Added some more store tests -- the only thing left to add is some governance testing, which might be a broader issue to address.
=> New store tests for setting final fees, and paying fees in both Eth and ERC20 (fixes #459)

.circleci/config.yml, .gitignore, ci/docgen.sh, package.json
A few notes:
- I forked the solidity-docgen package because v2 was missing the ability to import external dependencies (like openzeppelin). Once this feature is added in v2, we should move off of our fork.
- For whatever reason, reading this package directly from a repo (this happens on the unforked repo as well) causes a strange preinstall failure in some environments (the npm error messages are extremely unclear - my theory is that something is causing babel to fail). Specifically, this seems to fail in the coverage environment (ganache-cli docker image). The fix for this is to make the dependency optional so a failure doesn't cause the install the fail. This issue should be fixed once we stop using our fork.
- The markdown representation is built to be consumed by a static site …
=> Generate markdown representation of Solidity docs

core/test/Voting.js, core/test/scripts/Voting.js, core/utils/Crypto.js, core/utils/Random.js, core/utils/Voting.js, package.json
Our Voting script test seems to be flaking on master. This was due to assumptions about the starting vote phase that didn't hold. I'm not exactly sure why the test's assumption about phasing didn't hold. That deserves to be investigated, but this fix should make the test robust to arbitrary phasing start states.
This fix makes that test robust to starting in any vote phase. It also does a few other things:
- Pulls out the phase/round increment utility functions used in the Voting.sol test for use in other tests.
- Adds the core/utils/ directory so it is covered by prettier (and reformats those files).
=> Fix flaky test

core/contracts/Voting.sol
Moves all price request metadata, including vote tallying and price resolution, into the `PriceRequest` struct. The `PriceRequest` struct is indexed via `keccak256(abi.encode(identifier, time))`. The goal is to reduce the number of structs, and (hopefully) make the code more intuitive. 
Feedback welcome.
Edit:
~~- [ ] Add tests~~
=> Move all PriceRequest metadata into the PriceRequest struct

core/contracts/Voting.sol
This PR removes `resolvedPrice` to reduce gas costs since it's not too expensive to recompute the modal outcome each time it's requested (which should usually be once).
=> Remove resolvedPrice

common/globalTruffleConfig.js
This adds the kovan testnet to the truffle config. Because the truffle config was repetitive and confusing, I wanted to simplify the construction of the `networks` portion of the config so that it was clear what options were unique and what options were unchanged between networks.
=> Add Kovan Testnet to Truffle config

core/contracts/ResultComputation.sol, core/contracts/Voting.sol, core/contracts/test/ResultComputationTest.sol, core/test/ResultComputation.js
The basic premise of this PR is that if we store the hash of the reveal rather than the exact price that was revealed, we don't need to store a boolean to denote whether the voter revealed. This is because there is no known price that will generate a `0x0` hash, so the default will never be misinterpreted as a valid vote for some price - it will always fail the comparison.
A few notes:
- This approach as written will only work for voting systems where there is only one "correct" vote per vote instance since the result hash must be directly compared to the voter's hash. This will likely not work for a median-style system where ranges of values are considered acceptable.
- This also includes a small optimization so that we delete the old `ResultComputation` struct when a vote is rolled …
=> Store the revealHash rather than the reveal price

core/contracts/Voting.sol, core/scripts/local/VoteGasEstimation.js
I preemptively blamed Ganache for `estimateGas` returning the wrong value. The actual problem was that `estimateGas` intentionally includes the gas refund. To get the actual gas used, there's a `gasUsed` field in the receipt.
I updated [this doc](https://docs.google.com/document/d/1NjI3bXG2HjunVfu9KzXNrsliOWpN1SeICREoe8Lx2DA/edit?usp=sharing), but the gas usage dropped from 6.4M -> 3.5M.
=> Fix gas estimation script to exclude gas refund

core/contracts/ExpandedIERC20.sol, core/contracts/TokenizedDerivative.sol, core/contracts/VotingToken.sol
This makes `VoteToken` and `TokenizedDerivative` conform to the same expanded (+mint and burn) ERC20 interface.
=> Unify Expanded ERC20 method signatures

common/gckms/ManagedSecretProvider.js, core/contracts/EncryptedSender.sol, core/scripts/Voting.js, core/test/EncryptedSender.js, core/test/scripts/Voting.js, core/utils/Crypto.js
This PR uses the `EncryptedSender` contract to add blockchain persistence to the voting script. 
There are a few assumptions baked into this implementation:
- Everyone who wants to persist votes must have access to the account that owns the voting tokens.
- Persistence always happens *after* the commit transaction is confirmed. 
These assumptions are not expected to be permanent, so there are a few scattered TODOs to make these assumptions more flexible (other accounts persisting votes that are expected to be committed by the script, for instance), but we probably want to discuss a particular direction before moving in any particular direction.
Note: this implementation also assumes that the private keys being used are always accessible via a `wallets` object on the provider. This is true …
=> Add blockchain persistence to the Voting script

Dockerfile, core/scripts/Voting.js, core/test/scripts/Voting.js, package.json
Two follow up changes:
1. Environment variables are obviously not the best way to set API keys. Figuring out a better way is tracked in #490 
2. Does the script reveal votes over and over? If so, we might need to update EncryptedSender somehow to remember that the vote was revealed? (Not sure about this yet)
Issue #491
=> Send one email at the end of committing or revealing

core/contracts/Voting.sol, core/scripts/Voting.js, core/test/Voting.js, core/test/scripts/Voting.js
To try to minimize the code duplication, made the checks quite minimal. If this function is called for an (identifier, time) that's not currently being voted on in the reveal phase, the returned value is pretty much useless.
=> Add view function to check whether a voter has revealed a vote

common/MigrationUtils.js, core/migrations/10_deploy_tokenized_derivative_utils.js, core/migrations/11_deploy_tokenized_derivative_creator.js, core/migrations/13_deploy_encrypted_sender.js, core/migrations/1_initial_migration.js, core/migrations/2_deploy_finder.js, core/migrations/3_deploy_voting_token.js, core/migrations/4_deploy_voting.js, core/migrations/5_deploy_registry.js, core/migrations/6_deploy_price_feed.js, core/migrations/7_deploy_financial_contracts_admin.js, core/migrations/8_deploy_store.js, core/migrations/9_deploy_return_calculator.js
This PR adds command line options to allow certain portions of the system to be preserved in a call to `truffle migrate --reset`. The migration has been broken down into three components:
- The `Finder` contract.
- The `VoteToken` contract.
- Everything else. We may wish to break this down further at a later point, but until we have a use case in mind, it seemed easiest to keep the rest of the contracts bunched together.
I'm looking for feedback on these choices - I'm not sure they make sense from a usability perspective, so lmk what you think.
Issue #513.
=> Allow parts of previous migrations to be preserved

core/migrations/3_deploy_voting_token.js
This adds `TokenMigrator` to the migration process via a new command line parameter. If a new `VotingToken` replaces an old `VotingToken` and the `--token_conversion_rate` parameter is set equal to a valid value, a `TokenMigrator` will be deployed to mint new tokens for old token holders.
=> Add TokenMigrator to migrations process

common/MigrationUtils.js, common/globalTruffleConfig.js, core/migrations/7_deploy_financial_contracts_admin.js
There were a few mistakenly hardcoded URLs and outdated network checks in our truffle config and migration utility file. Once these were fixed, I was able to successfully run a full migration against Kovan.
=> Fix bugs in prod/testnet migrations

core/contracts/FixedPoint.sol, core/contracts/TokenMigrator.sol, core/contracts/TokenizedDerivative.sol, core/contracts/Voting.sol, core/contracts/test/FixedPointTest.sol, core/contracts/test/ResultComputationTest.sol, core/migrations/4_deploy_voting.js, core/migrations/8_deploy_store.js, core/scripts/local/VoteGasEstimation.js, core/test/Store.js, core/test/TokenMigrator.js, core/test/TokenizedDerivative.js, core/test/Voting.js
This changes the name of the internal variable `value` in the `FixedPoint.Unsigned` struct to `rawValue`.
Reasoning: the transaction options object that is optionally passed as the last argument in a truffle transaction call has a field called `value` to denote the amount of ether sent. If we were to pass a `FixedPoint.Unsigned` value as the last argument in a transaction call, it would look very similar to truffle and to a reader. I think it makes sense to change it to preempt any problems that may arise due to this conflict.
=> Change value to rawValue

core/contracts/Voting.sol, core/test/Voting.js
Add events for the sequence a price request goes through.
Compared to earlier versions of this PR, I removed events for `RevealPhaseStarted` and `CommitPhaseStarted`. They may not be as useful because the phases start/stop based on time, not when the first commit or reveal happens.
=> Add proposal for events

common/gckms/ManagedSecretProvider.js, core/contracts/EncryptedSender.sol, core/scripts/Voting.js, core/test/EncryptedSender.js, core/test/scripts/Voting.js, core/utils/Crypto.js
This PR changes the encryption scheme for on-chain (salt, price) persistence in `EncryptedSender` due to limitations in metamask - instead of encrypting and decrypting (salt, price) messages with the user's ethereum address key pair, this moves to deriving a "one-time key pair" from a signature. This signature is generated by the user's ethereum account. Since all wallets that are integrated with web3 can generate signatures, this allows the dApp and the automated voting system to get access to the keypair without receiving the user's keys in plaintext (which is prohibited in metamask for obvious reasons).
It's currently implemented such that a unique message is signed for each round of voting, so the generated key-pair is only used for a single round.
=> Derive Key Pair from signature

.circleci/config.yml, voter-dapp/package.json, voter-dapp/src/ActiveRequests.js, voter-dapp/src/App.js, voter-dapp/src/App.test.js, voter-dapp/src/drizzleOptions.js, voter-dapp/src/index.js
This PR integrates the voter-dapp with Drizzle. We still have to use our
fork of Drizzle because the version of web3 Drizzle uses doesn't support
structs as return values (e.g., from `getPendingRequests`).
Follow up PRs will add other required columns, i.e., what vote the user has committed.
Issue #532
=> Add table showing active (i.e., pending) requests

core/contracts/AddressWhitelist.sol, core/contracts/AdministrateeInterface.sol, core/contracts/ExpandedIERC20.sol, core/contracts/LeveragedReturnCalculator.sol, core/contracts/ManualPriceFeed.sol, core/contracts/MultiRole.sol, core/contracts/PriceFeedInterface.sol, core/contracts/RegistryInterface.sol, core/contracts/ReturnCalculatorInterface.sol, core/contracts/Testable.sol, core/contracts/Withdrawable.sol
The only contract left should be the `TokenizedDerivative`. I think that one is worthy of its own PR.
=> Add natspec docs for most contracts

core/config/identifiers.json
We should use these crypto identifiers with expiries at the end of the year for any future dApp deployments since the futures we were using are expired.
=> Use crypto identifiers for contract creation

core/scripts/local/RequestOraclePrice.js, core/truffle-config.js, core/utils/Serving.js, package.json
This will allow the RequestOraclePrice script to be triggered by an http request on a port. The end goal is to allow [Cloud Scheduler](https://cloud.google.com/scheduler/) to send a request over [PubSub](https://cloud.google.com/pubsub/) to trigger RequestOraclePrice running in [Cloud Run](https://cloud.google.com/run/).
Also updated prettier command to cover all of `core/` because it wasn't covering `js` in `core/scripts/local/`.
=> Add request trigger option to RequestOraclePrice

core/contracts/Voting.sol, core/test/Voting.js
For example, if a price request fails to resolve, then it automatically
becomes pending in the next round. Then, suppose the next commit phase
goes by with no activity. The voter dapp will then try to pull
the `hasRevealed` status, which should show `Cannot be revealed`. The
voter dapp relies on the `hasRevealed` call to return `false`.
Issue #532.
=> Change `hasRevealed` to only apply to the current round

core/scripts/local/RequestOraclePrice.js, core/utils/Serving.js
There are a few distinct changes made in this PR:
- A time input of 0 instructs the script to use the *time of request*. This allows the same server to make multiple, distinct requests. This is needed to get the cron job to continually make new requests rather than re-requesting the same price.
- The server responds to HTTP POSTs. This is needed because GCP PubSub pushes with posts rather than gets.
- The callback is never called in the server case to allow the server to run indefinitely rather than shutting down immediately after the first request.
=> Minor PriceRequest script refinements

core/contracts/Voting.sol, core/migrations/13_deploy_encrypted_sender.js, core/networks/42.json, core/scripts/Voting.js, core/test/EncryptedSender.js, core/test/scripts/Voting.js
- Removes references to `EncryptedSender` as a standalone contract
- Voting script now uses `batchCommit` and `batchReveal`
=> Support batch commit/reveal in the Voting script

core/scripts/Voting.js
Note: I'm not exactly sure if testing the email body makes sense. These sorts of tests often end up being "change detectors" (they basically just hardcode the expected output and fail whenever anything changes). Please let me know if you have an idea for a good way to test this.
I worked with @rcai1 to come up with an email template that made sense. Here's a sample (note the link doesn't match up with the txn hash - I was running on ganache, so I fudged that part :)):
**The AVS has revealed 3 price requests on-chain.**
__Price request 1__:
Price feed: BTCUSD
Request time: Thu, 18 Jul 2019 13:36:51 GMT (Unix timestamp: 1563457011)
Value revealed: 9770.62
*Salt: 91688650169801159701281221741261196733890428798947866347522299367376684217265
**Transaction: …
=> Add commit/reveal details in email

voter-dapp/src/ResolvedRequests.js
This modifies the resolved requests table in two ways:
- Fixes the event queries so they pick up past resolved requests (we forgot to add the `fromBlock` key).
- Adds a "Show all" button at the bottom to optionally toggle showing all past requests instead of just the ones from the last round id. We may want to limit this to some arbitrary number of rounds (like 100) in the future, but for now, it seems to be relatively snappy with 30 or 40.
=> Fix resolved requests table

voter-dapp/src/Header.js
This attempts to make the header conform to the visual spec in figma a bit closer:
- Right aligns the rightmost informational text.
- Converts the token numbers to their decimal form and limits their precision to 2 decimal places.
- Limits the precision of the percentage to 4 decimal places.
- Makes the time formatting conform to the figma spec (more closely, at least :) ).
=> Tweak formatting and visual spacing in header component

sponsor-dapp-v2/jsconfig.json
This setting allows imports such as `import routes from "lib/routes";`
rather than `import routes from "../../lib/routes";`. The code in
sponsor-dapp-v2 relies on imports relative to `src`.
=> Set `baseUrl` from jsconfig.json file

sponsor-dapp-v2/package.json, sponsor-dapp-v2/src/components/application/index.js, sponsor-dapp-v2/src/contracts, sponsor-dapp-v2/src/drizzleOptions.js, sponsor-dapp-v2/src/index.js, sponsor-dapp-v2/src/store/store.js
In this implementation, we allow Drizzle to create a shared Redux store that all the other actions plug in to.
Issue #589
=> Setup Drizzle

sponsor-dapp-v2/package.json, sponsor-dapp-v2/src/components/Position.js, sponsor-dapp-v2/src/lib/custom-hooks.js, sponsor-dapp-v2/src/views/Landing.js, sponsor-dapp-v2/src/views/Start.js, sponsor-dapp-v2/src/views/ViewPositions.js
A few notes:
- This moves us to using a forked version of drizzle react that includes a promise-based `useCacheCall` and `useDrizzleState`.
- I kept the render functions (as we did in a previous PR) to make the diff easier to read. Will remove these in a future PR.
- I left the `liquidationPrice` hardcoded - we agreed that we would write that logic in a future PR as it's needed in a few places.
- I added real links to the ETH faucets for ropsten and kovan, but we still need to determine where to link for the DAI faucets.
- For mainnet and ganache, since there are no faucets, I added logic to omit the faucet buttons from the render.
- I'm not sure what labels and units we wanted to use for the table on the View Positions page, so I used the token names and the quantities of tokens since …
=> Add data to View Positions page

sponsor-dapp-v2/src/lib/routes.js, sponsor-dapp-v2/src/views/ManagePositions.js, sponsor-dapp-v2/src/views/Withdraw.js
Far from the ideal implementation. Because the original Withdraw component wasn't parameterized based on any incoming data, I pretty much had to scrap and rewrite it.
Some of this code could definitely be broken up/reused, but I want to write the Deposit component first, to get a better handle on the shared vs. unique logic.
Fix some percentage related bugs in ManagePositions.
Also fix a bug in ManagePositions where token value was calculated based
on the total supply, not the user's balance.
Issue #604.
=> Rewrite withdraw view with real data

sponsor-dapp-v2/src/drizzleOptions.js
A previous PR broke parts of the dApp that were depending on the Registry contract to query existing TokenizedDerivatives.
=> Re-add registry to store

sponsor-dapp-v2/src/components/Step1.js, sponsor-dapp-v2/src/components/Step2.js, sponsor-dapp-v2/src/components/common/Dropdown.js, sponsor-dapp-v2/src/drizzleOptions.js, sponsor-dapp-v2/src/views/Steps.js
This implements steps 1-2. A few notes:
- I used a pattern of passing down refs to subcomponents to modify parent state without explicitly triggering a re-render. This also worked well to persist child state in cases where the child is torn down and brought back up.
- I removed the redux state modifications and just hardcoded what remained of the required JSON data to simplify the component a bit.
- I tried to avoid moving any of the child components to a hook implementation to avoid unnecessary code churn.
- I had to modify their Dropdown component so that it would both communicate the user's choice back up the stack and so it could take a starting selection.
Issue #616
=> Implement Steps 1-2

sponsor-dapp-v2/src/lib/custom-hooks.js
Note that this regex isn't perfect. It'll allow some corner cases like "2." and disallow some cases like ".2" (but "0.2" will work).
=> Update text input regex to allow decimals

sponsor-dapp-v2/src/components/common/IconSvgComponent.js
The icons are stored as files in `public/svg`, and we need to explicitly
prefix paths relative to `public` with `process.env.PUBLIC_URL`.
Fixes #628.
=> Fix icons not loading by properly loading assets from public folder

sponsor-dapp-v2/src/components/Step1.js, sponsor-dapp-v2/src/components/Step2.js, sponsor-dapp-v2/src/components/Step3.js, sponsor-dapp-v2/src/lib/custom-hooks.js, sponsor-dapp-v2/src/views/Steps.js
This PR adds the visuals/persistence to step 3 without adding the contract creation. It also restructures Steps 1-3 so that the drizzle calls are done at the lower level components and the higher level component is only for multi-stage persistence and handling transitions between steps.
As a part of this change, I moved the hooks that were previously in `Steps.js` to the `custom-hooks.js` file.
=> Restructure Steps 1-3

common/MigrationUtils.js, common/PublicNetworks.js, common/gckms/GckmsConfig.js, common/globalTruffleConfig.js, core/migrations/11_deploy_tokenized_derivative_creator.js, core/migrations/13_deploy_testnet_token.js, core/scripts/Voting.js, scripts/deploy_dapp.sh, sponsor-dapp-v2/src/lib/custom-hooks.js
The goal of this PR is to make it as easy as possible to add a new public network.
This is accomplished by making everything in the repo pull the list of public networks and any unique properties about each network from a single, central config.
To add a new network in the future, one should just have to edit a single config file.
This PR also adds the rinkeby testnet.
=> Add rinkeby and create a general public networks config

core/migrations/13_deploy_testnet_token.js, core/migrations/14_support_identifiers.js
This adds a new step to migrations where all the identifiers are approved.
It also adds whitelisting to the deployment step of the TestnetERC20 contract.
Fixes #647.
=> Whitelist margin currencies and approve identifiers during migrations

core/config/identifiers.json, core/scripts/PublishPrices.js
Several changes:
1. Change spacing to separate each feed into its own stanza
2. Print an overall "SUCCESS" or "FAILURE" message
3. Use `serverTimestamp` rather than `tradeTimestamp`
4. Use `getCrypto` API call for crypto quotes from Barchart
More context on #3:
The field `tradeTimestamp` returns values with an incorrect timezone
offset (at least during Daylight Savings Time).
Issue #656 
=> Update price feed pushing to match desired API calls

core/scripts/publishPrices.sh
This polling interval should keep us below our market data query limits.
Issue #656 
=> Reduce polling interval on `publishPrices.sh` to 10 minutes

sponsor-dapp-v2/src/components/Step1.js, sponsor-dapp-v2/src/components/Step3.js
The function `fromWei` can't accept `BN` instances in optimized mode.
=> Use `formatWei` rather than `fromWei` to fix issue in optimized mode

sponsor-dapp-v2/src/lib/custom-hooks.js
The other fields returned by this function are strings too.
=> Return `collateralizationRequirement` as a string

sponsor-dapp-v2/src/components/Step1.js, sponsor-dapp-v2/src/components/Step2.js, sponsor-dapp-v2/src/components/Step3.js, sponsor-dapp-v2/src/components/Step4.js, sponsor-dapp-v2/src/components/Step5.js, sponsor-dapp-v2/src/components/Step6.js, sponsor-dapp-v2/src/views/Steps.js
In some cases, if the `div` element returned by `components/StepN.js`
changes entirely, then the the outer `CSSTransition` doesn't work and
results in the CSS class overrides `step-N-enter-done` never getting
applied to the div that has the CSS class `step`. This results in all of
the content having opacity 0 and being invisible.
One way to address this issue is to make sure that the direct child of
`CSSTransition` is always the same wrapper div.
Fixes #638 
=> Lift wrapper div outside of Step components to fix transitions

core/config/identifiers.json
Before adding this identifier back, we should scale its value
appropriately.
=> Temporarily remove CMC index from identifiers

sponsor-dapp-v2/src/views/ManagePositions.js
This field does *not* represent excess short margin balance, it's just
the short margin balance.
Fixes #672 
=> Fix "Excess Collateral" field to be short margin balance

core/config/identifiers.json
It's scaled down by ~1B so the value should be ~250 rather than 250B.
=> Add scaled CMC Total Market Cap Index

sponsor-dapp-v2/sample_gae_app.yaml
This adds a sample app.yaml to the repository that seems to fix #646 (as far as I can tell). It basically matches everything *without* a `.` and sends it to `index.html`. Otherwise, it attempts to find the file in the build directory. I assume this rule should generally hold for our application and other react applications since when referencing specific files, they generally have an extension, but normal user-facing url paths don't have an extension.
I've done a test deployment of this and it seems to work. Images are loading and when fresh loading a url like `/ManagePositions/0x0f680cF767D63F6468b28D299Efce4429C45fb89`, the dApp works as one would expect.
I've replaced the config in our CI deployment with this one as well. Please let me know if you see any flaws with this approach. …
=> Add sample app.yaml with routing fix

sponsor-dapp-v2/sample_gae_app.yaml
This tells the browser to always redirect to the https version of the site.
=> Add https redirect to GAE config

core/config/identifiers.json, core/scripts/local/ApproveIdentifiers.js
This PR will remove some existing identifiers, which will pull them from the dapp. However, those who have already built on these identifiers will see their contracts never expire. I don't think this is that big of a deal at this stage since it's only for a select few identifiers.
Note: this also adds a script to approve any identifiers that are listed in the config but unapproved.
=> Remove strange Custom Indices

.circleci/config.yml, sponsor-dapp-v2/src/components/common/ExpandBox.js, sponsor-dapp-v2/src/views/ManagePositions.js
This PR just prevents the dapp from crashing in the event of expiry. There are many fields that will be filled with `--` in that case, but I think that's appropriate as a first step.
Note: this PR required an update to the our forked version of drizzle-react, so I changed the name of a dependency cache in our ci configuration to wipe it clean.
Fixes #681.
=> Prevent dApp from crashing after expiry

sponsor-dapp-v2/src/components/Step2.js
This just uses the local timestamp of the machine to filter out any old expiries.
Fixes #695.
=> Filter out past expiries

.circleci/config.yml, core/scripts/PublishPrices.js, core/test/scripts/PublishPrices.js
This just adds a new test case that does a run through the runExport() function and verifies that it returns no errors.
This is useful since we seem to be changing the identifiers often - we should have an automated test to verify those changes work.
Note: I have added a new context to CI that has all of our API keys. The test ensures all are present before running, so those without permission to access those keys will get a free pass on this test. Going to look into adding an *approval* step for access to the api_key context in circleci so that those who aren't part of our organization will see this test run as well.
Fixes #694
=> Add test to verify the price feed script

core/scripts/Voting.js, core/test/scripts/Voting.js
If something failed while constructing the object VotingSystem or
sending a notification, then we won't be able to alert for that.
This PR should handle the case where the call to `batchCommit` or `batchReveal` fails.
=> Send notification in case AVS crashes (in most cases)

sponsor-dapp-v2/src/views/ManagePositions.js
This is part 1/2 for allowing token holders to redeem their tokens.
This enables/disables buttons based on the state of the contract and who's using the dApp.
Note: part 2/2 will be allowing token holders to access this page from the ViewPositions page if they own tokens.
Related to #688.
=> Disable buttons based on state and user on ManagePositions

README.md
(the old link expired; the new link does not expire).
=> updating broken slack invite link

sponsor-dapp-v2/src/components/Step5.js, sponsor-dapp-v2/src/lib/custom-hooks.js, sponsor-dapp-v2/src/views/Borrow.js, sponsor-dapp-v2/src/views/ManagePositions.js, sponsor-dapp-v2/src/views/Repay.js, sponsor-dapp-v2/src/views/ViewPositions.js
The strange liquidation price was due to a bug in how public networks + web3 deal with reverting view methods. See https://forum.openzeppelin.com/t/require-in-view-pure-functions-dont-revert-on-public-networks/1211 for more on this issue. This PR adds a workaround to allow the dApp to continue to work correctly.
Fixes #717
=> Workaround for non reverting view methods bug

.circleci/config.yml, .gitignore, README.md, antora.yml, ci/deploy_to_staging.sh, ci/docgen.sh, core/contracts/EncryptedSender.sol, core/contracts/TokenMigrator.sol, documentation/contract.hbs, documentation/gae_app.yaml, documentation/intro.md, documentation/prelude.hbs, documentation/tutorials/sample_tutorial.md, package.json, playbook.yml, scripts/build_docs_site.sh, scripts/deploy_docs.sh, scripts/gen-nav.js
This PR adds a full autogenerated documentation static site modeled after docs.openzeppelin.com. It depends on two forks of open zeppelin work:
- https://github.com/UMAprotocol/docs_ui, which is a new repo because open zeppelin did not isolate their UI components from the rest of their documentation website. Loosely based on https://github.com/OpenZeppelin/docs.openzeppelin.com. However, I made quite a few changes to make the UI more UMA-y :).
- https://github.com/UMAprotocol/solidity-docgen/tree/fork, which is a fork of open zeppelin's repo by the same name. We've been forking this repository for a while, but I made more significant changes to make this work better for our needs. Two changes of note: I fixed a bug where array types don't display correctly (opened an issue about this on …
=> Add Docs Site

core/contracts/TokenizedDerivative.sol, core/contracts/TokenizedDerivativeCreator.sol, core/migrations/6_deploy_price_feed.js, core/scripts/ManualPublishPriceFeed.js, core/scripts/local/InitializeSystem.js, core/test/TokenizedDerivative.js, core/test/scripts/EmergencyShutdown.js, core/utils/Constants.js, sponsor-dapp-v2/src/components/Step3.js, sponsor-dapp-v2/src/views/ManagePositions.js
Sponsors can now use their own price feed contract when creating a new
TokenizedDerivative. The sponsor dApp doesn't support this feature, but
the sponsor can use the CLI.
=> Remove price feed from finder

documentation/explainers/price-feed-configuration.md, documentation/tutorials/creating-tokens-locally.md, documentation/tutorials/prerequisites.md
All we need to do to get syntax highlighting and code block backgrounds is to add a language for the block in github. This causes asciidoc to label it a code block and not a literal block, which has different styling. We should start doing this going forward. Added benefit is that we get syntax highlighting for free :)
=> Add syntax highlighting for code blocks

core/migrations/11_deploy_tokenized_derivative_creator.js, core/networks/4.json
This PR modifies our deployment and deployed addresses in a few ways:
- Redeploys the updated TokenizedDerivativeCreator.
- Adds a new LeveragedReturnCalculator that has leverage of 2. The default will still be one, but the other is included in the networks file just to help us keep track of the address.
- Removes the `if` in migrations around adding ETH as a margin currency so it's enabled for all networks.
=> Redeploy TokenizedDerivativeCreator

core/config/identifiersTest.json
`identifiersTest.json` was outdated, changed key `expiry` -> `expiries`
=> Fixed identifiersTest.json

.circleci/config.yml, core/scripts/Voting.js, core/test/scripts/Voting.js
Note: while changing the config and modifying the broken test, I noticed a bug in how we query intrinio. The `moment` library outputs it's format in local time unless you force it to produce utc. So, the query was sending different times based on where the local machine was (circleci was failing because their machines are in a different time zone). I double checked that intrinio expects these times in UTC.
=> Remove outdated config options in Voting.js

core/contracts/DesignatedVoting.sol, core/contracts/Voting.sol, core/contracts/VotingInterface.sol, core/test/DesignatedVoting.js, core/test/Voting.js
Price requests are no longer tracked per round. Instead, all pending
price requests are maintained separately. Round finalization is no
longer O(# price requests) but O(1). Each price request is marked as
resolved separately.
Retrieving rewards is now more complicated, because the state of which
price requests a voter participated is maintained off-chain.
The motivation behind this change is to get rid of any O(# price
requests) operations, which could run out of gas if there are too many
price requests.
=> Reorganize the way price requests are tracked

core/contracts/AddressWhitelist.sol, core/contracts/Finder.sol, core/contracts/Store.sol, core/contracts/Voting.sol
This change is to comply with the Solidity style guide:
https://solidity.readthedocs.io/en/v0.5.12/style-guide.html
Resolves bug #744.
=> Move events declarations after state variables

ci/run_slither.sh
Just to get CI back up and running, disabling the low severity events-reentrancy check that causes events to be emitted out of order in the case of a reentrancy.
=> Remove re-entrancy events check

package.json
This package snuck in in https://github.com/UMAprotocol/protocol/pull/723, but we aren't using it.
=> Remove unnecessary package

core/contracts/DesignatedVoting.sol, core/contracts/Voting.sol, core/contracts/VotingInterface.sol, core/test/Voting.js
Build ability to set Voting.sol as migrated
Setting Voting as migrated prevents financial contracts from querying it: they must query the new Voting system instead. The new Voting system can call `getPrice` and `hasPrice` on the old Voting, allowing it to serve queries about previously resolved price requests.
Pending votes are effectively cancelled, in that financial contracts can never access their results and rewards won't be issued.
NOTE: we are trying to make the minimum set of changes to enable the migration, since we don't know anything about what the next Voting.sol will look like.
Issue #774
=> Build ability to set Voting.sol as migrated

core/contracts/Governor.sol, core/test/Governor.js
This PR adds multi-transaction proposals as discussed offline.
Some notes:
- Multi-transaction proposals must be executed in order. If one transaction fails, no transaction after that one can run.
- There's a fair amount of manual array manipulation in the PR due to limitations on converting memory arrays to storage arrays.
=> Add multi-transaction proposals

common/Enums.js, core/contracts/FinancialContractsAdmin.sol, core/contracts/Finder.sol, core/contracts/Registry.sol, core/contracts/Store.sol, core/migrations/15_deploy_governor.js, core/migrations/7_deploy_financial_contracts_admin.js, core/test/FinancialContractsAdmin.js, core/test/Finder.js, core/test/Registry.js, core/test/Store.js, core/test/TokenizedDerivative.js
Part of #781.
This PR updates the permissions for the Finder, Registry, Admin, and Store as described in https://github.com/UMAprotocol/protocol/issues/781#issuecomment-563495306.
It also fixes a small issue in the store where the `0` role was implicitly being used for the Withdrawer role.
=> Update permissioning for Finder, Registry, Admin, and Store

core/contracts/DesignatedVoting.sol, core/contracts/DesignatedVotingFactory.sol, core/migrations/16_deploy_designated_voting_factory.js, core/test/DesignatedVoting.js, core/test/DesignatedVotingFactory.js
Add a factory to create `DesignatedVoting` instances. That factory maintains a mapping of the instances it has deployed, to allow off-chain infrastructure to be able to find DesignatedVoting contracts based on the hot wallet address.
An additional benefit of that approach is that no transactions need to be issued from the cold wallet as part of setup.
Note several limitations of this approach:
1. No way to look up by cold wallet address
2. Won't work with DesignatedVoting instances deployed without the factory
3. Won't work if you change the voter address in DesignatedVoting.
IMO these limitations don't justify adding unnecessary functionality, but curious about your thoughts.
Issue #778 
=> Add a factory to create DesignatedVoting instances

core/contracts/DesignatedVoting.sol, core/scripts/DeployDesignatedVoting.js, core/test/DesignatedVoting.js, voter-dapp/src/ActiveRequests.js, voter-dapp/src/Dashboard.js, voter-dapp/src/Header.js, voter-dapp/src/drizzleOptions.js
In this first-pass implementation, if the account selected in Metamask
has a DesignatedVoting contract deployed, the voter dapp will prefer to
use that contract instead.
Follow-up PRs can improve the UX (significantly) and build a flow
to deploy the contract from the dapp.
=> Support voting through DesignatedVoting from voter dapp

core/contracts/Voting.sol, core/test/Voting.js, voter-dapp/src/ActiveRequests.js, voter-dapp/src/Dashboard.js, voter-dapp/src/Header.js, voter-dapp/src/ResolvedRequests.js
This PR also removes the method `Voting::hasRevealed`, is there a reason
to keep it around? If so, we'd have to either 1) add it to
`DesignatedVoting.sol`, or 2) have it take in a voter address rather
than relying on `msg.sender`.
Issue #787 
=> Support DesignatedVoting when filtering events

package.json
Continuous integration is broken because of a breakage in test isolation in a recent truffle release. Since it's a bug on their end, I think we should just downgrade until it's fixed.
See https://github.com/trufflesuite/truffle/issues/2710 for more details.
=> Downgrade truffle temporarily to fix ci

sponsor-dapp-v2/src/components/Step2.js, sponsor-dapp-v2/src/components/common/ExpandBox.js
Timestamp was displaying months instead of minutes on the ManagePosition page.
I corrected this by using LTS (locale timestamp) as we do in Step 2. I went ahead and unified the two date displays in the process since there's no reason for them to use different formats.
=> Correct timestamp display

core/contracts/Voting.sol, core/test/Voting.js
The point of this PR is to make it easier for offchain applications to match up RewardsRetrieved events with VoteRevealed and PriceResolved events.
This PR changes the RewardsRetrieved event in the following ways:
- If a voter passes 10 votes to retrieveRewards (and the transaction succeeds), they should see 10 RewardsRetrieved events emitted.
- 2 new fields have been added: identifier and time.
Note: voters can retrieve rewards for the same vote multiple times and, therefore emit multiple RewardsRetrieved events, but tokens will be awarded and documented in the event on the first call only.
Any changes unrelated to the RewardsRetrieved event are workarounds for solidity "stack too deep" errors.
=> Make RewardsRetrieved event more consistent

.circleci/config.yml, documentation/tutorials/prerequisites.md, sponsor-dapp-v2/package.json, voter-dapp/package.json
UMAProtocol's fork of Drizzle needed to have its web3 version updated as well, otherwise certain packages (e.g., scrypt) fail to build with node12.
Issue #795 
=> Update to Node v12

voter-dapp/src/ActiveRequests.js
Use the same utility function to generate random salt in the dApp that the Truffle unit tests use. In optimized mode, BN's aren't always recognized as BN's due to a known issue, so we have to call .toString().
Truffle test:
https://github.com/UMAprotocol/protocol/blob/f3a2ce6a0f9036c58dcc9f91d062556862df30c8/core/test/Voting.js#L1023
=> Make salt generation in dApp more consistent with unit tests

core/contracts/Governor.sol, core/contracts/IdentifierWhitelist.sol, core/contracts/IdentifierWhitelistInterface.sol, core/contracts/OracleInterface.sol, core/contracts/TokenizedDerivative.sol, core/contracts/Voting.sol, core/contracts/test/MockOracle.sol, core/migrations/10_support_identifiers.js, core/migrations/4_deploy_voting.js, core/networks/4.json, core/networks/42.json, core/scripts/TransferPermissions.js, core/scripts/local/ApproveIdentifiers.js, core/scripts/local/InitializeSystem.js, core/scripts/local/RequestOraclePrice.js, core/scripts/local/VoteGasEstimation.js, core/test/DesignatedVoting.js, core/test/Governor.js, core/test/IdentifierWhitelist.js, core/test/TokenizedDerivative.js, core/test/Voting.js, core/test/scripts/EmergencyShutdown.js, core/test/scripts/TransferPermissions.js, core/test/scripts/Voting.js, core/utils/Constants.js, documentation/explainers/dvm_interfaces.md, documentation/tutorials/customizing-tokens-via-cli.md, sponsor-dapp-v2/src/drizzleOptions.js, sponsor-dapp-v2/src/lib/custom-hooks.js
moved struct and Setter/Getters to a new Contract
Upon construction, `Voting.sol` and `MockOracle` instantiate new instances of this struct
contracts compile, migrations fail
=> Refactor Voting supportedIdentifier struct and methods

core/contracts/Voting.sol, core/test/Voting.js
This pull request modifies how the `gatPercentage` is set within `voting.sol`. Before the `gatPercentage` was set on construction and then could not be changed. In this PR, the `gatPercentage` is set on construction and can then be modified using a new function `setGatPercentage`. 
As with the `inflationRate`, the `gatPercentage` is locked at the start of the reveal phase with the internal function `_freezeRoundVariables`. This stores the `gatPercentage` and `inflationRate` for that round such that any modifications will only be applied to the following voting round.
Tests and comments encompass these changes.
=> Uniform inflation rate handeling

core/contracts/TokenizedDerivative.sol, core/scripts/local/BatchGasEstimation.js, core/scripts/local/VoteGasEstimation.js
This PR contains a new script `BatchGasEstimation.js` which determines the max number of batched commits, reveals, and reward retrievals that can fit into a single transaction. 
To optimize the execution time of the script, a variant of a binary search algorithm is used to decrease the number of brute force searches that need to be conducted. 
Based off a default ganache configuration with gas limit set to `60000000000` and gas price set to `2000` the following maximums are possible with the current contracts:
| Function        	| Max in one tx 	| Gas used 	|
|-----------------	|---------------	|----------	|
| batchCommit     	| 184              	| 6701759  	|
| batchReveal     	| 58            	| 5828051  	|
| retrieveRewards 	| 130           	| 3314252  	|
=> Batch reveal gas estimation

voter-dapp/src/ActiveRequests.js
This PR adds a limitation on the number of batch commit and reveals that can be done on one transaction by the user. This is done by defining a `canExecuteBatch` function that checks how many check boxes have been selected. If this exceeds a threshold of 20 the button is disabled and the user is informed. 
The screenshot below shows how the front end limits the max number that can be committed and revealed within one transaction.
The number 25 was informed by the work done in #828
=> Limit the number of batch commits & reveals that can be done

core/scripts/local/BatchGasEstimation.js
This PR changes how the `BatchGasEstimation.js` script handels submitting a commitment to include an encrypted payload along with the commitment. 
Additionally, this PR incorporates the changes required to use `identifierWhitelist` as implemented in PR #819. 
As a result of the addition of the encryption blob, the total number of transactions that can be fit within one commitment has decreased. Based off the current gas limit from Etherscan over the last 6 months of 9950000, the following maximum `batchCommit`, `batchReveal` and `retrieveRewards` are possible:
| Function        	| Max in one tx 	| Gas used 	|
|-----------------	|---------------	|----------	|
| batchCommit     	| 28            	| 6654676  	|
| batchReveal     	| 58            	| 5828051  	|
| retrieveRewards 	| 129 …
=> Updated batch gas estimation script to include encrypted payload

common/globalTruffleConfig.js
This small change enables the truffle optimizer. This results in decreasing bytecode size and makes interacting with contracts cheaper.
For example, the `voting.sol` contract bytecode was decreased from `22916` to `15694`. This is a considerable saving of 7222 bytes without sacrificing any performance or functionality.
=> Enable truffle optimization

core/contracts/AddressWhitelist.sol, core/contracts/Registry.sol, core/contracts/Store.sol, core/contracts/Voting.sol
This PR makes a number of functions that were previously private public. This makes building front ends and components that connect to the contract easier.
One consideration was making `FixedPoint.Unsigned`'s public and how this would work in the case of contract readability. This was tested with truffle console to ensure that the public interfaces are useable and all contract state was able to be read directly from the console. 
close #829
=> Improve contract viewability

core/scripts/local/CalculateContractBytecode.js
This simple script enables quick checking of byte code size and validation if the contract is currently below the block limit defined by EIP170. It can be run from the core directory by specifying the contract name you wish to check.
For example, say you wish to find the bytecode size of the `Voting.sol` build created by truffle. You would run the following from `/core`:
```
node scripts/local/CalculateContractBytecode.js --contract Voting
```
and the output would look like this:
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
finished compiling 🚀!
loading Voting.json
Contract is 15504 bytes in size.
This leaves a total of 9072 bytes within the EIP170 limit 🔥.
```
=> Added bytecode calculator tool

core/scripts/Voting.js, core/test/scripts/Voting.js
AVS now batches commits & reveals up to a specified amount of transactions that we have deemed safely under the block gas limit. Based on the total pending requests available to the user, the AVS will use as few batches as possible to execute all requests. For example, if the transaction limit is 25, and there are 101 pending requests, then the AVS will use 5 batches => (25, 25, 25, 25, 1),
Added a unit test to check that AVS is using optimal amount of batch commits & reveals, and refactored existing AVS unit tests to check for correct number of batch commits & reveals.
Importantly, I suppressed all console.log's in the AVS test script to keep consistent with rest of the truffle test suite that does not print to console.
Similar to #826
Fixes #562 
Signed-off-by: Nick Pai …
=> Add limit on max # of transactions that can fit into batch commits/reveals to AVS

core/contracts/Voting.sol, core/test/Voting.js
This PR adds getPriceRequestStatuses to allow offchain applications to view the current status of any current or previous price request.
The intention is to allow the voter dapp to more easily determine whether a voter should request a reward.
=> Add getPriceRequestStatuses view method

common/globalTruffleConfig.js, documentation/explainers/keys-and-networks.md
Ledger changed the standard derivation path they used in Ledger Live (their desktop app). This means that most people get funneled into the `"44'/60'/0'/0/0"` derivation path by default rather than the legacy one that our library assumes.
This PR changes the derivation path for the *_ledger networks to `"44'/60'/0'/0/0"`. The legacy (as ledger calls it) derivation path will be moved to *_ledger_legacy.
=> Add network for updated ledger derivation path

package.json
This updates the coverage tool to the stable version that follows the beta version we were using. By my understanding, nothing changed between these versions other than bug fixes.
=> Update coverage to non-beta version

common/Constants.js, voter-dapp/src/Dashboard.js, voter-dapp/src/RetrieveRewards.js
This adds a rudimentary rewards claiming section to the voter dapp.
The flow works as follows:
1. The dapp searches the last 10 rounds for rewards.
2. If there are any rewards to claim, the dapp will select a batch and display a "Claim Rewards" button to allow the user to send the transaction to claim those rewards.
3. If none are found, it displays a button to allow the user to do a query across all past rounds if they wish.
4. If they query all rounds and no rewards are found, the dapp displays text that no unclaimed rewards are found.
A few notes:
- The PriceResolved event is not emitted until the first individual claims rewards for that request. This means that for each price request someone must claim rewards on the command line before that option will be available in the dApp. We'll …
=> Add claim rewards to voter dApp

voter-dapp/src/ActiveRequests.js
This hot fix fixes a bug with the voter dapp that shows an error message prematurely.
=> Added hot fix for voterdapp multi-select

core/contracts/Registry.sol, core/contracts/RegistryInterface.sol, core/test/Registry.js
This PR changes how the registry stores data about party members. These changes prevent derivative contracts from being removed from the registry, improved queriability for parties and dynamic party allocation to derivatives. 
close #833 and close #780
=> Registry contract refactor

common/MetaMaskTruffleProvider.js, common/globalTruffleConfig.js, core/contracts/Registry.sol, package.json
This PR enables metamask to be used as a truffle provider 🕺. This can be done by specifying the the metamask as a network parameter when calling truffle. For example, to open a console session with Metamask as the provider run:
```
truffle console --network metamask
```
This will use the network that metamask is connected to at the time of connection.
=> Metamask truffle provider

core/contracts/financial_templates/Liquidatable.sol, core/test/financial_templates/Liquidatable.js
This PR slightly refactors Liquidatable so that we track both the last used index and the liquidations in an array rather than using separate data structures.
All the methods continue to work similarly as they did before, except that when the array is accessed out of bounds, solidity automatically throws rather than giving an uninitialized struct.
This also includes a slight rewriting of some of the modifiers, so we don't repeatedly call the same method.
=> Minor Liquidatable refactor

.circleci/config.yml, common/AdminUtils.js, core/scripts/cli/admin.js, core/scripts/cli/cli_entry.sh, voter-dapp/src/ActiveRequests.js, voter-dapp/src/drizzleOptions.js
Adds a button next to an admin proposal that shows up a dialog explaining the proposal. The explanation text is what the CLI shows: we could try to improve both over time. E.g., interpret the most common admin proposals and show special handling for "setInflationRate".
I tried a few different options, such as a separate table and a tooltip, but this option seemed like the best for now.
Table:
Popup:
=> Decode admin proposals in voter dapp

scripts/deploy_dapp.sh
The one weird thing is that this change also applies to the sponsor
dapp, where it isn't necessary.
Options here are to:
1. Set CI=false on the entire `deploy_dapp.sh` invocation for voter dapp
only
2. Parameterize `deploy_dapp.sh`
3. Do nothing. What's good for the goose is good for the gander.
PR #880 imports AbiUtils from the voter dapp, which results in a build
warning that has to be ignored. AFAIK the only way to ignore webpack
build warnings from React is to turn off CI mode.
=> Fix bug in voter dapp deployment due to build warning

sponsor-dapp-v2/src/components/Step3.js, sponsor-dapp-v2/src/components/Step6.js, voter-dapp/src/Dashboard.js, voter-dapp/src/DesignatedVotingTransfer.js, voter-dapp/src/RetrieveRewards.js, voter-dapp/src/TokenTracker.js
This PR implements [EIP747](https://ethereum-magicians.org/t/eip-747-wallet-watchasset/1048) which provides a simple mechanism to enable users to track tokens from their wallet. In the case of the voter dapp this will enable voters to track UMA tokens from their metamask wallet. For the sponsor dapp this will enable sponsors to add their newly minted tokens to their metamask wallet token tracker.
The screenshot below shows the metamask window.
Right now EIP747 does not provide any interface to detect if a token is already tracked. This makes the UX clunky for users that have already tracked a token. Ideally a "track token" button should only be shown if and only if user is not already tracking it. For this reason the track token button has been excluded from the voter dapp. When EIP747 …
=> Eip747 implementation

core/contracts/financial_templates/Liquidatable.sol, core/test/financial_templates/Liquidatable.js
This issue will close #895 which included a bug where `liquidatable` was using the `disputeTime` opposed to the `LiquidationTime` when creating and disputing liquidations.
=> Update `liquidatable` `disputeTime` to use `LiquidationTime`

core/contracts/financial_templates/Liquidatable.sol, core/contracts/financial_templates/PricelessPositionManager.sol
This PR removes all require messages from liquidatable and priceless position manager to decrease contract bytecode size within a manageable limit issue #911 will add these back to the contracts once we've been able to better optimize the implementation.
=> Removed require messages

core/contracts/financial_templates/FeePayer.sol, core/contracts/financial_templates/PricelessPositionManager.sol
This moves the _getStore() method to the FeePayer contract since that's the only place where it would be needed.
It also changes the types returned by _getStore and _getIdentifierWhitelist to return a contract type rather than an address so the caller doesn't have to cast.
=> Refactor _get[interface] functions

core/contracts/financial_templates/PricelessPositionManager.sol
Inspired by this [article on optimizing contract bytecode size](https://blog.polymath.network/solidity-tips-and-tricks-to-save-gas-and-reduce-bytecode-size-c44580b218e6), I replaced some of the re-used modifiers in `PricelessPositionManager`.
It saves ~500 bytes, a modest savings from a modest programmer
=> Replace code inside function modifiers with single-line call to internal method

core/scripts/local/CalculateContractBytecode.js
When running the bytecode script, users should now specify the `-c` flag so truffle will compile before running. Previously the script was compiling the contracts, itself, but it was doing so without respecting the repo's truffle config.
=> Modify bytecode script to use external compilation

core/contracts/financial_templates/implementation/FeePayer.sol, core/contracts/financial_templates/implementation/PricelessPositionManager.sol, core/contracts/oracle/implementation/DesignatedVoting.sol, core/contracts/oracle/implementation/DesignatedVotingFactory.sol, core/contracts/oracle/implementation/Finder.sol, core/contracts/oracle/implementation/Governor.sol, core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/FinderInterface.sol, core/contracts/tokenized_derivative/ContractCreator.sol, core/contracts/tokenized_derivative/TokenizedDerivative.sol
This moves the finder into the oracle directory and separates it into an interface and implementation.
=> Separate finder into interface and implementation

core/contracts/financial_templates/implementation/Token.sol
In PR #922 I forgot to add the dependency `Token is TokenInterface ...`
=> Quick fix where Token is TokenInterface

core/contracts/financial_templates/implementation/Liquidatable.sol
This PR cleans up the liquidatable withdraw method in a few ways:
- It removes the transfer call from each if statement and instead performs it at the bottom of the method where the event is emitted.
- The method now returns a fixed point number rather than a uint (matches the way we typically deal with these numbers).
- It separates the if elses in the dispute succeeded case into ifs in case one address holds multiple roles in the liquidation (technically one address could be all three).
- It fixes an issue where the liquidation data structure wasn't being wiped after all parties had withdrawn. This was because we were checking the balance of the contract rather than checking whether all parties were deleted.
- Modifies the method to use `safeTransfer` rather than vanilla transfer.
=> Refactor Liquidatable withdraw

core/contracts/oracle/implementation/DesignatedVoting.sol, core/contracts/oracle/implementation/Governor.sol, core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/VotingInterface.sol
`Governor` currently imports `Voting` in order to call `getPrice()` and `requestPrice()`. Instead, it should import `OracleInterface` which has `getPrice()`. I renamed `_getVoting` and all instances of `Voting` to `Oracle`-related names.
`DesignatedVoting` imports `Voting` to call `batchCommit`, `batchReveal`, so I added these to `VotingInterface`.
Resolves #932
=> Add methods to `VotingInterface` to eliminate imports of `Voting`

core/contracts/financial_templates/implementation/Liquidatable.sol, core/test/financial_templates/Liquidatable.js
Makes small change to #926 which added a parameter to `createLiquidation` to prevent front-running. I changed `IsEqual` to `IsGreaterThanOrEqual` when comparing the new parameter to the underlying collateral (returned by `_getCollateral`). We do not need to revert any liquidations if the collateral declines, as the collateralization ratio has only gotten worst.
=> Check that liquidated amount is >= underlying collateral amount instead of ==

core/contracts/financial_templates/implementation/PricelessPositionManager.sol, core/test/financial_templates/PricelessPositionManager.js
Adds `mulCeil` and `divCeil` to fee adjustment calculations in `_payOracleFees` and `payFees`. It is possible that the `feePaid` divided by the `totalPositionCollateral` needs to be "ceil'd" rather than "floor'd". If this "fee %" is lower than what we expect, then all of the position collaterals become slightly higher than what we expect, potentially causing some token redemptions to not be fully backed by collateral. Therefore, we must "ceil" the "fee %"
Fixes #873
=> Fix rounding errors in ExpiringMultiparty

core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial_templates/PricelessPositionManager.js
This means that after the first call to `settleExpired()`, the contract can no longer be impacted by UMA voter/DVM actions.
=> Store an expiry price in PPM

ci/run_slither.sh
This PR includes several changes to `run_slither.sh`:
- Remove unnecessary `truffle compile` before running `slither`: `build.sh` (earlier in CI workflow) already compiles contracts
- add --filter-paths=@openzeppelin to slither script to ignore Openzeppelin contracts. Although we depend on these contracts and therefore we must ensure that they are secure as well, we should ignore for a couple reasons. One being that presumably openzeppelin rigorously tests their contracts before publishing. Second, we added a bunch of detectors to exclude while running Slither just because the openzeppelin contracts throw
- Detectors that we can remove from the `--exclude` flag: `locked-ether`, `reentrancy-eth`, `uninitialized-state-variables`, `shadowing-local`, `low-level-calls`, …
=> Edit Slither CI script: filter out @openzeppelin contracts, add back detectors

financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, liquidator/liquidator.js, liquidator/package.json
Nothing internal has been implemented in this PR.
Ideally, we'd want liquidator/ to depend on financial-templates-lib/ via an NPM dependency.
Issue #992 
=> Add shim of liquidator script

core/contracts/oracle/implementation/Voting.sol
For improving security, make price request data private in `Voting.sol`
Fixes #982 
=> make pricerequest contract data private

core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js
This PR introduces emergency shutdown to the NFCT. This required a small change to how state pertaining to a price retrieval is stored within the `settleExpired` function. Previously a bool `hasExpiryPrice` was used to check if a price had been received. This is now changed to use a enum `ContractState` which defines three different states, including a pending and received price state.
At contract emergency shutdown, the expiring multiparty contract's `expirationTimestamp` is set to the shutdown time. This means that the normal exit process via `settleExpired` is still functional in the normal way, once the DVM has resolved the price request.
No fees are charged during an emergency shutdown.
This PR also fixes two vulnerabilities as a byproduct:
1) liquidations are now disabled post …
=> NFCT Emergency Shutdown

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/ExpiringMultiParty.js, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js, financial-templates-lib/test/ExpiringMultiPartyClient.js
This PR introduces the notion of a `siphon` function that enables excess collateral to be drained out of a contract if it has not been redeemed after a set maturity. All drained funds are sent to the store. 
The implementation in this PR was informed from a discussion we had during the week. If we choose to change how this siphon function works it's not a huge deal as this PR lays the foundation for this process. We can always introduce more logic to it as well as additional governance steps if we deem it appropriate.
Post `siphonDelay` all functionality is disabled except for the `siphon` function as the `onlyPostExpiration` modifier operates within the range from:
```
expiatory < t < expiry + siphonDelay
```
close #1001
=> Expiring multi party `siphon`

financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyClient.js
This PR adds the logic to `expiringmultipartyClient` to detect pending withdrawals and add them to state. A few additional comments to the contract tests were also added.
close #1000
=> Add pending withdrawal detection to `ExpiringMultiPartyClient`

ci/deploy_to_staging.sh, common/Enums.js, core/contracts/oracle/implementation/ContractCreator.sol, core/contracts/oracle/implementation/Registry.sol, core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/AdministrateeInterface.sol, core/contracts/oracle/interfaces/RegistryInterface.sol, core/contracts/oracle/interfaces/StoreInterface.sol, core/migrations/14_deploy_register_creator.js, core/migrations/8_deploy_governor.js, core/scripts/CheckDeploymentValidity.js, core/scripts/local/BatchGasEstimation.js, core/scripts/local/InitializeSystem.js, core/scripts/local/RequestOraclePrice.js, core/scripts/local/VoteGasEstimation.js, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/oracle/DesignatedVoting.js, core/test/oracle/Registry.js, core/test/oracle/Voting.js, core/test/scripts/DecodeTransactionData.js, core/test/scripts/EmergencyShutdown.js, core/test/scripts/Voting.js, core/test/tokenized-derivative/TokenizedDerivative.js, sponsor-dapp-v2/src/lib/custom-hooks.js, sponsor-dapp-v2/src/views/ViewPositions.js
This is a mostly mechanical change to go from `derivative` language to using the generic term `contract` (or `financialContract` in a small number of places).
Since this involved many changes in the Registry, I went ahead and modified a few of the comments in that file to make them clearer.
Fixes #975.
=> Change `derivative` to `contract` in the DVM

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/migrations/17_deploy_tokenfactory.js, core/test/financial-templates/ExpiringMultiParty.js, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js, core/utils/Constants.js
There is no reason for an EMP deployer to pass in a TF address, I instead register the contract with the Finder and grab it there.
I could see a counter argument if we want to enable multiple implementations of TF--thoughts?
=> remove TokenFactory address from EMP config

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/test/financial-templates/ExpiringMultiPartyCreator.js
Force expirations to be start of month, between April 2020 and June 2021. Removes the need to check for latest expiration timestamp because all timestamps must be on the hardcoded list.
=> Discretize  expiration timestamps

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/ExpiringMultiParty.js, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, liquidator/test/Liquidator.js
This PR removes the sipon functionality added to the contracts in #1002. In doing so, this PR will close #1027
=> Removed siphon from EMP

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/migrations/17_deploy_tokenfactory.js, core/migrations/18_deploy_expiring_multi_party_creator.js, core/test/financial-templates/ExpiringMultiParty.js, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js, core/utils/Constants.js
Originally, I registered `TokenFactory` with the `Finder` thinking that it is a singleton contract referenced by other contracts and therefore should be added to the Finder for smoother upgradeability.
However, I didn't realize that `Finder` is explicitly made a DVM contract, designed to be owned by the DVM's governor. This can be seen in [`/scripts/TransferPermissions`](https://github.com/UMAprotocol/protocol/blob/master/core/scripts/TransferPermissions.js).
However, I still don't think it is clean to have original implementation of `ExpiringMultiPartyCreator.createExpiringMultiparty()` take in a `TokenFactory` address. I think that the deployer of a financial template should not be responsible for determining which TF to set. Therefore, I have made one small change and ask that the …
=> Revert commit that adds TF to Finder

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/test/financial-templates/ExpiringMultiPartyCreator.js
Regarding the addition of July 2021, I realize that if we want the last expiration to be June 30 2021, then we need an additional timestamp: July 2021. The previous latest timestamp was June 2021.
=> Add Olympics 2020 expiration timestamp and July 2021 

core/.env_sample, financial-templates-lib/Logger.js, liquidator/liquidator.js, liquidator/test/Liquidator.js, package.json
This PR adds basic slack integration to the liquidator bot to close #1030 . Additional refinement is require to improve the output styling and formatting of the slack message, as detailed in issue #1031 . 
The screenshots below shows the current slack output for a few basic operations in liquidating 5 positions
This output is currently the same as generated in the console. Issue #1031 will add a custom formatter to create nice looking markdown logs in Slack.
Information on creating webhooks can be found here: https://slack.com/intl/en-za/help/articles/115005265063-Incoming-Webhooks-for-Slack
=> Added slack integration to liquidator

.circleci/config.yml, ci/deploy_to_staging.sh, package.json
This PR fixes our docs generation so it works with 0.6. To do this, I made some changes to our solidity-docgen fork and put them on the `fork-updated` branch.
These changes include:
- Updating to the latest open zeppelin commit.
- Removing some of our changes/commented code that are no longer necessary due to updates in the upstream repo.
- Fixing a minor 0.6 compatibility issue in the upstream repo.
This commit includes all changes that differ from HEAD of the upstream repository:
https://github.com/UMAprotocol/solidity-docgen/commit/8b918b387337615d4991f4eb3d4042810b0f0bdf
Fixes #977
=> Fix docs generation to work with Solidity 0.6

ci/run_truffle_tests.sh, disputer/disputer.js, disputer/index.js, disputer/package.json, disputer/test/Disputer.js, package.json
This follows the general template established by the liquidation bot.
Two TODOs left in the code:
- Managing collateral inventory.
- Withdrawing collateral after the dispute is completed.
Pertains to #1011.
=> Add dispute bot implementation

ci/run_truffle_tests.sh, financial-templates-lib/package.json, liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js
While starting work on adding reward withdrawal logic to the Liquidator bot, I ran into build and test issues
- `winston-slack-transporter` was missing from `package.json` for `financial-templates-lib`
- `liquidator/test` was not up to date with latest NFCT contract code meaning that these changes were not getting caught in CI. I fixed the tests and added to CI similar to financial-templates-lib
=> Add Liquidator bot tests to CI, update dependency requirements, update tests

financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, liquidator/liquidator.js
- added methods to return (1) expired liquidations and (2) disputed liquidations. Instead of creating these two arrays, I could have instead consolidated them into one `withdrawableLiquidations` but I thought it might be useful specifically for the Disputer bot to get just the disputed liquidations because the disputer cannot withdraw from an expired liquidation.
- Throughout the course of adding the above methods, I found various parts we could refactor in the main `_update()` method in the EMP Client
- Added to and reorganized some of the EMP Client unit tests
In a follow-up pull request, I will add logic to `liquidator/liquidator.js` to actually withdraw rewards, but for now I've left placeholder TODO's.
=> Refactored and added methods to ExpiringMultiPartyClient to support the Liquidator withdrawing rewards

scripts/build_docs_site.sh
@rcai1 wants to use `.png`s on the docs site, so I figured it would make sense to go ahead and add them along with `.jpg`s to our `build_docs_site.sh` script.
=> Add .jpg and .png file extensions to docs site

disputer/disputer.js, disputer/index.js, disputer/test/Disputer.js, financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyClient.js
Adds `queryAndWithdrawRewards` (like in the liquidation bot) to the dispute bot. This is a fairly straightforward change.
Outside of the dispute bot, this change required a slight addition to the liquidation object that the EMP returns to make it easier to determine the liquidations that are eligible for withdrawal.
Fixes  #1092.
=> Add withdraw functionality to dispute bot

package.json
OZ released a number of breaking changes. If the `^` is included then compilation will fail as the current OZ versions include some changes to directory structure (`ownable.sol` and `ERC20Snapshot.sol` move) and some implementation changes.
=> Locks OZ version used in the NFCT

disputer/disputer.js, disputer/test/Disputer.js
This just adds a quick simulation of the txn before sending that should catch an insufficient balance. There are more sophisticated implementation of inventory management that give more detailed descriptions of what went wrong, but that seems unnecessarily complex at this point.
Fixes #1092.
=> Add basic inventory management to the dispute bot

financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, liquidator/liquidator.js
This PR is kinda a mismash of refactors on the liquidator. I combined them because some of the log changes were due to the changes in structure and logic. Happy to try to decompose if it's difficult to review.
This PR does a few things:
- Slightly simplifies the structure of the liquidation bot by returning early in a few places.
- Updates log message positioning and level so there are no `info` messages that get sent on every iteration. `info` should now only be used if a transaction is sent since that's the only case where the state is likely to change before the next iteration.
- Adds filtering to the liquidation withdrawals, so withdraw isn't even attempted if `this.account` wasn't the liquidator.
- Removed the check for a withdrawal amount of 0, since the `.call` will revert in that …
=> Minor refactor of liquidation bot

disputer/index.js
Since we don't test the `index.js` files, the disputer had a few typos and errors.
=> Fix errors in disputer index.js

liquidator/liquidator.js, liquidator/test/Liquidator.js
The liquidation bot currently attempts to liquidate before simulating the transaction to ensure it doesn't revert. This PR adds the simulation step, which will catch cases where the liquidation bot doesn't have enough capital to initiate the liquidation (in addition to other sporadic errors, like the sponsor modifying their position, etc).
=> Detect if there's not enough capital to liquidate

scripts/build_docs_site.sh, scripts/gen-nav.js
Github anchors are generated based on the section title. The html site generates them in a different style. This PR adds preprocessing to correct for this difference.
- It adds an underscore at the beginning of the anchor.
- It adds a leading underscore to all anchors.
- It corrects a previous error where links that had anchors were not being correctly converted from `.md` to `.html`.
I also included a minor, unrelated error message change to improve debuggability of the site generation.
Issue #1055.
=> Fix anchors in docs site links

scripts/build_docs_site.sh
The nested structure of our docs cannot be replicated in antora since their concept of modules (as far as I'm aware) cannot be nested. So essentially all docs sit at the module level. The github repo structure does not mirror this, so we have to massage the links to flatten them into the antora structure. I've added two more preprocessing `sed` commands to flatten these links.
cc @rcai1 @hlambur
Issue #1055.
=> Flatten docs site links

documentation/synthetic_tokens/tutorials/creating_from_truffle.md
Fixing a small issue with a link in the synthetic token tutorial.
=> Fix explainer link

core/contracts/common/interfaces/Uniswap.sol, core/contracts/common/test/UniswapMock.sol
This adds an interface and a mock for Uniswap V2. Note: I've only included the `Sync` event that we'll use to calculate the TWAP offchain. Since this isn't currently used in any of our other contracts, we're free to add to it as we see fit.
Note: for reference, here's this event in the uniswap v2 contract: https://github.com/Uniswap/uniswap-v2-core/blob/1f563ce23b6dbe972d667c79058d0299e6f10ff6/contracts/UniswapV2Pair.sol#L59
=> Add Uniswap interface and mock

core/scripts/PrecisionErrors.js, core/scripts/local/DeployEMP.js
Also cleans up the test suite and makes results clearer to understand.
`settleExpiry` test case:
```
Precision loss in proportion of collateral redeemed via settleExpired()
** Position expires, settlement price is 0.5: Actual and Credited Collateral should be equal **
┌───────────────────────────────────┬────────────────────────┐
│              (index)              │     totalPosition      │
├───────────────────────────────────┼────────────────────────┤
│   Collateral owned by Contract    │ '0.000000000000000001' │
│ Total position tokens outstanding │ '0.000000000000000001' │
│     Non-Sponsor token balance     │ '0.000000000000000001' │
│       Sponsor token balance       │          '0'           │
└───────────────────────────────────┴────────────────────────┘
** After a Non-Sponsor …
```
=> Add precision loss study on `settleExpired()` to Precision Errors script

core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js
Resolves #1049 
There are two situations where we need to handle `(withdrawalRequestAmount > _getCollateral(sponsor)`:
1.  `withdrawPassedRequest()`: Requested withdrawal amount might be greater than position's collateral (due to regular fees accrued, or user just requested too much), so we instead withdraw the full collateral available
2. `createLiquidation()`: Pending withdrawal amount is greater than position's collateral, so calculating `startCollateralNetWithdrawal = startCollateral.sub(withdrawalRequestAmount)` could revert. Here, if `withdrawalRequestAmount > startCollateral` then I set `startCollateralNetWithdrawal = 0`.
I also added a test to `PricelessPositionManager.js` that shows that it is impossible to withdraw instantly (via `withdraw()`) the full position collateral.
=> Handle withdrawal requests that are greater than position's collateral

common/globalTruffleConfig.js, core/contracts/financial-templates/implementation/SyntheticToken.sol, core/scripts/IntegrationTests.js
This PR adds two an addition integration test (which follows the same pattern as before by iteratively calling `create`, `createLiquidation`, `deposit`, `redeem`, `withdrawLiquidation` and `settleExpired`) but uses unfriendly numbers **and** a regular fee. 
**TLDR:** Contract drift is directly proportional to the total collateral locked and the number of iterations performed. This relationship places a reasonable bound on how much _dust_ can be lost in a contract at expiry and quantifies how much is lost from interactions. From the iterative experiments an average of ~ 1Wei is lost per 1 unit of collateral (1e18) which is shown to scale linearly with collateral added. Under no configuration is the contract locked.
In order for these tests to pass up to 1000 iterations the contract …
=> basic adversarial integration tests

common/SolidityTestUtils.js, financial-templates-lib/test/UniswapPriceFeed.js
In the Uniswap price feed library, it's important that we handle multiple trades in the same block correctly. Since we don't control the contract we're subscribing to, we'll also have to use the block time to correctly compute TWAPs.
For these reasons, it was necessary to build a utility functions that can bunch transactions into the same block and control the block timestamp of that block.
Relevant to issue #1138.
=> Add intrablock uniswap test and utility

core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/Liquidatable.js
This PR adds functionality to force the liquidator to post the final fee as a "bond". If the liquidator wins the liquidation, then they receive this bond back. If not, it goes to pay the final fee.
=> Liquidator pays final fee bond

core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/scripts/PrecisionErrors.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js
This PR enforces that `withdraw`, `redeem`, `settleExpired` and `withdrawLiquidation` all transfer from the contract the exact amount of collateral that the position's collateral is decreased by. The tradeoff is that the user might receive 1e-18 less collateral than they expected to receive.
The bulk of this PR is additional unit tests to make sure that contracts are dealing with precision loss in the expected way.
More specifics below:
___
In `withdraw()`, `redeem()`, `settleExpired()`, and `withdrawLiquidation()`, collateral is transferred out of the contract via `safeTransfer(amount)` while the internal counter `rawTotalPositionCollateral` or `rawLiquidationCollateral` is decreased. 
The ideal is to always maintain the invariant that `(rawCollateral * cumulativeFeeMultiplier)` is less …
=> Resolve precision loss in functions that call `_removeCollateral()` and withdraw collateral to the caller

core/scripts/cli/sponsor/redeem.js, core/scripts/cli/sponsor/withdraw.js, core/scripts/local/DeployEMP.js
Fixed a bug where user received less collateral than they were expecting and therefore failed to unwrap the expected amount of WETH. 
Can re-create the situation by creating a position with 3 tokens (4.5 ETH collateral), and redeeming 1 token. This should redeem 1/3 of the collateral, 1.5 ETH, but due to rounding returns slightly less than that.
Resolves #1173 
=> Sponsor CLI: confirms withdrawal amount for redeem and withdraw before unwrapping WETH collateral

liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js
Resolves #1067 
I elected to make both bots take as input a callable `pricefunction(timestamp_seconds)` as this seems more powerful. 
=> Change "price feed" in Liquidator bot into a "price function" to standardize with Disputer bot

core/contracts/financial-templates/implementation/Liquidatable.sol, core/test/financial-templates/Liquidatable.js
This PR adds return values to createLiquidation and dispute to allow the caller to compute the tokens and/or collateral that will be pulled from their accounts when called.
=> Add return values to createLiquidation and dispute

scripts/build_docs_site.sh
Previously:
```
[link here](www.example.com/example.md)
```
was being changed to:
```
[link here](www.example.com/example.html)
```
However, we want external sites to retain their extension.
The only links we want to change are ones to `.md` files that are within the site. For example:
```
[link here](./internal_file.md)
```
should be changed to:
```
[link here](./internal_file.html)
```
This PR updates the sed to distinguish.
cc @rcai1 this should fix the link issue you were seeing.
=> Update docs site to not change `.md` extensions for external links

financial-templates-lib/GasEstimator.js, financial-templates-lib/test/GasEstimator.js
Resolves #1183 
`getPrice()` was only called internally by `_update()`, so I re-named to `_getPrice()` to better highlight that a client should be calling `getCurrentFastPrice()`.
=> Gas Estimator: Add unit tests, change getPrice to _getPrice

core/contracts/oracle/implementation/Governor.sol, core/test/oracle/Governor.js
Resolves #1190 
Make `propose()` a payable function and check that the caller deposits enough ETH to cover all payable transactions (i.e. In which the `Transaction` struct has `value > 0`.
One design decision I made that I'm not 100% sure on: I could have made `propose()` or `executeProposal()` payable. I chose to make the "upfront" action payable so that voters would not vote through a proposal that ultimately can't execute because the contract doesn't have enough ETH to execute payable transactions.
=> [P1-H02] Add ability for Governor to execute payable proposed transactions

core/contracts/common/test/ReentrancyChecker.sol, core/contracts/oracle/implementation/Governor.sol, core/test/oracle/Governor.js
This PR prevents a re-entrancy attack where a proposal execution re-enters and attempts to execute itself again.
It's prevented by deleting the proposal before the execution rather than after.
This PR also adds a test contract, called `ReentrancyChecker` that can be used to check for re-entrancy protection.
=> [P1-H03] Prevent re-entrancy on Governor executeProposal

financial-templates-lib/UniswapPriceFeed.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, financial-templates-lib/test/GasEstimator.js, financial-templates-lib/test/UniswapPriceFeed.js
This adds a historical TWAP function to the Uniswap price feed.
On construction, the price feed must be told the maximum historical lookback allowed so it knows how many events to look back.
Curious to hear thoughts on whether this method should stop users (or return `null`) when passing in a timestamp that is past the lastUpdateTime. There are definitely tradeoffs either way.
Note: I removed an accidental `it.only()` that revealed some previously broken tests. I removed the `it.only()` and fixed the tests in this PR.
=> Add historical TWAP

core/contracts/oracle/implementation/Registry.sol, core/test/oracle/Registry.js
This PR prevents one address being registered multiple times in the `Registry` upon calling `registerContract`. This change prevents the `Registry` from ending in an inconsistent state as a result of one address being registered multiple times as a party for one contract address.
The `registerContract` function now behaves more like `addPartyToContract` which previously enforced this check that an address cant be added multiple times.
close #1195
=> [P1-M04] Refactor registry to prevent multiple address registration during inital contract registration

core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/implementation/test/VotingTest.sol, core/test/oracle/Voting.js
This PR corrects an issue where the length of `pendingPriceRequests` in `Voting.sol` was not being decreased when the last element was deleted.
To ensure this behavior remains correct, I added a unit test to verify the raw array's length.
Note: to access its length, one would need to add a custom method rather than just making the array a public variable. Rather than adding a new public method on the `Voting` contract that would only be used for testing, a derived `TestVoting` contract was added to access this variable. Definitely open to doing this a different way, but, to me, this seemed like the cleanest solution.
=> [P1-L11] Correct element deletion in pendingPriceRequests array

core/contracts/oracle/implementation/Governor.sol, core/contracts/oracle/implementation/test/GovernorTest.sol, core/test/oracle/Governor.js
This PR:
- Breaks out and documents the steps in the `bytes32` manipulation functions in `Governor.sol`.
- Changes the name of the `_uintToBytes` to `_uintToUtf8` to make its intention clearer.
- Adds tests for the `bytes32` manipulation functions in `Governor.sol`.
=> [P1-M02] Test and document the bytes32 manipulation functions in Governor.sol

core/contracts/oracle/implementation/Finder.sol, core/test/oracle/Finder.js
The `Finder` should only allow implementation addresses to be contracts. This PR integrates with the OZ [Addresses.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.0.0-beta.0/contracts/utils/Address.sol#L24) library to enforce this.
=> [P1-L02] Prevent EOAs from registering in the finder

core/contracts/oracle/implementation/Store.sol, core/test/oracle/Store.js
Right now the store does not emit events after fees being updated. This PR adds them and associated tests.
Open question: I dont really see enough test coverage for weekly delay fees. This should be expanded.
=> [P1-L14] Add events to store state fee update

core/contracts/common/implementation/MultiRole.sol
This PR removes the use of a hardcoded `false` within `require` statement within `MultiRole.sol` in favour of a direct `revert` call.
=> [P1-N11] Remove hard-coded condition statement in require

core/contracts/common/implementation/Withdrawable.sol, core/contracts/common/test/WithdrawableTest.sol, core/test/common/Withdrawable.js
This PR ensures that only valid roles can be added to the Withdrawal contract via the `setWithdrawRole` function. This function is only ever called from the constructor of `DesignatedVoting.sol`, which calls `setWithdrawRole` in the constructor using the Roles enum.
=> [P1-L13] Add onlyValidRole to setWithdrawRole

core/contracts/common/implementation/Withdrawable.sol
This PR replaces the use of transfer with sendValue to enable sending ether to contracts with callback functions.
=> [P1-L10] Replace transfer with sendValue

common/EncryptionHelper.js, common/VotingUtils.js, core/contracts/oracle/implementation/Governor.sol, core/contracts/oracle/implementation/Voting.sol, core/scripts/local/BatchGasEstimation.js, core/scripts/local/VoteGasEstimation.js, core/test/oracle/DesignatedVoting.js, core/test/oracle/Governor.js, core/test/oracle/Voting.js, voter-dapp/src/ActiveRequests.js
Resolves #1216 
Resolves #1219 
Caller now must include an address, price request timestamp, round ID, and pricefeed identifier with their vote hash. The hash is enforced in `revealVote`.
This includes fixes for the voting-cli and the voter-dapp as well.
=> [P1-H01] Require additional data in vote commit hash to prevent duplication of votes

core/contracts/oracle/implementation/Voting.sol, core/test/oracle/Voting.js
NOTE: there is a functionality difference now in that we no longer emit
events for voters who didn't vote. Do we rely on this behavior anywhere?
=> [P1-L09] Suppress reward events if user already retrieved or didn't vote

core/contracts/common/implementation/MultiRole.sol, core/contracts/oracle/implementation/Store.sol, core/contracts/oracle/implementation/VoteTiming.sol, core/test/common/MultiRole.js, core/test/oracle/Store.js, core/test/oracle/VoteTiming.js
There are a number of places in the DVM that do not have sufficient input validation. This PR adds this as well as associated tests.
=> [P1-L08] Add input validation throughout DVM

core/contracts/common/implementation/FixedPoint.sol, core/contracts/oracle/implementation/ContractCreator.sol, core/contracts/oracle/implementation/ResultComputation.sol
@ptare I think their suggestion to remove TODOs is a reasonable one. Do you think any of these should be tracked separately or are they not worth it?
For exponentiation-by-squaring one, we could just remove the TODO and just mention an alternative implementation?
I'm not super concerned about making everything withdrawable.
I think we've decided (by default) that we don't want to parameterize the "majority" threshold.
Thoughts?
=> [P1-N02] Remove TODOs

core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/oracle/implementation/Store.sol, core/contracts/oracle/interfaces/StoreInterface.sol, core/contracts/tokenized-derivative/TokenizedDerivative.sol, core/test/oracle/Store.js
The previous implementation transferred all the approved tokens, which
is suboptimal because allowances are not considered payments. Note that
this PR doesn't change functionality because the only callers to
`payOracleFeesErc20` were other contracts.
We prefer to have an explicit function rather than the callers simply
transferring tokens because while this implementation of Store.sol
doesn't do anything in this function, we want the StoreInterface to have
an explicit function we can plug in to later.
=> [P1-L19] Explicitly pass in amount of ERC20 to pay as fees

.eslintrc.js, package.json
This PR adds the [eslint-plugin-mocha](https://github.com/lo1tuma/eslint-plugin-mocha) package to eslint to check for `it.only` or `describe.only`. Specifically, the [no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md) rule is used to enable this. 
The screenshot below shows the output of ESLINT if an `it.only` is left in a test:
=> Detect `it.only` in tests with eslint

core/contracts/common/implementation/MultiRole.sol, core/test/common/MultiRole.js
=> Add events to MultiRole contract

core/contracts/oracle/implementation/Finder.sol, core/test/oracle/Finder.js
Reverts #1210 because we do not plan to upgrade the deployed Finder contract and we should keep repo code consistent with deployed code.
=> [P1-L02] Revert #1210

core/contracts/common/implementation/AddressWhitelist.sol, core/contracts/common/implementation/ExpandedERC20.sol, core/contracts/common/implementation/FixedPoint.sol, core/contracts/common/implementation/MultiRole.sol, core/contracts/common/implementation/TestnetERC20.sol, core/contracts/common/implementation/Timer.sol, core/contracts/common/implementation/Withdrawable.sol, core/contracts/oracle/implementation/DesignatedVoting.sol, core/contracts/oracle/implementation/VoteTiming.sol, core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/StoreInterface.sol
=> [P1-N12] Add NatSpec comments to remaining external DVM methods

core/contracts/oracle/implementation/Governor.sol, core/contracts/oracle/implementation/test/GovernorTest.sol, core/migrations/9_deploy_governor.js, core/test/oracle/Governor.js
This adds a line to the governor constructor that starts the proposal ids at an arbitrary number. This means we'll be able to ensure that when the Governor is upgraded, the proposal ids can continue to be unique. Note: this uniqueness is not absolutely necessary for the Governor to function correctly, but it does help the voters differentiate the proposals without having to use the timestamp.
It does involve inline assembly to directly modify the length of the array (modifying `length` was disallowed starting in Solidity 0.6).
=> Add starting id to governor constructor

core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/VotingInterface.sol, documentation/oracle/dvm_interfaces.md
=> [P1-N10] Warn users against re-using salts

core/contracts/oracle/implementation/Voting.sol, core/test/oracle/Voting.js
This just changes the name of the various roundId parameters so they are all the same. Namely, this will allow us to take advantage of the `getLatestEvent` (offchain) function for all the Voting events.
=> Change parameter names in Voting events for consistency

core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/VotingInterface.sol, documentation/oracle/dvm_interfaces.md
=> Move salt reuse warnings to `commitVote`, refine language

core/contracts/financial-templates/implementation/ExpiringMultiParty.sol
This PR removes a redundant import within the EMP. Originally the OZ audit found another 2 redundant end points but these were removed when we upgraded the timable implementation, in this [PR](https://github.com/UMAprotocol/protocol/pull/1236). As a result this PR is tiny 🍹
=> [P1-N15] removed import

core/scripts/cli/voting/getResolvedVotesByRoundId.js, voter-dapp/src/ResolvedRequests.js, voter-dapp/src/RetrieveRewards.js
#1275 changed the event argument name for `PriceResolved` from `resolutionRoundId` to `roundId`. This PR fixes the Voting CLI and Voter-dApp by filtering on this changed argument name.
I discovered this bug while testing the Voting CLI to see if I could display the pending Admin proposals.
=> DVM clients should filter on "roundId" instead of "resolutionRoundId"

core/contracts/financial-templates/implementation/PricelessPositionManager.sol
The `_getStoreAddress` function is implemented in the `PricelessPositionManager`, however it is never used. This PR removes this function.
=> [P2-N08] Removed unused repeated function in EMP

core/contracts/financial-templates/implementation/PricelessPositionManager.sol
This removes the pending withdraw data before executing the transfer of collateral.
I am still undecided if and how we should test re-entrancy for this change. I toyed with creating a contract `ReentrancyCheckerERC20` which inherits both `ReentrancyChecker` and `ExpandedERC20`. The idea is to override the `transfer` (or `safeTransfer`) method in the collateral contract such that when `withdrawPassedRequest()` calls `collateral.safeTransfer()` it triggers a pre-loaded reentrancy attack.
@mrice32 since you worked on the reentrancy fixes in the DVM, do you have any insight here if this would be a viable approach? Note that the `ReentrancyCheckerERC20` still needs to be a valid ERC20 that correctly excecutes methods like `safeTransferFrom` which is called by `create()` in order to get a test …
=> [P2-L01] Enforce Check-Effects-Interactions pattern in withdrawPassedRequest

core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/VotingInterface.sol
Follow up to #1217 
- @dev comment in `revealVote` lists hash contents in incorrect order. This should match the order in `commitVote` and more importantly the order that data is listed in `abi.encodePacked()`
- Error message "Revealed data != commit hash" might be shown to an end user that's not familiar with the "!=" idiom. I made this more readable.
=> Clarify copy in Voting.revealVote

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/test/financial-templates/ExpiringMultiPartyCreator.js
An increase in gas usage during deployment of ExpiringMultiPartyCreator,
but should reduce gas usage when deploying individual EMPs.
=> [P02-N02] Store valid timestamps in a map rather than an array

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/Liquidatable.sol
You could argue that the second parameter in LiquidationWithdrawn
shouldn't be indexed. Thoughts?
=> [P02-N06] Index parameters in events

ci/run_truffle_tests.sh, financial-templates-lib/price-feed/PriceFeedInterface.js, financial-templates-lib/price-feed/UniswapPriceFeed.js, financial-templates-lib/test/price-feed/UniswapPriceFeed.js
This adds a simple interface that all price feeds should implement.
This PR also includes changes to force the UniswapPriceFeed to conform to this interface, and it moves the price feeds to their own directory.
=> Add PriceFeedInterface

voter-dapp/src/DesignatedVotingDeployment.js
Now that we have the docs to show how to set up the 2key contract, we should also have a link to it from the dapp. This quick PR implements this.
=> Added link to docs for 2 key contract in voter Dapp

core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/ExpiringMultiParty.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js
This PR makes several changes that validate function input:
`PricelessPositionManager.sol`:
- constructor requires `_expirationTimestamp` to be greater than the current contract block timestamp.
- `deposit` requires `collateralAmount` to be greater than 0.
- `withdraw` and `requestWithdrawal` requires `collateralAmount` to be greater than 0 and less than the sponsor's position size. If charged fees cause the requested withdrawal amount to be greater than the collateral (net of fees), then the withdrawal amount gets set to collateral net of fees. @ptare This might require tweaking the Sponsor CLI if the CLI currently allows a user to withdraw/request a withdrawal greater than their position. Before it would get reduced to their full position, now it reverts.
- `withdrawPassedRequest` …
=> [P2-L02] Additional input validation

core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol
I believe these are all either done or we have decided not to do them
(e.g., we're find the implementation of remargin).
=> [P02-N13] Remove TODOs

core/contracts/financial-templates/implementation/PricelessPositionManager.sol
Not all internal methods require documentation, but I thought these
functions would benefit from documentation. Note: we do NOT use or
require natspec format for internal function documentation.
In a separate PR, I'll rewrite existing documentation in Natspec format to NOT use natspec for internal methods.
=> [P01-N11] Add documentation for a few internal methods

core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol
We use natspec only for the public methods.
=> [P02-N10] Use single-line comments rather than natspec for internal methods

documentation/synthetic_tokens/tutorials/creating_from_truffle.md
This PR addresses an issue with a long code snippet in the markdown linter. Pretter lints code within code blocks within markdown to remain consistent within all documentation. However there are some examples in the documentation where this is not desired. The code chunk changed in this PR should not be linted as this linting prevents the code chunk from being able to be copied into a truffle console.
=> Fix long code snippit markdown

financial-templates-lib/price-feed/MedianizerPriceFeed.js, financial-templates-lib/price-feed/PriceFeedInterface.js, financial-templates-lib/test/price-feed/MedianizerPriceFeed.js, financial-templates-lib/test/price-feed/PriceFeedMock.js
Adds a price feed that takes price feeds as constructor inputs and medianizes their outputs.
This will allow the implementation of an exchange price median using this price feed constructed with the multiple CryptoWatchPriceFeeds.
There were a few implementation decisions that were made that impact how this price feed will perform in production:
1. It returns the *max* of all of its constituent price feeds' `lastUpdateTime`s.
2. It returns `null` whenever any of the constituent price feeds return `null` or `undefined` for any call. This implies that it's effectively a "weakest link breaks the chain" type of system and errs on the side of being more correct but less reliable.
Note: this implementation also includes a `MockPriceFeed` to make unit testing easier.
=> Add MedianizerPriceFeed

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/ExpiringMultiPartyCreator.js, core/test/financial-templates/Liquidatable.js, core/test/financial-templates/PricelessPositionManager.js
- emit EndedSponsorPosition when sponsors are removed via transfers, settlements post-expiry, and liquidations.
- No longer register any party members with EMPCreator
- In EMPCreator's `CreatedExpiringMultiParty` event, renamed parameter from `partyMemberAddress` to `deployerAddress`
=> [P2-M03] Track sponsors via events

.circleci/config.yml, common/globalTruffleConfig.js, core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/ExpiringMultiPartyLib.sol, core/migrations/14_deploy_expiring_multi_party_creator.js, core/scripts/local/CalculateContractBytecode.js
This PR contains several features
- Increases gas limit on CI local Ethereum networks to more realistic (but conservative) 9,000,000.
- Reduces # of runs on optimizer in truffle-config to default of 200. Fewer runs = lower deployment cost and less deployed bytecode.
- Change `bytecode` to `deployedBytecode` in `CalculateContractBytecode.js` script.
- Abstract deployment of EMP into a library, which EMPCreator will call via `createExpiringMultiParty(params)`. H/t to @mrice32 for the idea. This separates EMP bytecode on-chain from the EMP-creator, which means that the EMP-creator is no longer the bytecode bottleneck for deploying the EMP set of contracts. 
`deployedBytecode` Statistics:
___
This PR:
- EMP Creator = `3041` bytes
- EMP = `17170` bytes
- EMPLib = `20974` bytes
Previous:
- EMP …
=> Gas limit tweaks and EMP bytecode optimization

core/contracts/financial-templates/implementation/Liquidatable.sol, core/test/financial-templates/Liquidatable.js, disputer/test/Disputer.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyEventClient.js, liquidator/liquidator.js, monitors/test/ContractMonitor.js
A liquidator can now specify a min and a max for collateralization ratio
of the position they are liquidating.
The idea is to avoid a delayed liquidation ending up liquidating a
position in haircut territory. E.g., if a liquidation takes a long time
to process and the underlying price moves significantly in that time.
=> [P02-H02] Restrict liquidations by min collateralization ratio as well

disputer/disputer.js, disputer/index.js, disputer/test/Disputer.js, financial-templates-lib/ExpiringMultiPartyClient.js, financial-templates-lib/GasEstimator.js, financial-templates-lib/price-feed/UniswapPriceFeed.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyEventClient.js, financial-templates-lib/test/GasEstimator.js, financial-templates-lib/test/price-feed/UniswapPriceFeed.js, liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js
This PR refactors 1) disputer, 2) liquidator, 3) ExpiringMultiPartyClient 4) UniswapPriceFeed to all follow a dependency injection pattern enabling re-usage of the Winston logging instance injected from the base class. This pattern was implemented in the monitoring bots infrastructure to enable stub testing of Winston events emitted and to have one single logger instance through a bot implementation. Se [PR 1252](https://github.com/UMAprotocol/protocol/pull/1252) for more info on Winston testing.
Note that this PR does not use this dependency injection to perform testing on the bots Winston messages. Rather this refactor sets up the ability for testing to be performed and this is deferred for a later PR and is documented in [issue …
=> Scaffolding logger dependency injection

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol
This PR adds ~2000 bytes to the `deployedBytecode`, giving us ~1300 bytes to finish remaining EMP tasks
```
Contract is 23275 bytes in size.
This leaves a total of 1301 bytes within the EIP170 limit.
```
=> [P2-L06] Add require messages back to EMP

core/contracts/financial-templates/implementation/FeePayer.sol, core/test/financial-templates/PricelessPositionManager.js
If `pfc` is not greater than `totalPaid`, then `payFees()` will revert. I chose to enforce `PfC > totalPaid` as opposed to `>=` to be consistent with `_payFinalFees()`, which would prevent the `cumulativeFeeMultiplier` from ever getting set to 0.
Additionally, `payFees()` now exits early without emitting an event if `totalPaid == 0`.
=> [P2-N01] Check whether regular fees owed is less than the available collateral

core/contracts/financial-templates/implementation/Liquidatable.sol, core/scripts/IntegrationTests.js, core/scripts/PrecisionErrors.js, core/test/financial-templates/Liquidatable.js, disputer/test/Disputer.js, financial-templates-lib/test/ExpiringMultiPartyClient.js, financial-templates-lib/test/ExpiringMultiPartyEventClient.js, liquidator/liquidator.js, monitors/test/ContractMonitor.js
This adds a `deadline` parameter to `createLiquidation()` to protect callers from the price moving against them (and invalidating their liquidation) in the case that their transaction sits longer than expected in the mempool.
Note: the only logical changes to createLiquidation are the addition of the require at the top. Everything else is just restructuring to avoid the stack too deep error.
=> Add deadline to createLiquidation()

financial-templates-lib/price-feed/CryptoWatchPriceFeed.js, financial-templates-lib/price-feed/Networker.js, financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js, financial-templates-lib/test/price-feed/NetworkerMock.js
This adds a price feed based on the cryptowatch api: https://docs.cryptowat.ch/rest-api/.
It also adds a `Networker` object that enables mocking of network calls/responses in the tests.
Next step: construct a price feed that aggregates multiple exchange price feeds.
Note: an aggregated price feed will just compose the outputs of multiple individual price feeds by taking them in its constructor.
=> Add CryptoWatchPriceFeed

core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol, core/scripts/DeploySyntheticTokens.js, core/scripts/local/AdvanceEMP.js, core/scripts/local/DeployEMP.js, core/test/financial-templates/ExpiringMultiPartyCreator.js
- EMPCreator should deploy EMP's with same Timer that it is initialized with
- Withdrawal and Liquidation liveness extended to 120 mins
=> EMPCreator refactors

core/contracts/financial-templates/implementation/PricelessPositionManager.sol
I know there are other ways that requests can be unwithdrawable, but I think it's still reasonable to make this inequality consistent.
=> [P2-M02] Make inequality consistent

disputer/disputer.js, financial-templates-lib/clients/ExpiringMultiPartyClient.js, financial-templates-lib/clients/ExpiringMultiPartyEventClient.js, financial-templates-lib/clients/TokenBalanceClient.js, liquidator/liquidator.js, monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/ContractMonitor.js
This PR refactors the liquidator and collateralization ratio monitor to both use the timestamp that the client last updated to query prices, rather than the current contract time. This is important as it is possible there is a deviation in price between the blockchain query and the price query resulting in inconsistent behavior of the bots.
A few commenting and order changes were also made to continue working towards clean bot code. Additionally, state update logs were also added that were stripped out in the previous PR.
Close #1335
=> Updated bots to use consistant time source

disputer/disputer.js, disputer/index.js, financial-templates-lib/helpers/GasEstimator.js, financial-templates-lib/logger/Logger.js, financial-templates-lib/logger/PagerDutyTransport.js, liquidator/index.js, liquidator/liquidator.js, monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/index.js
This PR adds the additional `warn` level to the Winston monitoring stack. After this refinement our bots have 4 distinct levels of notification as follows:
1. **Debug.** It can be considered a console log. Used periodically to inform status updates of repetitive state changes like polling or no events found. Only viewable on GCE logs. 
2. **Info.** Used to report informative events, like a liquidation/dispute/dispute settlement. These events are noteworthy but don’t require action or acknowledgment from any team member. Viewable on GCE logs and sends a slack message to appropriate channels. 
3. **Warn.** Used to report warning events that might require a response but don't necessarily indicate system failure. Require Acknowledgment from the person on duty, or escalation occurs until the …
=> Added additional logging levels and comment cleanup

core/contracts/financial-templates/demo/DepositBox.sol, core/contracts/financial-templates/implementation/demo/DepositBox.sol, core/test/financial-templates/demo/DepositBox.js
This example will set up a “Checking Account” contract in which the user deposits ETH into the contract and can periodically withdraw ETH corresponding to a desired USD amount. When the user wants to make a withdrawal, a price request is enqueued with the UMA DVM. 
To be used in documentation explaining the flow of our system to a prospective user.
=> Contracts and unit tests for minimal financial template that incorporates the DVM

core/contracts/financial-templates/implementation/ExpiringMultiParty.sol, core/contracts/financial-templates/implementation/FeePayer.sol, core/contracts/financial-templates/implementation/Liquidatable.sol, core/contracts/financial-templates/implementation/PricelessPositionManager.sol, core/test/financial-templates/PricelessPositionManager.js
This PR adds a method called depositTo that allows anyone to make a deposit into anyone else's account. This should enable users to implicitly separate wallets that they use to top-up their positions from more privileged wallets used to do more complex position management.
ExpiringMultiPartyLib bytecode notes:
```
Pre-PR:                                               27 bytes under the bytecode limit.
After adding depositTo:                               70 bytes over the limit.
After removing public variable and re-entrancy check: 12 bytes under the limit.
```
=> Add DepositTo

core/contracts/oracle/implementation/Store.sol
Fixes the rendering on the docs site so the list shows up as a list rather than a single line of text.
=> Update Store docs to fix site rendering

ci/deploy_to_staging.sh
This just means we won't have to manually delete old versions when app engine hits its max and starts causing the deployments to fail.
=> Delete old GAE versions on deployment

.prettierrc, documentation/synthetic_tokens/tutorials/creating_from_truffle.md
The linter breaks `truffle console`. This Pr adds an overide to ignore semicolons on `.md files`
=> Removed and updated linter

documentation/synthetic_tokens/tutorials/creating_from_truffle.md, documentation/synthetic_tokens/tutorials/prerequisites.md
This PR addresses some small formatting issues that made the tutorials difficult to navigate. Specifically, the prettier linter made some sections of code more cumbersome to copy-paste. This PR addresses these issues by using 
```
```
On code blocks that the linter wanted to format incorrectly.
This PR also updates the `prerequisites.md` to tell users to use at least 9 million gas to prevent the creation of an EMP from reverting.
=> Fix javascript formatting in truffle tutorial

financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js
This adds a price feed factory that will generate a price feed from the provided config.
This allows price feed users, like the various bots, to read in a config from a file and pass that config (or some subset of that config) into the `createPriceFeed` factory function to construct a price feed. This means that those bots don't have to do any direct price feed configuration, keeping their code clean of any price feed implementation details.
This is the last prerequisite to injecting the price feed implementations into the bots.
=> Add CreatePriceFeed factory

Dockerfile, financial-templates-lib/logger/PagerDutyTransport.js
This PR adds a `try catch` block around the pager duty message sending function call. This change comes from testing a miss-configured monitor bot where pagerduty locked up the Winston logger. This try catch enables the pagerduty transport to gracefully fail without locking up winston.
=> Better pager duty error handling

monitors/ContractMonitor.js
This PR addresses a bug in the contract monitor module. Previously the wrong block number reference was being used. This PR addresses this.
=> fix error in contract monitor

core/contracts/financial-templates/common/FeePayer.sol, core/contracts/financial-templates/expiring-multiparty/ExpiringMultiParty.sol, core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol, core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, core/scripts/cli/sponsor/showMarketDetails.js, core/scripts/cli/sponsor/transfer.js, core/scripts/cli/sponsor/withdraw.js, core/test/financial-templates/PricelessPositionManager.js, financial-templates-lib/clients/ExpiringMultiPartyClient.js, financial-templates-lib/test/clients/ExpiringMultiPartyClient.js
- The `pfc` function in `FeePayer` has a comment that says “profic from corrution”
- Now that `PositionData` has two request deadlines, consider renaming `requestPassTimestamp` to `withdrawalRequestPassTimestamp`
- The `requestTransferPosition`  comment references a non-existent `newSponsorAddress` parameter
- The `payRegularFees`  comment says it will revert if the fees exceed the `pfc`, but that’s no longer true
- The `ExpiringMultiParty` contract doesn’t have any NatSpec comments.
- The `ExpiringMultiPartyCreator` constructor NatSpec is missing a `@param` for `_timerAddress`
- The `@return` statement of `createLiquidation` only describes one parameter
- The `dispute` function is missing its `@return` statement
- The `PricelessPositionManager` constructor is missing the `@param …
=> Respond to initial EMP audit issues

Dockerfile, README.md
We have deleted the `umaprotocol/voting` docker hub repo in favor of the `umaprotocol/protocol` repo. This PR cleans up some additional docs and comments to ensure consistency with this change.
=> Container Update

disputer/index.js, financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js, liquidator/index.js
The constructor parameters in the `createPriceFeed` have `web3` coming before the `logger`. This is the only js library in all off-chain infrastructure that does not first have the logger come first. This PR corrects this.
=> Change createPriceFeed constructor param order to match other infrastructure

financial-templates-lib/price-feed/CryptoWatchPriceFeed.js
This PR addresses a small typo in the `CryptoWatchPriceFeed` which made running all elements of the infrastructure impossible as the api key could not be read correctly.
=> Fix bug in CryptoWatchPriceFeed

core/scripts/umip-2/1_Propose.js, core/scripts/umip-2/2_VoteSimulate.js, core/scripts/umip-2/3_Verify.js, core/scripts/umip-3/2_VoteSimulate.js
In reusing the voting simulation from UMIP-3, there was a little weirdness due to the failed upgrade, which meant there was an extra proposal in the queue. I removed that weirdness to allow UMIP-2 to use the same code. I'm open to other ways of doing this, but I figured this would cause the least churn.
Side note: to use the vote simulation script, you have to pass in the --repeated flag so it uses the post-UMIP-3 commit hash. I figured that wasn't worth changing.
I'm okay with some of this code being a little janky since we'll likely delete/deprecate it in fairly short order, but curious how others feel.
=> Add UMIP-2 Upgrade Scripts

financial-templates-lib/logger/SlackTransport.js
This PR modifies how the slack bot text formatted handles spreading nested objects. When a key-value pair is passed to Winston the slack transport formatted is meant to spread this text to make it readable from slack. Example usage of the logger is:
```
Logger.info({
at: "Monitor#index",
message: "Monitor started 🕵️‍♂️",
empAddress: address,
pollingDelay: pollingDelay,
priceFeedConfig
});
```
Here the `priceFeedConfig` is an object that the slack formatted should spread to show the contents in slack. Before this PR the formatted would output a message like this:
The problem here is that the `priceFeedConfig` has an object _within_ the object, two levels down. This should be spread accordingly. 
The change in this PR ensures that any level of nested objects are spread. The implementation …
=> Improve slack transport object formatting

scripts/bot-deployment/DeployBotGCP.sh, scripts/bot-deployment/PushBotHotFix.sh, scripts/bot-deployment/UpdateBotGCP.sh
This PR makes specifying environment variables config option with the `UpdateBotGCP.sh` and `PushBotHotFix.sh` scripts. If no configs are specified then the GCP instances will keep their previous configs.
=> Improve gcp scripts to make config file optional

common/VotingUtils.js, core/scripts/Voting.js, core/scripts/cli/voting/commitVotes.js, core/scripts/cli/voting/displayStatus.js, core/scripts/cli/voting/filterRequestsByRound.js, core/scripts/cli/voting/retrieveRewards.js, core/scripts/cli/voting/revealVotes.js
- Adds a library to `VotingUtils` to get voter address, signer address, and contract to send votes to dependent on whether user is using a designated voting proxy.
- Incorporates this into voting CLI tool. Previously, voting CLI did not support voting through proxy.
- Voting CLI now supports retrieving rewards through proxy. This was broken previously because `retrieveRewards` has a different interface in `Voting.sol` vs `DesignatedVoting.sol`. I opted to just call `Voting.retrieveRewards` but needed to pass in the correct `voterAddress`.
- Voting CLI previously did not filter out already-revealed votes, and attempting to reveal an already-revealed vote would throw an error. I filter these out now
- Library is upstream of the AVS tests in `Voting.js` so I fix these
Signed-off-by: Nick Pai …
=> Fix VotingUtils library to integrate DesignatedVoting proxy

scripts/bot-deployment/DeployBotGCP.sh
Providing a service account will allow us to grant specific gcloud privileges to the instance up front, like key access or storage reads.
=> Add service account argument to bot deployment script

common/FormattingUtils.js, common/gckms/GckmsConfig.js, financial-templates-lib/test/price-feed/PriceFeedMock.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/SyntheticPegMonitor.js
This implements methods for checking pricefeed price volatility in the `SyntheticPegMonitor`:
- `checkPegVolatility`: check's medianizer's vol
- `checkSyntheticVolatility`: check synthetic's vol
This adds two configuration params to the monitor: `volatilityWindow` and `volatilityAlertThreshold`. Volatility is calculated as the % difference between the Minimum and the Maximum price over a time range. The time range's most recent time is the monitor's `lastUpdateTime` and the latest time is `lastUpdateTime - volatilityWindow`.
___
Console logs:
```sh
2020-05-19 17:22:23 [debug]: {
"at": "SyntheticPegMonitor",
"message": "Checking synthetic price volatility",
"pricefeedVolatility": "806876552798844232",
"pricefeedLatestPrice": "40059428888888888",
"minPrice": "22170540000000000",
"maxPrice": …
```
=> Implement pricefeed identifier volatility monitor

core/config/identifiers.json, core/migrations/14_deploy_expiring_multi_party_creator.js, core/scripts/local/DeployEMP.js, core/test/financial-templates/ExpiringMultiPartyCreator.js
This changes a few pieces of code to make the creation process faster/simpler:
- Updates the migrations to pre-register the EMP creator with the Registry..
- Updates the deployEmp script with production-y parameters, so very little will need to be changed when deploying to mainnet.
- Removes parts of the deployEmp script that aren't absolutely required to deploying the EMP contract.
- Adds a log message to the deployEmp script that encodes the construction params used for EMP contract. This will be useful when attempting to verify the contract on Etherscan.
=> Streamline EMP Creation process

core/scripts/cli/sponsor/listExpiredMarkets.js, core/scripts/cli/sponsor/listMarkets.js, core/scripts/cli/sponsor/marketUtils.js
The list markets operation was taking a long time when more than a few contracts were deployed, so they were parallelized to make the process a bit faster.
The spinner stop operation was also moved so it keeps spinning until the contract reads are done.
=> Optimize list markets operation in the CLI

common/ServerUtils.js, liquidator/index.js, liquidator/test/index.js, voter-dapp/src/ActiveRequests.js
This adds a blackbox monitor server to the Liquidator. Follow on PR's to add this to other bots. We need to be confident that this is compatible with GCP health check infra.
=> Add Blackbox monitor server to Liquidator bot

core/scripts/cli/sponsor/create.js, core/scripts/cli/sponsor/marketUtils.js, core/scripts/cli/sponsor/transactionUtils.js
This fixes two small issues in the CLI:
- We weren't pulling in the network id correctly from ganache, causing all etherscan links to be "fake-etherscan".
- Passing in larger numbers of tokens caused the BigNumber library to start printing numbers in scientific notation, causing issues elsewhere.
- Etherscan urls using `/contract/` didn't seem to work -- at least not on kovan.
=> Fix minor issues in CLI

scripts/bot-deployment/DeployBotGCP.sh, scripts/bot-deployment/PushBotConfigs.sh, scripts/bot-deployment/PushBotHotFix.sh, scripts/bot-deployment/UpdateBotGCP.sh
This PR:
- Adds a script to push all configs in a directory up to the bot-configs bucket.
- Updates the GCP zone that the bots are deployed in.
- Adds a scope parameter to the deployment script that will allow the bots to access outside services like GCP Storage and GCKMS.
=> Update bot deployment scripts

common/globalTruffleConfig.js
Often when running truffle using GCP the connection will time out. This is despite having a 1gb fiber line but is solely due to slow round trip connection to GCP. Increasing this timeout on truffle makes the connection more consistent.
=> Add timeout to truffle

common/globalTruffleConfig.js, financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/price-feed/UniswapPriceFeed.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/UniswapPriceFeed.js
Add inversion parameter so the UniswapPriceFeed doesn't require a particular ordering of reserve tokens in the Uniswap smart contract.
=> Add invert parameter to Uniswap price feed

core/scripts/cli/sponsor/create.js, core/scripts/cli/sponsor/currencyUtils.js, core/scripts/cli/sponsor/liquidationUtils.js, core/scripts/cli/sponsor/showMarketDetails.js, core/scripts/cli/sponsor/viewLiquidationDetails.js, core/scripts/cli/sponsor/withdraw.js, core/scripts/local/DeployEMP.js, core/scripts/local/DisputeEMP.js, core/scripts/local/DisputeLiquidationEMP.js, core/scripts/local/PushPriceEMP.js, core/scripts/local/liquidateEMP.js, core/scripts/local/withdrawLiquidationEMP.js
Apologies for the big PR, but a lot of these changes depend on each other so it was easier for me to develop on the same branch. Originally I was only working on #1499 but made all of these edits along the way. Many of the changes are new helper scripts to test the sponsor CLI with liquidations, disputes, and withdrawing liquidation rewards.
New features/bug fixes:
- BigNumber config is moved to top of `create.js` so that large number strings are not automatically displayed in scientific format. This caused a bug on line 22: `const minPositionSize = BigNumber((await emp.minSponsorTokens()).toString());` which cannot cast scientific-notation string to `BigNumber`.
- Warn user before creating a position if they do not have enough collateral to create their desired new position.
- …
=> Many fixes to Sponsor CLI 

core/scripts/local/AdvanceEMP.js, core/scripts/local/DeployEMP.js, core/scripts/local/DisputeEMP.js, core/scripts/local/PushPriceEMP.js, core/scripts/local/liquidateEMP.js, core/scripts/local/withdrawLiquidationEMP.js, documentation/synthetic_tokens/tutorials/using_the_uma_sponsor_cli_tool.md
Reflects new scripts added in #1507  and adds explanations to tutorials about why an initial sponsor position must be created before using the CLI locally and how the `minSponsorTokens` contract parameter affects CLI actions.
=> Update EMP tutorials to reflect latest `DeployEMP.js` scripts and other helper scripts

financial-templates-lib/clients/ExpiringMultiPartyEventClient.js, financial-templates-lib/test/clients/ExpiringMultiPartyEventClient.js, monitors/CRMonitor.js, monitors/ContractMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/ContractMonitor.js
Adds `NewSponsor` event tracker to `ExpiringMultiPartyEventClient`.
Fixes bug in this client that sets `this.lastBlockNumberSeen = currentBlock` to `this.lastBlockNumberSeen = currentBlock + 1` so that events in the last block are not double-counted.
Fix bugs in `CRMonitor` and `SyntheticPegMonitor` that attempt to print values from an `undefined` object in cases where the monitors fail to fetch pricefeed data.
Example slack message for `NewSponsor` monitor:
Resolves #1506
=> NewSponsor events monitor + fixing bot error-catching bugs that I ran into

liquidator/liquidator.js, liquidator/test/Liquidator.js, monitors/CRMonitor.js, monitors/SyntheticPegMonitor.js, monitors/test/CRMonitor.js, monitors/test/SyntheticPegMonitor.js
This PR refactors the bots configuration variables to all take in consistently scaled numbers. Before this PR there were multiple ways of representing percentages in configs. `crAlert` in `WALLET_MONITOR_OBJECT` for example was represented by `140` but `volatilityAlertThreshold` in `SYNTHETIC_PEG_MONITOR_OBJECT` was represented as `200000000000000000`. This PR changes the scaling of configurations to all follows one common standard. 
This standard is as follows: 
1) All currency terms are expressed in their number of significant figures; 1 Ether threshold, for example, is represented as 1000000000000000000 (1e18). If a token has less significant figures then it is represented with it's native number of units. 1 USDC, therefore, would be 1000000 (1e6).
2) All non-currency parameters are …
=> Change bot configurations to take in consistantly scale variables

documentation/oracle/economic_architecture.md
This PR fixes an issue with a link rendering in the `Economic Architecture ` documentation. Previously this link rendered like this:
The fix presented in this PR is to use a link shortener, rather than solving the actual issue. This was done as a quick workaround as fixing how the docs interpret this link will be a much longer tailed fix and there was no easy obvious solution.
=> Update economic_architecture.md link error

financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/price-feed/CryptoWatchPriceFeed.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
You don't have to have an API key to make API requests to cryptowatch. For convenience (especially for those using the tutorials), I think it makes sense to make it an optional parameter.
This will also be useful when integrating it into the sponsor cli tool.
Related to #1529.
=> Make CryptoWatch api key optional

financial-templates-lib/clients/ExpiringMultiPartyEventClient.js, financial-templates-lib/test/clients/ExpiringMultiPartyEventClient.js
Adds event tracking for:
- `Deposit`
- `Create`
- `Withdrawal`
- `Redeem`
- `RegularFeesPaid`
- `FinalFeePaid`
Refactors the `NewSponsor` event tracking to cross-reference `Create` events and track collateral/tokens transferred
=> Add events to EMPEventClient that we will need to query to create Daily Report

common/globalTruffleConfig.js
Declaring providers using functions means that all providers will not be constructed on every truffle instantiation. Since the HDWalletProvider seems to poll blocks periodically after its construction, we were previously constructing at least 2 public network providers *per public network* for a total of 8 providers. This means that while running any sort of truffle operation, we had 8 HDWalletProviders constantly polling public networks through infura.
Note: I use a strange singleton construction in this PR because truffle calls the provider constructor method multiple times (6 times on a truffle console initialization). To prevent that from causing over-polling, we only construct the provider on the first call and then return the same provider for all calls after that.
=> Declare providers using functions to reduce Infura polling

ci/deploy_to_staging.sh
This adds the prod deployment to ci. The prod versions that ci deploys *will not* receive traffic until they are manually promoted in GAE. This will allow for a manual release process.
Note: despite these versions not receiving traffic, they are still available at URLs like the following:
```
https://[VERSION_ID]-dot-[SERVICE_NAME]-dot-[PROJECT_NAME].df.r.appspot.com]
```
This could allow us to do prod tests against specific versions before releasing them.
=> Add prod deployment to ci

financial-templates-lib/clients/ExpiringMultiPartyClient.js, financial-templates-lib/test/clients/ExpiringMultiPartyClient.js, monitors/ContractMonitor.js, monitors/test/ContractMonitor.js
Current slack logs do not make it clear whether liquidated collateral is the `liquidatedCollateral` or the `lockedCollateral`:
Liquidator bot's logs print `amountCollateral`, which I broke down into `liquidatedCollateral` and `lockedCollateral`:
ContractMonitor's logs display only `liquidatedCollateral`:
=> Monitor logs to differentiate between liquidatedCollateral and locked collateral

common/FormattingUtils.js, monitors/ContractMonitor.js, monitors/test/ContractMonitor.js
New proposed message for each liquidation detected by `ContractMonitor`:
```
{
at: 'ContractMonitor',
message: 'Liquidation Alert 🧙‍♂️!',
mrkdwn: "<https://etherscan.io/address/0x887f4CB8F229ABf9F7808c78e3f57b4E674349da|0x887...4349d> (Monitored liquidator bot) initiated liquidation for 150.00 (liquidated collateral = 140.00) DAI of sponsor <https://etherscan.io/address/0xE405e4cb525857202324171c008Ec947C6742a6A|0xE40...742a6> collateral backing 50.00 ETHBTC tokens. Sponsor collateralization ('liquidatedCollateral / tokensOutsanding') was 280.00%, using 1.000 as the estimated price at liquidation time. With a collateralization requirement of 150.00%, this liquidation would be disputable at a price below 1.86. tx: <https://etherscan.io/tx/0x78b38f1481b88bc596274e5dea885649c8b239afd1b45d4ac6 …
```
=> Add CR requirement, estimated price at liquidation time, and max disputable price to ContractMonitor reporting of liquidation events

common/globalTruffleConfig.js
This modifies our truffle config to do two things:
- Allow the user to set `CUSTOM_NODE_URL` in the env and point all public networks to a custom node.
- Default to connecting to infura over websockets.
Fixes #1562 
Fixes #1563
=> Add custom node urls and connect to infura over ws

monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/ContractMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/BalanceMonitor.js, monitors/test/CRMonitor.js, monitors/test/ContractMonitor.js, monitors/test/SyntheticPegMonitor.js
This PR refactors the monitor bot to pull the 1) `collateralCurrencySymbol` 2) `syntheticCurrencySymbol` 3) `priceIdentifierName` and 4) `networkId` from the base monitor instance.
Close: #1417
=> Pull EMP parameters from parent in monitor bot

scripts/bot-deployment/DeployBotGCP.sh
This PR overhalls the `./scripts/bot-deployment/DeployBotGCP.sh` to only take in one parameter: the bots name. From this, the script finds an associated service account and pulls down the relevant bot config file. If either the name provided does not match a service account or there is no config for the name provided then the script will not deploy anything. This ensures that the user always deploys an up to date config and that the associated service account is correct.
=> Update bot deployment script to pull config from GCP bucket and check service account

.gitignore, Dockerfile, reporters/SendSlackReport.sh
[Slack API](https://api.slack.com/methods/files.upload) is expected to respond `{ok:true,...}` if the upload was successful, we can verify that. We'll print out file type and size if successful.
New dockerfile requirement:
- Installs [jq](https://stedolan.github.io/jq/) which is `sed` for JSON data
Other update
- Add report to `.gitignore` in case they are not properly deleted (i.e. if script stops for whatever reason)
- log response.json in a local file we can use to debug
=> Programmatically verify file upload success for daily report

common/globalTruffleConfig.js
There was a bug in the provider singleton implementation. `this` was being bound to an object that *looked* the same on every call, but was not persisting the singleton provider (for whatever reason). This meant that each time truffle called the function, it was creating a new provider, which was the opposite intention.
This PR just creates a global variable that's assigned instead. This makes the implementation easier to understand, and I have tested to be sure that the inside of the `if` statements are only hit once.
Note: this *should* decrease the number of eth_getBlockByNumber calls since there won't be 6 providers created on every instantiation.
=> Fix singleton provider

common/VotingUtils.js, core/scripts/cli/cli.js, package.json
Currently: 
- dApp's salt is type Decimal, while CLI's salt is type Hex.
Solution:
- CLI needs to `toString()` its salt to be a decimal.
I also upgraded the [eth-crypto](https://github.com/pubkey/eth-crypto) dependency but this did not affect the encryption/decryption process.  
I tested and verified using the 8 possible commit-reveal user flows on the `test` network:
- Commit on dApp, reveal on CLI
- Commit on dApp, reveal on dApp
- Commit on CLI, reveal on dApp
- Commit on CLI, reveal on CLI
- Commit on dApp, reveal on CLI w/ 2Key contract
- Commit on dApp, reveal on dApp w/ 2Key contract
- Commit on CLI, reveal on dApp w/ 2Key contract
- Commit on CLI, reveal on CLI w/ 2Key contract
Resolves #1472 
=> CLI needs to construct salt the same way that dApp does

scripts/bot-deployment/DeployBotGCP.sh, scripts/bot-deployment/DeployReporterCR.sh
This PR adds a script to enable google Cloud Run containers to be deployed and creates an associated cloud scheduler. This contains the following steps:
1) Pull down the config file for the bot from the GCP storage bucket.
2) Deploy the Cloud Run instance with the config file
3) Fetch the deployed Cloud Run URL for the new instance.
4) Computes the default service account using the GCP project number
5) Creates a scheduler job with the associated URL and service account to run the Cloud Run instance daily @ 8AM UTC.
=> Google Cloud Run deployment script

scripts/bot-deployment/DeployBotMonitorConfig.sh
This PR adds a script that creates a monitor metric and associated alerting policy to send alerts if a winson log is not seen for a given duration. Previously this was a very repetitive and tedious process for each bot deployed. This script greatly simplifies these steps.
=> Winston logging metric creator

scripts/bot-deployment/DeployReporterCR.sh
This PR adds branching logic to the Daily reporter cloud run script to facilitate either creating a new or updating an existing cloud run cron job based on the list of other deployed jobs. 
close #1597
=> Cloud run deployment script branching logic

financial-templates-lib/logger/SlackTransport.js, monitors/SyntheticPegMonitor.js, monitors/test/SyntheticPegMonitor.js
This PR makes three small changes to the synthetic monitor bot:
1) remove the word "High" from volatility alerts as this is redundant and causes the line to wrap 
2) removes white space around the `⭢` in the log message to decrease the line length and
3) removes number formatting on threshold values in the synthetic monitor.
Note that the line length wrapping is a slack restriction and enforces the same length parameters on all devices/platforms, irrespective of how wide the screen is. This change is to ensure that all messages are on one line for consistency.
The previous slack message looked as follows:
After this PR looks as follows:
close #1606
=> Fix volitility alert message

common/FormattingUtils.js, reporters/GlobalSummaryReporter.js, reporters/SponsorReporter.js, reporters/uniswapSubgraphClient.js
I'm not sure this is the most intuitive way to display it, but I'm trying to show the difference between the value in the "period" column versus the previous period, which is the same length as the default "period" but shifted back by one `PERIOD_LENGTH`.
- add helper format modules to add signs to numbers
- remove **current** "net tokens minted" and "net collateral deposited" stats and replace with in-code accounting assertions to make sure they equal `totalTokensOutstanding` and `totalPositionCollateral`, respectively
- fix typos in dispute stats
Resolves #1610 
Example of new delta column:
=> Add delta column to daily reporter, showing difference between current and previous period

.gitignore, lerna.json, package.json
Right now, these are just alternative ways of running `npm install`:
```
yarn
```
or 
```
lerna bootstrap
```
This will allow us to slowly add packages that will be managed by lerna.
=> Add lerna and yarn workspaces

reporters/GlobalSummaryReporter.js
One side effect of this PR was that I realized how bloated the `GlobalSummaryReporter.js` module was getting and how often it repeated the same code of querying event data and filtering it based on the block timestamp. I refactored all of these methods to take in an array of "periods: {label, startBlock, endBlock}", which will go through all of the events once and sum up cumulative stats, while simultaneously adding the event data to one of the relevant periods. The user defines the arrays of periods to use earlier in the call to `generateSummaryStatsTable()`.
Resolves #1609 
New Token Holder stats table appearance (notice the # token holder stat for the specified period):
=> Add token holder # stats for period

documentation/synthetic_tokens/tutorials/liquidation.md
There's a missing instruction to navigate into the core folder before running `npx truffle compile`. Since the root folder doesn't have a `truffle-config.js`, this will fail. Thus I have added an extra step to ` cd core` before running the compile step.
=> Update missing step in liquidator tutorial

documentation/synthetic_tokens/tutorials/liquidation.md
This PR addresses a few small formatting errors in the liquidator bot tutorials. These are as follows:
1) Previously comments did not render correctly in `bash` code blocks with the `#` symbol.
After this PR they look like this:
2) There was an error in formatting a hyperlink. Previously looked like this:
Now looks like this:
3) the section headings hyperlinks were broken. These now work as expected.
=> Fix small formatting errors in liquidator tutorial docs

ci/docgen.sh, documentation/contract.hbs, package.json
Required for #1631. `lerna bootstrap` doesn't generate a binary for solidity-docgen when pulled from git. My guess is that this has something to do with post install scripts not being run, but this is as good a reason as any to move away from using our fork.
Most of these changes just flow from the advice from @frangio in #1046.
=> Move off of solidity-docgen fork

core/scripts/local/DeployEMP.js
- Add `--identifier` flag enabling user to customize EMP's identifier
=> Remove hard coded price identifier from DeployEMP script

scripts/bot-deployment/DeployBotGCP.sh
Currently we cannot deploy a new GCP instance via this script before manually deleting the existing one. This automates the deletion process by first checking whether an image exists already and subsequently deleting it if so.
=> GCP deploy script: delete instance before deploying

financial-templates-lib/helpers/GasEstimator.js
EthGasStation requires an API key from the 1st of July. This is not a big issue and certainly is not a large development overhead to implement. However, it does introduce the need for _all users_ to include an API key in their config. This burden is very irritating. Alternatively, an API could be hardcoded into the code but this is bad practice and could be used until rate limited. 
Rather than adding in an API key parameter to the `GasEstimator.js` module, this PR changes the module to use a different service to estimate gas. This can be seen [here](https://www.etherchain.org/tools/gasPriceOracle).
Fortunately, etherchain & EthGasStation both return objects of the same structure and so minimum code changes were needed to be made. The only real difference is that EthGasStation scales all …
=> Move away from EthGasStation to Etherchain for gas estimations

disputer/index.js, financial-templates-lib/logger/SpyTransport.js, liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js, monitors/ContractMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/SyntheticPegMonitor.js
Due to [UMIP-5](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-5.md) we require the ability to change logging levels for specific events as well as change the behavior in some monitors. 
To accommodate this requirement, this PR introduces a new optional config setting that can be passed into bots. **This config object is currently only applied to the liquidator bot specifically for the `liquidationEvent` log.** An example log override object is shown below:
```
LIQUIDATOR_CONFIG={"logOverrides":{"positionLiquidated":"warn"}}
```
This config will override the position liquidated log from its default `info` to a `warn` level event.
In future, we can choose to add additional overrides as needed. For example, we might want to have a log override in the monitor for specific …
=> Refine logging levels to enable overrides and disable logic

financial-templates-lib/price-feed/UniswapPriceFeed.js, financial-templates-lib/test/price-feed/UniswapPriceFeed.js
Currently, if there is ever an invalid price (i.e. if reserve0/reserve1 == 0 and we attempt to divide by 0), the Uniswap price feed will crash.
In production, this might not be possible, but very possible when testing with the `UniswapMock`
=> Uniswap pricefeed should handle invalid prices in history

disputer/disputer.js, financial-templates-lib/logger/Logger.js, financial-templates-lib/logger/PagerDutyTransport.js, financial-templates-lib/logger/SlackTransport.js
While testing the kovan disputer bot in preparation for a main net test I came across a bug in the slack transport that produced the following error:
This error meant that **no slack message was sent and the bot hung**. The dispute event was fired correctly & pager duty did correctly catch this but it is still a pretty bad bug that it broke the bot and caused the system to freeze with no logs to slack.
This error was as a result of a previously undetected typo in the disputer bot-message string apon creating a dispute. Specifically the id field for a dispute was identified as `disputeId`, where it should have been specified as `liquidationId`. As a result of PR [1527](https://github.com/UMAprotocol/protocol/pull/1527) this implementation became brittle which made the `undefined` value …
=> Patch winston slack logger

financial-templates-lib/price-feed/CryptoWatchPriceFeed.js
Currently, when we fail to parse Cryptowatch's API response, we send the response object as an error via `new Error(priceResponse)`, however we should stringify this so that we can see the error. See below for what the current error log looks like:
=> Stringify CryptoWatch API response for error logs

financial-templates-lib/helpers/GasEstimator.js
Changelog:
- Change Logger level for GasEstimator errors from `error` to `debug` so that if an external API fails (like Etherchain did recently), then it won't keep sending Pagerduty/Slack alerts.
- Add a backup API, etherscan, to fall back to before falling back on default value.
- Update default gas price to be conservatively higher, in line with current safe gas prices of ~50
Questions for @chrismaree @mrice32 :
- Should I make the logs level `debug` or `info`? Note that `info` would print to Slack (but not PagerDuty)
Resolves #1663
=> Handle gas station API failures more gracefully

disputer/disputer.js, disputer/test/Disputer.js
Disputer was failing to detect when a withdraw will fail because of an existing [bug](https://github.com/ethereum/solidity/issues/4840) in `solidity`/`web3`.
=> Disputer should correctly simulate reward withdrawals

reporters/GlobalSummaryReporter.js, reporters/uniswapSubgraphClient.js
Now that we have a Mainnet dispute, I was able to test and patch some bugs displaying the Dispute and Final fee stats
Another bug was that we had an accounting check asserting that `netCollateralDeposited == totalPositionCollateral`. However, the RHS of this assertion should be `PfC`. This is a check that total amount of collateral in the contract is consistent with `PfC`, which includes current liquidations that are not captured by `totalPositionCollateral`.
Finally, I increased the Uniswap subgraph delay parameter to 5 blocks because I noticed an error between the latest block in Infura's mainnet node and the graph. This parameter is used so that if we want to get the current data, for example, we will actually be asking the graph to send us data from 5 (previously 3) blocks behind the …
=> Various Daily Reporter Fixes

documentation/synthetic_tokens/tutorials/mint_tokens_via_etherscan.md
Fixes #1676 
Tutorial should be a little friendlier towards people who want to mint yCOMP now.
I would still like to see:
1. A mention of the "community-developed" frontend so ppl can double check their GCR calculations (but I understand why we might want to leave this out).
2. A link to the Uniswap market for yCOMP, which as of right now is yet to be created. I can pre-compute it but I don't want that to hold up this PR.
=> Update tutorial with yCOMP EMP address

scripts/bot-deployment/DeployJsonScheduler.sh
This simple script is a subset of the functionality in [DeployReporterCR.sh](https://github.com/UMAprotocol/protocol/blob/a9bcb653b70e5615d4a3c6e75845746ae7b26624/scripts/bot-deployment/DeployReporterCR.sh). The point of this script is to make a cloud scheduler POST object that can accept JSON as the body. Importantly **this functionality is NOT exposed in the GCP dashboard** and so you have to make JSON body post scheduler calls from the CLI. 
Once the full hub and spoke implementation is done we should need to only use this script when creating new scheduler cadences. For example if we want a new daily reporter that logs every 6 hours, we would use this script. Otherwise, in the ideal case, there will only be 1 scheduler for each polling frequency.
=> Add simple script for creating a GCP cloud Scheduler with a json body

core/test/financial-templates/Liquidatable.js
This unit test verifies this action as harmless. These are the takeaways:
- Dispute always succeeds because the `requiredCollateral = (tokensOutstanding * settlementPrice * collateralRequirement) = 0`. Even though the liquidated collateral is 0, 0 >= 0 in the check for `isDisputeSuccessful = Boolean(liquidatedCollateral >= requiredCollateral)`. 
- Because dispute succeeds, liquidator pays final fee. This is good behavior since the liquidator initiated a useless price request.
- The disputer can call `withdrawLiquidationRewards()` after the dispute resolves to get back their final fee bond.
- The liquidator and sponsor both cannot call `withdrawLiquidationRewards()` because the contract does not allow them to withdraw 0 rewards.
- The unfortunate side effect is that the liquidation data …
=> Add unit tests documenting what happens when you call `createLiquidation()` with `maxTokensToLiquidate = 0`

financial-templates-lib/price-feed/CryptoWatchPriceFeed.js, financial-templates-lib/test/price-feed/PriceFeedMock.js, monitors/SyntheticPegMonitor.js, monitors/test/SyntheticPegMonitor.js
This error arose from a call to `getHistoricalPrice` from `SyntheticPegMonitor` and crashed the monitor:
There are two things should address this issue
1. `CryptoWatchPriceFeed` should make sure that invalid `this.historicalPricePeriods[x]` are handled correctly.
2. `SyntheticPegMonitor` uses `getHistoricalPrice` to compute historical volatility, but it currently will return `volatility = null` if `getHistoricalPrice(mostRecentTime)===null`. Instead, it should prepare for this error and just use the other price data points within the price window to compute historical vol.
=> Handle bad historical price response from CryptoWatch

financial-templates-lib/logger/SpyTransport.js, liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js
My implementation of this feature changes `queryAndLiquidate()` to take in one parameter `tokenBalanceWei` which is the max amount of tokens it will try to liquidate. It will use this figure to either liquidate the full position, the full balance (in a partial liquidation), or the full balance minus some amount to account for the min sponsor size.
I tested with the bots also:
1. Liquidator has 175 tokens, full position to be liquidated is 350 tokens:
2. Sponsor [requests to withdraw all collateral](https://kovan.etherscan.io/tx/0xb8d7eda0590d9eb8c4510e97eee333e581e4f4b2034eb502364f3334590332ef#eventlog), making it clearly undercollateralized
3. Liquidator bot [partially liquidates](https://kovan.etherscan.io/tx/0x4777962c5ceeaa15bb75fec6f25f4fa3b713503cffda960e875f79d000e0458a#eventlog) …
=> Liquidator bot caller has option to partially liquidate positions

core/scripts/local/getMedianHistoricalPrice.js, financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js
Sample script for getting a median historical price. Uses default price config objects and allows user to specify an `identifier` and `time`.
Example runs:
- Getting a historical price:
```
$(npm bin)/truffle exec ./scripts/local/getMedianHistoricalPrice.js --network mainnet --identifier eth/btc --time 1592952360
ETH/BTC price @ 1592952360 = 0.02525
```
- Requesting an invalid identifier:
```
$(npm bin)/truffle exec ./scripts/local/getMedianHistoricalPrice.js --network mainnet --identifier compusdt
Error: Identifier 'COMPUSDT' not found in defaultConfigs object. Please add to the object to continue. Current available identifiers are ["ETH/BTC","COMPUSD"].
```
- Not specifying a time and defaulting to current time:
```
$(npm bin)/truffle exec ./scripts/local/getMedianHistoricalPrice.js …
```
=> Add price script to get median historical price

disputer/index.js, disputer/test/index.js, financial-templates-lib/logger/SlackTransport.js, financial-templates-lib/price-feed/CreatePriceFeed.js, liquidator/index.js, liquidator/test/index.js
This PR makes the liquidator and disputer bot easier to start up and run. After this change, the `PRICE_FEED_CONFIG` object variable has become optional. If it is not included then the bot will attempt to infer the config from a pre-defined default config list. If it is included, then the bot will join the default with the inferred config using the `createReferencePriceFeedForEmp` added by @nicholaspai yesterday.
This PR is part 1 of 2 for issue #1617. This PR covers the liquidator and disputer bots. A follow-up PR will be for the monitor and reporter bots.
=> Improve liquidator and disputer bot defaults

common/globalTruffleConfig.js, financial-templates-lib/clients/ExpiringMultiPartyEventClient.js, monitors/index.js, package.json, reporters/cloud-run-scripts/CloudResponse.js, reporters/cloud-run-scripts/CloudRunnerHub.js
This PR modifies the Cloud Run hub to "remember" the last block number it ran from. This is done by querying the last block number the hub saw at the start of the loop and then using this parameter as the `STARTING_BLOCK_NUMBER` for the bots. The hub then uses the current block number as the `ENDING_BLOCK_NUMBER`. At the same time the bot records the current observed block number as the last seen block number, ensuring that for the next loop of the hub execution the time has progressed without skipping any blocks.
This ensures that the bots query events from the `STARTING_BLOCK_NUMBER` until the `ENDING_BLOCK_NUMBER`, representing the discrete-time steps the hub has seen.
In order to accommodate this functionality, the `ExpiringMultiPartyEventClient.js` was modified to take in this new …
=> Make Hub and Spoke implementation stateful of last block query

disputer/index.js, disputer/test/index.js, liquidator/index.js, liquidator/test/index.js
Like #1704 these tests should check for "error"-level winston logs, not whether any errors are thrown. In fact, errors should not be thrown because they are caught by a root try-catch.
=> Fix false positive liquidator and disputer "index.js" tests

.circleci/config.yml, scripts/deploy_docs.sh
This PR uses lerna to install dependencies in the docs build script. This fixes the problem in the ci staging deployment, where npm was initiating a full reinstall requiring additional system dependencies that were not present in that docker container.
Note: this was tested by temporarily enabling the deploy_to_staging job to be run in the ci for this PR. That test worked, so I reverted that config update.
=> Fix staging deployment

common/Enums.js, voter-dapp/src/RetrieveRewards.js
1. Fixes #1695.
2. Fixes #1683.
I've tested this locally in ganache, but likely haven't covered *all* edge cases. Please suggest test cases that should be run if you can think of any interesting ones.
Note: this does not handle prevent users from erroneously attempting to retrieve rewards that are expired. However, the default reward retrieval lookback was updated to not show expired rewards by default. This should be fixed in a separate PR.
=> Multiple Fixes to dApp reward retrieval

documentation/synthetic_tokens/tutorials/mint_tokens_via_etherscan.md
Signed-off-by: Adrian Li <li.adrianmc@gmail.com>
=> Fix faulty double-quotes in Etherscan minting tutorial

common/SolidityTestUtils.js, monitors/ContractMonitor.js, monitors/index.js, monitors/test/ContractMonitor.js
Resolves #1688
Unfortunately I have been unable to add a unit test for these changes on local networks because all of the local contracts use the `Testable` contract with manual timing. My changes to `ContractMonitor` assume that the `liquidationTime` for any liquidation event is the block timestamp, which is only true for public networks. (We can't query the liquidation object's `liquidationTime` property because the liquidation is deleted after all rewards are withdrawn, which could immediately after the dispute settlement if the dispute FAILs.)
I ultimately tested on mainnet and focused retrospectively on a resolved dispute.
- This is what the logs now look like for dispute settlement events where a price is available:
- If the price is not available, then this simplified log is shown: …
=> Add details about resolved price requests to ContractMonitor's logs about Dispute Settlements

disputer/package.json, lerna.json, package.json
A few notes:
- The disputer will continue to import packages from across the repo since there's no other way to import those js files.
- I've made the dependencies only include packages that the disputer explicitly requires. All other dependencies will come through cross-dependencies elsewhere in the repo. The only exception to this may be truffle, but it's unclear how we'll run truffle once all the dust settles, so I decided to leave it out for now.
- I kept the package private so we'll avoid publishing it until the entire repo is converted.
Related to #1720.
=> Make disputer an independent sub-package

lerna.json, package.json, reporters/package.json
Two external dependencies are not listed on the root `package.json` but I think these are OK because they look like Node.js library methods: `url` and `child_process`.
Related to #1720 
=> Create /reporters lerna package

disputer/disputer.js, disputer/index.js, disputer/test/Disputer.js, liquidator/index.js, liquidator/liquidator.js, liquidator/test/Liquidator.js
This pull request adds the ability for the bot operator to provide a `DISPUTER_OVERRIDE_PRICE` or `LIQUIDATOR_OVERRIDE_PRICE` to override the default price feed when choosing the preform liquidations or disputes.
Resolves #1448 
Resolves #1702
=> Add price override parameters to liquidator and dispute bots

financial-templates-lib/price-feed/CreatePriceFeed.js, monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/ContractMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/BalanceMonitor.js, monitors/test/CRMonitor.js, monitors/test/ContractMonitor.js, monitors/test/SyntheticPegMonitor.js, monitors/test/index.js
The goal of this PR is to drastically cut down the parameters required to run a monitor bot and to implement aggressive defaulting: **you should be able to run the monitor bot by simply providing the EMP address**. This PR is pretty big as it overhalls all monitor modules config inputs and validations.
**High-level changes are as follows:**
1) Before this PR each monitor module would take in its own config object. These looked like: `CONTRACT_MONITOR_OBJECT`, `SYNTHETIC_PEG_MONITOR_OBJECT`, `WALLET_MONITOR_OBJECT` & `BOT_MONITOR_OBJECT`. This is pretty clunky as there are a lot of custom configs needed. Added to this the structure of each of these configs was not consistent: some are arrays of objects, some are arrays of addresses and some are objects. Lastly, the previous implementation …
=> Decrease monitor bot config requirment

reporters/GlobalSummaryReporter.js, reporters/index.js, reporters/uniswapSubgraphClient.js
Daily reporter was using an older subgraph endpoint
In addition, reporter assumed that Uniswap pair to grab data for was SYNTHETIC_TOKEN - COLLATERAL_TOKEN but this is not the case for yCOMP:
- The yCOMP synthetic uses DAI as the collateral, but the Uniswap pair we care about is yCOMP-COMP
- However, the ETHBTC synthetic uses DAI as the collateral and the Uniswap pair we care about is ETHBTC-DAI
Therefore, I pass a new parameter into GlobalSummaryReporter that allows user to override the Uniswap pair token. We assume that the `GlobalSummaryReporter` prints out data for a pair involving the EMP's synthetic currency (i.e. ETHBTC or yCOMP), but there could be multiple pairs and tokens the synthetic can trade against. By default, we assume that the user wants the pair including the EMP's …
=> Update subgraph API endpoint for daily reporter

core/package.json
This fixes the ci breakage caused by a collision between #1735 and #1729 (I think).
To have access to the buidler binary, the dependencies need to be added to the sub-package (core). They could be removed from the base package.json as well, but as a matter of simplicity, we're holding off cleaning out the root dependencies until the lerna refactor is over.
=> Fix buidler tests

core/buidler.config.js
There was a typo in the `--debug` config changes, so it would fail on startup. The modifications were being added to the incorrect nested object.
=> Fix buidler --debug

core/migrations/14_deploy_expiring_multi_party_creator.js, core/migrations/5_deploy_voting.js, core/migrations/8_deploy_store.js, core/migrations/9_deploy_governor.js
Fixes a small issue in #1735 where `Timer.deployed()` is called on networks where there is no deployed timer, causing the migrations to fail. The net effect is that migrations on non-test networks would always fail.
This PR changes these calls to only happen inside the ternary.
=> Fix timer issue in migrations

.prettierignore
Buidler artifacts were being picked up by prettier and causing errors. This adds two directories that buidler leaves behind to `.prettierignore`.
=> Add buidler artifact directories to prettier ignore

core/config/identifiers.json, core/scripts/local/ConvertWeth.js, core/scripts/local/CreateTokens.js, core/scripts/local/DeployEMP.js, disputer/disputer.js, disputer/index.js, financial-templates-lib/clients/ExpiringMultiPartyClient.js, financial-templates-lib/price-feed/CreatePriceFeed.js, financial-templates-lib/price-feed/CryptoWatchPriceFeed.js, financial-templates-lib/test/clients/ExpiringMultiPartyClient.js, financial-templates-lib/test/clients/TokenBalanceClient.js, financial-templates-lib/test/price-feed/CreatePriceFeed.js, financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js, liquidator/index.js, liquidator/liquidator.js, monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/BalanceMonitor.js, monitors/test/SyntheticPegMonitor.js
EMP deployment and management scripts:
- Add USDETH to identifiers.json list that all get added to IdentifierWhitelist on migration
- Add WETH9 wrapping/unwrapping flow to CreateToken script.
- Add a WETH9 conversion script.
- Update DeployEMP script to use yUSD config details. Updated script so that it adds an identifier to the whitelist if neccessary, and also deals with the WETH9 conversion flow.
Disputer:
- Adds additional details to logs such as disputer's address and data about any "disputable liquidations". Previously, there were no logs detailing disputable liquidations prior to sending out the dispute transaction.
- Collateral approval transaction hash was not parsed correctly from web3.
- Log details about any potential withdrawable disputed liquidations, even before attempting …
=> Monitor bot and EMP deployment script updates made while kovan-"war games" testing for yUSD

core/scripts/identifier-umip/1_Propose.js, core/scripts/identifier-umip/3_Verify.js
This PR expands the `identifier-umip` scripts (used to propose and verify identifier additions) to handle multiple identifiers in the same proposal. Now one can do this by passing the `--identifier` flag multiple times:
```
npx truffle exec ./scripts/identifier-umip/1_Propose.js --network mainnet-fork --identifier USDETH --identifier ETHUSD
```
=> Allow multiple identifiers in the identifier UMIP scripts

core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, core/test/financial-templates/Liquidatable.js
specifically updates `LiquidationCreated` and `LiquidationWithdrawn`
There might be room for one more event param if needed.
this references #1553
=> feat(liquidatable): #1553 add new event params to liquidatable events

core/scripts/creator-umip/1_Propose.js, core/scripts/creator-umip/2_VoteSimulate.js, core/scripts/creator-umip/3_Verify.js
These scripts propose an UMIP for adding a new contract creator to the registry and verify that it was added correctly after execution.
These will be used to propose [UMIP-9](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-9.md).
=> Add scripts to propose new contract creator

core/scripts/collateral-umip/1_Propose.js, core/scripts/collateral-umip/2_VoteSimulate.js, core/scripts/collateral-umip/3_Verify.js
This makes a proposal to add a final fee for the collateral currency and approve the collateral currency.
This will be used to propose [UMIP-10](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-10.md).
Note: this script assumes that the AddressWhitelist address stored in truffle artifacts is the collateral currency whitelist.
=> Add script to enable proposing and verifying new collateral currencies

common/Enums.js
Once a liquidation has expired and the liquidator has withdrawn rewards, the liquidation will be deleted because there are no rewards for other parties remaining. However, the liquidator bot incorrectly translates the ensuing state (state gets reset to 0 once a liquidation is deleted) as "Dispute Failed". 
The subtlety here is that after calling `withdrawLiquidation()` on EITHER a failed-disputed-liquidation OR an expired-liquidation, the state will get set to 0:
See this incorrect log message's "liquidation status" value for example:
Corrected log message here:
=> Explain liquidation status better post-withdrawing rewards

monitors/ContractMonitor.js
=> ContractMonitor: When reporting Liquidation events, get `liquidationTime` from block timestamp not on-chain struct

liquidator/liquidator.js, monitors/BalanceMonitor.js, monitors/CRMonitor.js, monitors/SyntheticPegMonitor.js, monitors/index.js, monitors/test/BalanceMonitor.js, monitors/test/CRMonitor.js
New log level overrides for the following alerts
- collateralThreshold: when a bot's collateral token balance falls below a threshold
- ethThreshold: when a bot's ETH balance falls below a threshold
- crThreshold: when a monitored wallet's CR falls below a threshold
Updated unit tests as well
=> Add log-level overrides to BalanceMonitor and CRMonitor

voter-dapp/src/ResolvedRequests.js, voter-dapp/src/apollo/queries.js, voter-dapp/src/containers/VoteData.js
UMA subgraph interface changed:
- `commitedVotes` now `committedVotes`
-  Round`claimedPercentage` no longer a prop but also no longer necessary since `inflationRate` is available.
Big add here is that we can use the round's queried `inflationRate` and avoid making contract calls in the VoteData container.
Resolves #1769 
=> Patched Voter dApp to work w/ updated subgraph

reporters/GlobalSummaryReporter.js, reporters/uniswapSubgraphClient.js
`pairs` query no loner contains `swaps` object.
=> Patch client for updated uniswap subgraph

core/scripts/liquidity-mining/CalculateBalancerLPProviders.js, core/scripts/liquidity-mining/test/CalculateBalancerLPProviders.js
This PR refactors the Liquidity mining script to make it testable via truffle and adds a set of unit tests to validate its behavior.
Specifically, the script is refactored to have one main entry point `calculateBalancerLPProviders` which calls two subsequent functions: `_updatePayoutAtBlock` and `_calculatePayoutsBetweenBlocks`. These two functions contain the business logic of defining payouts at a given block number and payouts over a range of blocks. These two functions are then tested extensively in this test suite.
This refactor **does not directly test** the `calculateBalancerLPProviders` as this preforms two pieces of logic that are not simple to test:
1) finding a block number from a given timestamp is hard to mock and can be manually validated when the script runs and 
2) the …
=> Liquidity mining unit tests

reporters/GlobalSummaryReporter.js, reporters/index.js, reporters/uniswapSubgraphClient.js
- Allows caller to not have to pass in UNISWAP_PRICE_FEED_CONFIG so that in future we can allow callers to choose to pass in BALANCER_PRICE_FEED_CONFIG for example
- Separates exchange stats from holder stats. Previously they were loaded in same function so not passing in uniswap pricefeed would block holder stats from showing
Reporter with exchange stats:
Reporter without exchange stats:
=> Reporter: add support for other exchange stats besides Uniswap, like Balancer

reporters/GlobalSummaryReporter.js, reporters/SponsorReporter.js, reporters/graphql/umaSubgraph.js, reporters/graphql/uniswapSubgraph.js
This will fix the ABI-incompatibility issue where the reporter cannot query `getPastEvents(LiquidationCreated)` for EMP's with outdated ABI's such as ETHBTC and yCOMP. Moreover, it still works with the yUSD contract. This means that once this PR is merged we can move the ETHBTC and yCOMP reporters to point to `docker/latest` container instead of `docker/abi-patch`.
This is the first PR that will begin the refactoring of the `reporter` to query subgraph data instead of calling `getPastEvents` which is the more efficient approach going forwards.
Additionally, fixes a bug in `SponsorReporter` where collateral in the position was not being reported correctly.
Finally, fixes one other bug in setting the latest block # to query the uniswap subgraph for.
Signed-off-by: Nick Pai …
=> Daily Reporter to query liquidation events from subgraph instead of on-chain past events

common/Crypto.js, common/TruffleConfig.js, core/buidler.config.js, core/contracts/oracle/implementation/Voting.sol, core/contracts/oracle/interfaces/VotingInterface.sol, core/scripts/Voting.js, core/test/oracle/DesignatedVoting.js, core/test/oracle/Governor.js, core/test/oracle/Voting.js, core/test/scripts/Voting.js
BREAKING CHANGE: snapshotting no longer is automatic on first reveal and must be run as a seperate call!
This is a first attempt at implementing solution #4 defined in https://docs.google.com/document/d/11ap5q2ga2OaVIV6MLxpRjzbLZTr0xraUIt2DdfcyzWI/edit#
This introduces a breaking API change, requiring you to verify your signature when snapshot is taken before reveal. Snapshotting no longer happens automatically in the reveal. This could technically be included in reveal, but the combination of the signature being optional for most reveals (since snapshot happens once) and adding signature argument to reveal would require a few other functions changing, meant that it was cleaner to isolate snapshotting. I will leave it up to debate as to what the right design is here. 
Tests have been …
=> feat(voting): #1763 require snapshot EOA validation before running reveal

core/scripts/liquidity-mining/CalculateBalancerLPProviders.js
This PR removes redundant logic from the Balancer liquidity mining script. Previously, the script would try and find the balancer pool based on the provided address. If the user did not provide an address then the script would look for the tokens the pool held. It would then use a different query to find the shareholders.
It turns out that the issue all along was the graph does not support addresses with checksum case. This is why for some pool the query would return the correct balances and for others, it would not. By simply converting the `poolAddress` to a lower case string the query always returns correctly and so the additional roundabout logic that this script had before is no longer needed.
=> Simplify balancer lequidity mining

.circleci/config.yml
**Motivation**
CI was broken due to #1776.
**Summary**
This PR changes the name of the CircleCI cache to one that exists and contains the repo, dependencies, and build.
**Issue(s)**
Fixes #1776.
=> ci: fix broken cache name

reporters/GlobalSummaryReporter.js, reporters/graphql/umaSubgraph.js, reporters/index.js
**Motivation**
#1797
**Summary**
I removed all the `EMPClient` dependency as well as any event querying outside of the `EMPEventClient`.
Runtime decreased from >35 seconds to 5 seconds mostly because we no longer need to call `empClient.update()`
IMPORTANTLY: This temporarily will remove all period-specific data for `summary stats` such as Collateral Deposited for a period (and delta vs previous period). This is because the summary cash flows cannot be sub-divided currently by the UMA subgraph. 
**Details**
- To calculate synthetic token holder count, previously was going through all `Transfer` events and constructing a token holder list. I removed the `Transfer`-event fetching as this was running into our web3 node's rate-limiting. Instead, …
=> Daily Reporter: Remove `EMPClient` dependency and event querying done outside of `EMPEventClient`

voter-dapp/src/containers/VoteData.js
**Motivation**
#1802 
**Summary**
Store `roundInflationRate` as pct like the other pct's
**Issue(s)**
Fixes #1802
=> Voter dApp: round inflation rate should be %

monitors/ContractMonitor.js, monitors/test/ContractMonitor.js
**Motivation**
#1827 
**Summary**
Moved the `liquidationEvents.find(...)` block within the same `try-catch` that attempts to query the DVM's resolved price. I also updated the unit tests to capture situation where EMPEvent client is not updated after a LiquidationWithdrawn event is emitted.
**Issue(s)**
Fixes #1827
=> ContractMonitor: catch error if LquidationCreated is not found for matching LiquidationWithdrawn event

core/index.js, core/package.json, core/test/scripts/index.js
**Motivation**
Once core is deployed, this will allow users to import the contract artifacts, the abis, and the addresses by network.
**Summary**
Simple index.js file was added.
Some notably missing features: browser support and truffle/ethers instantiations. These may be added in the future, but they may end up being unnecessary.
**Issue(s)**
Fixes #1816.
=> core: add basic entrypoint

voter-dapp/src/ActiveRequests.js, voter-dapp/src/ResolvedRequests.js
**Motivation**
Incorrectly implemented logic to determine whether to show the spam switch, previously the check was that if `allPendingRequests >= filteredPendingRequests` which was supposed to check if there were any filtered out requests. This returns a false positive: if there are no price requests on the blacklist, then the condition will always evaluate to true, displaying the spam switch needlessly.
**Summary**
I set a `hasSpamRequests` flag after filtering out non-blacklisted requests. After setting this flag, I then check `showSpamRequests` to determine whether display all requests or only non-blacklisted requests.
=> Voter dApp bug: Only show spam filter switch if there are spam requests on blacklist

reporters/GlobalSummaryReporter.js, reporters/graphql/umaSubgraph.js
**Motivation**
Adds the feature originally removed in #1798 when we started calculating total collateral/synthetics deposited/withdrawn for a given EMP using The Graph data. I didn't realize at the time that you could make queries for a specific block height, which I leverage in this PR.
**Summary**
Optionally pass in a `blockNumber` to the UMA subgraph query which modifies the query to fetch data for a specific block height.
**Details**
Example historical data for the two most recent 2-day periods:
**Issue(s)**
Fixes #1845
=> feat(reporter): Global summary reporter to display historical EMP contract stats for period and deltas between periods

scripts/DeployNode.sh
**Motivation**
Geth is the more popular and stable node client, and having an easy way to deploy a node instance to GCP is valuable for users who don't want to use a node provider service.
**Summary**
Minor updates were made to the deployment script to make it deploy a fairly standard geth node.
**Details**
Note: the current script deploys a pretty beefy instance by default (there's an optional parameter to change this). This helps to avoid syncing issues, but might not be necessary once the node is synced.
The instance size is based on the instances used by the geth team to benchmark for this mode of syncing: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/.
**Issue(s)**
Fixes #1841.
=> feat(scripts): update node deployment script to use geth

core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, core/test/financial-templates/PricelessPositionManager.js
**Motivation**
#1843 
**Summary**
The GCR `require` statement was turned into an OR condition including the current condition (where create CR > GCR) and adding a new one (where resultant position CR > GCR).
**Details**
GCR unit tests updated as well.
I tested a deployment on Kovan of the updated EMPLib and the bytecode deployed fine. The `deployedBytecode` increased by 116 bytes from my local calculation.
**Issue(s)**
Fixes #1843
=> feat(EMP contracts) Create callable if new position CR is above GCR

financial-templates-lib/test/price-feed/BalancerPriceFeed.js
fix(price-feed): #1872 change balancer test to start blocks more in future, also generalize the historical price test
Signed-off-by: David Adams <david@adams.software>
**Motivation**
#1872
**Summary**
Increased time in future which blocks are mined to prevent intermittent collisions. Also generalized test that was failing. 
**Details**
Unable to replicate error locally, will try running CI multiple times.
**Issue(s)**
Fixes #1872
=> fix(price-feed): Attempt to fix intermittent CI issues caused by balancer price feed test

packages/core/networks/42.json
EMPLib and EMP were verified using the `solic-input.json` method, while EMPCreator required me to manually flatten the contract via (`truffle-flattener`),
- EMPCreator: https://kovan.etherscan.io/address/0x8f6e999530787492c62CfA5A8C937A4Be5886A13
- EMPLib: https://kovan.etherscan.io/address/0x9c53d9f4e959b1cd2ee25c45f50aff45dca471ce
- Example EMP: https://kovan.etherscan.io/address/0x834ada34847ff7b9442cf269e0de3091dc7bb895
=> feat(networks): Update EMPLib and EMPCreator addresses on Kovan to those that have been verified on Etherscan

.circleci/config.yml, packages/cli/package.json, packages/common/package.json, packages/core/package.json, packages/disputer/package.json, packages/financial-templates-lib/package.json, packages/liquidator/package.json, packages/monitors/package.json, packages/reporters/package.json, packages/voter-dapp/package.json, scripts/run_release.sh
**Motivation**
#1883
**Summary**
The registry URLs needed to be tweaked in the npm config. Not 100% sure why only npmjs.org works, but this is the URL that's recommended in the docs, so it seems sensible to continue using it.
Note: this also bumps the versions because some versions were bumped in the process of testing this fix. I wanted to bump them one last time so when this PR hits master, it will do a publish to ensure it works as expected.
**Issue(s)**
Fixes #1883
=> build(release): fix ci release script

packages/financial-templates-lib/src/clients/Web3WebsocketClient.js, packages/financial-templates-lib/src/logger/SpyTransport.js, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/liquidator/index.js, packages/monitors/index.js, packages/monitors/test/index.js
**Motivation**
Issue: [1857](https://github.com/UMAprotocol/protocol/issues/1857)
Issue: [1812](https://github.com/UMAprotocol/protocol/issues/1812)
**Summary**
The monitor bot was re-factored to use a custom web3 socket provider enabling re-try logic on failed websocket connections. Additionally, the monitor bot was re-factored to enable execution without truffle.
**Details**
This implementation follows the patterns from the equivalent liquidator bot PR [1856](https://github.com/UMAprotocol/protocol/pull/1856)
=> feat(monitor): Run bot without Truffle and add websocket retry logic

packages/disputer/index.js, packages/disputer/test/index.js, packages/financial-templates-lib/src/clients/Web3WebsocketClient.js
**Motivation**
Issue: [1857](https://github.com/UMAprotocol/protocol/issues/1857)
Issue: [1812](https://github.com/UMAprotocol/protocol/issues/1812)
**Summary**
The disputer bot was re-factored to use a custom web3 socket provider enabling re-try logic on failed websocket connections. Additionally, the disputer bot was re-factored to enable execution without truffle.
**Details**
This implementation follows the patterns from the equivalent liquidator bot PR [1856](https://github.com/UMAprotocol/protocol/pull/1856)
=> feat(disputer): Run bot without Truffle and add websocket retry logic

packages/reporters/src/cloud-run-scripts/SendSlackReport.sh
This PR fixes the hardcoded path issue within the `SendSlackReport.sh` script used to generate daily reports.
It has been tested in production on a temp docker container.
=> fix pathing

packages/cli/src/voting/commitVotes.js, packages/cli/src/voting/filterRequestsByRound.js, packages/cli/src/voting/getResolvedVotesByRoundId.js, packages/common/index.js, packages/common/package.json, packages/common/src/BlacklistedPriceRequests.js, packages/common/src/FormattingUtils.js, packages/common/src/PriceIdentifierUtils.js, packages/common/src/VotingUtils.js, packages/core/scripts/local/SnapshotCurrentRound.js, packages/voter-dapp/src/ActiveRequests.js, packages/voter-dapp/src/ResolvedRequests.js, yarn.lock
**Motivation**
#1870 
**Summary**
We assume that price requests for a given identifier always resolve to the same precision, which is default 18 decimals but can be overridden to a different precision. Therefore, we add a list of identifiers that must resolve to non-18 decimals.
**Details**
[web3](https://github.com/ethereum/web3.js/issues/3169) does not support arbitrary wei precision so I import an `ethersproject` package that handles the `toWei/fromWei` conversion easily by passing in number of decimals to support. This is the same package that [ethers.js](https://github.com/ethers-io/ethers.js/blob/master/packages/units/src.ts/index.ts#L64) uses.
**Issue(s)**
Fixes #1870
=> feat(voter-dapp&voter-cli): Hardcode list of non-18 decimal precision identifiers

packages/common/src/AdminUtils.js
**Motivation**
#1899 parsed price requests via `formatFixed` instead of `fromWei`, which always returns a float whereas `fromWei` sometimes returned ints, particularly for Admin requests. Therefore, the voter dApp incorrectly parses admin votes as "1.0" instead of "1".
**Summary**
`translateAdminStatus` should parse "1.0" votes as YES and "0.0" as NO
**Issue(s)**
Fixes #1870
=> fix(voter-dapp): Parse Admin requests properly

packages/voter-dapp/src/ActiveRequests.js
**Motivation**
Incorrect price stored in cache, this does not affect any on-chain data
**Details**
Need to use `formatFixed` method with `identifierPrecision`
=> fix(voter-dapp): Salt + price cache incorrectly formats saved vote

README.md, package.json
**Motivation**
To help users understand how to work and run commands inside the monorepo.
**Summary**
A few convenient yarn scripts were added to root and the readme was updated and extended to explain how to use the new tooling.
Note: this README includes a shift in how we install packages. Since `npx lerna bootstrap` and `yarn` do the exact same thing when used in a yarn workspaces repo, I've elected to make the default installation method `yarn` for simplicity.
**Issue(s)**
Fixes #1884
=> docs(readme): add lerna and yarn documentation to the README

packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, packages/core/test/financial-templates/Liquidatable.js
**Motivation**
#1911 
**Summary**
Store `settlementPrice` in intermediate var.
**Issue(s)**
Fixes #1911
=> fix(emp-contract): LiquidationWithdrawn settlementPrice emitted correctly.

packages/voter-dapp/src/ActiveRequests.js
**Motivation**
Admin vote shows invalid admin vote by default:
**Summary**
If no vote committed, don't attempt to `translateAdminVote()`
=> fix(voter-dapp): admin votes don't show INVALID ADMIN VOTE before committing a vote

packages/liquidator/index.js, packages/liquidator/src/OneInchExchange.js, packages/liquidator/test/Liquidator.js, packages/liquidator/test/OneInchExchange.js
**Motivation**
issue #1922
**Summary**
The most recent PR [1855](https://github.com/UMAprotocol/protocol/pull/1855) merged in on Friday last week broke production bots due to an incorrect import of truffle artifacts. Artifacts **must** be injected into the models, like everywhere else in the bots. This change meant that bots would **only** work when executing with `truffle test` and would fail if run with `truffle exec ...` or `node ...`.
**Details**
This PR addresses this error. Additionally, there was a subsequent error in how web3 was being imported for utilities that was also addressed.
**Issue(s)**
Close #1922
=> fix(liquidator 1inch integration) incorrect use of artifacts broke production implementation

packages/reporters/src/GlobalSummaryReporter.js
**Motivation**
Daily reporter is blank when both `cumulative` and `period` data is shown.
```sh
┌─────────────────────────────────────────┬────────────┬────────────┬──────────────────────────┬─────────────────────┐
│                 (index)                 │ cumulative │  current   │ 08/25/2020 to 09/01/2020 │ Δ from prev. period │
├─────────────────────────────────────────┼────────────┼────────────┼──────────────────────────┼─────────────────────┤
│          # of unique sponsors           │    322     │     72     │            14            │         +4          │
│          collateral deposited           │            │            │         2,937.70         │     -13,377.19      │
│          collateral withdrawn           │            │ …
```
=> fix(reporter): Currently overwrites some rows in table

packages/financial-templates-lib/index.js, packages/financial-templates-lib/src/price-feed/PriceFeedMockScaled.js
**Motivation**
#1938 
**Summary**
Include priceFeedMockScaled instead of priceFeedMock in your tests and update accordlingly.
For minimal effort you can try in the tests:
```js
const { PriceFeedMockScaled: PriceFeedMock } =  require("@umaprotocol/financial-templates-lib");
// sorry for long args
// decimals by default = 18
priceFeedMock = new PriceFeedMock(undefined, undefined, undefined, undefined, decimals);
// when setting price you must not convert toWei but provide in eth. the mock will convert it for you.
//New mock takes a decimal value, and when setting price provide it as a string in ETH.
// from  
priceFeedMock.setHistoricalPrice(toWei("1.75"));
// to 
priceFeedMock.setHistoricalPrice("1.75");
```
**Issue(s)**
Fixes #1938
=> feat(pricefeed): add pricefeedmockscaled which can use non 18dec

.circleci/config.yml, package.json, packages/common/src/TruffleConfig.js, packages/financial-templates-lib/src/clients/Web3WebsocketClient.js, packages/liquidator/package.json
**Motivation**
This PR fixes a few issues in the truffle config:
- The nodeUrl does not correctly resolve when not using a custom node.
- Providers are not set up as functions for local networks, so they wouldn't work with scripts that are run as node processes.
- A bunch of local networks are no longer used or required (as far as I can tell).
test-fork was also moved to its own command and ci job since it requires its own ganache instance.
**Summary**
Truffle config was updated to correctly resolve the node url internally and for files that import it.
Providers are now all functions. There are no `host` and `port` fields.
Many local networks were removed.
**Issue(s)**
Fixes #1888 
Fixes #1909.
=> fix(truffle): correct node url resolution in truffle config

packages/financial-templates-lib/src/price-feed/PriceFeedMockScaled.js
**Motivation**
https://github.com/UMAprotocol/protocol/issues/1941
**Summary**
Uses an imported Web3 (which doesn't contain a provider, but _does_ contain utils) rather than a global one.
**Issue(s)**
Fixes #1941
=> fix(price-feed): fix import issue in PriceFeedMockScaled

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
**Motivation**
#1933.
**Summary**
The cryptowatch price feed was slightly reorganized to throw errors when the api breaks.
Note: the two api calls were also parallelized to slightly speed up execution.
**Issue(s)**
Fixes #1933
=> feat(price-feeds): refactor cryptowatch to throw errors to allow retries

packages/common/src/TruffleConfig.js
**Motivation**
Truffle config changes caused tests to be flaky.
**Summary**
Mirrored the way truffle initializes their http provider in the config, so our initialization would match theirs.
For reference: https://github.com/trufflesuite/truffle/blob/813664a0c23c2ed8af423c1163a1cddb6d8fad7e/packages/provider/index.js#L30.
**Issue(s)**
N/A
=> fix(truffle-config): fix flaky test provider

packages/core/scripts/local/DeployBalancerMock.js, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
BalancerMock used to test SyntheticPegMonitor
`createReferencePriceFeed` config changed so that user doesn't have to specify a MEDIANIZER_PRICE_FEED `.env` var if they are running a bot against an EMP with the USDBTC identifier
=> fix(emp-renbtc): add balancerMock and USDBTC reference pricefeed

packages/core/scripts/local/DeployEMP.js, packages/disputer/index.js, packages/disputer/src/disputer.js, packages/disputer/test/index.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/liquidator/index.js, packages/liquidator/test/index.js, packages/monitors/src/BalanceMonitor.js, packages/monitors/src/CRMonitor.js, packages/monitors/test/BalanceMonitor.js, packages/monitors/test/CRMonitor.js
**Motivation**
1) BalanceMonitor should report collateral currency alerts with correct decimal conversion
Follow up to #1947 
2) CRMonitor should take requested withdrawal amounts into account when determining CR ratios
3) Liquidator and Disputer should infer decimals for returned prices from pricefeed from collateral currency
=> fix(monitors): bugs related to decimal conversion and one CR monitor requested-withdraw oversight

packages/financial-templates-lib/src/price-feed/BalancerPriceFeed.js, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/utils.js, packages/financial-templates-lib/test/price-feed/BalancerPriceFeed.js, packages/financial-templates-lib/test/price-feed/utils.js
**Motivation**
#1955 
**Summary**
Fixes some API issues and bugs with the balancer price feed that came up during wargames testing.
Additionally default balancer lookback to 0 blocks, and update block finder to add a single block even if its before age, so there is at least one. 
**Issue(s)**
Fixes #1955
=> fix(price-feed): fix age pruning, toBN conversions and param check

packages/voter-dapp/src/DrizzleLogin.js
**Motivation**
#1962 
**Summary**
Added some logic to detect if web3 exists by checking the window.ethereum object. If nothing found it will default to a button which tells user to get metamask. If metamask is found, it will show the standard login button. 
**Details**
This is what the user sees if metamask is not installed after this change. 
**Issue(s)**
Fixes #1962
=> fix(voter-dapp): direct user to download metamask if web3 is not detected

packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
**Motivation**
API Key wasn't being applied because the capitalization of the query param was incorrect.
**Summary**
Fixed the capitalization.
**Issue(s)**
N/A
=> fix(cryptowatch): fix cryptowatch price feed api query param

packages/common/src/TruffleConfig.js
Small bug in the truffle config where `argv` is not imported resulting in errors in latest docker configs in serverless environment.
=> fix(truffle-config) include required argv import

package.json, packages/core/package.json, packages/liquidator/package.json, packages/liquidator/test-fork/OneInchExchange.js, yarn.lock
**Motivation**
#1977.
**Summary**
- Updated the ganache version because the existing version was crashing when trying to estimate gas.
- The one inch fork tests were broken, so some fixes were necessary to get them passing again.
- The truffle command needed to be changed to take in a list of files because passing in a directory doesn't work (and fails silently).
- I also moved the ganache dev dependency up to root because it's useful everywhere, not just core.
**Issue(s)**
Fixes #1977
=> fix(tests): fix liquidator fork tests so they run correctly in ci

packages/monitors/index.js, packages/monitors/src/ContractMonitor.js
**Motivation**
Small PR that fixes [1980](https://github.com/UMAprotocol/protocol/issues/1980) to enable additional log overrides for new sponsor created events.
**Summary**
Adds an additional log override for `newPositionCreated` to quieten this alert.
**Issue(s)**
Fixes #1980
=> feat(monitor-bot) Additional override levels on new sponsors created

.circleci/config.yml
**Motivation**
`test_fork` ci job seems to be very flaky because the estimate gas calls are eating up large amounts of memory.
**Summary**
Add a node env variable for the ganache instance on that job to increase it's memory to 4 gigs.
**Issue(s)**
N/A -- issue hasn't been reported.
=> ci: fix fork flakiness by adding node mem

packages/disputer/index.js, packages/liquidator/index.js
**Motivation**
Liquidator and Disputer log their decimals every time they boot. This is noisy in the serverless bots where they spam on every loop:
**Summary**
Simply change the logging level on creating loggers.
=> feat(liquidator/disputer) change decimal logging level

Dockerfile, packages/core/scripts/severless-cloud-run/CloudRunHub.js, packages/core/scripts/severless-cloud-run/CloudRunSpoke.js
**Motivation**
issue: https://github.com/UMAprotocol/protocol/issues/1875
**Summary**
This PR uses the GitHub API to pull config files directly when executing the spokes process from the hub.
**Details**
This PR adds an option setting within the `HUB_CONFIG` used to parameterize the GitHub calls. An example config that pulls settings from github, uses GCP to run the spoke and stores last queried block number on GCP looks as follows:
```
HUB_CONFIG={"configRetrieval":"git","gitSettings":{"organization":"UMAProtocol","repoName":"bot-configs","accessToken":"GIT-ACCESS-TOKEN"},"saveQueriedBlock":"gcp","spokeRunner":"gcp"}
```
This PR also bumps the docker version to use node 14 to enable the `?.` syntax used in a few places.
**Issue(s)**
First PR addressing #1875. Subsequent PRs will update …
=> feat(serverless-bots) pull configs from github

packages/core/scripts/severless-cloud-run/CloudRunHub.js
**Motivation**
Previously, the hub would log all information returned from the spokes within one large log. This is great for debugging within GCP. See the screenshot below where you can see the top part of a returned log from the hub, including the start of the output from the spokes:
An issue with this is that all messages sent to the Winston transport with `error` or `info` get sent to slack. This log message is way too big to fit within slack and infact exceeds the ~5000 char limit on the slack webhook.
**Summary**
As a result, this PR changes how the logging works at the resolution of a failed hub call to generate two logs: 
1) a detailed log that can be read in from GCP, the `debug` log level. This log contains all returned values.
2) a less detailed log that can be read from slack, …
=> fix(serverless-hub) winston return values from hub to slack transport

packages/cli/cli_entry.sh
**Motivation**
CLI fails to startup when installed as a package because npm bin doesn't do dynamic resolution of the truffle dep.
**Summary**
Use `npx` instead. This was tested by modifying the installed package.
**Issue(s)**
N/A issue was never reported.
=> fix(cli): fix cli startup when installed as a package

packages/common/src/TruffleConfig.js
**Motivation**
The fork tests are still failing after https://github.com/UMAprotocol/protocol/pull/1993 failed to fix the issue.
**Summary**
This adds a hardcoded gas limit to the mainnet-fork network so no gas estimation is required.
**Issue(s)**
N/A
=> ci: fix fork tests by including a hardcoded gas amount

packages/core/contracts/common/interfaces/TransactionBatcher.sol, packages/core/scripts/local/ClaimAllRewards.js
**Motivation**
We needed to claim all rewards on behalf of voters in a more efficient way due to the increase in the number of voters since the last Voting.sol upgrade.
**Summary**
To retrieve rewards on behalf of many voters' at once in a gas efficient way, I decided to slightly optimize the ClaimAllRewards script to include use an on-chain transaction batcher contract and parallelize infura calls. Note: once the number of voters ~doubles, this script may need to be set up to split the batch into multiple transactions to avoid hitting the block gas limit.
**Issue(s)**
N/A
=> feat(scripts): add script to batch reward retrieval for many voters at once

packages/voter-dapp/src/apollo/queries.js, packages/voter-dapp/src/containers/VoteData.js
**Motivation**
Ever since the subgraph incorporated multiple Voting contracts in this [PR](https://github.com/UMAprotocol/uma-subgraph/pull/6), a query for `priceRequestRounds.identifier` has failed and thrown this error:
```
{
"errors": [
{
"locations": [
{
"line": 3,
"column": 17
}
],
"message": "Null value resolved for non-null field `identifier`"
},
...
```
I believe this is possibly a problem where price requests for an older Voting contract are not found on the newer Voting contract. I'm currently working with a subgraph developer to fix this issue, but in the absence of a fix this PR will change the query to fetch the price request's identifier via a different method.
You can grab identifier from the `priceRequestRounds.id`, which is …
=> fix(voter-dapp) UMA subgraph query for `priceRequestRounds.identifier` fails

packages/core/scripts/local/getMedianHistoricalPrice.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/src/price-feed/MedianizerPriceFeed.js
**Motivation**
#2054
**Summary**
Add optional `debug` parameter to Medianizer `getHistoricalPriceFeed` method to print out the name of the exchanges and the specific prices from which a median is derived from.
**Details**
This should not affect any of the liquidator/disputer bot behaviors.
**Issue(s)**
Fixes #2054
=> improve(median-pricefeed-script) Add helpful logs to medianizer pricefeed output

.circleci/config.yml
**Motivation**
`test_fork` job fails very often due to ganache running out of memory. This is caused by a bug in ganache: https://github.com/trufflesuite/ganache-cli/issues/570. We see it during estimateGas calls.
**Summary**
Removed the job from the circleci config.
**Issue(s)**
N/A
=> ci(tests): remove test_fork job because it consistently fails

packages/core/buidler.config.js, packages/core/package.json, yarn.lock
**Motivation**
Right now it's hard to see how much gas our PRs add and the function scoping within tests. https://github.com/cgewecke/buidler-gas-reporter offers a plugin to buidler to tell you how much gas each function uses within tests. This PR adds this.
**Summary**
After running tests the following output is generated:
This shows the gas used on different method calls & the gas used in deploying contracts. In the future we can integrate it into CI to send gas reports in a similar way to coveralls as documented here https://github.com/cgewecke/eth-gas-reporter#continuous-integration-travis-and-circleci
**Details**
Added a new packaged and one-line change in buidler config.
=> feat(buidler-tooling) Added gas reporter

packages/core/contracts/common/implementation/FixedPoint.sol, packages/core/contracts/common/test/SignedFixedPointTest.sol, packages/core/contracts/common/test/UnsignedFixedPointTest.sol, packages/core/test/common/SignedFixedPoint.js, packages/core/test/common/UnsignedFixedPoint.js
**Motivation**
To represent negative funding rates, we need to be able to use signed fixed point numbers.
**Summary**
The fixed point library was expanded to have a `Signed` type with similar functions to the Unsigned type.
Note: I changed the architecture of the tests a bit to avoid manually entering obvious checks that can be verified by comparing against standard js comparisons/arithmetic.
**Issue(s)**
Fixes #2101.
=> feat(contracts): add signed fixed point

packages/core/contracts/financial-templates/common/FeePayer.sol, packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/funding-rate-store/interfaces/FundingRateStoreInterface.sol, packages/core/contracts/financial-templates/funding-rate-store/test/MockFundingRateStore.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol, packages/core/contracts/financial-templates/test/FundingRateApplierTest.sol, packages/core/scripts/local/CalculateContractBytecode.js, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
Integrate SignedFixedPoint into the FundingRateApplier and FundingRateStore to make all funding rates centered at 0. Please give feedback here -- let me know if you think this implementation decision doesn't make sense. IMO, it makes the funding rates and the math easier to reason about.
**Summary**
In theory, this should've made the computations simpler. In practice, the inclusion of the new fixed point type and methods increased the bytecode size substantially (600 bytes or so). To make this work, I reworked some areas of the contract to reduce the bytecode.
I also reworked the inheritance structure so that FundingRateApplier inherits from Testable and doesn't store the Timer locally (the current logic was slightly broken as a 0x0 Timer address would've made it fail in …
=> feat(pmp): integrate signed fixed point into funding rate applier

packages/core/scripts/serverless-orchestration/ServerlessHub.js
**Motivation**
GCP sometimes returns flaky errors when calling GCP `datastore`. This occurs when reading to and writing from the last used blocknumber for the monitor bot & normally produced the following error:
The issue is currently discussed on GCP GitHub issues here: https://github.com/googleapis/nodejs-datastore/issues/679
For now, this PR adds in a small change to the monitor hub to wrap the data retrieval and stage for the block number within re-try logic to try and mitigate this error. This is **not** a long term fix but aims to make the error less irritating in the interim until there is an official fix for GCP data store within GCP cloud run.
**Summary**
Adds `async-retry` logic to the datastore module.
=> feat(serverless-hub) Added re-try logic to gcp calls

packages/core/scripts/serverless-orchestration/ServerlessHub.js
**Motivation**
https://github.com/UMAprotocol/protocol/pull/2111 yesterday introduced a small bug in the hub wherein by not returning the nested value within the retry logic. The PR has been tested in production with a hot-fix docker container and has been validated to work as expected.
**Summary**
Adds a `return` to the value retrieved from GCP data store. This PR also expands the error message a bit by showing the underlying `configObject` & `lastQueriedBlockNumber` returned by the function.
=> fix(serverless-hub) retry logic bug

.circleci/config.yml
**Motivation**
Coverage is failing.
**Summary**
Just changed the node version in ci to be locked on 12.
**Issue(s)**
N/A
=> ci: lock node version at 12

Dockerfile
**Motivation**
locks node version in docker in accordance with PR https://github.com/UMAprotocol/protocol/pull/2135
**Summary**
Locks docker node version for consistency.
=> docker: lock node version at 12

packages/financial-templates-lib/package.json, packages/financial-templates-lib/src/logger/SlackTransport.js
**Motivation**
https://github.com/UMAprotocol/protocol/issues/2121
Previously the slack transport was limited to sending slack messages no larger than 3500 chars due to a limitation in the slack webhook API. If a message was sent to the API larger than this limit then the transport would fail silently. Normally, this was never an issue as the usage of the Winston logger than would send slack messages is conscious of the size as we are always consistent to not send massive error messages. 
However, this is not always going to be a fair assumption that messages are less than this limit. For example, https://github.com/UMAprotocol/protocol/pull/2118 could produce a slack message that exceeds this limit if the number of bots running is fairly high and they all error out at the same time. …
=> improve(slack-transport) remove upper bound on slack message length

packages/financial-templates-lib/src/price-feed/MedianizerPriceFeed.js
**Motivation**
The `MedianizerPriceFeed.js` implementation does not run batches of calls in parallel. This PR replaces the for loop + await syntax with a Promise.all & map.
**Summary**
Small 1 liner change to speed up pricefeed execution.
**Details**
=> improve(medianizer-price-feed) make update method parallelized

packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol, packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js
**Motivation**
#2149 
**Summary**
Anyone can call `withdrawLiquidation` now, although it will revert if there are no rewards to disperse. It will pay out rewards owed to the liquidator, sponsor, and disputer.
The `LiquidationWithdrawn` event is also changed to include more details about all of the payments. Previously it was only emitted to display data about the caller's withdrawal.
This reduces the contract bytecode by ~400 bytes because it gets rid of an if-else branch, previously determining whether the caller was the sponsor, liquidator, or disputer.
**Issue(s)**
Fixes #2149
=> refactor(perp-liquidatable) Withdraw dispute/liquidation rewards in one transaction instead of multiple

packages/affiliates/apps/CreateDataSet.js, packages/affiliates/createdataset.example.js, packages/affiliates/libs/bigquery.js, packages/affiliates/libs/datasets.js, packages/affiliates/package.json, packages/affiliates/test/e2e/README.md, packages/affiliates/test/e2e/datasets.js
**Motivation**
#2140
**Summary**
This adds a library file called `datasets` which is a collection of modules to generate data set files from bigquery/coingecko and save them to disk in an organized way. This can then be read out through the "mocks" which reconstruct the data from the file. 
Some effort has been put into reducing the filesize for the block list as it will be stored as comma separated values.
This adds a new app called "CreateDataSet" which takes in a configuration file found in createdataset.example.js. 
End to end tests have also been added which are ignored by CI to test the dataset functionality. This can be expanded on in the future as we add more apps/scripts.
**Issue(s)**
Fixes #2140
=> feat(affiliates): improve dataset generation and mocking libraries

packages/core/scripts/local/HistoricalPriceRequests.js
**Motivation**
We might want to display this data on an UMA client.
**Summary**
Queries all `PriceRequestAdded` events and successively filters out non-Admin and non-Expiry requests.
**Details**
Example run:
```sh
yarn truffle exec ./packages/core/scripts/local/HistoricalPriceRequests.js --network mainnet_mnemonic
yarn run v1.22.10
$ /Users/nicholaspai/UMA/protocol/node_modules/.bin/truffle exec ./packages/core/scripts/local/HistoricalPriceRequests.js --network mainnet_mnemonic
Using network 'mainnet_mnemonic'.
There are currently 0 unresolved non-admin price requests.
There have been 3 non-expiry price requests.
✨  Done in 19.04s.
```
=> feat(scripts) Add script to return non-expiry, non-admin price requests

packages/affiliates/apps/CreateDataSet.js, packages/affiliates/apps/DeployerRewards.js, packages/affiliates/libs/affiliates.js, packages/affiliates/libs/models.js, packages/affiliates/test/mocha/affiliates.js
**Motivation**
#2171
**Summary**
- adds extra data to allow for "siloing" of rewards per emp
- also adds start / end block timestamp and numbers
**Issue(s)**
Fixes #2171
=> feat(affiliates): add extra data to deployer reward results

ci/run_slither.sh
**Motivation**
Fix the slither ci job, now that the executable is updated in the docker image.
**Summary**
try-catches are not handled correctly by slither -- see https://github.com/crytic/slither/issues/511, so that check needed to be disabled. This also re-enables the locked ether check and set slither to not analyze test files.
**Issue(s)**
N/A
=> ci(slither): fix slither ci job

.circleci/config.yml
**Motivation**
ci is failing due to multiple solidity versions being compiled twice.
**Summary**
Truffle is finding absolute paths in our previously published artifacts and looking for them in ci, which causes it to find a second set of contracts that have a different (newer) version. To keep it from doing this, we basically just move the protocol dir in the test job to disrupt these absolute paths.
**Issue(s)**
N/A
=> ci: fix double compilation target issue

packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol, packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js
**Motivation**
#2219 
**Summary**
Builds a new `ConfigStore` on each `createPerpetual()` call. `createPerpetual()` now takes an additional `ConfigSettings` param for default config setting values.
**Details**
Follow up PR will add the `ConfigStore` address to the Perpetual's constructor params and read from the `ConfigStoreInterface` settings such as reward rate, proposer bond pct, etc.
**Issue(s)**
Fixes #2219
=> feat(perpetual): Create ConfigStore to house mutable perpetual params (upgradeable after timelock)

.circleci/config.yml
This PR just clears the dep cache which seems to fix the sporadic ci errors.
=> ci: clear dependency cache

packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol, packages/core/test/financial-templates/expiring-multiparty/Liquidatable.js, packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
This PR points the EMP at the OptimisticOracle for settlement rather than the DVM directly. This will allow settlement to be much faster (potentially 2 hours).
**Summary**
Some notes:
- The payout from the contract's perspective is the same, as it now offers a reward for resolving the request that is equal to the final fee.
- This adds an interface for the OptimisticOracle so other contracts don't need to import the entire contract.
**Issue(s)**
N/A
=> feat(emp): replace liquidation and settlement logic from DVM to optimistic oracle

packages/core/scripts/local/DeployEMP.js
**Motivation**
This script allows the user to call a deployed EMPCreator contract to deploy a new EMP. This script actually successful sends a `createExpiringMultiParty()` transaction because the EMPCreator ABI has not changed from the deployed ABI. However, the call to `web3.eth.abi.encodeParameters(ExpiringMultiParty.abi[0].inputs, [empConstructorParams])` fails:
According to the [web3 docs](https://web3js.readthedocs.io/en/v1.2.6/web3-eth-abi.html#encodeparameters), `encodeParameters` encodes function parameters for a specific contract ABI. `.abi[0]` references the constructor function for the EMP and `.inputs` matches the user's desired constructor params with the constructor params. This line fails because the EMP ABI available to scripts …
=> bug(deploy-emp): Fix EMP ABI to display constructor params

packages/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol, packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.js
**Motivation**
#2233 
**Details**
Allows deployer to specify a FPLib when deploying a new EMP. Previous behavior would default all EMP's to not using a FPLib, which isn't a major bug but doesn't take advantage of the FPLib contract param.
**Issue(s)**
Fixes #2233
=> bug(emp-creator): add financialProductLib address to deployment params

packages/affiliates/apps/DeployerRewards.js, packages/affiliates/libs/affiliates.js, packages/affiliates/test/mocha/affiliates.js, yarn.lock
**Motivation**
#2254 
**Summary**
This adds a fallback function for getting synthetic prices. Changes the api internally, each synthetic price now gets a "calcValue" function with it, to convert it to usd.  If synthetic price feed fails it will fallback to coingecko feed. Tested with uGas and did a basic sanity check vs renbtc dec contract.
**Issue(s)**
Fixes #2254
=> feat(affiliates): add coingecko synthetic price fallback and calculator

packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js, packages/core/test/financial-templates/perpetual-multiparty/Perpetual.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2228
**Summary**
TODO: Determine if we should set reasonable limits on these time bounds.
This adds 100 bytes of bytecode to `PerpetualLib`.
**Issue(s)**
Fixes #2228
=> improve(perpetual) move proposal time bounds into config store

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
#2266.
**Summary**
Limit optimistic oracle requests to right now or the past. No future requests should be allowed.
**Issue(s)**
Fixes #2266
=> fix(optimistic-oracle): add future time require to optimistic oracle

packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js, packages/core/test/financial-templates/perpetual-multiparty/Perpetual.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2259 This enhances the Perpetual's economic security by allowing the Perpetual contract deployer to set funding rate bounds via timelock.
Changes:
- Adds config params to limit the range of possible funding rates to propose. This bounds a dishonest proposer's PfC
- Remove bounds from proposer bound, which can be changed to limit a proposer's PfC based on the funding rate.
- Remove future time limit from proposer timestamp, OptimisticOracles must be in the past starting with #2267
**Issue(s)**
Fixes #2259
=> improve(perpetual): Modify ConfigStore constraints and params

packages/affiliates/libs/affiliates.js, packages/affiliates/libs/contracts.js, packages/affiliates/libs/mocks.js, packages/affiliates/libs/models.js, packages/affiliates/libs/processors.js, packages/affiliates/scripts/example-dataset-playback.js, packages/affiliates/test/mocha/affiliates.js
**Motivation**
#2175 
**Summary**
This adds some very basic tests based on easy to reason about scenarios
- scenario 1: 2 emps and only 1 has had a balance: 100% of rewards go to emp with balance
- scenario 2: bunch of emps, and 2 have equal balance: 50% of rewards get split between emps with balance
There is some extra code here around mocking libraries which did not end up getting used. It was too complicated to mock on chain transaction data with custom values. 
There were a bunch of nasty merge issues in the tests/mocha/affiliates. I will leave a comment on the only part that changed.
**Issue(s)**
Fixes #2175
=> improve(affiliates): add some basic test cases to validate payout logic

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
Dev mining for Mario.cash requires the BCH-BTC default price feed. This PR adds this to DefaultPriceFeedConfigs.js
**Summary**
SImply adds the price feed. This feed follows [UMIP-23](https://github.com/chicfilabae/UMIPs/blob/549bf9cb37558bcd77cb6db44661ad9c9910ef32/UMIPs/umip-23.md)'s implementation details.
=> feat(default-price-feed) Add BCH-BTC Default price feed

packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/test/FundingRateApplierTest.sol, packages/core/test/financial-templates/common/FundingRateApplier.js
**Motivation**
#2282
**Issue(s)**
Fixes #2282
=> improve(funding-rate-applier): Replace NewFundingRateMultiplier event with FundingRateUpdated

scripts/DeployNode.sh
**Motivation**
Add minor improvements to the geth deployment script.
**Summary**
Changes the http and ws port to a nonstandard port to help avoid port scanners from hitting our node. Also adds a tags the instance as an "http-server", which by default opens port 80, but can be customized to include additional ports in the firewall.
**Issue(s)**
N/A
=> improve(node-deploy): update node deployment script

packages/core/contracts/financial-templates/common/FeePayer.sol, packages/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol, packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiParty.js, packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.js, packages/core/test/financial-templates/expiring-multiparty/Liquidatable.js, packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
We closed #2283 after deciding that `gulp()` addresses the original problem that `trimExcess()` was supposed to solve, that of frozen collateral currency in the contract. With `gulp()` added, `trimExcess()` only addresses the additional concern of non-collateral currency frozen in the contract, which we deem unnecessary to address. 
For the sake of consistency between EMP and Perp interfaces, this PR removes `trimExcess` from the EMP and adds unit tests highlighting some "edge" cases for `gulp()` functionality.
Additionally, I have highlighted a "flash gulp" known vulnerability that the team has chosen to ignore in [this document](https://docs.google.com/document/d/19-BbHWfbdCRyDCxPTGr8fSla5zKWmqUbmQetkiVB4i4/edit).
=> improve(fee-payer) Remove trimExcess from EMP and add gulp edge case unit tests

packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
**Problem:**
In the createPerpetual function of the PerpetualCreator contract, the CreatedConfigStore event is emitted without the emit keyword.
Since Solidity v0.4.21, the emit keyword has been recommended to distinguish events from other function calls.
**Solution in this PR**
The `PerpetualCreator` is updated to follow the correct specification by using the `emit` keyword.
=> fix(dec-2020-audit): [L05] Event missing emit keyword

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
The Optimistic oracle allows anyone to propose a price or dispute a proposal on behalf of the zero address. Since the state of the incentive mechanism is partially determined by whether the proposer or disputer addresses are non-zero, this won’t update the state machine, but it will set variables and emit events prematurely. For example, a client may incorrectly react to a DisputePrice event even though the dispute is not recognized by the oracle. Consider restricting the proposePriceFor and disputePriceFor function parameters to non-zero participants.
**Summary**
Adds 2 require statements in the appropriate functions and adds a tests to ensure calls fail when passing 0x0 address.
=> fix(dec-20-audit): [L11] Propose or Dispute a price from the zero address

packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol, packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js, packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2307
The `repay` function of the `PerpetualPositionManager` contract simply redeems the tokens and then deposits the retrieved collateral. This should have no net effect on the collateral token. This produces clean code but introduces unnecessary fragilities and complexities:
- the deposit function pulls the collateral, so the user needs to have previously granted the relevant collateral token allowance to the contract before either having the collateral or knowing the amount of the deposit. Confusingly, they need to do this for an operation that ostensibly has nothing to do with the collateral token.
- the matching transfers correctly result in the same collateral balances, but they unexpectedly emit opposing Transfer events
- …
=> fix(dec-20-audit): [L02] Complex Repay Function

packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
**Problem:**
The Liquidatable constructor and the PerpetualLiquidatable constructor both revert if the collateral requirement is not greater than 100%, but the error message states “CR is more than 100%”.
**Solution in this PR:**
This PR fixes this by making the error messages more descriptive.
=> fix(dec-20-audit): [L07] Incorrect error message

packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/common/financial-product-libraries/PreExpirationIdentifierTransformationFinancialProductLibrary.sol, packages/core/contracts/financial-templates/common/financial-product-libraries/StructureNoteFinancialProductLibrary.sol, packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol, packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
**Problem identified in Audit**
**In FundingRateApplier.sol:**
- line 142: “to” should be removed
**In PreExpirationIdentifierTransformationFinancialProductLibrary.sol:**
- line 10: “than” should be “then”
- line 21: “Cant” should be “can’t”
- line 23: “exposes” should be “expose”
**In StructureNoteFinancialProductLibrary.sol:**
- line 14: “determine” should be “determined”
- line 23: “can not” should be “cannot”
- line 25: “exposes” should be “expose”
**In ConfigStore.sol:**
- line 14: “and” should be “an”
- line 144: “can” should be removed
**In PerpetualCreator.sol:**
- line 20: there is an extra space
**In PerpetualLiquidatable.sol:**
- line 545: “valid(liquidation” should be “valid (liquidation”
**In PerpetualPositionManager.sol:**
- line 229: “witdrawl.” should be “withdrawal.”
- …
=> fix(dec-2020-audit): [N08] Typographical errors

packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
**Problem:**
In the PerpetualPositionManager.sol file, consider removing the import statement for FeePayer.sol, as it is never used in the PerpetualPositionManager contract.
Also, in the FundingRateApplier.sol file, consider removing the import statements for StoreInterface.sol and FinderInterface.sol, as they are never used in the FundingRateApplier contract.
**Solution in this PR**
These redundant imports were removed.
=> fix(dec-2020-audit): [N09] Unnecessary imports

packages/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
**Problem identified in audit:**
In lines 102 and 104 of PerpetualCreator.sol the derivative variable is cast to the address type. Since it is defined as address type, the casts are unnecessary.
**Solution in this PR**
The redundant type casting was removed. This change was also made to the EMP creator, which was not audited but the change was made for consistency.
=> fix(dec-2020-audit): [N10] Unnecessary type cast

packages/core/package.json, packages/core/scripts/local/DeployEMP.js, yarn.lock
**Motivation**
The deployment script should use core@1.2.1 that includes the patched ExpiringMultiPartyCreator.
**Summary**
This adds a new version to the package.json and points the DeployEmp.js script at v1.2.1.
**Issue(s)**
N/A
=> improve(core): update deploy script to use patched deployment

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
[L06] Inconsistent hasPrice determination
The hasPrice function of the OptimisticOracle contract returns true if the request is either Settled or Resolved. Although the internal state of the contract does not record the price in the Resolved state, this makes sense because retrieving the price will settle the request. This means that from a user’s point of view, a Resolved price request can be considered to have a price. However, the same reasoning suggests that an Expired price request can also be considered to have a price.
Consider adding another condition to the hasPrice function so it returns true for Expired price requests.
**Summary**
This adds an additional state check to resolve hasPrice to true if price proposal is …
=> fix(dec-20-audit): [L06] Inconsistent hasPrice determination

packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
**Problem:**
The `createPerpetual` function of the PerpetualCreator contract will run most of its logic before eventually reverting when the `params.collateralAddress` is not approved. Similarly, the withdraw function of the PerpetualPositionManager contract reverts when `collateralAmount` is equal to zero, but only after already getting the positionData using the nontrivial _getPositionData.
**Solution in this PR:**
This PR moves the required checks to the top of the function to follow the Checks-Effects-Interactions pattern. 
Note that the audit recommends checking that an identifier is registered within the `IdentifierWhitelist` to preserve gas within the `PerpetualCreator` in the case of a reverting call. This change was chosen to _not_ be implemented as this function is not called …
=> fix(dec-2020-audit): [L10] Functions not failing early

packages/core/contracts/financial-templates/common/FeePayer.sol, packages/core/contracts/financial-templates/common/FundingRateApplier.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
**Motivation**
In the Perpetual Multiparty template, the funding rate is applied on every fee-accruing transaction, where the total change is simply the rate applied evenly since the last update. This implies that the compounding rate depends on the frequency of update transactions, and it never reaches the ideal of continuous compounding.
This approximate-compounding pattern is common in the Ethereum ecosystem, and the discrepancy is likely unimportant in this case. Nevertheless, in the interest of clarity, we believe it is worth noting. Consider documenting this behavior in the FundingRateApplier comments.
**Summary**
Added notes to `FeePayer` and `FundingRateApplier` which both implement approximate-compounding for continuous computations.
=> fix(dec-20-audit): [N01] Add notes about Approximate compounding

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
The optimistic oracle is designed so that in the event of a dispute, the incorrect party pays the bond penalty to the vindicated party, as determined by the DVM. However, if the proposer and disputer are the same entity, this transfer has no effect. The only remaining deterrent is the DVM fee. Since the bond size is specifically chosen to dissuade attackers from submitting the wrong price and delaying resolution, the ability to nullify the bond penalty undermines the economic reasoning. Moreover, if the reward exceeds the DVM fee, the attacker may actually be positively rewarded for delaying the resolution.
This attack does not apply to contracts deployed from the Perpetual Multiparty template, because they disregard disputed price requests. Nevertheless, it does limit the …
=> fix(dec-20-audit): [H01] Bond penalty may not apply

packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
**Motivation**
The ERC777 token standard extends ERC20 tokens to include send and receive hooks on every balance update. Although the standard is intended to be backwards compatible, it can introduce unexpected risks into systems designed to work with ERC20s.
In this case, the Liquidatable contract has been refactored to distribute funds to all participants in the same transaction. The same pattern is used in the PerpetualLiquidatable contract. If any of those addresses have a receive hook that reverts, none of the participants could withdraw their funds.
Similarly, if an address that requests a price from the Optimistic oracle prevents the dispute refund transfer, they will disable the dispute functionality.
If the system should support ERC777 tokens, consider isolating the transfer …
=> improve(dec-20-audit): [N02] Consider ERC777 tokens

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
Dev mining calculations and bots for uGAS-FEB21 and uGAS-MAR21 require default price feeds. This PR adds the necessary default price feeds to DefaultPriceFeedConfigs.js.
**Summary**
Adds the price feed. GASETH-FEB21, GASETH-MAR21 follow the implementation details from [UMIP-25](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-25.md), GASETH-TWAP-1Mx1M follows the implementation details from [UMIP-22](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-22.md).
=> feat(default-price-feed) Add GASETH-TWAP-1Mx1M, GASETH-FEB21, GASETH-MAR21

packages/core/scripts/local/getMedianHistoricalPrice.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js
**Motivation**
- Adds verbose logs for CryptoWatch's `getCurrentPrice()` method. 
- Prints out how many decimals it is truncating the median price to.
- Adds ability for user to specify a `PRICE_FEED_CONFIG` in their environment which could include params like "apiKey" for CryptoWatch
Example run:
```
yarn truffle exec ./packages/core/scripts/local/getMedianHistoricalPrice.js --network mainnet_mnemonic --identifier USDETH
Using network 'mainnet_mnemonic'.
Optional '--time' flag not specified, defaulting to the current Unix timestamp (in seconds): 1609431280
⏰ Fetching nearest prices for the timestamp: Thu, 31 Dec 2020 16:14:40 GMT
(coinbase-pro:ethusd) No OHLC available @ 1609431280
- ✅ Falling back to Current Price:0.001362082351498971
- ⚠️ …
```
=> improve(voter-helper-script): Add more information to script that helps voters resolve prices

packages/common/src/PriceIdentifierUtils.js, packages/core/config/identifiers.json
**Motivation**
New identifiers must resolve to same precision as collateral:
- ELASTIC_STABLESPREAD/USDC, STABLESPREAD/USDC ==> 6 decimals, same as USDC
- STABLESPREAD/BTC, BCHNBTC ==> 8 decimals, same as renBTC
Once the latest EMP factory is deployed, we will be able to assume that all identifiers can resolve to 18 decimals, but currently the identifier precision must match the EMP's collateral precision.
=> improve(voter-dapp): add hardcoded precision for new identifiers

packages/cli/README.md, packages/common/README.md, packages/core/README.md, packages/disputer/README.md, packages/financial-templates-lib/README.md, packages/liquidator/README.md
**Motivation**
Packages don't have READMEs.
**Summary**
Adds READMEs for core, financial-templates-lib, common, disputer, and liquidator. Packages remaining without READMEs (cc @pemulis): reporter, monitors, and serverless-orchestration.
**Issue(s)**
N/A
=> docs: add package readmes for half of remaining packages

README.md
Signed-off-by: pemulis <john.d.shutt@gmail.com>
**Motivation**
Main README says to install node `lts`, which is now a 14.x version that breaks the repo.
**Summary**
Notes in the main README that you need to install nodejs v12.x.x since later versions break the repo.
**Issue(s)**
N/A
=> docs(node-v): fixes node version in documentation

packages/financial-templates-lib/src/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js, packages/monitors/index.js, packages/monitors/src/SyntheticPegMonitor.js, packages/monitors/test/SyntheticPegMonitor.js
**Motivation**
Currently, the `SyntheticPegMonitor` assumes that the `TOKEN_PRICE_FEED` (i.e. the "synthetic") and the `MEDIANIZER_PRICE_FEED` (i.e. the "peg") are returning prices denominated in the same currency. However, consider the case where the synthetic market is (zeldaCash - USDC) and the peg market is tracking (STABLESPREAD/ETH). This can result in the following erroneous log:
**Summary**
Adds an optional construction parameter to this monitor called the `denominatorPriceFeed` which will divide the synthetic price if available.
Example environment variable to divide the synthetic price by the price of ETHUSD:
```
TOKEN_DENOMINATOR_PRICE_FEED_CONFIG={"type":"cryptowatch","apiKey":"XXX","exchange":"coinbase-pro","pair":"ethusd","lookback …
```
=> fix(bots): Add feature to denominate synthetic price by another price feed + remove noisy BasketSpreadPriceFeed logs

packages/disputer/src/disputer.js, packages/disputer/test/Disputer.js, packages/financial-templates-lib/src/price-feed/BalancerPriceFeed.js, packages/financial-templates-lib/src/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/src/price-feed/DominationFinancePriceFeed.js, packages/financial-templates-lib/src/price-feed/MedianizerPriceFeed.js, packages/financial-templates-lib/src/price-feed/PriceFeedInterface.js, packages/financial-templates-lib/src/price-feed/PriceFeedMock.js, packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js, packages/financial-templates-lib/test/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/test/price-feed/DominationFinancePriceFeed.js, packages/financial-templates-lib/test/price-feed/MedianizerPriceFeed.js, packages/financial-templates-lib/test/truffle/BalancerPriceFeed.js, packages/financial-templates-lib/test/truffle/UniswapPriceFeed.js, packages/monitors/src/ContractMonitor.js, packages/monitors/test/ContractMonitor.js
**Motivation**
`Disputer` should not throw warning if trying to lookup liquidation time beyond price feed lookback (`lastUpdateTimestamp` - `lookback`):
- Adds `getLookback` to PriceFeedInterface which is the earliest possible timestamp for which a historical price could be available
- Usethis information in `disputer` and `ContractMonitor` and don't throw warning if trying to fetch price for liquidation time earlier than historical lookback. This is possible if the user explicitly sets a shorter lookback than the EMP's liquidationLiveness window. e.g. This avoids sending out warnings if a liquidation occurred earlier than the pricefeed's lookback window and its liveness has not expired.
=> improve(price-feed-interface): Add getLookback to interface

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
Uniswap pools need to specify `poolDecimals` if non-18 decimals
Use UniswapPriceFeed whereever `uniswap-v2` is listed on CryptoWatch due to flaky CW api.
=> fix(default-price-feed-config): specify pool decimals

packages/disputer/src/disputer.js, packages/disputer/test/Disputer.js, packages/liquidator/src/liquidator.js, packages/liquidator/test/Liquidator.js, packages/monitors/index.js, packages/monitors/src/BalanceMonitor.js, packages/monitors/src/CRMonitor.js, packages/monitors/src/ContractMonitor.js, packages/monitors/src/SyntheticPegMonitor.js, packages/monitors/test/BalanceMonitor.js, packages/monitors/test/CRMonitor.js, packages/monitors/test/ContractMonitor.js, packages/monitors/test/SyntheticPegMonitor.js
**Motivation**
While working on the perp liquidator bot I found a subtle but substantial bug present within the Liquidator & Disputer bots regards to how configs are passed around.
**Summary**
PR https://github.com/UMAprotocol/protocol/pull/1924 merged on 2 Sep 2020 refactored the bots to pass around bot parameters as named values. However, this PR introduced a bug by incorrectly naming the `liquidatorConfig`. This bug can be seen in the following places:
1) in the `index.js` we feed in the `liquidatorConfig` as a named type `liquidatorConfig` here: https://github.com/UMAprotocol/protocol/blob/d782c56503a220a7eaa14baa8d03d925b5e956b6/packages/liquidator/index.js#L184
2) HOWEVER the `liquidator.js` file refers to this variable as `config`, here: …
=> fix(monitor,disputer,liquidator bots): correctly pass in bot config objects into bots

packages/core/scripts/local/getMedianHistoricalPrice.js
**Motivation**
Decimals are off in the getMedianHistoricalPrice script.
**Summary**
Ensures all price feeds are seeded with 18 as their decimals so the `fromWei` call at the end works as expected.
**Issue(s)**
N/A
=> fix(scripts): fix conversion in historical price feed script

packages/core/scripts/mainnet/ProposeAdmin.js, packages/voter-dapp/run_tests.sh, packages/voter-dapp/src/ActiveRequests.js
**Motivation**
The QA script was slightly out of date when I tried to use it.
**Summary**
- The `ProposeAdmin.js` script had been moved and args updated. The path and args were updated at the callsite.
- The `ProposeAdmin.js` script was modified to only work on mainnet (it depended on a hardcoded address). A minor update was made to make it work on any network.
- The `ProposeAdmin.js` script was missing an arg in its propose call.
- The voter-dapp depends on artifacts pulled from npm, so the migrate call needs to be made from the voter-dapp directory rather than the core directory. Otherwise, the migration will write to the local core artifacts, which are different from the ones the voter dapp reads from.
**Issue(s)**
N/A
=> fix(voter-dapp): fix QA script

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/core/test/financial-templates/common/FundingRateApplier.js, packages/core/test/oracle/OptimisticOracle.js
**Motivation**
OpenZeppelin pointed out an issue in the [H01 fix](https://github.com/UMAprotocol/protocol/pull/2329). In the (admittedly unlikely) case that the final fee is 0, the burned portion of the bond gets trapped in the optimistic oracle contract and can never be retrieved.
**Summary**
This fixes the issue by conditioning the payout on the sum of the burned bond _and_ the final fee being > 0, which was the original intention of the code.
**Issue(s)**
N/A
=> fix(dec-20-audit): [H01] fix optimistic oracle fee burning logic when final fee == 0

packages/core/contracts/financial-templates/common/FeePayer.sol, packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
PR2327 introduced a few small typos. This PR addresses these. In particular:
- penatly in FeePayer:107
- regualr in FeePayer:140
- calculating instead of calculated and a missing space after the full stop in PerpetualLiquidatable:424-425
=> fix(smart-contracts): fixed audit PR typos 

.circleci/config.yml
**Motivation**
Coverage takes a long time to run on each build, so we'd like to move it to nightly. It can still be run manually if desired on a particular PR.
**Summary**
Add a new nightly workflow that runs at midnight each night and includes checkout and install + coverage.
**Issue(s)**
N/A
=> ci: move coverage to nightly

packages/affiliates/libs/affiliates/devmining.js, packages/affiliates/libs/processors.js, packages/affiliates/test/mocha/devmining.js
**Motivation**
#2416 
**Summary**
This adds an "isExpired" flag to the emp balances state which gets toggled on expiry event. This flag is snapshotted along with balances every block and checked before balances are contributed to total value. If expired, emp balances are ignored. A test is added to verify this works in a very simple case. This was also tested manually against 2020-12-28 through 2021-01-4, where 2 contracts expire. 
**Issue(s)**
Fixes #2416
=> feat(affiliates): emps which expire do not contribute to rewards after expiry

packages/liquidator/index.js, packages/liquidator/src/liquidationStrategy.js, packages/liquidator/src/liquidator.js, packages/liquidator/test/Liquidator.js, packages/liquidator/test/index.js
**Motivation**
Problem mentioned as part of #2419
Previously, this error log is being emitted even if the WDF is not being activated on purpose (i.e there is no error):
**Summary**
Liquidator queries `LiquidatorStrategy` to determine if it should emit a specialized log about the WDF not being activated yet.
=> improve(liquidator): Send log when WDF is purposefully not activated

.circleci/config.yml
**Motivation**
coverage currently requires a privileged context to run, which causes the nightly build to fail because it cannot be run with privileged permissions: see https://circleci.canny.io/cloud-feature-requests/p/allow-restricted-contexts-within-scheduled-workflows.
**Summary**
Coverage seems to only require the coveralls token to run correctly, so I figure it isn't too dangerous to provide that variable to all ci jobs rather than making it privileged (it's not a paid service and the token can be regenerated if compromised). This update has been made in the circleci config.
**Testing**
**Issue(s)**
N/A
=> ci(nightly): fix nightly by removing privileged context

package.json, yarn.lock
**Motivation**
There is an Intel-specific dependency that breaks compatibility with computers running the new M1 chip from Apple.
**Summary**
Replaces the Intel-specific dependency with one that works with alternate instruction sets.
Note: There are still some failing tests if you run this on a computer running an Apple M1 chip, but it doesn't break existing tests on regular Intel chipsets.
**Details**
This also updates the ganache-cli version to be compatible with node v15. The reason for this is because node v15 works natively with Apple's M1 chip, while earlier versions do not.
Interestingly, all tests passed locally after building and running with node v15 on an older MacBook. That means that this PR would appear to make the project …
=> feat(m1): update dependencies to run on apple m1 chip

packages/financial-templates-lib/src/price-feed/DominationFinancePriceFeed.js
**Motivation**
The domination price feeds return undefined for their decimals value.
**Summary**
Save the priceFeedDecimals value in the price feed object.
**Testing**
**Issue(s)**
N/A
=> fix(financial-templates-lib): fix domination finance feed decimals

packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js
**Motivation**
The Uniswap price feed has a bug where few trades (last trade long before the lookback window) will cause the uniswap price feed to just take the spot price rather than the TWAP.
**Summary**
Reimplemented the update function to streamline and simplify the implementation by condensing most of the complex looping logic into a single looping block.
To fix the issue, this adds an exponential lookback to quickly make larger and larger historical queries to _always_ find the correct most recent sync event before the window.
**Testing**
Note: this could probably use some specific tests for low volume pools. Will add.
**Issue(s)**
N/A
=> fix(uniswap-pf): fixes a low volume bug in the uniswap price feed

packages/core/scripts/local/getMedianHistoricalPrice.js
**Motivation**
The price feed script shouldn't uppercase the user input since some identifiers have lowercase characters.
**Summary**
Removed the toUpper call.
**Testing**
**Issue(s)**
N/A
=> improve(core): remove toUpper in price feed script because some identifiers are lowercase

packages/voter-dapp/src/apollo/queries.js, packages/voter-dapp/src/containers/VoteData.js
**Motivation**
"Vote Stats" button not working for the price request with identifier "GASETH-TWAP-1Mx1M".
**Summary**
The VoteData container erroneously assumes that you can determine the price request's identifier by delimiting the struct's `id` by the "-" symbol and grabbing the first element. This doesn't work if the identifier has "-" in it! Instead, we grab the identifier directly from the subgraph by modifying the graphql query.
**Testing**
=> fix(voter-dapp): Query identifier directly from subgraph

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
This PR adds AMPL-USD to DefaultPriceFeedConfigs.js
**Summary**
Simply adds the price feed. This feed follows UMIP-33's implementation details.
=> feat(default-price-feed) Add AMPL-USD Default price feed

packages/common/src/FindContractVersion.js, packages/common/src/MultiVersionTestHelpers.js, packages/common/src/ProviderUtils.js, packages/liquidator/index.js, packages/liquidator/package.json, packages/liquidator/test/Liquidator.js
**Motivation**
The most recent functionality with the perpetual bot support included the ability to automatically detect what contract version we are using. For some or other reason this failed to work in production.
**Summary**
After much painful testing, I was able to get this method to work in production by using ethers.js over web3.js. I'm not actually sure why this works, but it does 🤷 
**Details**
**Testing**
=> fix(FindContractVersion): address web3.js inconsistant production behaviour with ethers.js

packages/common/src/PriceIdentifierUtils.js
**Motivation**
when https://github.com/UMAprotocol/protocol/pull/2454 was merged the `PriceIdentifierUtils` was not updated. This synthetic is intended to be collateralied in USDC and so the feed needs to be scaled accordingly. This can be seen within UMIP-33 [here](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-33.md#technical-specification).
**Summary**
updated `PriceIdentiferUtils.js`.
**Testing**
=> fix(PriceIdentifierUtils): Add correct AMPLUSD decimals

.circleci/config.yml
**Motivation**
Slither tends to cause more problems than it solves in ci. We run it in a separate docker image and it consistently breaks when interacting with our toolchain. It also doesn't seem to provide a lot of value -- by my understanding, it has never caught a smart contract bug -- it has caught some minor stylistic or readability issues.
**Summary**
This PR removes slither from ci, but leaves the run script in place in case we want to run it in the future.
**Testing**
**Issue(s)**
N/A
=> ci(slither): remove slither from ci

packages/disputer/src/disputer.js, packages/disputer/test/Disputer.js, packages/financial-templates-lib/src/logger/Logger.js, packages/monitors/src/SyntheticPegMonitor.js, packages/monitors/test/SyntheticPegMonitor.js
**Motivation**
- The `Disputer` unneccessarily computes `getHistoricalPrice()` twice, the second time it fails to check for errors. This PR refactors the disputer logic so that it caches the result of the first and only `getHistoricalPrice()` call
- The `SyntheticPegMonitor` handles errors from the pricefeed in an unncessarily complex manner. The other pricefeed clients all just send the `Error` object to the logger, which has error-parsing logic. This PR simplifies how this monitor reports errors.
**Testing**
=> improve(disputer): improve how pricefeed clients pass through errors

packages/common/src/FindContractVersion.js
**Motivation**
`FindContractVersion.js` depends on ethers.js. The previous implementation only worked with `http` and `https` web3 providers and not `wss` ones. This means that the script broke in production, where we use WebSockets. 
This PR changes the implementation to rely on the existing web3 provider with the ethers `Web3Provider` provider.
**Summary**
**Testing**
=> fix(FindContractVersion): address inconsistent provider behavior

packages/core/scripts/local/getMedianHistoricalPrice.js, packages/disputer/src/disputer.js, packages/financial-templates-lib/src/price-feed/BalancerPriceFeed.js, packages/financial-templates-lib/src/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/src/price-feed/DominationFinancePriceFeed.js, packages/financial-templates-lib/src/price-feed/InvalidPriceFeedMock.js, packages/financial-templates-lib/src/price-feed/MedianizerPriceFeed.js, packages/financial-templates-lib/src/price-feed/PriceFeedInterface.js, packages/financial-templates-lib/src/price-feed/PriceFeedMock.js, packages/financial-templates-lib/src/price-feed/PriceFeedMockScaled.js, packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js, packages/financial-templates-lib/test/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/test/price-feed/DominationFinancePriceFeed.js, packages/financial-templates-lib/test/price-feed/MedianizerPriceFeed.js, packages/financial-templates-lib/test/truffle/BalancerPriceFeed.js, packages/financial-templates-lib/test/truffle/UniswapPriceFeed.js, packages/monitors/src/ContractMonitor.js, packages/monitors/src/SyntheticPegMonitor.js, packages/monitors/test/SyntheticPegMonitor.js
**Motivation**
Some price feeds cannot do a full 2 hour lookup during `update()` as it would be too inefficient.
**Summary**
Make the standard `getHistoricalPrice` fn async.
**Testing**
**Issue(s)**
N/A
=> feat(financial-templates-lib): make getHistoricalPrice async

packages/disputer/index.js, packages/liquidator/index.js, packages/monitors/index.js, packages/serverless-orchestration/src/ServerlessHub.js, packages/serverless-orchestration/test-helpers/TimeoutSpokeProcess.js
**Motivation**
This PR addresses two issues identified within the serverless configuration:
- Often spoke logs are dropped at the end of a spoke execution and are not logged correctly.
- There was a mismatch between the timed out spokes and the error spokes reported in hub logs. 
**Details**
**Problem 1:**
When debugging hub/spoke interactions, you can sometimes find that the bottom-most set of logs can get lost. The screenshot below shows the logs within a spoke for a given bot. This bot executed correctly and all logs were produced. however, some did not show up within GCP correctly. 
To deal with this issue, each bot's `index.js` file was updated to accommodate a 2-second timeout before the process terminates. This is a pretty shitty patch but it solves the issue and for now it'll be a …
=> fix(serverless-hub): Address dropped spoke logs and mismatch timedout spokes

packages/liquidator/mocha-test/liquidationStrategy.js, packages/liquidator/src/liquidationStrategy.js, packages/liquidator/src/liquidator.js, packages/liquidator/test/Liquidator.js
**Motivation**
#2510 
Related to #2508
**Summary**
Adds check to `liquidationStrategy` to ignore WDF threshold if no withdrawal request to extend. The WDF is typically used to maintain a balance of funds with which to extend withdrawal timers, but this should be ignored if there are no withdrawals to process.
**However, this is a controversial PR because merging it would mean that we can no longer guarantee that a bot will always have >= WDF in token balance.**
Something to consider if we merge this PR: Does this render the `whaleDefenseFundWei` parameter irrelevant? I.e. can we merge this PR AND subsequently remove that param?
**Testing**
**Issue(s)**
Fixes #2510
=> improve(liquidator): Ignore WDF if no withdrawal request to extend

packages/common/src/TimeUtils.js, packages/financial-templates-lib/src/price-feed/utils.js, packages/financial-templates-lib/test/price-feed/utils.js
**Motivation**
To build a price feeds that require past block queries at specific _times_, we need a way to find the exact block at or immediately preceding a particular timestamp. Our existing block querying utilities _can_ do this, but they query _all_ blocks over a certain range. This utility serves a slightly different purpose in that it uses a binary search (technically interpolation search) to find the block for a timestamp at any point in the blockchain's history without needing _all_ blocks since that point. Because it's a binary-style search, this can take slightly longer since all queries need to be done in series.
**Summary**
The BlockFinder follows the same style as the other block querying utilities. Its interface is a single function to get the block for a timestamp.
Note: …
=> feat(financial-templates-lib): add BlockFinder

packages/trader/hardhat.config.ts, packages/trader/package.json, packages/trader/src/index.ts, packages/trader/src/tsconfig.json, packages/trader/test/index.ts, packages/trader/tsconfig-build.json, packages/trader/tsconfig.json, yarn.lock
**Motivation**
The trader package doesn't currently have a test setup.
**Summary**
It was a little tricky to get typescript tests set up in hardhat using truffle5 and web3, but it's doable. This PR adds a sample test and shuffles the package configuration to make it so `hardhat test` works as one would expect. I suspect there may be other issues down the road, but this should be a good place to start and has the basics.
**Testing**
**Issue(s)**
N/A
=> improve(trader): add hardhat test setup

packages/financial-templates-lib/package.json, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/ExpressionPriceFeed.js, packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/test/price-feed/ExpressionPriceFeed.js, yarn.lock
**Motivation**
To support more arbitrary types of price feeds, it is becoming clear that it would be useful to be able to define arbitrary expressions that combine existing price feeds. This is a proposal for a price feed that takes expressions of the form:
```
"BTCUSD * 100 / ETHUSD"
```
Note: the library can actually handle _far more_ complex expressions, even multiline ones. But, for now, we should encourage users to keep them fairly simple.
**Summary**
This is a _proposal_ for a type of expression-parsing price feed to add more generality to the price feed creation process. This would move much of the simple math to the config and leave only the data-acquisition to the price feeds themselves.
I haven't added the configuration and construction portions of this price feed, as I want to …
=> feat(price-feeds): add ExpressionPriceFeed

packages/financial-templates-lib/package.json, packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/TraderMadePriceFeed.js, packages/financial-templates-lib/test/price-feed/TraderMadePriceFeed.js
**Motivation**
Follow up on UMAProtocol/UMIPs#97, [umip-32](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-32.md).
Similar to CryptoWatch price feed implementation, this PR can help us to get CNYUSD exchange rate from TraderMade
**Testing**
- [✅ ]  Ran end-to-end test, running the code as in production
- [✅ ]  New unit tests created
- [✅ ]  All existing tests pass
=> feat(default-price-feed): add TraderMadePriceFeed

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
CryptoWatch OHLC data is often empty for FRAX/USDC and ESD/USDC markets because they are relatively low volume on Uniswap. Replace with UniswapPriceFeed that better handles missing data within a TWAP window.
=> improve(default-pricefeed): Swap UniswapPriceFeed for CryptoWatchPriceFeed for elastic basket

packages/financial-templates-lib/src/price-feed/ExpressionPriceFeed.js, packages/financial-templates-lib/test/price-feed/ExpressionPriceFeed.js
**Motivation**
ExpressionPriceFeed should support expressions that are multi-line.
**Summary**
When multiline expressions are passed in, mathjs returns `ResultSet`, which can return multiple results at once. In that case, the ExpressionPriceFeed returns the last line's result.
**Testing**
**Issue(s)**
N/A
=> feat(financial-templates-lib): add Multiline support to ExpressionPriceFeed

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
ESD/USDC and FRAX/USDC pools return 6 precision prices based on how we query `Sync` events. This currently means that those prices are returning unexpected values.
=> patch(default-pricefeeds): Update poolDecimals for elasticStablespread

packages/core/contracts/oracle/implementation/OptimisticOracle.sol, packages/financial-templates-lib/src/clients/OptimisticOracleClient.js, packages/financial-templates-lib/test/clients/OptimisticOracleClient.js, packages/optimistic-oracle/src/proposer.js, packages/optimistic-oracle/test/proposer.js
**Motivation**
Part of #2411
Adds dispute logic to Optimistic Oracle proposer bot.
**Summary**
- Added event parameters to `OptimisticOracle.sol` to simplify bot logic. See comments for more details.
- Implemented `sendDisputes` in the `packages/OptimisticOracle: proposer.js` bot which checks proposed prices for `undisputed proposals` and sends disputes where `disputePrice != proposePrice`
Future work:
- Add a disputePrice buffer configuration variable to the OO bot which allows `disputePrice` and `proposePrice` to diverge beyond a certain precision, (e.g. 5 decimals of precision), without having to send a dispute.
- Add settlePrice feature
**Details**
- Adding event parameters to `OptimisticOracle.sol` should be harmless but its important to …
=> feat(optimistic-oracle-proposer): Add dispute logic

packages/core/contracts/umips/VotingUpgrader.sol, packages/core/scripts/voting-upgrade-umip/1_Propose.js, packages/core/scripts/voting-upgrade-umip/3_Verify.js
**Motivation**
To allow the foundation hot wallet to claim rewards on behalf of voters in the old voting contract, we need to set it as the migrated address.
**Summary**
Added a parameter to the upgrader contract and passed the foundation hot wallet to the constructor in the upgrade script.
Note: the migrated address has the following abilities:
- Migrated address can request a price to "start a vote"
- Nobody can cast votes (so any incomplete votes cannot be finalized and, therefore generate rewards).
- Migrated address can call claim rewards.
**Testing**
**Issue(s)**
N/A
=> improve(core): update voting upgrade script to pass proposer wallet as migrated address

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
This price identifier is self referential. It tracks the price of the synthetic that uses it.
UMIP-38 for price identifier spec: https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-38.md
**Summary**
Added config for tracking the Uniswap pool for new synthetic.
**Testing**
=> feat(pricefeeds): Add COMPUSDC-APR-MAR28/USDC

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
Signed-off-by: FreshmanQ <xunand@quarkchain.org>
**Motivation**
Part of #2479 
**Summary**
Add CNYUSD price identifier default configuration 
**Testing**
- [✅ ]  Existing tests adequate, no new tests required
=> improve(pricefeed): Add default config for CNYUSD to TraderMade

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/LPPriceFeed.js, packages/financial-templates-lib/src/price-feed/VaultPriceFeed.js, packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/test/price-feed/LPPriceFeed.js, packages/financial-templates-lib/test/price-feed/VaultPriceFeed.js
**Motivation**
We'd like to be able to price LP tokens. This LPPriceFeed can basically be used wherever there's a pool of tokens (one or more) and you'd like to know how much of a particular token is redeemable for a single LP share.
For instance, in a Uniswap pool with 50 WETH, 1 WBTC, and 25 LP shares, you could configure this feed to tell you how much WETH you'd get back for an LP share. The "price" that it would return would be 2 since the 50 WETH is spread over 25 shares. You could configure another instance of this feed to tell you how many WBTC each share is redeemable for. The "price" for that feed would be 0.04.
**Summary**
The LPPriceFeed was implemented very similarly to the VaultPriceFeed given that they do very similar things: make a smart contract call or two, do some math, …
=> feat(financial-templates-lib): add LPPriceFeed

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
**Motivation**
#2588
**Summary**
When this PR is merged, bot configs need to be changed that are using `apiKey` as a config param.
**Issue(s)**
Fixes #2588
=> refactor(create-price-feeds)!: Each PriceFeed renames apiKey config param

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
To support [UMIP-26](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-26.md), default price feeds for XAUPERL and XAUUSD need to be added. Merging this PR should allow #2534 to be closed.
**Summary**
These price feeds follow the specifications in UMIP-26.
**Testing**
**Issue(s)**
NA
=> feat(financial-templates-lib): add a new price feed config for XAUPERL

packages/affiliates/libs/affiliates/devmining.js, packages/financial-templates-lib/src/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/src/price-feed/DominationFinancePriceFeed.js, packages/financial-templates-lib/src/price-feed/MedianizerPriceFeed.js, packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js
**Motivation**
Part of #2461
**Summary**
Implements `getHistoricalPricePeriods() => [time, price]` for Uniswap and BasketSpread price feeds.
**Testing**
TODO: Does this work for `affiliates`?
=> improve(pricefeed): Add getHistoricalPricePeriods to BasketSpread and Uniswap

packages/financial-templates-lib/src/price-feed/ExpressionPriceFeed.js, packages/financial-templates-lib/test/price-feed/ExpressionPriceFeed.js
**Motivation**
Matching `BasketSpreadPriceFeed` which also aggregates component pricefeed errors, the Expression pricefeed should be throwing the full Error objects not just their `.stack` parameters.
**Testing**
=> patch(expression-pricefeed): Throw errors not errors.map(err => err.stack)

packages/disputer/src/disputer.js
**Motivation**
After dispute is sent, DIsputer logs details about the transaction receipt including the historical price it used to submit the dispute. The price is not correctly cast to a String before sending to the logger, which causes the Slack Transport to error.
Notice in the logs below how the `price` looks strange, because the `price` is actually a BN object.
**Testing**
Tested on Kovan
=> patch(disputer): Cast liquidation price BN --> String before logging

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js, packages/financial-templates-lib/src/price-feed/TraderMadePriceFeed.js, packages/financial-templates-lib/test/price-feed/TraderMadePriceFeed.js
**Motivation**
TraderMade API expectedly returns no timeseries data over the weekend, but the price identifier UMIPs that suggest using the TraderMade API request that pricefeeds fall back to the last known price, see [UMIP-32](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-32.md#weekend-price) for an example of this recommendation.
[The PR that implemented the TraderMadePriceFeed originally was supposed to implement this fallback](https://github.com/UMAprotocol/protocol/pull/2479#issuecomment-771237776) but the feature got lost to no individual fault. This PR therefore adds the fallback functionality to both the `update()` and `getHistoricalPrice` methods:
- `update` fetches historical price data from the `minute` timeseries but …
=> improve(tradermade-pricefeed): Fall back to hourly OHLC interval when minute interval fails

packages/common/src/MultiVersionTestHelpers.js, packages/disputer/index.js, packages/disputer/src/disputer.js, packages/disputer/test/Disputer.js, packages/liquidator/index.js, packages/liquidator/src/liquidator.js, packages/liquidator/test/Liquidator.js, packages/liquidator/test/index.js
**Motivation**
Resolved disputes are withdrawn successfully but event log parsing is mishandled if EMP version is not a legacy (<=1.2.2) one.
Additionally, we can query `settlementPrice` from the event logs instead of making a call to the VotingContract.getPrice(), which removes the need for the bots to construct the Voting contract.
Tested log output to Slack successfully on Kovan.
**Testing**
=> patch(disputer,liquidator): Handle changed LiquidationWithdrawn event params

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
After applying the variable renames on https://github.com/UMAprotocol/protocol/pull/2480 last iteration, we missed updating `DefaultPriceFeedConfig.js`, thus this new PR.
**Summary**
Renamed `convert` & `currency` to `quoteCurrency`.
**Details**
This fixes a potential liquidator bot error should the `PRICE_FEED_CONFIG` won't include `quoteCurrency` parameter for `coinmarketcap` & `coingecko` price feeds.
This is the liquidation bot error if the value is `PRICE_FEED_CONFIG={ "apiKey": "<cmc-api-key>" }`
```
[error]: {
"at": "Liquidator#index",
"message": "Liquidator execution error🚨"
}
Error: Price feed config is invalid
```
**Testing**
=> fix(price-feeds): correct PHPDAI default price feed config

packages/common/src/FindContractVersion.js
**Motivation**
Latest Mainnet EMP hash is not recognized because it is not included in `FindContractVersion.js`.
**Summary**
Added the ExpiringMultiParty contract hash.
**Testing**
Tested by running monitor bots after including this contract hash locally. 
**Issue(s)**
NA
=> fix(contract-versions): Add mainnet contract hash

packages/core/contracts/oracle/test/VotingAncillaryInterfaceTest.sol, packages/voter-dapp/src/Dashboard.js, packages/voter-dapp/src/MigrationBanner.js, packages/voter-dapp/src/NotificationBanner.js, packages/voter-dapp/src/RetrieveRewards.js, packages/voter-dapp/src/drizzleOptions.js
**Motivation**
Contract upgrades have required a 2key upgrade as well, and we will need to warn users who have not migrated to the newest 2key, to do so. 
**Summary**
The dashboard now has logic which looks up if a user has UMA tokens at the old 2key contract, if so, a banner component has been added which directs the user to the migration guide.
**Details**
This is an example of what it looks like, in production it will not show if a user has 0 uma at address
**Testing**
=> feat(voter-dapp): fetch users 2key contract state, and show migration banner if required

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
The uSTONKS_APR21 price [identifier](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-47.md) needs a default price feed config.
**Summary**
Adds the default price feed config.
**Testing**
**Issue(s)**
NA
=> feat(financial-templates-lib): add uSTONKS default price feed

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
The contract originally using the `GASETH-TWAP-1Mx1M` price identifier has expired. The default `GASETH-TWAP-1Mx1M` is being updated to support another contract and is accompanied by this UMIP [edit](https://github.com/UMAprotocol/UMIPs/pull/203).
**Summary**
Reference pool address has been updated to new uGAS Uniswap pool.
**Testing**
Ran monitor bot.
**Issue(s)**
NA
=> improve(financial-templates-lib): updates GASETH-TWAP-1Mx1M default config

packages/core/scripts/local/ClaimAllRewards.js
**Motivation**
Over the past few weeks, I've had to modify the claim rewards script a few times as a part of our upgrade process. To make this process easier in the future, I thought it might be nice to publish these updates.
**Summary**
A few notable updates:
- The script can now exclude addresses.
- The script can now claim for all rounds if unspecified or user-specified round(s).
- The script can now be used to only claim for one or multiple addresses instead of all addresses.
- The script can talk to multiple Voting versions at once.
- The script now takes an option just to print a summary of unclaimed rewards rather than claiming.
**Testing**
**Issue(s)**
N/A
=> feat(core): general improvements to claim rewards script

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
The Basis price feed configs should use a median rather than a mean. This follows the guidelines of the [umip-40](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-40.md). 
**Summary**
Change mean to median within the price feed expressions.
**Testing**
Ran monitor bot.
**Issue(s)**
NA
=> fix(financial-templates-lib): Change Basis configs to use median

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
To support the AAVEUSD, USDAAVE, UMAUSD, USDUMA, SNXUSD, USDSNX, LINKUSD, USDLINK, UNIUSD and USDUNI price identifiers added in [UMIP-57](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-57.md), default price feed configs need to be added.
All of these price identifiers use Coinbase Pro, Binance and OKEx and are all available on Cryptowatch. 
**Summary**
Added medianizer configs for each price identifier listed.
**Testing**
Ran USD/XYZ price feeds in a monitor bot locally.
**Issue(s)**
NA
=> feat(financial-templates-lib): Add various altcoin price feed configs

Dockerfile
**Motivation**
The docker build process was previously using commands that are repeated in the package.json. This PR updates this to have one source of truth.
=> fix(docker): point docker build to use commands in package.json rather than hardcoded commands

packages/common/src/ContractUtils.js
**Motivation**
Empirical testing has revealed that the `estimateGas()` method in `web3.eth.Contract` objects sometimes underestimates. This adds a similar buffer used in other bots like the [disputer](https://github.com/UMAprotocol/protocol/blob/master/packages/disputer/src/disputer.js#L200).
**Testing**
=> improve(run-transactions): Add gas limit estimation buffer

packages/financial-templates-lib/src/price-feed/Networker.js
**Motivation**
The networker has a error log that should be changed to throw an error. When the Networker fails to complete a request it will produce an error even though it correctly fetched pricing information in the subsequent execution.
An example of the error produced can be seen below:
However, the bot _did_ correctly finish its execution cycle, after the retry logic re-initiated the price request. see screenshot below:
As a result, This PR updates the networker to rather throw an error such that the error can be bubbled up to the price feed using it, enabling the bot to re-run its execution and optimistically return a value price on the next retry loop.
=> fix(networker): throw on error rather than logging an error

packages/common/src/FindContractVersion.js
**Motivation**
ci is broken due to a merge issue I believe.
**Summary**
Removed the duplicate key in the object that ci is complaining about.
**Testing**
**Issue(s)**
N/A
=> fix(common): duplicate key causing lint to fail

packages/merkle-distributor/package.json
**Motivation**
We recently added a new package version of core to support the latest contract artefacts. This PR updates the Merkle-distributor package.json to match what is published in npm which uses these new releases.
=> fix(Merkle-distributor): bump package versions of core and update package to match npm

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
To support the OCEANUSD and USDOCEAN price identifiers added in [UMIP-46](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-46.md), default price feed configs need to be added.
OCEANUSD and USDOCEAN price identifiers use Binance, Bittrex and BitZ and are all available on Cryptowatch.
**Summary**
Added medianizer configs for OCEANUSD and USDOCEAN price identifiers.
**Testing**
Ran OCEANUSD and USDOCEAN price feeds in a monitor bot locally.
**Issue(s)**
NA
=> Add default price feed configs for OCEANUSD and USDOCEAN

packages/core/scripts/collateral-umip/1_Propose.js, packages/core/scripts/creator-umip/1_Propose.js, packages/core/scripts/identifier-umip/1_Propose.js
**Motivation**
Proposal scripts that are used often should use embedded gas price estimation.
**Summary**
Added the gas estimator class to these scripts to estimate the gas price.
**Testing**
**Issue(s)**
N/A
=> feat(proposal-scripts): add gas price estimation to reusable proposal scripts

packages/merkle-distributor/scripts/0_MerklePayoutIngestor.ts
**Motivation**
The injestor has a small bug when dealing with only 1 payout file. This PR Addresses this. Additionally, the comments are slightly changed.
=> fix(merkle-distributor-injestor): fix a small bug and typo

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Summary**
Adds a price feed config to support the USDBTC_18DEC price identifier added in [UMIP-66](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-66.md). This follows the exact same pattern as the existing USDBTC price identifier.
**Testing**
**Issue(s)**
NA
=> Add USDBTC_18DEC price feed config

packages/reporters/scripts/SendSlackReport.sh
**Motivation**
The docker container does not have ts-node within it. using npx is a simple work around.
=> fix(reporter): address issue with running within docker container

packages/reporters/scripts/SendSlackReport.sh
**Motivation**
Due to how `ts-node` executes within a docker container, it is required to be in the same directory as the script being run. This PR fixes this.
=> fix(reporter): address ts-node issue

packages/core/scripts/umip-3/2_VoteSimulate.js
**Motivation**
Known error when passing large unsigned uints as function arguments where an int is expected. Newer web3 doesn't seem to cast between uints and ints like it used to:
```
Error: value out-of-bounds (argument="salt", value="93598013133266225946634221140404577226246205875115240595869719382411854555386", code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)
at runExport (/Users/nicholaspai/UMA/protocol/packages/core/scripts/identifier-umip/2_VoteSimulate.js:195:44)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at run (/Users/nicholaspai/UMA/protocol/packages/core/scripts/identifier-umip/2_VoteSimulate.js:255:5) {
reason: 'value out-of-bounds',
code: 'INVALID_ARGUMENT',
argument: 'salt',
value: …
```
=> improve(admin-scripts): Use SignedInt for salt

packages/core/scripts/identifier-umip/3_Verify.js
**Motivation**
Adds console logs showing the price identifiers being verified in the UMIP verification script. This is helpful when you're adding a bunch of identifiers at once, especially for troubleshooting failed verifications.
**Summary**
Just added some logs.
**Details**
**Testing**
**Issue(s)**
n/a
=> feat(scripts): log identifiers being verified

packages/common/src/FindContractVersion.js, packages/core/contracts/financial-templates/common/financial-product-libraries/KpiOptionsFinancialProductLibrary.sol, packages/core/test/financial-templates/common/financial-product-libraries/KpiOptionsFinancialProductLibrary.js
**Motivation**
To create KPI options, we require a simple library to transform the collateral requirement and price of an EMP. 
Behavior:
- Pre-expiry the price is always set to 2.
- Post-expiry the price is not transformed
- The collateral requirement is always set to 1
The price identifier that will be used with this library is the `uTVL_KPI_UMA` price identifier, defined in [UMIP-65](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-65.md). `uTVL_KPI_UMA` sets a price ceiling of 2, so enforcement a pre-expiry collateralization requirement of 2 tokens will ensure that positions cannot become under collateralized by means of an increase in the token price.
**Summary**
`KpiOptionsFinancialProductLibrary.sol` added with associated unit tests.
**Testing**
Check a box to describe …
=> feat(financial-product-library): Create a KPI Options financial product library

packages/merkle-distributor/scripts/1_CreateClaimsForWindow.ts, packages/merkle-distributor/scripts/2_PublishClaimsForWindow.ts
**Motivation**
The scripts in their current form  assume the runner wants to send a tx in while running the script. this makes them incompatible with multisigs and other implementations. 
This PR modifies the scripts to enable the tx to be done separately, by a multis or directly on etherscan.
=> fix(merkle-distributor-scripts): add option to print a table of output params rather than sending a tx

packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
**Motivation**
To support contracts using the `STABLESPREAD/USDC_18DEC` or `BCHNBTC_18DEC` price identifiers, default configs need to be added. These are the exact same configs as what are used for `STABLESPREAD/USDC` and `BCHNBTC`.
**Summary**
Adds default price feed configs.
**Testing**
Ran monitor bot locally
**Issue(s)**
NA
=> feat(financial-templates-lib): Add default pf configs

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/CryptoWatchPriceFeed.js, packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js, packages/financial-templates-lib/test/price-feed/CryptoWatchPriceFeed.js
**Motivation**
CW price feeds need to be able to compute a TWAP to allow us to generate more stable prices for funding rate calculations.
**Summary**
Uses the TWAP utility function to compute the TWAP across the cryptowatch array of price periods.
**Testing**
**Issue(s)**
N/A
=> feat(price-feeds): add twap to cryptowatch

packages/common/src/FindContractVersion.js
**Motivation**
EMP and Perp contract code hashes needs to be added back to `FindContractVersion.js`.
**Summary**
Adds mainnet latest EMP and Perp hashes to `FindContractVersion.js`.
**Testing**
**Issue(s)**
NA
=> fix(find-contract-version): Add EMP and perp contract hashes

packages/core/scripts/local/getHistoricalPrice.js, packages/core/scripts/local/getMedianHistoricalPrice.js, packages/financial-templates-lib/src/price-feed/BasketSpreadPriceFeed.js, packages/financial-templates-lib/src/price-feed/ExpressionPriceFeed.js
**Motivation**
Recent price requests for `STABLESPREAD` identifiers have highlighted that the `BasketSpreadPriceFeed` does not pass down a `verbose` flag to children pricefeeds, which may or may not implement additional logging useful for running the `getHistoricalPrice` script. Also removes any mentions of "medianizer" because this script is being used for al pricefeed now, not just medianizers.
**Summary**
Example run: `yarn truffle exec ./packages/core/scripts/local/getHistoricalPrice.js --network mainnet_mnemonic --identifier STABLESPREAD/USDC --time 1616936400`
**Testing**
=> improve(pricefeed-script): Pass verbose flag down from meta pricefeeds

packages/trader/src/RangeTrader.ts, packages/trader/src/TraderConfig.ts, packages/trader/src/index.ts
**Motivation**
There is no way to provide the range trader config via env variables.
**Summary**
Adds the range trader config to the index.ts file and passes it along.
**Testing**
**Issue(s)**
N/A
=> fix(trader): pass along range trader config from env variables

packages/financial-templates-lib/src/proxy-transaction-handler/DSProxyManager.js
**Motivation**
Minor trader fix to ensure the gas price estimation is updated before sending transactions.
**Summary**
Just added a few update calls.
**Testing**
**Issue(s)**
N/A
=> fix: call update on gas estimator before sending transactions

packages/monitors/src/OptimisticOracleContractMonitor.js
**Motivation**
Typically we want to be alerted loudly when OO proposals and requests are made. However, funding rate proposals are expected to be sent often, possibly every liveness period during times of extended volatility. Therefore we should detect which identifiers are funding rate ones and lower the default log level.
This PR makes the possibly erroneous assumption that identifiers that end with "_FR" are funding rate identifiers. Currently this is true but we should either refactor this bot or codify this rule off chain going forwards.
**Testing**
=> fix(optimistic-oracle-monitor): Reduce default log level for funding rate price requests

packages/voter-dapp/src/apollo/client.js, packages/voter-dapp/src/apollo/queries.js
**Motivation**
Old subgraph has now been replaced by two separate subgraphs ([repo](https://github.com/UMAprotocol/subgraphs)) that sync faster and better separate concerns, including one dedicated to DVM events. We still need to decide how we automate deployments to a `staging` and a `production` subgraph and we also should add these under the `umaprotocol` subgraph account instead of `nicholaspai` but TBD how we solve that. This fix enables the "vote stats" button to display again.
**Testing**
=> fix(voter-dapp): Change subgraph URL and query

packages/common/src/FindContractVersion.js
**Motivation**
This PR adds back a missing contract hash for the perpetual.
=> feat(find-contract-verion): add back perpetual hash

packages/core/networks/1.json
**Motivation**
As part of the UMA move to use DSProxys in liquidations and the roll out of the range trader, we require a main net DSProxy deployment. This PR adds this address to the networks file.
Note I have already verified this source code on etherscan as well as a deployed child DSProxy. all future DSProxies should auto-verify as a result.
=> feat(networks): Add DSProxyFactory

packages/common/src/PriceIdentifierUtils.js, packages/core/contracts/oracle/implementation/test/OptimisticRequesterTest.sol, packages/optimistic-oracle/src/proposer.js, packages/optimistic-oracle/test/proposer.js
**Motivation**
`uSTONKS` expires at the end of April and `uGAS` expires at the end of May. They are self-referential contracts that are using the latest version of the EMP. The bots currently are going to provide a price at expiry of the 2-hour TWAP instead of the final closing index value of uSTONKS. We need the bots to blacklist these two contracts so they do not propose a price. We assume that a manual price will occur instead.
The price request alert should still be emitted by the `optimistic-oracle-monitor` (i.e. the blacklist resides in the proposer bot, not the client shared between bot and monitor).
**Summary**
To check if an identifier is coming from an EMP post-expiry, we attempt to construct an EMP using the price request's …
=> feat(optimistic-oracle-proposer): Blacklist identifiers to skip post-expiry

packages/affiliates/payouts/dappmining/2021-03-29_2021-04-05_YD-BTC-JUN21_0012.json
**Motivation**
#2839
**Details**
Dapp mining for YD-BTC-JUN21 using .3 of dev mining rewards for this period: `Math.floor(5406.981699304750995364 * 0.3) = 1622`
```
{
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "5406.981699304750995364",
"weekNumber": 12,
"endDate": "04/05/2021 11:00 PM",
"startDate": "03/29/2021 11:00 PM",
"startTime": …
```
=> improve(affiliates): Dapp Mining rewards for YD-BTC-JUN21

packages/affiliates/payouts/dappmining/2021-03-29_2021-04-05_YD-ETH-JUN21_0012.json
**Motivation**
#2838
**Details**
Dapp mining for YD-ETH-JUN21 using .3 of dev mining rewards for this period: `Math.floor(12146.780307974979067477 * 0.3) = 3644`
```
{
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "12146.780307974979067477",
"weekNumber": 12,
"endDate": "04/05/2021 11:00 PM",
"startDate": "03/29/2021 11:00 PM",
"startTime": …
```
=> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21

packages/monitors/src/OptimisticOracleContractMonitor.js
**Motivation**
Some of these alerts are redundant, by default only the OO Monitor's `PriceProposed` event should be "info" level. The `PriceSettlement` is captured by the funding rate monitor's `FundingRateUpdated` log and the `PriceRequest` is redundant with `PriceProposed` for funding rates specifically:
**Testing**
=> improve(optimistic-oracle-monitor): Change default log level for PriceRequests and PriceSettlements to "debug" from "info"

packages/core/contracts/financial-templates/common/financial-product-libraries/CoveredCallFinancialProductLibrary.sol
**Motivation**
Updates financial product library to allow anyone to set the strike price for a newly deployed covered call. Previously, only the deployer of the _library_ contract can set the strike price for a covered call contract using the library, which limits the reusability of the library, as each deployer would need to deploy their own library.
There is a limited risk of an uneconomical griefing attack, where someone (for some reason) sets the strike price of a covered call contract before the deployer sets the strike price. There is no incentive to do so, but if it became a problem for some reason, deployment of the covered call and setting of the strike price could be done via an atomic transaction.
A different risk would be an …
=> feat(call): allow anyone to set strike price in covered call library

packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/src/price-feed/EthVixPriceFeed.js, packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js, packages/financial-templates-lib/test/price-feed/EthVixPriceFeed.js
**Motivation**
ethVIX and iethVIX allow for the trading of model-free expected volatility of ETH. ethVIX is best understood as a long volatility position while iethVIX is a short volatility position. The ethVIX index is very similar to the Cboe VIX which tracks the expected volatility of the S&P 500. By trading ethVIX or iethVIX traders can take long or short positions against volatility, either as a speculative trading instrument itself or a hedge for other speculative trades.
Here are some examples of how traders might use ethVIX and iethVIX:
- In early March of 2020, 0xAlice believes that the global pandemic will greatly affect the price of ETH but she’s not sure if it will drop like the stock market or go up as a safe haven asset. She buys ethVIX for roughly 80 USDC per token. On …
=> feat(price-feed): Proposed dVIX Price Feed Interface

packages/funding-rate-proposer/src/proposer.js
**Motivation**
`updateFundingRate` currently proposes funding rates to all Perpetuals in parallel, which means we cannot hardcode the `nonce` before passing transactions to the `ynatm` transaction manager. This leads `ynatm` to send ou transactions that bump gas but incorrectly increment the nonce, which causes unneccessary transaction reverts.
We need to update `ynatm` or implement an alternative transaction management feature that handles nonce management for parallel transactions. Until then, we need to submit transactions sequentially to `ynatm`.
**Testing**
=> improve(funding-rate-proposer): update funding rates sequentially in order to set nonce

packages/affiliates/liquidity-mining/yusdbtc-weekly-payouts/Week_30_Mining_Rewards.json
Last weeks LM had the wrong week number in the payout file due to a user error. The payouts recipients and amounts were correct, this was simply a semantic error.
=> fix(lm-payouts): address wrong week number in YD-BTC
