- sponsor-dapp/src/components/ContractDetails.js
- sponsor-dapp/src/components/ContractInteraction.js
- sponsor-dapp/src/utils/TokenizedDerivativeUtils.js
The contract enforces the correct limit independent of this PR. This PR just shows an informational message.
> Show max tokens that can be created

- v1/contracts/Finder.sol
- v1/test/Finder.js
> Emit an event when an interface address changes

- v1/contracts/FixedPoint.sol
- v1/contracts/ResultComputation.sol
- v1/contracts/test/FixedPointTest.sol
- v1/contracts/test/ResultComputationTest.sol
- v1/test/FixedPoint.js
- v1/test/ResultComputation.js
Things that still need to be done in follow up PRs:
1. Implement GAT (decide where this should go)
2. Implement a method to check whether a voter was correct. Decide whether to store a voter's votes.
Issue #413
> Add ResultComputation library based on mode computation

- common/globalTruffleConfig.js
This adds a backup infura API key so users without access to secret CI environment variables can still pass CI.
> Add a backup Infura API key

- common/globalTruffleConfig.js
> Add a backup Infura API key (#431)

- core/contracts/OracleInterface.sol
- core/contracts/Voting.sol
Needed in TokenizedDerivative unit tests.
> Extract OracleInterface from Voting.sol

- core/contracts/test/TestableTest.sol
- core/test/Testable.js
> Fix Testable test flake

- core/migrations/12_deploy_register_creator.js
- core/scripts/local/InitializeSystem.js
- core/test/Registry.js
- core/test/TokenizedDerivative.js
- core/utils/Enums.js
These roles are referenced from several places.
> Add Javascript object mirroring Registry.Roles

- core/contracts/test/FixedPointTest.sol
- core/test/FixedPoint.js
Signed-off-by: Roz Stengle <rosalind.stengle@gmail.com>
> Mixed comparison tests for FixedPoint library (fixes #458)

- core/contracts/TokenizedDerivative.sol
- core/test/TokenizedDerivative.js
I'm fairly confident that there are some edge cases and other state transitions that this PR doesn't correctly handle.
Issue #469 
> Pay final fee from TokenizedDerivative

- core/scripts/Voting.js
- core/test/scripts/Voting.js
- core/utils/Enums.js
While we build the persistence, I put in an in-memory persistence thing.
This approach will NOT work in practice, but can be used by unit tests.
Issue #491.
> Add scaffolding and main loop for automated voting system

- core/scripts/local/VoteGasEstimation.js
I think I forgot to commit this in the previous PR :(
> Move VoteGasEstimation script to right location

- core/scripts/Voting.js
- package.json
The price API will likely change. Just looking for comments!
Signed-off-by: Roz Stengle <rosalind.stengle@gmail.com>
> Retrieving prices for a request (identifier, time) for automated voting (#492)

- Automated.md
First stab at a document outlining the steps to set up automated voting system. This documentation is neither complete nor polished yet.
> Stab at steps to set up automated voting system

- Dockerfile
> Update docker run instructions

- core/scripts/local/VoteGasEstimation.js
> Parameterize rounds and voters in gas estimation script

- core/scripts/Voting.js
- core/test/scripts/Voting.js
Signed-off-by: Roz Stengle <rosalind.stengle@gmail.com>
> Moving API specific functionality away from fetchPrice

- core/contracts/Voting.sol
- core/contracts/VotingInterface.sol
This adds an interface for the Voting side of `Voting.sol`.
> Add VotingInterface

- ci/run_truffle_tests.sh
- core/networks/42.json
Adds a Kovan deployment and verify it in CI.
> Add Kovan deployment

- core/scripts/Voting.js
Add log messages on each iteration so the user can easily convince themselves that the script is still running.
> Add per-iteration log messages

- core/scripts/local/RequestOraclePrice.js
> Fix incorrect include in PriceRequest script

- common/Crypto.js
- core/contracts/Voting.sol
- core/scripts/Voting.js
- core/test/Voting.js
- core/utils/EncryptionHelper.js
> Support batch commit and persisting encrypted votes

- core/contracts/EncryptedSender.sol
- core/contracts/Voting.sol
- core/test/Voting.js
> Support batch reveals and reveals that remove the encrypted message

- core/scripts/local/AdvanceToNextVotingPhase.js
Helpful for local testing of the voter dapp.
Issue #532.
> Add helper script to advance to next voting phase

- voter-dapp/src/ActiveRequests.js
- voter-dapp/src/drizzleOptions.js
> Add column for vote status

- Dockerfile
- core/scripts/runCommand.sh
- core/scripts/runVoting.sh
This will allow [Cloud Run](https://cloud.google.com/run/) to execute arbitrary commands in the docker image.
> Use COMMAND env variable to set the docker command at runtime

- voter-dapp/src/ActiveRequests.js
The prices in the other states will be in the next PR (because they will require
the message signing code as well).
Issue #532. 
> Show revealed price from `VoteRevealed` events

- core/contracts/VotingToken.sol
Feel free to critique the specific choices of name/symbol.
> Add standard ERC20 metadata to token

- core/scripts/Voting.js
- core/test/scripts/Voting.js
- package.json
A few notes:
- The gmail sender seems to work fine on google cloud.
- I've read [some reports](https://nodemailer.com/usage/using-gmail/) of auth issues with directly authenticating against SMTP server since they do bot detection, but I haven't had any issues with testing locally and on google cloud instances located in the US.
Fixes #566
> Add gmail and console notifications to AVS

- common/Crypto.js
- core/scripts/Voting.js
- core/test/EncryptedSender.js
- core/test/Voting.js
- core/test/scripts/Voting.js
> [WIP] Rename `deriveKeyPairFromSignature` function

- core/scripts/local/RequestOraclePrice.js
> Reset nonce cache if it exists on a long running server

- package.json
This reverts commit 877bbf3b7f4325112086ecc15881ab6e1a4ed2cb.
> Rollback of Version change

- voter-dapp/src/ActiveRequests.js
> [WIP] Add (messy) ability to edit and save commits

- sponsor-dapp-v2/src/views/ManagePositions.js
This function was used in PR #598 only to simplify the git diff. No changes were made to the JSX in this PR.
Issue #595.
> Remove temporary local function

- sponsor-dapp-v2/src/components/common/ExpandBox.js
- sponsor-dapp-v2/src/drizzleOptions.js
- sponsor-dapp-v2/src/views/ManagePositions.js
> Fill in remaining fields in details box

- sponsor-dapp-v2/src/views/Withdraw.js
Thoughts?
The Deposit component is very similar to Withdraw, and I think all three of these hooks can be used there.
Issue #604
> Breakdown Withdraw into reusable hooks

- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/lib/routes.js
- sponsor-dapp-v2/src/views/Deposit.js
- sponsor-dapp-v2/src/views/ManagePositions.js
- sponsor-dapp-v2/src/views/Withdraw.js
NOTE: I made one change in `useCollateralizationInformation`, which is to treat `changeInShortBalance` as a positive change, i.e., it should be added to `totalHoldings`. That requires us to negate the value passed in from `Withdraw.js`.  
These components are very similar.
Issues #614  and #604 .
> Implement Deposit modal with hooks extracted from Withdraw

- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/views/Deposit.js
- sponsor-dapp-v2/src/views/Withdraw.js
> Removes `render` functions from functional components

- common/FormattingUtils.js
- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/lib/routes.js
- sponsor-dapp-v2/src/views/Borrow.js
- sponsor-dapp-v2/src/views/Deposit.js
- sponsor-dapp-v2/src/views/ManagePositions.js
- sponsor-dapp-v2/src/views/Withdraw.js
Similar to the Deposit and Withdraw components, this component had to be
significantly modified, but we could reuse some custom hooks.
In all of these modals, I'm going to punt the helper texts and  and conditional enabling/disabling the button. I'll make those improvements in a separate PR at the end.
Issue #622. 
> Implement Borrow component to create tokens

- sponsor-dapp-v2/src/lib/routes.js
- sponsor-dapp-v2/src/views/ManagePositions.js
- sponsor-dapp-v2/src/views/Repay.js
> Implement Repay component to redeem tokens

- sponsor-dapp-v2/src/views/Borrow.js
- sponsor-dapp-v2/src/views/Repay.js
> Add helper text for Borrow and Repay components

- sponsor-dapp-v2/src/views/Borrow.js
- sponsor-dapp-v2/src/views/Repay.js
No other changes.
Fixes #622. Fixes #629.
> Remove temporary render methods

- core/config/identifiers.json
- core/scripts/PublishPrices.js
- sponsor-dapp-v2/src/identifiers.json
- sponsor-dapp-v2/src/lib/custom-hooks.js
This PR does a few things:
- Adds a few new types of price feeds: barchart equities, CMC total market cap index, and constant price feeds.
- Adds new identifiers in identifiers.json for the sponsor dapp v2.
- Integrates the identifiers.json config with the sponsor dapp v2.
Fixes #644.
> Update price feeds

- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/views/Start.js
- sponsor-dapp-v2/src/views/ViewPositions.js
> Add DAI txn faucet to button

- sponsor-dapp-v2/src/components/Step5.js
- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/views/Borrow.js
> Add liquidation price

- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/views/ViewPositions.js
This took a little more maneuvering than usual because it needed to be computed dynamically.
> Add liquidation price to ViewPositions page

- sponsor-dapp-v2/src/views/Borrow.js
> Show identifier name rather than hardcoded `BTC/USD`

- sponsor-dapp-v2/src/assets/scss/modules/_btn.scss
- sponsor-dapp-v2/src/components/ApproveOrDefault.js
- sponsor-dapp-v2/src/components/Position.js
- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/views/Repay.js
This is pretty standard outside of the modification of the scss. 
I had to modify it because the span and strong components were inheriting properties from the context. Specifically, the span was inheriting a red color, making the text invisible on top of the button. Using divs, the text styling may be slightly different than the other processing buttons, but everything is visible, in the expected color, and works.
Feel free to tweak the above as you see fit as it's certainly not a perfect solution. 
Note: I won't be able to respond to feedback on this PR before they need to be submitted, so if you do have requested changes, feel free to just copy my branch: https://github.com/mrice32/protocol/tree/token_preapproval and modify it to create new PR with the fixes.
Fixes #650.
> Token preapproval

- sponsor-dapp-v2/src/components/application/index.js
> Display static message suggesting Rinkeby if Drizzle fails to load

- sponsor-dapp-v2/package.json
- sponsor-dapp-v2/src/components/Position.js
- sponsor-dapp-v2/src/components/Step3.js
- sponsor-dapp-v2/src/components/Step4.js
- sponsor-dapp-v2/src/components/Step5.js
- sponsor-dapp-v2/src/components/application/index.js
- sponsor-dapp-v2/src/lib/custom-hooks.js
- sponsor-dapp-v2/src/lib/google-analytics.js
- sponsor-dapp-v2/src/views/Borrow.js
- sponsor-dapp-v2/src/views/Deposit.js
- sponsor-dapp-v2/src/views/Landing.js
- sponsor-dapp-v2/src/views/ManagePositions.js
- sponsor-dapp-v2/src/views/Repay.js
- sponsor-dapp-v2/src/views/Start.js
- sponsor-dapp-v2/src/views/Steps.js
- sponsor-dapp-v2/src/views/ViewPositions.js
- sponsor-dapp-v2/src/views/Withdraw.js
These are showing up on Google Analytics. We can revise them later as we
decide what's missing, what's extraneous, etc.
> Set up Google Analytics with pageviews and custom events

- core/config/identifiers.json
> added custom constant index for USD/ETH

- README.md
Still requires some "TBD" sections to be filled in
> Add some v1 instructions

- core/config/identifiers.json
- sponsor-dapp-v2/src/components/Step2.js
- sponsor-dapp-v2/src/components/Step3.js
The "Details" dropdown already handles perpetual contracts correctly.
Fixes #686 
> Add Perpetual as an expiry

- core/scripts/Voting.js
- core/test/scripts/Voting.js
Let me know if you think this'll be too spammy.
> Always notify user and keep going if some commits fail

- core/scripts/Voting.js
- core/test/scripts/Voting.js
- package.json
NOTE: It sppears that some symbols aren't available in Intrinio's sandbox
instance, but would presumably be available once we have a real
subscription.
> Fetch equities data from Intrinio and also support Constant prices

- core/scripts/Voting.js
We may be moving off Barchart soon, but we might as well commit this
working code.
Happy to also not submit this PR.
> Fetch futures prices from Barchart

- core/scripts/Voting.js
- core/test/scripts/Voting.js
> [WIP] Add numerator/denominator calculation to AVS

- sponsor-dapp-v2/src/components/Step2.js
Regina wants this text to be slightly modified before demoing this at devcon.
> Add (alpha) to Perpetual text

- core/contracts/DesignatedVoting.sol
- core/contracts/Withdrawable.sol
- core/test/DesignatedVoting.js
> Add DesignatedVoting contract for two-key voting system

- .circleci/config.yml
- .prettierrc
- core/scripts/Voting.js
- package.json
> Add remaining data sources to AVS

- core/contracts/TokenizedDerivative.sol
> Document TokenizedDerivative.sol in natspec format

- core/contracts/AddressWhitelist.sol
- core/contracts/AdministrateeInterface.sol
- core/contracts/ContractCreator.sol
- core/contracts/DesignatedVoting.sol
- core/contracts/EncryptedSender.sol
- core/contracts/ExpandedIERC20.sol
- core/contracts/Finder.sol
- core/contracts/LeveragedReturnCalculator.sol
- core/contracts/ManualPriceFeed.sol
- core/contracts/MultiRole.sol
- core/contracts/PriceFeedInterface.sol
- core/contracts/ReturnCalculatorInterface.sol
- core/contracts/Store.sol
- core/contracts/StoreInterface.sol
- core/contracts/Testable.sol
- core/contracts/TestnetERC20.sol
- core/contracts/VoteTiming.sol
- core/contracts/VotingToken.sol
We prefer using `@title` over file-level comments, so this PR also
deletes all remaining file-level comments.
Issue #726 
> Clean up titles for all smart contracts

- core/contracts/Migrations.sol
> Add @title annotation for Migrations.sol

- documentation/explainers/dvm_interfaces.md
This is an expanded version of explaining the oracle interface.
> How Users and Voters Interact with the DVM doc

- documentation/tutorials/customizing-tokens-via-cli.md
> Add tutorial for basic command line interactions

- documentation/tutorials/running-the-avs.md
Sorry about the nasty table. It looks fine when rendered but the markdown is rough.
> Add AVS Instructions Docs

- core/contracts/VotingInterface.sol
- documentation/explainers/dvm_interfaces.md
Primarily, the behavior of retrieve rewards has changed.
> Update documentation for changes in #751

- documentation/explainers/tokenized-derivative.md
Adds an explainer for the Tokenized Derivative (mainly the initialization parameters).
> Tokenized Derivative Docs

- documentation/explainers/dvm_interfaces.md
> Update API documentation for changes in #775

- core/contracts/Governor.sol
- core/contracts/Voting.sol
- core/contracts/VotingToken.sol
- core/migrations/15_deploy_governor.js
- core/test/Governor.js
This PR should conclude all contract changes in #781.
> Update contract permissioning in Voting, VotingToken, and Governor contracts

- core/migrations/3_deploy_voting_token.js
- core/test/DesignatedVoting.js
- core/test/Voting.js
- core/test/VotingToken.js
- core/test/scripts/Voting.js
> Add minting to migrations

- voter-dapp/src/Dashboard.js
- voter-dapp/src/DesignatedVotingDeployment.js
- voter-dapp/src/DesignatedVotingTransfer.js
This flow needs to be executed from the *voting* account, and the user
will have to provide that ownership (or cold wallet) address.
> Add flow to deploy DesignatedVoting contract from voter dapp

- core/contracts/Voting.sol
Signed-off-by: Christopher Maree <christopher.maree@gmail.com>
close #779
> Updated contract requires to decrease byte size

- core/.env_sample
- documentation/explainers/tokenized-derivative.md
- documentation/tutorials/creating-tokens-locally.md
- documentation/tutorials/customizing-tokens-via-cli.md
- documentation/tutorials/deploy-your-own-price-feed.md
Added small updates to tutorials and other docs.
> Documentation updates

- core/scripts/local/RequestOraclePrice.js
> Fix typo in interface name

- core/scripts/cli/cli.js
- core/scripts/cli/cli_entry.sh
@ptare made some good points in #845, but I merged it before he had a chance to add his comments.
This PR adds better error handling for the CLI tool, as @ptare suggested.
> Add better error handling in the CLI tool

- core/scripts/cli/cli.js
- core/scripts/cli/vote.js
- core/scripts/cli/wallet.js
- package.json
This PR implements the beginnings of the CI script which includes a menu system that can be traversed by the user to execute specific functions. 
To quickly run the script execute from `/core`:
```
./scripts/cli/cli_entry.sh --network test
```
> Cli menu list

- core/contracts/VoteTiming.sol
- core/contracts/Voting.sol
- core/migrations/4_deploy_voting.js
- core/test/Voting.js
> Expire rewards after a certain time

- core/contracts/financial_templates/implementation/Liquidatable.sol
- core/test/financial_templates/Liquidatable.js
Issue is explained in #924 , I simply added a `collateralAmount` to the method and added a test to `Liquidatable`
Resolves #924 
> Adds parameter to `createLiquidation` to protect against possible front-running of pending liquidations

- ci/run_truffle_tests.sh
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial_templates/PricelessPositionManager.js
- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/delay.js
- financial-templates-lib/test/ExpiringMultiPartyClient.js
Some changes to address in follow up PRs:
1. Figure out how to subscribe to events
2. How to link to the contracts themselves
Issue #939 
> Add method to get current positions

- core/contracts/financial-templates/implementation/Liquidatable.sol
- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/test/ExpiringMultiPartyClient.js
Next step:
Design API for how, given a price, to check whether a position is liquidatable. And how to determine if a liquidation is disputable.
Issue #939 
> Add method to get undisputed liquidations

- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/test/ExpiringMultiPartyClient.js
Remaining tasks:
1. API/method for determining when a liquidation should be disputed.
2. Try to get event subscriptions to work. Or not.
Issue #939 
> Add method to determine which positions are undercollateralized

- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/test/ExpiringMultiPartyClient.js
The API for this is a bit clunky, I don't love it.
Issue #939 
> Add method to detect disputable liquidations

- financial-templates-lib/test/ExpiringMultiPartyClient.js
Not sure how this ever passed presubmits.
> Fix build by removing duplicate import

- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/test/financial-templates/Liquidatable.js
- financial-templates-lib/ExpiringMultiPartyClient.js
Expiry variable doesn't need to be stored since we already have liquidation time.
> Remove expiry variable

- core/contracts/oracle/implementation/Voting.sol
- core/test/oracle/Voting.js
> Change Voting.sol Requirement: GAT < 100% to <= 100% 

- liquidator/index.js
- liquidator/liquidator.js
- liquidator/test/Liquidator.js
This PR improves the entry script `index.js` for starting the liquidator bot to correctly initiate async calls to the liquidator. Additionally, the liquidator module was refactored to submit transactions on chain using parallel async handeller.
Logging in the liquidator was also improved to show information about all the liquidations that were submitted.
> Added additional logic for liquidations and async calls

- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/Logger.js
- financial-templates-lib/package.json
- liquidator/index.js
- liquidator/liquidator.js
- liquidator/package.json
- liquidator/test/Liquidator.js
- package.json
This PR adds a winston logger to the current implementation. close #1014. A sample log result of liquidating 5 positions can be seen below:
```
2020-03-05 16:29:18 [info]: {
"at": "liquidator#index",
"message": "liquidator started",
"empAddress": "0xfd40ACe9CC8CbDc73A12EBda703637c1Cbe999F2",
"currentPrice": 1.3
}
2020-03-05 16:29:18 [info]: {
"at": "liquidator",
"message": "Checking for under collateralized positions"
}
2020-03-05 16:29:19 [info]: {
"at": "ExpiringMultiPartyClient",
"message": "client updated"
}
2020-03-05 16:29:19 [info]: {
"at": "liquidator",
"message": "undercollateralized positions detected!",
"number": 5,
"underCollateralizedPositions": [
{
"sponsor": "0x6e4400769c2Cf2296b7071768d8769eBE06DAa92",
"requestPassTimestamp": "0",
"withdrawalRequestAmount": "0", …
```
> Liquidator logger

- core/test/scripts/PublishPrices.js
This is it, the one you've all been waiting for! Will reduce CI runtime by up to 50%!
Fixes #1010 
> Remove unit tests that depend on external API's

- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/test/financial-templates/Liquidatable.js
This PR adds a small change to the events emitted by the create liquidation event to close #875
> Improve liquidatable event

- core/scripts/cli/cli.js
- core/scripts/cli/sponsor.js
> Add sponsor as a (stub) option in UMA CLI

- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial-templates/PricelessPositionManager.js
> Check collateralization ratio of newly created tokens, rather than new Position

- core/scripts/cli/sponsor.js
- core/scripts/cli/sponsor/listMarkets.js
> Add sponsor CLI directory and stub ListMarkets

- core/test/financial-templates/Liquidatable.js
- core/test/financial-templates/PricelessPositionManager.js
Make variable naming consistent, fixes #1048
> Replace priceTrackingIdentifier with priceFeedIdentifier

- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial-templates/Liquidatable.js
> Allow Liquidation to be disputed and have rewards withdrawn post expiry

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/listMarkets.js
- core/scripts/cli/sponsor/showMarketDetails.js
> Show market details and initial create flow

- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showMarketDetails.js
> Improve the kick off point for actions from ListMarkets

- core/scripts/cli/sponsor/showMarketDetails.js
Based on a suggestion from @nicholaspai on PR #1073.
Issue #1040 
> Refactor code for actions in showMarketDetails

- core/scripts/cli/sponsor/redeem.js
> Implement redeem flow for sponsors

- core/scripts/cli/sponsor/showMarketDetails.js
> Remove unused variable

- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transfer.js
> Implement deposit and transfer flows

- common/PublicNetworks.js
- core/contracts/financial-templates/implementation/WETH9.sol
- core/migrations/19_deploy_local_weth.js
- package.json
> Add copy of WETH9 and local migration for it

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/currencyUtils.js
- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/withdraw.js
- core/scripts/local/DeployEMP.js
> Wrap and unwrap ETH in sponsor CLI

- core/scripts/cli/sponsor/currencyUtils.js
- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/withdraw.js
> Improve messaging around remaining transactions

- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/viewLiquidationDetails.js
We could definitely do a lot more here, but I'm not sure how important this flow is.
Issue #1040
> Display and select liquidations

- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/test/financial-templates/Liquidatable.js
> Converge all Liquidatable.sol variable names referencing the liquidation ID into "liquidationId"

- liquidator/index.js
- liquidator/test/index.js
> Can dry run index.js for Liquidator bot

- .vscode/settings.json
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
This PR adds commenting and formatting changes to the `PricelessPositionManager.sol` such that it conforms to the solidity Natspec and styling guide.
> PricelessPositionManager.sol natspec

- core/contracts/financial-templates/implementation/FeePayer.sol
This PR adds natspec to the feepayer
> FeePayer.sol natspec

- core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
> ExpiringMultiPartyCreator.sol natspec

- financial-templates-lib/UniswapPriceFeed.js
- financial-templates-lib/test/UniswapPriceFeed.js
This is the initial stub for the Uniswap price feed class. Currently, it only computes the current Uniswap price.
Issue #1138.
> Add initial uniswap price feed library

- core/contracts/financial-templates/implementation/Liquidatable.sol
Resolves #984 in the name of consistency with `PricelessPositionManager`
> Refactor Liquidatable Modifiers to call Internal Methods

- core/test/financial-templates/Liquidatable.js
> Checks Liquidatable State Phase changes

- core/test/financial-templates/PricelessPositionManager.js
> Checks PricelessPositionManager State phase changes

- core/contracts/financial-templates/implementation/SyntheticToken.sol
> SyntheticToken.sol natspec

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transactionUtils.js
- core/scripts/cli/sponsor/withdraw.js
Use round ceil in `create` flow to make sure we send enough collateral.
Various small formatting and text improvements.
Issue #1040
> Formatting and rounding fixes

- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
There are a few spelling mistakes & typos that made it through the previous PRs.
> fix spelling mistakes in PricelessPositionManager.sol

- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/scripts/PrecisionErrors.js
- core/scripts/cli/sponsor/withdraw.js
- core/scripts/local/AdvanceEMP.js
- core/scripts/local/DeployEMP.js
- core/test/financial-templates/PricelessPositionManager.js
> Make definition of "expiry" for requested withdrawals consistent with rest of EMP

- core/scripts/cli/sponsor.js
- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/currencyUtils.js
- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/withdraw.js
Specifically:
1. Support non-WETH collateral currencies
2. Eliminate top level menu with only one option in it
3. Remove actions if a pending withdrawal is present
> Small tweaks to collateral currencies and menu options

- core/networks/1.json
- core/networks/4.json
> Updated networks files to include WETH9 addresses

- financial-templates-lib/UniswapPriceFeed.js
- financial-templates-lib/test/UniswapPriceFeed.js
This PR adds a TWAP calculation over a window ending at the current time. 
There are some simple test cases for now. I've added TODOs for test cases that should be added once #1151 is merged.
Issue #1138.
> Add current TWAP calculation

- core/scripts/cli/sponsor.js
- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/currencyUtils.js
- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/listExpiredMarkets.js
- core/scripts/cli/sponsor/marketUtils.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transactionUtils.js
- core/scripts/cli/sponsor/withdraw.js
- core/scripts/local/DeployEMP.js
See Issue #1156 for details.
Specifically in this PR (numbers correspond to list in issue)::
1. Provide collateral currency when listing markets
2. Change "borrow" to "mint" language
3. Expand messaging around withdraw request vs. instantaneous
6. Show (1/N) when running multiple transactions
8. Reprint sponsor's position after any action (so they can see what
changed)
Start building flow around expiration by first allowing you to see
expired markets and their states.
> Respond to user feedback on CLI

- financial-templates-lib/ExpiringMultiPartyClient.js
- financial-templates-lib/test/ExpiringMultiPartyClient.js
Part of #1176 
Adds external wrapper methods to `_update()`:
- `update()`: calls `_update()` unless within update threshold
- `forceUpdate()`: calls `_update()`
The idea is that the calling module (i.e. liquidator and disputer bot) would call `forceUpdate()` once before polling, and then call `update()` after each iteration. After any liquidation or dispute, or any action that clearly will change the state of the EMP client, they will call `forceUpdate()`.
> EMP Client: add external methods update() and forceUpdate()

- core/contracts/financial-templates/implementation/FeePayer.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial-templates/Liquidatable.js
- core/test/financial-templates/PricelessPositionManager.js
> Add events for ending a sponsor and paying fees

- core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
This should probably be programmatically enforced in some way, but with limited time, a comment is probably sufficient.
> Add comment about renouncing ownership of AddressWhitelist

- core/test/oracle/Finder.js
> Move Finder test to correct directory

- core/contracts/common/implementation/MultiRole.sol
- core/contracts/common/implementation/Testable.sol
- core/contracts/common/implementation/Withdrawable.sol
- core/contracts/oracle/implementation/ContractCreator.sol
> [P1-N16] Mark contracts not meant to be instantiated as `abstract`

- core/contracts/oracle/implementation/DesignatedVoting.sol
- core/contracts/oracle/implementation/Store.sol
> [P1-N13] Remove redundant inheritance of MultiRole

- documentation/community/previous_and_upcoming_events.md
> Add Liquid Staking Working Group call

- documentation/map.txt
- documentation/oracle/governance/UMA_token_holder_responsibilities.md
- documentation/oracle/governance/adding_a_price_identifier.md
This adds another section to the proposed "Governance" section of the docs site.
> Create "Adding a price identifier"

- core/contracts/oracle/implementation/DesignatedVoting.sol
- core/contracts/oracle/implementation/Governor.sol
- core/contracts/oracle/implementation/Registry.sol
- core/contracts/oracle/implementation/ResultComputation.sol
- core/contracts/oracle/implementation/Voting.sol
This PR fixes a number of errors in the contracts comments.
> [P1-L12] Address a number of erroneous comments through the DVM

- core/contracts/oracle/implementation/Voting.sol
- core/test/oracle/Voting.js
> [P1-L16] Use SafeMath to add uints for rewards expiration time

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/listExpiredMarkets.js
- core/scripts/cli/sponsor/listMarkets.js
- core/scripts/cli/sponsor/marketUtils.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showExpiredMarketDetails.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transactionUtils.js
- core/scripts/cli/sponsor/withdraw.js
Also add more details to the expired markets.
Issue #1156 
> Wording and copy fixes to the sponsor CLI

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/deposit.js
- core/scripts/cli/sponsor/marketUtils.js
- core/scripts/cli/sponsor/redeem.js
- core/scripts/cli/sponsor/showExpiredMarketDetails.js
- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transactionUtils.js
- core/scripts/cli/sponsor/transfer.js
- core/scripts/cli/sponsor/viewLiquidationDetails.js
- core/scripts/cli/sponsor/withdraw.js
Almost certainly missed some.
Issue #1156 
> Use template literals consistently in sponsor CLI

- core/contracts/oracle/implementation/Store.sol
- core/test/oracle/Store.js
This PR adds a test that verifies the late fee behavior and documentation to the Store function describing how the late fee is computed.
> [P1-N14] Test and document late fee behavior

- package.json
> Update openzeppelin import

- core/contracts/oracle/implementation/Store.sol
- core/migrations/8_deploy_store.js
- core/test/oracle/Store.js
Initialize regular and late fees in the Store constructor rather than allowing them to default to 0.
> [P1-L22] initialize fee percentages in Store constructor

- documentation/synthetic_tokens/known_issues.md
Signed-off-by: Christopher Maree <christopher.maree@gmail.com>
> GCR front running known issue

- core/contracts/oracle/implementation/VoteTiming.sol
> [P1-N01] Add clarifying comment about initial round ID not starting at 0 or 1

- core/migrations/8_deploy_store.js
> Fix bug in Store migration to respect controllableTiming

- core/scripts/cli/voting/filterRequestsByRound.js
- voter-dapp/src/ActiveRequests.js
The smart contract changes were in PR #1231.
> Update dapp and voter CLI to use EncryptedVote events

- core/scripts/DeploySyntheticTokens.js
If useful, we could do a lot more to generalize this script.
> Add helper script to deploy EMPs based on a CSV config

- core/networks/42.json
This is the commit hash for the deployment: b2f75de71dc88c546b40b150597824152da78827
> Update to latest Kovan deployment

- documentation/synthetic_tokens/tutorials/creating_from_truffle.md
Adds "minSponsorTokens" and "timerAddress" parameters.
> Update with 2 add'l parameters

- STYLE.md
Resolves #1277 to match changes described in #1271 
> Update STYLE.md with latest guidelines

- common/PublicNetworks.js
This PR corrects the Dai address in the `PublicNetworks.js` file. Additionally the `wethAddress`s on all networks were updated to contain the correct cammel case checksum.
> Update Dai network address

- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial-templates/PricelessPositionManager.js
> [P02-L04] Fix unsafe addition of current time and withdrawal liveness

- core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
- core/contracts/financial-templates/implementation/FeePayer.sol
- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/contracts/financial-templates/implementation/SyntheticToken.sol
- core/contracts/financial-templates/implementation/TokenFactory.sol
- core/test/financial-templates/Liquidatable.js
- financial-templates-lib/ExpiringMultiPartyEventClient.js
This PR addresses a number of typos through the NFCT. This also includes fixing a number of formatting and spacing issues with comments and long lines.
> [P2-N14] Fixed contract typos NFCT

- core/scripts/local/ClaimAllRewards.js
Add a local script that will automatically claim all rewards for all voters where possible in a given round.
> Add ClaimAllRewards script

- core/contracts/financial-templates/implementation/FeePayer.sol
> [P02-N07] Add view modifier to function that doesn't modify storage

- core/contracts/oracle/implementation/ContractCreator.sol
> Remove hardcoded "registry" string in ContractCreator

- ci/deploy_to_staging.sh
This reverts commit 4a9333e8d9b335ae0d9af6402e96d65557dc6d8c.
> Unfreeze voter dapp

- core/networks/1.json
Update the mainnet addresses to those that were created in UMIP-3.
> Update mainnet addresses

- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
> [P02-N04] Document what token approvals each method call requires

- core/contracts/common/implementation/Testable.sol
- core/contracts/oracle/implementation/DesignatedVoting.sol
- core/contracts/oracle/implementation/Governor.sol
- core/contracts/oracle/implementation/VoteTiming.sol
- core/contracts/oracle/interfaces/VotingInterface.sol
> Fix typos in DVM comments

- documentation/getting_started/architecture_overview.md
- documentation/getting_started/priceless_defi_contracts.md
- documentation/getting_started/uma_oracle_design.md
Some markdown files are not conforming to the linter spec. This PR fixes this
> Lint additional markdown files

- core/scripts/local/DeployEMP.js
> Fix DeployEMP.js script for PR #1308

- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transfer.js
- core/scripts/local/DeployEMP.js
> Update Transfer flow in Sponsor CLI

- core/contracts/financial-templates/implementation/FeePayer.sol
> [P02-N03] Use local variable instead of calling helper function twice

- documentation/developer_reference/bug_bounty.md
- documentation/oracle/governance/UMA_token_holder_responsibilities.md
> add link to OZ audit

- core/contracts/financial-templates/implementation/FeePayer.sol
- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
- core/test/financial-templates/ExpiringMultiPartyCreator.js
- core/test/financial-templates/Liquidatable.js
- core/test/financial-templates/PricelessPositionManager.js
Decided not to rename create. Clarified the functionality in a docstring instead.
> [P02-N12] Adjust naming of variables and functions

- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/transfer.js
> Update sponsor CLI for naming changes in #1341

- core/contracts/financial-templates/implementation/FeePayer.sol
- core/contracts/financial-templates/implementation/Liquidatable.sol
- core/contracts/financial-templates/implementation/PricelessPositionManager.sol
> [P02-L05] Fix comments and docstrings

- documentation/community/previous_and_upcoming_events.md
> add DeFi Discussions talks

- financial-templates-lib/price-feed/MedianizerPriceFeed.js
I forgot to add this commit to #1357. This just adds better comments around exactly what operation each medianizer method performs.
> Add missing comments to MedianizerPriceFeed

- documentation/getting_started/priceless_defi_contracts.md
- documentation/getting_started/uma_oracle_design.md
> fix relative links

- monitors/test/CRMonitor.js
I'm not sure how this passed CI which started failing on [this commit](https://github.com/UMAprotocol/protocol/commit/0397482bb39dba706dc60b38cdb43a98e152cc2c).
> Fix CR Monitor test

- core/contracts/financial-templates/implementation/FeePayer.sol
> Fix a typo in FeePayer

- core/scripts/cli/sponsor/showMarketDetails.js
- core/scripts/cli/sponsor/viewLiquidationDetails.js
Also fix an issue where non-WETH currencies were getting unwrapped.
> Check if a liquidation is withdrawable before withdrawing

- documentation/ROOT/index.md
> redo intro

- documentation/getting_started/uma_oracle_design.md
> add changes requested by allison

- documentation/synthetic_tokens/tutorials/prerequisites.md
> add ganache prereq

- core/networks/42.json
This PR updates our kovan networks to include the latest verified deployed version.
> updated networks

- documentation/community/previous_and_upcoming_events.md
> add Allison's event

- documentation/map.txt
- documentation/oracle/security.md
> create security section

- financial-templates-lib/price-feed/Networker.js
- liquidator/index.js
- liquidator/liquidator.js
- liquidator/test/Liquidator.js
- liquidator/test/index.js
Integrates the configurable price feed modules into the liquidator bot.
> Integrate price feed into liquidator

- liquidator/liquidator.js
Update should be called before the price is queried.
> Fix liquidator price feed update

- Dockerfile
This PR updates the node version in our docker containers to use docker 12.
> Update docker version

- disputer/disputer.js
- disputer/index.js
- disputer/test/Disputer.js
- disputer/test/index.js
Pretty similar to the liquidation bot integration.
> Integrate price feed into dispute bot

- common/ObjectUtils.js
- disputer/disputer.js
- liquidator/liquidator.js
> Refactor default configuration object for Liquidator/Disputer bots into common module

- documentation/community/previous_and_upcoming_events.md
> add Hart's event

- disputer/index.js
- liquidator/index.js
- monitors/index.js
This PR addresses a number of inconsistencies with the price feed integration. For one the liquidator and disputor bots now enforce the provision of a price feed configuration.
> Clean up bot price feed integration

- documentation/developer_reference/bug_bounty.md
- documentation/synthetic_tokens/known_issues.md
> add link to audit and change scope

- documentation/map.txt
- documentation/oracle/economic_architecture.md
> add economic architecture section

- documentation/synthetic_tokens/explainer.md
> remove sentence in synthetic token explainer

- documentation/map.txt
- documentation/oracle/known_issues.md
> reorg oracle section

- documentation/community/interviews_and_press.md
> add podcast and blog post links

- documentation/getting_started/architecture_overview.md
- documentation/getting_started/uma_oracle_design.md
- documentation/oracle/tutorials/integrating_the_dvm.md
> add cross-references between pages

- documentation/synthetic_tokens/tutorials/creating_from_truffle.md
This PR fixes a broken element in the Truffle tutorial as a result of the upgrade to use one universal time source within testing UMA contracts.
> Updated truffle tutorial to include timer

- documentation/oracle/tutorials/voting_with_uma_tokens.md
> add links to voter dapp and instructions

- common/FormattingUtils.js
This fixes the number formatting so it doesn't add commas after the decimal point.
> Fix decimal formatting

- disputer/index.js
- financial-templates-lib/logger/Logger.js
- liquidator/index.js
- monitors/index.js
This PR removes the hacky delay in the logger when yielding the final promise.
Inspiration: https://github.com/winstonjs/winston/issues/1250#issuecomment-452128291
> Improve logger promise handling

- README.md
This PR adds the coveralls reports badge to our readme.
> Add coveralls reports to readme

- common/gckms/GckmsConfig.js
This will allow us to pass the config similarly to how we pass other configs.
> Allow GCKMS config to be passed in via env

- financial-templates-lib/price-feed/UniswapPriceFeed.js
This PR fixes a type in the UniswaPriceFeed which resulted in the price feed breaking downstream bots.
> Patch Uniswap Price feed

- core/scripts/cli/cli.js
- voter-dapp/src/ActiveRequests.js
> Block voter-cli until we fix encryption compatibility issues

- core/scripts/local/DeployEMP.js
Keeping this as a draft because I think we should discuss the pros/cons of longer symbols.
> Update synthetic token params

- monitors/BalanceMonitor.js
- monitors/CRMonitor.js
- monitors/ContractMonitor.js
- monitors/SyntheticPegMonitor.js
- monitors/test/BalanceMonitor.js
This PR updates the default symbol in the bots. This is a temp fix until we improve this element of the bots.
> Update bot default names

- core/scripts/local/DeployEMP.js
- Change identifier name to ETH/BTC
- Change synthetic symbol to "...-AUG20"
> Fix EMP config

- core/networks/1.json
These addresses came out of UMIP-2.
> Add mainnet addresses

- documentation/getting_started/uma_oracle_design.md
> fix PFC typo

- documentation/oracle/known_issues.md
> Create bribery attack section

- documentation/synthetic_tokens/explainer.md
> fix Github implementation link

- core/scripts/cli/sponsor/create.js
- core/scripts/cli/sponsor/showMarketDetails.js
> Handle min position size in CLI create step

- disputer/index.js
- disputer/test/index.js
- liquidator/index.js
- liquidator/test/index.js
`index.js` root file of disputer and liquidator instantiate a `TokenBalanceClient` which constructs `ERC20` token objects that we can use to set allowances. I set these once to the max int value for convenience.
Resolves #1491
> Disputer and Liquidator bots pre-approve EMP to transfer their tokens

- monitors/SyntheticPegMonitor.js
- monitors/test/SyntheticPegMonitor.js
> Increase precision of price's displayed by SyntheticPegMonitor to 4

- liquidator/index.js
This small PR adds the ability to add a custom liquidator config. The bots had support for this before but the config param was never provided to the bots on construction.
> Added liquidator config to bot initilization parameters

- monitors/ContractMonitor.js
- monitors/index.js
- monitors/test/ContractMonitor.js
This pull request enables a config object to be passed to the monitor bot. This object specifies an arrays containing addresses of liquidator and dispute bots. If an address included in these arrays creates a position, creates a liquidation or is liquidated the log text will be updated accordingly. This is not new functionality; rather this PR enables the functionality by correctly passing in the configs.
This PR also refines parameter validation in the monitor bot and adds additional comments.
> Contract monitor configuration parameters

- common/globalTruffleConfig.js
> Force truffle to estimate gas

- ci/deploy_to_staging.sh
In order to allow prod to be moved up to more recent versions periodically, we'll need to preserve versions that aren't handling traffic. This change will preserve 100 versions to keep us below the 210 limit, but leave space for a large number of recent versions for us to choose from when doing a prod release.
Part of #1534.
> Preserve last 100 GAE versions that aren't receiving traffic

- documentation/map.txt
- documentation/synthetic_tokens/tutorials/liquidation.md
- package.json
> Create liquidation bot tutorial

- ci/run_truffle_tests.sh
Signed-off-by: Christopher Maree <christopher.maree@gmail.com>
> Remove check in CI to make CI independent of test networks

- financial-templates-lib/clients/TokenBalanceClient.js
- reporters/SponsorReporter.js
- reporters/index.js
This PR implements the first half of the Daily reporter PRD. This includes the implementation of 1) UMA Risk table and 2) Sponsor table. The screenshot below shows this initial output:
> Daily reporter implementation

- CONTRIBUTING.md
- STYLE.md
> Add js function declaration style guidelines

- monitors/CRMonitor.js
- monitors/test/CRMonitor.js
> Include liquidation price in CR alert

- financial-templates-lib/clients/ExpiringMultiPartyEventClient.js
- financial-templates-lib/test/clients/ExpiringMultiPartyEventClient.js
> Add LiquidationWithdrawn and SettleExpiredPosition events to EMPEventClient

- common/FormattingUtils.js
> Fix formatWithMaxDecimals to correctly handle negatives

- reporters/SponsorReporter.js
- reporters/index.js
This small PR refines the `SponsorReporter` to conform to the format laid out in the `GlobalSummaryReporter` as laid out by @nicholaspai  by including an additional comment before each section printed out in the console. This PR also fixes a small issue with the provided world emoji.
Comment, new emoji and different text color for starting script.
World emoji before:
World emoji after:
> Small refinement to daily reporter format

- CONTRIBUTING.md
> Add no PR without an issue rule to CONTRIBUTING

- disputer/disputer.js
- financial-templates-lib/clients/ExpiringMultiPartyClient.js
- financial-templates-lib/price-feed/CryptoWatchPriceFeed.js
- financial-templates-lib/price-feed/UniswapPriceFeed.js
- liquidator/liquidator.js
- monitors/BalanceMonitor.js
- monitors/CRMonitor.js
- monitors/ContractMonitor.js
- monitors/SyntheticPegMonitor.js
This PR refactors the bots usage of web3 utils to all re-use scope instances of the utilities created in the constructor.
close #1411
> Refactor bots usage of web3 utilities

- scripts/DeployNode.sh
This is meant to be a sample script -- it's not parametrizable and has a list of preconditions at the top of the file.
> Add sample node deployment script for GCE

- reporters/GlobalSummaryReporter.js
- reporters/SendSlackReport.sh
> Add # of unique sponsors in period to report; fix small bug send slack script

- disputer/disputer.js
- disputer/index.js
- financial-templates-lib/clients/ExpiringMultiPartyClient.js
- financial-templates-lib/clients/ExpiringMultiPartyEventClient.js
- financial-templates-lib/clients/TokenBalanceClient.js
- financial-templates-lib/helpers/GasEstimator.js
- financial-templates-lib/price-feed/CryptoWatchPriceFeed.js
- financial-templates-lib/price-feed/MedianizerPriceFeed.js
- financial-templates-lib/price-feed/Networker.js
- financial-templates-lib/price-feed/UniswapPriceFeed.js
- liquidator/index.js
- liquidator/liquidator.js
- monitors/BalanceMonitor.js
- monitors/CRMonitor.js
- monitors/ContractMonitor.js
- monitors/SyntheticPegMonitor.js
- monitors/index.js
This PR standardizes the commenting across all bots, modules, and clients in our ecosystem. 
close #1446
> Improve bot commenting

- STYLE.md
- reporters/GlobalSummaryReporter.js
- reporters/SponsorReporter.js
- reporters/index.js
> Daily Reporter: Change class-level functions from "arrow" to traditional syntax

- reporters/SponsorReporter.js
This PR refactors the risk reporter tables to join into one single table with columns for each sponsor.
Previous implementation:
New implementation:
> Improve daily reporter by joining sponsor tables by columns

- documentation/oracle/governance/UMIPs.md
This is just to keep this doc in line with https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-1.md.
> Update UMIP docs to match the UMIP repo

- common/globalTruffleConfig.js
> Add notice about secrets stored in public repo

- monitors/ContractMonitor.js
- monitors/test/ContractMonitor.js
- scripts/bot-deployment/DeployReporterCR.sh
This PR introduces two small changes to the monitor bot:
1) fixes the missing symbol in log messages.
2) makes a small reduction in the string sent in the message.
> Patch missing token symbol monitor bot

- documentation/synthetic_tokens/tutorials/creating_from_truffle.md
- documentation/synthetic_tokens/tutorials/liquidation.md
- documentation/synthetic_tokens/tutorials/prerequisites.md
- documentation/synthetic_tokens/tutorials/using_the_uma_sponsor_cli_tool.md
Targeting a task within #1595 
A first-pass audit of the synthetic tokens tutorials. Mostly just to make sure things work and are not too out-of-place. i.e. whatever small changes that can improve readability.
> [Tutorials Audit] Synthetic Tokens

- README.md
A very small change just to shrink and center the logo on the README.
> Center and shrink logo on README

- disputer/disputer.js
- disputer/index.js
- financial-templates-lib/clients/ExpiringMultiPartyClient.js
- financial-templates-lib/clients/ExpiringMultiPartyEventClient.js
- financial-templates-lib/clients/TokenBalanceClient.js
- financial-templates-lib/helpers/GasEstimator.js
- financial-templates-lib/helpers/delay.js
- financial-templates-lib/logger/Logger.js
- financial-templates-lib/logger/SlackTransport.js
- financial-templates-lib/logger/SpyTransport.js
- liquidator/index.js
- liquidator/liquidator.js
- monitors/BalanceMonitor.js
- monitors/ContractMonitor.js
- monitors/SyntheticPegMonitor.js
- monitors/index.js
> EMP Clients: use traditional function style for file/class-level functions

- README.md
The previous version was actually really janky. repeated sentences and longer than needed.
> Update README.md coverage description

- disputer/disputer.js
I missed this as part of #1637 
> Fix function style for Disputer

- financial-templates-lib/price-feed/CreatePriceFeed.js
This will allow COMPUSD tokens to work with the CLI tool.
> Add COMPUSD default reference price feed

- voter-dapp/src/ActiveRequests.js
Fixes #1661 
Simplifies a long tooltip.
> Simplify tooltip for voter dapp

- documentation/synthetic_tokens/tutorials/liquidation.md
Fixes #1645 
See issue above for more details.
> Update liquidator bot tutorial w/ feedback from user testing

- reporters/GlobalSummaryReporter.js
yCOMP-COMP uniswap pair data returns nothing currently, we need to handle this so the reporter doesn't crash.
These rows now display an error message:
```
allTokenStatsTable["# trades in Uniswap"] = {
cumulative: "Graph data unavailable"
};
allTokenStatsTable["volume of trades in Uniswap in # of tokens"] = {
cumulative: "Graph data unavailable"
};
```
> Daily Reporter: check if the Graph data for Uniswap pair is empty

- reporters/SponsorReporter.js
- reporters/index.js
This PR makes token symbols dynamic in the `SponsorReporter` module within the Daily reporter. It also refactors where these symbols appear: rather than being in line with each field they appear in the first column.
**Previous implementation:**
**New implementation:**
> Updated Daily reporter SponsorReporter to take in dynamic token symbol

- common/ContractUtils.js
- reporters/GlobalSummaryReporter.js
> Fix bugs so that daily reporter reports resolved prices

- reporters/SponsorReporter.js
Removes a console log that should not have been left over.
> Small cleanup in daily reporter

- core/scripts/cli/wallet/getTwoKeyContract.js
- core/scripts/cli/wallet/readDefaultAccountInfo.js
- documentation/oracle/tutorials/voting_with_uma_tokens.md
> CLI auto detects two key contract from voter's address instead of asking user to set env. variable

- common/globalTruffleConfig.js
This comes from feedback from CLI users. Some have asked for the ability to change the offset and number of keys that are generated from wallets.
Fixes #1700.
> Add env variables to control the number and offset for derived keys

- monitors/index.js
- monitors/test/index.js
Its impossible for `Poll.run` to throw any errors but this test checks that it doesn't throw errors. So we didn't catch this invalid construction of the monitor index.js script.
> Fix false positive Monitors/index.js test

- monitors/test/index.js
> Add endingBlock param to monitors/index.js test

- disputer/index.js
- liquidator/index.js
Resolves #1707 
Also fixes a bug that emerged when resolving merge conflicts from #1705 where `logger` (dependency injection) was reverted back to `Logger`.
> Use gas estimator to set gas price for approving bot allowances

- lerna.json
- package.json
- voter-dapp/package.json
> Add voter-dapp to lerna packages

- core/package.json
- lerna.json
- package.json
Resolves #1730 
Leaves out CLI related deps which we'll move into their own package in #1728
> Add core package to Lerna

- core/test/scripts/Voting.js
Intrinio calls are now failing because the intrinio subscription has been canceled. This PR removes the one test that relies on intrinio, which should fix ci (works on my machine :)).
> Remove intrinio test to fix ci

- core/scripts/umip-8/1_Propose.js
- core/scripts/umip-8/2_VoteSimulate.js
- core/scripts/umip-8/3_Verify.js
This adds a script to propose [UMIP-8](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-8.md).
> Add script for UMIP-8

- financial-templates-lib/clients/ExpiringMultiPartyClient.js
**Motivation**
#1787 
**Summary**
I set `this.latestBlock` to the latest block height at the beginning of the `update()` call. Every contract query in `update()` explicitly makes a `.call(undefined, this.latestBlock )` so that all contract calls in the same `update()` iteration query state at the same height. Because disputer and liquidator bots are fed the data from this module, they will be using not out-of-sync data to determine whether to liquidate/dispute positions.
**Details**
If this is accepted then we should set the same defaultBlock override in the disputer and monitor bots, because they both make successive read-only contract calls and make decisions based on their values.
**Issue(s)**
Fixes #1787
> EMP Client: Set default block at beginning of update()

- core/scripts/liquidity-mining/CalculateBalancerLPProviders.js
- core/scripts/liquidity-mining/FindBlockAtTimeStamp.js
This PR refines the LM scripts in three ways:
1) The script no longer takes in data time but rather takes in a discrete block number.
2) To accommodate specifying date-time, a separate script was added called `FindBlockAtTimeStamp.js` which returns the block number closest to a given timestamp. To run this script you can execute:
```
truffle exec ./scripts/liquidity-mining/FindBlockAtTimeStamp.js --dateTime="2020-05-05 00:00"
```
which will find the block as close to that timestamp as possible. The script assumes the date-time is UTC formatted.
3) While testing the script with our current yUSD pool the balancer subgraph does NOT have our pool listed via a direct query. However, it _is_ possible to query the pool for a provided `tokensList` parameter. An example query to find the …
> Refine lequidity mining script

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- voter-dapp/README.md
**Motivation**
Contribution guidelines should clearly describe our GH process for making changes.
**Summary**
CONTRIBUTING.md was updated along with a few other supporting files. Some of the old content was moved to the voter-dapp README.
**Issue(s)**
Fixes #1831.
> docs(contributing): updates contributing guidelines

- liquidator/liquidator.js
- yarn.lock
**Motivation**
Make sure all the transactions in the bot goes through
**Summary**
Added `ynatm` for all `.send` calls in `liquidator.js`
**Details**
Added `ynatm` for the `withdraw.send` calls in `liquidator.js`
> Feat(liquidation bot): Added more retries for liquidation bot

- ci/deploy_to_staging.sh
- scripts/deploy_dapp.sh
**Motivation**
#1880.
**Summary**
Updated the file paths in the staging deployment scripts.
**Issue(s)**
Fixes #1880.
> ci(staging): fix staging deployment

- packages/core/test/financial-templates/ExpiringMultiPartyCreator.js
**Motivation**
#1930 
**Summary**
Moved date from September 1 2020 to sometime in 2030.
**Issue(s)**
Fixes #1930
> fix(contract-tests): EMPcreator expiration timestamp must be in future

- packages/common/src/AdminUtils.js
- packages/core/package.json
- packages/core/scripts/local/SnapshotCurrentRound.js
- packages/core/scripts/local/getPrivateKeyFromMnemonic.js
- packages/voter-dapp/README.md
- packages/voter-dapp/package.json
- packages/voter-dapp/run_tests.sh
- packages/voter-dapp/src/ActiveRequests.js
- packages/voter-dapp/src/ResolvedRequests.js
**Motivation**
#1926 
#1925 
**Summary**
Script will run user through commit-reveal-claim cycle for normal and admin price requests, with and without a 2key contract. Script takes care of deploying contracts, submitting price requests, advancing round phases, and getting Metamask set up properly.
**Details**
Example log of script:
<details>
<summary>Expand</summary>
```sh
➜  voter-dapp git:(npai/fix-voter-dapp) ✗ ./run_tests.sh
####################################################################
####################################################################
####################################################################
####################################################################
- Have you started Ganache in a separate window at port 9545? Be sure to use the following …
```
> feat(voter-dapp): Display no-votes in Resolved Requests appropriately, add all-in-one testing script

- packages/cli/cli.js
- packages/cli/cli_entry.sh
- packages/common/package.json
- packages/disputer/index.js
- packages/disputer/package.json
- packages/liquidator/index.js
- packages/liquidator/package.json
- packages/monitors/index.js
- packages/monitors/package.json
- packages/reporters/index.js
- packages/reporters/package.json
**Motivation**
https://github.com/UMAprotocol/protocol/issues/1815
**Summary**
Just adds these scripts as the binaries for the bot packages.
**Issue(s)**
Fixes #1815.
> build(bots): adds bin directive for bots

- packages/common/src/FormattingUtils.js
- packages/disputer/index.js
- packages/disputer/test/Disputer.js
- packages/disputer/test/index.js
- packages/liquidator/index.js
- packages/liquidator/test/Liquidator.js
- packages/liquidator/test/index.js
**Motivation**
#1949
**Summary**
Log and exit early without throwing if EMP is expired
**Issue(s)**
Fixes #1949
> fix(liquidator, disputer): Exit early if EMP is expired

- packages/common/src/FormattingUtils.js
> fix(common) Imports 'assert' twice, breaks CI

- packages/voter-dapp/src/ResolvedRequests.js
**Motivation**
I stumbled upon this feature request while running the gas rebate script. I wanted to calculate gas rebates beginning at the renBTC collateral Admin vote, but I realized that the Voter dApp does not make it easy to determine which "Admin" vote corresponded to a specific Governor action. For example, how was I supposed to know (without @claytonroche 's emails) that Admin 10 corresponded to whitelisting renBTC as collateral?
#1964 
**Details**
Need to cross `ProposalExecuted(uint256 indexed id, uint256 transactionIndex)` Governor events against `NewProposal(uint256 indexed id, Transaction[] transactions)`.
**Summary**
Preview:
**Issue(s)**
Fixes #1964
> feat(voter-dapp): Add explain button to decode resolved Admin proposal transactions

- .circleci/config.yml
**Motivation**
deploy_to_staging job fails on every commit.
**Summary**
Added prerequisites that may be necessary for package installation. Note: this is required on some of the other jobs.
**Issue(s)**
N/A
> ci(deploy): fix broken build in deployment job

- packages/cli/src/voting/revealVotes.js
- packages/common/src/Crypto.js
- packages/core/scripts/local/AdvanceToCommitPhase.js
- packages/core/scripts/local/AdvanceToNextVotingPhase.js
- packages/voter-dapp/run_tests.sh
- packages/voter-dapp/src/ActiveRequests.js
- packages/voter-dapp/src/Dashboard.js
**Motivation**
#1876
**Summary**
- This adds a snapshot button which only shows when in reveal state and snapshot is 0. Will show reveal button if it detects the contract has a snapshot for the current reveal. 
- updates the run_tests script to not automatically snapshot for you, but wait until you do it in the UI.
- adds a new script which goes to fix an issue when running script on wrong part of dvm cycle
- small update to update cli to warn user if no snapshot has been taken before reveal
**Details**
after commit phase ends, reveal phase starts. if no snapshot then this is shown to user:
clicking the button has you sign a hashed message 
which once snapshot is taken shows you the reveal button
**Issue(s)**
Fixes #1876, #1969
> feat(voter-dapp): #1876 add first snapshot UI flow before reveal

- packages/voter-dapp/src/DesignatedVotingDeployment.js
**Motivation**
We received feedback from an DVM voter that deploying the 2key contract was very expensive. Currently, the voter dApp doesn't make it clear that deploying the 2key contract is an OPTION but is certainly not a requirement. In fact, for many voters who do not use a multiple layer custody hierarchy, it probably makes little sense to pay the cost of deploying a contract. We should warn users about this.
#1982 
**Details**
**Issue(s)**
Fixes #1982
> feat(voter-dapp) Warn users about tradeoffs of deploying 2key

- packages/cli/package.json
- packages/common/package.json
- packages/core/package.json
- packages/disputer/package.json
- packages/financial-templates-lib/package.json
- packages/liquidator/package.json
- packages/monitors/package.json
- packages/reporters/package.json
- packages/voter-dapp/package.json
**Motivation**
Publish job is failing because lerna/npm assume the packages are to be published in restricted mode.
**Summary**
Added a param to all the package json files to override this default behavior for scoped packages.
**Issue(s)**
N/A
> fix(packages): add access param to packages so scoped packages will correctly publish

- packages/core/scripts/creator-umip/1_Propose.js
- packages/core/scripts/creator-umip/3_Verify.js
- packages/core/scripts/umip-3/2_VoteSimulate.js
**Motivation**
Modify comments for upcoming UMIP14 to register new EMPCreator
**Summary**
I ran into errors running 1_Propose.js unless I explicitly set the `gas` transaction config, otherwise everything else is comment updates.
> fix(umip-test): Tweaks to EMPCreator Propose scripts Npai/update creator umip script

- packages/core/networks/42.json
- packages/voter-dapp/src/apollo/client.js
**Motivation**
Voting contract had a slight ABI change, the read only method `snapshotMessage changed to `snapshotMessageHash`.
Contract has been verified on Kovan and is stored in the canonical Finder address
Kovan subgraph was updated as well in this [PR](https://github.com/UMAprotocol/uma-subgraph/pull/5)
> improve(networks): update Kovan Voting address

- packages/core/config/identifiers.json
**Motivation**
These new identifiers were approved recently on Kovan, and should be auto approved in future deployments of the IdentifierrWhitelist
> improve(identifiers): Add new identifiers to automatically whitelist in future IdentifierWhitelist deployments

- packages/voter-dapp/src/ResolvedRequests.js
**Motivation**
#2020 
**Summary**
I'm not entirely sure why I didn't catch this previously, possibly because the resolved request at index 0 was not an admin-request.
**Issue(s)**
Fixes #2020
> fix(voter-dapp): display resolved admin request at index 0

- packages/core/contracts/financial-templates/perpetual-multiparty/PositionManager.sol
**Motivation**
issue #2016
**Summary**
The implementation of the `PositionManager.sol` for the perpetual token is very similar in implementation details to the `PricelessPositionManager.sol` from the EMP. As a result, this PR simply adds **an exact copy** of the original `PricelessPositionManager.sol` to make subsequent PRs easier to review.
**Issue(s)**
issue #2016
> feat(perpetual-position-manager) initial EMP PricelessPositionManager code copy

- packages/core/networks/1.json
**Motivation**
The upgrade was just run, so the voting address should be updated to match.
**Summary**
Change the Voting address in the 1.json file.
**Issue(s)**
N/A
> feat(core): upgrade voting contract deployment

- packages/voter-dapp/src/ActiveRequests.js
**Motivation**
#2034 
**Issue(s)**
Fixes #2034
> improve(voter-dapp) Only show snapshot button if there are pending requests

- packages/core/scripts/local/DeployEMP.js
**Motivation**
This script is currently not working when run in the test env due to a hardcoded address.
**Summary**
The script was generalized to allow callers to specify a collateral address when needed, but to otherwise use the deployed address (which should work in test envs).
**Issue(s)**
N/A
> fix(scripts): slightly generalize deploy emp script to work in more envs

- packages/voter-dapp/src/RetrieveRewards.js
**Motivation**
#2059 
**Details**
**Issue(s)**
Fixes #2059
> improve(voter-dapp): Display pending claimable rewards above Claim button

- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/disputer/CHANGELOG.md
- packages/disputer/package.json
- packages/financial-templates-lib/CHANGELOG.md
- packages/financial-templates-lib/package.json
- packages/liquidator/CHANGELOG.md
- packages/liquidator/package.json
- packages/monitors/CHANGELOG.md
- packages/monitors/package.json
- packages/reporters/CHANGELOG.md
- packages/reporters/package.json
- packages/voter-dapp/CHANGELOG.md
- packages/voter-dapp/package.json
**Motivation**
To release recent smart contract functional and address changes to match the chain.
**Summary**
This is just the result of running `yarn create-release`.
**Issue(s)**
N/A
> improve(release): create release

- packages/disputer/index.js
- packages/disputer/test/Disputer.js
- packages/disputer/test/index.js
- packages/liquidator/index.js
- packages/liquidator/test/Liquidator.js
- packages/liquidator/test/index.js
**Motivation**
#2067 
#2068 
**Summary**
Removed all expiration logic in disputer as you can dispute and withdraw rewards post-expiry + tests
Liquidator should attempt to withdraw rewards post-expiry + tests
**Issue(s)**
Fixes #2067 
Fixes #2068
> fix(bots) Fix liquidator and disputer expiry logic

- packages/liquidator/test/index.js
**Motivation**
Self-explanatory
> improve(tests) Remove console.log from liquidator test

- packages/core/contracts/financial-templates/perpetual-multiparty/Perpetual.sol
- packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLib.sol
- packages/core/test/financial-templates/perpetual-multiparty/Perpetual.js
**Motivation**
#2080 
**Summary**
Current contracts are `420` bytes under the EIP170 limit:
```sh
➜  core git:(npai/perp-lib) ✗ yarn truffle exec ./scripts/local/CalculateContractBytecode.js --network test --contract PerpetualLib
yarn run v1.22.5
$ /Users/nicholaspai/UMA/protocol/node_modules/.bin/truffle exec ./scripts/local/CalculateContractBytecode.js --network test --contract PerpetualLib
loading PerpetualLib.json
Contract is 24156 bytes in size.
This leaves a total of 420 bytes within the EIP170 limit.
```
**Details**
**Issue(s)**
Fixes #2080
> feat(perpetual) add Perpetual and PerpetualLib contracts

- packages/common/src/ObjectUtils.js
- packages/liquidator/index.js
- packages/liquidator/mocha-test/liquidationStrategy.js
- packages/liquidator/package.json
- packages/liquidator/src/liquidationStrategy.js
- packages/liquidator/src/liquidator.js
- packages/liquidator/test/Liquidator.js
- packages/liquidator/test/index.js
**Motivation**
#2032 
**Summary**
This adds in a liquidator strategy module with some mocha tests. This replaces the previous "tokensToLiquidate" calculation. Additional tests have been added to validate the strategy when running. "Whale defense strategy" is disabled by default, and on enable it will error out if certain values are not provided which are required. 
**Issue(s)**
Fixes #2032
> feat(liquidator): adds in whale withdraw defense strategy

- packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
- packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js
**Motivation**
#2024
#2047 
**Summary**
All liquidatable public methods should update funding rate. 
Funding rate multiplier should modify amount of token debt counted for token redemption values on dispute settlements.
**Issue(s)**
Close #2024
Close #2047
> feat(perp-liquidatable) Integrate funding rate applier

- packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js
- packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2103 
**Issue(s)**
Fixes #2103
> improve(unit-tests): position manager tests should check that fees accrue following a shutdown

- packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2105 
**Issue(s)**
Fixes ##2105
> improve(unit-tests): demonstrate precision loss on funding rate multiplier

- packages/financial-templates-lib/index.js
- packages/financial-templates-lib/src/price-feed/InvalidPriceFeedMock.js
- packages/monitors/src/SyntheticPegMonitor.js
- packages/monitors/test/SyntheticPegMonitor.js
**Motivation**
#2113 
**Summary**
Vol errors occur when historical price data is unavailable, add details about this.
Updated error log:
**Issue(s)**
Fixes #2113
> improve(synthetic-peg-monitor) Add more details to Volatility error logs

- packages/core/package.json
- packages/core/scripts/collateral-umip/1_Propose.js
- packages/core/scripts/collateral-umip/3_Verify.js
- packages/core/scripts/collateral-umip/utils.js
- yarn.lock
**Motivation**
Often we need to propose collateral currencies that do not have a standard number of decimals.
We also sometimes need to propose multiple collateral currencies in the same UMIP.
**Summary**
Updates the script to allow both of these use cases.
**Issue(s)**
N/A
> feat(scripts): update UMIP collateral script

- packages/affiliates/package.json
**Motivation**
Publish is failing on master due to a minor error in the affiliates package.json.
**Summary**
Added a section to the config to specify how to publish the package. Note: this PR also disables publishing of this package for the time being until we're ready to do an initial release. This was done using the `private` directive.
**Issue(s)**
N/A
> fix(affiliates): fix package.json

- packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js
**Motivation**
Typo.
**Summary**
Fixes a copy-paste error.
**Issue(s)**
N/A
> improve(financial-templates-lib): fix docs typo

- packages/core/index.js
- packages/core/mocha-test/index.js
- packages/core/package.json
- packages/core/test/scripts/index.js
- yarn.lock
**Motivation**
#2180.
**Summary**
This just adds an arg to all core index.js functions to take a version string.
**Issue(s)**
Fixes #2180.
> feat(core): add legacy versioning

- packages/affiliates/libs/affiliates.js
- packages/affiliates/libs/bigquery.js
- packages/affiliates/libs/datasets.js
- packages/affiliates/libs/models.js
- packages/affiliates/libs/processors.js
- packages/affiliates/scripts/example-balances.js
**Motivation**
#2173 
**Summary**
Previously when running script for some time frames, it would fail with incorrect or negative balances. This is because we need to generate balances from start of each emp deployment. 
This fix allows us to run deployer rewards for any time period that does not encompass the emp creation time. This brute forces the query from bigquery, it has to search through all time to get these logs and costs about 25 cents per contract.
- gets balances and emp deployer events for all time vs respecting user start time. We need balances to generate from all time, but user may specify a start time that does not meet this requirement.
- fixes bug when handling events that call settle expired. apparently users without positions can call this.
**Issue(s)**
Fixes #2173, …
> fix(affiliates): when getting balances use all time logs instead of logs from start time

- packages/common/package.json
- packages/core/package.json
- yarn.lock
**Motivation**
Bump web3 version to fix affiliates test.
**Summary**
Bump web3 version to fix affiliates test.
**Issue(s)**
N/A
> fix(affiliates): bump web3 version

- packages/affiliates/CHANGELOG.md
- packages/affiliates/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/disputer/CHANGELOG.md
- packages/disputer/package.json
- packages/financial-templates-lib/CHANGELOG.md
- packages/financial-templates-lib/package.json
- packages/liquidator/CHANGELOG.md
- packages/liquidator/package.json
- packages/monitors/CHANGELOG.md
- packages/monitors/package.json
- packages/reporters/CHANGELOG.md
- packages/reporters/package.json
- packages/voter-dapp/CHANGELOG.md
- packages/voter-dapp/package.json
**Motivation**
Before locking in the abis, we need to do a release to npm.
**Summary**
This includes a small change to include identifiers.json in the core package.
**Issue(s)**
N/A
> improve(release): release

- packages/affiliates/test/mocha/models.js
**Motivation**
This test is flaky and dependent upon an external mainnet node.
> improve(affiliates): comment out test that attempts to connect to mainnet node

- packages/core/package.json
**Motivation**
Make the 1.2.0 abis available to those who want to access previous versions.
**Summary**
It just requires us to add the alias to the package.json.
**Issue(s)**
N/A
> improve(core): add 1.2.0 release to previous core versions

- packages/liquidator/test/Liquidator.js
**Motivation**
#2249 
**Summary**
Potential other tasks:
- Improve documentation with examples
- Recommend default values for WDF-related params
- More unit tests demonstrating more edge cases
**Issue(s)**
Fixes #2249
> improve(liquidator): Self audit liquidator's WDF strategy implementation

- packages/core/scripts/local/DeployEMP.js
**Motivation**
Deployment script needs to use older abis to interact with mainnet contracts.
**Summary**
Moved the deployment script to using a custom abi version that the user can input.
**Issue(s)**
N/A
> fix(deploy-script): add version parameter to deployment script

- packages/core/contracts/financial-templates/common/FeePayer.sol
- packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
- packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
- packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
- packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js
- packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
**Motivation**
#2277 
**Details**
I removed several require messages to make up for increased bytecode, contract's have < 50 bytes remaining in this PR. The contract reverts in these require statements for reasons that are relatively obvious to the user, such as depositing 0 tokens, or withdrawing more than their collateral amount.
The Perpetual still has no way of removing non-collateral tokens sent to the contract FYI.
**Issue(s)**
Fixes #2277
> feat(fee-payer): Add gulp method to distribute excess collateral to all sponsors

- packages/core/scripts/umip-3/2_VoteSimulate.js
**Motivation**
#2301 
**Summary**
This fixes vote simulate script to vote on all active proposals rather than being hardcoded to work with just one. Most of logic copied from `core/scripts/umip-15/2_VoteSimulate.js`.   This was tested in production by forking mainnet at a time where we have several proposed votes.
Fixes #2301
> feat(core): update vote simulate script to run on N proposols rather than just 1

- packages/affiliates/README.md
- packages/affiliates/examples/README.md
- packages/affiliates/examples/dapp-mining/README.md
- packages/affiliates/examples/dapp-mining/ethers-tagging.js
- packages/affiliates/examples/dapp-mining/web3-tagging.js
**Motivation**
#2320 
**Summary**
Basic readme for context around dapp mining, and examples of how to tag transactions in web3 and ethers.
**Issue(s)**
Fixes #2320
> feat(affiliates): add readmes and examples for dapp mining tagging

- packages/core/contracts/oracle/implementation/OptimisticOracle.sol
**Motivation**
Continuation of https://github.com/UMAprotocol/protocol/pull/2345. In that PR, I accidentally didn't commit the note to the optimistic oracle file.
**Summary**
Added the same note to the optimistic oracle.
**Issue(s)**
N/A
> improve(dec-20-audit): [N02] Consider ERC777 tokens (continued)

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/scripts/local/DeployEMP.js
- yarn.lock
**Motivation**
We released a new patch.
**Summary**
This just updates the version numbers stored in the master branch to match that patch.
**Issue(s)**
N/A
> improve(core): bump version numbers to align with most recent patch release

- packages/monitors/README.md
- packages/reporters/README.md
- packages/serverless-orchestration/README.md
**Motivation**
We want to have slim READMEs for all of our packages that provide some basic information and direct the reader to the main docs site for more in-depth instructions to set up and run the bots.
**Summary**
Adds brief READMEs for three packages that don't currently have them.
**Issue(s)**
N/A
> docs(readmes): add readmes for monitors, reporters, and serverless-orchestration packages

- packages/affiliates/payouts/dappmining/2021-01-04-0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5.json
**Motivation**
#2405
**Summary**
First week of dapp mining payouts for the yd-eth-mar21 contract found at `0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5`.
Rewards are based off of dev mining rewards for this contract found in PR #2400. Based on rewards for this contract the total Dapp mining rewards will be ` Math.floor(19617.080282865066141511 * .3) = 5885`. By default untagged rewards will assumed to be coming from UMA address at `0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35`.
**Details**
To reproduce results.
Create a config file called `dappmining.json`
```
{
"startTime": 1609718400000,
"endTime": 1610323200000,
"totalRewards": 5885,
"defaultAddress": …
```
> improve(affiliates): dappmining - week1 rewards for yd-eth-mar21 contract

- packages/affiliates/payouts/dappmining/2021-01-04-0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8.json
**Motivation**
#2404
**Summary**
First week of dapp mining payouts for the yd-btc-mar21 contract found at `0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8`.
Rewards are based off of dev mining rewards for this contract found in PR #2400. Based on rewards for this contract the total Dapp mining rewards will be ` Math.floor(21601.35493843455405486 * .3) = 6480`. By default untagged rewards will assumed to be coming from UMA address at `0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35`.
**Details**
To reproduce results.
Create a config file called `dappmining.json`
```
{
"startTime": 1609718400000,
"endTime": 1610323200000,
"totalRewards": 6480,
"defaultAddress": …
```
> improve(affiliates): dappmining - week 1 payout for yd-btc-mar21 contract

- packages/affiliates/apps/DevMiningRewards.js
- packages/affiliates/libs/affiliates/devmining.js
- packages/affiliates/libs/synthPrices.js
**Motivation**
#2397
**Summary**
- add optional cryptowatch api key
- add optional price fallbacks in USD
- add fixed decimal (18) to pass in and config synth price grabber
**Issue(s)**
Fixes #2397
> fix(affiliates): update synthPrices with fixed decimals, allow default fallback prices

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: pemulis <john.d.shutt@gmail.com>
**Motivation**
It would be helpful to have a section on testing in the pull request template so that reviewers know how to test the changes.
**Summary**
Adds that section.
**Issue(s)**
N/A
> docs(pr-template): add testing section in pr template

- packages/voter-dapp/src/ResolvedRequests.js
**Motivation**
#2428
**Summary**
Changes a line to add empty dependencies `[]` to a useMemo call to prevent multiple re renders
**Issue(s)**
Fixes #2428
> fix(voter-dapp): fix memo call to prevent rerender loop

- packages/core/migrations/17_deploy_perpetual_creator.js
**Motivation**
Removes some code from the perpetual creator migration that isn't needed, after discussion with @mrice32.
**Summary**
* Removes code where collateral whitelist is added to the finder, since it should already be there.
* Removes code adding a TestnetERC20 to the whitelist, since it should already be added.
**Testing**
**Issue(s)**
https://github.com/UMAprotocol/protocol/issues/2441
> improve(migration): remove unnecessary code from perpetual creator migration

- packages/affiliates/payouts/dappmining/2021-01-11-0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5.json
**Motivation**
#2427 
**Summary**
To re run:
create a dappmining.json:
```
{
"startTime": 1610406000000,
"endTime": 1611010800000,
"totalRewards": 5560,
"defaultAddress": "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"
}
```
and run `node app/DappMiningRewards.js dappmining.json`
**Issue(s)**
Fixes #2427
> improve(affiliates): add dapp mining rewards for yd-eth week of 1/11-1/18

- packages/affiliates/payouts/dappmining/2021-01-11-0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8.json
…1 through 21/01/18
**Motivation**
#2437
**Summary**
To re run:
create a dappmining.json:
```
{
"config": {
"startTime": 1610406000000,
"endTime": 1611010800000,
"totalRewards": 6596,
"defaultAddress": "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"
}
```
and run `node app/DappMiningRewards.js dappmining.json`
**Issue(s)**
Fixes #2437
> improve(affiliates): add dapp mining rewards for yd-btc-mar21 for week 21/01/11 through 21/01/18

- .circleci/config.yml
- Dockerfile
- README.md
- ci/install_node_npm.sh
**Motivation**
Upgrades to the latest long-term support version of nodejs in our CircleCI and Docker configuration.
**Summary**
This would let us use new node features.
**Details**
We need to see if this passes continuous integration in the pull request process.
**Testing**
**Issue(s)**
Fixes #XXXX
> improve(node-lts): update circleci and docker config to use the latest lts version of nodejs

- packages/affiliates/payouts/dappmining/2021-01-18-0xE4256C47a3b27a969F25de8BEf44eCA5F2552bD5.json
**Motivation**
#2469
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2464: `17725.248459790237130069 * .3 = 5317`
```
{
"startTime": 1611010800000,
"endTime": 1611615600000,
"totalRewards": 5317,
"defaultAddress": "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"
}  
}
```
**Issue(s)**
Fixes #2469
> improve(affiliates): dapp mining for yd-eth week 21/01/25

- packages/affiliates/payouts/dappmining/2021-01-18-0x1c3f1A342c8D9591D9759220d114C685FD1cF6b8.json
**Motivation**
#2468
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2464: `20344.530263355492126194 * .3 = 6,103.35`
```
{
"startTime": 1611010800000,
"endTime": 1611615600000,
"totalRewards": 6103,
"defaultAddress": "0xa0dfF1F09a0DCEda7641b7eB07c3BDbe66a06C35"
}
```
**Issue(s)**
Fixes #2468
> improve(affiliates): dapp mining yd-btc rewards for 21/01/25

- packages/affiliates/apps/DevMiningRewards.js
- packages/affiliates/libs/affiliates/devmining.js
**Motivation**
#2462 
**Summary**
This is  a quick fix that needed to be added in order to run dev mining for this week due to the inclusion of dom finance.
- When querying synthetic price the dev mining processor will switch between different output types by detecting if its an 
array or not
- convert synthetic time from S to MS.
- do not check valid addresses for payout addresses so that we can support running script before partner address is given
**Testing**
**Issue(s)**
Fixes #2462
> fix(affiliates): switch between price feed output and also convert time to ms

- packages/core/config/identifiers.json
**Motivation**
Our desired price id DAI:PHP is not available yet, thus this PR to add the id in Kovan
**Summary**
Added `DAIPHP` to `packages/core/config/identifiers.json`
**Details**
Added `DAIPHP` to `packages/core/config/identifiers.json`
**Testing**
**Issue(s)**
https://github.com/UMAprotocol/protocol/issues/2474
> feat(core): adds DAIPHP price id

- packages/affiliates/payouts/dappmining/2021-01-25_2021-02-01_YD-BTC-MAR21_0003.json
**Motivation**
#2494
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2491: `Math.floor(18134 * .3) = 5440`
```
{
"weekNumber": 3,
"totalRewards": 5440,
"startTime": 1611615600000,
"endTime": 1612220400000
}
```
**Issue(s)**
Fixes #2494
> improve(affiliates): add Dapp Mining rewards for YD-BTC-MAR21 between 2021/01/25 and 2021/02/01

- packages/affiliates/payouts/dappmining/2021-01-25_2021-02-01_YD-ETH-MAR21_0003.json
**Motivation**
#2495
**Details**
Dapp mining for yd-eth-march using .3 of dev mining rewards for this period  #2491: `14161 * .3 = 4248`
```
{
"weekNumber": 3,
"totalRewards": 4248,
"startTime": 1611615600000,
"endTime": 1612220400000
}
```
**Issue(s)**
Fixes #2495
> improve(affiliates): Add Dapp Mining rewards for YD-ETH-MAR21 between 2021/01/25 and 2021/02/01

- packages/financial-templates-lib/src/helpers/GasEstimator.js
**Motivation**
When testing locally I noticed that this causes web3 function calls to break in some tests. This might have caused the bots to error out in the past.
> fix(gas-estimator): Prevent float gas prices

- CONTRIBUTING.md
- MAINTAINING.md
**Motivation**
To keep the repos organized, we need to add an on-duty maintainer structure.
**Summary**
Added `MAINTAINING.md`.
**Testing**
**Issue(s)**
N/A
> docs: add MAINTAINING.md

- packages/affiliates/payouts/dappmining/2021-02-01_2021-02-08_YD-ETH-MAR21_0004.json
**Motivation**
#2523
**Details**
Dapp mining for yd-eth-march using .3 of dev mining rewards for this period  #2518: `Math.floor(14740.068840825999212874 * .3)`
```
{
"weekNumber": 4,
"totalRewards": 4422,
"whitelist": [
"0x9a9dcd6b52B45a78CD13b395723c245dAbFbAb71",
],
"startTime": 1612220400000,
"endTime": 1612825200000
}
```
**Issue(s)**
Fixes #2523
> improve(affiliates): dapp mining rewards yd-eth-mar21 2021-02-08

- packages/affiliates/payouts/dappmining/2021-02-01_2021-02-08_YD-BTC-MAR21_0004.json
**Motivation**
#2522
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2518: `Math.floor(15316.758523086977303426 * .3)`
```
{
"weekNumber": 4,
"totalRewards": 4595,
"whitelist": [
"0x9a9dcd6b52B45a78CD13b395723c245dAbFbAb71",
],
"startTime": 1612220400000,
"endTime": 1612825200000
}
```
**Issue(s)**
Fixes #2522
> improve(affiliates): dapp mining rewards yd-btc-mar21 2021-02-08

- packages/core/scripts/DecodeTransactionData.js
- yarn.lock
**Motivation**
Example output for proposal with 2 transactions:
Old:
```
Your decoded transaction information:
{
"name": "propose",
"params": {
"transactions": [
{
"to": "0x54f44eA3D2e7aA0ac089c4d8F7C93C27844057BF",
"value": "0",
"data": "0x7e7e591d0000000000000000000000003832d2f059e55934220881f831be501d180671a7000000000000000000000000000000000000000000000000000001001d1bf800"
},
{
"to": "0xdBF90434dF0B98219f87d112F37d74B1D90758c7",
"value": "0",
"data": "0xe43252d70000000000000000000000003832d2f059e55934220881f831be501d180671a7"
}
]
}
}
```
New:
```
Your decoded transaction information:
Transaction is a proposal containing 2 transactions:
{
"name": "setFinalFee",
"params": {
"currency": "0x3832d2F059E55934220881F831bE501D180671A7", …
```
> improve(decode-transaction-data): Recursively print txn data

- packages/affiliates/apps/GetSheetsDevminingStatus.js
- packages/affiliates/package.json
- yarn.lock
**Motivation**
#2515 
**Summary**
Very basic script that reads from google sheets and spits out important data for dev mining. Requires some env vars, documented in code in order to run correctly.
**Details**
This is a low risk script, tested in production against our current google sheet and manually checked between @Tommy1231232 @smb2796 and I for errors. 
**Testing**
**Issue(s)**
Fixes #2515
> feat(affiliates): add script to read from google sheet dev mining status

- packages/core/networks/42.json
**Motivation**
Updates Kovan addresses so we can do a pre-release, which will be accessible to the updated launch-emp and new launch-perp repos.
**Summary**
Updates `42.json` to include the new Kovan addresses.
**Details**
N/A
**Testing**
**Issue(s)**
N/A
> feat(kovan): update kovan addresses

- packages/liquidator/index.js
**Motivation**
Follow up to #2530 which removes this param.
> improve(liquidator): Remove references to whaleDefenseFundWei

- packages/voter-dapp/run_tests.sh
- packages/voter-dapp/src/ActiveRequests.js
**Motivation**
- Update path to `getPrivateKeyFromMnemonic`
- Change identifiers to vote on to non-18 decimal identifiers to test that voter dapp is using correct precision
- Update voter dapp backup feature to include raw price which allows user to see the raw price that they committed
**Testing**
> improve(voter-dapp): update test script

- packages/affiliates/payouts/dappmining/2021-02-08_2021-02-15_YD-BTC-MAR21_0005.json
**Motivation**
#2553
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2541: `Math.floor(14733.426577007680355462 * .3) = 4420`
```
{
"totalRewards": 4420,
["MakeShift Finance", "0x45Ea614a7Ea47Ec393BDA310F901702DB1347df9"]
],
"weekNumber": 5,
"endDate": "02/15/2021 11:00 PM",
"startDate": "02/08/2021 11:00 PM",
"startTime": 1612825200000,
"endTime": 1613430000000,
"whitelist": [ …
```
> improve(affiliates): Dapp Mining rewards for YD-BTC-MAR21 2021/02/08 and 2021/02/15

- packages/affiliates/payouts/dappmining/2021-02-08_2021-02-15_YD-ETH-MAR21_0005.json
**Motivation**
#2552
**Details**
Dapp mining for yd-eth-march using .3 of dev mining rewards for this period  #2541: `Math.floor(17180.933058155691222569 * .3) = 5154`
```
{
"totalRewards": 5154,
["MakeShift Finance", "0x45Ea614a7Ea47Ec393BDA310F901702DB1347df9"]
],
"weekNumber": 5,
"endDate": "02/15/2021 11:00 PM",
"startDate": "02/08/2021 11:00 PM",
"startTime": 1612825200000,
"endTime": 1613430000000, …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-MAR21 2021/02/08 through 2021/02/15

- packages/common/package.json
**Motivation**
A missing dep from a removed package broke ci.
**Summary**
Added chalk-pipe to the common package, where it is used.
**Testing**
**Issue(s)**
N/A
> fix(common): add missing dependency to fix tests

- packages/core/scripts/DecodeTransactionData.js
**Motivation**
Decode script doesn't give the user _all_ of the nested transaction information. Specifically `to` and `value` are missing. Ex:
```
Your decoded transaction information:                                                                                                                                                                                                         
Transaction is a proposal containing 4 transactions:                                                                                                                                                                                          
{ …
```
> improve(core): add to and value to decode script output

- packages/liquidator/src/liquidator.js
**Motivation**
Removing code that never should have been committed from #2530 and that fails when a liquidation is detected and both START_BLOCK and END_BLOCK are set (such as on GCP)
**Testing**
> fix(liquidator): Remove unneccessary event query

- README.md
**Motivation**
Fixing two broken links in README.
**Testing**
**Issue(s)**
#2348
> fix(readme): Fix broken links

- packages/financial-templates-lib/src/clients/OptimisticOracleClient.js
- packages/financial-templates-lib/test/clients/OptimisticOracleClient.js
- packages/optimistic-oracle/index.js
- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/index.js
- packages/optimistic-oracle/test/proposer.js
**Motivation**
Fixes #2411 
**Summary**
Proposer bot can settle proposals and disputes it was involved in, as a proposer and disputer respectively.
Also improved `OptimisticOracleClient` to filter out proposals that have already been settled.
**Testing**
**Issue(s)**
Fixes #2411
> feat(optimistic-oracle-proposer): Can settle proposals and disputes

- packages/core/contracts/common/interfaces/Uniswap.sol
- packages/core/contracts/common/test/UniswapMock.sol
- packages/disputer/test/index.js
- packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
- packages/financial-templates-lib/src/price-feed/UniswapPriceFeed.js
- packages/financial-templates-lib/test/truffle/UniswapPriceFeed.js
- packages/liquidator/test/index.js
- packages/monitors/test/index.js
- packages/serverless-orchestration/test/ServerlessHub.js
- packages/serverless-orchestration/test/ServerlessSpoke.js
**Motivation**
Fixes #2557
**Summary**
`poolDecimals` is replaced by internal class variable `this.baseCurrencyDecimals` which is autodetected from `Uniswap` contract. `Uniswap.sol` was updated with `token0` and `token1` public methods.
Follow up, but less urgent PR, makes same change to `BalancerPriceFeed`. No identifiers use this pricefeed currently, thus less urgent.
**Testing**
**Issue(s)**
Fixes #2577
> refactor(uniswap-pricefeed): Remove poolDecimals param

- packages/optimistic-oracle/src/proposer.js
**Motivation**
Tiny PR adding a DEBUG log to enhance testing for when the bot is purposefully skipping disputes.
> feat(optimistic-oracle-proposer): Add DEBUG log about skipping dispute

- packages/core/networks/42.json
**Motivation**
Updates the Kovan address for the Optimistic Oracle, since we redeployed it with some extra event details and a shorter liveness window. Need this merged so we can make another @next release for people using our packages to test their products on Kovan.
**Summary**
See above.
**Details**
**Testing**
**Issue(s)**
n/a
> fix(oo): update optimistic oracle address for kovan

- packages/core/migrations/11_deploy_optimistic_oracle.js
- packages/core/scripts/local/CreateTokens.js
- packages/core/scripts/local/DeployEMP.js
- packages/core/scripts/local/ProposePriceEMP.js
- packages/core/scripts/local/SettleTokens.js
- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/proposer.js
**Motivation**
Proposal bot changes:
- Proposer bot now emits an ERROR level log when a price request is detected.
- `transactionConfig` is removed from logs because it does not explicitly set the `gas` param, which causes the SlackTransporter to error out when it attempts to compute `.length` on `{ ...txnConfig, gas: undefined }`. Its a bit esoteric but I see no real drawback to removing this config from the logs. The other option is to explicitly set `gas` to the result of an `estimateGas` call
Script changes:
- (DeployEMP.js) Builds off of #2531 and replaces the "DeployEMP.js` diff from #2531
- (DeployEMP.js): New EMP's have slightly different constructor arguments that this script needs to handle.
- (SettleTokens.js): New script to easily …
> improve(proposer): Send alert when price request detected, improve scripts to enhance OO bot testing

- packages/affiliates/payouts/dappmining/2021-02-15_2021-02-22_YD-ETH-MAR21_0006.json
**Motivation**
#2591
**Details**
Dapp mining for yd-eth-march using .3 of dev mining rewards for this period  #2584: `Math.floor(17809.92065430851969227 * .3) = 5342`
```
{
["MakeShift Finance", "0x45Ea614a7Ea47Ec393BDA310F901702DB1347df9"]
],
"empRewards": "17809.92065430851969227",
"weekNumber": 6,
"endDate": "02/22/2021 11:00 PM",
"startDate": "02/15/2021 11:00 PM",
"startTime": 1613430000000, …
```
> improve(affiliates): dapp mining yd-eth week 7

- packages/affiliates/payouts/dappmining/2021-02-15_2021-02-22_YD-BTC-MAR21_0006.json
**Motivation**
#2592
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period  #2584: `Math.floor(13575.393688179154686177* .3) = 4072`
```
{
["MakeShift Finance", "0x45Ea614a7Ea47Ec393BDA310F901702DB1347df9"]
],
"empRewards": "13575.393688179154686177",
"weekNumber": 6,
"endDate": "02/22/2021 11:00 PM",
"startDate": "02/15/2021 11:00 PM",
"startTime": 1613430000000,
"endTime": 1614034800000,
"totalRewards": 4072, …
```
> improve(affiliates): dapp mining yd-btc week 7

- packages/core/scripts/mainnet/GetAllSponsors.js
**Motivation**
Example script useful for getting any sponsors that have ever created a position on an EMP.
> feat(get-all-sponsors): Helper script to query all historical sponsors across all EMP's

- packages/common/src/FindContractVersion.js
**Motivation**
ci is broken due to a change in contract hash.
**Summary**
Updated the hashes.
**Testing**
**Issue(s)**
N/A
> ci(contract-versions): replaced contract version hashes for local testing

- packages/voter-dapp/src/apollo/client.js
**Motivation**
New subgraph URL has been updated to handle new Voting contract. As an example, see Admin Request 57 "vote stats" which are now visible (but not visible on the production code vote.umaproject.org)
**Testing**
> patch(voter-dapp): Update subgraph URL

- packages/core/networks/42.json
> improve(networks): Update Voting contract to one with faster phase time

- packages/common/package.json
**Motivation**
The current release is broken by a file that's missing in the common package.json.
**Summary**
Add the file to the package.json.
**Testing**
**Issue(s)**
N/A
> fix(common): missing required file in common

- packages/affiliates/CHANGELOG.md
- packages/affiliates/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/disputer/CHANGELOG.md
- packages/disputer/package.json
- packages/financial-templates-lib/CHANGELOG.md
- packages/financial-templates-lib/package.json
- packages/liquidator/CHANGELOG.md
- packages/liquidator/package.json
- packages/monitors/CHANGELOG.md
- packages/monitors/package.json
- packages/optimistic-oracle/CHANGELOG.md
- packages/optimistic-oracle/package.json
- packages/serverless-orchestration/CHANGELOG.md
- packages/serverless-orchestration/package.json
- packages/trader/CHANGELOG.md
- packages/trader/package.json
- packages/voter-dapp/CHANGELOG.md
- packages/voter-dapp/package.json
**Motivation**
Release a small patch to fix the common package.
**Summary**
Patch version bump across all packages to require the newest common version.
**Testing**
**Issue(s)**
N/A
> improve(release): patch release to fix common

- packages/financial-templates-lib/index.js
- packages/financial-templates-lib/src/clients/FinancialContractEventClient.js
- packages/financial-templates-lib/src/clients/OptimisticOracleEventClient.js
- packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
- packages/monitors/index.js
- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
- packages/monitors/test/index.js
- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/proposer.js
- packages/serverless-orchestration/test/ServerlessSpoke.js
**Motivation**
- Monitor: New `OptimisticOracleMonitor` created to track contract events
- Bot runner: `monitors/index.js` was changed to allow a `type` where the user can specify either `optimistic-oracle` or `financial-contract`. This allows the OptimisticOracle contracts to be monitored without having to construct all of the FinancialContract specific overhead.
**Testing**
> feat(optimistic-oracle-monitor): Support OptimisticOracle event monitoring

- packages/core/scripts/local/EncodeParams.js
**Motivation**
This is a lightweight script for generating encoded parameters for an EMP. It's useful if the EMP was deployed through `launch-emp` or some other method, and could be modified to encode parameters for Perpetuals in the future. We need properly encoded parameters to verify the EMP contract on Etherscan.
**Summary**
Using `DeployEMP` as a starting point, stripped the script down to just what was needed to encode the parameters.
**Details**
**Testing**
**Issue(s)**
n/a
> feat(encoding): add EncodeParams example script

- packages/affiliates/payouts/dappmining/2021-02-22_2021-03-01_YD-ETH-MAR21_0007.json
**Motivation**
#2630
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period: `Math.floor(17864.90858633614703861 * .3) = 5359`
```
{
],
"empRewards": "17864.90858633614703861",
"weekNumber": 7,
"endDate": "03/01/2021 11:00 PM",
"startDate": "02/22/2021 11:00 PM",
"startTime": 1614034800000, …
```
> improve(affiliates): dapp mining rewards for YD-ETH-MAR21 week 7

- packages/affiliates/payouts/dappmining/2021-02-22_2021-03-01_YD-BTC-MAR21_0007.json
**Motivation**
#2631
**Details**
Dapp mining for yd-btc-march using .3 of dev mining rewards for this period: `Math.floor(15140.674317681903863862 * .3) = 4542`
```
{
],
"empRewards": "15140.674317681903863862",
"weekNumber": 7,
"endDate": "03/01/2021 11:00 PM",
"startDate": "02/22/2021 11:00 PM",
"startTime": 1614034800000, …
```
> improve(affiliates): dapp mining rewards for YD-BTC-MAR21 week 7

- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
Signed-off-by: FreshmanQ <xunand@quarkchain.org>
**Motivation**
Part of #2479 
**Summary**
Add EURUSD price identifier default configuration 
**Testing**
- [✅ ]  Existing tests adequate, no new tests required
> improve(pricefeed): Add default config for EURUSD to TraderMade

- packages/common/package.json
- packages/core/scripts/local/RequestOraclePrice.js
- packages/voter-dapp/package.json
- packages/voter-dapp/run_tests.sh
- packages/voter-dapp/src/ActiveRequests.js
- packages/voter-dapp/src/Dashboard.js
- packages/voter-dapp/src/DesignatedVotingDeployment.js
- packages/voter-dapp/src/ResolvedRequests.js
- packages/voter-dapp/src/RetrieveRewards.js
- packages/voter-dapp/src/containers/VoteData.js
- packages/voter-dapp/src/drizzleOptions.js
- packages/voter-dapp/truffle-config.js
- yarn.lock
**Motivation**
#2371
**Summary**
Adds support for latest contract abi with ancillary data and fixes some bugs.
**Details**
- updates package file to latest abis
- uses ancillary data in calls when needed. also sets it to 0x since there is no ability to specify in this pr
- fixes infinite loop in requesting resolved requests
- tested with run_test script for 2key and non 2key scenarios
- "fixes" bug when decoding encrypted data which i ran into again, see #1969. this was resolved by updating the library version of `eth-crypto`
**Issue(s)**
Fixes #2371
Fixes #1969
> improve(voter-app): update app to work with newest voting version 1.2.2

- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
As requested by @smb2796 , here are the BTC and ETH 3m/6m configs.
> Adding configs for btc and eth 3m/6m basis

- packages/core/networks/42.json
**Motivation**
Updates the `PerpetualCreator` and `PerpetualLib` addresses. It was easier to redeploy the creator contract than to propose changes to the `ConfigStore` settings for all of the perpetuals that were deployed from the old factory.
Cf https://github.com/UMAprotocol/launch-perpetual/pull/2
**Summary**
Deployed and tested new a new `PerpetualCreator` contract to Kovan.
**Details**
Tested that new `Perpetual` contracts created through this factory are verifying automatically on Etherscan.
Also, in case you're curious, I had to manually copy the deployed bytecode from Etherscan into the Truffle artifact so that it would exactly match what was deployed previously. That allowed Etherscan to autoverify the newly deployed creator and …
> fix(kovan): update perp creator kovan address

- packages/funding-rate-proposer/index.js
- packages/optimistic-oracle/index.js
- packages/serverless-orchestration/src/ServerlessSpoke.js
**Motivation**
`web3.eth.net.getId()` does not return correctly for `_gkcms` provider unless its the second Promise returned in the Promise.all()'s in the bot runners.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> patch(bot-runners): Change default configs and patch gckms provider issue

- packages/core/package.json
**Motivation**
We need to add the new versions of core to core itself so they can be accessed via version strings.
**Summary**
Just add the new version aliases to the core package deps.
**Testing**
**Issue(s)**
N/A
> improve(core): add new versions to package.json

- packages/funding-rate-proposer/index.js
- packages/optimistic-oracle/index.js
**Motivation**
GCP logger not capturing all logs:
But Hub correctly logs all output:
**Summary**
Adds a `delay(2)` to mirror how other bots handle this issue
**Testing**
> patch(bot-runner): Add delay(2) to make sure logs are captured by spoke

- packages/financial-templates-lib/src/clients/FinancialContractEventClient.js
- packages/financial-templates-lib/test/clients/FinancialContractEventClient.js
- packages/monitors/index.js
- packages/monitors/src/ContractMonitor.js
- packages/monitors/test/ContractMonitor.js
**Motivation**
#2638
**Summary**
Monitors `FundingRateUpdated` events for Perpetual contracts. Does not affect existing EMP monitors. Tested on existing Kovan perpetual contract with some FundingRateUpdated event history.
**Testing**
**Issue(s)**
Fixes #2638
> feat(monitors): Add FundingRateUpdate event messages to monitor

- packages/affiliates/apps/DevMiningRewards.js
- packages/affiliates/apps/GetSheetsDevminingStatus.js
- packages/affiliates/libs/affiliates/devmining.js
- packages/affiliates/libs/affiliates/utils.js
- packages/affiliates/libs/processors.js
- packages/affiliates/libs/synthPrices.js
- packages/affiliates/test/mocha/devmining.js
**Motivation**
#2661
**Summary**
Allows a way to specify EMP version for the abi when decoding events.  This adds additional config param when specifying emp address and payout address. 
**Details**
Several other important changes were grouped into this PR for convenience:
- bug fix: cryptowatch key was not being set correctly causing rate limits
- feat: optional tradermade key configuration added
- feat: added ability to fetch fallback price from spreadsheet
- feat: logged out the json object which caused errors when serializing data in unix pipe. this helps with diagnosing reason why stringify fails. 
- improve: commented out error logging when parsing rows in spreadsheet to reduce confusing logs. errored rows are still ignored.
- …
> fix(affiliates): explicitly set version of emp abi

- packages/affiliates/apps/GenerateDevMiningPr.js
- packages/affiliates/libs/affiliates/utils.js
**Motivation**
#2657
**Summary**
Updates the dev mining pr string, and documents how to use the app to generate pr message.
**Testing**
**Issue(s)**
Fixes #2657
> feat(affiliates): add pr template generation and app

- packages/affiliates/libs/synthPrices.js
**Motivation**
#2683 
**Summary**
Just adjust winston logger to send errors to std.err
**Testing**
**Issue(s)**
Fixes #2683
> fix(affiliates): winston logger configured to log only to stderr

- packages/affiliates/CHANGELOG.md
- packages/affiliates/package.json
- packages/common/CHANGELOG.md
- packages/common/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/disputer/CHANGELOG.md
- packages/disputer/package.json
- packages/financial-templates-lib/CHANGELOG.md
- packages/financial-templates-lib/package.json
- packages/funding-rate-proposer/CHANGELOG.md
- packages/funding-rate-proposer/package.json
- packages/liquidator/CHANGELOG.md
- packages/liquidator/package.json
- packages/merkle-distributor/CHANGELOG.md
- packages/merkle-distributor/package.json
- packages/monitors/CHANGELOG.md
- packages/monitors/package.json
- packages/optimistic-oracle/CHANGELOG.md
- packages/optimistic-oracle/package.json
- packages/serverless-orchestration/CHANGELOG.md
- packages/serverless-orchestration/package.json
- packages/trader/CHANGELOG.md
- packages/trader/package.json
- packages/voter-dapp/CHANGELOG.md
- packages/voter-dapp/package.json
**Motivation**
Release new merkle distributor bytecode and related packages.
**Summary**
Ran the release script.
**Testing**
**Issue(s)**
N/A
> improve: release

- packages/financial-templates-lib/src/price-feed/Networker.js
**Motivation**
For price feed that wants to use subgraphs as data source requires support for POST requests in `Networker.getJson()`.
Usually to fetch data from subgraphs we need to send a POST request with GraphQL query as a payload.
While working on[ RAI x UMA challenge ](https://gitcoin.co/issue/reflexer-labs/geb/97/100024834) I needed to write price feed using subgraphs.
It would be great if `Networker` can have support for this. Using `Networker` makes testing much easier.
**Summary**
- It doesn't require any big change, just allowing [`option`](https://www.npmjs.com/package/node-fetch#fetchurl-options) param to `fetch` call is required.
```diff
-  async getJson(url) {
-    const response = await fetch(url);
+  async getJson(url, options) {
+    const response = await fetch(url, …
```
> feat(Networker): enable support for POST requests in getJson()

- packages/core/contracts/oracle/implementation/test/OptimisticRequesterTest.sol
- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/monitors/test/OptimisticOracleContractMonitor.js
- packages/optimistic-oracle/src/proposer.js
**Motivation**
+ bonus feature adding emojis to OO proposer bot's error logs.
**Testing**
> improve(optimistic-oracle-monitor): Make wei logs more readable

- packages/monitors/index.js
**Motivation**
Looping monitor does not re-populate its array of promises that it should be fulfilling in parallel on every loop iteration.
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> patch(monitor): Repopulate monitor runner promises every loop

- packages/core/contracts/merkle-distributor/implementation/MerkleDistributor.sol
- packages/core/test/merkle-distributor/MerkleDistributor.js
- packages/merkle-distributor/scripts/2_PublishClaimsForWindow.ts
**Motivation**
Addressing several recommendations to improve the quality of the code base:
- The `lastCreatedIndex` variable name and comments suggest it indicates an existing window. In fact, it is the index that will be assigned to the next window. Consider updating the name and comments accordingly.
- The `WithdrawRewards` event does not specify the reward currency. Consider including it as well.
- The `setWindow` function performs the token transfer before emitting the event. If the reward token follows the ERC777 specification, it is possible that the caller has a `tokensToSend` hook that re-enters the `setWindow` function, which would cause the `CreatedWindow` events to be emitted in the wrong order. This may fall outside the threat model, since the function can only be called by …
> improve(merkle-distributor): Assorted fixes + natspec comments

- packages/affiliates/payouts/dappmining/2021-03-15_2021-03-22_YD-ETH-MAR21_0010.json
**Motivation**
#2758
**Details**
Based on dev mining rewards #2755
to re-run
create config.json file
```js
{
"config": {
],
"empRewards": "12344.494553734517073299",
"weekNumber": 10,
"endDate": "03/22/2021 11:00 PM",
"startDate": "03/15/2021 11:00 PM",
"startTime": 1615849200000,
"endTime": 1616454000000,
"totalRewards": 3703,
"whitelist": [ …
```
> improve(affiliates): dapp mining rewards yd-eth mar21 week 11

- packages/affiliates/payouts/dappmining/2021-03-15_2021-03-22_YD-BTC-MAR21_0010.json
**Motivation**
#2759
**Details**
Based on dev mining rewards #2755
to re-run
create config.json file
```js
"config": {
],
"empRewards": "7555.408988779409007158",
"weekNumber": 10,
"endDate": "03/22/2021 11:00 PM",
"startDate": "03/15/2021 11:00 PM",
"startTime": 1615849200000,
"endTime": 1616454000000,
"totalRewards": 2266,
"whitelist": [ …
```
> improve(affiliates): dapp mining rewards yd-btc mar21 week 11

- packages/common/src/FindContractVersion.js
**Summary**
Updates the perpetual hash in `FindContractVersion`
**Testing**
**Issue(s)**
NA
> fix(find-contract-version): Fix the perpetual bytecode hash

- packages/merkle-distributor/payout-windows/chain-id-1-reward-window-1-payout-information.json
- packages/merkle-distributor/scripts/2_PublishClaimsForWindow.ts
**Motivation**
As part of the KPI options initiative, we require merkle proofs to be added to IPFS, cloudflare and ultimately tokens sent to the merkle distribution [contract](https://etherscan.io/address/0xA5808A5B7324084c212F8B86e6795440f69AD419). This PR adds key information on the payouts, including the `merkleRoot` and `ipfsHash` for future reference. This information should be used by the UMA foundation to seed the merkle distribution contract.
**Recreating this output**
The output presented in this PR is the culmination of running separate scripts.
1. Combining the payouts outputs from the `token-distribution` repo.
First, the outputs from the official UMA [token-distribution](https://github.com/UMAprotocol/token-distribution) repo needs to be joined together. This can be done by …
> feat(merkle-distributor): Add KPI options payout information

- packages/funding-rate-proposer/src/proposer.js
Signed-off-by: Nick <nick@umaproject.org>
**Motivation**
[UMIP-62](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-62.md) says FR should be to 9 decimals of precision. This PR adds the feature to the FRP to specify decimals of precision. Default is 9.
**Testing**
> fix(funding-rate-proposer): Should propose funding rates to certain precision

- packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/src/price-feed/ForexDailyPriceFeed.js
- packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/test/price-feed/ForexDailyPriceFeed.js
**Motivation**
the [exchangeratesapi](https://exchangeratesapi.io/pricing/) pricing plans changed and we need to parameterize an `access_key` to get access to free daily data.
**Testing**
> fix(forexdaily-pricefeed): Add apiKey config

- packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/src/price-feed/ForexDailyPriceFeed.js
- packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
- packages/financial-templates-lib/test/price-feed/ForexDailyPriceFeed.js
**Motivation**
[It appears that api.exchangerates.io was acquired recently and put behind a paywall](https://github.com/exchangeratesapi/exchangeratesapi/issues/117) so this PR replaces the endpoint with a recommended stable drop-in replacement (using the same ECB daily forex data) [exchangerate.host](https://exchangerate.host/#/#faq).
> fix(forex-daily-pricefeed): Fix endpoint

- packages/common/src/FindContractVersion.js
- packages/core/contracts/financial-templates/common/financial-product-libraries/CoveredCallFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
**Motivation**
Addressing some typographical errors:
- Line 77 says "an collateral token" instead of "a collateral token"
- Line 86 says "cover call" instead of "covered call"
- Misleading comment in Line 454 of the Liquidatable contract that states the sponsor and disputer reward percentages cannot (cumulatively) exceed zero but the actual restriction is that they cannot exceed 1.
> improve(financial-contracts): Clean up comments

- packages/core/scripts/collateral-umip/1_Propose.js
- packages/core/scripts/identifier-umip/1_Propose.js
**Motivation**
Some small improvements to logs and comments in the proposal scripts.
**Summary**
Minor changes to logging, which required some more imported artifacts and methods in the identifier proposal script.
**Details**
n/a
**Testing**
**Issue(s)**
n/a
> improve(scripts): better logs and comments in collateral and identifier proposal scripts

- packages/affiliates/apps/GetSheetsDevminingStatus.js
**Motivation**
#2852 
**Summary**
include SHEET_TAB env
**Testing**
**Issue(s)**
Fixes #2852
> fix(affilates): properly use SHEET_TAB from env

- packages/core/scripts/identifier-umip/1_Propose.js
- packages/core/scripts/identifier-umip/3_Verify.js
**Motivation**
Noticed a few errors in the instructions for running scripts to propose new price identifiers.
**Summary**
Fixed them based on the instructions from the collateral scripts, which were more up-to-date. I ran the scripts for a recent round of mainnet proposals using the new instructions, and they worked.
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(scripts): correct instructions for running price identifier scripts

- package.json
**Motivation**
The main mono repo `package.json` has a poor description. This PR aims to fi this.
I'm open to other descriptions! feel free to comment on others :)
> fix(package.json): fix mono-repo package description

- packages/affiliates/payouts/dappmining/2021-04-12_2021-04-19_YD-ETH-JUN21_0014.json
**Motivation**
#2885
**Details**
Dapp mining for YD-ETH-JUN21 week 15 from 2021/04/12 to 2021/04/19 using 0.3 of dev mining rewards for this period: `Math.floor(11444.061681226090128918 * 0.3) = 3433`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "11444.061681226090128918",
"weekNumber": 14,
"endDate": "04/19/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 15

- packages/core/scripts/mainnet/WithdrawTokens.js
- packages/core/scripts/mainnet/WithdrawTokens.ts
**Motivation**
Plan to use this script to transfer all of the tokens from our current multi-collateral bot to be redeemed by sponsor wallets, as we're consolidating to a single-collateral bot system.
**Summary**
This is a stripped-down version of the `WithdrawTokensFromDSProxy` script in the `trader` package.
**Details**
n/a
**Testing**
**Issue(s)**
n/a
> feat(scripts): add WithdrawTokens for bot wallet consolidation

- packages/affiliates/payouts/dappmining/2021-04-19_2021-04-26_YD-ETH-JUN21_0015.json
**Motivation**
#2908
**Details**
Dapp mining for YD-ETH-JUN21 week 16 from 2021/04/19 to 2021/04/26 using 0.3 of dev mining rewards for this period: `Math.floor(17088.79568171916738494 * 0.3) = 5126`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "17088.79568171916738494",
"weekNumber": 15,
"endDate": "04/26/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 16

- packages/core/src/FindContractVersion.js
**Motivation**
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix: Add contract hash

- packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
- packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
**Motivation**
Param description in documentation refers to collateral when it should be synth tokens.
**Summary**
Fixed _minSponsorTokens description.
**Details**
Tiny change, although I'm not sure about the exact wording.
**Testing**
**Issue(s)**
N/A
> fix: fixes _minSponsorTokens description in contract docs

- packages/funding-rate-proposer/src/proposer.js
**Motivation**
Alternate solution to problem posed in #2920 
**Testing**
> fix(funding-rate-proposer): Move early exit after pricefeed update

- packages/optimistic-oracle/src/proposer.js
- packages/optimistic-oracle/test/proposer.js
**Motivation**
Parallel implementation #2826 for `optimistic-oracle-disputer`
**Testing**
> fix(optimistic-oracle-disputer): Ignore blacklisted identifiers

- packages/core/contracts/financial-templates/common/financial-product-libraries/PostExpirationIdentifierTransformationFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/common/financial-product-libraries/PreExpirationIdentifierTransformationFinancialProductLibrary.sol
**Motivation**
We have an audited `PreExpirationIdentifierTransformationFinancialProductLibrary` for transforming pre-expiry prices returned by an EMP. This makes some slight tweaks to create a `PostExpirationIdentifierTransformationFinancialProductLibrary` that does the same thing, but transforms the post-expiry price instead.
**Summary**
Copy-paste job with some modifications to change the post-expiry price rather than the pre-expiry price of the EMP.
This also removes the `onlyOwner` restriction from `setFinancialProductTransformedIdentifier` in `PreExpirationIdentifierTransformationFinancialProductLibrary`, to allow the library to be used by any contract deployer, not just the address that deployed the library.
**Details**
n/a …
> feat(lib): add post-expiration price transformation fpl

- ci/generate_lerna_config.sh
**Motivation**
Minor issue blocking the last job generated on tests pipeline. 
**Testing**
> fix (CircleCI): Adjust CI generated file

- packages/core/contracts/chainbridge/SinkGovernor.sol
- packages/core/contracts/chainbridge/SourceGovernor.sol
- packages/core/test/chainbridge/e2e.js
- packages/core/test/chainbridge/sinkGovernor.js
- packages/core/test/chainbridge/sourceGovernor.js
- yarn.lock
**Motivation**
Add a source and sink governor to relay governance transactions to L2s.
**Summary**
Added two contracts: GovernorSource and GovernorSink.
Note: still working on writing tests.
**Testing**
**Issue(s)**
N/A
> feat(core): add governor source and sink

- packages/cloud-functions/merkle-distributor-helper/package.json
- packages/cloud-functions/uma-tvl-calculator/package.json
- packages/cloud-functions/uma-tvl-fetcher/package.json
**Motivation**
Package names should all be prefixed with `@uma` for consistency (even private ones).
**Summary**
Updates a few package names that don't follow this pattern.
**Testing**
**Issue(s)**
N/A
> improve: make package names consistent

- packages/common/src/HardhatConfig.js
- packages/core/contracts/chainbridge/SourceGovernor.sol
- packages/core/deploy/001_deploy_finder.js
- packages/core/deploy/002_deploy_registry.js
- packages/core/deploy/004_deploy_generic_handler.js
- packages/core/deploy/005_deploy_sink_oracle.js
- packages/core/deploy/006_deploy_source_oracle.js
- packages/core/deploy/015_deploy_sink_governor.js
- packages/core/deploy/016_deploy_source_governor.js
**Motivation**
To do the L1 deployments for the l1-l2 bridge, we need a source governor script.
**Summary**
Added this deployment script, and updated a few minor tags/dependencies for clarity.
**Testing**
**Issue(s)**
N/A
> feat(core): add SourceGovernor to hardhat deployment

- packages/disputer/src/disputer.js
- packages/disputer/test/Disputer.js
**Motivation**
Historical price should have buffer before disputer should submit disputes in case historical price API is inaccurate for any reason.
**Testing**
> feat(disputer): Add dispute threshold to mirror liquidator's threshold

- packages/core/scripts/DecodeTransactionData.js
**Motivation**
We need a way to "unwrap" multicall transactions.
**Summary**
Adds multicall unwrapping functionality to the decode transaction data script.
**Testing**
**Issue(s)**
N/A
> improve(decode): add multicall unwrapping to the DecodeTransactionData script

- packages/core/contracts/common/implementation/ExpandedERC20.sol
- packages/core/contracts/common/interfaces/ExpandedIERC20.sol
- packages/core/contracts/financial-templates/common/financial-product-libraries/ContractForDifferenceFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/common/financial-product-libraries/LinearContractForDiffrenceFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/contract-for-difference/ContractForDifference.sol
- packages/core/contracts/financial-templates/test/ContractForDifferenceFinancialProjectLibraryTest.sol
- packages/core/test/financial-templates/contract-for-difference/ContractForDifference.js
**Motivation**
This PR adds initial CFD smart contract and unit tests. A number of basic libraries were also added.
> feat(cfd): initial CFD stub and tests

- packages/affiliates/payouts/dappmining/2021-05-17_2021-05-24_YD-ETH-JUN21_0019.json
**Motivation**
#3019
**Details**
Dapp mining for YD-ETH-JUN21 week 20 from 2021/05/17 to 2021/05/24 using 0.3 of dev mining rewards for this period: `Math.floor(14850.177306525402274494 * 0.3) = 4455`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "14850.177306525402274494",
"weekNumber": 19,
"endDate": "05/24/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 20

- packages/core/contracts/financial-templates/common/financial-product-libraries/ContractForDifferenceFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/common/financial-product-libraries/LinearContractForDiffrenceFinancialProductLibrary.sol
- packages/core/contracts/financial-templates/contract-for-difference/ContractForDifference.sol
- packages/core/contracts/financial-templates/test/ContractForDifferenceFinancialProjectLibraryTest.sol
**Motivation**
Build CFD contract.
**Summary**
Made some minor improvements to the CFD suite of contracts.
**Testing**
**Issue(s)**
N/A
> feat(cfd): minor improvements to CFD suite

- packages/common/src/FormattingUtils.js
**Motivation**
Found bug while running war games on Polygon
**Summary**
**Details**
**Testing**
**Issue(s)**
Fixes #XXXX
> fix(common): Fix import of PublicNetworks

- packages/common/src/FormattingUtils.js
- packages/common/src/TransactionUtils.js
- packages/financial-templates-lib/src/clients/OptimisticOracleEventClient.js
- packages/financial-templates-lib/src/helpers/allowances.js
- packages/financial-templates-lib/src/price-feed/DefaultPriceFeedConfigs.js
- packages/financial-templates-lib/test/clients/OptimisticOracleEventClient.js
- packages/funding-rate-proposer/src/proposer.js
- packages/liquidator/index.js
- packages/monitors/src/OptimisticOracleContractMonitor.js
- packages/optimistic-oracle/index.js
- packages/optimistic-oracle/src/proposer.js
**Motivation**
Bugs encountered while integration testing Polygon mainnet contracts. 
**Summary**
- Fixed `PublicNetworks` import in `FormattingUtils`
- Set `chainId` in transaction configs which seems to be required for the Polygon RPC I'm working with. This is a good feature to have for the future as [replay-protection](https://community.infura.io/t/polygon-rpc-only-replay-protected-eip-155-transactions-allowed-over-rpc/2997) becomes more popular, anyways.
- Refactor `OptimisticOracleEventClient` and `OptimisticOracleMonitor` to handle price requests that did not originate from a `financial-contract`. Currently we assume that the `requester` is a contract that has a `collateralCurrency` callable method, but this is not always going to be the case.
- Add flag to …
> improve(optimistic-oracle): Make bot compatible with OO on Polygon

- ci/generate_lerna_config.sh
**Motivation**
Minor typo
**Testing**
> fix (CircleCI): Adjust required tests dependencies  

- packages/core/test/financial-templates/expiring-multiparty/Liquidatable.js
- packages/disputer/index.js
- packages/disputer/src/proxyTransactionWrapper.js
- packages/disputer/test/index.js
- packages/funding-rate-proposer/test/index.js
- packages/liquidator/index.js
- packages/liquidator/src/liquidator.js
- packages/liquidator/test/index.js
- packages/monitors/test/index.js
- packages/optimistic-oracle/test/index.js
**Motivation**
There are a number of small commenting issues in the dispute as a result of a janky merge. This small PR addresses these.
> fix(disputer): address wrong comments

- packages/affiliates/payouts/dappmining/2021-05-24_2021-05-31_YD-ETH-JUN21_0020.json
**Motivation**
#3047
**Details**
Dapp mining for YD-ETH-JUN21 week 21 from 2021/05/24 to 2021/05/31 using 0.3 of dev mining rewards for this period: `Math.floor(11012.631702376070805964 * 0.3) = 3303`
```
{
"config": {
[
],
[
"OpenDAO",
],
[
],
[
"ChickFlock",
]
],
"empRewards": "11012.631702376070805964",
"weekNumber": 20,
"endDate": "05/31/2021 11:00 PM", …
```
> improve(affiliates): Dapp Mining rewards for YD-ETH-JUN21 week 21

- packages/serverless-orchestration/src/ServerlessHub.js
**Motivation**
Small PR to add an additional notification path to the serverless hub.
> feat(serverlessHub): Add notification path for fatal errors

- packages/sdk/src/libs/coingecko/README.md
- packages/sdk/src/libs/coingecko/coingecko.test.ts
- packages/sdk/src/libs/coingecko/coingecko.ts
- packages/sdk/src/libs/coingecko/index.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1220/add-coingecko-price-call
**Summary**
This is part of a [larger task to allow for querying collateral prices from api.](https://app.clubhouse.io/uma-project/story/930/create-api-to-get-current-prices-of-collateral-s)  Since collateral prices are typically easy to find, i will use coingecko to query prices rather that bot price feeds (which will be used later for synthetic prices).
Trying to break pr into smaller chunks to make easier to review. 
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1220/add-coingecko-price-call
> feat: copy over affilaites coingecko, add current price call

- packages/core/contracts/chainbridge/SinkOracle.sol
- packages/core/contracts/chainbridge/SourceOracle.sol
**Motivation**
- `formatMetadata` comments in `SinkOracle` + `SourceOracle` should state that data bytes goes from 32 - END instead of 64 - END
- Missing `@param` tag for `price` in `SinkOracle.executePublishPrice`.
> improve(chainbridge): Fix comments

- packages/sdk/src/libs/stores/google-datastore/store.ts
- packages/sdk/src/libs/stores/index.ts
- packages/sdk/src/libs/stores/js-map/store.ts
- packages/sdk/src/libs/stores/sorted-js-map/README.md
- packages/sdk/src/libs/stores/sorted-js-map/index.ts
- packages/sdk/src/libs/stores/sorted-js-map/store.test.ts
- packages/sdk/src/libs/stores/sorted-js-map/store.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1228/add-sorted-in-memory-key-value-store
**Summary**
This is a useful primitive to allow for sorted queries on an in memory store. Will use this to serve price data until google datastore integration. Allows for querying between timestamps, or "slicing" ( like array.slice) which is great for pagination.
**Details**
This code was pulled from some previously unpublished code and converted to typescript.  Added more thorough tests.  Behaves similarly to traditional sorted No sql databases where keys are sorted alphabetically when dealing with strings.
This adds additional functions to the store interface `slice` and `between`
**Testing** …
> feat(sdk): add in memory sorted kv store 

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/prices.ts
- packages/sdk/src/libs/coingecko/coingecko.test.ts
- packages/sdk/src/libs/coingecko/coingecko.ts
- packages/sdk/src/libs/tables/base/table.ts
- packages/sdk/src/libs/tables/blocks/utils.ts
- packages/sdk/src/libs/tables/emps/utils.ts
- packages/sdk/src/libs/tables/generic/js-map.ts
- packages/sdk/src/libs/tables/generic/sorted-js-map.ts
- packages/sdk/src/libs/tables/historical-prices/sorted-js-map.ts
- packages/sdk/src/libs/tables/historical-prices/utils.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/932/create-api-to-get-historical-prices-of-collaterals
**Summary**
This adds a historical prices table in the sdk, which uses  a sorted map under the hood. Api uses this to construct historical price tables for all collateral currencies and keeps it up to date every N blocks as specified by `UPDATE_BLOCKS`
**Details**
Readme is updated with api calls:
- `historicalPricesByAddress(address:string,start:number=0,end:number=Date.now(),currency:"usd"="usd") => PriceSample[]`
- `sliceHistoricalPricesByAddress(address:string,start:number=0,length:number=1,currency:"usd"="usd") => PriceSample[]`
You can also check the postman collection of calls: https://www.getpostman.com/collections/e99f4e09e2443cb31ef4
**Testing**
Check a box to …
> feat(api): add historical price queries for collateral addresses 

- packages/sdk/src/libs/clients/emp/client.ts
- packages/sdk/src/libs/clients/erc20/README.md
- packages/sdk/src/libs/clients/erc20/client.test.ts
- packages/sdk/src/libs/clients/erc20/client.ts
- packages/sdk/src/libs/clients/erc20/index.ts
- packages/sdk/src/libs/clients/index.ts
- packages/sdk/src/libs/clients/registry/client.ts
- packages/sdk/src/libs/tables/blocks/README.md
- packages/sdk/src/libs/tables/emps/README.md
- packages/sdk/src/libs/tables/erc20s/README.md
- packages/sdk/src/libs/tables/erc20s/index.ts
- packages/sdk/src/libs/tables/erc20s/js-map.test.ts
- packages/sdk/src/libs/tables/erc20s/js-map.ts
- packages/sdk/src/libs/tables/erc20s/utils.ts
- packages/sdk/src/libs/tables/generic/sorted-js-map.ts
- packages/sdk/src/libs/tables/index.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1296/add-erc20-client-and-table-to-sdk
**Summary**
Need to be able to get token decimals for TVL/TVM in API as well as token name.  Generalized this so that we can have a erc20 client with typed data and store the token information in a table.
**Details**
- adds sdk/clients/erc20
- adds sdk/tables/erc20
- some small refactors to emp/registry clients to make them more consistent
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1296/add-erc20-client-and-table-to-sdk
> feat(sdk): add erc20 client and table 

- ci/tests/test-not-required.sh
> Fix (CircleCI): Adjust file with no test required

- packages/core/networks/1.json
- packages/core/networks/137.json
**Motivation**
New OO with refactored ancillary data logic + tunnel infrastructure deployed to mainnets
**Summary**
**Details**
**Testing**
> feat: Updated mainnet OO deployments

- packages/api/src/apps/api/README.md
- packages/api/src/apps/api/app.ts
- packages/api/src/index.ts
- packages/api/src/libs/queries.ts
- packages/api/src/services/actions.ts
- packages/api/src/services/blocks.ts
- packages/api/src/services/emp-registry.ts
- packages/api/src/services/emp-state.ts
- packages/api/src/services/erc20-state.ts
- packages/api/src/services/index.ts
- packages/api/src/services/prices.ts
**Motivation**
https://app.clubhouse.io/uma-project/story/1291/need-erc20-token-data-in-api
**Summary**
Previous versions did not properly fetch token decimals or token names for the emp. This adds this ability, plus dedicated storage for related erc20 tokens.
**Details**
This adds a new pattern called `queries` which joins data between tables. This is a utility file which can be re-used between services, found in `src/libs/queries.ts`
new routes are added to query erc20 information for a single address or all known addresses
**Testing**
**Issue(s)**
https://app.clubhouse.io/uma-project/story/1291/need-erc20-token-data-in-api
> feat(api): add token names and decimals to returned emp state
